### ISSUE TITLE
最近出现一些歌曲提示格式不支持,下载也会显示文件错误

### ISSUE THREAD

**Issue by 459217974** [nondanee/UnblockNeteaseMusic#10]

**Comment by 459217974** [comment]
装了 ffmpeg 之后 转格式出错了应该

fs.js:1939
      throw new Error('"start" option must be <= "end" option');
      ^

Error: "start" option must be <= "end" option
    at new ReadStream (fs.js:1939:13)
    at Object.fs.createReadStream (fs.js:1893:10)
    at /root/servers/UnblockNeteaseMusic/proxy.js:82:25
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by nondanee** [comment]
请告知下是哪首歌？显示获取的音源来自哪个平台？
还有您是安卓端吗？安卓端不支持下载。

**Comment by 459217974** [comment]
还有一首歌匹配错了
[Replace] http://dl.stream.qqmusic.qq.com/M800004VLn4B2EJLFC.mp3?vkey=8C57B9210E5DBE1C152EB28C70EC66CF26AEE153A06966039CAF37D6EA7F51F78FA850AAFFF61066AD7A58F837289F4C67D53F1FC7F9CBDC&uin=0&fromtag=53&guid=733295
3645

专辑: 王威
歌名: 她

**Comment by 459217974** [comment]
我是用的安卓  我以为能下载的   但是下载程序就崩溃了有点伤啊   崩溃日志上面给了

歌曲无法识别那个我没看到有替换音源的日志  可能是没找到资源导致的吧

**Comment by nondanee** [comment]
### 崩溃的问题
看到了，不是ffmpeg转换出错，应该是下载中断文件被截断了，读取预下载文件为空，end比start小了。
你试试把项目根目录里的cache删掉看看

### ffmpeg
因为因为之前主要来源QQ源格式是m4a，需要转换，现在已改为mp3。现在应该仅剩酷我是aac格式，默认还未启用，所以ffmepg意义不太大

### 格式不支持
我自己也试了下，提示格式不支持应该就是没有匹配到音源。好像是我代码的问题，会尽快修复

### 匹配策略
现在没有匹配策略，只是简单的取搜索结果第一条，可能会匹配错。
匹配策略比较困难，因为不同平台命名规则不一样，专辑type，solo歌曲等，不能直接用名称一致来判断。

### 不支持安卓
我之前试了安卓端下载(v5.4.1)，预下载缓存完了，下载进度条走完，最后还是提示失败。
已经做了MD5校验，不知道还缺了什么字段校验。
安卓上旧的版本应该是支持的

**Comment by 459217974** [comment]
我遇到的问题更新之后基本都修复了  感谢
