### ISSUE TITLE
安卓shell脚本,只代理网易云音乐

### ISSUE THREAD

**Issue by Flysky12138** [nondanee/UnblockNeteaseMusic#100]
由于在安卓上，我用PAC方式代理不了网易云，所以自己写了个脚本。
流量、WiFi都能代理。
> 下载地址：https://github.com/Flysky12138/Proxy

**Comment by nondanee** [comment]
看过了

可以不用 redsocks 转换 tcp 流量，直接 nat forward 到 unblock 的两个端口上就行了
另外，你都 root，为什么不直接在安卓直接运行 node 呢？

**Comment by Flysky12138** [comment]
算了不会，手机上还是用xp框架的模块吧

**Comment by nondanee** [comment]
大概这样
```diff
- iptables -t nat -A OUTPUT -p tcp -m owner --uid-owner $re -m tcp --dport 80 -j REDIRECT --to-ports 8123
+ iptables -t nat -A OUTPUT -p tcp -m owner --uid-owner $re -m tcp --dport 80 -j DNAT --to-destination $Host:$Port
```

**Comment by Flysky12138** [comment]
嗯，改好了，还行

**Comment by NewBugger** [comment]
> 大概这样
> 
> ```diff
> - iptables -t nat -A OUTPUT -p tcp -m owner --uid-owner $re -m tcp --dport 80 -j REDIRECT --to-ports 8123
> + iptables -t nat -A OUTPUT -p tcp -m owner --uid-owner $re -m tcp --dport 80 -j DNAT --to-destination $Host:$Port
> ```

十分感谢，用上了，iptables 一劳永逸（不再需要调用权限）
