### ISSUE TITLE
padavan的entware环境下，运行报错

### ISSUE THREAD

**Issue by blueveryday** [nondanee/UnblockNeteaseMusic#108]
`[MI-3 /media/AiDisk_a1/UnblockNeteaseMusic]# node app.js -f 59.111.181.61 -p 9529
HTTP Server running @ http://0.0.0.0:9529
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::9529
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at Promise.all.then.result (/media/AiDisk_a1/UnblockNeteaseMusic/app.js:76:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
[MI-3 /media/AiDisk_a1/UnblockNeteaseMusic]#
`

不知道什么原因。
好像不支持IPV6，IPV4我没有公网地址。
我用netstat -an | grep LISTEN查看端口监听，发现ipv4没有端口打开，ipv6有9527端口打开。

**Comment by nondanee** [comment]
再换别的端口呢？一样报错吗？

**Comment by nondanee** [comment]
翻了下文档，应该是默认支持 IPv6 的
> If host is omitted, the server will accept connections on the unspecified IPv6 address (::) when IPv6 is available, or the unspecified IPv4 address (0.0.0.0) otherwise.
> Note: In most operating systems, listening to the unspecified IPv6 address (::) may cause the net.Server to also listen on the unspecified IPv4 address (0.0.0.0).

https://nodejs.org/dist/latest-v6.x/docs/api/net.html#net_server_listen_port_hostname_backlog_callback
https://nodejs.org/dist/latest-v8.x/docs/api/net.html#net_server_listen_port_host_backlog_callback
https://nodejs.org/dist/latest-v10.x/docs/api/net.html#net_server_listen_port_host_backlog_callback
https://nodejs.org/dist/latest-v12.x/docs/api/net.html#net_server_listen_port_host_backlog_callback

**Comment by blueveryday** [comment]
换了端口还是不行。

**Comment by nondanee** [comment]
那你试试
```
node -e 'http.createServer().listen(9529)'
```
看看会不会报错
再把 9529 换成别的端口号试试会不会报错

**Comment by blueveryday** [comment]
运行你给的命令，没有报错，但是界面像假死了一样，没有反应。

**Comment by nondanee** [comment]
没报错就行，是没有回显的
那说明端口可以用啊

**Comment by blueveryday** [comment]
但是查询端口监听，里面没有这个端口开启。

**Comment by nondanee** [comment]
会有端口监听啊
![image](https://user-images.githubusercontent.com/26399680/58853361-956e6080-86cc-11e9-90ba-85d0c638a683.png)

好的

**Comment by nondanee** [comment]
是已经 OK 了，可以用了吗？

**Comment by blueveryday** [comment]
> 是已经 OK 了，可以用了吗？已经解决了的话麻烦 close issue

不行，没有监听端口。
命令直行没有报错，但是没有端口监听。

**Comment by blueveryday** [comment]
![image](https://user-images.githubusercontent.com/29169337/58854285-6b6a6d80-86cf-11e9-9a01-cc9619c99c7d.png)

**Comment by nondanee** [comment]
README 里有说啊
> 支持 Windows 客户端，UWP 客户端，Linux 客户端 (1.2 版本以上需要自签证书 MITM，启动客户端需要增加 --ignore-certificate-errors 参数)，macOS 客户端 (726 版本以上需要自签证书)，iOS 客户端 (配置 https endpoint 或使用自签证书)，Android 客户端和网页版 (需要自签证书，需要脚本配合)

**网页版 (需要自签证书，需要脚本配合)**

**Comment by blueveryday** [comment]
> README 里有说啊
> 
> > 支持 Windows 客户端，UWP 客户端，Linux 客户端 (1.2 版本以上需要自签证书 MITM，启动客户端需要增加 --ignore-certificate-errors 参数)，macOS 客户端 (726 版本以上需要自签证书)，iOS 客户端 (配置 https endpoint 或使用自签证书)，Android 客户端和网页版 (需要自签证书，需要脚本配合)
> 
> **网页版 (需要自签证书，需要脚本配合)**

兄弟，客户端怎么弄参数进去？
自签证书不会弄。

**Comment by nondanee** [comment]
你是 linux 客户端？直接加参数 `netease-cloud-music --ignore-certificate-errors` 启动

仓库里有签好的 CA 证书，可以直接用；自签证书教程参考 #48 (这是 pinned 着的 issue，你应该提前去看的)

**Comment by blueveryday** [comment]
> 你是 linux 客户端？直接加参数 `netease-cloud-music --ignore-certificate-errors` 启动
> 
> 仓库里有签好的 CA 证书，可以直接用；自签证书教程参考 #48 (这是 pinned 着的 issue，你应该提前去看的)

win10系统，有时候网页，有时候pc客户端，我研究一下，谢谢。

**Comment by nondanee** [comment]
以后要仔细审题啊老哥

> 支持 
> Windows 客户端，
> UWP 客户端，
> Linux 客户端 (1.2 版本以上需要自签证书 MITM，启动客户端需要增加 --ignore-certificate-errors 参数)，
> macOS 客户端 (726 版本以上需要自签证书)，
> iOS 客户端 (配置 https endpoint 或使用自签证书)，
> Android 客户端
> 和
> 网页版 (需要自签证书，需要脚本配合)

**对 Windows 客户端没有任何要求** 
即，不用自签证书可以直接用 Windows  客户端

能提供的我都提供了，证书下载下来双击打开就能安装

有一个配合网页版的简易脚本，在这里可以找到 
https://github.com/nondanee/UnblockNeteaseMusic/releases/tag/v0.12.0

并且源码已包含 chrome extension 的附属版本
https://github.com/nondanee/UnblockNeteaseMusic/tree/master/browser

**Comment by blueveryday** [comment]
非常感谢，谢谢。
