### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by wo2429** [nondanee/UnblockNeteaseMusic#109]
如果是国外服务器，在代理的时候，访问一下谷歌什么的，会导致报错，1分钟内没网络。

**Comment by nondanee** [comment]
访问谷歌的话，你直接用来全局代理了？
报什么错呢？错误信息的麻烦贴一下

**Comment by wo2429** [comment]
> 访问谷歌的话，你直接用来全局代理了？
> 报什么错呢？错误信息的麻烦贴一下

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

确实是用的代理模式  ，全局的

**Comment by nondanee** [comment]
你加一个这个防止进程退出吧，我也不知道是哪个的 error 事件
```
process.on('uncaughtException', e => {
	console.log(e.stack)
	console.log('NOT exit...')
})
```

现在是敏感时间，应该是 GFW 的 RST
http proxy 的 connect SNI 信息还是明文的所以非常明显，建议不要直接代理爬墙

**Comment by wo2429** [comment]
> 你加一个这个防止进程退出吧，我也不知道是哪个的 error 事件
> 
> ```
> process.on('uncaughtException', e => {
> 	console.log(e.stack)
> 	console.log('NOT exit...')
> })
> ```
> 
> 现在是敏感时间，应该是 GFW 的 RST
> http proxy 的 connect SNI 信息还是明文的所以非常明显，建议不要直接代理爬墙

谢谢大锅

**Comment by wo2429** [comment]
比较小白，问一下，加那个文件里面

**Comment by nondanee** [comment]
加在 app.js 最下面好了

**Comment by wo2429** [comment]
> 加在 app.js 最下面好了

谢谢  麻烦了
