### ISSUE TITLE
国外的服务器突然不能运行命令了

### ISSUE THREAD

**Issue by Mathisdifficult** [nondanee/UnblockNeteaseMusic#110]
[root@instance-2 UnblockNeteaseMusic]# node app.js
{ Error: connect ETIMEDOUT 223.252.199.66:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '223.252.199.66',
  port: 80 }

**Comment by nondanee** [comment]
`ping 223.252.199.66` 这个是不是一直 timeout?

**Comment by nondanee** [comment]
感觉应该是 httpdns 那里超时了，你看看服务器上 music.httpdns.c.163.com 的 nslookup 是不是 223.252.199.66，这个域名能不能 ping 通

当然我可以把这个错误 catch 了，不过如果 httpdns 失败了可能会影响移动端使用

**Comment by Mathisdifficult** [comment]
[root@instance-2 ~]# nslookup music.httpdns.c.163.com 
Server:         169.254.169.254
Address:        169.254.169.254#53

Non-authoritative answer:
Name:   music.httpdns.c.163.com
Address: 59.111.160.195
Name:   music.httpdns.c.163.com
Address: 223.252.199.66


[root@instance-2 ~]# ping 223.252.199.66
PING 223.252.199.66 (223.252.199.66) 56(84) bytes of data.

超时

**Comment by nondanee** [comment]
那你把 httpdns 的部分去掉好了
app.js Line 70
```diff
-- Promise.all([httpdns(hook.target.host[0])].concat(hook.target.host.map(host => dns(host))))
++ Promise.all([].concat(hook.target.host.map(host => dns(host))))
```

**Comment by Mathisdifficult** [comment]
thanks 解决了

**Comment by toooonyy** [comment]
遇到的同样的问题，目前是把 `music.httpdns.c.163.com` 指向了一个正常的 ip，那个小 patch 也可以解决。
