### ISSUE TITLE
hosts模式下android依旧显示无版权

### ISSUE THREAD

**Issue by 962978926** [nondanee/UnblockNeteaseMusic#112]
uwp和ios下都正常工作，已参考帖子添加223.252.199.10和103.251.128.85两条静态路由规则。
安卓版本8.1，网易云6.2.1。

**Comment by nondanee** [comment]
参考了哪个帖子麻烦贴一下

**Comment by 962978926** [comment]
readme中关于android的那两条

**Comment by nondanee** [comment]
我不知道诶

好像别的大佬也发现了这个问题
https://github.com/nondanee/UnblockNeteaseMusic/issues/65#issuecomment-490204146

你自己抓个包看一下吧

**Comment by 962978926** [comment]
好的，谢谢耐心解答
