### ISSUE TITLE
docker 如何添加参数 -e -p 的参数呢？

### ISSUE THREAD

**Issue by tanpengsccd** [nondanee/UnblockNeteaseMusic#113]
我想装在群晖上。

**Comment by nondanee** [comment]
我搜了下群晖 docker 的帖子
好像是这个位置：
"创建容器 > 高级设置 > 环境 > 执行命令 > 命令"

**Comment by tanpengsccd** [comment]
oh yes ,成功。thx。简单说下教程。
我是用的caddy 不是nginx 作为endpint 的入口。
# 安装 caddy ，证书自己想办法（建议看这篇文章https://github.com/andyzhshg/syno-acme）
首先安装 https://hub.docker.com/r/abiosoft/caddy/ 
配置方式 里面有说明，注意一点，网络必须勾选“使用和 docker host 相同的网络”
![image](https://user-images.githubusercontent.com/13959880/59294615-723b4680-8cb4-11e9-9ab2-ee53a71a3246.png)
caddyfile:
```
https://flat.yourhost.com:10443 {
    tls /etc/caddycerts/flat.yourhost.com.cer /etc/caddycerts/flat.yourhost.com.key
    proxy / flat.yourhost.com:18443
}
```
# 安装 nondanee/unblockneteasemusic
同样 网络必须勾选“使用和 docker host 相同的网络”
然后只要是命令行 需要自己输入参数
`-e https://flat.yourhost.com:10443 -p 18080:18443`
![image](https://user-images.githubusercontent.com/13959880/59295187-a6633700-8cb5-11e9-942b-b8ecdbe12b9f.png)

# 然后就行了
![image](https://user-images.githubusercontent.com/13959880/59295371-196cad80-8cb6-11e9-9866-70fc1ec4e9e8.png)

PS：flat.yourhost.com 可能需要自己设置 DNS 到 本地群晖的 ip地址（比如192.168.2.10）

**Comment by nondanee** [comment]
好的

如果仅仅给 macOS 客户端用，不需要修改 endpoint
