### ISSUE TITLE
本地运行可以把0.0.0.0改成127段的一个单独ip吗

### ISSUE THREAD

**Issue by Howard-00** [nondanee/UnblockNeteaseMusic#114]

**Comment by nondanee** [comment]
可以的 
```
.listen(port, '127.0.0.1')
```
> https://nodejs.org/dist/latest-v10.x/docs/api/net.html#net_server_listen_port_host_backlog_callback

不想加 option，因为懒==，而且可以用防火墙把外网请求屏蔽了
请问有实际的使用场景吗？

**Comment by Howard-00** [comment]
> 可以的
> 
> ```
> .listen(port, '127.0.0.1')
> ```
> 
> > https://nodejs.org/dist/latest-v10.x/docs/api/net.html#net_server_listen_port_host_backlog_callback
> 
> 不想加 option，因为懒==，而且可以用防火墙把外网请求屏蔽了
> 请问有实际的使用场景吗？

主要是预防可能的冲突，特别是80端口时

**Comment by nondanee** [comment]
好的，我加个选项好了，默认还是 0.0.0.0 接受外网访问

冲突的问题其实也可以用 hostname + 反代解决
