### ISSUE TITLE
虾米还是灰

### ISSUE THREAD

**Issue by Benny-F** [nondanee/UnblockNeteaseMusic#116]
在你的国内服务器上跑 bridge.js（跑了）
把 host 改成你自己地址
UnblockNeteaseMusic/provider/insure.js
Line 2 in 0184369
 const host = '127.0.0.1' （改成这样了）
把仅用于 qq 的限制去掉
UnblockNeteaseMusic/provider/insure.js
Line 13 in 0184369
 if(path != 'qq/ticket') return Promise.reject() （这行删掉了）
然而虾米还是不行。
另外，网易《无尽光芒》不行，提示歌曲不存在。
我是初学者，请多指教，谢谢。

**Comment by nondanee** [comment]
先问一下，你说的 "虾米还是不行" 怎么体现？

**Comment by Benny-F** [comment]
就是灰色的还是灰色，点击播放提示争取版权这类的。iPhone 6sp测试。服务器国内的。

**Comment by nondanee** [comment]
这个项目叫 unblockneteasemusic
跟虾米客户端没关系
(虽然传言要合并)

**Comment by Benny-F** [comment]
那么虾米的unblock失败在哪里呢？bridge是不是有特定端口？我是nat机在跑。

**Comment by nondanee** [comment]
你理解错了
bridge 是一个简单的 RPC server
为了防止匹配阶段被其他平台的海外墙阻拦

此代理只解析特定的流量请求(来自网易云)对虾米无效

如果有能力的话你可以写一个 unblockxiamimusic

需要针对虾米音乐的 API 重写 hook.request.before 和 hook.request.after

**Comment by Benny-F** [comment]
我糊涂了，不是默认支持四个吗？还是只支持网易云音乐？我是没有这个能力了，希望您能继续努力！

**Comment by nondanee** [comment]
默认用了 4 个平台匹配的搜索结果让网易云灰色的歌曲可以播放

只支持网易云音乐

不好意思我不是虾米用户 😅

**Comment by Benny-F** [comment]
原来是这样啊！非常感谢！
