### ISSUE TITLE
httpServer.on('connect', (req, cltSocket, head)=>{....}) 里的head似乎没作用

### ISSUE THREAD

**Issue by onewayticket255** [nondanee/UnblockNeteaseMusic#117]
[https://nodejs.org/dist/latest-v12.x/docs/api/http.html#http_event_connect](https://nodejs.org/dist/latest-v12.x/docs/api/http.html#http_event_connect) 是带head的，但是我实际测试时候`console.log(head)`只会显示`<Buffer >`，没有具体数据。删除` srvSocket.write(head)`也不影响。

[https://github.com/nondanee/UnblockNeteaseMusic/blob/bc8b94a98f034e7b3e827ace8d694a923a763cc3/server.js#L136](https://github.com/nondanee/UnblockNeteaseMusic/blob/bc8b94a98f034e7b3e827ace8d694a923a763cc3/server.js#L136)去掉这一行也可以正常运行。

现在搞不清楚这个head到底是什么，是否可以删除。

**Comment by nondanee** [comment]
我知道
没有影响
但文档给的 example 写了

https://nodejs.org/dist/latest-v10.x/docs/api/http.html#http_event_connect

所以留着吧 (不差这一行)

**Comment by nondanee** [comment]
或许和 websocket 有关？(我猜测)

**Comment by onewayticket255** [comment]
好的，看来head确实很奇怪。以后再研究了。

**Comment by nondanee** [comment]
我发现文档里有=.=

https://nodejs.org/api/http.html#http_event_connect_1
> `head` \<Buffer\> The first packet of the tunneling stream (may be empty)

我感觉应该就是 tls client hello 这个 packet
