### ISSUE TITLE
macos 封面不显示

### ISSUE THREAD

**Issue by shugo-chara** [nondanee/UnblockNeteaseMusic#121]
一直靠chrome插件过活（懒），直到最近发现副作用也阻挡不了一些歌变灰了，于是充新更新了unm，发现除了还是一如既往第一次启动需要网络错误半天外，在macos的网易云客户端（700）上显示不出歌曲封面。评论和歌单图片都正常请求到，除了歌曲封面。
然后换了android上的终端运行，没有出现这个问题。
![image](https://user-images.githubusercontent.com/20610965/59744736-2ab54b80-92ae-11e9-88fe-e41f61efb4fe.png)

**Comment by nondanee** [comment]
把 type 改成 https 试一下
https://github.com/nondanee/UnblockNeteaseMusic/issues/91#issuecomment-492280542

**Comment by shugo-chara** [comment]
> 把类改成https试一下
> [＃91（评论）](https://github.com/nondanee/UnblockNeteaseMusic/issues/91#issuecomment-492280542)

谢谢，解决了。准备换成ClashX来替代，请问有相关的配置教程吗，我把http端口改好后不起效，规则里看到默认就有网易的规则。外部控制设置默认9090没有办法更改端口
