### ISSUE TITLE
pm2 設置問題

### ISSUE THREAD

**Issue by theandychung** [nondanee/UnblockNeteaseMusic#123]
之前不知道看到哪個issue裡面有寫說可以用pm2設定成後台執行
`pm2 start D:\GitHub\UnblockNeteaseMusic\app.js`
設定成功後就忘了
現在因為網易雲IP改過了以後更新了一下本地的code
結果pm2變成無法像以前一下用了
記得好像是哪裡需要改IP
請問是哪個檔案呢?

**Comment by nondanee** [comment]
更新 code 以后应该需要删除一下旧的 app
```
pm2 list
pm2 delete <appName>
pm2 start ……
```

**Comment by theandychung** [comment]
抱歉
我只有周末比較有空回應

每次開機後我都需要用pm2 start
所以這方面我有注意
並不是使用上的問題

我用pm2時發現無法使用後
我試圖用原本的指令
`node app.js -p 80 -f xxx.xxx.xxx.xxx`
後發現也不能用
ping網易雲後發現網易雲換了ip了 (yyy.yyy.yyy.yyy)
現在若改輸入
`node app.js -p 80 -f yyy.yyy.yyy.yyy`
後便可以使用
但是pm2還是不能使用
請問有方法解決嗎

**Comment by nondanee** [comment]
能不能 `pm2 list` 截个图？

**Comment by theandychung** [comment]
![](https://i.imgur.com/viPnOpl.png)

**Comment by nondanee** [comment]
然后 `pm2 show app` 可以看到启动参数的

**Comment by theandychung** [comment]
![](https://i.imgur.com/eowFFlr.png)

**Comment by nondanee** [comment]
显示 script args 是空的，pm2 start 要带参数

**Comment by theandychung** [comment]
請問要怎麼查這個參數?
我對pm2不是很熟悉
之前這樣用都沒問題就沒有繼續研究了...

**Comment by nondanee** [comment]
`pm2 delete app`
`pm2 start app.js -p 80 -f yyy.yyy.yyy.yyy`

**Comment by theandychung** [comment]
還是不行
塗掉的地方皆是yyy.yyy.yyy.yyy
![](https://i.imgur.com/RHsf0pG.png)

**Comment by nondanee** [comment]
报错了 script not found，检查一下文件按位置

**Comment by theandychung** [comment]
argument好像不能這樣加
我再研究研究
謝謝

**Comment by theandychung** [comment]
`pm2 start app.js -- -p 80 -f yyy.yyy.yyy.yyy`
這樣就可以了

**Comment by nondanee** [comment]
👌
