### ISSUE TITLE
音质部分有点美中不足..

### ISSUE THREAD

**Issue by Tarhyru** [nondanee/UnblockNeteaseMusic#124]
在网易云上几首锁定的音乐..下下来发现是128的...
我看是多来源的..有办法手动查看各来源的音质自主选择么...

**Comment by owen0525** [comment]
记得以前好像是非会员也可以试听和下载高音质的歌曲，不过最近发现不行了（不过这个又涉及到版权的问题，蛋疼）

**Comment by nondanee** [comment]
@Tarhyru
可以改全局的匹配优先级 `-o`

在客户端界面上每首单独选择肯定不行，要做也只能在 console 里面选择，桌面端可以，但移动端一定会超时

QQ 音质就只有 128k，不想用的话可以直接去掉

**Comment by nondanee** [comment]
@owen0525
是说无损吗？
如果服务端不鉴权的话
可以强制优先下载高音质
但不是每个人都要无损的，比如我自己

**Comment by Tarhyru** [comment]
@nondanee 
我把QQ排掉发现那首歌..只有64了...
其实..我也不是特别追求无损，但很多音乐320和128区别还是很明显的...

**Comment by nondanee** [comment]
@Tarhyru
歌曲 id 报一下
排掉 QQ 以后匹配了哪个源？

**Comment by Tarhyru** [comment]
@owen0525 
我单独试了 网易 虾米 百度 都匹配不到东西..
最后应该是匹配到的咪咕
id=26341140

**Comment by nondanee** [comment]
@Tarhyru 
试了下确实只能 QQ 和 咪咕
不过 [26341140] sister's noise 这首歌网易是有版权的，所以充个黑胶吧
