### ISSUE TITLE
部署在vps上会消耗流量吗

### ISSUE THREAD

**Issue by lycor1s** [nondanee/UnblockNeteaseMusic#125]
我用的是流量计费的服务器，想知道转发的时候是不是完整转发一首歌的流量

**Comment by nondanee** [comment]
是的，跟用 $$/$$R 代理是一样的
而且移动端下载的时候可能需要转发两遍 #101 https://github.com/nondanee/UnblockNeteaseMusic/commit/3fe72f305fab1569c02dd0600c9c2d72225c16cc
