### ISSUE TITLE
运行脚本后还是无法听Jay的歌

### ISSUE THREAD

**Issue by fengxiakira** [nondanee/UnblockNeteaseMusic#126]
感谢大佬卓越的贡献！
我的问题是脚本成功运行，Jay的歌也成功从灰色变黑
但就是无法播放，一旦播放就会变成“加载失败”。
请问有什么解决办法么？

**Comment by nondanee** [comment]
什么平台
如果是 iOS / macOS 的问题
先把 opened issue 看一遍

**Comment by fengxiakira** [comment]
> 什么平台
> 如果是 iOS / macOS 的问题
> 先把 opened issue 看一遍

windows PC 平台

![image](https://user-images.githubusercontent.com/16449313/60106969-0e912e80-9734-11e9-83d4-514856feb219.png)

脚本没有异常

![image](https://user-images.githubusercontent.com/16449313/60107017-27014900-9734-11e9-9a5e-2179b05ea3dc.png)

**Comment by nondanee** [comment]
客户端版本号？

**Comment by fengxiakira** [comment]
> 客户端版本号？

2.5.0 
请问是用了QQ音乐免费音源的关系么？

**Comment by nondanee** [comment]
没关系，床边故事会匹配网易自己的音源

启动参数用了什么？代理模式还是 hosts？
Unblocker 版本号？你再试试别的下架歌曲，是不是全都不行？

Windows 客户端应该是配合使用最简单的了……不应该啊
