### ISSUE TITLE
Linux版本界面提示没有网络

### ISSUE THREAD

**Issue by louizen** [nondanee/UnblockNeteaseMusic#127]
ERROR:ssl_client_socket_impl.cc(1072)] handshake failed; returned -1, SSL error code 1, net_error -100

**Comment by nondanee** [comment]
Linux 客户端需要额外操作，README 里有写

**Comment by louizen** [comment]
麻烦到你了，我是小白，看了readme还是不知道怎么操作。
怎么自签证书？

**Comment by nondanee** [comment]
自签证书看 👉 https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-477870013
