### ISSUE TITLE
MacOS食用心得

### ISSUE THREAD

**Issue by archer9812** [nondanee/UnblockNeteaseMusic#128]
## 前言
这里就不介绍Mac怎么装NodeJS了。假设你下载好了源码并且装好了NodeJS，那么来看我的心得你可能会很有帮助。

### 安装依赖
```bash
npm install -g forever
```
大陆地区推荐下面的方法
```bash
npm install -g cnpm --registry=https://registry.npm.taobao.org
cnpm install -g forever
```

### 创建脚本
在电脑上的任何地方都可以，创建一个sh脚本，假设是163.sh
```
vi 163.sh
```
内容如下
```bash
forever start <app.js路径> -p 80 -f <ping网易云的地址>
例: forever start /Users/apple/Downloads/UnblockNeteaseMusic-master/app.js -p 80 -f 59.111.181.35
```
保存一下。按照下图设置为终端启动，并给予最高权限。
![image](https://user-images.githubusercontent.com/20982281/60155384-8d619680-981c-11e9-8728-471cfe8ccfc4.png)

### 设置脚本开机启动
![image](https://user-images.githubusercontent.com/20982281/60155428-ac602880-981c-11e9-94e9-1cbd8824ca81.png)
![image](https://user-images.githubusercontent.com/20982281/60155461-c8fc6080-981c-11e9-8ace-1d37c56082eb.png)
添加启动项，不要忘记保存

### 补充
如果你要使用Host方法，现在添加就可以，每次开机无需输入密码。
```bash
sudo vim /etc/hosts
```
如果你要使用PAC方法，修改一下创建脚本（163.sh）。
```bash
sudo networksetup -setautoproxyurl Wi-Fi http://localhost/proxy.pac
forever start <app.js路径> -p 80 -f <ping网易云的地址>
```
这样需要每次开机输入一次密码。
另外，最好先安装
http://d1.music.126.net/dmusic/NeteaseMusic_1.5.10_636_web.dmg
再覆盖安装
http://d1.music.126.net/dmusic/NeteaseMusic_2.0.0_700_web.dmg
直接安装700版本直接是HTTPS，无法使用。

**Comment by nondanee** [comment]
PAC 设置关机会保留的，不需在脚本里 set

客户端也可以随便更新
仓库里的 CA 证书安装一下，再开启 https 监听就行了

**Comment by archer9812** [comment]
> PAC 设置关机会保留的，不需在脚本里 set
> 
> 客户端也可以随便更新
> 仓库里的 CA 证书安装一下，再开启 https 监听就行了
