### ISSUE TITLE
感觉无法在安卓上部署阿 。。。 

### ISSUE THREAD

**Issue by kaweizz** [nondanee/UnblockNeteaseMusic#129]
配置了node.js环境
然后丢上去，跑了一下 报错。。

**Comment by nondanee** [comment]
报什么错呢？

**Comment by kaweizz** [comment]
![wenti](https://user-images.githubusercontent.com/24218920/60195615-f58c9880-986d-11e9-99be-e33b26f76733.png)

如果我说的不对..不要笑..能力有限.

搭好了node.js环境，把包丢进去。运行为什么会报错呢= =

**Comment by kaweizz** [comment]
如果安卓上有更优雅的方案...可以补全一下 README ..

部署在路由器上 感觉还行.. 但我想带着走，

**Comment by nondanee** [comment]
permission deny 肯定不是我的问题啊......你自查下有没有给存储权限之类的

有更好的方案: nodejs-mobile + VPNservice，可是没人写啊😂

**Comment by kaweizz** [comment]
这软件就一个权限。。就是存储..给了的。 总之就是运行不起来..

移动端无法优雅

**Comment by kaweizz** [comment]
VPNservice...是公网服务吗？

**Comment by kaweizz** [comment]
以我的才能 估计也就只能到这里了。。 等有缘人吧.. 就不折腾了。

**Comment by nondanee** [comment]
@kaweizz 
应该是运行的起来的，你说一下在 `cd yy` 之前的步骤吧

nodejs-mobile 是一个把 node 运行环境打包进 apk 开源项目
https://github.com/JaneaSystems/nodejs-mobile

VPNservice 是 android 的一个系统 API
https://developer.android.com/reference/android/net/VpnService

**Comment by kaweizz** [comment]
apt update && apt upgrade
.....
...
Y/N   Y!
...
..
100%

apt install nodejs


-----------------------------------------
welcome to node.js v12.4.0.

大概如此..多的 也忘记了。 


pkg install stu  
...
stu / su  
获取这个软件的root权限。


按理说 已经有node.js环境了。 应该可以执行的。。 不知道什么情况 。小白一个

**Comment by nondanee** [comment]
不需要 root 权限
你 exit 了再来一次试试吧
而且你这个情况不需要 ping 和 `-f`
就 `node app.js -p 2333` 就可以了

**Comment by kaweizz** [comment]
mkdir yy 

电脑建立那个文件夹不行。 （好像格式不一样，终端认不到）

用终端建立一个“YY”文件夹

复制目录中的“UnblockNeteaseMusic” 移动到/复制到  “YY”

切换到终端 

node app.js -p 2333 -f %ip% 

基本思路就是这样 ... 首次使用安卓node..

**Comment by nondanee** [comment]
复制的权限可能有问题吧？
你用 git 试试吧
```
pkg install git
git clone https://github.com/nondanee/UnblockNeteaseMusic.git
```

**Comment by kaweizz** [comment]
do you want to continue? [Y/N]    这个选啥 0.0

第一次使用git 需要cd 到路径 下载到路径内吗？  

mkdir XX
CD XX

pkg install git
git clone https://github.com/nondanee/UnblockNeteaseMusic.git

这样吗？

**Comment by nondanee** [comment]
git clone 会自动创建文件夹的
不用手动 mkdir

**Comment by kaweizz** [comment]
看来没点基础还真不行... 这个git clone 自动创建的文件不知道去哪里了 = =

**Comment by nondanee** [comment]
ls 看一下啊，就在当前目录下
文件夹名字叫 UnblockNeteaseMusic

**Comment by kaweizz** [comment]
你说不用ping(IP)  那怎么和网易云建立联系阿 ？ 

也是127.0.0.1:2333吗？

**Comment by kaweizz** [comment]
http://<127.0.0.1:2333>/proxy.pac     这样吗？

**Comment by kaweizz** [comment]
感谢大佬。。

pkg install git  这个命令一直出错， 试了十几次 终于把GIT 装上去了。 

确实git还是好用。 搭起来了！！！ running http://0.0.0.0:2333 这咋搞阿 = = 

不PING music.163.com  怎么建立联系 = =

**Comment by kaweizz** [comment]
电脑有cmd 可以写一段代码自动判定 music.163.com 的IP 变化 ..
手机只有终端，只能锁一个IP 这里还有一些不懂得。。 不知道怎么解决IP一直变这个问题 = =

**Comment by nondanee** [comment]
设置 WLAN 代理，README 里写了

ping 也建立不了联系，`-f` 是为 hosts 模式准备的
你应该参考了别人的教程吧？我可没说一定要 ping

**Comment by nondanee** [comment]
> http://<127.0.0.1:2333>/proxy.pac

用 pac 的话，代理选自动，地址填这个 `http://127.0.0.1:2333/proxy.pac`，两边没有 `<` `>`

**Comment by kaweizz** [comment]
我确实参考了大部分别人的教程，加上了一些自己的想法。  
肯定先学别人的。。不然怎么入门...
ping 的方式。。确实有效。我刚才测试了。

问题是...您说的 直接使用 node app.js -p 2333
代理选自动 http://127.0.0.1:2333/proxy.pac 
这样也无效奥

**Comment by kaweizz** [comment]
README 里 好像写了  [-u url]  

这样好像是行不通的唉 。 

案例   node app.js -p 2333 music.163.com   

这样吗？

**Comment by nondanee** [comment]
就这样 `node app.js -p 2333` 不要加别的

请问无效怎么体现？

**Comment by kaweizz** [comment]
见鬼了...居然真的可以了 ...我之前测试了无数次..都不行！！

这样的话？？？莫非PC也可以 直接 node app.js -p 2333 ?

**Comment by nondanee** [comment]
当然可以

**Comment by kaweizz** [comment]
至此。 
我得出的结论就是。

作者才是官方正统... 虽然他们发布的做法让我饶了一个大弯路，但好歹领进门了。  


-------------------------------------------------------------------------------------------------------

感谢作者一晚上默默指导，万分感谢。    有和我一样不懂的小白 可以参考本issues 。 再次拜谢。
