### ISSUE TITLE
歌曲无法播放

### ISSUE THREAD

**Issue by leewp14** [nondanee/UnblockNeteaseMusic#13]
(node:24237) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): SyntaxError: Unexpected token u in JSON at position 0
使用代理器

**Comment by nondanee** [comment]
麻烦告知一下是哪首歌

**Comment by leewp14** [comment]
我试过的每一首都这样。也试了脚本README中截图的歌曲。
我自己设置了一个server, 那个server里设置了proxy. 普通通过我的server使用网易可以下载播放。但通过此脚本却不能播放。（可以搜索等等，版权歌曲也不便灰，唯独播放任何歌曲都失效失效）
随后也试过了直接连接proxy使用也一样。
我是这么用的: `sudo node start app.js -p 80 -u http://35.167.126.77:80` (server在线，可以试试)
不知我的setup有任何不对之处，如有，还请见谅 :sweat_smile: 
proxy 是[这里的](https://s1.jixun.moe/163/ips.html)

**Comment by nondanee** [comment]
好的，请问系统是macOS吗？使用hosts模式？
抱歉你架设的server我无法连接上，另外你的server是否支持https tunnel？jixun上的反代我试了下都无此功能

**Comment by nondanee** [comment]
你是通过[此配置](https://jixun.moe/post/ymusic-hosts-fix/)设置的proxy server吗？

**Comment by nondanee** [comment]
如果想使用类似jixun的反代服务器
可以这样设置`sudo node app.js -p 80 -f 35.167.126.77`
这样设置就不是proxy了，原理类似改hosts

**Comment by nondanee** [comment]
抱歉没懂你的意思
要用`-p`代理功能的代理服务器必须支持https tunnel
我也在海外，不过是用ss的privoxy代理回国😢，都在本地

**Comment by leewp14** [comment]
噢，明白了！原来是要用支持https tunnel的proxy
我试试看，谢谢！
也顺便请问，你代理回国，是自己的server还是使用其他代理资源？

**Comment by nondanee** [comment]
@leewp14 自己买的server，UOvZ的，带宽大一些😂
