### ISSUE TITLE
安卓装了证书，路由自动中转到服务端不行吗？

### ISSUE THREAD

**Issue by muziling** [nondanee/UnblockNeteaseMusic#130]
在群晖上装了docker版本，服务器信息是
192.168.222.8:5678  ，windows版的网易设这个代理可用，然后比如我的安卓手机IP是 192.168.222.22，在路由器上用iptables转发网易的IP到服务器，转发命令：
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 39.105.63.80 -j DNAT --to-destination 192.168.222.8:5678
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 47.100.127.239 -j DNAT --to-destination 192.168.222.8:5678
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 59.111.160.195 -j DNAT --to-destination 192.168.222.8:5678
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 59.111.160.197 -j DNAT --to-destination 192.168.222.8:5678
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 59.111.181.35 -j DNAT --to-destination 192.168.222.8:5678
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 59.111.181.38 -j DNAT --to-destination 192.168.222.8:5678
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 59.111.181.60 -j DNAT --to-destination 192.168.222.8:5678
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 59.111.181.61 -j DNAT --to-destination 192.168.222.8:5678
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 59.111.181.155 -j DNAT --to-destination 192.168.222.8:5678
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 118.24.63.156 -j DNAT --to-destination 192.168.222.8:5678
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 193.112.159.225 -j DNAT --to-destination 192.168.222.8:5678
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 223.252.199.66 -j DNAT --to-destination 192.168.222.8:5678
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 223.252.199.67 -j DNAT --to-destination 192.168.222.8:5678

安卓手机装不装这个证书（https://raw.githubusercontent.com/nondanee/UnblockNeteaseMusic/master/ca.crt），灰色的音乐都是提示资源不存在。

不知道我哪一步操作不正确

**Comment by nondanee** [comment]
手机上要装证书

**Comment by nondanee** [comment]
--to-destination 不要写端口号，你这样会把 https 请求发到 http 端口上

**Comment by nondanee** [comment]
把 http 和 https 分开写试试看
-d 223.252.199.67:80 --to-destination 192.168.222.8:5678
-d 223.252.199.67:443 --to-destination 192.168.222.8:<你的 https 端口>

**Comment by muziling** [comment]
docker 只有8080 一个端口吧， 看了代码是启动参数允许 冒号分隔开HTTP 和HTTPS两个端口，
那能更新下docker不？

**Comment by nondanee** [comment]
好的

**Comment by nondanee** [comment]
因为代理模式下 https 端口是内部转发用的，不需要 expose，默认又不开启 https 监听所以一直没改 Dockerfile，抱歉

**Comment by muziling** [comment]
我看app.js里只默认了8080端口监听，并没有8081端口，是不是这里也需要增加？
另外dsm里docker我删了，重装UnblockNeteaseMusic ，还是只有8080端口，是不是需要更新到hub仓库？

**Comment by nondanee** [comment]
@muziling 
默认不开启 https 监听，需要 `-p 8080:8081`
是的还没更新，是 release auto trigger

**Comment by muziling** [comment]
app.js只默认了8080，没默认8081不行吧，  至少docker启动后，8080端口用浏览器打开会有nginx的提示， 8081就是无法访问的页面了

**Comment by muziling** [comment]
点错了，点成关闭issue了

**Comment by nondanee** [comment]
启动 docker image 可以带参的啊
你自己加上 `-p 8080:8081` 就行了 https://github.com/nondanee/UnblockNeteaseMusic/issues/113#issuecomment-500866307

**Comment by muziling** [comment]
可能是openwrt 同一个网段转发不行吧， docker里的日志没收到iptables转过来的报文，这个不属于这个项目的问题，关闭吧，我用的iptables命令应该有问题：
`iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 39.105.63.80 --dport 80 -j DNAT --to-destination 192.168.222.8:5678
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 47.100.127.239 --dport 80 -j DNAT --to-destination 192.168.222.8:5678
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 59.111.160.195 --dport 80 -j DNAT --to-destination 192.168.222.8:5678
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 59.111.160.197 --dport 80 -j DNAT --to-destination 192.168.222.8:5678
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 59.111.181.35 --dport 80 -j DNAT --to-destination 192.168.222.8:5678
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 59.111.181.38 --dport 80 -j DNAT --to-destination 192.168.222.8:5678
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 59.111.181.60 --dport 80 -j DNAT --to-destination 192.168.222.8:5678
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 59.111.181.61 --dport 80 -j DNAT --to-destination 192.168.222.8:5678
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 59.111.181.155 --dport 80 -j DNAT --to-destination 192.168.222.8:5678
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 118.24.63.156 --dport 80 -j DNAT --to-destination 192.168.222.8:5678
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 193.112.159.225 --dport 80 -j DNAT --to-destination 192.168.222.8:5678
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 223.252.199.66 --dport 80 -j DNAT --to-destination 192.168.222.8:5678
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 223.252.199.67 --dport 80 -j DNAT --to-destination 192.168.222.8:5678

iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 39.105.63.80 --dport 443 -j DNAT --to-destination 192.168.222.8:5679
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 47.100.127.239 --dport 443 -j DNAT --to-destination 192.168.222.8:5679
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 59.111.160.195 --dport 443 -j DNAT --to-destination 192.168.222.8:5679
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 59.111.160.197 --dport 443 -j DNAT --to-destination 192.168.222.8:5679
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 59.111.181.35 --dport 443 -j DNAT --to-destination 192.168.222.8:5679
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 59.111.181.38 --dport 443 -j DNAT --to-destination 192.168.222.8:5679
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 59.111.181.60 --dport 443 -j DNAT --to-destination 192.168.222.8:5679
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 59.111.181.61 --dport 443 -j DNAT --to-destination 192.168.222.8:5679
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 59.111.181.155 --dport 443 -j DNAT --to-destination 192.168.222.8:5679
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 118.24.63.156 --dport 443 -j DNAT --to-destination 192.168.222.8:5679
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 193.112.159.225 --dport 443 -j DNAT --to-destination 192.168.222.8:5679
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 223.252.199.66 --dport 443 -j DNAT --to-destination 192.168.222.8:5679
iptables -t nat -A PREROUTING -p tcp -s 192.168.222.22 -d 223.252.199.67 --dport 443 -j DNAT --to-destination 192.168.222.8:5679
`

**Comment by nondanee** [comment]
不太熟 iptables
你看看这个吧 https://www.right.com.cn/forum/forum.php?mod=redirect&goto=findpost&ptid=692049&pid=4104303
