### ISSUE TITLE
我又来了。安卓是不是存在伪后台，感觉有时候终端会不工作

### ISSUE THREAD

**Issue by kaweizz** [nondanee/UnblockNeteaseMusic#131]
如果终端在后台不工作的话， 网易云就会不工作= = 因为网络的问题。 

我突然想到4G好像没有网络代理的。。这就是你们说的证书什么的吗 = =

我大胆猜想这个后台可能需要forever 来试试..

**Comment by kaweizz** [comment]
大佬如果累的话，可以先去休息.

等啥时候有空 啥时候来指点一下。 

主要就是  后台/4G代理     这两个问题目前。

**Comment by nondanee** [comment]
保证 termux 不关就好了
如果 termux 关了， forever 也没用

如果你不手动 exit，termux 会驻留通知栏的，不是伪后台也不会被强杀

安卓上可以不用证书

4G 可以在 APN 里设置代理
