### ISSUE TITLE
设置了http://<Server Name:PORT>/proxy.pac   部分软件出现网络问题

### ISSUE THREAD

**Issue by kaweizz** [nondanee/UnblockNeteaseMusic#132]
VIA浏览器全挂。（网络问题不能用了）
知乎部分CSS？（是这样说嘛？）  

昨天因为就QQ和终端两点研究，所以没测别的软件。 
PAC模式是不是有一个PAC规则的。。是不是那个没配置 配置不正确 或者 有部分BUG?

**Comment by nondanee** [comment]
确实是 PAC 下，via 有问题，但是 chrome 没问题

PAC 规则那个文件你可以下载下来看看，应该没什么问题

试了下手动 (全局代理) 下，via 可以用

**Comment by kaweizz** [comment]
代理-手动
服务器主机名:127.0.0.1
服务器端口:2333
对以下对象绕过代理:空
IP:DHCP

还是不行唉  （大佬真是劳模 啥时候都在。

**Comment by nondanee** [comment]
可以的吧，你再试试

**Comment by nondanee** [comment]
<img src="https://user-images.githubusercontent.com/26399680/60242949-b8fe8280-98e9-11e9-8ab2-c1d1da13ee75.png" width="50%">

**Comment by kaweizz** [comment]
问题找出来了。。
我刚才使用了 -S 的参数 = = 
算是一个解决方案吧。 只是看起来没那么优雅 。 
所有流量都走UnblockNeteaseMusic 感觉怪怪的。  

谢谢大佬.

**Comment by kaweizz** [comment]
虽然termux常驻通知栏，所有权限都打开了（事实上就一个储存
感觉还是有伪后台的情况，[需要手动切换到termux页面，让termux响应过来]
termux假死之后，全线瘫痪~~（锁屏100%响应不过来
(可能是部分机型ROM的问题吧？ 


可能需求更优雅的终端APP 。。又或许是ROM
---------------------------------------------
基本如此

**Comment by nondanee** [comment]
本地代理，又不多占内存又不多耗流量也不泄露数据不影响网速
没什么奇怪的......

以后解决了麻烦 close 一下
优雅实现你还是自己想吧 (不在我的职责范围内)
