### ISSUE TITLE
在WLS2中运行UNM,WIN10通过netsh interface portproxy转发没任何效果

### ISSUE THREAD

**Issue by HiJackXD** [nondanee/UnblockNeteaseMusic#134]
系统：win10最新预览版/WSL2

---------------------------------
因为WLS2基于HYPER V，所以win10不能直接通过localhost访问UNM。
所以我想在win10上转发本地端口到WLS2的端口(172.17.234.26:8080)。转发后，浏览器的确可以访问到http://127.0.0.1:8080/proxy.pac。
但在win10网络设置代理中填上http://127.0.0.1:8080/proxy.pac 后，网易云就网络异常了，用172.17.234.26 的地址就正常.
请问这是什么原因呢？

---------------------------
windows转发命令是
```
netsh interface portproxy add v4tov4 listenport=8080 listenaddress=127.0.0.1 connectport=8080 connectaddress=172.17.234.26
```

**Comment by HiJackXD** [comment]
windows转发命令是
netsh interface portproxy add v4tov4 listenport=8080 listenaddress=127.0.0.1 connectport=8080 connectaddress=172.17.234.26

**Comment by nondanee** [comment]
不清楚
会不会是 netsh 和系统代理有冲突？
试试看在 windows 客户端里填写代理 127.0.0.1:8080 吧
