### ISSUE TITLE
获取播放地址失败

### ISSUE THREAD

**Issue by ZORfree** [nondanee/UnblockNeteaseMusic#135]
如题，在pc上设置http代理后，使用正常，局域网内，手机设置代理，也可以

但是 pc上 frp http映射8080至公网域名后，手机设置代理就无效了，没有网络

然后pc上http 改为tcp映射，手机设置代理后，正常有网络，控制台上也有请求日志，进入歌曲后，也返回了正确的链接，如下图，但是播放的时候，显示获取播放地址失败
![image](https://user-images.githubusercontent.com/26847215/60382719-f30e8680-9a99-11e9-8335-51405bee8514.png)
求问大佬，这种方法可行吗？要怎么做？

**Comment by nondanee** [comment]
是的需要 tcp 映射

我觉得可行

是 Android 吧？
看 log 是我主动关了 tunnel
你可以试下安装证书并开启 https 监听
