### ISSUE TITLE
在vps上部署项目，可以在运行之后继续对服务端进行操作吗？

### ISSUE THREAD

**Issue by IlIlIlllIIl** [nondanee/UnblockNeteaseMusic#136]
如题，在执行了node app之后，除了按下ctrl+c 不然会一直工作，有办法让其在后台工作吗？

**Comment by nondanee** [comment]
pm2, forever, supervisor, nohup, screen 等 https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-442431602

**Comment by IlIlIlllIIl** [comment]
已解决
