### ISSUE TITLE
求救一下

### ISSUE THREAD

**Issue by finsxc** [nondanee/UnblockNeteaseMusic#139]
大佬们 我真的不是伸手党 纯小白弄了一天了… 

现在就是打开后没有网络

我的步骤是买的阿里的轻型服务器，centos7装了宝塔，然后PM2添加项目，安全里也把8080给放行了，换过端口也不行，windows客户端代理写上后就是没网络，更别提IOS小火箭了…

哪步出错了求教 求救 真的要哭了

**Comment by nondanee** [comment]
怎么救啊😳

**Comment by finsxc** [comment]
> 怎么救啊😳

我这为啥不能用啊大佬 有哪里出错了吗

**Comment by finsxc** [comment]
> 怎么救啊😳

重装了几遍宝塔 甚至换了版本 还是不行

**Comment by nondanee** [comment]
你的联系方式发我邮箱吧

**Comment by finsxc** [comment]
> 你的联系方式发我邮箱吧

好的 已发 哭了
