### ISSUE TITLE
运行$ node app.js提示不是程序也不是批处理   

### ISSUE THREAD

**Issue by 1147612708** [nondanee/UnblockNeteaseMusic#14]

**Comment by 1147612708** [comment]
exe的一直在Server running @ http://0.0.0.0:8080这行 动也不动

**Comment by JasonKhew96** [comment]
请阅读 [使用](https://github.com/nondanee/UnblockNeteaseMusic#%E4%BD%BF%E7%94%A8)
请问使用的是HOST，客户端代理，还是pac代理？

**Comment by nondanee** [comment]
@1147612708 抱歉，`$` 是linux shell的提示符，你只需要键入`node app.js`到cmd窗口就可以了

**Comment by nondanee** [comment]
@1147612708 使用需要配置，请先阅读README，如果是windows客户端，在客户端设置里填上代理地址即可使用

**Comment by 1147612708** [comment]
hosts 改了好像没用（可能我瞎弄没弄对）readme 上的配置只适用Linux客户端的？ Windows客户端里的代理地址填什么好  萌新一枚 不懂求大佬详细一点的教程

**Comment by 1147612708** [comment]
![qq 20180909184913](https://user-images.githubusercontent.com/42194937/45263872-98e9f980-b464-11e8-859f-3f33f1d496bf.png)
我的是这样的 代理不可用

**Comment by JasonKhew96** [comment]
@1147612708 我的也显示不可用，可是可以用😂😂😂

**Comment by nondanee** [comment]
解释一下为什么提示不可用
客户端测试代理的地址用的是 http://music.163.com
好像8月底网易云官网换上https
请求这个http的官网会302重定向到https
状态码不是200所以提示不可用
可以试试看使用privoxy等著名的代理服务器，应该都会报不可用
