### ISSUE TITLE
与shadowsocks冲突

### ISSUE THREAD

**Issue by youaremywind** [nondanee/UnblockNeteaseMusic#140]
mac 使用了解锁代理就无法科学上网 使用ssr科学上网就无法解锁了 仔细看了下是pac地址变了 但是如何即可科学上网又可解锁？将两个pac合二为一？

**Comment by youaremywind** [comment]
![image](https://s2.ax1x.com/2019/07/02/ZGYjw4.png)

**Comment by goxofy** [comment]
善用搜索

**Comment by nondanee** [comment]
去编辑 $$R 的 gfwlist.js
