### ISSUE TITLE
关于endpoint选项与带package的url相关问题

### ISSUE THREAD

**Issue by GoldenMean58** [nondanee/UnblockNeteaseMusic#143]
最近发现的这个项目，能恢复变灰的歌曲，但是依然有部分歌曲无法播放，发现文档写的endpoint选项，并且在源码中找到了
`http://music.163.com/package/...`
这个链接，我想问下这个链接对某些歌曲是否已经失效，但是似乎代理找到了可用链接但没有替换掉这个失效的链接，比如：
[床边故事](http://music.163.com/package/aHR0cDovL3AxLm11c2ljLjEyNi5uZXQvYUhJOGN5MFBhaXE5a3pUQ1pJNmd2dz09LzM0MzE1NzU3OTMxOTE2Nzk=/415792916.mp3)
返回资源不存在

我通过修改部分代码修复了这个问题，但是还是想具体了解下这个项目

同一首歌(id相同)在Linux环境下无法播放，Windows环境却可以正常播放，链接都是同一个，但是用浏览器都返回资源不存在

另外我想问下endpoint的作用是什么

感谢！

系统：Arch Linux
网易云版本：1.2.1

**Comment by GoldenMean58** [comment]
好像找到问题了，我用的是改hosts文件的方法，导致music.163.com被屏蔽了，所以只有music.163.com的源不能播放，给的package链接请求不到数据

**Comment by nondanee** [comment]
你理解错了，替换的链接不是真实连接
真实地址被包装在 music.163.com 里面
`http://music.163.com/package/真实链接的 base64 编码结果/歌曲 id.mp3`

https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-488250457
> 这个末端地址是 unblock server 自己构造的，网易云官网上没有资源（这个地址以 music.163.com 开头只是为了在 hosts 模式下让这个请求到达 unblock server）

这个链接的请求在经过 proxy 的时候会被解析成真实链接并请求
浏览器因为没有过 proxy 所以返回资源不存在

我不知道你是怎么修改代码修复的
要包一层还因为 Android 客户端无法播放带 querystring 的链接(不知道为什么)，而 QQ 的链接必须有 `?vkey=`

具体是哪首歌，请提供 ID，我去查一下

**Comment by GoldenMean58** [comment]
@nondanee
也就是说链接
`http://music.163.com/package/真实链接的 base64 编码结果/歌曲 id.mp3`
实际上应该给代理处理而不是直接去请求网易云，对吗

歌曲应该没问题，是我没有理解导致操作过于智熄(上面链接估计没走proxy)

我修改的代码很简单粗暴，文件[hook.js](https://github.com/nondanee/UnblockNeteaseMusic/blob/master/hook.js)，第260行
``` javascript
item.url = `${global.endpoint || 'http://music.163.com'}/package/${crypto.base64.encode(song.url)}/${item.id}.mp3
```
替换为：
```javascript
item.url = song.url
```
这样就行了

**Comment by nondanee** [comment]
@GoldenMean58 
好的，改了也没什么问题，可以用就行了
package 主要是为了移动端的兼容性

**Comment by nondanee** [comment]
我退回旧版本测了下好像没 querystring 的问题，可能是当时我弄错了
下个版本我会改成 `item.url = song.url`
谢谢提醒
