### ISSUE TITLE
【问题】客户端连接代理后灰色未变

### ISSUE THREAD

**Issue by yuukiyuuna** [nondanee/UnblockNeteaseMusic#144]
服务端：Centos7 ，IP为日本东京
客户端：windows网易云2.5.3

客户端网易云设置http代理后，可以加载歌曲，但原本灰色的还是灰色的，除此之外一切正常

想问下大佬，是我的配置有问题么，还是客户端版本太高

![image](https://user-images.githubusercontent.com/17798350/60798248-5c318080-a1a3-11e9-964a-952d5310d370.png)

**Comment by nondanee** [comment]
卧槽……

**Comment by nondanee** [comment]
你的 node 版本是多少？

**Comment by stariveer** [comment]
好像新版确实有问题

**Comment by stariveer** [comment]
回滚一个版本,97a61de66f079ff185d69fc23e3e268f051ce556就可以

FYI:
node 版本 v6.17.1

辛苦作者了

**Comment by nondanee** [comment]
- https://nodejs.org/dist/latest-v10.x/docs/api/crypto.html#crypto_crypto_createcipheriv_algorithm_key_iv_options
- https://nodejs.org/dist/latest-v8.x/docs/api/crypto.html#crypto_crypto_createcipheriv_algorithm_key_iv_options
- https://nodejs.org/dist/latest-v6.x/docs/api/crypto.html#crypto_crypto_createcipheriv_algorithm_key_iv

嗯因为我把 iv 改成 `null` 了
node 8+ 的文档上有写
>  If the cipher does not need an initialization vector, iv may be `null`.

node 6 应该是不支持的，我会 rollback

**Comment by yuukiyuuna** [comment]
node版本是v8.11.4

**Comment by nondanee** [comment]
@yuukiyuuna 
node 8 文档 history 里注了
v8.12.0 | The iv parameter may now be null for ciphers which do not need an initialization vector.

已经 rollback 了

**Comment by yuukiyuuna** [comment]
是按照之前那个老哥说的，将node降级至 v6.17.1 么？

下面回复的这句“node 6 应该是不支持的”
还是降到别的版本

小白一个，还请原谅需要细问下，不然听不懂
﻿ε≡٩(๑>₃<)۶ 一心向学

**Comment by nondanee** [comment]
pull 新版代码，或者重新 clone

**Comment by yuukiyuuna** [comment]
感谢，现在已经可以用了

辛苦了，作者
