### ISSUE TITLE
咦~我的issues怎么消失了？出现很多假音源。 

### ISSUE THREAD

**Issue by kaweizz** [nondanee/UnblockNeteaseMusic#149]
大多数是网易云独享。 其他曲库也没有版权（资源）的

脚本会乱塞一个...

**Comment by nondanee** [comment]
匹配规则的问题
默认取各平台搜索结果第一条
具体匹配到哪个专辑哪首歌，要看各平台的搜索排序算法
而且一般来说搜索结果是不会空着的，如果没有完全匹配的，平台也会自动推荐相似歌曲
所以会播放另一首歌

参考 https://github.com/nondanee/UnblockNeteaseMusic/issues/10#issuecomment-415926335 https://github.com/nondanee/UnblockNeteaseMusic/issues/18

网易云独享的话，充钱就可以解决了

**Comment by nondanee** [comment]
issues 里默认只显示 open 的，你之前提的都 closed 了
要看自己的 issue 可以用 author filter
https://github.com/nondanee/UnblockNeteaseMusic/issues?q=author%3Akaweizz

**Comment by kaweizz** [comment]
感谢提供逻辑。
事实上，充钱能解决的问题。UnblockNeteaseMusic都可以解决。 
--------------------------------------------------------------------------------------------
我用文字重现一下场景。 
网易云很特殊，有很多常驻的翻唱音乐人。他们的音源只会发布在网易云，一旦下架，除非之前有缓存（.us转.mp3/除非使用前几年的“音乐间谍”/当前的“鱼声音乐”），全网基本搜不到了。 
anylisten(Fork源码) https://github.com/cilone/AMP
鱼声音乐 https://github.com/AnyListen/YaVipCore/releases
以上基本是充钱也解决不了的。（除非使用黑科技）

不然重写一下这部分的算法，让八竿子打不着的就直接黑了算了（不然想吃苹果，吃出香蕉的味道挺糟糕的...想了半天好像自己原来在吃香蕉）(不过好像说是平台的问题，不是脚本的问题...那也没办法了奥)
-----------------------------------------------------------------------------------------------
我不会造轮子，希望UnblockNeteaseMusic更好。

**Comment by nondanee** [comment]
> 匹配策略比较困难，因为不同平台命名规则不一样，专辑type，solo歌曲等，不能直接用名称一致来判断。

匹配是不是同一首歌的逻辑现在还没有，因为没什么好的策略，你让我重写我也写不来......等 PR
