### ISSUE TITLE
最近发现使用代理会导致一些应用的图片打不开, 或者微信的表情显示不了

### ISSUE THREAD

**Issue by 459217974** [nondanee/UnblockNeteaseMusic#15]
最近发现使用代理会导致一些应用的图片打不开, 或者微信的表情显示不了

**Comment by nondanee** [comment]
好像是PAC的问题，我试了下PAC下QQ的图片都不能显示，直接填ip端口号用全局代理就能看到，麻烦你也尝试下

**Comment by 459217974** [comment]
我是在手机WiFi上设置的代理, 应该是全局代理没有用pac的吧

**Comment by nondanee** [comment]
嗯嗯好的，已找到问题所在，确实不在PAC上😂

**Comment by 459217974** [comment]
感谢修复, 说句题外话, 我还是觉得代理这个方法有点不太方便, 我前几天想在你的基础上把下载的歌曲直接传到网易云盘, 查了一下发现好多人说上传云盘的接口加密十分复杂无法解析, 不知道你有没有兴趣往这个方向想想办法

**Comment by nondanee** [comment]
我没有懂😂，是想把下载下来的歌自动上传到云盘吗？

**Comment by 459217974** [comment]
不好意思,忘了回复了..就是网易云音乐有个云盘,传到那里的音乐能自动跟自己的歌单里的歌关联上,这样就可以不用代理也可以听了...最近网易的民谣大范围下架太伤了啊...
