### ISSUE TITLE
有很多被翻唱的歌识别错误。

### ISSUE THREAD

**Issue by X-Crack** [nondanee/UnblockNeteaseMusic#150]
这里给出两首

1：Wonderful U（Cover AGA）
2：凉liangliang（Cover zbc&yzw）
歌手：Britneylee小暖

网易云很优秀的一个翻唱歌手。

这俩歌不知道为啥识别成别的歌了。

**Comment by X-Crack** [comment]
还有个问题就是，node app.js 是同步的啊，SSH一旦关闭 监听服务也随之关闭了，我不是很懂，不是干这行的。

能改成异步的嘛。

**Comment by nondanee** [comment]
问题1 #149 
问题2 #136

**Comment by X-Crack** [comment]
感谢！
