### ISSUE TITLE
音源匹配出错

### ISSUE THREAD

**Issue by shugo-chara** [nondanee/UnblockNeteaseMusic#151]
id=571854572
这首下架歌匹配还是有问题。默认匹配的是qq源的独唱http://isure.stream.qqmusic.qq.com/M500004b4gah1fz3Ho.mp3?vkey=2514037104B0E5A7C0C5CCC35C50472AA74780EC4B2848D66D27C0F9DB83B0A563FB0483DC4B77BC30295B89595F01074536FE73F8818917&uin=0&fromtag=8&guid=7332953645
这种有办法修正吗。

**Comment by nondanee** [comment]
看了下是搜索关键词的问题

**Comment by daxinnan** [comment]
前两天林俊杰新歌还可以听，比如  我们很好， 现在要么不是他的歌要么不对
