### ISSUE TITLE
特定歌曲无法播放

### ISSUE THREAD

**Issue by yukinotech** [nondanee/UnblockNeteaseMusic#152]
中间的歌曲“triangle”无法播放，也无法下载。

已在2个不同的电脑，不同的wifi下，复现这个问题，应该是音源的问题。

采用node app.js -p 80 -f 59.111.181.60和改host启动

![](https://i.loli.net/2019/07/14/5d2a92c52fffc14117.png)

**Comment by nondanee** [comment]
那就是没有匹配到咯

**Comment by yukinotech** [comment]
> 那就是没有匹配到咯

意思是说所有的音源都没有这个歌是这个意思吗？我这样启动打开了所有的音源吗？

**Comment by nondanee** [comment]
emmm 我不知道啊，你知道哪个平台有版权呢？
没有，用 `-o ......` 开启

**Comment by yukinotech** [comment]
> emmm 我不知道啊，你知道哪个平台有版权呢？
> 没有，用 `-o ......` 开启

之前疏忽了，已读文档，增加了migu音源解决了问题。

谢谢及时回复。可以关闭该issue。

**Comment by nondanee** [comment]
好的
下次你可以自己关闭
