### ISSUE TITLE
服务端的性能好像有问题？

### ISSUE THREAD

**Issue by X-Crack** [nondanee/UnblockNeteaseMusic#153]
我觉得是架构有瑕疵，
我默认在VPS上开的是80端口，但是80端口一直被扫，然后SSH频繁滚动日志，滚着滚着就造成了网络阻塞。
最后的结果就挂了。必须重启进程。

**Comment by nondanee** [comment]
挂了总有原因吧？
报了什么错 exit 的呢？

你觉得是日志的问题
那就把 stdout 重定向到 /dev/null 好了
