### ISSUE TITLE
 mac 客户端每日推荐里音乐包歌曲无法播放

### ISSUE THREAD

**Issue by wendingp** [nondanee/UnblockNeteaseMusic#154]
mac 客户端

每日推荐歌单里如果有音乐包歌曲就播放不了 点播放提示要购买音乐包

但是搜索同一首歌或者在其他页面就可以播放

**Comment by nondanee** [comment]
？？？日推还会推荐付费歌曲的吗
这么智熄的操作

macOS 客户端版本号是多少？

**Comment by wendingp** [comment]
最新的, 2.1.0 build:782

难道我听付费太多了推荐系统我是 rmb 玩家了??? 23333

**Comment by nondanee** [comment]
好的我看看

**Comment by GoldenMean58** [comment]
Linux平台出现同样问题

**Comment by nondanee** [comment]
因为推荐是随机的我不太好测，麻烦你们测一下哈，应该是修复了

**Comment by wendingp** [comment]
@nondanee 好像还是不行 我这次又是日推最后一首要音乐包 还是听不了

看你改的是 radio, 可能日推跟电台不一样?

**Comment by nondanee** [comment]
@wendingp 
哦哦是我弄错了，你在试下，麻烦了 😂
