### ISSUE TITLE
分享一个PAC，看资料写了一个。

### ISSUE THREAD

**Issue by X-Crack** [nondanee/UnblockNeteaseMusic#156]
var direct = "DIRECT;";

var wall_proxy = function(){ return "PROXY 127.0.0.1:9090; direct"; };

function FindProxyForURL(url, host) {
	if(dnsDomainIs(host, ".163.com") || dnsDomainIs(host, ".126.net")) {
		if(dnsDomainIs(host, ".music.163.com") || dnsDomainIs(host, ".music.126.net")) {
			return wall_proxy();
		}
	}
	return direct;
}

参考地址1：http://technet.microsoft.com/zh-cn/library/cc985335.aspx#BKMK_Ex1
参考地址2：https://docs.oracle.com/cd/E19438-01/820-6317/adyrs/index.html

参考2讲解的比较详细。

这个pac不会代理视频资源，视频资源是直连的。

**Comment by nondanee** [comment]
？？？没懂你的意思

**Comment by X-Crack** [comment]
windows 用的，设置pac文件，然后代理指定IP呀。

**Comment by nondanee** [comment]
我滴妈，自带 PAC 你不知道吗？

**Comment by X-Crack** [comment]
哪里有啊。

**Comment by nondanee** [comment]
https://github.com/nondanee/UnblockNeteaseMusic#方法-2-设置代理
> PAC 自动代理脚本地址 `http://<Server Name:PORT>/proxy.pac`

**Comment by X-Crack** [comment]
行吧。我没有看到程序目录中含有pac文件，所以就自己搞了一个。
