### ISSUE TITLE
关于安卓端的使用

### ISSUE THREAD

**Issue by auntspock** [nondanee/UnblockNeteaseMusic#157]
大大，目前在win端网易能正常使用了，但是关于如何调整音源搜索顺序和安卓端的使用始终不知如何设置：
1、调整音源的搜索顺序：是重新执行一遍node app.js XXXX命令行还是在某个配置文件里面手动修改？
2、安卓端的使用：看教程是在 WLAN > 修改网络 > 高级选项 > 代理 中设置，是在下图中填写吗？我已填写并保存，但是无法选中该wifi。
<img src='http://i1.fuimg.com/694677/4e9b81dc76f613ca.jpg'>
不知为何图片显示不完整，只有贴个外链了，麻烦大大手动点击查看。
http://i1.fuimg.com/694677/4e9b81dc76f613ca.jpg

查了下，是不是需要另外装代理软件配合使用，比如ssr吗，但是ssr需要设置账户和密码才能连接，而我装有UNM的centos7服务器里面没有看到设置密码的地方。还请大大指路，谢谢

**Comment by nondanee** [comment]
Q: 如何调整音源搜索顺序
A: `-o` 后面的就是顺序啊，你不是已经会改了吗？用 supervisord 的话就改配置文件 `command=...`
![](https://camo.githubusercontent.com/3fb38a2ffb56a708c50a86272f98934134f0febe/687474703a2f2f69322e7469696d672e636f6d2f3639343637372f343137373138363134306239623066332e6a7067)

Q: 安卓端的使用始终不知如何设置
A: 是这个位置。无法选中是什么意思？
不需要另装代理软件，设置 WLAN 代理就能用了

**Comment by auntspock** [comment]
Q1，对，大大，我确实会用-o参数，但是如上图所示，我重新输入一次node app.js XXX -o XXX 就会出现上图中16070端口被占用的提示。所以，如果我要修改音源顺序的话，要么node app.js -p 其他端口号，要么在supervisord的配置文件里面如下修改对吧

[supervisord]
nodaemon=false

[program:netease]
user=root
directory=/opt/UnblockNeteaseMusic
command=/usr/bin/node app.js -s -p 16070 -o kugou qq xiami XXXX 
autostart=true
autorestart=true

**Comment by nondanee** [comment]
对的

**Comment by auntspock** [comment]
Q2，安卓端设置如下
<img src='http://i1.fuimg.com/694677/d78d1d46e1a53afb.jpg'>

<img src='http://i1.fuimg.com/694677/0031bf5f3f01af5e.jpg'>

<img src='http://i1.fuimg.com/694677/bd312c92778b0357.jpg'>

图1表示设置完成（ssid名为test），图2表示保存完成，图3表示wlan列表搜不到名为test的wifi，请大大过目，谢谢

**Comment by nondanee** [comment]
已连接的那个长按，修改网络，填代理

**Comment by auntspock** [comment]
果然。泪奔。能用了。非常感谢大大！！
Q3，只有手机端处于wifi情况下才能使用本程序对吗。
Q4，如果我同时开梯子，是不是会影响本程序使用

**Comment by nondanee** [comment]
Q3，移动数据下可以修改 APN
Q4，应该会有影响

**Comment by auntspock** [comment]
Q4，已测试安卓端，挂了梯子的情况下网易客户端就无法加载了。
Q3，没有在手机内找到APN选项，只找到VPN选项并设置如下并提示如下
<img src='http://i1.fuimg.com/694677/86bd3c93f4418a23.jpg'>

<img src='http://i1.fuimg.com/694677/1bdba716f45088fa.jpg'>

<img src='http://i1.fuimg.com/694677/a6ef733435ebeea3.jpg'>

**Comment by auntspock** [comment]
Q4，输入图7中设置的密码后，点击连接，提示失败，如图8所示
<img src='http://i1.fuimg.com/694677/69b2a46f4b9a3f53.jpg'>

**Comment by nondanee** [comment]
不是 VPN 啊
就叫 APN (接入点名称)，网上搜一下 "APN 设置" 应该有的

**Comment by auntspock** [comment]
嗯，是的大大，刚刚是我理解错了，已删回复，现在在查APN

**Comment by auntspock** [comment]
Q3，已在安卓端4G流情况下量测试成功。不过，如果是先切换APN再登陆网易，会在登陆时有下图的提示。所以我是先登陆网易账号再去切换APN，不过切换之后，qq可以通信，但浏览器无法访问百度等网站。这样操作对吗，大大
<img src='http://i2.tiimg.com/694677/e4bf77902701f81d.jpg'>

**Comment by nondanee** [comment]
是的，登录 API 强制 https 无法降级，所以无法登录，可以装证书解决 （登录一次就行了啊，低频操作）

我试了下 chrome、via、夸克，以及 QQ 和微信内置浏览器（X5）都没问题（局域网环境）
如果是用境外服务器，可能会是 GFW 的问题
也可能是手机系统的问题或者 webview 版本的问题？不清楚

WLAN 代理那里把 “手动” 改成 "代理自动配置"，填地址 `http://<Server Name:PORT>/proxy.pac`
（APN 没法用 PAC）

**Comment by auntspock** [comment]
噢噢，降级，虽然不懂，但是感觉很厉害。证书，我稍后去其他issue查一下。
对，代理服务器是日本的，我还以为本程序只能装在境外，特意去搞了个，囧，那我还是搞个国内的吧，然后测试一下再来回复大大。
原来是在wlan设置pac模式，我试试。
Q5，PAC的意思是指仅使用代理IP访问网易云客户端，使用真实IP访问其他网站和app吗

**Comment by auntspock** [comment]
已在安卓端的wlan设置为pac模式，目前能正常访问百度等国内网址了，大大威武。

**Comment by nondanee** [comment]
装在哪里没有要求（因为是 http 代理，很容易被墙检测到）
Q5，可以这么理解
