### ISSUE TITLE
ios在局域网的使用办法?

### ISSUE THREAD

**Issue by shzxm** [nondanee/UnblockNeteaseMusic#159]
找了一圈都是ios通过nginx使用的
不知道有没办法在同一局域网下
ios通过代理来实现解锁?
我已经试过了直接在wifi设置里边设置代理   无效
也试过了使用shadowrocket新增http加规则     无效.
证书也安装了.也信任了.
都是同样的
歌曲没有解锁.也不能听
![image](https://user-images.githubusercontent.com/9905297/61787843-3bc02200-ae43-11e9-9148-a4228ed04417.png)

**Comment by nondanee** [comment]
没说要用 nginx 啊？
装证书以后 `-p` 设了双端口吗？没有的话去试试（我猜测没有）
我没有设备，之前别人说最新版无效了，我也不知道真的假的

**Comment by shzxm** [comment]
双端口怎么设置，我用的1066:443
第二个端口用什么？
我是挂在电脑上的

**Comment by nondanee** [comment]
你已经设置过了啊，那我就不知道了
随便用什么端口都行

你手动把日志里面这几个 59 开头的 IP 
```
59.111.21.14
59.111.21.13
59.111.179.214
```
加到 hook host 里试试看
https://github.com/nondanee/UnblockNeteaseMusic/blob/e7af784917b2e9da9535cbd245a3b2d9397a9ce2/hook.js#L21-L31

**Comment by shzxm** [comment]
> 你已经设置过了啊，我那就不知道了
> 随便什么用都端口行
> 
> 你手动把日志里面这几个59开头的IP
> 
> ```
> 59.111.21.14
> 59.111.21.13
> 59.111.179.214
> ```
> 
> 加到hook host里试试看
> https://github.com/nondanee/UnblockNeteaseMusic/blob/e7af784917b2e9da9535cbd245a3b2d9397a9ce2/hook.js#L21-L31

我去试一下.

**Comment by shzxm** [comment]
![image](https://user-images.githubusercontent.com/9905297/61790487-e9363400-ae49-11e9-81af-65a0ceffdf94.png)
变成这样了....

**Comment by nondanee** [comment]
应该可以了吧？

**Comment by shzxm** [comment]
> 应该可以了吧？

不行.....还是不能解锁.显示无版权,.还是灰色

**Comment by nondanee** [comment]
那你去 #137 问问吧，没办法=.=
