### ISSUE TITLE
《纸短情长》播放不了

### ISSUE THREAD

**Issue by name327** [nondanee/UnblockNeteaseMusic#160]
使用程序版本：0.16.0
网易云音乐版本 ：2.5.3（Build:197682）
问题：播放歌曲 《纸短情长》 会提示加载失败，但是查看程序后台日志，发现输出
MITM > music.163.com 
[557581284] 纸短情长
http://isure.stream.qqmusic.qq.com/M500001IDhBO2bow8j.mp3?vkey=AD7EF202B929F895D15287F57306145FE32A43F0BD72241907474D6494E1D789EBAE2EAC8AB3CC45B27E2E13E34E4DAC951338BAF83044A1&uin=0&fromtag=8&guid=7332953645
并且该url 可以正常播放

**Comment by nondanee** [comment]
我的版本是 2.5.4 (Build:197709)
试了下可以播放啊

![image](https://user-images.githubusercontent.com/26399680/61929286-878eda80-afad-11e9-8673-7861e9d04ed0.png)
