### ISSUE TITLE
好几首歌，能匹配到，但是播放不了

### ISSUE THREAD

**Issue by QCEnjoyLL** [nondanee/UnblockNeteaseMusic#161]
程序用的最新版0.16.3
客户端版本2.5.4（Build：197709）
直接播放不了，但是日志输出的音源能直接播放哎
像这几首都不行
[186001] 七里香
[http://isure.stream.qqmusic.qq.com/M500004Z8Ihr0JIu5s.mp3?vkey=ED94CB51963EA6A18BA28BD59F0B2D5B029763CCDA377A7EFBC6EBBD355098C4E5DED5F19D5E0697FD8F36476D6A40C7EB798CD07EF3215E&uin=0&fromtag=8&guid=7332953645](http://isure.stream.qqmusic.qq.com/M500004Z8Ihr0JIu5s.mp3?vkey=ED94CB51963EA6A18BA28BD59F0B2D5B029763CCDA377A7EFBC6EBBD355098C4E5DED5F19D5E0697FD8F36476D6A40C7EB798CD07EF3215E&uin=0&fromtag=8&guid=7332953645)

MITM > interface.music.163.com 
[186003] 外婆
[http://isure.stream.qqmusic.qq.com/M5000027gHes1HjRNe.mp3?vkey=ED94CB51963EA6A18BA28BD59F0B2D5B029763CCDA377A7EFBC6EBBD355098C4E5DED5F19D5E0697FD8F36476D6A40C7EB798CD07EF3215E&uin=0&fromtag=8&guid=7332953645](http://isure.stream.qqmusic.qq.com/M5000027gHes1HjRNe.mp3?vkey=ED94CB51963EA6A18BA28BD59F0B2D5B029763CCDA377A7EFBC6EBBD355098C4E5DED5F19D5E0697FD8F36476D6A40C7EB798CD07EF3215E&uin=0&fromtag=8&guid=7332953645)
MITM > isure.stream.qqmusic.qq.com

MITM > interface.music.163.com
[186011] 断了的弦
[http://isure.stream.qqmusic.qq.com/M500003ZdxP61ClQZ5.mp3?vkey=ED94CB51963EA6A18BA28BD59F0B2D5B029763CCDA377A7EFBC6EBBD355098C4E5DED5F19D5E0697FD8F36476D6A40C7EB798CD07EF3215E&uin=0&fromtag=8&guid=7332953645](http://isure.stream.qqmusic.qq.com/M500003ZdxP61ClQZ5.mp3?vkey=ED94CB51963EA6A18BA28BD59F0B2D5B029763CCDA377A7EFBC6EBBD355098C4E5DED5F19D5E0697FD8F36476D6A40C7EB798CD07EF3215E&uin=0&fromtag=8&guid=7332953645)

**Comment by nondanee** [comment]
你改了 `-o` 参数吗？
我看了下用默认参数会 pending，网易旧链有问题，匹配会卡住
用 `-o qq` 可以播放吗？

**Comment by QCEnjoyLL** [comment]
之前是默认的，不过照你说的改成-o qq后，可以了，不过这样改了过后是只匹配qq音源还是优先匹配呢？

**Comment by nondanee** [comment]
是的，改了以后只匹配 qq 的音源
默认配置里的网易云旧链有点问题，把 Promise 卡住了...

**Comment by QCEnjoyLL** [comment]
需要其他的加在qq后边就可以了吧

**Comment by nondanee** [comment]
嗯，排在前面的优先
