### ISSUE TITLE
ios12.4下载安装了证书，但是不能验证信任，是有问题还是本来就这样

### ISSUE THREAD

**Issue by banjuzaijian** [nondanee/UnblockNeteaseMusic#163]

**Comment by nondanee** [comment]
你截个图

**Comment by banjuzaijian** [comment]
> 你截个图

![IMG_0487](https://user-images.githubusercontent.com/46417352/62050109-3e57b880-b243-11e9-8499-488bac192c74.PNG)
![IMG_0488](https://user-images.githubusercontent.com/46417352/62050117-41eb3f80-b243-11e9-8565-62fffcaa0dbb.PNG)

**Comment by nondanee** [comment]
装 CA 证书啊哥哥
你这个是服务器证书……

**Comment by banjuzaijian** [comment]
好的.........
