### ISSUE TITLE
能同时实现y2b,google（fq）和解锁云音乐吗？

### ISSUE THREAD

**Issue by aff2018** [nondanee/UnblockNeteaseMusic#165]
能同时实现看y2b,google等（fq）和解锁云音乐吗？
在同一个vps上，同IP，同一个端口实现上述两种功能？也就是说不用切换节点！

刷了好久issues，没看到
用ss或V2ray
请教如何实现？
谢谢

**Comment by nondanee** [comment]
部署在海外的话，除了 QQ 和咪咕，其它音源都不能用的（在东南亚的话，joox 可以用）

用 v2ray 的 https://github.com/nondanee/UnblockNeteaseMusic/issues/148
转换成 ss 的 https://github.com/nondanee/UnblockNeteaseMusic/issues/162#issuecomment-515982523
用 iptables 的 https://github.com/nondanee/UnblockNeteaseMusic/issues/58#issuecomment-487346706

**Comment by aff2018** [comment]
用了#162的方法，客户端用了全局，可以，谢谢。
网易云音乐不知道要加哪些规则进去？

Nzix <notifications@github.com>于2019年7月30日 周二13:49写道：

**Comment by nondanee** [comment]
规则在 PAC 里，不过可能用不了，参见 👉  #162

**Comment by aff2018** [comment]
kitsunebi 中处理，好简单：
开启日志，运行网易云音乐，看日志，添加了两条


Nzix <notifications@github.com>于2019年7月30日 周二17:18写道：

**Comment by nondanee** [comment]
好的👌
