### ISSUE TITLE
让大家去信任一个完全公开的证书是很危险的

### ISSUE THREAD

**Issue by ITJesse** [nondanee/UnblockNeteaseMusic#166]
我发现你在项目中公开了默认使用的证书，包含 CA证书，以及私钥。如果大家都去信任这个 CA，在其被恶意利用后会导致严重的后果。

此处提议：
1. 默认不提供证书，需要使用 https 功能的用户自行生成证书
2. 提供默认证书，但是在首次运行时给用户明确的安全提示

**Comment by nondanee** [comment]
谢谢

不过
默认配置不开启 https 监听

README 里写的是 "需要自签证书"，而不是 "需要开启 https 监听"
README 里也没有教如何开启 https 监听

开启 https 端口都是用户主动打开的，默认都看过 #48，#65 及相关讨论
(至于别的教程，都不是我写的，我也管不了)

对于最新的 Windows 和 Android 客户端这个证书已经没有用了 (构不成威胁)
UWP 一直没更新还是用 http 接口 (没有影响)
linux 客户端需要自己加 ignore flags (用户自主)
macOS 客户端和浏览器或许还有用

**CA 私钥并没有公开，要作恶的话，只会是我作恶了......**

相比之下，还是那些部署代理公开分享给别人的比较危险

**Comment by nondanee** [comment]
已在 https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-477870013 添加说明

**Comment by ITJesse** [comment]
建议将 #48 直接链接到自签证书的地放。

然后 docker 部署的地方可以添加下这条命令：
`docker run -v server.crt:/usr/app/src/server.crt -v server.key:/usr/app/src/server.key nondanee/unblockneteasemusic --port 8080:8081`

**Comment by ITJesse** [comment]
谢谢，那我就关闭 issue 了。
