### ISSUE TITLE
docker安装无法正常使用

### ISSUE THREAD

**Issue by qiuzi** [nondanee/UnblockNeteaseMusic#167]
`
HTTP服务器正在运行@ http://0.0.0.0:8080

TUNNEL  -  music.163.com:443

TUNNEL  -  music.163.com:443

TUNNEL  -  music.163.com:443

TUNNEL  -  music.163.com:443

`
使用http代理方式无法打开
具体如何使用？docker也无法修改参数

**Comment by nondanee** [comment]
docker 为啥无法修改参数？？？

> 支持 Windows 客户端，UWP 客户端，Linux 客户端 (1.2 版本以上需要自签证书 MITM，启动客户端需要增加 --ignore-certificate-errors 参数)，macOS 客户端 (726 版本以上需要自签证书)，iOS 客户端 (配置 https endpoint 或使用自签证书)，Android 客户端和网页版 (需要自签证书，需要脚本配合)

网页版这样打不开很正常，pin 着 3 个 issue
