### ISSUE TITLE
大佬，有个问题又要麻烦你了：搭建好后，用个2-3小时，网络就变慢了，不知道什么情况

### ISSUE THREAD

**Issue by aff2018** [nondanee/UnblockNeteaseMusic#168]
用阿里云新手2.0，2.5刀sgp，512M内存，做的
系统debian9
用的这个方法搞成一个新的$$进行连接的
https://www.lajiblog.com/index.php/archives/4/
起初，测速正常的30M
用个2小时左右，可能更短，测速发现变成15M左右了
然后用原来的$$，进行测试，发现速度也变15M左右了
重启系统
测试又变回30M了。
反复试过，还是这样。

不知道是什么情况？
不知道有其他人遇到过这样的情况吗？

**Comment by Yansongsongsong** [comment]
🤔插菊花 你这样真的可以吗
我按照这个方法设置了$$之后 android现实 connect fail 然后并没办法解锁🤔

**Comment by aff2018** [comment]
确定可以。只是有我遇到的vps上网络带宽突然变小了，还没解决

**Comment by Yansongsongsong** [comment]
soga  我测试一下

**Comment by iDesperad0** [comment]
我觉得如果你转换成ss服务且可用的话，那么大佬这边的工作已经结束了吧，剩下的你应该要从goproxy上面排查了吧😂

**Comment by aff2018** [comment]
搞不懂。刚又试了一下，用了十分钟左右，速度又变成18M左右。
重启vps，又恢复30M，没办法了。

Panini <notifications@github.com>于2019年7月31日 周三16:58写道：

**Comment by iDesperad0** [comment]
@aff2018 另外，有个疑问请教一下，你客户端是怎么使用这个转换后的ss服务的？

**Comment by aff2018** [comment]
$$客户端呀

Panini <notifications@github.com>于2019年7月31日 周三17:18写道：

**Comment by iDesperad0** [comment]
@aff2018 
......我当然知道是ss客户端，具体是哪个呢？
我的意思是科学上网和音乐这两个ss代理是怎么同时运行的。手动切换还是用的类surge等规则代理应用？

**Comment by aff2018** [comment]
不切了，直接用goproxy 生成的$$节点，同时具备这两功能

Panini <notifications@github.com>于2019年7月31日 周三17:23写道：

**Comment by iDesperad0** [comment]
这样啊，了解了，没仔细看那个教程，原来是合二为一了
然后客户端把云音乐设置走ss服务就好了吧
另外，你说的带宽下降问题，估计就是goproxy的事儿，你可以试试关了goproxy，直连原先的ss服务看看带宽是否下降呢。

**Comment by aff2018** [comment]
我原先的，用着没事。但使用新的goproxy生成的$$后。再用原先的，同样带宽下来了。重启vps后立马恢复。

Panini <notifications@github.com>于2019年7月31日 周三17:44写道：

**Comment by aff2018** [comment]
试了先关goproxy ，测速没恢复。又试了关node app.js，再测速，速度恢复。

bwh 123 <aff201805@gmail.com>于2019年7月31日 周三17:48写道：

**Comment by nondanee** [comment]
可以监控进出口流量啊，像 iftop 之类的，你自己查查呗
或者你看看 node app.js 的日志都在请求什么网址

代理开在什么端口？此端口安全组（防火墙）有没有开
感觉是代理端口被扫到，然后别人偷去爬数据了...

**Comment by aff2018** [comment]
应该不是被扫到偷用。我现在开着，但没去用它。还是用的老$$，测速30M，只要一用新的$$,立马变16-18M(这时，用老的$$,速度也是16-18M),直到停止app.js，再用老$$，速度恢复30M

Nzix <notifications@github.com>于2019年7月31日 周三19:38写道：

**Comment by nondanee** [comment]
你的意思是只要一用这个代理就会掉咯？
那用 WLAN 代理试试呗。。。
看看再用旧的 SS 会不会掉到 30M

**Comment by aff2018** [comment]
WLAN代理是什么🤔？试试去

Nzix <notifications@github.com>于2019年7月31日 周三19:50写道：

**Comment by nondanee** [comment]
WIFI 那里设 http 代理啊 =.=

**Comment by aff2018** [comment]
好吧，明白了

Nzix <notifications@github.com>于2019年7月31日 周三19:52写道：

**Comment by aff2018** [comment]
试了wlan连接方式。再测又掉了。停了app.js服务，恢复正常了

bwh 123 <aff201805@gmail.com>于2019年7月31日 周三19:53写道：

**Comment by nondanee** [comment]
@aff2018 
你用什么测的速啊，speedtest 网页版？测速节点选哪里？

**Comment by aff2018** [comment]
直接用fast app试的。反正用这unblockmusic节点，没法上外网。不点具体听歌的话，可以上外网，只要一听过。再上外网就没速度了。

Nzix <notifications@github.com>于2019年8月4日 周日17:29写道：

**Comment by nondanee** [comment]
@aff2018 
麻烦用 speedtest.net 再测一下谢谢

http 代理明文的，sni 信息会泄露，不要用来上外网，被封端口也有可能

**Comment by aff2018** [comment]
这两天在外旅行的。过两天回家再试。要说被封端口的话我停了这docker:docker stop
unblockmusick。用我老的$$连，测试，速度就回来了。大佬能不能解决这问题：同一节点端口既解决听歌又解决上外网。

Nzix <notifications@github.com>于2019年8月4日 周日17:41写道：

**Comment by nondanee** [comment]
emmm 我没说清楚
有用 goproxy 转换就没关系的
裸连 http 代理 (WLAN / APN 代理) 会被封

**Comment by aff2018** [comment]
我用goproxy 转了的。你能复现这问题吗？

Nzix <notifications@github.com>于2019年8月4日 周日17:54写道：

**Comment by nondanee** [comment]
用阿里云轻量云 hk 试了下
```
cloudiplc                                                                                aliyun
speedtest-cli <-http-> privoxy <-socks5-> ss-local <-ss-> ss-server
speedtest-cli <-http-> privoxy <-socks5-> ss-local <-ss-> goproxy <-http-> unblockneteasemusic
speedtest-cli                             <-http->                                                          unblockneteasemusic
```

**Comment by nondanee** [comment]
那你试一下 goproxy + privoxy 这样的速度吧
privoxy 是老牌的 http 代理了

测三组
ss-server
goproxy + privoxy
goproxy + unblockneteasemusic
