### ISSUE TITLE
提升音质可能吗？

### ISSUE THREAD

**Issue by koolca** [nondanee/UnblockNeteaseMusic#169]
大佬，能判断网易是低音质（比如128kb）版本，当作灰色歌曲一样来替换源吗？

**Comment by nondanee** [comment]
能啊，判一下 `br` 就行了

替换的音源码率也不一定比 128k 高啊

**Comment by iDesperad0** [comment]
建议使用- o 把酷我放到首位，320kb太爽了，QQ的音源作者已经折腾好几次了，腾讯封的贼快。

**Comment by koolca** [comment]
谢谢大佬回复。
因为不懂这个nodejs语言，不断尝试之下，找到了可能修改的地方。改好之后，优先酷我，下载的码率128-320都有，不算完美，但也有改进

**Comment by iDesperad0** [comment]
@koolca 
酷我酷狗和QQ同属腾讯，曲库会有共享，少部分独家没有的也有QQ殿后，总比只有QQ一个音源（128kb/s）强哈

**Comment by koolca** [comment]
@iDesperad0 嗯嗯，现在至少比网易云的满屏128kbps好一些

**Comment by nondanee** [comment]
网易云满屏 128k 吗？？？我怎么没发现
是不是花钱就能解决？？？那充个黑胶吧

**Comment by iDesperad0** [comment]
@nondanee 也可能他的歌单里全是周杰伦或者摩登天空厂牌的歌吧😂

**Comment by shugo-chara** [comment]
@nondanee 我也注意到了。今天用宝塔部署在服务器上了，然后才注意到所有客户端上版权音质都是默认“极高音质”，更该为无损就会自动弹出一个打不开的vip支付窗口。我本身是年费黑椒，想问下有办法能默认改为无损音质吗。

**Comment by nondanee** [comment]
@shugo-chara 
我可以切换啊，Windows 和 Android 上都可以切
那你不用代理的时候应该能切换的吧？

中间加 `--`
```
pm2 start app.js -- -o  qq xiami baidu
```

**Comment by shugo-chara** [comment]
> @shugo-chara
> 我可以切换啊，Windows 和 Android 上都可以切
> 那你不用代理的时候应该能切换的吧？
> 
> 中间加 `--`
> 
> ```
> pm2 start app.js -- -o  qq xiami baidu
> ```

我是说在宝塔的pm2管理器里，没有办法直接添加 后缀命令，会提示非法。
![132](https://user-images.githubusercontent.com/20610965/62758010-158fb880-bab8-11e9-88c4-6c27ccef6380.png)
如果想改优先级的话不知道怎么改了。。

**Comment by nondanee** [comment]
@shugo-chara 

https://github.com/nondanee/UnblockNeteaseMusic/blob/0a69671f1595336dc17348a613c1409aefe3cfef/provider/match.js#L17

顺序这里改

这个位置切换音质我回去看看

**Comment by shugo-chara** [comment]
> @nondanee 
> 
> https://github.com/nondanee/UnblockNeteaseMusic/blob/0a69671f1595336dc17348a613c1409aefe3cfef/provider/match.js#L17
> 
> 顺序这里改
> 
> 这个位置切换音质我回去看看

3q~~我改下试试。

**Comment by nondanee** [comment]
@shugo-chara 
切换音质的问题在 https://github.com/nondanee/UnblockNeteaseMusic/issues/178#issuecomment-522259284 回复你了，你去看一下

- 播放页的音质在交互上不是默认音质而是实际音质（但做了匹配的歌音质显示不准确）
- 匹配播放的歌不能切换音质
