### ISSUE TITLE
一个导致不能下载并且血崩的错误

### ISSUE THREAD

**Issue by lxlsproblem** [nondanee/UnblockNeteaseMusic#17]
作者大大，今天在下载歌曲的时候弹出了一个错误，在某些特定歌曲必定会出现，出现问题后后面所有的歌曲都会因为网络错误无法下载。
请问这个有办法解决吗？
![snipaste_2018-09-15_15-40-33](https://user-images.githubusercontent.com/43290316/45583916-2ada8200-b8fd-11e8-9dc1-d77072c4cb69.png)
![snipaste_2018-09-15_15-40-51](https://user-images.githubusercontent.com/43290316/45583920-36c64400-b8fd-11e8-8290-fcb562591148.png)

**Comment by nondanee** [comment]
应该是有文件下载中断网了？读文件大小的时候报了0，start(0)比end(0-1)小了
改了一下，你试试看吧。我试了下载stay with me就没遇到这个问题😂

**Comment by nondanee** [comment]
修改了下载逻辑，已经不用预下载了，也不会有这个问题了

**Comment by alienzj** [comment]
![图片](https://user-images.githubusercontent.com/8847420/54483778-811c8380-4894-11e9-92d2-16a8607430ba.png)
@nondanee Nzix小哥，不能下载周董的歌
