### ISSUE TITLE
https的问题

### ISSUE THREAD

**Issue by koolca** [nondanee/UnblockNeteaseMusic#170]
还有个棘手的问题好像无法解决，求助大佬
先说说我的搭建环境吧，我利用本地linux服务器搭建了unblockneteasemusic，开通80端口，然后路由器将两个music.163.com劫持到此服务器的ip。
现在win10 UWP测试正常，但安卓手机和网页都不能正常，我判断是443端口的问题。由于linux服务器还有nginx运行在443端口，于是利用ngnix将music.163.com域名proxy_pass http://127.0.0.1，证书已按进阶配置里生成，并配置给nginx了。
到此为止，android和网页仍然不能work，现象就是网页提示“music.163.com 将您重定向的次数过多”，node大量提示MITM > music.163.com

**Comment by koolca** [comment]
更新环境，unblockneteasemusic开通了-p 80:81，然后nginx劫持*.163.com为proxy_pass https://127.0.0.1:81，网页可以打开了，不过播放不了。。。我看log都能match上，但不播放。android app好像劫持无用，流量没有通过unblockneteasemusic，app版本为google play最新版

**Comment by nondanee** [comment]
如果你没装脚本的话，网页上大部分应该还是灰的吧？("我的歌单" 那里有效果)
网页的话可以看看 console 报错，network 日志之类的，麻烦提供一下

安卓的话 play 版最新 4.3.1
应该装了证书就可以用了
你试试把这几个 server name 都写 nginx 里面
https://github.com/nondanee/UnblockNeteaseMusic/blob/24caf3605ad085e1d6e2e3fd427befa312ef2904/hook.js#L21-L31

**Comment by koolca** [comment]
@nondanee 谢谢大佬深夜回复。今天晚些时候我试试

**Comment by koolca** [comment]
刚试了一遍网页播放效果，发现指定-e “https://music.163.com"之后可以正常播放，不加此参数不能播放，但log正常。大佬能详细解释一下这个endpoint用途吗？ @nondanee

**Comment by nondanee** [comment]
endpoint 的问题参考 #143

我看了下控制台是 fetch 跨域报错 (虽然报错了，但是过个几十秒还是可以播放的)

> OPTIONS https://isure.stream.qqmusic.qq.com/M5000039MnYb0qxYhV.mp3?vkey=CB606627B0CBE4E5A88820328261DB5E1EB2B1A2323F3AE11848D54C1D9D563D6B3124C7ED14971730692A8C3CF525B0D562835CA733B8DB&uin=0&fromtag=8&guid=7332953645 504 (Gateway Time-out)
> Access to fetch at 'https://isure.stream.qqmusic.qq.com/M5000039MnYb0qxYhV.mp3?vkey=CB606627B0CBE4E5A88820328261DB5E1EB2B1A2323F3AE11848D54C1D9D563D6B3124C7ED14971730692A8C3CF525B0D562835CA733B8DB&uin=0&fromtag=8&guid=7332953645' from origin 'https://music.163.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

加了 endpoint  以后就不跨域了

**Comment by koolca** [comment]
谢谢 @nondanee 
网页播放能解决，然而通过劫持上面这些域名，安卓app仍然无法正常播放，要么打不开，要么越过Unblock了，证书已导入。以后还是用UWP播放下载吧。

**Comment by nondanee** [comment]
👌
