### ISSUE TITLE
音源音乐错误反馈。。。

### ISSUE THREAD

**Issue by 815169876** [nondanee/UnblockNeteaseMusic#171]
周杰伦的《不该》……音乐错误

**Comment by iDesperad0** [comment]
我这里杰伦的《不该》匹配没有问题，建议使用-o 把酷我酷狗音源放在QQ前面，完美匹配。

另外，匹配方法是取搜索结果的第一条，所以肯定会出现极少部分歌曲匹配错误的（譬如部分歌曲会匹配成live版），目前这个问题无法解决。

**Comment by nondanee** [comment]
没办法=.=

https://y.qq.com/portal/search.html#page=1&searchid=1&remoteplace=txt.yqq.top&t=song&w=不该(with%20aMEI)%20-%20周杰伦%20%2F%20张惠妹
的搜索结果排在第一是 《如果你也听说》
