### ISSUE TITLE
加载失败，代理连接可以正常打开

### ISSUE THREAD

**Issue by joh2254717** [nondanee/UnblockNeteaseMusic#172]
代理服务器正常，解析的连接可以打开，windows客户端报加载失败。
![failed](https://user-images.githubusercontent.com/23419458/62440296-1061ff00-b782-11e9-8664-940f4534fee3.png)

**Comment by joh2254717** [comment]
是因为部署在海外的缘故么

**Comment by nondanee** [comment]
我可以用啊
应该没关系
有没有加 `-s` ？

**Comment by joh2254717** [comment]
![cang](https://user-images.githubusercontent.com/23419458/62444950-96397680-b791-11e9-9bff-5010ed591817.png)
![uni](https://user-images.githubusercontent.com/23419458/62444955-98033a00-b791-11e9-9516-a67e63e55d38.png)
![ver](https://user-images.githubusercontent.com/23419458/62444956-99ccfd80-b791-11e9-8ce9-995b4f204f50.png)


![s](https://user-images.githubusercontent.com/23419458/62444943-90439580-b791-11e9-84f3-32113a2b79ea.png)
![ins](https://user-images.githubusercontent.com/23419458/62444944-920d5900-b791-11e9-9b2d-3defbc774053.png)


目前是加了-s的，这两首歌是我这测试播放不了的，以及服务端的截图，客户端的版本这些。
不清楚是海外服务器的原因还是客户端版本的原因。

**Comment by nondanee** [comment]
原因是有 `-s`
insure.stream.qqmusic.com 的请求会被 block
加上 `-e http://music.163.com` 就行了

**Comment by joh2254717** [comment]
好的，我去试下。

**Comment by joh2254717** [comment]
感谢，可以了。
麻烦问下 -e  参数只用加 http://music.163.com 就可以了么 ，不太明白作用。
另问，国外部署是否需要架设国内中继呢，感谢。

**Comment by nondanee** [comment]
关于 `-e` 的作用参考 👉  #143 
中继的话看你需要，如果只用 QQ 音源听个响的话就不用中继了

**Comment by joh2254717** [comment]
好的，感谢。
我干脆直接把服务端放国内得了 😄

**Comment by nondanee** [comment]
👌

**Comment by Zhujion** [comment]
> 👌

弱弱的问下 你们说的-e 是这个意思吗node app.js -e http://music.163.com

**Comment by nondanee** [comment]
@Zhujion 
是

你加了 `-s` 吗？加了的话还需要 ` -e http://music.163.com`，没加的话不需要

**Comment by Zhujion** [comment]
没有加-s  直接在app.js中修改端口，然后直接node app.js 运行，音源链接可以播放，但是window 网易云音乐客户端 显示加载失败

**Comment by Zhujion** [comment]
> @Zhujion
> 是
> 
> 你加了 `-s` 吗？加了的话还需要 ` -e http://music.163.com`，没加的话不需要

没有加-s 直接在app.js中修改端口，然后直接node app.js 运行，音源链接可以播放，但是window 网易云音乐客户端 显示加载失败

**Comment by nondanee** [comment]
@Zhujion 
那可能是你的设置问题吧？我试了下可以啊 =.=

**Comment by Zhujion** [comment]
> @Zhujion
> 那可能是你的设置问题吧？我试了下可以啊 =.=

大佬 牛批 我知道原因了。。 原因是网易云客户端填写ip的时候 复制过去的。前面多个空格。
大佬 66666

**Comment by Zhujion** [comment]
> @Zhujion
> 是
> 
> 你加了 `-s` 吗？加了的话还需要 ` -e http://music.163.com`，没加的话不需要

大佬 ios 手机端 用代理 播放不了 - -！
您看看
[185906] 发如雪
http://aqqmusic.tc.qq.com/amobile.music.tc.qq.com/M5000027oMO61wWi55.mp3?vkey=FA1504A5CA3FA14C6D14A3A36526F2A0455D78A28AC7820853A24CC955199BBA7F6FE1858D60B796133CC1F21B2A1E3C187CFEBB5199E37D&uin=0&fromtag=8&guid=7332953645
TUNNEL > aqqmusic.tc.qq.com:80
TUNNEL > localhost:9999
MITM > interface3.music.163.com 
TUNNEL > aqqmusic.tc.qq.com:443
TUNNEL > localhost:9999
MITM > music.163.com 
TUNNEL > aqqmusic.tc.qq.com:443
TUNNEL > aqqmusic.tc.qq.com:443
TUNNEL > localhost:9999
MITM > music.163.com

**Comment by nondanee** [comment]
@Zhujion 
参考这个 👉 https://github.com/nondanee/UnblockNeteaseMusic/issues/65#issuecomment-493718439
