### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by maxzhang666** [nondanee/UnblockNeteaseMusic#173]
之前正常更新了之后在运行报了
Object.values is not a function

难道我node版本问题么？

```
TypeError: Object.values is not a function
    at require.then.then.jsonBody (/root/UnblockNeteaseMusic/app.js:71:173)
    at process._tickCallback (internal/process/next_tick.js:109:7)

```

**Comment by nondanee** [comment]
我的问题
查了下要 node 7+
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/values

我等下改
你先升级吧
现在 lts 是 11

**Comment by maxzhang666** [comment]
这么巧，我刚换了台服务器部署也发现node版本问题了
23333、

**Comment by nondanee** [comment]
应该可以了

**Comment by maxzhang666** [comment]
感谢，我更新了node版本也ok了
