### ISSUE TITLE
依照方法3配置成功后无法使用

### ISSUE THREAD

**Issue by LoongCatChina** [nondanee/UnblockNeteaseMusic#176]
>  可以确认配置方法完全正确，照理应该已经生效。
> 但是打开云音乐却提示“网络不给力”，求解？
> 已解决，Windows 10的代理设置中需要取消对于本地服务器不使用代理服务器的设置。

**但是Android设置后网易云仍然无法联网？Xperia XZ Premium**

**Comment by nondanee** [comment]
方法 3 是哪个啊？README 里的方法 3 是调接口啊

**Comment by nondanee** [comment]
你说的 Windows 10 设置是这个？

![image](https://user-images.githubusercontent.com/26399680/62918031-0454ed80-bdd1-11e9-9479-aa92d52bed12.png)

不需要取消啊！

**Comment by LoongCatChina** [comment]
> 方法 3 是哪个啊？README 里的方法 3 是调接口啊

电脑上我是按照方法3弄好的，然后手机上我直接按照方法2填入了地址和端口无法使用，估计是我打开方式不对，求教。

**Comment by nondanee** [comment]
方法 3 是哪个啊 😂 
这个吗？https://github.com/nondanee/UnblockNeteaseMusic#方法-3-调用接口
还是你参考了别人的教程，麻烦贴一下

你地址填了啥，能不能截个图。如果网易云不能联网的话，其它 APP 能联网吗？
(P.S. issue 里面贴图，文件直接拖到输入框里就行了，仅限 PC 浏览器)

**Comment by LoongCatChina** [comment]
> 方法 3 是哪个啊 😂
> 这个吗？[https://github.com/nondanee/UnblockNeteaseMusic#方法-3-调用接口](https://github.com/nondanee/UnblockNeteaseMusic#%E6%96%B9%E6%B3%95-3-%E8%B0%83%E7%94%A8%E6%8E%A5%E5%8F%A3)
> 还是你参考了别人的教程，麻烦贴一下
> 
> 你地址填了啥，能不能截个图。如果网易云不能联网的话，其它 APP 能联网吗？
> (P.S. issue 里面贴图，文件直接拖到输入框里就行了，仅限 PC 浏览器)

我感觉是我错了，我直接在电脑上配置了可以用，手机直接在Wifi设置里面设置了http代理，所有app都无法联网

**Comment by nondanee** [comment]
我很好奇啊，你说的方法 3 到底是什么 =.=

**Comment by nondanee** [comment]
还有手机上 http 代理的地址你填的是什么

**Comment by LoongCatChina** [comment]
就是在电脑上“调用接口”？
手机上填写的是127.0.0.1：端口

**Comment by nondanee** [comment]
方法 3 是作为依赖给别的 node.js 应用提供的

手机上代理的地址填你电脑在局域网里的地址

**Comment by nondanee** [comment]
解决了吗？
