### ISSUE TITLE
有些歌會出現播放與實際不符的情況

### ISSUE THREAD

**Issue by jason5545** [nondanee/UnblockNeteaseMusic#18]
譬如說 選的歌是a 實際放出來的卻是b的情況 這個有辦法解決嗎...

**Comment by nondanee** [comment]
emmm暂时没办法
匹配策略比较难做，因为各个平台歌手歌曲名称可能不一样，直接用=肯定有很多匹配不成功

现在没有匹配策略，就直接取搜索结果第一个，所以如果平台给的搜索结果不准也没办法了

如果在国内的话默认三个源匹配的应该还算准吧

**Comment by jason5545** [comment]
'匹配算法確實麻煩 尤其我聽的外文歌比較多 就不太準了吧 大概
