### ISSUE TITLE
[-o] 参数指定音源的话，哪个音乐质量最好，怎么排序最优呢？

### ISSUE THREAD

**Issue by forodo** [nondanee/UnblockNeteaseMusic#181]
我看到 **-o** 可以指定的音乐有好几个**[qq xiami baidu kugou kuwo migu joox]**，但是不知道他们哪个更好用，怎么排序才是最优。
有木有清楚的说下呗~

**Comment by nondanee** [comment]
qq 只有 128k
xiami 你没加过 x5sec 应该是不能用的
joox 只能在港澳东南亚用

还有每家搜索精度不一样
有的对日文歌名搜索不太友好
有的对 live / 合唱搜索不太友好

你自己试试就行了

**Comment by forodo** [comment]
对了，我看还有一个 netease，这个是什么？
另外，如果所有音源都加上的话，是不是更占用资源？（但是相对电脑来说是不是还是很少？）

**Comment by nondanee** [comment]
netease 是网易云旧链
已经失效

会的，主要是耗时。资源的话还好吧
都加上也只会取匹配到的排在最前的那个
