### ISSUE TITLE
运行node出错

### ISSUE THREAD

**Issue by GeT1t** [nondanee/UnblockNeteaseMusic#183]
node app.js -p 8080

```
{ Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:636:8) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
```

**Comment by nondanee** [comment]
这肯定是你自己的问题啊
因为公司的证书吧？

**Comment by GeT1t** [comment]
公司的网络，这样有什么办法解决呢

**Comment by nondanee** [comment]
你查查 `NODE_TLS_REJECT_UNAUTHORIZED`

应该这样就行了 
```sh
export NODE_TLS_REJECT_UNAUTHORIZED=0
```

**Comment by GeT1t** [comment]
感谢，已经解决，在代码中添加了
```process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";```

**Comment by KarasuCvs** [comment]
> 感谢，已经解决，在代码中添加了
> 
> `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";`

你好, 请问这段代码应该添加在哪里?

**Comment by nondanee** [comment]
@KarasuCvs 
加在 app.js 第一行好了

**Comment by KarasuCvs** [comment]
> @KarasuCvs
> 加在 app.js 第一行好了
谢谢, 但是我加在第一行之后变成语法错误了.
C:\Windows\System32\UnblockNeteaseMusic>node app.js
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at read.then.body (C:\Windows\System32\UnblockNeteaseMusic\request.js:88:64)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by nondanee** [comment]
@KarasuCvs 
那可能是你公司的流量审查 ban 了你的请求
你可以浏览器试一下打不打得开这个地址
https://httpdns.n.netease.com/httpdns/v2/d?domain=music.163.com

**Comment by KarasuCvs** [comment]
@nondanee 
{
"msg": "OK",
"data": {
"music.163.com": {
"ttl": 300,
"ip": [
"103.126.92.132",
"103.126.92.133"
]
}
},
"code": 200
}
这是我打开后看到的内容. 我用的是家庭IPv6光纤.

**Comment by nondanee** [comment]
@KarasuCvs 
咦你家庭宽带也有证书问题吗？
那你在
https://github.com/nondanee/UnblockNeteaseMusic/blob/30ea1f9efc8ab4097cef73b67ccb986f2dcd6adc/app.js#L70
这行后面加上 `.catch(() => [])` 试试

**Comment by KarasuCvs** [comment]
@nodanee 
谢谢!!似乎正常运行了.
