### ISSUE TITLE
IOS播放失败

### ISSUE THREAD

**Issue by xesygao** [nondanee/UnblockNeteaseMusic#185]
最新版本的客户端好像是6.3。
shadowrocket配置以下规则：

> - USER-AGENT: NeteaseMusic*
> - DOMAIN-SUFFIX: 163.com
> - DOMAIN-SUFFIX: 126.net

灰色歌曲显示可用，但是播放失败，提示网络不给力。
查看日志已经成功匹配到音乐链接(我默认用的酷我)，怀疑是服务端开启了严格模式导致酷我的链接播放不了。但是我在shadowrocket把酷我设置成直连，不走代理，依然播放不了。
麻烦有经验的大佬指点下

**Comment by nondanee** [comment]
shadowrocket 能看 log 吗
你看看酷我的资源是不是请求了 https ？
酷我 win.web.ra01.sycdn.kuwo.cn 这个域名没有 https 的

**Comment by huaxinchan** [comment]
win的这个项目代理和安卓xp模块都失效了，貌似是网易云的API改了？

**Comment by nondanee** [comment]
@huaxinchan 
失效的证据呢？部分歌曲匹配不到很正常

**Comment by huaxinchan** [comment]
> @huaxinchan
> 失效的证据呢？部分歌曲匹配不到很正常

就拿周董的歌来说吧(Taylor的一样)，加载过的有缓存可以播放，没缓存的会加载失败，看服务端日志，QQ音乐的链接是解析出来了，复制到浏览器也可以正常播放，所以是什么问题呢？
[https://ws1.sinaimg.cn/large/006Xmmmgly1g66dnybx10j30o702aq2v.jpg](url)
[https://ws1.sinaimg.cn/large/006Xmmmgly1g66dnz7c1dj30qj0iaamn.jpg](url)
[https://ws3.sinaimg.cn/large/006Xmmmgly1g66do0c56dj31c20i0dux.jpg](url)

**Comment by nondanee** [comment]
@huaxinchan 
你是不是加了 `-s` ？

**Comment by huaxinchan** [comment]
> @huaxinchan
> 你是不是加了 `-s` ？

对，刚刚试了一下去掉就正常了，不过之前一直都是加 -s 的也正常的，好像最近才不行

**Comment by xesygao** [comment]
> shadowrocket 能看 log 吗
> 你看看酷我的资源是不是请求了 https ？
> 酷我 win.web.ra01.sycdn.kuwo.cn 这个域名没有 https 的

shadowrocket日志看不到有请求酷我的链接，服务端日志酷我是http的

**Comment by nondanee** [comment]
@huaxinchan 
https://github.com/nondanee/UnblockNeteaseMusic/releases/tag/v0.16.0
是 0.16.0 改的，看更新日志
默认不 package 了，裸连 insure.stream.qqmusic.qq.com 的话不在白名单内，会被 ban

**Comment by huaxinchan** [comment]
> @huaxinchan
> https://github.com/nondanee/UnblockNeteaseMusic/releases/tag/v0.16.0
> 是 0.16.0 改的，看更新日志
> 默认不 package 了，裸连 insure.stream.qqmusic.qq.com 的话不在白名单内，会被 ban

好的

**Comment by nondanee** [comment]
@xesygao 
客户端会升到 https 的，和服务器日志无关
你加上 `-e http://music.163.com` 试试吧，证书也去装一下

**Comment by xesygao** [comment]
> @xesygao
> 客户端会升到 https 的，和服务器日志无关
> 你加上 `-e http://music.163.com` 试试吧，证书也去装一下

-e是有的。感觉跟客户端升级https应该没关系，我用qq的源，这个是有https的，也不能播放。上一周WIFI那边配置自动代理就能用的，这一周就不行了，可能客户端自动升级了

**Comment by nondanee** [comment]
@xesygao 
那就没办法了，iOS 我没法测 =.=

**Comment by GeQ1an** [comment]
我今天尝试了一下，歌曲名称变亮了，但却无法下载或播放音乐。
配置环境是 macOS，使用 iOS 客户端。
具体操作是：
1. 下载 Node.js
2. 项目首页 Download ZIP 并解压，在目录内通过 OpenInTerminal 打开 Terminal
3. 输入 node app.js 运行
4. iOS 端使用 Quantumult 配置 HTTP 代理，并加入网易云音乐相关规则
服务端有提示解析成功，但 iOS 客户端提示播放失败。如下图：
[服务端](http://chuantu.xyz/t6/702/1566388371x3703728804.png) [客户端](http://chuantu.xyz/t6/702/1566388443x3703728804.jpg)
失败后，尝试了安装证书、关闭 Quantumult、使用系统设置代理的方法，问题依旧。
请问是我哪里的操作不当吗？还是 iOS 客户端真的不能用了...

**Comment by nondanee** [comment]
@GeQ1an 
我也不知道还能不能用 =.=

你改成这样试试吧
```
node app.js -p 8080:8081 -e http://music.163.com
```

**Comment by su3817806** [comment]
pac  加上以下配置就好了

DOMAIN-SUFFIX,music.163.com,PROXY
DOMAIN-SUFFIX,interface.music.163.com,PROXY
DOMAIN-SUFFIX,interface3.music.163.com,PROXY
DOMAIN-SUFFIX,apm.music.163.com,PROXY
DOMAIN-SUFFIX,apm3.music.163.com,PROXY
IP-CIDR,59.111.181.38/32,PROXY
IP-CIDR,59.111.181.60/32,PROXY
IP-CIDR,223.252.199.66/32,PROXY
IP-CIDR,223.252.199.67/32,PROXY
IP-CIDR,59.111.160.195/32,PROXY
IP-CIDR,59.111.160.197/32,PROXY
IP-CIDR,47.100.127.239/32,PROXY
IP-CIDR,118.24.63.156/32,PROXY
IP-CIDR,193.112.159.225/32,PROXY
IP-CIDR,39.105.63.80/32,PROXY
IP-CIDR,59.111.181.35/32,PROXY
IP-CIDR,115.236.118.33/32,PROXY

**Comment by xesygao** [comment]
> pac 加上以下配置就好了
> 
> DOMAIN-SUFFIX,music.163.com,PROXY
> DOMAIN-SUFFIX,interface.music.163.com,PROXY
> DOMAIN-SUFFIX,interface3.music.163.com,PROXY
> DOMAIN-SUFFIX,apm.music.163.com,PROXY
> DOMAIN-SUFFIX,apm3.music.163.com,PROXY
> IP-CIDR,59.111.181.38/32,PROXY
> IP-CIDR,59.111.181.60/32,PROXY
> IP-CIDR,223.252.199.66/32,PROXY
> IP-CIDR,223.252.199.67/32,PROXY
> IP-CIDR,59.111.160.195/32,PROXY
> IP-CIDR,59.111.160.197/32,PROXY
> IP-CIDR,47.100.127.239/32,PROXY
> IP-CIDR,118.24.63.156/32,PROXY
> IP-CIDR,193.112.159.225/32,PROXY
> IP-CIDR,39.105.63.80/32,PROXY
> IP-CIDR,59.111.181.35/32,PROXY
> IP-CIDR,115.236.118.33/32,PROXY

我的应该不是代理的问题，就算全局代理也播放不了。

**Comment by su3817806** [comment]
新版可能加了什么检测。我刚才一下也是显示网络错误，全局也不行。但是在小火箭里面只把走流量的配置加进去就好了

**Comment by illusion77** [comment]
> 新版可能加了什么检测。我刚才一下也是显示网络错误，全局也不行。但是在小火箭里面只把走流量的配置加进去就好了

请问具体是怎么做的呢？我用的是小火箭的HTTP全局代理也不行

**Comment by su3817806** [comment]
> > 新版可能加了什么检测。我刚才一下也是显示网络错误，全局也不行。但是在小火箭里面只把走流量的配置加进去就好了
> 
> 请问具体是怎么做的呢？我用的是小火箭的HTTP全局代理也不行

配置那里使用这个配置http://www.ydlrqx.com/WangYiMusic.conf

**Comment by illusion77** [comment]
> > > 新版可能加了什么检测。我刚才一下也是显示网络错误，全局也不行。但是在小火箭里面只把走流量的配置加进去就好了
> > 
> > 
> > 请问具体是怎么做的呢？我用的是小火箭的HTTP全局代理也不行
> 
> 配置那里使用这个配置http://www.ydlrqx.com/WangYiMusic.conf

还是无效，用这个配置而不用全局代理的话，会走正常流量了，亮都不亮了，原来是网络连接失败。

**Comment by su3817806** [comment]
> > > > 新版可能加了什么检测。我刚才一下也是显示网络错误，全局也不行。但是在小火箭里面只把走流量的配置加进去就好了
> > > 
> > > 
> > > 请问具体是怎么做的呢？我用的是小火箭的HTTP全局代理也不行
> > 
> > 
> > 配置那里使用这个配置http://www.ydlrqx.com/WangYiMusic.conf
> 
> 还是无效，用这个配置而不用全局代理的话，会走正常流量了，亮都不亮了，原来是网络连接失败。

app.js
server.whitelist = ['music.1236.net', 'vod.1236.net'].map(escape)
这里加上
server.whitelist = ['music.1236.net', 'vod.1236.net',"m8.music.126.net","m7.music.126.net"].map(escape)

**Comment by ch3nyy** [comment]
请教-e https://music.163.com和-e http://music.163.com在原理上是什么区别呢？我用-e http://music.163.com是可以的

**Comment by wfatestaynight** [comment]
我再 hook 里面加上了下面几个 ip 地址，现在好像 ios 最新版歌曲可以播放
hook.target.host = [ 
    'music.163.com',
    'interface.music.163.com',
    'interface3.music.163.com',
    'apm.music.163.com',
    'apm3.music.163.com',
    'mam.netease.com',
    'api.iplay.163.com',
    // 'crash.163.com',
    // 'clientlog.music.163.com'
    '59.111.21.14',
    '59.111.21.13',
    '59.111.179.214',
    '115.236.118.33'                                                                                                                                                                      
]

**Comment by nondanee** [comment]
@ch3nyy 
原理上没什么区别 https://github.com/nondanee/UnblockNeteaseMusic/issues/143#issuecomment-509181898
一个是 http 的，可以直接拦流量
还有一个是 https 的，要用自己的 "假" 证书拦流量 （可能不被信任无法连接）

iOS 客户端好像会自动把播放地址从 http 升到 https (内部逻辑我不知道)，并没有什么区别

**Comment by nondanee** [comment]
@wfatestaynight 
你这个是老版本吧？更新下看看

**Comment by finsxc** [comment]
> 最新版本的客户端好像是6.3。
> shadowrocket配置以下规则：
> 
> > * USER-AGENT: NeteaseMusic*
> > * DOMAIN-SUFFIX: 163.com
> > * DOMAIN-SUFFIX: 126.net
> 
> 灰色歌曲显示可用，但是播放失败，提示网络不给力。
> 查看日志已经成功匹配到音乐链接(我默认用的酷我)，怀疑是服务端开启了严格模式导致酷我的链接播放不了。但是我在shadowrocket把酷我设置成直连，不走代理，依然播放不了。
> 麻烦有经验的大佬指点下

大佬 你用-s 后是自己写了个新的小火箭配置吗 能分享一下吗.. 我用默认的配置加上述规则后 
因为是严格模式 默认配置里的网址就全崩了 自己重新搞了新的写上去也不对（主要搞不会小火箭的规则）
