### ISSUE TITLE
请问“加载失败”是怎么回事？

### ISSUE THREAD

**Issue by jayzjp** [nondanee/UnblockNeteaseMusic#188]
Win10，网易云版本号2.5.4，node.js方式，代理是在客户端内填的代理（127.0.0.1:8080），看node貌似运行正常，会显示MITM或者TUNNEL开头的提示。变灰歌曲都变黑了，但是都听不了（免费的可以听QAQ），加了-s也布星......都显示加载失败，请问怎么解决鸭ヽ(°◇° )ノ？

**Comment by FiseTch** [comment]
我也碰到了相同的问题。

**Comment by nondanee** [comment]
加了 `-s` 肯定步星
具体哪首歌？测试专用周杰伦？我没问题啊？

**Comment by skymon4** [comment]
我刚也碰到了这种问题

**Comment by skymon4** [comment]
在服务器上的没问题 但是在本地不行 就很奇怪

**Comment by nondanee** [comment]
@skymon4 
服务器和本地的运行参数一样吗？
具体是哪首歌？
日志有没有匹配成功提示？

**Comment by skymon4** [comment]
运行参数都一样 日志没进去 听别的日志会动 都是周杰伦不进日志 就是突然一下不行了

**Comment by nondanee** [comment]
@skymon4 
有加参数吗？加了什么，有没有改过 `-o` ？

**Comment by skymon4** [comment]
![image](https://user-images.githubusercontent.com/33510540/63505711-9ada8a80-c506-11e9-912c-9b1e42677e3b.png)
j就是这么启动的
![image](https://user-images.githubusercontent.com/33510540/63505738-a4fc8900-c506-11e9-9d82-b958cb889236.png)
还有这个 我从吾爱破解上下载的

**Comment by nondanee** [comment]
@skymon4 
那你的版本是多少？
```
node app.js -v
```
看一看

**Comment by skymon4** [comment]
10.16.0

**Comment by skymon4** [comment]
我寻思不是版本的问题 因为我刚用的时候好好的

**Comment by nondanee** [comment]
@skymon4 
那重启 server 呢？

可是我现在还可以用啊
![image](https://user-images.githubusercontent.com/26399680/63507576-9fa13d80-c50a-11e9-8e37-5d7e7233583d.png)

**Comment by tempscript** [comment]
刚刚也遇到这个问题，发现是qq音乐源的问题，只要把qq音乐源换掉就正常了

**Comment by skymon4** [comment]
怎么换

**Comment by tempscript** [comment]
node app.js -a 127.0.0.1 -o  kugou   kuwo xiami migu

**Comment by jayzjp** [comment]
> @jayzjp
> 加了 `-s` 肯定步星
> 具体哪首歌？测试专用周杰伦？我没问题啊？

谢谢哦，好像是音乐源的问题，用楼下哥们的命令启动就好啦~

**Comment by jayzjp** [comment]
> node app.js -a 127.0.0.1 -o kugou kuwo xiami migu

谢谢哦，问题解决了。

**Comment by skymon4** [comment]
666

**Comment by xyal-343448187** [comment]
docker 咋个解决音乐源的问题喃

**Comment by nondanee** [comment]
@xyal-343448187 
`docker start [options] nondanee/unblockneteasemusic` 后面加 `-o`
你用 GUI 的话也肯定有选项可以增加启动参数或者修改启动命令的

**Comment by nondanee** [comment]
@xyal-343448187 
`docker start [options] nondanee/unblockneteasemusic` 后面加 `-o`
你用 GUI 的话也肯定有选项可以增加启动参数或者修改启动命令的

**Comment by Mydong** [comment]
> > node app.js -a 127.0.0.1 -o kugou kuwo xiami migu
> 
> 谢谢哦，问题解决了。

解决了，谢谢作者和楼上各位，我还以为是哪个地方失效了。
因为公司的电脑今天下午还政策，晚上回家后，家里的不能用。更换后，可以正常播放了。

**Comment by Code-Evan** [comment]
> > > node app.js -a 127.0.0.1 -o kugou kuwo xiami migu
> > 
> > 
> > 谢谢哦，问题解决了。
> 
> 解决了，谢谢作者和楼上各位，我还以为是哪个地方失效了。
> 因为公司的电脑今天下午还政策，晚上回家后，家里的不能用。更换后，可以正常播放了。

你好，请问这行代码该怎么用？

**Comment by Code-Evan** [comment]
> node app.js -a 127.0.0.1 -o kugou kuwo xiami migu

你好，请问这个命令怎么使用呢，不太懂。。。。

**Comment by Code-Evan** [comment]
> node app.js -a 127.0.0.1 -o kugou kuwo xiami migu

你好，请问这个命令怎么使用呢？不太懂。。

**Comment by 1014967323** [comment]
> node app.js -a 127.0.0.1 -o kugou kuwo xiami migu
> 你好，多写几个音源有什么不是更好吗？多了会很影响速度吗？
> 谢谢哦，问题解决了。
> 
> 解决了，谢谢作者和楼上各位，我还以为是哪个地方失效了。
> 因为公司的电脑今天下午还政策，晚上回家后，家里的不能用。更换后，可以正常播放了。
> 
> 你好，请问这行代码该怎么用？
