### ISSUE TITLE
纯小白请教部署问题

### ISSUE THREAD

**Issue by Redlove2015** [nondanee/UnblockNeteaseMusic#190]
能否像ssr部署那样麻烦您有空出个纯小白教程。只会搭建一下ssr以及v2ray，所以readme看不懂。想搭建在debian上，请问该怎么操作呢？另外我v2ray采用的Ws+tls，那么能否，使用v2ray的同时我的vps就自动运行这个呢？这样我就能上外网的同时听啦！

**Comment by nondanee** [comment]
搭建教程看 看 👉 #22 ，不懂的可以问我
与和 v2ray 配合使用看 👉 #148，你可以问一下那边同学
