### ISSUE TITLE
## QQ 音源限制策略日渐严格

### ISSUE THREAD

**Issue by xiaobaiha** [nondanee/UnblockNeteaseMusic#191]
## QQ 音源限制策略日渐严格
游客身份过不了 CDN 鉴权，感觉凉凉
没办法的办法，带上自己的 cookie
祝这个项目好运

2019.3.15

如果有需求，可以改用 @messoer 的 API
https://www.bzqll.com/2019/04/318.html
~~自己动手丰衣足食~~

2019.7.28

_Originally posted by @nondanee in https://github.com/nondanee/UnblockNeteaseMusic/issues/30#issuecomment-473205753_

QQGET音乐地址返回403是因为游客的问题吗

**Comment by nondanee** [comment]
vkey 的问题，没有权限或者超时了
哪个歌哪个 url 403 了？麻烦贴一下

**Comment by xiaobaiha** [comment]
周杰伦的很多歌状态可用但是听不了，就找了其中一首看了一下，应该是等你下课

**Comment by nondanee** [comment]
我没问题啊 =.=

![image](https://user-images.githubusercontent.com/26399680/63508280-3c180f80-c50c-11e9-87d2-5642afe37471.png)

**Comment by xiaobaiha** [comment]
![image](https://user-images.githubusercontent.com/28567286/63508923-89e14780-c50d-11e9-9b48-46c49f2eec12.png)
直接播放失败跳过了

**Comment by xiaobaiha** [comment]
貌似qq的没成功过，能听的都是xiami

**Comment by xiaobaiha** [comment]
http://isure.stream.qqmusic.qq.com/M500002qU5aY3Qu24y.mp3?vkey=AD8C754B37BC517CE4DB1416A36D6A4765F9B7F57E985DAB74C8EE0D3E105B001B57B2E2BC9AD97021D2E7121AAF47EEB73BFD82A94A5EAB&uin=0&fromtag=8&guid=7332953645

**Comment by nondanee** [comment]
@xiaobaiha 
我这边没问题
![image](https://user-images.githubusercontent.com/26399680/63513002-af734e80-c517-11e9-90b0-8f8c0db52270.png)

你看看换这几个 host 可不可以？
https://github.com/nondanee/UnblockNeteaseMusic/blob/30ea1f9efc8ab4097cef73b67ccb986f2dcd6adc/provider/qq.js#L104

**Comment by xiaobaiha** [comment]
最后一个可以，感谢！
