### ISSUE TITLE
突然不能用了

### ISSUE THREAD

**Issue by seaboyang** [nondanee/UnblockNeteaseMusic#192]
前天晚上参照 Mac 配合 proxifier 的方法成功播放变灰歌曲。今天再次播放的时候网易云音乐提示“播放失败，网络错误，请检查网络设置”。终端界面也没有连接 QQ 音乐的内容出现。不知道是哪出了问题

**Comment by nondanee** [comment]
先加上 `-o kuwo kugou migu`

好像很多人反映 QQ 音乐有问题？
但是我自己不能复现 =.=
等等看

**Comment by seaboyang** [comment]
> 

请问在哪加，完全不懂。见谅

**Comment by nondanee** [comment]
启动命令里加
```
node app.js -o kuwo kugou migu ...
```

**Comment by seaboyang** [comment]
node app.js -o kuwo kugou migu -p 8000:8043

> 启动命令里加
> 
> ```
> node app.js -o kuwo kugou migu ...
> ```

谢谢。现在可以正常使用了。应该就是 QQ 音乐的问题

**Comment by sandglasstu** [comment]
> 启动命令里加
> 
> ```
> node app.js -o kuwo kugou migu ...
> ```

大佬我也遇到了，本地加参数解决了，docker里面怎么加参数呢，改了Dockerfile貌似没用
