### ISSUE TITLE
反馈几个小问题

### ISSUE THREAD

**Issue by iDesperad0** [nondanee/UnblockNeteaseMusic#193]
1. 酷狗的音源貌似用不了了

2. 以蔡依林的《怪美的》这首歌为例，酷我匹配的是一个live合作版，但是通过“怪美的+蔡依林”搜索，结果却是原版的，这个：http://www.kuwo.cn/search/list?key=%E6%80%AA%E7%BE%8E%E7%9A%84%20%20%E8%94%A1%E4%BE%9D%E6%9E%97

3. 更新到Android最新的6.3.2版本后，发现载入变得很慢，包括加载所有歌曲，查看评论等。回滚到6.3.1正常，不知道其他人是否有这个问题。

**Comment by nondanee** [comment]
有点忙，issue 回不过来，稍后处理

**Comment by iDesperad0** [comment]
**更新：**

4. 看来QQ的音源也挂了，这下可地震了😂 

5. kuwo的匹配明显不如QQ的准确

6. 要不要我帮你写个Android平台使用的伪教程给部分像我一样的小白😂

**Comment by nondanee** [comment]
@iDesperad0 
1. 酷狗我会修的

2. 嗯，因为搜索 API 不唯一
你给的网址用手机浏览器打开是 http://m.kuwo.cn/?key=%E6%80%AA%E7%BE%8E%E7%9A%84%20%20%E8%94%A1%E4%BE%9D%E6%9E%97#1 结果就是 live 排第一个

3. 这个我还没试

4. QQ 我还是不确定挂没挂，因为我自己这边没问题，也不知道怎么修 😂

5. 是的

6. 你愿意写当然欢迎啦，不用请示我 😂

**Comment by Anemone0** [comment]
QQ貌似挂了

**Comment by nondanee** [comment]
@Anemone0 嗯确实

**Comment by Anemone0** [comment]
还有救吗？我刚上车就挂了

**Comment by nondanee** [comment]
@iDesperad0 
1. 酷狗的修了

2. 下个版本会改成你发的那个 PC web 用的 API

3. 试过了，我搭在本地的，好像没什么感觉。但是遇到过卡死的 bug，播放页显示 0:00 - 0:00 无法播放，点别的歌播放页也没变化一直是刚才那首歌卡着，强制停止再打开就好了

4. 换了个 sip，还能应付下

6. 有人抢先写了 😂 #214

**Comment by nondanee** [comment]
@Anemone0 嗯？QQ 挂掉的话不用 QQ 就行了啊。

**Comment by Anemone0** [comment]
我可能是不会用，我用docker装的直接就不能用了 显示加载失败

![image](https://user-images.githubusercontent.com/47690290/63936253-f7532200-ca91-11e9-9ff0-cd878e45b88c.png)
