### ISSUE TITLE
恕我直言，项目很伟大，使用说明烂到死

### ISSUE THREAD

**Issue by Zhang-Shijun** [nondanee/UnblockNeteaseMusic#194]
我想这不是我一个人的看法，应该是大部分人的心声，按照教程，Google加项目说明。无论是VPS还是本地，我表示都没有成功

**Comment by nondanee** [comment]
我先问一下，你是不是 iOS

**Comment by Zhang-Shijun** [comment]
不是MacBook

**Comment by nondanee** [comment]
那你有没有仔细看过 README ？
请听题，请问 macOS 客户端上使用有什么要求吗？

**Comment by grapeot** [comment]
我觉得readme很赞诶，我在windows，mac上都成功了。甚至还有https自签名证书的脚本。

**Comment by Heartbeats1104** [comment]
我也觉得Readme “很赞”诶，看了以后直接开了网易云点的会员还有QQ音乐跟酷狗的诶。甚至连百度音乐会员都开了。

**Comment by guozhigq** [comment]
> 我觉得readme很赞诶，我在windows，mac上都成功了。甚至还有https自签名证书的脚本。

我的MAC一直弄不上 可以教教我吗

**Comment by nondanee** [comment]
@Heartbeats1104 
这......你带上自己的登录凭据，那些会员也是可以用起来的......

**Comment by nondanee** [comment]
@guozhigq 
一样的问题，请问 macOS 客户端使用有什么要求

(我求求你们在 README 页，Ctrl + F 搜一下 "mac"，看看前后我写了什么话行不行)
至于达到要求怎么做，issue 里最顶部有三个 pinned 位，里面都有写
当然如果你不想自己查，也可以问我那些要求怎么才能达到，我给你贴链接 (issue 里全有)

**Comment by guozhigq** [comment]
> @guozhigq
> 一样的问题，请问 macOS 客户端使用有什么要求
> 
> (我求求你们在 README 页，Ctrl + F 搜一下 "mac"，看看前后我写了什么话行不行)
> 至于达到要求怎么做，issue 里最顶部有三个 pinned 位，里面都有写
> 当然如果你不想自己查，也可以问我那些要求怎么才能达到，我给你贴链接 (issue 里全有)

你好，我都看了，也都照做了，最起码尝试了不下五次，我是在虚心问，不愿意告诉也请不要用这种语气好么，自己能解决的话，谁愿意低声下气的问别人呢？

**Comment by JasonKhew96** [comment]
> > @guozhigq
> > 一样的问题，请问 macOS 客户端使用有什么要求
> > (我求求你们在 README 页，Ctrl + F 搜一下 "mac"，看看前后我写了什么话行不行)
> > 至于达到要求怎么做，issue 里最顶部有三个 pinned 位，里面都有写
> > 当然如果你不想自己查，也可以问我那些要求怎么才能达到，我给你贴链接 (issue 里全有)
> 
> 你好，我都看了，也都照做了，最起码尝试了不下五次，我是在虚心问，不愿意告诉也请不要用这种语气好么，自己能解决的话，谁愿意低声下气的问别人呢？


readme那里的已经很清楚了，请先解释“弄不上”，不然就哪个步骤出了问题 或 附上日志，不然不知道哪出了错，怎么帮你解决？

**Comment by guozhigq** [comment]
> > > @guozhigq
> > > 一样的问题，请问 macOS 客户端使用有什么要求
> > > (我求求你们在 README 页，Ctrl + F 搜一下 "mac"，看看前后我写了什么话行不行)
> > > 至于达到要求怎么做，issue 里最顶部有三个 pinned 位，里面都有写
> > > 当然如果你不想自己查，也可以问我那些要求怎么才能达到，我给你贴链接 (issue 里全有)
> > 
> > 
> > 你好，我都看了，也都照做了，最起码尝试了不下五次，我是在虚心问，不愿意告诉也请不要用这种语气好么，自己能解决的话，谁愿意低声下气的问别人呢？
> 
> readme那里的已经很清楚了，请先解释“弄不上”，不然就哪个步骤出了问题 或 附上日志，不然不知道哪出了错，怎么帮你解决？

[
![Snipaste_2019-08-24_00-09-02](https://user-images.githubusercontent.com/25545225/63609632-06f1e700-c60a-11e9-90f4-d4e320f05285.png)
![Snipaste_2019-08-24_00-48-55](https://user-images.githubusercontent.com/25545225/63609646-1113e580-c60a-11e9-8aa0-86e454aaf9bb.png)
![Snipaste_2019-08-24_00-53-32](https://user-images.githubusercontent.com/25545225/63609653-12dda900-c60a-11e9-8073-ed3007676722.png)

](url)

**Comment by guozhigq** [comment]
> > > @guozhigq
> > > 一样的问题，请问 macOS 客户端使用有什么要求
> > > (我求求你们在 README 页，Ctrl + F 搜一下 "mac"，看看前后我写了什么话行不行)
> > > 至于达到要求怎么做，issue 里最顶部有三个 pinned 位，里面都有写
> > > 当然如果你不想自己查，也可以问我那些要求怎么才能达到，我给你贴链接 (issue 里全有)
> > 
> > 
> > 你好，我都看了，也都照做了，最起码尝试了不下五次，我是在虚心问，不愿意告诉也请不要用这种语气好么，自己能解决的话，谁愿意低声下气的问别人呢？
> 
> readme那里的已经很清楚了，请先解释“弄不上”，不然就哪个步骤出了问题 或 附上日志，不然不知道哪出了错，怎么帮你解决？

已上传

**Comment by JasonKhew96** [comment]
![image](https://user-images.githubusercontent.com/29531167/63614047-af0cad80-c614-11e9-9a29-edb4a58d0a91.png)
@guozhigq

**Comment by nondanee** [comment]
@guozhigq 
我希望你都看了，我完全没有不愿意告诉你的意思
我的语气是真的是在求你再仔细看一遍 README (不是 #22，那里只有基础配置)
并回答出我问你的问题
也完全没有让你放低姿态来求我
你这么说的话真是委屈你低声下气问  @grapeot 了

**你没回答我的问题，我回答给你，阅读理解我做给你看**

在 README 里搜索 "mac" **一共有 6 个结果**
4 个结果在 "使用"，1 个在 "效果" ，1 个在 "致谢"

4 个在 "使用" 中的结果
1. ~~密码认证~~ (可以不用)
2. **macOS 客户端 (726 版本以上需要自签证书)**
3. **(新版 Linux 客户端和 macOS 客户端已无法降级)**
4. ~~设置代理~~ (你用的 hosts)

说明
**对 macOS 客户端的版本有要求**
对新版客户端的解决方法：**自签证书**

**在 issue 页最底部有三个 pinned issue (也都打了 pinned tag)**
分别是 "食用指南" "已知 BUG" 和 "进阶配置"
**自签证书属于额外设置，写在 "进阶配置" 里**
那个 issue 里已经把，是什么，为什么，怎么做都写得很清楚了

**请接受你没有仔细看 README 的事实**

**Comment by nondanee** [comment]
还有我们伟大的 issue author
请不要装死了

README 写得不好，你可以 PR
issue 里写得不好，你可以新建一个，我会 pin 的 (#56 #65 都是用户提供的教程)

Google 其它人写的教程没让你成功，你咋不去怪他们，只来怪我？？？

**口嗨谁不会啊！**

如果我明明写了的东西你都不看，应该算你无理取闹吧？

**Comment by nondanee** [comment]
@Zhang-Shijun 
还有我们伟大的 issue author
请不要装死了

README 写得不好，你可以 PR
issue 里写得不好，你可以新建一个，我会 pin 的 (#56 #65 都是用户提供的教程)

Google 其它人写的教程没让你成功，你咋不去怪他们，只来怪我？？？

**口嗨谁不会啊！**

如果我明明写了的东西你都不看，应该算你无理取闹吧？

**Comment by kossel** [comment]
我觉得如果谁觉得写得不好可以PR，这是个开源项目啊。。。 我弄了2天， 觉得可以弄个FAQ， 把有用的comment 都列出来。 （例如我那个和本地nginx冲突）

**Comment by Heartbeats1104** [comment]
好叼哦！人家issue author都懒得理你。项目首页read me说了下载跟执行，说了需要自签证书，紧接着的有issue链接吗？没有。如何签，怎么签？没说。issue一个就将说有问题说清了吗？貌似好几个issue分开的。

**Comment by Heartbeats1104** [comment]
还口嗨，笑死

**Comment by nondanee** [comment]
@Heartbeats1104 
本来就是开源项目啊
你觉得有问题怎么不 PR？？？
你觉得一个 issue 就够了那你 create 啊？？？
你在干嘛
在这里怼我就个 jb 用

我为什么要贴把所有链接都贴在 README 里？
我为什么要把所有内容写在一个 issue 里？
别的平台都不需要的操作我干嘛要强行塞给别人？
3 个 pinned issue 都白 pinned 了？没有用我 pinned 在那里干嘛？

issue 也可以搜索啊，in this repo 也可以搜索啊，都不会用？
而且我有什么责任把你教会？我逼你用了？

200 来个 issue 你看看别人提的都是怎么提的，你再看看你？
笑死

**Comment by nondanee** [comment]
@Heartbeats1104 
而且你去充会员的问题跟他们的问题完全不一样
我不是跟你说了吗
带 cookie 或许可以用起来啊

你去跟他们凑什么热闹？

**Comment by Kzel** [comment]
LMAO readme写的很详细了

**Comment by a211212abc** [comment]
...wtf 自己看不懂rm还去怪开源作者 活久见

**Comment by nondanee** [comment]
@Heartbeats1104 
我挖个坟 
5 Dec 2019 [v0.22.2 版本](https://github.com/nondanee/UnblockNeteaseMusic/releases/tag/v0.22.2)
开始支持设置 QQ 音乐的 cookie

**Comment by yesmiley** [comment]
楼上有点意思，本来就白嫖的东西，也有还不错的教程，自己没弄成功就代表readme不合格了
搞不来就老老实实花钱买会员呗，有啥可喷的

**Comment by tnnevol** [comment]
不看食用指南？

**Comment by zhuhongjie** [comment]
> 好叼哦！人家issue author都懒得理你。项目首页read me说了下载跟执行，说了需要自签证书，紧接着的有issue链接吗？没有。如何签，怎么签？没说。issue一个就将说有问题说清了吗？貌似好几个issue分开的。

要不要教教你怎么下载？要不要教教你怎么执行？要不要教教你怎么打开链接？脑瘫

**Comment by tnnevol** [comment]
> > 好叼哦！人家issue author都懒得理你。项目首页read me说了下载跟执行，说了需要自签证书，紧接着的有issue链接吗？没有。如何签，怎么签？没说。issue一个就将说有问题说清了吗？貌似好几个issue分开的。
> 
> 要不要教教你怎么下载？要不要教教你怎么执行？要不要教教你怎么打开链接？脑瘫

像这种人，屎到屁股眼都不会拉
