### ISSUE TITLE
hosts 模式 Android 无法登录

### ISSUE THREAD

**Issue by wenLiangcan** [nondanee/UnblockNeteaseMusic#195]
修改了 hosts 启用了 AFWall + ，已经登录的 App 内还是无法播放没版权的音乐，尝试清除用户数据后无法重新登录，提示登录失败，用备份软件恢复数据后是可以正常使用的除了无法播放被限制的音乐。

**Comment by nondanee** [comment]
确实是不能登录的，因为登录接口不会降级 http
(解决这个问题的话需要 6.2.5 之前的版本，然后去装个证书，打开 https 监听，应该就能登录了)

先登录，登录后再改 hosts 启用 AFWall+
(我猜你应该不会被欧盟 GDPR 限制必须开着代理或者改 hosts 才能登录吧？)

无法播放无版权音乐的话你加上 `-o kuwo` 去试周杰伦吧，最近 QQ 的音源好像有点问题

**Comment by nondanee** [comment]
在已知 BUG 里 https://github.com/nondanee/UnblockNeteaseMusic/issues/30#issuecomment-472538422 已更新
