### ISSUE TITLE
windows端无法正常使用 没版权的歌曲只是点亮了 安卓端WIFI代理设置也是一样的

### ISSUE THREAD

**Issue by doumua** [nondanee/UnblockNeteaseMusic#197]
第一和第三模式都是
换过很多端口了

都只是点亮了 无法加载 无法播放

**Comment by nondanee** [comment]
哪来的第三模式啊？😥

你先加上 `-o kuwo` 试一下，可能是 QQ 音源的问题

**Comment by doumua** [comment]
![TIM截图20190823141155](https://user-images.githubusercontent.com/54427450/63570425-b6e63680-c5af-11e9-96c3-4355deecc5f0.png)


windows模式啊 然后都用不了 这个 -o 加上去启用不了

**Comment by nondanee** [comment]
就是音源排序那行
这么看你已经没在用 QQ 的音源了
那么应该是别的问题

你用哪首歌测试的？我试一下

**Comment by doumua** [comment]
这几首测试的
![TIM截图20190823141718](https://user-images.githubusercontent.com/54427450/63570707-a5e9f500-c5b0-11e9-8b4f-98e136e32389.png)

**Comment by JasonKhew96** [comment]
![image](https://user-images.githubusercontent.com/29531167/63570960-5ce67080-c5b1-11e9-9d6d-e89c6000f2b0.png)
qq源没问题

**Comment by doumua** [comment]
> ![图片](https://user-images.githubusercontent.com/29531167/63570960-5ce67080-c5b1-11e9-9d6d-e89c6000f2b0.png)
> QQ源没问题

但是无法播放下载

**Comment by nondanee** [comment]
@doumua 

![image](https://user-images.githubusercontent.com/26399680/63572117-a4bac700-c5b4-11e9-8a2a-36c6e2506f21.png)

按你的音源排序 `kuguo kuwo xiami migu` 会匹配到这个
可以播放

下载也没问题

![image](https://user-images.githubusercontent.com/26399680/63572241-fa8f6f00-c5b4-11e9-8d1d-e781b543fc30.png)

**Comment by doumua** [comment]
> @doumua
> 
> ![图片](https://user-images.githubusercontent.com/26399680/63572117-a4bac700-c5b4-11e9-8a2a-36c6e2506f21.png)
> 
> 你按的音源排序`kuguo kuwo xiami migu`会匹配到这个
> 可以播放
> 
> 下载也没问题
> 
> ![图片](https://user-images.githubusercontent.com/26399680/63572241-fa8f6f00-c5b4-11e9-8d1d-e781b543fc30.png)

看来是我的问题了 唉。。。搞不懂 是跟网络有啥关系吗

**Comment by nondanee** [comment]
@doumua 
可能会有
你能提供 log 吗？

**Comment by doumua** [comment]
> @doumua
> 可能会有
> 你能提供log吗？

log是什么 话说可以用别的软件什么的交流吗。。我是个小白

**Comment by nondanee** [comment]
@doumua 
你把联系方式发我邮箱里吧
邮箱在 profile 页里有 https://github.com/nondanee

**Comment by doumua** [comment]
> @doumua
> 你把联系方式发我邮箱里吧
> 邮箱在个人资料页里有https://github.com/nondanee

发送了
