### ISSUE TITLE
Android 使用数据模式如何用此项目

### ISSUE THREAD

**Issue by zengxiaoliang** [nondanee/UnblockNeteaseMusic#198]
背景：
现每月数据流量都是以G为单位，很少连WiFi；因此想寻找在手机上启动项目，并能正常工作的方法

个人初步解决方案：
1. Android手机安装Termux后，可以使用git clone  或者wget 获取UnblockNeteaseMusic 
2. 使用Termux 安装node后启动项目
3. 在设置--无线和网络--移动网络--接入点名称（APN）---新增APN --填入名称、APN、ip和端口(项目监听地址) ；完成后保存并使用新建的apn
4. 启动网易云音乐 可正常破灰

问题：
系统中所有请求都会经UnblockNeteaseMusic代理，希望能使用pac或者指定代理。尝试过用v2ray最终失败。

**Comment by nondanee** [comment]
所有请求全过本地代理并没有什么延迟和开销

你是遇到了有 APP 加载不了还是什么问题吗？

APN 没办法用 PAC

v2ray 有相关讨论你可以参考一下 #148

**Comment by zengxiaoliang** [comment]
所有请求走UnblockNeteaseMusic时，APP工作正常，只是这种情况下手机耗电增加（不确定是否跟终端一直打印大量日志有关系，有没有配置关闭日志输出进行测试下。

**Comment by tarontop** [comment]
> 背景：
> 现每月数据流量都是以G为单位，很少连WiFi；因此想寻找在手机上启动项目，并能正常工作的方法
> 
> 个人初步解决方案：
> 
> 1. Android手机安装Termux后，可以使用git clone  或者wget 获取UnblockNeteaseMusic
> 2. 使用Termux 安装node后启动项目
> 3. 在设置--无线和网络--移动网络--接入点名称（APN）---新增APN --填入名称、APN、ip和端口(项目监听地址) ；完成后保存并使用新建的apn
> 4. 启动网易云音乐 可正常破灰
> 
> 问题：
> 系统中所有请求都会经UnblockNeteaseMusic代理，希望能使用pac或者指定代理。尝试过用v2ray最终失败。

使用ProxyDroid，前提是手机要root,这个软件可以单独对网易云音乐走代理（自己选），其他的不走代理，基本上能满足你的要求

**Comment by nondanee** [comment]
@zengxiaoliang 
可以用 screen 命令，这样不会打屏，但是之后可以查看日志
如果就不要日志的话 `>  /dev/null` 就行了
