### ISSUE TITLE
MAC系统无法解锁问题

### ISSUE THREAD

**Issue by dlpuzhangyue** [nondanee/UnblockNeteaseMusic#199]
1 网易云版本

![image](https://user-images.githubusercontent.com/29819173/63575951-d2583e00-c5bd-11e9-971e-50c14a53fc04.png)

2 host配置

![image](https://user-images.githubusercontent.com/29819173/63575984-e603a480-c5bd-11e9-99cd-b971e139d577.png)

3 证书安装

![image](https://user-images.githubusercontent.com/29819173/63576017-f451c080-c5bd-11e9-99b3-a5fb03953e72.png)

4 项目启动正常 music.163.com 无法正常访问

![image](https://user-images.githubusercontent.com/29819173/63576071-0d5a7180-c5be-11e9-84c2-dd9b90115f79.png)

![image](https://user-images.githubusercontent.com/29819173/63576335-80fc7e80-c5be-11e9-8a36-c42198794fa1.png)

希望得到您的回复 @nondanee

**Comment by nondanee** [comment]
加一下 `-o kuwo`
QQ 音源有点问题

**Comment by dlpuzhangyue** [comment]
感谢您的回复 我主要是在使用网易云音乐时遇到这个问题，您的意思是让我去尝试酷我音乐么？

那网易云问题出来哪里呢 还请您帮忙解决 万分感谢 @nondanee

**Comment by nondanee** [comment]
@dlpuzhangyue 
哦哦我看错问题了不好意思
ping 结果不同没关系的

你把启动命令改成
```
sudo node app.js -p 80:443 -f 59.111.181.160
```

**Comment by dlpuzhangyue** [comment]
能监听到页面访问 但是还是被拒绝连接了😢 @nondanee

**Comment by nondanee** [comment]
@dlpuzhangyue 
chrome 的错误提示什么？

**Comment by dlpuzhangyue** [comment]
music.163.com 打不打不开。

**Comment by nondanee** [comment]
@dlpuzhangyue 
*.music.163.com 这个是服务器证书，不需要安装到系统中，只需要装 CA 证书

err name not resolved 错误的话，重启 chrome 或者参考这个
https://www.drivereasy.com/knowledge/how-to-fix-err-name-not-resolved-error/

**Comment by dlpuzhangyue** [comment]
把您发的
`
sudo node app.js -p 80:443 -f 59.111.181.160

`
改成了

`
sudo node app.js -p 80:443 -f 59.111.181.60
`
就好用了 可能是您写错了 再次感谢您的耐心解答 感恩 @ @nondanee

**Comment by nondanee** [comment]
哦哦是我看错了 😥😂
