### ISSUE TITLE
有些歌曲无法下载，提示该资源仅限开通会员后下载，现在去开通会员！

### ISSUE THREAD

**Issue by popo3680** [nondanee/UnblockNeteaseMusic#20]
有些歌曲无法下载，提示该资源仅限开通会员后下载，现在去开通会员！
大部分VIP资源可以下载

**Comment by nondanee** [comment]
@popo3680 已经把下载接口请求转发到试听接口了，可以试试

**Comment by alienzj** [comment]
![图片](https://user-images.githubusercontent.com/8847420/54483817-3cddb300-4895-11e9-9013-3d2e32bb4087.png)
@nondanee Nzix大佬，切换了不同音质，都没法下载周杰伦的歌。
谢谢你开发这个软件，很棒！

**Comment by nondanee** [comment]
@alienzj 是能听但不能下载的问题吗？还是试听下载都不行？描述不完整啊。部署在国内还是海外还是用的 demo 服务器？如果可以麻烦提供一下 log
