### ISSUE TITLE
安卓手机，Azure主机，表示手动跟自动都失败

### ISSUE THREAD

**Issue by isyume** [nondanee/UnblockNeteaseMusic#200]
完全按照教程，然而还是灰色。不知道是我手机问题，还是教程不清。

**Comment by nondanee** [comment]
加上 `-o kuwo` 试一下
默认源的 qq 从昨晚开始反馈有问题，(部分地区部分线路 403)，先不要使用

P.S. 如果觉得教程还不够清晰，你可以自己开个 issue 写教程，我帮你 pin。
