### ISSUE TITLE
播放周杰伦的歌失败，但是歌是亮的，后台日志解析出来的歌曲地址在浏览器打开是可以播放的

### ISSUE THREAD

**Issue by wangmm1994** [nondanee/UnblockNeteaseMusic#202]
![1](https://user-images.githubusercontent.com/23711956/63631600-d1c2b480-c65c-11e9-871f-07b7cbfdb0fe.png)
![2](https://user-images.githubusercontent.com/23711956/63631604-d4250e80-c65c-11e9-851e-44b77385429d.png)
![3](https://user-images.githubusercontent.com/23711956/63631606-d5563b80-c65c-11e9-8d5b-e49934010c3b.png)
![4](https://user-images.githubusercontent.com/23711956/63631607-d71fff00-c65c-11e9-9675-4107407b4484.png)

**Comment by hustlyt** [comment]
音源排序那里，把qq排在前面就可以了

**Comment by Chetimberk** [comment]
> ## 音源排序那里，把qq排在前面就可以了
> 没注意看，原来酷我的音质好点

同样问题，修改了把qq排在前面也加载失败

**Comment by Chetimberk** [comment]
> ## 音源排序那里，把qq排在前面就可以了
> 没注意看，原来酷我的音质好点

同样问题，修改了把qq排在前面也加载失败

**Comment by wangmm1994** [comment]
解决了 目前的办法是把migu放在第一位
![TIM截图20190826090739](https://user-images.githubusercontent.com/23711956/63658923-fc3d7a80-c7e0-11e9-86da-31ecc0e00d7c.png)

**Comment by nondanee** [comment]
你的 kuwo 是不这个问题，我会修的，修完再 close =.=

**Comment by wangmm1994** [comment]
> 你的 kuwo 是不这个问题，我会修的，修完再 close =.=

目前酷狗酷我放在前面都听不了 就咪咕可以听

**Comment by nondanee** [comment]
@wangmm1994 
kugou 的 API 确实是炸了 #193 
kuwo 是部分线路 cdn 的问题，HEAD 请求不能正确重定向，你和 #197  这位问题一样

**Comment by sunzongzheng** [comment]
测试QQ音乐使用这个cdn目前是正常的
http://aqqmusic.tc.qq.com/amobile.music.tc.qq.com

**Comment by nondanee** [comment]
@sunzongzheng 
还有 http://mobileoc.music.tc.qq.com 也是能用的，能用多久看天

**Comment by nondanee** [comment]
@wangmm1994
重定向的问题已解决
加上 `-e http://music.163.com` 应该就可以同酷我的歌了
不过你用的小工具好像还不支持加这个参数
