### ISSUE TITLE
突然周杰伦的哥无法播放

### ISSUE THREAD

**Issue by wgnmzgj** [nondanee/UnblockNeteaseMusic#204]
1,80播放有问题，周杰伦的哥无法播放了

**Comment by JasonKhew96** [comment]
https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-524400435

**Comment by wangmm1994** [comment]
migu  放在第一个就可以听了

**Comment by lushans** [comment]
![image](https://user-images.githubusercontent.com/24622986/63688279-7bf73380-c839-11e9-92c8-c0268bdbf9b3.png)

-o migu 可以
相关issus #202
