### ISSUE TITLE
-f 参数好像没用？

### ISSUE THREAD

**Issue by yellowlm** [nondanee/UnblockNeteaseMusic#205]
大佬，我自己架的DNS上做了两个HOSTS的地址，然后运行

npx @nondanee/unblockneteasemusic -a 172.16.255.9 -p 80 -f 103.126.92.132

但是加上-f参数貌似没有效果，显示：

Error: getaddrinfo EAI_AGAIN interface.music.163.com
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:72:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'interface.music.163.com'
}

是不是我哪弄错了·?

**Comment by nondanee** [comment]
emmm
我看了下 EAI_AGAIN 是 dns 查询超时的错误

> EAI_AGAIN is a DNS lookup timed out error, means it is a network connectivity error or proxy related error.

`-f` 不作用在 dns 模块上，仅对 http 请求时 dns 解析有效
如果改了 hosts，那么查询结果应该是 127.0.0.1，也不会超时吧？

你试试在 bash 里执行 `nslookup interface.music.163.com` 有没有结果？
