### ISSUE TITLE
nginx 反代理问题

### ISSUE THREAD

**Issue by 4867896** [nondanee/UnblockNeteaseMusic#207]
使用nginx反代理后用自定义映射域名访问只显示标题，http反代理能解锁只能播放解锁的音乐，之前能播放的没法播放。
![SharedScreenshot](https://user-images.githubusercontent.com/32392205/63690785-26725500-c840-11e9-83cd-13b5d5a8a1bf.jpg)

不用nginx反代理，
本地测试只有http://10.1.1.161:1234有效，https://10.1.1.161:12345无法使用。
node ./app.js  -p 1234:12345-f  $HOSTIP  -e http://music.163.com -o xiami kugou kuwo migu
nginx 配置
证书没有重新生成，反代用的证书是免费的
#网易云音乐http代理
server {
        listen 0.0.0.0:90;
        server_name music.n.xxxx.tk;
        location / {
                proxy_pass http://10.1.1.161:1234; # http 端口
        	proxy_set_header HOST 'music.163.com';
        }
}
#网易云音乐https代理
server {
	listen 0.0.0.0:89 ssl ;
       server_name music.n.xxxx.tk;
	#指定PEM格式的证书文件 
	ssl_certificate /xxxx.cer;
	#指定PEM格式的私钥文件 
	ssl_certificate_key /xxxx.key;
	ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_prefer_server_ciphers on;
	ssl_session_timeout 10m;
	ssl_session_cache shared:SSL:10m;
    #让http请求重定向到https请求  
    error_page 497  https://$host:89$uri$args; 
    
	location / {
		proxy_pass https://10.1.1.161:12345; # https 端口

	    #Proxy Settings
        proxy_redirect     off;
	proxy_set_header HOST 'music.163.com';
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_max_temp_file_size 0;
        proxy_connect_timeout      90;
        proxy_send_timeout         90;
        proxy_read_timeout         90;
        proxy_buffer_size          4k;
        proxy_buffers              4 32k;
        proxy_busy_buffers_size    64k;
        proxy_temp_file_write_size 64k;
	}
}
不知道能不能这么玩。。

**Comment by lushann** [comment]
可以参考 
1. #48 末尾，作者的答复
2. #208 我根据1中所说作者的答复、目前自己在使用的conf

**Comment by 4867896** [comment]
请问你的反代理是用自己的域名，实现了music.163.com的功能并且解锁了么，不知道我对这个反代理是不是理解有问题，应为我用的反代理用的自己的域名通过网页进去只能看到如图的样子。

> 可以参考
> 
> 1. [＃48](https://github.com/nondanee/UnblockNeteaseMusic/issues/48)末尾，作者的答复
> 2. [＃208](https://github.com/nondanee/UnblockNeteaseMusic/issues/208)我根据1中所说作者的答复，目前自己在使用的CONF

**Comment by lushann** [comment]
不能用自己的域名，hosts只是在域名的dns解析中强制将网易云域名解析到咱们自己的服务器的ip上， 自签名证书只是伪造了网易云域名TLS证书，所以用自己的域名是不可取的。

只能通过nginx的default sever来处理这个，而不是指定自己的域名

**Comment by 4867896** [comment]
嗯，好的，谢谢。用了nginx反代要改host 并更改server_name _; 才能用么。

**Comment by lushann** [comment]
不然呢，好好看看文档再提问题吧

**Comment by nondanee** [comment]
@4867896 
server name 不一定是 `_`，也可以写 `music.163.com interface.music.163.com`

确实不能用自己的域名反代网易云
你截图页面空白的部分是个 iframe，可能只有正确的 window.parent 才能加载
页面中 script src 等地址都没有改写成你自己的域名，可能都无法加载成功

反代只是用来解决 80/443 端口冲突的

**Comment by 4867896** [comment]
好的，我理解了，感谢！

**Comment by lushann** [comment]
可参考
```
server {
        listen 80;
        server_name music.163.com interface.music.163.com;

        location / {
                proxy_pass http://127.0.0.1:1630;
                proxy_set_header HOST 'music.163.com';
        }
}
server {
        listen 443 ssl;
        server_name music.163.com interface.music.163.com;

        ssl on;
        ssl_certificate /etc/nginx/ssl/163/server.crt;
        ssl_certificate_key /etc/nginx/ssl/163/server.key;

        ssl_session_timeout 10m;
        ssl_session_cache shared:SSL:10m;

        ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers 'AES128+EECDH:AES128+EDH';
        ssl_prefer_server_ciphers on;

        location / {
                proxy_pass https://127.0.0.1:1631;
                proxy_set_header HOST 'music.163.com';
        }
}
```
