### ISSUE TITLE
酷我kuwo的音源播放不了任何歌曲，migu没问题

### ISSUE THREAD

**Issue by wanzhiyu** [nondanee/UnblockNeteaseMusic#209]

**Comment by wanzhiyu** [comment]
部分歌曲只有酷我才有……

**Comment by nondanee** [comment]
log 里面有匹配记录吗？
如果有的话，log 里面的 url 复制到浏览器打开会不会重定向？

**Comment by wanzhiyu** [comment]
> log 里面有匹配记录吗？
> 如果有的话，log 里面的 url 复制到浏览器打开会不会重定向？

有匹配记录：
[1336789966] 桃花笑
http://sp.sycdn.kuwo.cn/956159d0bd036477085e626503df3aa1/5d64c81e/resource/n3/59/92/2334733718.mp3
TUNNEL > sp.sycdn.kuwo.cn:80
TUNNEL > sp.sycdn.kuwo.cn:443
TUNNEL > sp.sycdn.kuwo.cn:443
TUNNEL > sp.sycdn.kuwo.cn:80
TUNNEL > sp.sycdn.kuwo.cn:443
TUNNEL > sp.sycdn.kuwo.cn:443
TUNNEL > sp.sycdn.kuwo.cn:80
TUNNEL > sp.sycdn.kuwo.cn:443
TUNNEL > sp.sycdn.kuwo.cn:443
TUNNEL > sp.sycdn.kuwo.cn:80
TUNNEL > sp.sycdn.kuwo.cn:443
TUNNEL > sp.sycdn.kuwo.cn:443
TUNNEL > localhost:18080
MITM > music.163.com
TUNNEL > localhost:18080
MITM > music.163.com

**Comment by nondanee** [comment]
你把 sp.sycdn.kuwo.cn... 这样的 url 复制到浏览器里打开看看 url 会不会变？
(你贴出来这个已经过期了，要再去 log 里找一个)

**Comment by wanzhiyu** [comment]
> 你把 sp.sycdn.kuwo.cn... 这样的 url 复制到浏览器里打开看看 url 会不会变？
> (你贴出来这个已经过期了，要再去 log 里找一个)

并不会变，只是单纯的无法访问

**Comment by nondanee** [comment]
那你看看这个打不打得开
http://sp.sycdn.kuwo.cn/1a84caba20e81ec2c273b0b2cf6f17e3/5d64d9ab/resource/n3/59/92/2334733718.mp3

你给我回复是 1 个小时前，1 个小时前的 url 放到现在肯定是过期了

**Comment by nondanee** [comment]
你点击可以下载是不是重定向了？
https://github.com/nondanee/UnblockNeteaseMusic/issues/202#issue-484769758
类似这样，前缀变成  223.110.0.9

**Comment by wanzhiyu** [comment]
> 那你看看这个打不打得开
> http://sp.sycdn.kuwo.cn/1a84caba20e81ec2c273b0b2cf6f17e3/5d64d9ab/resource/n3/59/92/2334733718.mp3
> 
> 你给我回复是 1 个小时前，1 个小时前的 url 放到现在肯定是过期了

可以访问这个链接，之前我估计也是可以访问的，是我浏览器的问题。

网易云里面确实可以下载，但是无法试听。

**Comment by wanzhiyu** [comment]
> 你点击可以下载是不是重定向了？
> [#202 (comment)](https://github.com/nondanee/UnblockNeteaseMusic/issues/202#issue-484769758)
> 类似这样，前缀变成 223.110.0.9

嗯，和那个issue描述的应该一致，那这个怎么解决呢？

**Comment by nondanee** [comment]
可能是下载支持重定向但是试听不支持

那你浏览器打开以后 url 有没有变化啊？

**Comment by wanzhiyu** [comment]
> 可能是下载支持重定向但是试听不支持
> 
> 那你浏览器打开以后 url 有没有变化啊？

哦哦不好意思总算弄明你的意思了，确实重定向了，长这样：
http://192.168.73.133/sp.sycdn.kuwo.cn/1a84caba20e81ec2c273b0b2cf6f17e3/5d64d9ab/resource/n3/59/92/2334733718.mp3

**Comment by wanzhiyu** [comment]
> 可能是下载支持重定向但是试听不支持
> 
> 那你浏览器打开以后 url 有没有变化啊？

这重定向问题有啥解决办法不~

**Comment by nondanee** [comment]
会修的

**Comment by zyz-1998** [comment]
node app.js -o migu
PC端
不能下载
可以听

**Comment by zyz-1998** [comment]
不行，泰妍的歌曲听不了，也下载不了，全是加载失败和下载404

**Comment by st503max** [comment]
借发
大佬 我在海外
migu之前旧版的解析可以听 新版的不能听
都是用杰伦的试 请问有解吗

**Comment by LoongCatChina** [comment]
> node app.js -o migu
> PC端
> 不能下载
> 可以听

好像不能下载了，用的酷我音源，可以听

**Comment by nondanee** [comment]
@wanzhiyu
解决重定向的方法
加上 `-e http://music.163.com` 应该就行了

**Comment by nondanee** [comment]
@zyz-1998 @LoongCatChina 
能听不能下载，而且浏览器里打开链接 404？
是代理不在本机吗？匹配的链接都是服务器验证过的，试试服务器是能不能打开和下载吧

**Comment by nondanee** [comment]
@st503max 
是什么平台？(iOS 我不清楚)
你先看看 log，是能匹配到不能播放，还是最近的音源问题，还是请求就没发到代理上？
