### ISSUE TITLE
windows客户端播放不了了

### ISSUE THREAD

**Issue by little-eight-china** [nondanee/UnblockNeteaseMusic#210]
点击之后，显示加载失败

**Comment by little-eight-china** [comment]
直接访问http://interface.music.163.com/，显示{"code":404,"msg":"璇ヨ祫婧愪笉瀛樺湪銆�"}

**Comment by little-eight-china** [comment]
加上-o kuwo kugou migu即可，我关闭了。

**Comment by Zhujion** [comment]
> 加上-o kuwo kugou migu就可以，我关闭了。

老哥 啥意思呀 和你一样的问题

**Comment by Zhujion** [comment]
> 加上-o kuwo kugou migu即可，我关闭了。

node app.js -o kuwo kugou migu
老哥 更换之后也是加载失败。但是音源链接可以播放

**Comment by little-eight-china** [comment]
> > 加上-o kuwo kugou migu即可，我关闭了。
> 
> node app.js -o kuwo kugou migu
> 老哥 更换之后也是加载失败。但是音源链接可以播放

那就不知道了，你先更新下代码再试试
