### ISSUE TITLE
PC 版使用 Proxy 失敗

### ISSUE THREAD

**Issue by rexx0520** [nondanee/UnblockNeteaseMusic#213]
PC 版使用 Proxy 模式
log 有 MITM 紀錄但是加載超時後顯示失敗
(某一日開始突然這樣失效的，已拉最新版 docker image 嘗試)

使用 host 模式的話正常
但是加載版權歌曲會顯示加載失敗
log 裡面沒有匹配紀錄

使用 docker, 部屬參數 -s -p 8887:8888 -o kuwo kugou migu
反向代理映射如下圖
![image](https://user-images.githubusercontent.com/20151124/63854013-b80fcd00-c9ce-11e9-9a0c-98d9015c1797.png)

**Comment by rexx0520** [comment]
在另一台電腦上 Proxy 正常運作
然而版權歌曲依然失敗，沒有查詢記錄

**Comment by nondanee** [comment]
海外吗？
如果海外的话 kuwo kugou 无法使用

**Comment by rexx0520** [comment]
> 海外吗？
> 如果海外的话 kuwo kugou 无法使用

海外沒錯，然而只使用 `-o migu` 好像也不會動

**Comment by nondanee** [comment]
那要看你听什么歌了，可能咪咕搜索不到吧

**Comment by rexx0520** [comment]
使用了最新的版本
看到查詢 log 了
實際使用瀏覽器瀏覽網址也可以獲取到 mp3 音樂
然而網易雲音樂依然顯示加載失敗

![image](https://user-images.githubusercontent.com/20151124/64005226-8881d180-cb42-11e9-8302-f26a58b3b2ce.png)

**Comment by nondanee** [comment]
浏览器打开有重定向吗？
有的话加上 `-e http://music.163.com`

**Comment by rexx0520** [comment]
> -e http://music.163.com

似乎沒有重定向

**Comment by rexx0520** [comment]
啊有了
用 -e [我的容器網址] 就通了

**Comment by nondanee** [comment]
emmm 我感觉 `-e http://music.163.com` 和直接写你自己的网址没啥区别啊 =.=

**Comment by rexx0520** [comment]
> emmm 我感觉 `-e http://music.163.com` 和直接写你自己的网址没啥区别啊 =.=

想想好像是這麼回事
剛剛思路是 我沒用 host 模式而是用客戶端內建代理 所以應該填容器網址
然而我忽略了它還是經 proxy 轉發 實際上沒差 (?
總之會動了 yay
