### ISSUE TITLE
Android 食用指南

### ISSUE THREAD

**Issue by 1553497378** [nondanee/UnblockNeteaseMusic#214]
# Android 食用指南

------

<font color=#0099ff size=6 face="黑体">本指南只介绍Android手机端的配置食用方法，</font>

<font color=#0099ff size=6 face="黑体">服务器指南点击</font>
<font size=6 face="黑体">[Windows](https://github.com/nondanee/UnblockNeteaseMusic/issues/22)</font>
<font color=#0099ff size=6 face="黑体">与</font>
<font  size=6 face="黑体">[linux](https://github.com/nondanee/UnblockNeteaseMusic/issues/208)</font>
<font color=#0099ff size=6 face="黑体">的安装配置查看</font>

> ####<font color=blue size=6 face="黑体">Android手机端配置如下：</font>
	1.服务器端启动项目成功后，可以看到下图
><img src="https://user-images.githubusercontent.com/33971782/63929643-5ca01680-ca84-11e9-901b-dba98caeb1ab.png" width = "500" height = "250"  />
	2.打开手机设置，选择SIM卡
><img src="https://user-images.githubusercontent.com/33971782/63930935-db964e80-ca86-11e9-8fc9-ccd5a1f1bf15.jpg" width = "150" height = "250"  />
	3.在SIM卡信息下选择要使用移动网络的SIM卡
><img src="https://user-images.githubusercontent.com/33971782/63930983-efda4b80-ca86-11e9-8c0a-33f11ee989b7.jpg" width = "150" height = "250"  />
	4.在运营商信息下选择APN接入点
><img src="https://user-images.githubusercontent.com/33971782/63931018-04b6df00-ca87-11e9-9baa-4e20ab679d66.png" width = "150" height = "250"  />
	5.点击右上角+新增一个接入点
><img src="https://user-images.githubusercontent.com/33971782/63931056-15ffeb80-ca87-11e9-83fa-6bd4fed7f2eb.png" width = "150" height = "250"  />
	6.名称：随意写,APN:cmwap,代理：192.168.1.1(PS:这里的代理ip地址为公网服务器ip地址),端口：8080,apn类型：default, 其他都不用填 
><img src="https://user-images.githubusercontent.com/33971782/63931091-2b751580-ca87-11e9-8ed8-85c2242cd3be.jpg" width = "150" height = "250"  />
	7.打开网易云音乐后，看到下图^_^成功了
><img src="https://user-images.githubusercontent.com/33971782/63931438-da195600-ca87-11e9-9efd-3a2f757bf7bc.jpg" width = "150" height = "250"  />

> ####PS：若有疑问请在下方留言，我看到后会尽快给大家回复

**Comment by 1553497378** [comment]
其实我是用JP服务器跑的项目，然后用手机连的代理

**Comment by nondanee** [comment]
你再 edit 改下排版吧
还有，最后一张图不说明问题，因为这一页本来就能听 😂

**Comment by 1553497378** [comment]
> 你再编改下排版吧
> 还有，最后一张图不说明问题，因为这一页本来就能😂

好的，是有点丑，晚上回去改下

**Comment by lushann** [comment]
这个是用手机卡数据的食用方式吗?

你这个代理ip `10.0.0.172` ，是内网ip啊, 如果是防止泄漏你JP服务器的IP,随便写了个内网ip的话，可以注明一下。

**Comment by 1553497378** [comment]
> 这个是用手机卡数据的食用方式吗？
> 
> 你这个代理ip `10.0.0.172`，是内网ip啊，如果是防止泄漏你JP服务器的IP，随便写了个内网ip的话，可以注明一下。

这个是手机卡数据食用方法，我用的代理ip为JP服务器公网ip，但也可以为内网ip（PS:如果你用本地主机跑项目，想要用手机连接可能会用到花生壳之类的内网穿透的工具），食用指南正在完善，请各位食客先不要急

**Comment by 1553497378** [comment]
> > 这个是用手机卡数据的食用方式吗？
> > 你这个代理ip `10.0.0.172`，是内网ip啊，如果是防止泄漏你JP服务器的IP，随便写了个内网ip的话，可以注明一下。
> 
> 这个是手机卡数据食用方法，我用的代理IP为JP服务器公网IP，但也可以为内网IP（PS：如果你用本地主机跑项目，想要用手机连接可能会用到花生壳之类的内网穿透的工具），食用指南正在完善，请各位食客先不要急

如果放到服务器上可能还会需要用到守护进程，例如（```nohup || forever || pm2```）等等，[食用教程](http://fengliner.github.io/2014/11/20/node.js%E5%90%8E%E5%8F%B0%E8%BF%90%E8%A1%8C/)

**Comment by lushann** [comment]
我在 #208 中也描述了pm2的针对此工具的相关使用方式

比较期待您的这个使用方法能够达到只针对网易云相关域名进行代理的效果

**Comment by oooldtoy** [comment]
网络连接失败。。。

**Comment by rexx0520** [comment]
其實 ProxyDroid 針對網易雲音樂做代理就行

**Comment by oooldtoy** [comment]
安卓手机还可以用termux做服务端，这样就不需要远程服务器了

**Comment by rexx0520** [comment]
讓 Android 跑這個還是太耗電了唄
建議放在 NAS 上之類的 電腦手機都能用

**Comment by panchao0716** [comment]
ios的好像不能用数据卡，只能连WiFi是嘛

**Comment by 1553497378** [comment]
> 安卓手机还可以用termux做服务端，这样就不需要远程服务器了


> 讓 Android 跑這個還是太耗電了唄
> 建議放在 NAS 上之類的 電腦手機都能用

我这个只是客户端的连接教程，服务端用linux或者windows搭建好环境配置，直接用手机连接就好了，不存在费电这么一说吧，电脑也可以通过服务端ip和port进行连接，并不影响使用

**Comment by 1553497378** [comment]
> ios的好像不能用数据卡，只能连WiFi是嘛

ios好像可以通过代理app来进行连接，好像需要国外的app store账号，我用的Android 手机

**Comment by panchao0716** [comment]
@1553497378 
国外id我倒是有，但是ss已经下架了，除了这个没其他办法吗，Android我倒是知道，本人也是做Android开发的可以自己写个APP走代理隧道就行

**Comment by 1553497378** [comment]
除了ss好像还有好几个别的也可以用的吧，具体有没有下架我也不清楚，网上可以找到免费的国外app store账号，你可以先找个账号进去看看

**Comment by de-conf** [comment]
建议使用openwrt host里面指向你的unlock-netease服务器,
安装旧版的网易云,可以完美解锁,我在豌豆荚下安装的3.8.0可以完美解锁!

**Comment by de-conf** [comment]
啊,好像播放不了,尽管旧版请求的是http,但是好像脚本处理不了

**Comment by Keen-King** [comment]
> > 安卓手机还可以用termux做服务端，这样就不需要远程服务器了
> 
> > 讓 Android 跑這個還是太耗電了唄
> > 建議放在 NAS 上之類的 電腦手機都能用
> 
> 我这个只是客户端的连接教程，服务端用linux或者windows搭建好环境配置，直接用手机连接就好了，不存在费电这么一说吧，电脑也可以通过服务端ip和port进行连接，并不影响使用

能否咨询一下，如何在远程服务器上部署么，我用forever在远程服务器上成功运行了进程，但是在本地调用的时候，还是链接失败
![Snipaste_2019-09-17_16-11-25](https://user-images.githubusercontent.com/53326526/65024414-6a500a00-d967-11e9-9317-a7356078c42a.jpg)
![Snipaste_2019-09-17_16-16-13](https://user-images.githubusercontent.com/53326526/65024415-6ae8a080-d967-11e9-9a4d-5202deb472d6.jpg)

**Comment by ssacpklnm** [comment]
必须要是8080端口吗，在服务端定义其他端口可以吗？还有不管什么运营商都是cmwap吗

**Comment by 1553497378** [comment]
是的，你试试看------------------ 原始邮件 ------------------
发件人: "ssacpklnm"<notifications@github.com>
发送时间: 2019年9月17日(星期二) 下午5:27
收件人: "nondanee/UnblockNeteaseMusic"<UnblockNeteaseMusic@noreply.github.com>;
抄送: "moopro"<1553497378@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [nondanee/UnblockNeteaseMusic] Android 食用指南 (#214)



必须要是8080端口吗，在&#x670D;务端定义其他端口可以吗？还有不管什么运营商都是cmwap吗
 
&mdash;

**Comment by David318** [comment]
> 安卓手机还可以用termux做服务端，这样就不需要远程服务器了

用termux具体应该怎么操作呢，请问能详细指点一下吗

**Comment by oooldtoy** [comment]
> > 安卓手机还可以用termux做服务端，这样就不需要远程服务器了
> 
> 用termux具体应该怎么操作呢，请问能详细指点一下吗

安装termux，然后再termux中安装node.js。
剩下的就和linux中运行app.js一样了。代理地址是127.0.0.1

**Comment by Keen-King** [comment]
> > > 安卓手机还可以用termux做服务端，这样就不需要远程服务器了
> > 
> > 
> > 用termux具体应该怎么操作呢，请问能详细指点一下吗
> 
> 安装termux，然后再termux中安装node.js。
> 剩下的就和linux中运行app.js一样了。代理地址是127.0.0.1

手机端的shell窗口么，我去试试

**Comment by Keen-King** [comment]
我在本地PC上成功了，并且用博客记录了相关的过程。
这是链接：
http://www.clzly.xyz:8080/2019/09/16/%E7%BD%91%E6%98%93%E4%BA%91%E6%8D%A2%E6%92%AD%E6%94%BE%E6%BA%90%E8%A7%A3%E5%86%B3%E6%92%AD%E6%94%BE%E9%97%AE%E9%A2%98/

但是想要在服务器上把dos命令改成对应的sh命令，一直出错，请问有没有人能帮我

@echo off
For /f "skip=1 tokens=2 delims=[" %%a in ('ping  music.163.com') do (
        For /f "tokens=1 delims=]" %%b in ("%%a") do (
                Set ip=%%b
        )
)
cd home/git/1
forever start app.js -p 2333 -f %ip%

**Comment by nondanee** [comment]
@Keen-King
没修改本地 hosts 不用加 `-f`

**Comment by Keen-King** [comment]
> > > 这个是用手机卡数据的食用方式吗？
> > > 你这个代理ip `10.0.0.172`，是内网ip啊，如果是防止泄漏你JP服务器的IP，随便写了个内网ip的话，可以注明一下。
> > 
> > 
> > 这个是手机卡数据食用方法，我用的代理IP为JP服务器公网IP，但也可以为内网IP（PS：如果你用本地主机跑项目，想要用手机连接可能会用到花生壳之类的内网穿透的工具），食用指南正在完善，请各位食客先不要急
> 
> 如果放到服务器上可能还会需要用到守护进程，例如（`nohup || forever || pm2`）等等，[食用教程](http://fengliner.github.io/2014/11/20/node.js%E5%90%8E%E5%8F%B0%E8%BF%90%E8%A1%8C/)

我在服务器上运行了

cd 路径
forever start --minUptime 1000 --spinSleepTime 1000 app.js -p 端口号 223.252.199.66

然后报错如下：
![1](https://user-images.githubusercontent.com/53326526/65232233-63f69500-db03-11e9-9b27-8c20bef21626.jpg)
![2](https://user-images.githubusercontent.com/53326526/65232234-648f2b80-db03-11e9-93c3-820c13321c34.jpg)
已经尝试过forever模块的卸载再安装了。求教

**Comment by yaohunzhanyue** [comment]
直接修改当前APN的代理地址就行了吧？不用新建这么麻烦

**Comment by nondanee** [comment]
@Keen-King 
报错信息不是提示你了吗
```
unblockneteasemusic: error: extra arguments found: 223.252.199.66
```
ip 之前没有 `-f` 啊

还有，你这样根本不需要用 `-f`
只要 forever start --minUptime 1000 --spinSleepTime 1000 app.js -p 端口号，就行了

**Comment by Keen-King** [comment]
> @Keen-King
> 报错信息不是提示你了吗
> 
> ```
> unblockneteasemusic: error: extra arguments found: 223.252.199.66
> ```
> 
> ip 之前没有 `-f` 啊
> 
> 还有，你这样根本不需要用 `-f`
> 只要 forever start --minUptime 1000 --spinSleepTime 1000 app.js -p 端口号，就行了

感谢！完成了

**Comment by xclyisen** [comment]
> > 安卓手机还可以用termux做服务端，这样就不需要远程服务器了
> 
> 用termux具体应该怎么操作呢，请问能详细指点一下吗

termux 资源可以从这里下载 https://download.csdn.net/download/xcl13014673050/11589520 亲测好使!!

**Comment by xiexinxinclimb** [comment]
> > 这个是用手机卡数据的食用方式吗？
> > 你这个代理ip `10.0.0.172`，是内网ip啊，如果是防止泄漏你JP服务器的IP，随便写了个内网ip的话，可以注明一下。
> 
> 这个是手机卡数据食用方法，我用的代理ip为JP服务器公网ip，但也可以为内网ip（PS:如果你用本地主机跑项目，想要用手机连接可能会用到花生壳之类的内网穿透的工具），食用指南正在完善，请各位食客先不要急

想询问下，为什么我试了之后，发现其他一些网站就无法使用了呢，网易是可以用的，其他的不行，有没有好的解决方案

**Comment by nondanee** [comment]
@xiexinxinclimb 
你是不是服务器上开启了严格模式 (加了 `-s`)？这样非网易云所属网站都访问不了，关掉就行了

**Comment by nondanee** [comment]
@1553497378 
我发现内容主要再教如何修改 APN，感觉和项目使用关系不大，所以就不保留了哈

个人建议
可以 "复制" 正在用的 APN 配置，加上代理服务器后新建一个 APN 
(因部分预制 APN 无法修改，比如 电信的 ctnet，只能新建)
