### ISSUE TITLE
ios端最新版已经挂了

### ISSUE THREAD

**Issue by su3817806** [nondanee/UnblockNeteaseMusic#215]
简单看了下好像会检测返回的url。如果是第三方的就会播放失败。。替换成163的就正常。

**Comment by nondanee** [comment]
"替换成163" 是什么意思啊？

**Comment by su3817806** [comment]
就是替换成m8.music.126.com  这个网易云解析的地址就可以。如果是qq音乐或者其他解析的就会出错。

**Comment by nondanee** [comment]
没有替换成 m8 开头的地址啊？你说的应该是网易服务器自己返回的地址 (本来就能听的那种)

**Comment by su3817806** [comment]
就是ios现在替换成其他的播放地址会出异常，必须返回网易云自己的地址才醒。

**Comment by zxx617117476** [comment]
我测试了windows和安卓的客户端都能正常听歌
就是IOS会显示  播放失败 网络不给力 无法继续播放
关于IOS网易云音乐的版本我测试了 6.3.2  6.3.1  6.2.5  6.2.3均无法播放

**Comment by u3u** [comment]
目前 iOS 听不了应该和客户端版本无关 我也测试过在之前能用的版本中也会提示网络不给力
推测是在播放前都会统一调用某个接口（一直都存在 可能是用来验证版权或跟踪网络状态之类的）
然后这个接口现在加了白名单策略 只有来自白名单域名的音频地址允许播放 所以都挂了

**Comment by bigNeoneo** [comment]
我也遇到这个问题了   `node app.js -p 17541 -e http://music.163.com`  这样就没问题，但是从其他源（除了163）的歌曲就下载失败，但是播放倒是没问题，然而 我不加-e 163这个。就任何歌都下载不了

**Comment by nondanee** [comment]
@bigNeoneo 
咦，你加了 `-e http://music.163.com` 就能听吗？
你的版本是多少啊？不少人说用不了，我什么都不知道 =.=

下载失败可以多重试几次，因为需要计算 md5，请求 pending 了，整首歌下完才返回
要计算 md5 的具体原因看 👉 #98 
因为移动端有做超时，等不及就直接报下载失败了，重试应该就行

不加 `-e` 任何歌都下不了我好像没法解释......

**Comment by vft9nesd** [comment]
> 我也遇到这个问题了 `node app.js -p 17541 -e http://music.163.com` 这样就没问题，但是从其他源（除了163）的歌曲就下载失败，但是播放倒是没问题，然而 我不加-e 163这个。就任何歌都下载不了

加`-e`完全无用啊， log链接可用，手机提示网络不给力
`MITM > 59.111.160.195 
[418602084] 说走就走
http://aqqmusic.tc.qq.com/amobile.music.tc.qq.com/M5000039ETYY01xVZo.mp3?vkey=B9E022E1FA43594EA1EC9D8940427D43C807ACE06606F05CD5EAF9D336B25A31C95335A84D27B026CC36CA5B9706C994F07EAA4E1735F3A1&uin=0&fromtag=8&guid=7332953645
MITM > 59.111.160.195 
MITM > 59.111.160.195 
`

**Comment by cccccpppppp** [comment]
我在vps上 `node app.js -p 80:443 -s -e http://music.163.com`然后Windows客户端设置代理没问题，但是苹果只能用手动代理模式，pac模式失效：
```
MITM > interface.music.163.com 
TUNNEL > localhost:443
MITM > music.163.com (ssl)
```

**Comment by panchao0716** [comment]
@cccccpppppp 你好，请问下手动代理对服务器和端口有什么要求吗

**Comment by cccccpppppp** [comment]
> @cccccpppppp 你好，请问下手动代理对服务器和端口有什么要求吗
https://github.com/nondanee/UnblockNeteaseMusic/issues/65#issuecomment-493718439
这里大佬说的很详细了

> 启动命令改为 node app.js -p port1:port2（port2 是用来内部转发的 https 端口），在 WiFi 设置里开启 http 代理，手动，填 IP 端口号 port1

端口应该没什么特别要求吧，我喜欢用80:443

**Comment by huangxd-** [comment]
ios还有救吗

**Comment by PingXD** [comment]
= =想知道IOS还有救么。。。没救我就换手机了 HAH

**Comment by gqbre** [comment]
我。。一直都可以。。刚清了缓存试过 iOS 最新版

**Comment by panchao0716** [comment]
@gqbre 你ios是用什么方法的全局代理不行了吧

**Comment by gqbre** [comment]
> @gqbre 你ios是用什么方法的全局代理不行了吧

https://github.com/nondanee/UnblockNeteaseMusic/issues/137

**Comment by huangxd-** [comment]
> > @gqbre 你ios是用什么方法的全局代理不行了吧
> 
> #137

难道是因为https？

**Comment by One0627** [comment]
node /usr/local/UnblockNeteaseMusic/app.js -p 自定义端口:443 -e https://music.163.com

 iPhone 用shadowrocket 代理成功 配置 和证书 记得弄
![image](https://user-images.githubusercontent.com/42073125/65358374-fb570780-dc2b-11e9-8e27-091874101b15.png)

**Comment by panchao0716** [comment]
@One0627 大佬能借下你的苹果id下个shadowrocket 吗

**Comment by waf2311** [comment]
> @One0627 大佬能借下你的苹果id下个shadowrocket 吗

微信小程序搜  大灰  ，里面搜火箭，看10s广告就能给你账号密码。

**Comment by huangxd-** [comment]
> node /usr/local/UnblockNeteaseMusic/app.js -p 自定义端口:443 -e https://music.163.com
> 
> iPhone 用shadowrocket 代理成功 配置 和证书 记得弄
> ![image](https://user-images.githubusercontent.com/42073125/65358374-fb570780-dc2b-11e9-8e27-091874101b15.png)

还是不行，网易云vip的可以下载，但是灰的变黑之后还是不能听或者下载，放弃...

**Comment by gqbre** [comment]
刚刚发现凉了。。一样出现了网络不给力的问题

**Comment by gqbre** [comment]
这次是真不行了，服务端日志显示能匹配到 QQ 音乐的音源，但就是提示网络不给力，退出重新登录也不行，Mac 端正常。之前一样的启动参数是可以的，不用自签证书换用仓库的证书也试了还是不行。大佬有空看看

**Comment by gqbre** [comment]
iOS 报网络不给力的试试加上 -e https://music.163.com，多半是这个原因

**Comment by Taosky** [comment]
应该是音源没有证书吧，我用pac + https反代音源是可以的。

**Comment by huangxd-** [comment]
> 应该是音源没有证书吧，我用pac + https反代音源是可以的。

求教具体怎么操作？

**Comment by Taosky** [comment]
> 
> 
> > 应该是音源没有证书吧，我用pac + https反代音源是可以的。
> 
> 求教具体怎么操作？

按照[这个指南](https://github.com/nondanee/UnblockNeteaseMusic/issues/65)配置音源就可以了。
