### ISSUE TITLE
建议增加网络连通性判断

### ISSUE THREAD

**Issue by mlgexyz** [nondanee/UnblockNeteaseMusic#216]
我家路由设置的凌晨4点自动重启，然后每天4点程序都会报错说DNS查不到

> Error: getaddrinfo EAI_AGAIN music.httpdns.c.163.com:80
    at Object._errnoException (util.js:1022:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'music.httpdns.c.163.com',
  host: 'music.httpdns.c.163.com',
  port: 80

**Comment by nondanee** [comment]
那检查了如果不通的话应该怎么做呢？
不启动？还是强行启动？
报错的话默认会 exit

**Comment by mlgexyz** [comment]
可否添加一个参数，无网络等待时长，默认为0，可选开启。
由于我是在程序长时间运行时突然报错的，如果有个等待时长的话，就可以先返回一个404状态，然后开始计时，如果限制时间内一直有请求的话，都先404，限制时间内网络恢复的话就继续正常运行，否则退出

**Comment by nondanee** [comment]
music.httpdns.c.163.com 只在代理启动的时候请求，运行时不会请求的
不太懂你说的 "无网络等待时长" 是什么意思 =.=

**Comment by mlgexyz** [comment]
刚才测试了一下，发现不是这个项目的问题，因为我程序是用[luci-app-unblockmusic](https://github.com/maxlicheng/luci-app-unblockmusic)放在路由器上的，然后这个luci插件会判断wan口状态，状态被改变就会重启，由于我主路由凌晨4点自动重启，从路由上放着luci-app-unblockmusic，连接方式采用AP中继，而一般AP中继完成时主路由的PPPoE拨号还没有完成，然后程序就报错了，没事没事，不是本体项目的锅

**Comment by nondanee** [comment]
👌
