### ISSUE TITLE
windows貌似挂了

### ISSUE THREAD

**Issue by LeoMalik** [nondanee/UnblockNeteaseMusic#217]
![image](https://user-images.githubusercontent.com/37207385/64031268-a539fb80-cb7a-11e9-8f5e-7cc7d1264b04.png)
![image](https://user-images.githubusercontent.com/37207385/64031169-74f25d00-cb7a-11e9-81ad-579ae3679c56.png)

还不知道具体原因是啥。

**Comment by nondanee** [comment]
或许你需要更新一下版本

**Comment by ActiveIce** [comment]
我clone了最新的，Windows端和安卓端都挂了，源是kuwo qq
