### ISSUE TITLE
Android手机使用代理的方式，打开云音乐客户端的个人中心时数据加载失败

### ISSUE THREAD

**Issue by zhoululu** [nondanee/UnblockNeteaseMusic#219]
![25076324b9eddfa4678c73c33b7cf1a](https://user-images.githubusercontent.com/11639934/64058070-2e335000-cbd8-11e9-919b-d064728e7e87.jpg)
点击“加载失败，请点击重试后”的终端工具打印信息如下
![捕获1](https://user-images.githubusercontent.com/11639934/64058096-96823180-cbd8-11e9-98d5-c0203423a86a.PNG)

**Comment by zhoululu** [comment]
个人中心页面的音乐tab下面显示“加载失败，请点击重试”

**Comment by nondanee** [comment]
https://github.com/nondanee/UnblockNeteaseMusic/issues/30#issuecomment-472538422
