### ISSUE TITLE
Windows客户端显示“加载失败”

### ISSUE THREAD

**Issue by riiyn** [nondanee/UnblockNeteaseMusic#220]
但是音源链接在网页打开可以播放，日志：
```
[415792916] 床边故事
http://aqqmusic.tc.qq.com/amobile.music.tc.qq.com/M500003LI1En1SErCk.mp3?vkey=2A1E964944F4882EA5472C841D20EA50E3AA778E40484FF085B4100118F69C15D14F263828E4950DCCBC27AD591F5ED04DA138855EBE44F2&uin=0&fromtag=8&guid=7332953645
MITM > music.163.com
MITM > music.163.com
MITM > music.163.com
MITM > music.163.com
TUNNEL > p4.music.126.net:443
TUNNEL > p3.music.126.net:443
MITM > music.163.com
TUNNEL > p4.music.126.net:443
TUNNEL > p4.music.126.net:443
TUNNEL > p3.music.126.net:443
TUNNEL > p4.music.126.net:443
TUNNEL > p4.music.126.net:443
TUNNEL > p3.music.126.net:443
TUNNEL > p3.music.126.net:443
TUNNEL > p3.music.126.net:443
MITM > music.163.com
MITM > music.163.com
MITM > music.163.com
MITM > music.163.com
```

大佬知道什么原因吗

**Comment by ActiveIce** [comment]
我也遇到了同样的情况，在Windows客户端

**Comment by nondanee** [comment]
你是不是加了 `-s` ?

**Comment by riiyn** [comment]
> 你是不是加了 `-s` ?

是的，之前也加了都没事，今天突然就不行了，是这个原因吗

**Comment by ActiveIce** [comment]
没有加-s
刚才短暂好了几次，然后又不行了，只看到解析的地址，不能播放。解析的地址直接粘贴到浏览器可以听。
感觉这问题是间歇性的




------------------ 原始邮件 ------------------
发件人: "riiyn"<notifications@github.com>;
发送时间: 2019年8月31日(星期六) 下午2:12
收件人: "nondanee/UnblockNeteaseMusic"<UnblockNeteaseMusic@noreply.github.com>;
抄送: "1053544791"<1053544791@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [nondanee/UnblockNeteaseMusic] Windows客户端显示“加载失败” (#220)



 
你是不是加了 -s ?
  
是的，之前也加了都没事，今天突然就不行了，是这个原因吗

**Comment by nondanee** [comment]
0.16.0 以前的版本没这个问题
"今天突然就不行了"那么你今天升级过了？

0.16.0 之后的版本严格模式下要加 `-e http://music.163.com`

**Comment by nondanee** [comment]
@ActiveIce 
那就不清楚了，我这边挺正常的

**Comment by riiyn** [comment]
@nondanee 今天刚升级到最新。。。谢谢大佬解惑：）

**Comment by Zhujion** [comment]
更新了项目，但是问题一样存在，各位大佬怎么解决的了
