### ISSUE TITLE
服务器docker失效

### ISSUE THREAD

**Issue by ssacpklnm** [nondanee/UnblockNeteaseMusic#221]
之前还可以，windows网易云客户端，自定义代理，现在首页图片什么的都可以加载，只有听歌的时候例如周杰伦的显示加载失败

**Comment by nondanee** [comment]
你看一眼版本？
```sh
docker start nondanee/unblockneteasemusic -v
```

**Comment by ssacpklnm** [comment]
> 你看一眼版本？
> 
> ```shell
> docker start nondanee/unblockneteasemusic -v
> ```

docker start并没有-v这个命令

**Comment by nondanee** [comment]
@ssacpklnm 
```
docker run nondanee/unblockneteasemusic -v
```

**Comment by bes1355** [comment]
同失效了，歌曲不会灰但是都是加载失败。

**Comment by nondanee** [comment]
@bes1355 
同问版本多少，不是最新版请 `docker pull`

**Comment by ssacpklnm** [comment]
我明天试一下，晚上用 #222 的脚本试了一下，还可以用，但是加载非常慢，不知道原因，谢谢帮助！

**Comment by nondanee** [comment]
@ssacpklnm 
docker 版本是 release 时 ci build 的，跟仓库代码没有区别
不会自动更新，需要手动 pull
用 docker 失效了说明这个项目失效了，前几天默认配置确实是失效了 https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-524400435
所以如果你 #222 可用那 docker 一定可用

加载慢我没办法，放到本地或者局域网部署应该就不慢了
