### ISSUE TITLE
Linux代理下网易云音乐提示无网络

### ISSUE THREAD

**Issue by Sunshine018** [nondanee/UnblockNeteaseMusic#223]
本人Ubuntu 18.04.3 LTS，仔细阅读了README.md和所有相关pinned的issue，严格按照每一步操作，但是上了代理（系统代理工具）之后打开网易云音乐会提示网络断开，而使用ss-qt5时所有的应用都不过代理

请问Linux下个人使用时我应该做什么？如果不使用系统自带的代理工具使用ss-qt5我应该怎么配置？

**Comment by Sunshine018** [comment]
看了一下关闭的issues，我发现相同问题了，再去配置一下
我先把issue关了，还不行再打开

**Comment by nondanee** [comment]
#208 看过吗？

**Comment by Sunshine018** [comment]
> #208 看过吗？

看过了，后来我又看了#48 ，发现证书配置有误，正在重试

**Comment by Sunshine018** [comment]
> > #208 看过吗？
> 
> 看过了，后来我又看了#48 ，发现证书配置有误，正在重试

当时以为证书出来以后直接就可以完成，没想到我只把ca.crt 装了没有把另外的两个证书和密钥覆盖掉XD

**Comment by nondanee** [comment]
好的👌

**Comment by Sunshine018** [comment]
> 
> 
> 好的ok_hand

放弃Linux了，现在在用Windows，成功
