### ISSUE TITLE
网易云不行了么?

### ISSUE THREAD

**Issue by xman55555** [nondanee/UnblockNeteaseMusic#224]
win版本 网易云2.5.5 197810  搜索歌曲 没有置灰,但是播放不了
![网易](https://user-images.githubusercontent.com/3001600/64073929-450c9c00-ccd7-11e9-966e-036c0c708688.png)

**Comment by nondanee** [comment]
提供一下 log

**Comment by guduwenjiu** [comment]
我也是这样 
这个链接是有效的,放在浏览器可以播放

MITM > interface.music.163.com 
[185815] 蒲公英的约定
http://aqqmusic.tc.qq.com/amobile.music.tc.qq.com/M50000140o6q3Jvfzr.mp3?vkey=98083C4F7687F6DC2F2921B3869873F4C53F406EEE7CDD529EBA4B4CACB1DA3AF51500DDED1128F125A14AC1BF0759100663DDCF23B326A8&uin=0&fromtag=8&guid=7332953645
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > m8.music.126.net 
MITM > clientlog.music.163.com

**Comment by panchao0716** [comment]
我的也是跟楼主一样加载失败但是我的log并没有二楼那个链接
![image](https://user-images.githubusercontent.com/35394467/64091741-3cbe6a80-cd84-11e9-84e5-d20a74a0d59d.png)

**Comment by guduwenjiu** [comment]
> 我的也是跟楼主一样加载失败但是我的日志并没有二楼那个链接
> ![图片](https://user-images.githubusercontent.com/35394467/64091741-3cbe6a80-cd84-11e9-84e5-d20a74a0d59d.png)

**Comment by nondanee** [comment]
@guduwenjiu 
那你是加了 `-s` 吗？加了 `-s` 的话，还需要 `-e http://music.163.com`

**Comment by nondanee** [comment]
@panchao0716 
你可能需要更新一下

**Comment by panchao0716** [comment]
大佬，，那目前ios设置全局代理那个不行了吗

**Comment by guduwenjiu** [comment]
> @guduwenjiu
> 那你的英文加了`-s`吗？了加`-s`的话教育，还需要`-e http://music.163.com`

加上参数之后和三楼一样了 log里面不显示了,但还是加载失败

**Comment by nondanee** [comment]
@panchao0716 
是 iOS 啊，那不清楚了，理论上匹配应该是没问题的，能不能播放我不知道

**Comment by nondanee** [comment]
@guduwenjiu 
不会吧？log 显示匹配结果和加不加 `-e`, `-s` 没关系，你再试试看

**Comment by panchao0716** [comment]
@nondanee 
Windows上可以，但是我通过PAC 全局自动代理设置了服务器地址和端口在ios上面显示网络不给力无法播放

**Comment by nondanee** [comment]
@panchao0716 
嗯 iOS 我确实不清楚能不能用，没有设备所以没法测试 #137 #215

**Comment by geekfaith** [comment]
Mac 上也不行 提示网络不给力

**Comment by nondanee** [comment]
@geekfaith
你这个问题不太一样，应该新开一个 issue 吧？
README 里写了 https://github.com/nondanee/UnblockNeteaseMusic#使用

> macOS 客户端 (726 版本以上需要自签证书)

macOS 客户端使用有要求，自签证书相关看这个 👉 https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-477870013

**Comment by geekfaith** [comment]
好的

**Comment by shugo-chara** [comment]
@nondanee 
反馈一下。

在开启中继模式的严格模式下，如果只加 -s参数的话，mac客户端正常播放，android客户端测试无法播放，logs能抓到地址但是手机上显示无法缓冲。

添加 -s -e http://music.163.com/ 后手机端当时也可以正常播放，但中继功能会消失，全部跳转回qq音源。 

如果使用中继的话，不能开启严格模式，否则要么会无法缓冲，要么中继会失效。
网易云版本：mac 2.1.1（790）  android 6.40

**Comment by nondanee** [comment]
@shugo-chara 
中继是 match 里的逻辑，和 `-s` `-e` 没关系的，不影响的

严格模式下其它音源链接受限，需要基于主机名的代理规则 (PAC 或改 hosts)
UA 规则和分应用代理都会把音源请求发到代理服务器，然后被 ban
