### ISSUE TITLE
中继RPC部署过程和疑问

### ISSUE THREAD

**Issue by shugo-chara** [nondanee/UnblockNeteaseMusic#226]
锅内的小水管服务器缓冲实在太慢了，参考了你回答的好几个issues，试着使用RPC中继，但是不知道是否搭建成功了。
目前试了下jay的歌曲，缓冲文件里还是只有3m左右的渣音质。

部署情况：

锅内服务器A
国外服务器B

在服务器A上的docker只运行了Bridge.js，端口2333（docker ps：8080-8081/tcp, 0.0.0.0:8080->2333/tcp）。
并且已经提前在服务器A里 //注释了provider/insure.js里的if(path != 'qq/ticket') return Promise.reject() 这行
同时在match里修改了音源优先级。
![image](https://user-images.githubusercontent.com/20610965/64151588-b1b5a100-ce65-11e9-9575-e625c2e3f0ea.png)
![image](https://user-images.githubusercontent.com/20610965/64152013-9dbe6f00-ce66-11e9-9fa1-8f602c4b638b.png)
***************************************
然后在服务器B上的docker里运行了app.js并修改音源优先级（node app.js -o kugou kuwo xiami migu joox），端口默认。并且已经在服务器B里的insure.js里把host改为了服务器A的ip:2333.
![image](https://user-images.githubusercontent.com/20610965/64152148-f4c44400-ce66-11e9-94b5-ff3c50160ad6.png)
***************************************
然后客户端直接使用服务器B的ip:port。
测试发现歌曲能正常听，但是不确定是不是有走锅内的中继。
试了下jay的歌看缓存只有3m，好像还是只有128kbps的样子，我的音源顺序已经剔除了qq，如果正常的话不是应该能请求到320的吗。

所以请问下我这个部署步骤是正确的吗，如果有问题的话要怎么改。

**Comment by nondanee** [comment]
`if(path != 'qq/ticket') return Promise.reject()` 的注释应该在服务器 B 做，A 不用

看 url 就能判断是哪家的音源了
目前有 320k 的只有 kuwo，migu，joox
baidu 没什么用，xiami 没法用，joox 限定港澳东南亚，用不上的话就不要加了

刚测了下发现 migu 挂掉了，改了 API 字段要等我修一下

**Comment by shugo-chara** [comment]
> `if(path != 'qq/ticket') return Promise.reject()` 的注释应该在服务器 B 做，A 不用
> 
> 看 url 就能判断是哪家的音源了
> 目前有 320k 的只有 kuwo，migu，joox
> baidu 没什么用，xiami 没法用，joox 限定港澳东南亚，用不上的话就不要加了
> 
> 刚测了下发现 migu 挂掉了，改了 API 字段要等我修一下

谢谢。
刚才取消了A的注释，对B进行了注释。音源的话重新排了下只留了kuwo，migu，joox了。
看了下jay的歌还都是3-4m。

ps，用的bt面板里安装docker，想看日志是不是正常中继了，但是不知道要在那哪里看- -。。。

**Comment by shugo-chara** [comment]
@nondanee 
弄了一下午，重新把两台服务器都重置了，音源顺序全都在match里修改为一致，docker里不添加其他命令。
现在都搭好后歌曲显示黑色，但是播放全部网络错误。
不用中继的话，单独用都没问题，头都绕晕了。。

![image](https://user-images.githubusercontent.com/20610965/64166474-272f6a80-ce82-11e9-9ce4-a346a8f6c920.png)

**Comment by shugo-chara** [comment]
@nondanee 
注释修改后被docker的端口映射跟“音源排序”坑了一下午。后来本体在pm2里运行解决了端口问题。

注释和host都在国外服务器B里进行。

弄到最后中继还是没起作用，单独用国内服务器的话是可以看到走别的源的，开启中继后，国外服务器里还全部都是qq。match里如果把qq音源注释掉的话就会提示网络错误，无法播放，所以推断是中继没出问题。
![image](https://user-images.githubusercontent.com/20610965/64171490-c7d75780-ce8d-11e9-9da4-e255cbc8e61f.png)
不知道是哪里出问题了。

ps。bridge.js无法用pm2管理器运行，会自动关闭。但是app.js可以用管理器运行。

**Comment by nondanee** [comment]
是的
增加注释和修改 host 都在服务器 B 上做
A 上只要 `node bridge.js 2333` 就好了
为啥不能用 pm2 呢？是端口冲突吗，`pm2 log ...` 显示了啥？
默认端口 9000，用 `pm2 start bridge.js -- 2333` 可以带参启动
访问 `<host>/qq/ticket` 可以测一下中继有没有开起来

国外服快速测试 (直接调方法)
```sh
cd UnblockNeteaseMusic
node
```

```js
test = require('.')
test(185670, ['kuwo']).then(console.log)
test(185670, ['kugou']).then(console.log)
```

测了下 migu 不用中继
kugou 能听的好像也很少了

**Comment by shugo-chara** [comment]
> 是的
> 增加注释和修改 host 都在服务器 B 上做
> A 上只要 `node bridge.js 2333` 就好了
> 为啥不能用 pm2 呢？是端口冲突吗，`pm2 log ...` 显示了啥？
> 默认端口 9000，用 `pm2 start bridge.js -- 2333` 可以带参启动
> 访问 `<host>/qq/ticket` 可以测一下中继有没有开起来
> 
> 国外服快速测试 (直接调方法)
> 
> ```shell
> cd UnblockNeteaseMusic
> node
> ```
> 
> ```js
> test = require('.')
> test(185670, ['kuwo']).then(console.log)
> test(185670, ['kugou']).then(console.log)
> ```
> 
> 测了下 migu 不用中继
> kugou 能听的好像也很少了

感谢提醒，试了下9000默认端口终于终于终于可以连上了。不知道为啥自定义端口就不行，用在app.js上就能访问。防火墙已经放行了，不过现在默认能用就行了。
今天pull了新版，就把migu的音源最优先了。不过发现我听的无版权的歌居然都用kuwo的源，因为小众么- -
![image](https://user-images.githubusercontent.com/20610965/64228362-842e2d80-cf21-11e9-9dd4-beee3c6701f6.png)
**********************************
bridge这边看日志有个xiami的错误，不过不影响中继使用。
![image](https://user-images.githubusercontent.com/20610965/64229090-c9535f00-cf23-11e9-8fae-334ae92e2cb1.png)

**Comment by nondanee** [comment]
@shugo-chara 
大概是咪咕日文歌资源比较匮乏吧，都去匹配酷我了
底下 `SyntaxError: Unexpected identifier` 这个错误应该是 13 行少了个逗号，可能你修改的时候没注意到

**Comment by shugo-chara** [comment]
@nondanee 
检查了bridge的内容没问题，预防万一又删掉重新拉了一遍还是报错。不知道是不是宝塔的node问题。查了下好像node环境也会引起这个错误。放着不管会影响中继吗？

****************************************

另一个就是 app.js -s 的严格模式是只过滤网易云吗，跟朋友一起用但是看log里一堆乱七八糟的访问。
运行 pm2 start app.js -s -p 2333后，pm2管理器里显示还是8080端口，而且看logs里还是会记录所有的一堆的请求。
![image](https://user-images.githubusercontent.com/20610965/64316738-a93da180-cff0-11e9-9d09-8c4fbd06f1c5.png)
请问有什么办法能把这些请求过滤掉吗，让它只用于网易云。

**Comment by nondanee** [comment]
@shugo-chara 
https://github.com/nondanee/UnblockNeteaseMusic/blob/b3b8ba7b73a99a18b3d5527d3bd15934b90c2b27/bridge.js#L14
仓库里报错第 14 行是个空行啊，你试下重新 clone 或者 reset --hard 吧

对的严格模式只放行网易云
pm2 start 加参数要带上 `--`
这样 `pm2 start app.js -- -s -p 2333`

**Comment by shugo-chara** [comment]
@nondanee 
= =我reset --hard和重新clone都试过了，我觉得我的智商可能基本告别自行车了。。

目前的状态：
![image](https://user-images.githubusercontent.com/20610965/64318973-48b16300-cff6-11e9-8747-5052a5470ce9.png)

14行确实是有空格的，你的代码里14行也是空格。。

**Comment by nondanee** [comment]
@shugo-chara 
把旧的 delete 掉再 start
`pm2 delete bridge`

**Comment by shugo-chara** [comment]
@nondanee 
是的。每次都是在pm2管理器面板里删掉后重新运行的。
预防万一这次直接在终端里删掉然后在运行还是不行，怀疑是宝塔自身配置的问题导致的。

**Comment by nondanee** [comment]
@shugo-chara 
我懂了，那是历史日志 😂
`pm2 start` 之前 `pm2 flush`

报那个语法错误的话程序根本起不来的

**Comment by shugo-chara** [comment]
@nondanee 
哦哦哦哦哦哦哦哦哦，这次解决了。
pm2 flush后重新start bridge后好像没报错了。nondanee pro。

![image](https://user-images.githubusercontent.com/20610965/64327262-5c64c580-d006-11e9-8339-7588f91a72f2.png)

治好了强迫症。
