### ISSUE TITLE
docker compose 的方式部署怎么添加 -s 等参数呢

### ISSUE THREAD

**Issue by FirstJavaMaster** [nondanee/UnblockNeteaseMusic#227]
readme和issues里都没有找到方法

**Comment by nondanee** [comment]
有是有，就是比较难找
Q: https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-518000452
A: https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-518005599

参考 https://stackoverflow.com/questions/37366857/how-to-pass-arguments-to-entrypoint-in-docker-compose-yml

**Comment by FirstJavaMaster** [comment]
> 有是有，就是比较难找
> Q: [#22 (comment)](https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-518000452)
> A: [#22 (comment)](https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-518005599)
> 
> 参考 https://stackoverflow.com/questions/37366857/how-to-pass-arguments-to-entrypoint-in-docker-compose-yml

非常感谢. 一看就明白了
