### ISSUE TITLE
请教一个小问题, 关于精准分流

### ISSUE THREAD

**Issue by wewall** [nondanee/UnblockNeteaseMusic#229]
https://github.com/nondanee/UnblockNeteaseMusic/blob/master/app.js#L70
[https://github.com/nondanee/UnblockNeteaseMusic#方法-1-修改-hosts](https://github.com/nondanee/UnblockNeteaseMusic#%E6%96%B9%E6%B3%95-1-%E4%BF%AE%E6%94%B9-hosts)
已经尝试把SSR和本软件结合使用, 以达到链接SSR即可解锁网易云无需多余配置,
现有一个问题,假如本机全局设置了代理, 那么网页 music.163.com 是无法打开的

```bash 
<Server IP> music.163.com
<Server IP> interface.music.163.com
```

想问一下,这两个域名我们的HTTP代理用到了那些URL路径

**Comment by nondanee** [comment]
默认配置下网页版不可用，因为
> 默认配置下本代理对网易云所有 HTTPS API 连接返回空数据，促使客户端降级使用 HTTP 接口 

> 支持 ...... 和网页版 (需要自签证书，需要脚本配合)

参见 README https://github.com/nondanee/UnblockNeteaseMusic#使用


具体哪些 url 我也说不清楚，你可以看下 if 的条件
https://github.com/nondanee/UnblockNeteaseMusic/blob/e35b6b9a5f7619713d1707b82bc844ae688dd678/hook.js#L70

https://github.com/nondanee/UnblockNeteaseMusic/blob/e35b6b9a5f7619713d1707b82bc844ae688dd678/hook.js#L102

https://github.com/nondanee/UnblockNeteaseMusic/blob/e35b6b9a5f7619713d1707b82bc844ae688dd678/hook.js#L106

https://github.com/nondanee/UnblockNeteaseMusic/blob/e35b6b9a5f7619713d1707b82bc844ae688dd678/hook.js#L186

https://github.com/nondanee/UnblockNeteaseMusic/blob/e35b6b9a5f7619713d1707b82bc844ae688dd678/hook.js#L206

在启动时 hook.target.host 会根据 httpdns 的返回数据更新一次

https://github.com/nondanee/UnblockNeteaseMusic/blob/e35b6b9a5f7619713d1707b82bc844ae688dd678/app.js#L76

**Comment by wewall** [comment]
十分感谢提供帮助
