### ISSUE TITLE
运行一段时间后会 crash

### ISSUE THREAD

**Issue by toooonyy** [nondanee/UnblockNeteaseMusic#23]
OS: macOS Mojave
node: 10.9.0
一般用 screen 挂着当后台程序，改 hosts 的模式。
log
```

Server running @ http://0.0.0.0:80
...
HTTP > http://music.163.com
HTTP > http://music.163.com
HTTP > http://music.163.com
HTTPS > https://alogs.umeng.com:443
HTTP > http://www.localnetwork.uop
events.js:167
      throw er; // Unhandled 'error' event
      ^
Error: read ECONNRESET
    at TCP.onread (net.js:660:25)
Emitted 'error' event at:
    at Socket.onerror (_stream_readable.js:690:12)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by nondanee** [comment]
收到，搜了下应该是这个问题
[alibaba/anyproxy #427 fix crashing issue when connection is reset](https://github.com/alibaba/anyproxy/pull/427)

不太确定，好像是http connect的错误
但是log显示感觉是个http request引起的
我修修看

BTW，你这是hosts模式吗？hosts下不该有除了网易云之外的请求吧😂

**Comment by toooonyy** [comment]
嗯，本机是的。但还有同局域网的移动设备走了代理

**Comment by nondanee** [comment]
加上了 socket error 的监听 [server.js#L75](https://github.com/nondanee/UnblockNeteaseMusic/blob/master/server.js#L75) 麻烦试试能不能解决
这次有比较多更新，拖了几天处理，抱歉 (可能bug更多了😢)

**Comment by toooonyy** [comment]
经过几天的使用，应该是不会 crash 了。
