### ISSUE TITLE
windows下与服务器连接建立失败

### ISSUE THREAD

**Issue by Times125** [nondanee/UnblockNeteaseMusic#234]
{ Error: connect ETIMEDOUT 59.111.21.13:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '59.111.21.13',
  port: 443 }

**Comment by piggone** [comment]
遇到了同样的问题，不知道该怎么解决.

**Comment by XceeLent** [comment]
Error: connect ETIMEDOUT 59.111.21.13:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1126:14) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '59.111.21.13',
  port: 443
}
昨天还好好的 今天突然就不行了 以为是挂了vpn的问题 把vpn关掉后也不行 现在其他网易云能听的歌也听不了了 提示没有网络连接
