### ISSUE TITLE
macOS 虽然双击播放提示“已开始播放”，但是并没有

### ISSUE THREAD

**Issue by lowking** [nondanee/UnblockNeteaseMusic#238]
![image](https://user-images.githubusercontent.com/33308659/64871215-59f21380-d677-11e9-975a-2fc9efa12630.png)

**Comment by lowking** [comment]
是不是资源有问题？有的歌曲可以有的不行

**Comment by nondanee** [comment]
这首网易有版权啊？播放肯定没问题的
https://music.163.com/#/song?id=452613551
提示网络不给力？
麻烦贴一下日志

**Comment by lowking** [comment]
> 这首网易有版权啊？播放肯定没问题的
> https://music.163.com/#/song?id=452613551
> 提示网络不给力？
> 麻烦贴一下日志

之前试了半小时，都不行，现在重新试了下，想看日志结果可以了
你说的日志是这个吗？还是有其他地方输出日志？
![image](https://user-images.githubusercontent.com/33308659/64873790-6dec4400-d67c-11e9-8704-64d057b47f03.png)

**Comment by nondanee** [comment]
是的
你这个版本可以不装证书直接用吗？好神奇

**Comment by lowking** [comment]
> 是的
> 你这个版本可以不装证书直接用吗？好神奇

![image](https://user-images.githubusercontent.com/33308659/64874378-798c3a80-d67d-11e9-8643-a32ea5e55522.png)
不知道你说的证书是不是这个，之前用ssh连接的时候设置过

**Comment by nondanee** [comment]
不是

那你现在可以用吗？

**Comment by lowking** [comment]
可以啊，正在用

**Comment by nondanee** [comment]
客户端版本号是多少？

**Comment by lowking** [comment]
![image](https://user-images.githubusercontent.com/33308659/64874742-3bdbe180-d67e-11e9-8634-4251afcbe394.png)
应该是最新的，刚买的电脑

**Comment by nondanee** [comment]
好的，那我 close 了？

因为之前有 macOS 客户端无法降级的问题 https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-477870013

不过 700 之后这些版本我都没测试过 =.=

2.0.0 (730)
2.1.0 (774)
2.1.0 (782)
2.1.0 (786)
2.1.1 (790)
2.1.2 (796)
