### ISSUE TITLE
公网部署是否有加密方式

### ISSUE THREAD

**Issue by SustechJoy** [nondanee/UnblockNeteaseMusic#239]
application已部署到公网，本地使用windows客户端，由于api对公网开放，有安全隐患，请问公网部署是否有加密方式。

**Comment by nondanee** [comment]
可以部署在本地，没有强制要求部署在公网
这是个 proxy，不是 api
proxy 没啥安全隐患 (http 无状态我也没缓存)，不过有被滥用的风险

http proxy 是明文的不支持加密
你可以[用 goproxy 转成 ss](https://www.lajiblog.com/index.php/archives/4/)，或者加上受信任证书变成 https 代理 (tls 有加密)

http proxy 可以加认证 (proxy authentication) 但是 Windows 客户端用不了 https://github.com/nondanee/UnblockNeteaseMusic/issues/30#issuecomment-455782470

README 里说了
> 若将服务部署到公网，强烈建议使用严格模式 (此模式下仅放行网易云音乐所属域名的请求) `-s`  限制代理范围 (需使用 PAC 或 hosts)，~~或启用 Proxy Authentication `-t <name>:<password>` 设置代理用户名密码~~ (目前密码认证在 Windows 客户端设置和 macOS 系统设置都无法生效，请不要使用)，以防代理被他人滥用

**Comment by SustechJoy** [comment]
明确，谢谢
