### ISSUE TITLE
检查更新的按钮点击没反应

### ISSUE THREAD

**Issue by kangxiaohui** [nondanee/UnblockNeteaseMusic#240]
我说 老哥  那个检查更新的按钮点击没反应啊，求修复
我说 老哥  那个检查更新的按钮点击没反应啊，求修复
我说 老哥  那个检查更新的按钮点击没反应啊，求修复

不经常上论坛  所以也不知道老哥更新没有  每次都点击检查更新  发现每次都没反应  老哥找个时间修复一下子把

**Comment by nondanee** [comment]
![image](https://user-images.githubusercontent.com/26399680/64905072-645aee80-d705-11e9-8ef0-bc81d7bcc765.png)

你是说这个 "检查更新" 吗？
这个更新是网易云音乐客户端的更新，和我没啥关系......
要用这个更新需要装证书，参考 👉 #48 

你想知道这个 repo 有没有更新，可以点上面 watch 按钮选 releases only，更新了会有邮件通知
![image](https://user-images.githubusercontent.com/26399680/64905129-12669880-d706-11e9-8677-2f03cea72d47.png)

**Comment by kangxiaohui** [comment]
不是  就是托盘里的网易云小工具  右击检查更新没反应

**Comment by JasonKhew96** [comment]
@kangxiaohui 你问错人了，请找论坛制作小工具的那位
