### ISSUE TITLE
请问在此脚本的基础上可以实现解锁虾米音乐变灰歌曲吗

### ISSUE THREAD

**Issue by seaboyang** [nondanee/UnblockNeteaseMusic#241]
突然发现以前收藏的大量日文歌被虾米下架了。然后就想到了这个方式，想知道怎么才能替换虾米的播放源

**Comment by Yansongsongsong** [comment]
只用这个库应该是不能方便地替换的 按照相似的思路你可以自己写一个框架去替换虾米的

**Comment by seaboyang** [comment]
> 只用这个库应该是不能方便地替换的 按照相似的思路你可以自己写一个框架去替换虾米的

谢谢。不会写框架只好在几个 app 之间来回切换着听了

**Comment by nondanee** [comment]
可以的
但是需要修改 hook.js (修改请求和返回数据)，provider/find.js (由歌曲 id 反查歌曲信息，构造搜索关键词)
其它部分都可以共用

不过需要事先确认
- 虾米客户端支持被代理，或者 https 能被拦截
- 已知虾米 API 的加密解密算法 (如果有的话)
- 已知返回数据中的 UI 控制字段

**Comment by seaboyang** [comment]
> 可以的
> 但是需要修改 hook.js (修改请求和返回数据)，provider/find.js (由歌曲 id 反查歌曲信息，构造搜索关键词)
> 其它部分都可以共用
> 
> 不过需要事先确认
> 
> * 虾米客户端支持被代理，或者 https 能被拦截
> * 已知虾米 API 的加密解密算法 (如果有的话)
> * 已知返回数据中的 UI 控制字段

谢谢
