### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Jakeshon-H** [nondanee/UnblockNeteaseMusic#242]
能否让手机版与电脑版的软件都实现软件自动更新，更新频繁的情况下每次都要重新下载，很繁琐，当然，这是我个人的请求，谢谢作者的无私奉献。

**Comment by nondanee** [comment]
我这边不提供可执行文件，你说的软件应该是衍生项目，可以直接联系他们的作者

手机版 @nining377
[nining377/UnblockMusicPro_Xposed](https://github.com/nining377/UnblockMusicPro_Xposed)

电脑版 @XIU2
 [X.I.U/解锁网易云音乐小工具](https://www.52pojie.cn/thread-1010165-1-1.html)
