### ISSUE TITLE
从2.4开始用不了

### ISSUE THREAD

**Issue by zousizhe** [nondanee/UnblockNeteaseMusic#244]
最新版用不了，发现从2.4开始在界面一点运行就定住几秒然后闪退，2.3正常，log都没有，直接掉了进程

**Comment by nondanee** [comment]
雨我无瓜
去论坛找 @XIU2 反馈

**Comment by XIU2** [comment]
@zousizhe 更新最新版本就行了，该问题是新加的端口占用检测导致的。
