### ISSUE TITLE
ios还有救吗？

### ISSUE THREAD

**Issue by huangxd-** [nondanee/UnblockNeteaseMusic#245]
为什么其他平台都可以😂

**Comment by nondanee** [comment]
不知道
(很大程度是因为作者没有 iOS 设备)

**Comment by a471640241** [comment]
> 为什么其他平台都可以😂

为什么我的Windows  iOS都不行了  歌曲部署灰色,但是播放的时候提示播放失败

**Comment by XIU2** [comment]
> > 为什么其他平台都可以😂
> 
> 为什么我的Windows iOS都不行了 歌曲部署灰色,但是播放的时候提示播放失败

可能是音源问题，尝试修改音源排序。

**Comment by nondanee** [comment]
@a471640241 Windows 上应该没问题的，你再试试吧

**Comment by Xuzan9396** [comment]
ios， 现在可以部署吗， mac上跑是没问题了

**Comment by TimelessMappleLeaf** [comment]
> ios， 现在可以部署吗， mac上跑是没问题了

你是怎么添加的代理啊，我服务器是没问题了 但是 Mac 上不知道 怎么添加代理啊

**Comment by nondanee** [comment]
@Xuzan9396 
我不知道
不过有人可以，那就是可以了
#56 #65 都看一下

**Comment by nondanee** [comment]
@TimelessMappleLeaf 
README 里有写啊
https://github.com/nondanee/UnblockNeteaseMusic#方法-2-设置代理
> macOS	系统偏好设置 > 网络 > 高级 > 代理

**Comment by Xuzan9396** [comment]
@TimelessMappleLeaf  mac , 1 .  node /Users/xuzan/Documents/UnblockNeteaseMusic/app.js -p 8090:4430 -f 59.111.181.35 ,  2. 
![image](https://user-images.githubusercontent.com/24741439/66829350-c2d5ef80-ef85-11e9-84f2-545be2d1a2d9.png)
3.重启网易云 ，很简单
