### ISSUE TITLE
Android版爱快路由器很简单就屏蔽ip了

### ISSUE THREAD

**Issue by qudongyu1** [nondanee/UnblockNeteaseMusic#246]
![搜狗截图20190919141459](https://user-images.githubusercontent.com/16526096/65218150-71eaec80-dae8-11e9-8f38-88e869660695.png)
![Screenshot_2019-09-19-14-19-34-960_com netease cl](https://user-images.githubusercontent.com/16526096/65218216-9e9f0400-dae8-11e9-840b-869f66a3c3cd.jpg)

**Comment by nondanee** [comment]
好，发到 #214 吧
