### ISSUE TITLE
启动报错Error: connect ECONNREFUSED 59.111.21.13:443 什么原因

### ISSUE THREAD

**Issue by LkaiGH** [nondanee/UnblockNeteaseMusic#247]
{ Error: connect ECONNREFUSED 59.111.21.13:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '59.111.21.13',
  port: 443 }

**Comment by nondanee** [comment]
用 release 版本

**Comment by nondanee** [comment]
https://music.httpdns.c.163.com
https://httpdns.n.netease.com

这两个打不打得开？(404 也算打开)

**Comment by LkaiGH** [comment]
可以打开

**Comment by nondanee** [comment]
那就没问题啊，你再试试呢？

你用了 master https://github.com/nondanee/UnblockNeteaseMusic/commit/a8b630574683aa907365fd9bcc990446428fe415 的代码？

**Comment by LkaiGH** [comment]
是的，我再试试

**Comment by NicholasLi-umbocv** [comment]
我有遇到同樣問題
環境為：Windows 10
使用的是 master a8b6305 的code
執行node app後出現以下錯誤：
{ Error: connect ECONNREFUSED 59.111.21.14:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '59.111.21.14',
  port: 443 }

**Comment by nondanee** [comment]
@NicholasLi-umbocv 
https://music.httpdns.c.163.com
https://httpdns.n.netease.com
部署的环境里这两个网站打得开吗？

打得开就没问题，打不开就 checkout v0.19.3

**Comment by NicholasLi-umbocv** [comment]
@nondanee 
嗯...網站能打得開，但就是會遇到ECONNREFUSED，然後程式就沒辦法跑了
不過git reset回 bf2a97c (v0.19.3)後就一切正常了

**Comment by nondanee** [comment]
@NicholasLi-umbocv 
这个打得开吗？
https://httpdns.n.netease.com/httpdns/v2/d?domain=interface3.music.163.com

**Comment by rti56kt** [comment]
@nondanee 
可以打開
(我是前面的NicholasLi-umbocv，不過那是我工作的帳號，剛剛發現忘記切了，現在換回我私人帳號回你)

**Comment by McGiRG3z** [comment]
同样问题，上述三个链接可以打开，但仍然没法使用。

**Comment by NameLessKnight** [comment]
在git页面下载master的代码，估计是你从别的地方copy的下载链接

**Comment by NameLessKnight** [comment]
DNS的問題，手動設置8.8.8.8試試吧

**Comment by NameLessKnight** [comment]
DNS的問題，手動設置8.8.8.8試試吧
@nondanee

**Comment by nondanee** [comment]
httpdns.n.netease.com 的 4 个 IP都试了下
59.111.21.13，59.111.21.14 这两个会 ECONNREFUSED
59.111.179.213，59.111.179.214 这两个是正常的

其实去掉 httpdns 对直接使用 http 代理的没啥影响
对使用 VPN service (Android / iOS) 的可能有点影响 (如果 sni 没识别到的话)

**Comment by zengxiaoliang** [comment]
android 下存在同样情况，还会到v0.14.x  正常。

**Comment by lonelykid** [comment]
https://music.httpdns.c.163.com
这个地址如果按照反代破解海外限制的要求设置了hosts，是指向了0.0.0.0的，把这条hosts去掉，不知道会不会受到限制。

**Comment by NameLessKnight** [comment]
我是通过直接设置DNS解决的，可能服务供应商的DNS服务器更新有延迟，http解析到的ip并不是最新的

**Comment by iveney** [comment]
v0.19.3 也遇到这个问题。

https://music.httpdns.c.163.com/ : ERR_CONNECTION_REFUSED
https://httpdns.n.netease.com/: 404

**Comment by wxxiao33** [comment]
v0.19.3 
node app.js -a 59.111.179.213
-a 好像没有效果

Error: connect ECONNREFUSED 59.111.21.13:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1126:14) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '59.111.21.13',
  port: 443
}

https://music.httpdns.c.163.com/ : 能打开
https://httpdns.n.netease.com/: 404
请问是什么原因呢

**Comment by nondanee** [comment]
@iveney 收到

**Comment by nondanee** [comment]
@wxxiao33 
`-a` 跟这个没关系
那你用的是应该是 master 分支的代码，不是 release 的版本，你 checkout 到 v0.19.3 上应该就行了

**Comment by wxxiao33** [comment]
> @wxxiao33
> `-a` 跟这个没关系
> 那你用的是应该是 master 分支的代码，不是 release 的版本，你 checkout 到 v0.19.3 上应该就行了

我用的v0.19.3，不知道是什么问题。把nodejs 重新装了一次，其余什么都没动，现在能用了。谢谢你了

**Comment by shugo-chara** [comment]
@nondanee 我也遇到了，重启服务器后就启动不了，更新到最新的版本还是不行。
浏览器打开
https://music.httpdns.c.163.com/ : ERR_CONNECTION_REFUSED
https://httpdns.n.netease.com/: ERR_CONNECTION_REFUSED

服务器运行
![image](https://user-images.githubusercontent.com/20610965/65851688-c4e95d00-e38e-11e9-9f4d-d208a0621de7.png)

**Comment by nondanee** [comment]
@shugo-chara 
安卓是吧？在用 VPNService 的代理客户端 (状态栏有钥匙图标的那种)？
那你开下 https 的端口，让客户端因为证书错误降级 http (默认用空数据降级)，可能会稍微快一点

**Comment by shugo-chara** [comment]
@nondanee 
安卓可以正常用，mac客户端不行了。

**Comment by nondanee** [comment]
@shugo-chara
你是说打开了 https 端口后安卓正常了，macOS 客户端不行了？

**Comment by shugo-chara** [comment]
@nondanee 不是，是mac突然就不能用了，以为是需要更新，然后重新部署了一遍后发现mac还是不能用。安卓手机一直正常。一直都没动过https端口之类的。
安卓用的分代软件一直正常。
mac一直用的clashx，之前都没问题，突然就网络错误了。

**Comment by shugo-chara** [comment]
@nondanee 
我找到mac客户端无法播放的原因了，clashX更新版本之后就死活连不上了。
然后我尝试直接用终端运行 node app.js - f 自己的服务器：p后，可以播放了，但是非常非常非常的卡。
然后换回proxifier代理试了下也可以播放，但是缓冲一样的卡。

但是android端一直都很稳定，速度也非常快。唯独mac端好端端的就这样了。我的服务器检查没问题。
版本 2.1.1 (790) 一直没更新。
********************************************
总结下就是
正常的代理服务器，只有mac端突然就不能播放，要么缓冲就非常非常卡，几十k的速度，然后过一会儿自己就卡的换歌了。logs里能正常抓到地址。
其他平台客户端都没问题。

试了几天不同的代理方法都没能解决。

不知道大佬有没有测试mac端看看。是不是macos端的问题。

**Comment by shugo-chara** [comment]
@nondanee 
所有方法都无效，最后尝试了下证书https转发的方法。
服务器运行 pm2 start app.js -- -p 2333:8080
![image](https://user-images.githubusercontent.com/20610965/66136455-75c55580-e636-11e9-9a3f-24b72f13cb35.png)
pm2里显示的8080
![image](https://user-images.githubusercontent.com/20610965/66136521-95f51480-e636-11e9-9b04-b4c6da43d3e4.png)

mac上下载了提供了仓库提供的证书，设置为始终信任。

代理里的规则还是ip：2333。
![image](https://user-images.githubusercontent.com/20610965/66136664-cd63c100-e636-11e9-9e2b-d0b36274cf80.png)

然后客户端还是跟之前一样，网络错误。偶尔可以播放但是非常卡，卡到显示网络不给力
log
![image](https://user-images.githubusercontent.com/20610965/66137147-9cd05700-e637-11e9-9c7e-3e134927ce07.png)
把能想到的原因都试过了还是没找到问题所在。

**Comment by lonelykid** [comment]
@shugo-chara 你用hosts文件试试，我试了所有方法，只有改hosts文件是最稳定的

**Comment by shugo-chara** [comment]
@lonelykid 谢谢～但是不是hosts的原因，我是在找现在问题出在哪。

**Comment by shugo-chara** [comment]
@nondanee 排查完毕，还是网易云客户端云控的问题。最近的几个版本都出问题，测试回到2.0.0或之前恢复正常。等下我会写一个排查指南吧，方便后面可能会遇到同样问题的人。

**Comment by nondanee** [comment]
@shugo-chara 
额刚在虚拟机里试了下 2.2.0 (800) 不卡啊，可以正常使用的
测试了设置网络代理和改 hosts 都没问题
