### ISSUE TITLE
周杰伦的“说好不哭”解析为多亮的“说好不哭”

### ISSUE THREAD

**Issue by hustlyt** [nondanee/UnblockNeteaseMusic#248]
网易云周杰伦的说好不哭，播放的却是**多亮的说好不哭**，日志里地址也是多亮的说好不哭，音源排序是migu,qq，如果改成qq,migu就可以播放了，但是说好不哭并没有在migu上架。
这个是因为在替换地址时是按照音乐名字来找的吗？

**重现步骤：**
搜索说好不哭，往下翻，翻到有一个歌曲名字叫“说好不哭”，歌手是“周杰伦(Jay Chou)”，专辑名叫“说好不哭”，直接双击播放这个歌曲，播放的是多亮的说好不哭。
但是如果是在周杰伦的主页点击播放，播放的还是周杰伦的说好不哭。

**Comment by nondanee** [comment]
差不多吧 https://github.com/nondanee/UnblockNeteaseMusic/issues/30#issuecomment-517984439

按照 "歌名 - 歌手名" 来找的
https://github.com/nondanee/UnblockNeteaseMusic/blob/a8b630574683aa907365fd9bcc990446428fe415/provider/find.js#L17

**Comment by hustlyt** [comment]
> 差不多吧 [#30 (comment)](https://github.com/nondanee/UnblockNeteaseMusic/issues/30#issuecomment-517984439)
> 
> 按照 "歌名 - 歌手名" 来找的
> https://github.com/nondanee/UnblockNeteaseMusic/blob/a8b630574683aa907365fd9bcc990446428fe415/provider/find.js#L17

哦哦这样啊
