### ISSUE TITLE
ios专辑页面正常.但是显示网络不给力,不能播放下载

### ISSUE THREAD

**Issue by shzxm** [nondanee/UnblockNeteaseMusic#249]
![image](https://user-images.githubusercontent.com/9905297/65389481-5a7e5e80-dd89-11e9-8369-96a06abbf479.png)
可以正常请求
证书已经安装
shadowrocket方式.
规则已经添加

**Comment by shzxm** [comment]
ios专辑页面正常.但是显示网络不给力,不能播放下载

**Comment by matianhe** [comment]
我和你的问题一样，也是显示网络不给力，安卓mac正常

**Comment by zsh065400** [comment]
> 我和你的问题一样，也是显示网络不给力，安卓mac正常

我的mac配置完自动代理，网易云用不了。安卓正常

**Comment by nondanee** [comment]
和 #137 #215 的反馈都是一样的问题
但是有人还可以用
https://github.com/nondanee/UnblockNeteaseMusic/issues/215#issuecomment-532944662
https://github.com/nondanee/UnblockNeteaseMusic/issues/215#issuecomment-533706081
我也不知道 =.=
