### ISSUE TITLE
大佬好，请问严格模式下win客户端怎么配PAC

### ISSUE THREAD

**Issue by FaustDash** [nondanee/UnblockNeteaseMusic#250]
如图，网易云客户端只允许配全局的代理T.T主机上没有80端口用了，搞不了host模式
![QQ图片20190923115952](https://user-images.githubusercontent.com/13502813/65401278-b1bc1780-ddf9-11e9-826c-a1d2a7965557.png)

**Comment by nondanee** [comment]
严格模式考虑过客户端全局代理无法设置 PAC 问题
客户端绝大部分请求都会放行的 (白名单内)
https://github.com/nondanee/UnblockNeteaseMusic/blob/a8b630574683aa907365fd9bcc990446428fe415/app.js#L63

加上 `-e http://music.163.com` 就行了

**Comment by FaustDash** [comment]
thx！
