### ISSUE TITLE
HTTP Server running @ http://0.0.0.0:80 之后没反应

### ISSUE THREAD

**Issue by joe960913** [nondanee/UnblockNeteaseMusic#251]
mac os系统，使用的是hosts代理
```shell
Impulsion:UnblockNeteaseMusic-0.19.3 zizhoutong$ sudo node app.js -p 80 -f 59.111.160.195
Password:
HTTP Server running @ http://0.0.0.0:80
```
之后就没反应了，打开netease后无法连接网络。

**Comment by nondanee** [comment]
你的网易云客户端版本是多少？
之前有人反馈 2.1.2(798) 是可以直接用的 #238，不需要额外配置
不过我没有试过，你可以试试看

再往前的反馈结果是 macOS 客户端不支持降级，在README 使用部分写了 https://github.com/nondanee/UnblockNeteaseMusic#使用

> macOS 客户端 (726 版本以上需要自签证书)

自签证书相关看这个 issue 👉 https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-477870013

**Comment by nondanee** [comment]
👌
