### ISSUE TITLE
网易云下载的歌曲只能是128k的, 能否支持320k或无损音质

### ISSUE THREAD

**Issue by taoing** [nondanee/UnblockNeteaseMusic#252]
网易云下载的歌曲只能是128k的, 能否支持320k或无损音质, 能通过配置解决吗

**Comment by nondanee** [comment]
酷我和咪咕音源支持 320k，酷狗和 QQ 只有 128k，不支持无损
配置参数详见 👉 https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-429515355
酷我理论上有 aac 无损，咪咕理论上有 flac 无损，代码里主动屏蔽了，你可以自己改代码

项目主要解决不能听的问题，音质尽力
如果你知道有高品 API (非第三方) 欢迎 PR

**Comment by taoing** [comment]
对node.js不熟悉, 能指出具体是改代码哪里吗. 通过 -o 参数指定音源顺序还是大多数歌曲下载只能128k

**Comment by nondanee** [comment]
酷我的
https://github.com/nondanee/UnblockNeteaseMusic/blob/a8b630574683aa907365fd9bcc990446428fe415/provider/kuwo.js#L52

咪咕的
https://github.com/nondanee/UnblockNeteaseMusic/blob/a8b630574683aa907365fd9bcc990446428fe415/provider/migu.js#L33

不能保证你改之后还能正常运行，比如非 mp3 文件无法读取比特率等问题

**Comment by nondanee** [comment]
大多数歌曲 128k 说明只匹配到 QQ 音源
目前 QQ 没有 "被公开" 的高品接口，第三方有，你可以自己去找
