### ISSUE TITLE
ios12.4越狱手机可以代理不

### ISSUE THREAD

**Issue by Chsengni** [nondanee/UnblockNeteaseMusic#255]
为什么在ios 上NewTerms 2  运行显示 http://0.0.0.0:8080 ,端口自己设置的

**Comment by Chsengni** [comment]
我在Cydia上装了node ，但是 没有代理功能，只能改 host啊 ，但是改host 又没有网，怎么办

**Comment by nondanee** [comment]
WLAN 可以设代理的啊，README 里有写
改 hosts 必须用 80 端口，README 里有写
