### ISSUE TITLE
转成 ss 协议 匹配列表的时候似乎不走代理

### ISSUE THREAD

**Issue by liangshiw** [nondanee/UnblockNeteaseMusic#257]
根据https://www.lajiblog.com/index.php/archives/4/
设置分应用代理(不设置也一样)，大量的请求失效。

![image](https://user-images.githubusercontent.com/16813853/65828517-3f05dd00-e2ce-11e9-9ed4-8103cd157f90.png)

**Comment by nondanee** [comment]
正常的
工作原理就是如此，参见 README
> 目前除 UWP 外其它客户端均优先请求 HTTPS 接口，默认配置下本代理对网易云所有 HTTPS API 连接返回空数据，促使客户端降级使用 HTTP 接口

**Comment by liangshiw** [comment]
额哦，不挂一层ss是OK的欸

**Comment by nondanee** [comment]
不 OK 怎么体现？

**Comment by liangshiw** [comment]
可能是我的问题吧，我再找找看先。
直接运行NeteaseMusic手机设置 apn 后是可以的
然后使用goproxy转成ss后用飞机设置分应用就尬了，我看日志在搜索音乐时，没有请求进来。还在找原因

**Comment by liangshiw** [comment]
![image](https://user-images.githubusercontent.com/16813853/65829068-fc470380-e2d3-11e9-9a84-cd9a5224c3eb.png)

**Comment by liangshiw** [comment]
大量的类似上图的错误。。

**Comment by nondanee** [comment]
有这个错误是正常的啊.....

**Comment by liangshiw** [comment]
-.- 正常的吗，不过现在音乐变灰了

**Comment by liangshiw** [comment]
有什么解决方案吗

**Comment by nondanee** [comment]
我试了下用 goproxy
```
./proxy sps -S http -T tcp -P 127.0.0.1:8080 -t tcp -p :18080 -h aes-192-cfb -j pass
```
unblockneteasemusic 这边启动就用
```
node app
```

可以用，也没出现你说的那个错误
就是加载很慢，如 #193，看 log 的内容应该是尝试了非常多 ip 的 https 请求后才成功降级 http

![image](https://user-images.githubusercontent.com/26399680/65832371-37a5fa00-e2f5-11e9-93d0-f8f1513e6edf.png)

这就不太清楚了 =.=

**Comment by nondanee** [comment]
清除数据又试了一次，除了加载比较慢 (得 6 到 7 秒)，灰色不会出现
Android 客户端版本 6.4.1

**Comment by liangshiw** [comment]
下载了最新的版本，暂时OK了。
