### ISSUE TITLE
惨！这个项目做了快一年了，结果我写个 GUI 软件仅一个多月就成功惊动官方了。。。

### ISSUE THREAD

**Issue by XIU2** [nondanee/UnblockNeteaseMusic#258]
刚刚收到了吾爱破解论坛站长的通知，因为官方联系论坛维权了，所以站长把我的帖子隐藏了。
为了避免惹上版权，我宣布了 解锁网易云音乐小工具 将停止更新（不过也没啥可更新的了，本来就没什么更新计划了）。
我特地跑来跟 @nondanee 提个醒~

没想到我就写了个 GUI 小工具，结果就惊动官方了😂。。。
软件莫名其妙就火了，网上被转到的到处都是，连累项目了。。。

@nondanee  作者你也注意点，毕竟我写的只是个 GUI 小工具，核心主程序还是你的项目。。。

**Comment by Sunshine018** [comment]
看来我们得悠着点用这个项目了

**Comment by XIU2** [comment]
> 看来我们得悠着点用这个项目了

你们这些使用者没啥事，主要是项目及作者。
作者也没留下什么联系信息，也不用担心收到维权。

不过项目肯定会受到一定影响。
毕竟项目目前最方便的方式是依靠 网易云音乐HTTP过渡HTTPS 的间隙来实现的。
虽然 HTTPS 也能用，但是还需要自己搞证书，设备导入证书什么的，提高了一定使用门槛。

估计接下来网易云音乐要加快 **全客户端强制HTTPS** 的进程了。

**Comment by XIU2** [comment]
@nondanee 如果你看到了，就把这个问题关掉吧！

**Comment by nondanee** [comment]
@XIU2 好的，知道了
