### ISSUE TITLE
Android使用指南

### ISSUE THREAD

**Issue by Sunshine018** [nondanee/UnblockNeteaseMusic#259]
根据基本使用指南来编写这一专项使用指南。
现在手头上没有设备，图片什么的十月一补。
先说一下需要准备的东西。
1.Termux或Neoterm
2.Xndroid[可选，具体用途以后细说]
3.可以联网的手机一台

**Comment by Sunshine018** [comment]
1.下载Termux或Neoterm，安装后打开。
注意：Neoterm使用时可能会先调用系统终端，请退出杀死进程后重启，选择“从软件源安装”

**Comment by Sunshine018** [comment]
2.先执行apt update，因为不执行这一命令可能无法安装程序。

**Comment by Sunshine018** [comment]
3.依次执行以下命令：
apt install git
apt install nodejs
git clone https://github.com/nondanee/UnblockNeteaseMusic

**Comment by Sunshine018** [comment]
4.依次执行如下命令：
cd UnblockNeteaseMusic
node app.js -p {端口号，自己任选一个即可，不能高于65535} -a 127.0.0.1

**Comment by Sunshine018** [comment]
5.进入设置，选择“SIM卡”，找到APN设置，创建一个APN。
APN移动用cmnet，联通用3gnet，电信用ctnet或ctlte，代理填127.0.0.1，端口号填你上一步输入的端口号，保存，切换即可
使用WLAN的小伙伴请进入WLAN，点开你连接的WLAN，代理选择手动，填127.0.0.1，端口填你上一步输入的端口号，保存即可。

**Comment by Sunshine018** [comment]
6.高级用法
可以使用Xndroid中的fqrouter来单独设置代理，需要ROOT，以后再说。

**Comment by nondanee** [comment]
谢谢

不过已经告知 Android 上可以用终端模拟器安装 Node.js https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-429513795
步骤和 #22 描述的也没啥区别，(总共 3 步，安装 Node，拉取代码，启动)，不用单独写教程了
APN 设置之前有 #214 教程，不过网上搜索一下 "APN 设置代理" 就有教程，感觉和项目本身关系也不太大，我也关闭了

**Comment by simplove** [comment]
刷了L大最新的固件，电脑版和IOS版都不用做任何设置，直接解锁，可是安卓版却不行。
已经在静态路由里面添加了223.252.199.10这个IP，还是不行。

**Comment by nondanee** [comment]
@simplove 
问过插件那边吗？自动代理怎么实现的？
手动设置代理可以用吗？如果可以的话就不是我这边的问题。

Android 端会直连的 IP 可能需要全部 ban 掉，不只 223.252.199.10 这一个 #337

**Comment by DoveBoy** [comment]
> 5.进入设置，选择“SIM卡”，找到APN设置，创建一个APN。
> APN移动用cmnet，联通用3gnet，电信用ctnet或ctlte，代理填127.0.0.1，端口号填你上一步输入的端口号，保存，切换即可
> 使用WLAN的小伙伴请进入WLAN，点开你连接的WLAN，代理选择手动，填127.0.0.1，端口填你上一步输入的端口号，保存即可。

这个亲测确实有效，大佬什么时候找到能用类似代理的方式直接切换那就最好了，比如Google浏览器中的插件，switchproxy for Omega中的pac配置文件
