### ISSUE TITLE
「iOS/macOS」能否屏蔽欧盟 GDPR ？

### ISSUE THREAD

**Issue by HenryQW** [nondanee/UnblockNeteaseMusic#26]
启动时会针对欧盟 IP 做检测，不知能否通过伪装跳过？理论上部署服务器不在欧盟境内就能绕过这个问题，无奈我的部署环境都在欧盟。

iOS：
![image](https://user-images.githubusercontent.com/5896343/47038457-75a81d80-d179-11e8-9bed-10ca06e5ee9b.png)

macOS：直接 301 无法登陆
![image](https://user-images.githubusercontent.com/5896343/47038513-94a6af80-d179-11e8-9322-551a90a6a275.png)

**Comment by nondanee** [comment]
你用这个试试, Vultr London 的节点
- unblock，就是这个repo
```
45.77.230.236:80
```

- 普通代理 https://gist.github.com/nondanee/b50d6107cdafa2460c81d929b2b2f91f/69f1f95b61e399fb85fff9003f40b77861072a2c
```
45.77.230.236:8080 
```

**Comment by HenryQW** [comment]
不行，绕不过

**Comment by nondanee** [comment]
mac 版吗？

**Comment by HenryQW** [comment]
mac 不在身边没测，iOS 不行

**Comment by nondanee** [comment]
嗯，我测试结果也这样
