### ISSUE TITLE
hosts 模式无效？

### ISSUE THREAD

**Issue by sunaihui** [nondanee/UnblockNeteaseMusic#260]
无法解锁

路由器运行 node app.js -p 80:443 -f 59.111.181.38 &
# HTTP Server running @ http://0.0.0.0:80
HTTPS Server running @ https://0.0.0.0:443
已经把下面域名劫持到路由器IP
music.163.com
interface.music.163.com

正在 Ping music.163.com [11.0.0.2] 具有 32 字节的数据:
来自 11.0.0.2 的回复: 字节=32 时间=1ms TTL=64
来自 11.0.0.2 的回复: 字节=32 时间=1ms TTL=64
来自 11.0.0.2 的回复: 字节=32 时间=1ms TTL=64
来自 11.0.0.2 的回复: 字节=32 时间=1ms TTL=64

**Comment by nondanee** [comment]
那你路由器 IP 是 11.0.0.2 吗？

**Comment by sunaihui** [comment]
> 那你路由器 IP 是 11.0.0.2 吗？

是的啊 客户端设置代理是可以解锁的

**Comment by nondanee** [comment]
那无法解锁的表现是什么
你说 Android 端还是 iOS 端？

**Comment by sunaihui** [comment]
> 那无法解锁的表现是什么
> 你说 Android 端还是 iOS 端？

我用的Windows客户端 Android客户端 都不行

**Comment by nondanee** [comment]
刚试了 Windows 客户端没问题

Android 客户端确实不行，REAME 里有写
https://github.com/nondanee/UnblockNeteaseMusic#方法-1-修改-hosts

> **Android 客户端下修改 hosts 无法直接使用**，原因和解决方法详见[云音乐安卓又搞事啦](https://jixun.moe/post/netease-android-hosts-bypass/)，[安卓免 root 绕过网易云音乐 IP 限制](https://jixun.moe/post/android-block-netease-without-root/)

解决方法不知道还有没有效果，你试试看
