### ISSUE TITLE
怎样弄那种挂DNS就可以连上网易云的东西吖。

### ISSUE THREAD

**Issue by Jacobxhz** [nondanee/UnblockNeteaseMusic#262]
以前ipad上好像有一种改Wi-Fi dns就可以用网易云音乐的，那是咋弄的。现在像Quantumult这种软件耗电好高啊。

**Comment by nondanee** [comment]
需要自己搭一个 dns server (比如 dnsmasq)
然后把这些域名
https://github.com/nondanee/UnblockNeteaseMusic/blob/3b935be283a87031ee8ab58634848ba87708eb65/hook.js#L26-L30
指向部署好的 unblockneteasemusic server
应该就行了 (没试过)

**Comment by Jacobxhz** [comment]
好的，谢谢我等会试试

**Comment by xinxin8816** [comment]
参考https://www.right.com.cn/forum/forum.php?mod=redirect&goto=findpost&ptid=692049&pid=410430
