### ISSUE TITLE
已解锁的试听歌曲仍限制播放时间片段

### ISSUE THREAD

**Issue by binsee** [nondanee/UnblockNeteaseMusic#263]
VIP歌曲只允许试听，通过本项目替换来源进行解锁后，进度条仍然限制了允许播放的时间段。

## 环境说明

测试环境：`WIN10` + `云音乐PC版 v2.5.6`
测试歌曲：`black bullet (インストゥルメンタル)` 歌手：`fripSide`

已解锁后的界面截图：
![image](https://user-images.githubusercontent.com/5285894/66251775-4a518080-e786-11e9-9876-081ed00b7cb6.png)
> 这个界面中不允许选择`试听区域`以外的时间点，播放时会从指定的试听起点开始播放，可以播放超出试听时间，但播放不到歌曲结束。

## 需要做的
解除试听歌曲的播放时间限制

## 过程

通过debug调试获取两首歌曲的原始信息：
![image](https://user-images.githubusercontent.com/5285894/66251855-36f2e500-e787-11e9-84a4-f1982eefff0b.png)
左侧是非VIP歌曲，右侧是限制了试听的VIP歌曲。可以发现数据中的`freeTrialInfo`字段指定了试听的时间起点和终点。

## 尝试解决

在 `hook.js` 中找到修改歌曲信息的代码在
```js
const tryMatch = ctx => {
	const netease = ctx.netease
	const jsonBody = netease.jsonBody
	let tasks = [], target = 0

	const inject = item => {
		item.flag = 0
		if((item.code != 200 || item.freeTrialInfo) && (target == 0 || item.id == target)){
			return match(item.id)
			.then(song => {
				item.url = global.endpoint ? `${global.endpoint}/package/${crypto.base64.encode(song.url)}/${item.id}.mp3` : song.url
				item.md5 = song.md5 || crypto.md5.digest(song.url)
				item.br = song.br || 128000
				item.size = song.size
				item.code = 200
				item.type = 'mp3'
				return song
			})
\\............
```

添加修正代码：

```js
				item.type = 'mp3'
//新增代码
				item.freeTrialInfo = null
//在 `return` 前添加
				return song
```

添加了额外的输出后得到如下：

```js
// patch before:
{ id: 28528422,
  url:
   'http://m8.music.126.net/20191005155444/651849ab54b1544af849ed7e5f69cacd/ymusic/ts/free/ddc061b3f462988c0ea2f8a73fbedfee.mp3',
  br: 128019,
  size: 305154,
  md5: 'ddc061b3f462988c0ea2f8a73fbedfee',
  code: 200,
  expi: 1200,
  type: 'mp3',
  gain: 0,
  fee: 1,
  uf: null,
  payed: 0,
  flag: 0,
  canExtend: false,
  freeTrialInfo: { start: 5, end: 24 },
  level: null,
  encodeType: null }

// patch after: 
{ id: 28528422,
  url:
   'http://aqqmusic.tc.qq.com/amobile.music.tc.qq.com/M500004eVsTO0kiGj6.mp3?vkey=17C6431F2644EE717FBC3BF0184B5E8FE7A4943079F66F772FC9AF4A760D92699F437E2605187A41C2067D4C0085ED5DB2BFCDF3C88E6840&uin=0&fromtag=8&guid=7332953645',
  br: 128000,
  size: 1534614,
  md5: 'f5d1c76f03e037396a7bfb0b779b289a',
  code: 200,
  expi: 1200,
  type: 'mp3',
  gain: 0,
  fee: 1,
  uf: null,
  payed: 0,
  flag: 0,
  canExtend: false,
  freeTrialInfo: null,
  level: null,
  encodeType: null }
```

界面截图：
![image](https://user-images.githubusercontent.com/5285894/66251939-7cfc7880-e788-11e9-865a-b4609bd31dea.png)

## 结束及额外的话
感谢本项目带来的便利，目前自己是在nas的docker中跑，加上在软路由(lede系统)上添加自定义dns指向到docker容器ip（使用MACvLAN网络，容器独立ip）以对内网无感生效，容器使用`resolv.conf`文件指定了外网的dns服务器以避免主路由下发错误dns解析。
但这种方式仍然对安卓新版客户端无效（指未在安卓设置代理服务器。使用pac代理会导致其他app打开网页异常，指定代理服务器又有些降速，做不到全局无感。指定代理服务器到**unblockmusic**时是可以解锁的）。
通过简单逆向安卓客户端发现安卓app内置了一个ip列表，首先会通过ip方式直接访问，逃过了dns污染，目前尝试在路由器上加iptables拦截数据包重定向到容器的方式还是很麻烦（对iptables还是不熟悉），暂时未能重定向直接通过ip连接的方式。

以下是从安卓app v6.4.2中找到的默认服务器ip列表：
```
1.81.5.114
1.81.5.115
110.185.122.114
110.185.122.115
14.18.239.11
14.18.239.12
223.202.198.132
223.202.198.134
59.111.179.213
59.111.179.214
59.111.21.13
59.111.21.14
```

如果有熟悉`iptables`的大佬，希望能解答下在路由器上通过`iptables`检测向指定外网ip的通讯，并将其重定向到指定ip端口的方法。
虽然有个[luci-app-unblockmusic](https://github.com/maxlicheng/luci-app-unblockmusic) 项目可以在软路由系统上直接运行 unblockmusic，但硬件性能不足，在lede中跑unblockmusic似乎会降低网络吞吐，且项目的iptables写的也不够好，对安卓仍然无效，暂时希望仍用docker容器来跑了。

**Comment by nondanee** [comment]
这样应该可以

```sh
iptables -t nat -A OUTPUT -p tcp -d <$Netease IP> --dport 80 -j DNAT --to-destination <$UnblockNeteaseMusic IP>:<$UnblockNeteaseMusic PORT>
```

**Comment by binsee** [comment]
> 这样应该可以
> 
> ```shell
> iptables -t nat -A OUTPUT -p tcp -d <$Netease IP> --dport 80 -j DNAT --to-destination <$UnblockNeteaseMusic IP>:<$UnblockNeteaseMusic PORT>
> ```

测试了`OUTPUT`不可行，在路由器上将内网设备的通讯重定向到其他内网设备，需要分别设置`PREROUTING`和`POSTROUTING`链，查资料折腾了很久，虽然做到了安卓使用，然而仍然存在某些异常的问题，然后放弃了。
回头去折腾 [luci-app-unblockmusic](https://github.com/maxlicheng/luci-app-unblockmusic) 项目，然后成功了，已经做到了安卓上的无感使用（不需要设置代理服务器和pac，不影响其他app使用）。

已经为其提交pr，备忘链接： https://github.com/maxlicheng/luci-app-unblockmusic/issues/60

------

关于iptables的使用折腾备忘：
```bash
ipset -! -N music hash:ip
echo { "59.111.21.13", "59.111.179.213", "59.111.21.14", "59.111.179.214", "1.81.5.114", "1.81.5.115", "110.185.122.114", "110.185.122.115", "14.18.239.11", "14.18.239.12", "223.202.198.132", "223.202.198.134" } |grep -Eo '[0-9]+?\.[0-9]+?\.[0-9]+?\.[0-9]+?' | sort | uniq | xargs -i ipset -! add music  {}
wget http://httpdns.n.netease.com/httpdns/v2/d?domain=p2.music.126.net,interface.music.163.com,interface3.music.163.com,clientlog.music.163.com,apm.music.163.com,apm3.music.163.com,p1.music.126.net,clientlog3.music.163.com -O- | grep -Eo '[0-9]+?\.[0-9]+?\.[0-9]+?\.[0-9]+?' | sort | uniq | xargs -i ipset -! add music  {}
ipset list music

# 需要说明本地网络配置
# 10.0.0.21 为跑unblockmusic的机器
# 10.0.0.3 为主路由器ip

iptables -t nat -N cloud_music

# 运行unblockmusic的设备需要跳过，避免死循环
iptables -t nat -A cloud_music -s 10.0.0.21 -j RETURN

# 使用DNAT重定向到unblockmusic
iptables -t nat -A cloud_music -p tcp --dport 80 -j DNAT --to-destination 10.0.0.21:8080
iptables -t nat -A cloud_music -p tcp --dport 443 -j DNAT --to-destination 10.0.0.21:8081

# 匹配服务器ip列表，跳到 cloud_music 链
iptables -t nat -I PREROUTING  -p tcp -m multiport --dport 80,443 -m set --match-set music dst -j cloud_music

# 设置数据包的源ip为路由器，否则 unblockmusic会将数据直接发给安卓设备，由于通讯的mac地址不匹配，tcp通讯会被安卓设备rst
iptables -t nat -I POSTROUTING  -p tcp -m multiport --dport 8080,8081 -d 10.0.0.21 -j SNAT --to-source 10.0.0.3

# 额外加的日志
iptables -t nat -I PREROUTING  -p tcp -m set --match-set music dst -j LOG --log-prefix 'music match PREROUTING :'
iptables -t nat -I POSTROUTING  -p tcp -m multiport --dport 8080,8081 -d 10.0.0.21 -j LOG --log-prefix 'unblock match POSTROUTING :'
```


关于 iptables 使用DNAT和SNAT的使用参考：
http://wsfdl.com/%E8%B8%A9%E5%9D%91%E6%9D%82%E8%AE%B0/2017/01/12/iptables_snat.html

**Comment by nondanee** [comment]
你看一眼 PREROUTING 的日志，有哪些 IP 被转发了？
我扫了下端口
```
1.81.5.114
1.81.5.115
110.185.122.114
110.185.122.115
14.18.239.11
14.18.239.12
223.202.198.132
223.202.198.134
59.111.179.213
59.111.179.214
59.111.21.13
59.111.21.14
```
好像只有 59.111.179.213, 59.111.179.214 能用
这两个在 httpdns 的结果里有，那 luci-app-unblockmusic 本就可以无感代理啊

**Comment by binsee** [comment]
> 你看一眼 PREROUTING 的日志，有哪些 IP 被转发了？
> 我扫了下端口
> 
> ```
> 1.81.5.114
> 1.81.5.115
> 110.185.122.114
> 110.185.122.115
> 14.18.239.11
> 14.18.239.12
> 223.202.198.132
> 223.202.198.134
> 59.111.179.213
> 59.111.179.214
> 59.111.21.13
> 59.111.21.14
> ```
> 
> 好像只有 59.111.179.213, 59.111.179.214 能用
> 这两个在 httpdns 的结果里有，那 luci-app-unblockmusic 本就可以无感代理啊

原先测试时，最新版安卓(**v6.4.2**)的不可以，另外还存在一些问题（比如某些歌单图片空白等），我正在调试查。
目前看来访问如`p2.music.126.net` 和 `clientlog3.music.163.com`这些域名时，会导致如下Error
```
{ Error: getaddrinfo ENOTFOUND null null:80
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'null',
  host: 'null',
  port: 80 }
```
原因是其脚本内重定向了以下域名通讯到unblockmusic，而unblockmusic对非名单域名处理有问题导致error
```
p2.music.126.net
interface.music.163.com
interface3.music.163.com
clientlog.music.163.com
apm.music.163.com
apm3.music.163.com
p1.music.126.net
clientlog3.music.163.com
```

这部分我确定后会另外发issue

**Comment by nondanee** [comment]
知道了

填成 null 是故意触发 error 的
用 iptables 转发就等于改 hosts，也等于反向代理
因为不符合规则的域名不会被反代 #254
https://github.com/nondanee/UnblockNeteaseMusic/blob/626253f0b9a32bd793b9ceb04043202591954562/hook.js#L25-L37
https://github.com/nondanee/UnblockNeteaseMusic/blob/626253f0b9a32bd793b9ceb04043202591954562/hook.js#L69

clientlog.music.163.com
clientlog3.music.163.com
可以和 music.163.com 公用 IP 我之前是知道的

刚测了下发现
p1.music.126.net
p2.music.126.net
这种 cdn 域名也能和 music.163.com 公用 IP 真是震惊了......

**Comment by binsee** [comment]
我也确实查到这里的代码
https://github.com/nondanee/UnblockNeteaseMusic/blob/626253f0b9a32bd793b9ceb04043202591954562/hook.js#L69
都准备开issue提pr删除`null`了，又读到你的回复，算是理解了你的意思。

那这么看来是否应该将cdn域名也添加到`hook.target.host`里去？

**Comment by binsee** [comment]
唔，重新测试了一下，发现并没有问题。有问题的是`luci-app-unblockmusic`项目的脚本

https://github.com/maxlicheng/luci-app-unblockmusic/blob/e0aac69e32515f13218a7b48831a83f296fdc6f7/app/root/etc/init.d/unblockmusic#L21
```
wget http://httpdns.n.netease.com/httpdns/v2/d?domain=p2.music.126.net,interface.music.163.com,interface3.music.163.com,clientlog.music.163.com,apm.music.163.com,apm3.music.163.com,p1.music.126.net,clientlog3.music.163.com -O- | grep -Eo '[0-9]+?\.[0-9]+?\.[0-9]+?\.[0-9]+?' | sort | uniq | awk '{print "ipset add music "$1}' > /tmp/musicip.sh
```

测试如下：

```bash
wget http://httpdns.n.netease.com/httpdns/v2/d?domain=interface.music.163.com,interface3.music.163.com,clientlog.music.163.com,music.163.com,apm.music.163.com,apm3.music.163.com,clientlog3.music.163.com -O- | grep -Eo '[0-9]+?\.[0-9]+?\.[0-9]+?\.[0-9]+?' | sort | uniq | xargs -i ipset -! add music  {}

### output ip list
115.236.118.33
118.24.63.156
193.112.159.225
223.252.199.66
223.252.199.67
39.105.63.80
47.100.127.239
59.111.160.195
59.111.160.197
59.111.181.35
59.111.181.38
59.111.181.60

root@lede:/tmp# nslookup p1.music.126.net
nslookup: can't resolve '(null)': Name does not resolve
Name:      p1.music.126.net
Address 1: 222.245.77.23
Address 2: 218.76.105.254

root@lede:/tmp# nslookup p2.music.126.net
nslookup: can't resolve '(null)': Name does not resolve
Name:      p2.music.126.net
Address 1: 218.76.105.254
Address 2: 222.245.77.23
```
cdn域名解析结果并不在httpdns解析结果内，因此**cdn域名**并没有和`music.163.com`共用ip。
那基本上unblockmusic拦截掉的都是`clientlog`了，正好我还想全屏蔽掉，省事了。

**Comment by nondanee** [comment]
```sh
curl http://223.252.199.67/_zXCW9kQAu07TgCSTN2t9A==/109951164407105357.jpg -H 'Host: p1.music.126.net' > test.jpg
```
```sh
curl http://223.252.199.67/api/album/81679689 -H 'Host: music.163.com' > test.json
```
亲测
```
115.236.118.33
223.252.199.66
223.252.199.67
59.111.160.195
59.111.160.197
59.111.181.35
59.111.181.38
59.111.181.60
```
这些确实是可以反代 p1.music.126.net

另，clientlog 被拦截可能无法记录听歌排行

**Comment by binsee** [comment]
嗯，那看来我只需要修改路由器上使用httpdns解析的域名列表即可，原先多了`p1.music.126.net`和`p2.music.126.net`，少了`music.163.com`。
暂时测试没有明显的异常了。
