### ISSUE TITLE
如何使用自己surge生成的证书

### ISSUE THREAD

**Issue by KwokLam** [nondanee/UnblockNeteaseMusic#265]
如果不想用openssl生成新的证书，而是使用手机上surge生成过的证书 怎么导入到代码中

**Comment by nondanee** [comment]
没用过 surge 不太清楚

如果是说 surge 生成的根证书
那要用 surge 的 CA 私钥签发对 music.163.com 和 *.music.163.com 的服务器证书

如果是说 surge 生成的服务器证书
那还需要服务器私钥 (只有证书没用)，你看看有没有办法导出

代码中使用 server.key (服务器私钥) 和 server.crt (服务器证书)
替换文件即可
