### ISSUE TITLE
相同网络环境下，某些设备的音乐匹配出现问题

### ISSUE THREAD

**Issue by zbttl** [nondanee/UnblockNeteaseMusic#266]
我有一台安卓 7 和另一台安卓 9 的红米，还有一台 windows 10 1903 的笔记本，所有设备都在同一个 wifi 下
1. windows 设备按官方的方法在本机上运行，一切正常
2. 安卓 7 红米使用 termux+proxydroid 在本机上运行，也正常
3. 安卓 9 红米使用安卓 7 红米的方案，部分歌曲匹配不正常。具体来说，是这两首歌
![image](https://user-images.githubusercontent.com/22035093/66270813-1fe8eb80-e88a-11e9-8449-3895c6fed972.png)
匹配正常情况下应该是这样
![image](https://user-images.githubusercontent.com/22035093/66270947-612dcb00-e88b-11e9-916f-e0ecad7ffc2f.png)
但是在安卓 9 设备上却匹配到了 kuwo 音源上
![image](https://user-images.githubusercontent.com/22035093/66270967-89b5c500-e88b-11e9-8011-0e6566334a70.png)
而且匹配到的这两首歌，第一首还不知道叫什么（酷我的听歌识曲识别不出来），第二首是 only my railgun，只有歌手对了
我试着让安卓 9 的 proxydroid 指向 windows 上正运行者的本项目，没问题，排除客户端的原因
另外在 windows 上使用这篇文章：[后增强器时代，怎样无感知解锁网易云付费歌曲](https://logi.ml/script/unblocking-netease-music-without-perception.html) 所提到的 windows 端工具也会复现该问题。

**Comment by nondanee** [comment]
不同平台匹配不一样的问题，可能 qq 音乐的 testfile 的 vkey 有点问题，重启一次 `node app` 试试看
因为匹配是动态的，我也不能保证每次匹配结果都是一样的

匹配不正确的问题，参考 👉 https://github.com/nondanee/UnblockNeteaseMusic/issues/30#issuecomment-517984439

**Comment by zbttl** [comment]
> 不同平台匹配不一样的问题，可能 qq 音乐的 testfile 的 vkey 有点问题，重启一次 `node app` 试试看
> 因为匹配是动态的，我也不能保证每次匹配结果都是一样的
> 
> 匹配不正确的问题，参考 👉 [#30 (comment)](https://github.com/nondanee/UnblockNeteaseMusic/issues/30#issuecomment-517984439)

emmm。。。重启过很多次了，结果都一样，匹配不正确的两个端都是匹配到这两首歌，而且我还尝试过用 -o 参数把 qq 圈到前面来或者把 kuwo 音源去掉，但要么就是跳过 qq 然后继续匹配 kuwo 或者干脆就直接放不出来。
#30 我都看过了，貌似没啥帮助我就来提问了
另外问一下作者大大，是网易官方的客户端才会留下这个项目所需要的 api 么？我尝试让 proxydroid 代理酷安那边的第三方网易客户端倒带，貌似没啥反应（

**Comment by nondanee** [comment]
这个......目测是 QQ 的链接可用性检查没有过，是这部分代码
https://github.com/nondanee/UnblockNeteaseMusic/blob/1562d92b7378b49552217da0fa222b34507a28f5/provider/match.js#L35-L54
我也没法在你设备上 debug，如果你会的话，可以自己查一下为什么 QQ 的链接被 filter 掉了

匹配不正确的问题，总结一下，就是我不会写

不是，支持倒带的 https://github.com/nondanee/UnblockNeteaseMusic/commit/9b8bc37b9affefab56e57576dcc7cfc97e10d7d7 (注意看 commit message)，不过还没有 release
记得在倒带的设置里把 “超时自动切换下一首” 的开关关掉

**Comment by nondanee** [comment]
今天发现 QQ 音源确实会时不时的 403 forbidden (被 filter 掉了)，不稳定
但这个没法修，只能随缘了
