### ISSUE TITLE
能不能增加一个socks5的协议？

### ISSUE THREAD

**Issue by 3131210** [nondanee/UnblockNeteaseMusic#267]
能不能增加一个socks5的协议？
在服务器建好了，但是只有http协议，在Android手机上平时也要用v2ray，是支持socks5协议的，想直接用这个代理网易云进程，不想单独再安装xx-net。

**Comment by nondanee** [comment]
不能 #53 #63 

你可以用代理转换工具进行转换，如
https://github.com/nadoo/glider
https://github.com/snail007/goproxy

v2ray 配置参考 #148

**Comment by 0njzy0** [comment]
master分支的v2ray outbound已经支持http [Support http outbound](https://github.com/v2ray/v2ray-core/pull/1813)
