### ISSUE TITLE
Android部分音乐无法下载且HTTP通道可能已被大量封锁

### ISSUE THREAD

**Issue by Sunshine018** [nondanee/UnblockNeteaseMusic#269]
#258 的问题出现后，使用最新版网易云音乐客户端发现部分版权音乐无法下载，提示下载失败，并且观察日志发现MITM项明显减少，TURNEL项明显增多，怀疑网易方面已经开始封锁HTTP通道，开发者注意一下吧，有可能现有的使用方式都无法解决问题了

**Comment by Sunshine018** [comment]
是TUNNEL不是TURNEL，抱歉

**Comment by nondanee** [comment]
无法下载的前提是可以播放吗？如果无法播放肯定无法下载
具体是哪首歌？麻烦举个例子
最新版是 6.4.1？增多的 tunnel 项可能都是失败的请求

**Comment by Sunshine018** [comment]
> 
> 
> 无法下载的前提是可以播放吗？如果无法播放肯定无法下载
> 具体是哪首歌？麻烦举个例子
> 最新版是 6.4.1？增多的 tunnel 项可能都是失败的请求

播放正常，无法下载，不知道现在问题解决没，我是通过把电脑上下载下来的音乐拷贝来解决的
具体在当时出现问题的音乐最典型的就是Luv Letter

**Comment by Sunshine018** [comment]
> 
> 
> 无法下载的前提是可以播放吗？如果无法播放肯定无法下载
> 具体是哪首歌？麻烦举个例子
> 最新版是 6.4.1？增多的 tunnel 项可能都是失败的请求

不过封锁HTTP还是有可能的，因为#258的工具作者都被官方叫去喝茶了......

**Comment by Sunshine018** [comment]
> 
> 
> 无法下载的前提是可以播放吗？如果无法播放肯定无法下载
> 具体是哪首歌？麻烦举个例子
> 最新版是 6.4.1？增多的 tunnel 项可能都是失败的请求

最新版本确实是6.4.1

**Comment by Sunshine018** [comment]
先撤了，睡觉去
如果确实有问题的话就得注意一下了，结果出来以后就把ISSUE关了吧，我看邮箱
辛苦开发者大大啦
