### ISSUE TITLE
使用PC版本2.5.0的一些问题

### ISSUE THREAD

**Issue by requestdeny** [nondanee/UnblockNeteaseMusic#27]
我已经用hosts的方法搭建完了，打开云音乐也可以使用了。但是变灰的歌虽然没变黑，但是打开来是播放失败。并不能听.其他的歌不受影响。可以播放。我在想是不是和我ip有关。我拿的一台英国的ip搭建的。属于欧盟的范围。。还是姿势不对

**Comment by requestdeny** [comment]
> emmm 因为替换的音源也可能存在海外限制
> UI上变灰是flag控制的，这个可以随便改；但是音源是请求服务器才能得到的，IP改不了啊，只能自己代理了
> 
> 之前试过，QQ、百度、酷我都有海外限制
> 好像虾米是没有的，不过虾米开放的资源也不多，没匹配到就会播放失败了

也就是说用国内的VPS这个问题就可以解决了么。我很久以前用的hosts是香港的。不知道香港的能不能用

**Comment by nondanee** [comment]
不能哦，我在hk😂

**Comment by nondanee** [comment]
顺便问一下，现在网易云应该没有海外限制了吧？不算版权下架的问题。

**Comment by requestdeny** [comment]
> 顺便问一下，现在网易云应该没有海外限制了吧？不算版权下架的问题。

除了版权下架的歌放不出。好像其他的都能放。不过ACG的歌变黑了。hosts以后也能放。但是周董的就不行..不是很懂他的屏蔽机制..

**Comment by requestdeny** [comment]
😂我还是感觉这个英国ip有毒。我换几台机子搭一个试试

**Comment by nondanee** [comment]
> 除了版权下架的歌放不出。好像其他的都能放。不过ACG的歌变黑了。hosts以后也能放。但是周董的就不行..不是很懂他的屏蔽机制..

hosts是指？用这个还是别人的呀？

**Comment by requestdeny** [comment]
> > 除了版权下架的歌放不出。好像其他的都能放。不过ACG的歌变黑了。hosts以后也能放。但是周董的就不行..不是很懂他的屏蔽机制..
> 
> hosts是指？用这个还是别人的呀？

就是自建了一个hosts.用这个啊.结果周董的歌放不出来。不过好像别的acg的黑掉的歌可以放。好神秘.

**Comment by nondanee** [comment]
> 就是自建了一个hosts.用这个啊.结果周董的歌放不出来。不过好像别的acg的黑掉的歌可以放。好神秘.

你看看log呀，ACG放的出来估计是匹配到了，我试了下JAY的歌虾米是没版权的😂

**Comment by requestdeny** [comment]
> 因为在 hk 是可以用 JOOX 可以听周董的，不知道你那边可不可以 😂 只不过 JOOX 匹配日文歌比较痛苦，它全用罗马音标名字...

我用网易云听得。我已经解决了，hosts完美运行。用来一台国内的加上sniproxy转发了一下.还是ip的问题。一定要用国内的ip才行.不能拿国外的转会有问题..
![qq 20181017201802](https://user-images.githubusercontent.com/11585577/47082788-c1c29300-d249-11e8-8307-ddbedcd8809f.png)

**Comment by HenryQW** [comment]
@requestdeny 因为 GDPR 网易云音乐直接屏蔽了欧盟 IP 段

**Comment by requestdeny** [comment]
> @requestdeny 因为 GDPR 网易云音乐直接屏蔽了欧盟 IP 段

欧盟的段能听歌（没有海外ip限制的）。不能登录而已。提前登陆好听歌到时能正常加载（至少我英国是这样.别的我就不清楚了）

**Comment by nondanee** [comment]
> 我用网易云听得。我已经解决了，hosts完美运行。用来一台国内的加上sniproxy转发了一下.还是ip的问题。一定要用国内的ip才行.不能拿国外的转会有问题..

hhhh 我的意思是我启用 JOOX 源就可以听到周董的歌了，不用代理回去
对的就是 IP 问题，自己有国内代理是最好的，不过这样的话直接部署在国内的上面不就好了吗 😂，也不用再转发了

**Comment by nondanee** [comment]
@HenryQW 代理端口就登出是什么操作😓，我去开一台英国的试一下好了

**Comment by requestdeny** [comment]
> > 我用网易云听得。我已经解决了，hosts完美运行。用来一台国内的加上sniproxy转发了一下.还是ip的问题。一定要用国内的ip才行.不能拿国外的转会有问题..
> 
> hhhh 我的意思是我启用 JOOX 源就可以听到周董的歌了，不用代理回去
> 对的就是 IP 问题，自己有国内代理是最好的，不过这样的话直接部署在国内的上面不就好了吗 😂，也不用再转发了

国内的机子都好贵..价格低的全是些垃圾带宽.搞了一台便宜的带宽又大的但是没有80口。无奈只能曲线救国😂.说多都是泪

**Comment by requestdeny** [comment]
> @HenryQW 代理端口就登出是什么操作😓，我去开一台英国的试一下好了

欧盟禁止登陆。直接弹出.

**Comment by HenryQW** [comment]
> @HenryQW 代理端口就登出是什么操作😓，我去开一台英国的试一下好了

因为网易云客户端每次网络状态变动都会做一个检测，所以就这样= =

**Comment by requestdeny** [comment]
> > @HenryQW 代理端口就登出是什么操作😓，我去开一台英国的试一下好了
> 
> 因为网易云客户端每次网络状态变动都会做一个检测，所以就这样= =

最简单的方法还是去搞一台便宜的国内机子。一劳永逸..

**Comment by allen0091** [comment]
有很多手機使用音量增強器能聽的歌 但電腦hosts方法不能聽

**Comment by nondanee** [comment]
> 国内的机子都好贵..价格低的全是些垃圾带宽.搞了一台便宜的带宽又大的但是没有80口。无奈只能曲线救国😂.说多都是泪

@requestdeny 哈哈哈，买的NAT？哪家啊，CloudIPLC？

**Comment by nondanee** [comment]
@allen0091 也在海外？

**Comment by requestdeny** [comment]
> > 国内的机子都好贵..价格低的全是些垃圾带宽.搞了一台便宜的带宽又大的但是没有80口。无奈只能曲线救国😂.说多都是泪
> 
> @requestdeny 哈哈哈，买的NAT？哪家啊，CloudIPLC？

嗯.119.99包年的那款。带宽流量都够用.

**Comment by toooonyy** [comment]
UK 裸连都可以听，可能歌单不一样？可以给几个听不了的看看吗
举个🌰，我的
![screen shot 2018-10-17 at 21 49 51](https://user-images.githubusercontent.com/3480434/47115484-9befbb00-d256-11e8-83fd-2f6e12ed210b.png)
![screen shot 2018-10-17 at 21 51 20](https://user-images.githubusercontent.com/3480434/47115548-ce99b380-d256-11e8-8d6b-d3fdd17b60bc.png)

**Comment by HenryQW** [comment]
@toooonyy 我这里根本就不让连接啊，所有操作永远是载入中

![image](https://user-images.githubusercontent.com/5896343/47116739-749aed00-d25a-11e8-9020-8823f9bfc6d3.png)

连接失败
![image](https://user-images.githubusercontent.com/5896343/47116731-6cdb4880-d25a-11e8-8f9e-4398df611b53.png)

也无法登陆。

**Comment by requestdeny** [comment]
> UK 裸连都可以听，可能歌单不一样？可以给几个听不了的看看吗
> 举个，我的
> ![screen shot 2018-10-17 at 21 49 51](https://user-images.githubusercontent.com/3480434/47115484-9befbb00-d256-11e8-83fd-2f6e12ed210b.png)
> ![screen shot 2018-10-17 at 21 51 20](https://user-images.githubusercontent.com/3480434/47115548-ce99b380-d256-11e8-8d6b-d3fdd17b60bc.png)

裸连没版权限制？这么神奇的么

**Comment by nondanee** [comment]
@toooonyy 
裸连是指？JAY的歌肯定灰的啊，大陆都灰的，你这也太不科学了

@HenryQW 
iOS上我测了下应该是绕不过，我没有surge
测试方式是 iOS 系统代理 => macOS unblockcloudmusic => macOS Charles  = 英国节点上的普通代理
用了 unblock 以后启动不会提示，可以登上去，但登上就 GDPR 退出
我看过登录的接口返回是正常的，也不知道界面上是怎么判断要弹框的
另外 Charles 里显示有很多ip访问，不是域名访问，这样 unblock 会失效的，架在国内都无法正常运行

macOS 上用这个就行了，改hosts或者设代理用都行，进入以后多切几个tab，因为要触发https降级

网页版用这个 [acgotaku/NetEaseMusicWorld](https://github.com/acgotaku/NetEaseMusicWorld)
如果能进入但不能播放就用[我的 fork](https://github.com/nondanee/NetEaseMusicWorld)

**Comment by HenryQW** [comment]
Surge 用 fengjueming/unblock-NetEaseMusic https://github.com/fengjueming/unblock-NetEaseMusic 可以绕过，闭源代码不知道怎么实现的。

**Comment by nondanee** [comment]
@HenryQW 人家应该是代回国的呀，不是写了国内节点为移动吗😂

**Comment by requestdeny** [comment]
我也想说。绕过有一台国内不就行了。我怀疑也和我一样的操作。是iplc..

**Comment by requestdeny** [comment]
没有80口。必须找一台有的转发。但是不限国内外..

**Comment by nondanee** [comment]
@allen0091老哥你的问题新开一个 issue 吧

**Comment by allen0091** [comment]
> @allen0091老哥你的问题新开一个 issue 吧
好啊

**Comment by toooonyy** [comment]
@nondanee 裸连就是直接用英国网连的啊

**Comment by requestdeny** [comment]
> @requestdeny
> 因为没有iOS设备所以测试比较麻烦，之前试过
> iOS和安卓应该差不多，都有httpdns，我上次是看着log手动加ip才成功的
> 你能详细说说用ss把dns放在服务器的搞定安卓端的步骤吗？很好奇，因为安卓对hosts是免疫的啊。

首先先自建一个DNS 。然后给自建的DNS添加规则。让请求music.163.com 走指定的ip。指定的则是自己搭建的那个网易云的hosts. 然后再把SS服务端的DNS解析从默认的8.8.8.8改成自建的DNS. 完成了此次操作。比较麻烦。但是很省事。网上有很多自建DNS的教程。还带着一堆去广告的规则。去广告的目的就是让广告的域名指向127.0.0.1. 那稍微修改一下。把网易云的域名添加进去广告里再带上ip。完事了.理论上全部的设备都有效。特别是安卓/ios这种没法改DNS又没法改hosts的。主要是图个方便。人懒.

**Comment by nondanee** [comment]
@requestdeny 我试了自建dns，可是安卓上还是无效啊。这个和直接改hosts没什么区别吧，我的理解，因为 ss 服务端无视系统 hosts 所以才要自建 dns。
看了 log 只有前几个请求经过 unblock，之后的应该是获取到 httpdns 后，直接 `https://ip` 去请求，再怎么改域名解析都没用啊
