### ISSUE TITLE
mac 配置不成功啊,是少了什么步骤吗

### ISSUE THREAD

**Issue by Xuzan9396** [nondanee/UnblockNeteaseMusic#270]
![image](https://user-images.githubusercontent.com/24741439/66414714-873ea100-ea2c-11e9-9c0f-00a9b6d25c77.png)

![image](https://user-images.githubusercontent.com/24741439/66414751-9a517100-ea2c-11e9-9657-5ae4c6b579a6.png)

![image](https://user-images.githubusercontent.com/24741439/66414790-a9d0ba00-ea2c-11e9-8dda-69931c028b69.png)

**Comment by nondanee** [comment]
2.X 原生不支持降级 http，需要从降级过的 1.X 覆盖安装才行 https://github.com/nondanee/UnblockNeteaseMusic/issues/43#issuecomment-465453286
建议装 CA 证书一步到位 #48

**Comment by Xuzan9396** [comment]
@nondanee  
![image](https://user-images.githubusercontent.com/24741439/66418318-6aa66700-ea34-11e9-9303-7330eb6d626c.png)
自签证书我已经装了， 然后将服务器私钥 (server.key) 和服务器证书 (server.crt) 拷贝我的项目中
运行的是 
![image](https://user-images.githubusercontent.com/24741439/66418438-b1945c80-ea34-11e9-86d0-5cf9aba56535.png)

**Comment by nondanee** [comment]
嗯然后应该就行了吧？

**Comment by Xuzan9396** [comment]
好像还是不太行， 我看issues 说下载这个版本， 现在网易云是这个版本,你看下我步骤，现在还是列表还是灰色的
零: 自签证书我已经装了， 然后将服务器私钥 (server.key) 和服务器证书 (server.crt) 拷贝我的项目中
运行的是,自签名ca.crt 文件导入mac系统中，选择永久信任
一：![image](https://user-images.githubusercontent.com/24741439/66418552-e99b9f80-ea34-11e9-9b0f-6dd540decb0b.png)，
二：运行的代码是node app.js -p 8080:4430 -f 59.111.181.35， 我本机的80端口和443端口都是被其他程序占用了，所以换成8080:4430，
三：![image](https://user-images.githubusercontent.com/24741439/66418707-3da68400-ea35-11e9-97cb-6bc9623cd365.png)

我的步骤还有什么问题吗？不知道什么问题， 求楼主知道 @nondanee

**Comment by nondanee** [comment]
那你先试一下全局代理行不行吧
勾选 "网页代理 (HTTP)" 和 "安全网页代理 (HTTPS)"，不要勾选 "自动代理配置"
都填地址 127.0.0.1，端口号 8080

**Comment by Xuzan9396** [comment]
@nondanee  我也是犯傻
![image](https://user-images.githubusercontent.com/24741439/66419443-ba862d80-ea36-11e9-91ce-ca42ef516e3b.png)
可以了，没点击应用，蠢了， 谢谢楼主， 早点休息， 这么晚还在回复，太感谢了，爱你😍

**Comment by nondanee** [comment]
好的👌
