### ISSUE TITLE
挂了vpn 和node 开启端口冲突问题

### ISSUE THREAD

**Issue by Xuzan9396** [nondanee/UnblockNeteaseMusic#271]
![image](https://user-images.githubusercontent.com/24741439/66448649-c993cc80-ea84-11e9-8a40-202a87860616.png)
l例如上图， 我shadowsocks 我是设置的PAC自动模式，

**Comment by Xuzan9396** [comment]
![image](https://user-images.githubusercontent.com/24741439/66448929-d49b2c80-ea85-11e9-934c-ce577a3f3d14.png)
项目是开的8080端口， 开了8080端口， vpn就用不了了，shadowsocks 是自动代理8090端口？请问这个怎么解决

**Comment by Xuzan9396** [comment]
![image](https://user-images.githubusercontent.com/24741439/66449015-1fb53f80-ea86-11e9-94e9-38dea5db96ce.png)
这个是shadowsocks开启的代理

**Comment by nondanee** [comment]
这个问题你自己解决啊
- 换个不用系统代理实现的 APP (类似 proxifier)
- 换用 hosts 模式
- 编辑 $$ 里的 gfwlist 来修改 $$ 的 PAC
- 换个策略代理 APP 把 $$ 和 node 整合到一起 (类似 surge, clash)

**Comment by Xuzan9396** [comment]
@nondanee  谢谢
