### ISSUE TITLE
ios使用http代理，无法打开古典专区

### ISSUE THREAD

**Issue by leij1ang** [nondanee/UnblockNeteaseMusic#272]
可以听无版权音乐，但是不能打开古典专区了
是不是代理之后，古典专区被拦截了？
使用的命令`nohup node app.js -p 811 -e https://xxxxx.xxxxx > /dev/null 2>&1 &`

**Comment by nondanee** [comment]
我试了下 "古典专区" Android 上也不行，其它小程序入口也都打不开
应该就是 https 被拦截了，类似这个问题 https://github.com/nondanee/UnblockNeteaseMusic/issues/30#issuecomment-472538422

iOS 的话可以安装证书试一下，参考 👉 https://github.com/nondanee/UnblockNeteaseMusic/issues/65#issuecomment-493718439

**Comment by nining377** [comment]
安卓使用我的模块是可以进古典专区的哟[nining377/UnblockMusicPro_Xposed](https://github.com/nining377/UnblockMusicPro_Xposed/releases)
