### ISSUE TITLE
无法使用hosts的方式访问网易音乐的域名

### ISSUE THREAD

**Issue by GithubLinmingxing** [nondanee/UnblockNeteaseMusic#273]
无法使用hosts的方式访问网易音乐的域名
![image](https://user-images.githubusercontent.com/35325493/66699040-ea268580-ed15-11e9-9898-3d68b2bd2f12.png)

![image](https://user-images.githubusercontent.com/35325493/66699118-8a7caa00-ed16-11e9-8578-06ed251b92e2.png)

**Comment by nondanee** [comment]
看 log 的话你在用代理模式啊

**Comment by GithubLinmingxing** [comment]
> 看 log 的话你在用代理模式啊

这是官方提供的项目呀，，我也没干啥。。

**Comment by nondanee** [comment]
我试了下没问题啊

因为如果只用 hosts 模式，log 里面应该只有网易云的请求，不会有 auth.hulu.com 的

这样吧，你改成 `-p 80:443 ...` 然后在浏览器里打开 music.163.com，看看能不能打开 (忽略证书问题)

**Comment by GithubLinmingxing** [comment]
> 我试了下没问题啊
> 
> 因为如果只用 hosts 模式，log 里面应该只有网易云的请求，不会有 auth.hulu.com 的
> 
> 这样吧，你改成 `-p 80:443 ...` 然后在浏览器里打开 music.163.com，看看能不能打开 (忽略证书问题)

后来我加了 -s 屏蔽了其他代理请求，只允许网易的。但是依旧是无法连接网络

**Comment by nondanee** [comment]
不会的吧，你把 hosts 改到 `129.28.201.39` 试一下

**Comment by GithubLinmingxing** [comment]
> 不会的吧，你把 hosts 改到 `129.28.201.39` 试一下
其他的服务器没问题的，我也是试过的，可能是我的服务器80被黑了，要么被网易屏蔽了

**Comment by nondanee** [comment]
那你发一下 IP，我试试

**Comment by nondanee** [comment]
这么说就是你自己的问题咯，那我 close 了哈

**Comment by xskyru** [comment]
好奇怪，我的现在客户端听歌没问题，但是不能更新，music.163.com也打不开，我用的hosts方法

**Comment by nondanee** [comment]
@xskyru 
安装证书了吗？不装打不开网页版
