### ISSUE TITLE
QQ音源失效

### ISSUE THREAD

**Issue by 1715173329** [nondanee/UnblockNeteaseMusic#274]
手动访问mp3地址出现403提示。

**Comment by nondanee** [comment]
知道的

**Comment by KiraYo4kage** [comment]
qq音乐的账号被ban了还是咋地，我把vkey等字段换成自己的是阔以的。

**Comment by zack66** [comment]
怎么修复qq音源

**Comment by nondanee** [comment]
@zack66
我也想问

**Comment by winterssy** [comment]
取 `purl` 字段拼接 `sip` 可获取 `.m4a` 格式的播放地址，不过版权保护的歌曲就无解了:disappointed_relieved:

**Comment by sunzongzheng** [comment]
看起来是web版接口 只能获取web版QQ音乐能听的歌曲url了

**Comment by nondanee** [comment]
@KiraYo4kage 
guid 用的是网页版游客身份的，没登录。
vkey 不是动态的吗，跟 guid 绑定的，怎么换呢？

**Comment by nondanee** [comment]
@winterssy 嗯，甚至改成 `M500` `.mp3` 都不行。。。

**Comment by lengyuxuan** [comment]
我还以为我服务器挂了。。。。

**Comment by KiraYo4kage** [comment]
> @KiraYo4kage
> guid 用的是网页版游客身份的，没登录。
> vkey 不是动态的吗，跟 guid 绑定的，怎么换呢？

我就单纯用网页版的抓包了下，然后把其他歌的vkey拿过来就可以用。手机端我也试了，就是域名不一样，然后是m4a格式的。大概这个vkey在同一次登录间是不变的吧，没太仔细研究。

**Comment by zack66** [comment]
更新了qq音源似乎还是不能用

**Comment by nondanee** [comment]
@zack66 海外不能用，VIP 歌曲不支持

**Comment by zack66** [comment]
> @zack66 海外不能用，VIP 歌曲不支持

国内服务器呢阿里云轻量

**Comment by nondanee** [comment]
@zack66 可以的

**Comment by zack66** [comment]
@nondanee 我的意思是  我是国内服务器阿里云轻量qq音源还是不能用我更新了的..   上面说的是国内服务器呢！阿里云轻量  不是问句-.-不好意思我没表达清楚sorry

**Comment by nondanee** [comment]
@zack66 
哦我应该打分号的
> 海外不能用；VIP 歌曲不支持

不是付费才行

![image](https://user-images.githubusercontent.com/26399680/67160330-30b55900-f382-11e9-8fd9-76e17b300a1c.png)

**Comment by zack66** [comment]
@nondanee 那内置一个vip账号进去就行了吧？

**Comment by nondanee** [comment]
@zack66 不知道，你试试呗

**Comment by zack66** [comment]
![image](https://user-images.githubusercontent.com/16634459/67160469-a66df480-f383-11e9-8088-82123f9837bf.png)
@nondanee 如果要内置的话是修改这一段吗？

**Comment by nondanee** [comment]
@zack66 是的

**Comment by zack66** [comment]
![image](https://user-images.githubusercontent.com/16634459/67160674-082f5e00-f386-11e9-9e7e-d65995fdc892.png)
@nondanee 你好作者 想问一下这个ID是用来干嘛的？

**Comment by nondanee** [comment]
@zack66 
是歌曲 id，拿歌曲 id 去请求音频文件链接

**Comment by zack66** [comment]
@nondanee 意思是我可以把这个ID加在上面吧

**Comment by nondanee** [comment]
@zack66 
加了没用
哦哦，懂了
你是想问 `const classic = [...]` 这个数组有什么作用吗？

是这样的
之前 QQ 音乐的 vkey 是任意歌曲任意音质通用的 (现在不可以)
即，用一首绝对可以听的歌来请求 vkey，再用这个 vkey 拼出付费歌曲高品的 url
classic 里的歌大概是 《爱如潮水》之类的经典歌曲，然后 random 随机取一首 (怕请求太集中了被封)

**Comment by zack66** [comment]
@nondanee 照你说的拼接出来也不能放啊直接403了你看看有什么不对的地方

**Comment by nondanee** [comment]
@zack66 
**之前** QQ 音乐的 vkey 是任意歌曲任意音质通用的 **(现在不可以)**

之前！
之前！
之前！

现在不可以！
现在不可以！
现在不可以！

你照我说的拼肯定不行！
