### ISSUE TITLE
mac可以播放无法下载

### ISSUE THREAD

**Issue by techxiu** [nondanee/UnblockNeteaseMusic#275]
使用Hosts方式，播放正常但是下载失败，重试几次了，如图

![截屏2019-10-13下午1.39.33.png](https://i.loli.net/2019/10/13/LW14CU8syREYc9u.png)

**Comment by xskyru** [comment]
请问你的hosts是怎添加的，我的为什么一直是失败的

**Comment by techxiu** [comment]
> 请问你的hosts是怎添加的，我的为什么一直是失败的

就改/etc/hosts啊，然后装证书信任，重新开网易云就OK了

**Comment by nondanee** [comment]
那用 migu 源匹配可以下载吗？
感觉最新版本已经修了这个问题啊

**Comment by techxiu** [comment]
> 那用 migu 源匹配可以下载吗？
> 感觉最新版本已经修了这个问题啊

也不可以诶 重试好几次了 安卓也是这样
进度条从0到100%然后下载失败
只有ios加了`-e https://music.163.com` 就能下载
不过ios只能用全局http代理 hosts不能播放不能下载

![截屏2019-10-15下午5.00.49.png](https://i.loli.net/2019/10/15/LQf5DMdKI4Noau8.png)

**Comment by nondanee** [comment]
@techxiu 
是不是阿里云上跑的版本没更新啊 👀

**Comment by techxiu** [comment]
> @techxiu
> 是不是阿里云上跑的版本没更新啊 👀

试了下把阿里云上的node升级从v6.17.1升级到了v10.16.3后
不加`-e https://music.163.com`Mac和安卓上都可以播放和下载惹，但是ios不能播放下载
加了`-e https://music.163.com`后，Mac和安卓不能下载，ios可以播放下载了
所以在服务器上跑了两个 算是解决了吧:)

**Comment by nondanee** [comment]
那么改成 `-e http://music.163.com` 呢
