### ISSUE TITLE
mac catalina 修改hosts网络连接失败

### ISSUE THREAD

**Issue by xihaoxiaohao** [nondanee/UnblockNeteaseMusic#276]
我从很久之前一直都在用修改hosts的方法，一直都很好用，现在用的是mac mojave系统也是可以成功听到灰色的音乐。
但最近朋友买了一台mac，安装的最新mac os catalina系统。
根据同样的[方法](https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-429514826), 当我运行 `node app.js -p 80 -f (ping music.163.com的ip)`打开最新的版本的网易云，terminal可以看到日志。但在朋友的电脑上用同样的方法，打开网易云，却显示网络连接失败，并且输出只显示`Server running @ http://0.0.0.0:80`看不到日志。
我检查了一下`/etc/hosts`的文件已经有
```
127.0.0.1 music.163.com
127.0.0.1 interface.music.163.com
```

请问有没有大神可以在最新的mac os成功用hosts的方法成功过？或者如何debug？

**Comment by techxiu** [comment]
Catalina成功，你证书装了吗

**Comment by xskyru** [comment]
我的10.15按照你的方法成功了

**Comment by techxiu** [comment]
> 我的10.15按照你的方法成功了

请问没版权音乐你能下载吗

**Comment by xihaoxiaohao** [comment]
> Catalina成功，你证书装了吗

@techxiu 我不是使用Proxifier的[代理方法](https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-436505087)，我用的是[修改hosts的方法](https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-429514826)，这样也需要安装证书吗？

**Comment by techxiu** [comment]
> > Catalina成功，你证书装了吗
> 
> @techxiu 我不是使用Proxifier的[代理方法](https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-436505087)，我用的是[修改hosts的方法](https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-429514826)，这样也需要安装证书吗？

macOS 客户端726 版本以后的都需要安装自签证书才行

**Comment by techxiu** [comment]
@xihaoxiaohao 见 https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-477870013

**Comment by nondanee** [comment]
之前有人反馈 798 不用装证书就可以用 #238 
不过装了证书肯定可以用

**Comment by xihaoxiaohao** [comment]
奇怪了，检查了一下log，不装证书用的是http，装了用的是https。。。

**Comment by xskyru** [comment]
我的现在也不行了，就清理过一次垃圾就不行了，之前一直很好用的。hosts里也添加了，现在客户端打开连网络都连不上

**Comment by lonelykid** [comment]
网上说catalina的自签证书有效期必须在825天之内，你可以重新签发一个试试
``
此外，所有在 2019 年 7 月 1 日后签发的 TLS 服务器证书（如证书的 NotBefore 字段中所示）必须遵循以下准则：
TLS 服务器证书必须包含一个内含 id-kp-serverAuth OID 的 ExtendedKeyUsage (EKU) 扩展。
TLS 服务器证书的有效期必须为 825 天或更短（如证书的 NotBefore 和 NotAfter 字段中所示）。
``

**Comment by hejnblack** [comment]
> 网上说catalina的自签证书有效期必须在825天之内，你可以重新签发一个试试
> `此外，所有在 2019 年 7 月 1 日后签发的 TLS 服务器证书（如证书的 NotBefore 字段中所示）必须遵循以下准则： TLS 服务器证书必须包含一个内含 id-kp-serverAuth OID 的 ExtendedKeyUsage (EKU) 扩展。 TLS 服务器证书的有效期必须为 825 天或更短（如证书的 NotBefore 和 NotAfter 字段中所示）。`

有自签证书生成的命令吗？。。。证书老是不被信任
