### ISSUE TITLE
提示“资源不存在”

### ISSUE THREAD

**Issue by Ar666** [nondanee/UnblockNeteaseMusic#278]
已部署好了服务，手机APP上灰色的确实变正常了，服务器上也刷出了日志，但是点歌曲提示“资源不存在”，各位大佬求解

**Comment by Xuzan9396** [comment]
求解，  ssl 证书， docker,代理， ios, 列表都亮了， 播放歌曲不存在

**Comment by nondanee** [comment]
有匹配日志吗？
```
[1391274164] 说好不哭
http://su.sycdn.kuwo.cn/5520fcbcd80daf53d9d9b8254ca02812/5da5b9db/resource/n3/97/51/1559630715.mp3
```
没有的话就是没匹配到，会提示不存在

server 在国外的话目前完全不可用，因为 QQ 挂掉了 #274 ，其它音源都有海外墙

**Comment by Ar666** [comment]
确实是国外的服务器，安卓手机本地搭建没问题👌🏻 谢啦
