### ISSUE TITLE
走到代理了显示连不上网

### ISSUE THREAD

**Issue by FlowerFestival** [nondanee/UnblockNeteaseMusic#279]
![image](https://user-images.githubusercontent.com/23180446/66907049-47367a00-f03b-11e9-91fd-9a5386213aeb.png)
![image](https://user-images.githubusercontent.com/23180446/66907076-5289a580-f03b-11e9-8bba-edeb47f3f59a.png)
mac证书加过了，代理开了，正常的请求页打到代理了，加了host配置就会显示没有网
![image](https://user-images.githubusercontent.com/23180446/66907182-849b0780-f03b-11e9-958f-7c93b0b3330c.png)
请问大佬是哪里有问题吗，如果不加hosts里的配置还是灰的，发现Windows就不需要加hosts直接代理就可以了

**Comment by nondanee** [comment]
emmm 设代理或者改 hosts 选一个就好了

**Comment by nondanee** [comment]
@BIGBbox  #22 有说明

**Comment by BIGBbox** [comment]
> @BIGBbox #22 有说明
看的不是很明白，我方法一和方法二那三步都操作了一遍，然后到了HTTP Server running @ http://0.0.0.0:80，就不止到怎么搞了

**Comment by nondanee** [comment]
@BIGBbox 
macOS 客户端？
看这个 👉 https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-477870013

第一个截图里的内容要有请求发到代理服务器才会有，你配置正确就会有的

用 shadowsocks 客户端的话，可以去改 shadowsocks 的 gfwlist，间接修改 PAC

**Comment by FlowerFestival** [comment]
> emmm 设代理或者改 hosts 选一个就好了

我只加代理，虽然走进来了，但是没起作用，我本地跑的node服务，不知道改选mac的哪个，选了两个页面的
![image](https://user-images.githubusercontent.com/23180446/66976534-d643a080-f0d4-11e9-8b16-e41f476f7ce4.png)

**Comment by FlowerFestival** [comment]
> 老哥你第一个页面里的内容是怎么设置的，我只设置了第三张图，代理我用的是shadowsocks，Mac端

![image](https://user-images.githubusercontent.com/23180446/66976563-e8bdda00-f0d4-11e9-9ded-8040d7c8568c.png)
设置的系统代理，没有用软件，但是好像不应该选网页不知道选哪个

**Comment by BIGBbox** [comment]
我把host改回去了，然后就能访问Google，改了host访问不了Google，不知道是哪步搞错了。。

**Comment by nondanee** [comment]
@FlowerFestival 
对的，就选这两个

**Comment by nondanee** [comment]
@BIGBbox 
可以你改 hosts 跟 google 没关系啊

**Comment by FlowerFestival** [comment]
> @FlowerFestival
> 对的，就选这两个

成功了😸
