### ISSUE TITLE
变灰歌曲破解後還是播放失敗

### ISSUE THREAD

**Issue by allen0091** [nondanee/UnblockNeteaseMusic#28]
有沒有人跟我一樣，使用音量增強器可以破解手機端变灰歌曲，但這個hosts方法破解好像只破解讓歌曲顯示不变灰而已

**Comment by nondanee** [comment]
大佬写的肯定比我的高级多了啊 😂
音量增强是有后端的，有 cloudflare 挡着我也不知道它的后端在哪儿
@bin456789 大佬能不能悄咪咪透露下后端实现鸭

**Comment by allen0091** [comment]
> 大佬写的肯定比我的高级多了啊 😂
> 音量增强是有后端的，有 cloudflare 挡着我也不知道它的后端在哪儿
> @bin456789 大佬能不能悄咪咪透露下后端实现鸭

我以為是bug 抱歉

**Comment by jason5545** [comment]
增強器好像也不能用了現在

**Comment by allen0091** [comment]
> 增強器好像也不能用了現在
网易云的版本好像要4.3才能用

**Comment by allen0091** [comment]
> 增強器好像也不能用了現在

网易云的版本好像要4.3才能用
