### ISSUE TITLE
什么都弄好了 老是说网络无法连接 

### ISSUE THREAD

**Issue by wpf900** [nondanee/UnblockNeteaseMusic#281]
项目搭建到了阿里云服务器上 node app.js -p 8080 是可以运行的 音乐是可以搜到的然后把这个音乐地址复制到浏览器上也是可以听的没有任何问题  但是 手机上面就是显示网络不给力 播放失败
下是请求的日志 和手机的效果
![911571305069_ pic](https://user-images.githubusercontent.com/35316602/67001274-ec208800-f10b-11e9-8b00-77dbbabf859b.jpg)
![931571305073_ pic](https://user-images.githubusercontent.com/35316602/67001294-f5115980-f10b-11e9-9990-99d896d686ee.jpg)

**Comment by nondanee** [comment]
去看 #65
