### ISSUE TITLE
不能适用于低版本的安卓版本吗

### ISSUE THREAD

**Issue by theFreeWall** [nondanee/UnblockNeteaseMusic#282]
利用安卓的Termux安装了 Node.js.
git运行之后成功出现http server running @http://0.0.0.0.:端口
并且能够成功从0.0.0.0下载pac文件,wlan代理配置也检查了
但是打开app并没有效果,网易云app版本号3.6.1
其他的几个插件都是支持4.1以上,所以猜测低版本的安卓端app不适用吗?
被这个问题困扰了好久......

**Comment by theFreeWall** [comment]
利用代理一定需要服务器支持吗?
按照 #256 drony配置的方法,我主机名填写的本地地址(127.0.0.1)
虽然Termux的页面一直不停的显示消息,tunnel> x.x.x.x(应该成功是让所有的连接都走了这个代理的意思吧),但实际上连不上去网

**Comment by nondanee** [comment]
@theFreeWall 
要选一下过滤器的，全局的话会把 termux 也代理了的

在 #256 的基础上
```
WIFI_NAME/NOT LISTED NETWORKS- 過濾器：
過濾默認值：引導全部
```
```
WIFI_NAME/NOT LISTED NETWORKS-過濾器：規則
(添加)
行動：允許所有
應用程序：网易云音乐
(保存)
```
你试试
确实有点复杂 =.=

**Comment by theFreeWall** [comment]
在设置仅代理网易云后, 成功有了MITM > music.163.com,但是网易云还是无法连接网络.........
并且还多了MITM > crash.163.com  似乎是崩溃上传bug的网址.
drony报错java.io.IOException:No data received from the server
我还尝试了一下大佬您另一个项目https://github.com/nondanee/Nroxy
但是报错java.io.IOException: Error running exec(). Command: [sh, -c, node /storage/emulated/0/Download/app.js ] Working Directory: /data/data/dev.nondanee.nroxy/files Environment: [PATH=$PATH:/data/data/dev.nondanee.nroxy/files/usr/bin]

**Comment by nondanee** [comment]
我去试了下，toast 一直在报 "服务器发生错误 (scode: 400)"，确实用不了，我也不太清楚
那个项目的问题还是去那边提吧
这边的问题应该解释清楚了，我就 close 了哈
