### ISSUE TITLE
可不可以多一个网易云音乐路径指定的选项

### ISSUE THREAD

**Issue by hupo376787** [nondanee/UnblockNeteaseMusic#283]
这样，点击启动后，直接启动云音乐，不用手动点击一次啦。

不过看作者心情啦，多点击一次也无所谓的啦，毕竟做的这么好

**Comment by nondanee** [comment]
我这边不支持点击启动
你说的应该是 @XIU2 的 GUI 工具吧，feature request 请直接找他

如果是点击 .bat 启动
那这样就可以
```cmd
start /d "C:\Program Files (x86)\Netease\CloudMusic\" cloudmusic.exe
node app.js
```
