### ISSUE TITLE
网络不给力，无法继续播放

### ISSUE THREAD

**Issue by a08381** [nondanee/UnblockNeteaseMusic#285]
![D5EECA39-7D2D-41A6-B50A-E0E6E5804009](https://user-images.githubusercontent.com/2505002/67146449-bd4a1380-f2bd-11e9-8887-d9cd8bce489b.png)
![9D71549B-F5FB-4AB8-B8F7-4743B486644A](https://user-images.githubusercontent.com/2505002/67146452-bde2aa00-f2bd-11e9-9511-b3b1557c9f64.png)

后台log正常

**Comment by nondanee** [comment]
看看 👉 #65

**Comment by K819** [comment]
加了（-s -e http s）只能播放第一首 之后出错 不知道因为什么 我的log和这个老哥很像 都能解析到url 但是不能播放

**Comment by a08381** [comment]
![QQ截图20191020154704](https://user-images.githubusercontent.com/2505002/67156438-229b1480-f351-11e9-8324-5908464d8dd8.png)

**Comment by a08381** [comment]
![QQ截图20191020154704](https://user-images.githubusercontent.com/2505002/67156456-5d04b180-f351-11e9-91cc-844aa70f5b7d.png)

![IMG_7744](https://user-images.githubusercontent.com/2505002/67156464-6b52cd80-f351-11e9-96c2-9c51622f1af3.PNG)

![IMG_7745](https://user-images.githubusercontent.com/2505002/67156469-7d347080-f351-11e9-8e0c-8d226c1c6730.PNG)



> 看这个 👉 #65

那么我问一句我哪里操作有问题吗？

**Comment by a08381** [comment]
> 看这个 👉 #65

![QQ截图20191020160543](https://user-images.githubusercontent.com/2505002/67156621-9dfdc580-f353-11e9-8ac2-7fbb08a8231c.png)

![IMG_7744](https://user-images.githubusercontent.com/2505002/67156624-a524d380-f353-11e9-8f4d-ac67bc0c1473.PNG)
![IMG_7745](https://user-images.githubusercontent.com/2505002/67156625-a8b85a80-f353-11e9-8484-1be487339960.PNG)

这下配置没错了吧？

**Comment by hydra77** [comment]
我也是信任了证书了，还是没用

**Comment by nondanee** [comment]
@K819 这个就不清楚了

**Comment by nondanee** [comment]
@a08381 
应该没错，但是你这次截图没有匹配成功的 log
看你的 VPN 亮着，建议先测试一下设置 WLAN 代理能不能用
另外，最好在 #65 反馈，那边 iOS 用户比较多
我没有 iOS 设备，不好意思

**Comment by nondanee** [comment]
@hydra77 应该有用啊

**Comment by hydra77** [comment]
> @hydra77 应该有用啊

我也很绝望呀，确实没用。。。。我这几天在nas重复安装这个好多次了

**Comment by nondanee** [comment]
@hydra77 
不好意思我没有 iOS 设备，所以我不知道现在到底行不行
不过我i感觉，如果有人说有用，那就是有用的 =.=

**Comment by hydra77** [comment]
> @hydra77
> 不好意思我没有 iOS 设备，所以我不知道现在到底行不行
> 不过我感觉，如果有人说有用，那就是有用的 =.=

emmm,应该是有用的，因为有人用国内的vps搭建成功了，配合surge或者其他软件都是没有问题，只是我使用docker里的镜像搭建的时候确实遇到了问题，这几天一直在寻找问题的根源。
