### ISSUE TITLE
nodeJS 显示请求成功但是网络无法连接

### ISSUE THREAD

**Issue by fengxiakira** [nondanee/UnblockNeteaseMusic#286]
<img width="600" alt="Screen Shot 2019-10-19 at 6 33 30 PM" src="https://user-images.githubusercontent.com/16449313/67152181-5f0e3800-f29f-11e9-8936-839f6fcb0641.png">
<img width="1008" alt="Screen Shot 2019-10-19 at 6 31 08 PM" src="https://user-images.githubusercontent.com/16449313/67152184-63d2ec00-f29f-11e9-9a99-00e04d8950d7.png">
<img width="555" alt="Screen Shot 2019-10-19 at 6 30 21 PM" src="https://user-images.githubusercontent.com/16449313/67152185-6d5c5400-f29f-11e9-946a-f1aa95c4350d.png">

项目已经更新至最新。node显示请求成功但是不知为何出现了tunnel 143 ?

云音乐版本号1.5.10

谢谢大佬！

**Comment by fengxiakira** [comment]
<img width="422" alt="Screen Shot 2019-10-19 at 9 16 15 PM" src="https://user-images.githubusercontent.com/16449313/67153396-6f7ddd00-f2b6-11e9-81b3-85fddcc3ccb7.png">
<img width="568" alt="Screen Shot 2019-10-19 at 9 18 37 PM" src="https://user-images.githubusercontent.com/16449313/67153398-7278cd80-f2b6-11e9-8a65-4bcd70a6f3f3.png">
<img width="776" alt="Screen Shot 2019-10-19 at 9 16 33 PM" src="https://user-images.githubusercontent.com/16449313/67153400-7573be00-f2b6-11e9-87ee-ba18dca99108.png">

改了host后，只显示了一次mitm，但网络还是无法连接
网易云版本号2.0.0
macOS mojave

**Comment by nondanee** [comment]
1.5.10 那个情况再点击其他 tab，切换歌单，应该就能显示出来了
2.0.0 这个情况我不太清楚

代理模式和 hosts 模式都可以用，没什么区别
如果降级一直不成功的话建议安装一下 CA 证书，参考 #48

**Comment by zack66** [comment]
> 1.5.10那个情况再点击其他标签，切换歌单，应该可以显示出来了
> 2.0.0这个情况我不太清楚
> 
> 代理模式和hosts模式都可以用，没什么区别
> 如果降级一直不成功的话建议安装一下CA证书，参考[＃48](https://github.com/nondanee/UnblockNeteaseMusic/issues/48)

0.20.1说好不哭可以放  周杰伦其它歌都放不出来
![image](https://user-images.githubusercontent.com/16634459/67156725-1add6f00-f355-11e9-8b11-7159c7409685.png)

**Comment by nondanee** [comment]
@zack66 
接口限制，用其他源也可以啊

**Comment by fengxiakira** [comment]
> 1.5.10 那个情况再点击其他 tab，切换歌单，应该就能显示出来了
> 2.0.0 这个情况我不太清楚
> 
> 代理模式和 hosts 模式都可以用，没什么区别
> 如果降级一直不成功的话建议安装一下 CA 证书，参考 #48

 试过切换歌单和tab同样还是网络无法连接。
代理模式是否会有自动断网的风险？

**Comment by nondanee** [comment]
@fengxiakira 
那无法降级，就直接装证书吧

会吧，高可用做不到
代理不关一般没问题，如果 crash 了就用 error log 发个 issue
当然代理关了其实也不一定就断网了，因为不是所有程序都遵循系统代理
用 PAC 会比全局代理好一点
改 hosts 也没问题，看你自己了，怎么舒服怎么来

**Comment by fengxiakira** [comment]
> @fengxiakira
> 那无法降级，就直接装证书吧
> 
> 会吧，高可用做不到
> 代理不关一般没问题，如果 crash 了就用 error log 发个 issue
> 当然代理关了其实也不一定就断网了，因为不是所有程序都遵循系统代理
> 用 PAC 会比全局代理好一点
> 改 hosts 也没问题，看你自己了，怎么舒服怎么来

问个小白问题，我用系统默认的ca证书怎么装啊，直接点击就好了么？
最后信任是这样的么？
<img width="695" alt="Screen Shot 2019-10-20 at 9 45 28 AM" src="https://user-images.githubusercontent.com/16449313/67160475-201fc700-f31f-11e9-8381-d80355ec43c9.png">

**Comment by nondanee** [comment]
@fengxiakira 是的

**Comment by fengxiakira** [comment]
我现在PAC代理也开了，证书也签了，可还是不行TAT ， 依旧网络无法连接

证书是*.music.163.com和UnblockNeteaseMusicRoot CA么？

<img width="990" alt="Screen Shot 2019-10-20 at 10 01 55 AM" src="https://user-images.githubusercontent.com/16449313/67160612-ae487d00-f320-11e9-97d6-2eaced2a376e.png">


<img width="695" alt="Screen Shot 2019-10-20 at 9 56 41 AM" src="https://user-images.githubusercontent.com/16449313/67160554-25c9dc80-f320-11e9-9d14-c1eb89a08052.png">
<img width="565" alt="Screen Shot 2019-10-20 at 9 45 44 AM" src="https://user-images.githubusercontent.com/16449313/67160569-4e51d680-f320-11e9-8edb-d8b432efdd15.png">

**Comment by nondanee** [comment]
@fengxiakira 
那你肯定没有好好看 🤔 https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-477870013
用代理改成 `node app.js -p 8080:8081`
用 hosts 改成 `node app.js -p 80:443 -f xxx.xxx.xxx.xxx`

**Comment by fengxiakira** [comment]
谢谢作者大大！ 现在可以放歌了！开心！
刚刚忽视了最后一步

所以换了端口就没有MITM和TUNNEL日志了么？我到现在还不知道这两个什么意思🤔

另外这个项目是可以打开网易付费歌曲的么？是不是还需要更换源？

麻烦作者大大了！

<img width="560" alt="Screen Shot 2019-10-20 at 10 07 16 AM" src="https://user-images.githubusercontent.com/16449313/67160676-75f56e80-f321-11e9-9cea-5522f1797c08.png">

**Comment by fengxiakira** [comment]
<img width="538" alt="Screen Shot 2019-10-20 at 10 14 53 AM" src="https://user-images.githubusercontent.com/16449313/67160807-80fcce80-f322-11e9-8be8-da4150068d62.png">

还是网络无法连接的样子，但反而我用80:443 可以跑起来？
至少网络可以连接了？

不懂求解😂

<img width="560" alt="Screen Shot 2019-10-20 at 10 07 16 AM" src="https://user-images.githubusercontent.com/16449313/67160820-a38ee780-f322-11e9-8d33-9c7609266b10.png">

**Comment by nondanee** [comment]
有请求到服务器上才会有日志 (hosts 模式应该只有 MITM 没有 TUNNEL)

mitm 和 tunnel 是 http 代理的两种方式，具体可以看 Jerry Qu 的这篇博文 https://imququ.com/post/web-proxy.html

可以，不用换源

**Comment by nondanee** [comment]
改了 hosts 就用 `-p 80:443`，还需要 `-f`
用代理就随便什么端口

看 log 应该已经正常了啊

**Comment by fengxiakira** [comment]
> 改了 hosts 就用 `-p 80:443`，还需要 `-f`
> 用代理就随便什么端口
> 
> 看 log 应该已经正常了啊

就是用PAC的话还是要加`-f 80:443` 还是 和 可以和host一样 `-p 80:443 -f`？

**Comment by fengxiakira** [comment]
<img width="558" alt="Screen Shot 2019-10-20 at 10 26 30 AM" src="https://user-images.githubusercontent.com/16449313/67160980-26fd0880-f324-11e9-9873-18e25c098273.png">

我觉得我启动命令也没有错啊，
但结果还是网络无法连接😢

**Comment by nondanee** [comment]
@fengxiakira 回头看了下，是你证书装错了 =.=
你是不是装了 server.crt？
应该要装 ca.crt，不用装 server.crt

**Comment by fengxiakira** [comment]
> @fengxiakira 回头看了下，是你证书装错了 =.=
> 你是不是装了 server.crt？
> 应该要装 ca.crt，不用装 server.crt

原来是这样！！我以为两个都要装

我再去试试！

**Comment by fengxiakira** [comment]
<img width="564" alt="Screen Shot 2019-10-20 at 10 39 34 AM" src="https://user-images.githubusercontent.com/16449313/67161181-f61dd300-f325-11e9-9f1f-9b101ec90856.png">

但有个问题，虽然歌不是灰的了但还是会自动替换成qq的源？明明是网易自己源的歌啊

也导致了歌不能放🤔

**Comment by nondanee** [comment]
@fengxiakira 
网易云的会员专享，没有会员就是不能听的
无法播放的时候会做匹配，替换成 QQ 源 
(网易有版权但是你的账户没有权限，并没有破解一说)
