### ISSUE TITLE
qq音源问题

### ISSUE THREAD

**Issue by zack66** [nondanee/UnblockNeteaseMusic#287]
似乎只能播放周董的说好不哭 周董其它歌都不能播放

**Comment by zack66** [comment]
http://music.wandhi.com/

**Comment by zack66** [comment]
> http://music.wandhi.com/
> 这个网站是否能拿来当API

![image](https://user-images.githubusercontent.com/16634459/67156906-1ade6e80-f357-11e9-836a-3ac289d090f3.png)
这个网站可以直接抓到播放地址

**Comment by nondanee** [comment]
不会接入第三方服务，你可以自己加到 provider 里
而且我试了，这个网站也只能播放《说好不哭》
