### ISSUE TITLE
想写一个类似的解析工具，但遇到了问题。

### ISSUE THREAD

**Issue by ejiaogl** [nondanee/UnblockNeteaseMusic#288]
1. 调用搜索接口“https://c.y.qq.com/soso/fcgi-bin/client_search_cp”，在返回的json中保存 “key=media_mid”的mid值。
2. 调用生成vkey接口“https://u.y.qq.com/cgi-bin/musicu.fcg” 随机{ "001yS0N33yPm1B", "000bog5B2DYgHN", "002bongo1BDtKz", "004RDW5Q2ol2jj","001oEME64eXNbp", "001e9dH11YeXGp", "0021onBk2QNjBu", "001YoUs11jvsIK", "000SNxc91Mw3UQ"，"002k94ea4379uy" } 传入该数组中的mid值，最终获得vkey。
3. 使用上述接口获取的vkey和media_mid值拼接出最终播放的url地址。

问题：
1. 上述第三点中拼接出的URL访问返回403
2. 上述第二点的接口会有两个vkey返回
JSONObject tmpJob = datasJob.getJSONArray("midurlinfo").getJSONObject(0);
vkey = tmpJob.getString("vkey");
if ("".equals(vkey)) {
	String testfile2g = datasJob.getString("testfile2g");
	String pattern = "vkey=(.*?)&";
	Pattern r = Pattern.compile(pattern);
	Matcher m = r.matcher(testfile2g);
	m.find();
	vkey = m.group(1);
}
第一个是从midurlinfo中的JSONObject中获取，第二个vkey是从testfile2g中正则出来，该思路是观看qq.js文件中所得到的，但是这两个key都无法播放新拼接出来的歌曲，即原纪录的media_mid； 希望得到作者的回复 感谢该项目。

**Comment by nondanee** [comment]
1. 是的，现在 vkey 是一对一的，指定 mid 指定音质，对应一个 vkey，不可重用。一首歌获得 vkey 拼到其他歌上就会 403
2. 因为从海外请求 midurlinfo 中取不到 vkey，但是海外请求返回了 testfile，里面的 vkey 可以拿来用

你分析的代码似乎早了一点呢，已经失效了 (4 天前) #274

**Comment by ejiaogl** [comment]
感谢作者的回复，已经更新好匹配规则以及下载无损了。

**Comment by nondanee** [comment]
NB 的
下载无损需要 cookie 吗？
用别的 API 吗？能不能公开？要不你 PR 一下？
![30b440a7ae5f9cd0](https://user-images.githubusercontent.com/26399680/67163726-01fcaa00-f3a5-11e9-8648-3c1aba257c3d.jpg)

**Comment by ejiaogl** [comment]
> NB 的
> 下载无损需要 cookie 吗？
> 用别的 API 吗？能不能公开？要不你 PR 一下？
> ![30b440a7ae5f9cd0](https://user-images.githubusercontent.com/26399680/67163726-01fcaa00-f3a5-11e9-8648-3c1aba257c3d.jpg)

F000 FLAC COOKIE 内置大法牛逼 哈哈哈哈哈哈哈

**Comment by zack66** [comment]
> NB 的
> 下载无损需要 cookie 吗？
> 用别的 API 吗？能不能公开？要不你 PR 一下？
> ![30b440a7ae5f9cd0](https://user-images.githubusercontent.com/26399680/67163726-01fcaa00-f3a5-11e9-8648-3c1aba257c3d.jpg)

内置账号就好了呀.flac

**Comment by nondanee** [comment]
@ejiaogl @zack66 
那我做不来
![5CA91BFF3C3E34948F26A1EB8D35F659](https://user-images.githubusercontent.com/26399680/67179415-c98eb780-f408-11e9-9594-14b2cb75cb4a.jpg)

**Comment by ejiaogl** [comment]
> @ejiaogl @zack66
> 那我做不来
> ![5CA91BFF3C3E34948F26A1EB8D35F659](https://user-images.githubusercontent.com/26399680/67179415-c98eb780-f408-11e9-9594-14b2cb75cb4a.jpg)

如果需要解析数字专辑，好像还是需要以前的那个接口 现在这个接口不可以
