### ISSUE TITLE
QQ 音乐 Vkey 为空 

### ISSUE THREAD

**Issue by zhangchaojiong** [nondanee/UnblockNeteaseMusic#289]
为什么部分 歌曲的 vkey 无法请求到？ 譬如下面：

https://c.y.qq.com/base/fcgi-bin/fcg_music_express_mobile3.fcg?g_tk=0&loginUin=0&hostUin=0&format=json&inCharset=utf8&outCharset=utf-8&notice=0&platform=yqq&needNewCode=0&cid=205361747&uin=0&guid=7332953645&songmid=001xd0HI0X9GNq&filename=M500001xd0HI0X9GNq.mp3

**Comment by nondanee** [comment]
你这个问题应该问 QQ 音乐啊！这是 QQ 音乐的接口，又不是我写的。。。 (VIP 歌曲怎么能让你随便拿 vkey？)
