### ISSUE TITLE
android端的指定代理问题

### ISSUE THREAD

**Issue by shugo-chara** [nondanee/UnblockNeteaseMusic#29]
在termux上安装了项目并且测试在wifi下可以正常解锁。
但是在移动网络下无效，想法是尝试用代理软件指定网易云，但是试了好几个软件都无效不知道为什么。
adguard里自带的代理，127.0.0.1:8080下指定网易云后代理提示正常，网易云无效。
drony里设置127.0.0.1：8080后termux里全局都有流量在跑，但是唯独网易云提示网络异常。
ss里设置127.0.0.1后网易云网络异常
不知 @nondanee 有没有android端可以用的指定应用走http代理的app。我找了好多发现都无法使用。要么网易云不生效，要么就是网易云提示网络异常。

**Comment by nondanee** [comment]
这个应该可以 [MengAndy/tun2http](https://github.com/MengAndy/tun2http/stargazers) 
[L172](https://github.com/MengAndy/tun2http/blob/master/android_app/app/src/main/java/com/tun2http/app/service/Tun2HttpVpnService.java#L172) 改成网易云的包名
不过需要自编译（我自己测试都是wifi环境，vpnservice 实现应该移动数据可用）

其实我已经在写安卓端了==
就是把 tun2http 和 nodejs 环境打包在一个 app 里
不会安卓开发，期末了根本没时间学，等放假吧，争取圣诞做出来！

**Comment by shugo-chara** [comment]
> 这个应该可以[MengAndy / tun2http ](https://github.com/MengAndy/tun2http/stargazers)
> [L172](https://github.com/MengAndy/tun2http/blob/master/android_app/app/src/main/java/com/tun2http/app/service/Tun2HttpVpnService.java#L172)改成网易云的包名
> 不过需要自编译（我自己测试都是wifi环境，vpnservice实现应该移动数据可用）
> 
> 其实我已经在写安卓端了== 
> 就是把tun2http和nodejs环境打包在一个app里
> 不会安卓开发，期末了根本没时间学，等放假吧，争取圣诞做出来！

@nondanee 速度好快～。好消息是刚刚又尝试了proxydroid这个老软件，终于成功指定代理网易云。
测试保持termux开启在后台，proxydroid代理之前网易云里搜索jay的歌一片灰，开启代理后恢复正常。坏消息是点进去歌曲要么提示资源不存在（大概是从服务器被删掉了？），要么出来的歌都是翻唱或者自制的版本，原曲均无法试听。终端里显示是xiami音乐的链接，但都是翻唱之类的- -。

**Comment by nondanee** [comment]
额，好像网页版用 `X-Real-IP` 绕过一次以后，其它端就能直接听了，很神奇 (不知道网易云内部逻辑)

**Comment by nondanee** [comment]
哦不，我看了下 QQ 的音源挂了...

**Comment by nondanee** [comment]
额尴尬，没挂，是我开错代理了...

**Comment by shugo-chara** [comment]
试了下nondanee/NetEaseMusicWorldPlus这个chrome的插件，对我这好像无效，网页端依旧灰色。
音源错误问题好像是抓到的虾米替换音源不对的原因，因为其他音乐库那边同样的歌曲也下架的原因吧- -
如果这样的话估计就没办法了。。
不过X-Real-IP的话，确实不清楚网易云的逻辑。网页端我很少使用，前阵子开始手机端4g和wifi直连下大部分都可以正常试听，mac的话依旧需要代理反灰才行。以前的话是所有平台都需要反代。不知是手机端的检测比较宽松还是间隔较长之类的，确实怪。
总之现在能全平台愉快的听歌了～～因为不听华语所以配合插件使用感良好。

**Comment by nondanee** [comment]
主要是不代理回国就没法使用 QQ 的音源
插件应该可以用的吧......

**Comment by nondanee** [comment]
@shugo-chara 
要让插件生效需要先关闭其它客户端，然后刷新网页版，接着各个端都能听了好像，你试试（同学告诉我的）有效时间 1-2 天
e.g. 如果已经开了 mac 端是灰的，那么插件在网页版无效，需要先关闭 mac 端，然后刷新(?或者重开)网页

**Comment by shugo-chara** [comment]
@nondanee 哦哦，测试确实如此，现在正常了。感谢～

**Comment by shugo-chara** [comment]
@nondanee 想问一下没有版权的歌是不是还是听不了。id=512376359这首在代理前是灰色，代理后客户端正常反灰但无法播放。以及可以试试咨询下大音量作者请求把他的源添加进来，很准的说。
ps。。android端上更新版本的命令和pc不一样吗，pc上正常更新android一直报错。。

**Comment by nondanee** [comment]
@bin456789 咨询一下可以用你的接口吗？
@shugo-chara 安卓上一直报错？是”关于网易云音乐“里面那个”新版更新“吗？还是说下 APK 报错？

**Comment by shugo-chara** [comment]
> @bin456789 咨询一下可以用你的接口吗？
> @shugo-chara 安卓上一直报错？是”关于网易云音乐“里面那个”新版更新“吗？还是说下 APK 报错？

不是，是unblockneteasemusic更新出错，一直提示找不到仓库地址。

**Comment by nondanee** [comment]
@shugo-chara 
哦哦，一样是 `git pull` 啊，我没改过 repo 的名字，可能是你没有 cd 到 project 文件夹里面执行？

**Comment by bin456789** [comment]
@nondanee 最好不要用，因为我的经常会挂掉，我过几天整理下歌曲匹配的细节再发给你

**Comment by nondanee** [comment]
@bin456789 好的，多谢大佬！

**Comment by shugo-chara** [comment]
@bin456789 哇～大大同意啦。感谢分享。
@找到原因了，android p上终端路径变了，更新路径就好了。嘿嘿，感觉圣诞节就有两个大佬联合出手的超级音量增大用了，开心。

**Comment by louisanna** [comment]
怎么和adguradhome 一起使用啊

**Comment by nondanee** [comment]
@louisanna 
查了下 adgurad home 是个 dns？
那么你把部署用的机器 dns 改了就好了
docker 启动可以就  `--dns=IP_ADDRESS`

**Comment by louisanna** [comment]
> @louisanna
> 查了下 adgurad home 是个 dns？
> 那么你把部署用的机器 dns 改了就好了
> docker 启动可以就 `--dns=IP_ADDRESS`

那我 adguard home 和UnblockNeteaseMusic在在一台设备上使用呢

**Comment by nondanee** [comment]
@louisanna 
dns IP 写 127.0.0.1 就行了吧

**Comment by louisanna** [comment]
> @louisanna
> dns IP 写 127.0.0.1 就行了吧

就是我AdGuardHome的解析dns为127.0.0.1：#端口？

**Comment by nondanee** [comment]
@louisanna 
应该是吧，dns 端口默认是 53，一般不用填的

**Comment by nondanee** [comment]
@shugo-chara 
安卓端最近写好了，咕了很久 😂，感兴趣的话可以试试看
https://github.com/nondanee/UnblockNeteaseMusic-Android
