### ISSUE TITLE
音源

### ISSUE THREAD

**Issue by iDesperad0** [nondanee/UnblockNeteaseMusic#291]
好久不见😆，之前觉得可能用kuwo的音源用到死的，不想前两天发现kuwo音源已经挂了，刚刚更新了最新版，已经修复了。现在的音源是不是这个情况：

- kuwo，最近已经不能100%获取320kbps的音源了，大部分是128kbps，拿大热的周杰伦举例，同一个歌手的不同歌曲也可能音质不同。海外还可以访问。

- QQ，基本全是128kpbs的音源，海外不能访问。

- migu，目前感觉匹配规则最诡异的音源😆，但是杰伦的歌都是高音质，海外可访问。

- 所有平台上需要另外购买的歌曲，全都是128kbps的低音质。

然后，有个建议，就是能否开个专门的issue来记录各大音源的流动变化，这样能直观的了解到当前这些音源的具体使用情况，也能减少很多没必要的issue提交。

另外，首页README中咪咕写成了咕咪，发现好久了，就没人提吗😆。

最后，感谢一直以来的持续分享。

**Comment by nondanee** [comment]
酷我海外能用吗？之前我试过不行吧
最近发现咪咕海外也用不了，之前可以
现在应该是所有的源在海外都用不了 (JOOX 不算)

我这边试了下酷我周杰伦的歌都是 320k 啊
QQ 改成了最普通的实现，128k (项目刚开始的时候用的这个 API)

其实能听付费纯属运气，钻空子，以后肯定越来越严格

一直没发现 😂

**Comment by iDesperad0** [comment]
@nondanee 我现在就用最新的版本部署的，vps在韩国，酷我能用的，就是有的320k有的128k，杰伦的歌我一会清除缓存再试试

嗯 我一直主张该花钱的时候要花钱，一直开着网易的黑胶，但是没版权的歌你花多少钱也没用，而且还不喜欢128kbps低音质的，实属无奈

不过我觉得尽管曲折，但是各大音源的API应该是不会彻底关闭的

谁让我们宁可用spotify也不想用QQ呢😂

**Comment by iDesperad0** [comment]
最新发现：你搜一搜罗大佑的《耶稣的另一个名字》这首歌，酷我的匹配令我哭笑不得😂😂😂

**Comment by nondanee** [comment]
看了下匹配的是这个《主播赏新晴：爱的另一个名字，叫做“聊得来”-李晓木》
http://kuwo.cn/play_detail/24615530

**Comment by nondanee** [comment]
API 不会关但是 Access Control 会加强，付费资源肯定会受限

**Comment by iDesperad0** [comment]
酷我我这里大陆IP也用不了了，能帮忙测试一下吗？

http://music.163.com/song?id=524149844&userid=186057

这首歌，我这里kuwo和qq都不行了，以前都是OK的。

**Comment by nondanee** [comment]
@iDesperad0 
没问题

![](https://user-images.githubusercontent.com/26399680/69008525-67cd5900-0986-11ea-81bb-a2f1ab572d7d.png)

http://su.sycdn.kuwo.cn/a30e7a3cf8edb9788fcd3eef13dbbf3b/5dd1537a/resource/n3/4/87/1555886531.mp3

**Comment by iDesperad0** [comment]
@nondanee 
我哭了，我只更细了一个版本而已，为什么我不行😭

命令：node app.js -o kuwo qq，就这么简单

**Comment by nondanee** [comment]
@iDesperad0 

不知道 ==

![image](https://user-images.githubusercontent.com/26399680/69008788-76693f80-0989-11ea-9f59-690f8bb61d37.png)

**Comment by iDesperad0** [comment]
@nondanee 
我刚又重拾在Mac本机部署，竟然OK了，之前一直用的是局域网内Docker部署。（奇怪，明明docker版用了好久了，一直都没怎么变动过，我再自己排查一下😭

另外，现在是不是kuwo kugou qq xiami migu这些常用源海外已经全都失效了？

最后，新的YouTube Music曲库很给力吗，想去试试了😁。

Always, thx.

**Comment by nondanee** [comment]
@iDesperad0
好

是的，全部不可用

我不知道，youtube 只是调通了 ==
webm 格式客户端播不了，m4a 音质一般，不是 mp3/flac 所以下载可能也有问题
