### ISSUE TITLE
服务器上启动 配置 -a 域名 失败

### ISSUE THREAD

**Issue by ibearye** [nondanee/UnblockNeteaseMusic#294]
启动
`node app.js -p 163 -a api.***.com`

提示
```
HTTP Server running @ http://api.***.com:163
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL: address not available 47.*.*.*:163
    at Server.setupListenHandle [as _listen2] (net.js:1263:19)
    at listenInCluster (net.js:1328:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1461:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:61:10)
Emitted 'error' event at:
    at emitErrorNT (net.js:1307:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by nondanee** [comment]
`-a` 是 listen 的地址，只有本机地址才行

**Comment by ibearye** [comment]
要设置在阿里云的ecs，独立ip是必须的吗？我尝试过默认参数启动，但是本地上代理填的是服务器公有ip，没成功。

**Comment by nondanee** [comment]
默认监听 0.0.0.0，公网应该可以访问的
没成功怎么体现？

**Comment by ibearye** [comment]
> 默认监听 0.0.0.0，公网应该可以访问的
> 没成功怎么体现？

歌还是灰的

**Comment by zyyz2450** [comment]
你是用的什么系统和软件？quantumult x可能会出现不能解锁的情况，用quantumult就可以

**Comment by ibearye** [comment]
> 你是用的什么系统和软件？quantumult x可能会出现不能解锁的情况，用quantumult就可以

mac os，直接系统偏好里改的。

本地搭建，是可以用的。阿里云ecs上不行。我也搞不太懂

**Comment by nondanee** [comment]
@ibearye 
`-a` 不设置默认全地址监听的，不用改
检查一下安全组防火墙之类的东西，可以直接从浏览器访问试试看
还有国内云用域名都要备案，没备案只能用 IP

**Comment by zyyz2450** [comment]
> > 你是用的什么系统和软件？quantumult x可能会出现不能解锁的情况，用quantumult就可以
> 
> mac os，直接系统偏好里改的。
> 
> 本地搭建，是可以用的。阿里云ecs上不行。我也搞不太懂

我是用了-a 127.0.0.1 做本地代理，然后用goproxy转成ss链接，你可以试试
