### ISSUE TITLE
网易云客户端播放灰色歌曲显示加载失败.

### ISSUE THREAD

**Issue by Archermars** [nondanee/UnblockNeteaseMusic#295]
我在自己的局域网弄了这个服务,灰色的歌曲会变成黑色,都能听,一切正常,
当放到公网服务器上设置这个服务时,歌曲是能变黑色,防火墙没拦截,但有些原本是灰色歌会显示加载失败,

**Comment by nondanee** [comment]
海外 VPS 不支持
