### ISSUE TITLE
某些歌曲，与实际不符

### ISSUE THREAD

**Issue by ZORfree** [nondanee/UnblockNeteaseMusic#296]
![image](https://user-images.githubusercontent.com/26847215/67730602-7207d180-fa30-11e9-87a1-ae67224e2780.png)
如图，时间对不上，实际内容也是完全不同，之前还可以的呢

**Comment by nondanee** [comment]
已知问题 https://github.com/nondanee/UnblockNeteaseMusic/issues/30#issuecomment-517984439
之前是什么时候？

**Comment by ZORfree** [comment]
> 已知问题 [#30 (comment)](https://github.com/nondanee/UnblockNeteaseMusic/issues/30#issuecomment-517984439)
> 之前是什么时候？

大概时间记不太清楚了，10月中旬，过完国庆节还是可以的

**Comment by nondanee** [comment]
看了下 [v0.20.1](https://github.com/nondanee/UnblockNeteaseMusic/releases/tag/v0.20.1) 是 10 月 19 号发的，QQ 音乐的 API 换了，不支持会员付费。
QQ 没法匹配到的话错误的概率比较大
