### ISSUE TITLE
为什么执行完启动命令关闭终端会失效？

### ISSUE THREAD

**Issue by guitarme** [nondanee/UnblockNeteaseMusic#299]
当执行node app.js -s -e https://music.163.com -p 5200:5201命令当时是可以播放，再关闭终端就好像结束了进程一样了

**Comment by XIU2** [comment]
因为这样执行只是前台运行，想要后台运行就这样执行：
`nohup node app.js -s -e https://music.163.com -p 5200:5201  > "/root/log.txt" 2>&1 &`
程序输出内容写入到 /root/log.txt 文件中。

**Comment by nondanee** [comment]
我解释不清楚为什么，不过有很多博文说这个，建议自己搜一下
https://www.google.com/search?q=为什么ssh一关闭，程序就不再运行
