### ISSUE TITLE
未来有计划修复灰色歌曲不能下载的问题吗

### ISSUE THREAD

**Issue by mao13820** [nondanee/UnblockNeteaseMusic#3]
hi，特别感谢你写的这个程序，很棒！谢谢！
我想问一下你未来有计划把灰色歌曲不能下载的问题修复吗，谢谢了

**Comment by nondanee** [comment]
这段时间会比较忙，暂时没有计划哈。
README里有说明，是因为其它平台音源不是mp3格式的问题

如果之后要做的话应该会先下载到本地用ffmpeg转码成mp3格式来实现，不过这样对环境的要求就比较高了

**Comment by mao13820** [comment]
好的，谢谢您了



毛皓天
AlexMao
 
发件人： Nzix
发送时间： 2018-07-01 23:56
收件人： nondanee/UnblockNeteaseMusic
抄送： mao13820; Author
主题： Re: [nondanee/UnblockNeteaseMusic] 未来有计划修复灰色歌曲不能下载的问题吗 (#3)
这段时间会比较忙，暂时没有计划哈。
README里有说明，是因为其它平台音源不是mp3格式的问题
如果之后要做的话应该会先下载到本地用ffmpeg转码成mp3格式来实现，不过这样对环境的要求就比较高了

**Comment by mao13820** [comment]
好的，谢谢您了

**Comment by nondanee** [comment]
已解决
