### ISSUE TITLE
请问，我在使用的过程中，经常会卡住，然后不能上网，需要手动ctrl c,跳过一下才能继续上网

### ISSUE THREAD

**Issue by liuliaocheng** [nondanee/UnblockNeteaseMusic#300]
就像这样：

MITM > music.163.com
MITM > music.163.com
MITM > music.163.com
MITM > p3.music.126.net
MITM > p3.music.126.net
MITM > p3.music.126.net
MITM > music.163.com
MITM > music.163.com
MITM > m7.music.126.net
TUNNEL > clients1.google.com:443
TUNNEL > clients1.google.com:443

遇到google就卡住，然后就需要手动ctrl c 跳过下,才能继续

我也没有访问google呀

**Comment by nondanee** [comment]
程序运行过程中不接受 stdin，并不存在阻塞等待用户交互，按 ctrl c 才能跳过的逻辑

按 ctrl c 会直接退出停止

Android 手机的 Play 框架，Chrome 浏览器自身可能都会访问 google
