### ISSUE TITLE
能否设置http代理密码？

### ISSUE THREAD

**Issue by harry890829** [nondanee/UnblockNeteaseMusic#301]
服务器上开放给外部的端口，总感觉怪怪的，这个功能可以设置么？

**Comment by nondanee** [comment]
不支持 https://github.com/nondanee/UnblockNeteaseMusic/issues/30#issuecomment-455782470
因为做不来

README 里也有写
> **~~或启用 Proxy Authentication `-t <name>:<password>` 设置代理用户名密码~~ (目前密码认证在 Windows 客户端设置和 macOS 系统设置都无法生效，请不要使用)**

替代方案: 
- 可以不开放外部端口
- 可以用严格模式
- 可以在前面加一个支持 proxy authentication 的 http 代理
- 可以在前面加一个 ss/ssr 等加密协议的 socks5/r2ray 代理
- (等等)
