### ISSUE TITLE
建议更改严格模式

### ISSUE THREAD

**Issue by a18214264850** [nondanee/UnblockNeteaseMusic#303]
建议严格模式增加放行qq啊，migu啊,xiami啊这几个源的地址，不然一旦 -s这几个也没法用的

**Comment by nondanee** [comment]
地址可能会变，加了不好维护，所以不会加的

README 里写得很清楚
> 使用严格模式 (此模式下仅放行网易云音乐所属域名的请求) `-s`  限制代理范围 (需使用 PAC 或 hosts)

请用 PAC 或 hosts，不要用全局代理

如果一定要代理这几个源的地址，加上 `-e http://music.163.com` 就可以
