### ISSUE TITLE
127.0.0.1该代理不可用

### ISSUE THREAD

**Issue by 1069605613** [nondanee/UnblockNeteaseMusic#305]

**Comment by nondanee** [comment]
https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-429514688
> 由于网易云 Windows 客户端的 Bug，测试代理会报错 "该代理不可使用"，实际并不影响
> 看到 `Server running @ http://0.0.0.0:8080` 之后出现如 `MITM > ...` 的请求日志即配置成功
