### ISSUE TITLE
切格瓦拉到此一游语录

### ISSUE THREAD

**Issue by ouzhrm** [nondanee/UnblockNeteaseMusic#306]
记者：为什么要白嫖naive music？
周某：没有钱了，肯定要做啊，不做没有好歌听。
记者：那你不会买个vip吗，有点零花钱的。
周某：付费是不可能付费的，这辈子不可能付费的。造音乐又不会造，就是白嫖这种东西，才能维持得了生活这样子。
记者：那你觉得你家好还是在基佬网好？
周某：肯定是进基佬网啊，上基佬网感觉像回家一样，在家里面一个人很无聊，
都没有友仔友女玩，进了里面去个个都是人才，说话又好听，我超喜欢在里面。

**Comment by nondanee** [comment]
既然决定留在网易云，充个会员还是应该的吧
