### ISSUE TITLE
音乐匹配建议

### ISSUE THREAD

**Issue by w2016561536** [nondanee/UnblockNeteaseMusic#308]
我是从unblockmusic pro 那边来的，那个仓库的所有者说你正在维护这个项目
希望unblockmusic pro在匹配音乐的时候可以去掉cover信息，因为(cover:xxx)这个真的是网易云特色，带这个cover匹配很容易出错

**Comment by XiaoWeiabc** [comment]
同感

**Comment by nondanee** [comment]
好的
