### ISSUE TITLE
-u 是否不支援 socks5 proxy?

### ISSUE THREAD

**Issue by rexx0520** [nondanee/UnblockNeteaseMusic#310]
如題
作為依賴庫調用時
`global.proxy = require('url').parse('socks5://xx.xx.xx.xx:xx') `可正常使用
`-u socks5://xx.xx.xx.xx:xx` 卻提示檢查 Proxy URL
應該是 app.js L25 的 regex 沒有包含 socks5 所致

**Comment by nondanee** [comment]
惊了！我写的代码没考虑 socks5 啊......

我觉得 global.proxy 应该也不支持 socks5 代理吧？

我猜可能是你的 socks5 代理兼容 http 代理

上游只支持 http 和 https 代理，而且没密码的那种

**Comment by rexx0520** [comment]
好的
看來我的 Proxy 確實相容 HTTP wwwww
