### ISSUE TITLE
资源不存在/网络错误

### ISSUE THREAD

**Issue by shugo-chara** [nondanee/UnblockNeteaseMusic#311]
最近好像版权的歌曲都听不了了，试了下jay之类的版权歌。用的中继+转发。
手机端提示资源不存在，电脑端是网络错误，无法播放。
已经更新到最新版。音源的话试着调整不同的源都不行。kuwo/joox/xiami/qq之类的都没办法听了。
![image](https://user-images.githubusercontent.com/20610965/68562084-882f7c00-048b-11ea-91bf-0e34a70b4f26.png)

然后极少数偶然会匹配到xiami的源，估计也是128的。绝大多数版权都无法播放了。
![image](https://user-images.githubusercontent.com/20610965/68561776-5d90f380-048a-11ea-8043-eb191717d286.png)

![image](https://user-images.githubusercontent.com/20610965/68561767-54a02200-048a-11ea-85c5-3b2aeb3272da.png)

更新：貌似qq源之前可以听的也不行了，有中继也不行。海外党彻底没有能用的源了吗= = 真是个悲伤的故事。

解决方法：
试了下cool里的niningxxx大大的db大喇叭，发现居然都可以播放，而且音质也基本都是最高- -。。之前他另一个unm pro用的也是这个项目，难道大喇叭换了？

**Comment by lyp741** [comment]
> 最近好像版权的歌曲都听不了了，试了下jay之类的版权歌。用的中继+转发。
> 手机端提示资源不存在，电脑端是网络错误，无法播放。
> 已经更新到最新版。音源的话试着调整不同的源都不行。kuwo/joox/xiami/qq之类的都没办法听了。
> ![image](https://user-images.githubusercontent.com/20610965/68562084-882f7c00-048b-11ea-91bf-0e34a70b4f26.png)
> 
> 然后极少数偶然会匹配到xiami的源，估计也是128的。绝大多数版权都无法播放了。
> ![image](https://user-images.githubusercontent.com/20610965/68561776-5d90f380-048a-11ea-8043-eb191717d286.png)
> 
> ![image](https://user-images.githubusercontent.com/20610965/68561767-54a02200-048a-11ea-85c5-3b2aeb3272da.png)
> 
> 更新：貌似qq源之前可以听的也不行了，有中继也不行。海外党彻底没有能用的源了吗= = 真是个悲伤的故事。
> 
> 解决方法：
> 试了下cool里的niningxxx大大的db大喇叭，发现居然都可以播放，而且音质也基本都是最高- -。。之前他另一个unm pro用的也是这个项目，难道大喇叭换了？

你好 请问你说的解决方法是什么？

**Comment by lollyhero** [comment]
ios 用什么源能听320K？我遇到的基本都是128  kuwo加qq

**Comment by nondanee** [comment]
@shugo-chara 
我这边没问题能正常听
启用了的 bridge 全部测了一遍也没有问题 (migu 还没加 insure，也是需要 bridge 的)

匹配到的 url 后会做一次可用性检查，可能在这个过程出错被 filter 掉了https://github.com/nondanee/UnblockNeteaseMusic/blob/b2eebf13f1ef20c81ced5d868c7be6a80f1ef80f/provider/match.js#L26
可以改成直接 `return urls` 试试看

joox 要求香港东南亚，其他的要求中国大陆，不知道你怎么一起 bridge 的==
海外可以用 youtube，去申请下 API KEY 就行了 #302 

大喇叭和本项目无关，用的 KuwoDes 
- java
https://github.com/Levi233/MusicPlayer/blob/master/app/src/main/java/com/chenhao/musicplayer/utils/crypt/KuwoDES.java
- python
https://github.com/XuShaohua/kwplayer/blob/master/kuwo/DES.py

或许可以转过来，比较麻烦

**Comment by nondanee** [comment]
@lollyhero 咪咕有，酷我可能会有，其他都没有

**Comment by lollyhero** [comment]
> 
> 
> @lollyhero 咪咕有，酷我可能会有，其他都没有 (不管任何平台都是)

谢谢解答，如果本身有320k资源的话 比如咪咕和酷我，下载的时候需要我有网易VIP才能下320吗，，因为我在UWP客户端切换320听都提示我需要VIP，且我用iPhone下载基本也都是128K的。
另外我iPhone把服务器切咪咕为默认源的时候，听的时候可以看到服务器解析了周杰伦的320K的音乐，但是下载就提示网络错误。

**Comment by lonelykid** [comment]
@nondanee 你好，我试了下youtube源，能匹配到，地址复制到浏览器能播放，但是音频长度为实际长度一倍，后面一半无声。在网易云播放的时候，进度条正常加载，但是一点播放，客户端就崩溃了，
``[1]    58301 floating point exception  ./NeteaseMusic``
服务器更新到最新版了，网易云是mac Version 1.5.10 (636)

**Comment by shugo-chara** [comment]
@nondanee 
@nondanee 
Thx～找到原因了。貌似是每次更新的文件路径不一致的原因。从第一次部署以后一直都是用git pull 项目地址来更新的，每次都提示已修改过的文件没有被更新，也没在意。
刚才看了下bt下好像初次部署时会克隆在root/UNM这个路径，但是之后更新就更新到/root的根目录里去了，所以我一直在用的都是第一次的版本。删掉所有旧版本重新克隆以下项目就正常了。

桥是一直在锅内的服务器上跑着没动过。音源现在去掉了joox。换成kuwo kugou youtube xiami migu qq了。这里面看哪个能用让它自己试吧，不过测试的大都是来自kuwo

youtube也配置了api，不过可能是平时几乎都是听的acg跟古典的缘故，没有出现用到它的地址，所以暂时不知道源是否正常。

ps.那个大喇叭虽然只有xp版，但获取到的音质都很强，也没有遇到匹配失败的。即便在锅外好像也没有受到影响，有点震惊。但UNM全平台还是舒心。

**Comment by nondanee** [comment]
@lollyhero 
不用在客户端切换音质，切换了不会有效果，匹配这边代码上就没有这个逻辑
下载不了可能因为别的问题......比如因为 MD5 校验

**Comment by nondanee** [comment]
@lonelykid
客户端这个我没办法啊，那你本地的 m4a 文件能用网易云播放吗？要不你给网易反馈下要求支持更多格式吧 😂
我测过现在的 Windows 客户端是可以播放 youtube 的 m4a 的，你把 macOS 客户端也更新到最新试试看呗，UWP 不知道我没试

嗯，是的
但是之前的公共中继也只有 qq vkey 获取，因为那时候 vkey 还可以共用，加上缓存后代价比较小
现在 vkey 策略变了，如果再开的话全部请求 track 压力会到我这里，我拒绝

是的，因为 vkey 限制严了，付费的歌 QQ 上都拿不到了，就用酷我源（已经有几个月了啊）

**Comment by nondanee** [comment]
@shugo-chara 
说过了，他用 KuwoDes，走酷我 mobi API，这个 API 应该是没限制的 (酷我本地破解会员很多的原因)
这个有空再看，可能就移植不过来，或者移植过来得加 dependency

“没有遇到匹配失败的” 这个我不清楚，可能有黑科技吧，没开源我也不知道

**Comment by lonelykid** [comment]
@nondanee 好像的确是mac客户端不支持m4a的问题。https://ytmp3.cc/，这个转mp3服务感觉完全没有下载转换的延迟，可能还是有直接获取mp3的api？

**Comment by nondanee** [comment]
@lonelykid 
you-get youtube-dl 这种都是没有 mp3 的
可能是有 api 但没有公开的资料我也没办法
