### ISSUE TITLE
window PC下资源不存在

### ISSUE THREAD

**Issue by runfi** [nondanee/UnblockNeteaseMusic#312]
通过 #22 配置 
---
```
通过该食用指南配置
在centos上pm2运行的代理
在window PC客户端 -> 工具 配置了相应的代理和端口
有挺大一部分歌曲无法正常播放
列表显示有资源（歌曲没有灰掉）
```
---
但是同一个代理在 ios上通过小火箭使用
大部分歌曲都能正常播放 比如周杰伦的 **一路向北**

**Comment by shugo-chara** [comment]
同环境同问题。
我这边是几乎全灭，所有无版权pc端网络错误，android端资源不存在。重新配置项目也不行，只能等 @nondanee 大大更新。

**Comment by nondanee** [comment]
不知道了，我没啥问题啊
本地起个服务看看？

**Comment by runfi** [comment]
> 不知道了，我没啥问题啊
> 本地起个服务看看？

本地服务并修改host没问题
问题仅出在windowPC使用代理情况下
 iphone使用同一个代理也很正常 T^T

**Comment by nondanee** [comment]
那可能是远程匹配到的 url 本地播放不了
比如远程被分配了 A 地区的 CDN 链接，本机在 B 地区无法访问 A 地区的 CDN server
可以加上 `-e` 让播放也走远程试试看

还有之前测过 Windows 客户端好像不支持 `-e https://music.163.com` 的自签证书
用 `-e http://music.163.com` 试试
