### ISSUE TITLE
Android 9 PAC 模式下无法直连 YouTube 和 Netflix 

### ISSUE THREAD

**Issue by SnowzTail** [nondanee/UnblockNeteaseMusic#313]
如题。

**Comment by nondanee** [comment]
为啥能直连？

**Comment by rexx0520** [comment]
個人建議
EdXposed/TaiChi + UnBlockMusic Pro

**Comment by SnowzTail** [comment]
> 個人建議
> EdXposed/TaiChi + UnBlockMusic Pro

谢谢

**Comment by SnowzTail** [comment]
> 为啥能直连？

不在国内...

**Comment by nondanee** [comment]
感觉这个应该没法解决

如果是 PAC 写法的问题
你可以浏览器打开 `http://<Server Name:PORT>/proxy.pac` 下载下来看一下
应该是符合标准的

其他的话可能是 ROM 对 PAC 支持的问题，还有客户端对 PAC 支持的问题
可以测一下 PAC 下使用浏览器是否能直连 youtube 和 netfix

**Comment by SnowzTail** [comment]
> 感觉这个应该没法解决
> 
> 如果是 PAC 写法的问题
> 你可以浏览器打开 `http://<Server Name:PORT>/proxy.pac` 下载下来看一下
> 应该是符合标准的
> 
> 其他的话可能是 ROM 对 PAC 支持的问题，还有客户端对 PAC 支持的问题
> 可以测一下 PAC 下使用浏览器是否能直连 youtube 和 netfix

看过 PAC 确实没有问题 浏览器也可以连接
应该是客户端支持问题 (除 Bilibili 外均无法正常访问)
感谢您的帮助
