### ISSUE TITLE
你好~Mac下有点问题想请教~设置完成后还是灰色的

### ISSUE THREAD

**Issue by chaotianjiao** [nondanee/UnblockNeteaseMusic#316]
我已经自己生成了证书并且已经替换了仓库里的两个文件，代理也设置了，但是搜索出来还是灰色的，想问下我哪里错了，下面是我的一些设置截图：
![image](https://user-images.githubusercontent.com/42534375/69324932-4e792500-0c84-11ea-8e53-e4374e79977d.png)
![image](https://user-images.githubusercontent.com/42534375/69324985-681a6c80-0c84-11ea-921c-24e5fa9f9875.png)
![image](https://user-images.githubusercontent.com/42534375/69325019-75cff200-0c84-11ea-8ea0-943f5cae2d70.png)
![image](https://user-images.githubusercontent.com/42534375/69325049-7f595a00-0c84-11ea-9a7b-2626b9afc0c8.png)
![image](https://user-images.githubusercontent.com/42534375/69325083-8c764900-0c84-11ea-8363-ef5ea5918cf8.png)
有些东西我不太懂，还请大佬多多指教下，我哪里没有设置对~

**Comment by nondanee** [comment]
PAC 地址是 http://127.0.0.1:8080/proxy.pac
加上端口号

**Comment by chaotianjiao** [comment]
![image](https://user-images.githubusercontent.com/42534375/69329757-a4ea6180-0c8c-11ea-8d80-5d4961c526a9.png)
![image](https://user-images.githubusercontent.com/42534375/69329778-b03d8d00-0c8c-11ea-9291-a807837dcf10.png)
![image](https://user-images.githubusercontent.com/42534375/69329843-c4818a00-0c8c-11ea-9d1a-3e755a8d2aa6.png)
好像还是不行~我是哪里没有配置对吗~，我确确实实是按照教程来的~

**Comment by chaotianjiao** [comment]
![image](https://user-images.githubusercontent.com/42534375/69330016-20e4a980-0c8d-11ea-9acc-1ba2bdfac5e2.png)
这个是Macd的版本信息，系统是catalina~

**Comment by nondanee** [comment]
@chaotianjiao 
emmm 我看错端口了==
![](https://user-images.githubusercontent.com/42534375/69329778-b03d8d00-0c8c-11ea-9291-a807837dcf10.png)
按这个来的话就是 8082，用你设的第一个端口

**Comment by chaotianjiao** [comment]
![Uploading image.png…]()

感谢大佬！膜拜大佬！再次感谢！笔芯ღ( ´･ᴗ･` )
