### ISSUE TITLE
最新版鲸鱼音效用不了

### ISSUE THREAD

**Issue by wendingp** [nondanee/UnblockNeteaseMusic#317]
![image](https://user-images.githubusercontent.com/17057603/69340956-92c7ed80-0ca3-11ea-8854-90735832de47.png)
如图

**Comment by nondanee** [comment]
用证书了吗？
已经用了的话就没办法

**Comment by wendingp** [comment]
> 用证书了吗？
> 已经用了的话就没办法

什么证书? 好像没用过

**Comment by nondanee** [comment]
参考 https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-477870013

**Comment by wendingp** [comment]
应该没有 你最新版没有这个问题吗

**Comment by lvhe19880210** [comment]
我这没问题

**Comment by nondanee** [comment]
@wendingp 
最新版没试过
建议用证书

**Comment by wendingp** [comment]
换成 node app.js -p 80:443 -f 59.111.181.60 这样可以了 thx!
