### ISSUE TITLE
如何在v2ray中实现爬墙和网易云音乐两不误？

### ISSUE THREAD

**Issue by a95788** [nondanee/UnblockNeteaseMusic#318]
并没有系统性学过Linux，还请高手高手高高手能够详细解读：）
我在国内服务器配置好后，但还没进行证书购买之类，如果要在iOS上同时实现：
开启爬墙的同时也能开启解锁云音乐的话应该要怎么实现？

我试过修改Hosts方法，能够做到，但是不知道怎么把用hosts去完成SSL的功能。

**Comment by nondanee** [comment]
#267 #148
v2ray 已经支持 http outbound 了，配置应该很简单
https://www.v2ray.com/chapter_02/protocols/http.html#outboundconfigurationobject

可以用自签证书，需要在设备上信任
有免费的 ssl 证书可以申请

通过改 hosts 使用需要 ssl 的话把 443 端口开起来就行了 `-p 80:443` https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-477870013
