### ISSUE TITLE
用4G直接连接路由器公网iP出现的问题

### ISSUE THREAD

**Issue by Koukotsukan** [nondanee/UnblockNeteaseMusic#321]
在4G或者其他WiFi环境下面用代理(4G的在APN里面添加代理)连路由器的公网iP的5200端口居然也可以连上，不只是能听灰色歌曲，最主要的是，还可以直接通过路由器iP上网，我无意中点开YouTube发现的，这个就有点可怕了，改配置文件里面的端口没有生效。（PS 不知道我用的是不是作者原装的，还是别人又改的版本，劳烦作者自己测试一下）

**Comment by Koukotsukan** [comment]
顺便，不确定是不是自己防火墙的问题，iPv6这个防火墙之前不能做端口转发我就直接关了。

**Comment by nondanee** [comment]
这个你得直接联系插件作者，插件不是我开发的
应该是开放端口的策略问题
https://github.com/maxlicheng/luci-app-unblockmusic
https://github.com/project-openwrt/luci-app-unblockneteasemusic

我这边要限制访问就用 `-s` 严格模式，仅限局域网访问可以 `-a` 设一个局域网 IP

**Comment by Koukotsukan** [comment]
收到，谢谢！

**Comment by 1715173329** [comment]
project-openwrt的插件默认是仅监听局域网的。。。
如果外网想要访问，就需要手动在进阶模式中开启。

maxlicheng的插件默认监听广域网，但是并没有调用iptables开放相关端口

所以如果你把防火墙设置为默认开放所有端口，那就没办法了

**Comment by Koukotsukan** [comment]
@1715173329  原来如此，但是在使用maxlicheng的插件时通过v6地址连接，即使关闭相关端口还是可以从公网连接进去，还是迷迷糊糊的，现在在用你的插件+openvpn解决公网问题

**Comment by 1715173329** [comment]
> @1715173329 原来如此，但是在使用maxlicheng的插件时通过v6地址连接，即使关闭相关端口还是可以从公网连接进去，还是迷迷糊糊的，现在在用你的插件+openvpn解决公网问题

v6当然，因为v6是有单独的防火墙规则，不清楚大雕的那个防火墙luci配置v6规则没有。。

**Comment by Koukotsukan** [comment]
@1715173329 所以很魔性哈哈
