### ISSUE TITLE
请教下咪咕改了sq可不可以实现解析m4a而不是flac

### ISSUE THREAD

**Issue by jsnjycwyz** [nondanee/UnblockNeteaseMusic#322]
按照提示把咪咕的js里sq取消了注释，可以获取到flac无损音源但是iOS的网易云好像不支持flac播放😂，抓了一下午咪咕的包发现如果识别为iOS客户端会请求同地址文件后缀名为.m4a，如果是安卓就是.flac，前面的路径貌似是一样的，想请教下可不可以在代码里把咪咕音源的请求改为m4a

**Comment by nondanee** [comment]
iOS 的网易云肯定能放 flac 啊，网易云自家的无损就是 flac 的

咪咕 m4a 不清楚
如果是最后只是后缀不一样的话 replace 一下就可以了
```js
playUrl.replace(/\.flac$/, '.m4a')
```
不过我试了下并不可以

**Comment by jsnjycwyz** [comment]
> iOS 的网易云肯定能放 flac 啊，网易云自家的无损就是 flac 的
> 
> 咪咕 m4a 不清楚
> 如果是最后只是后缀不一样的话 replace 一下就可以了
> 
> ```js
> playUrl.replace(/\.flac$/, '.m4a')
> ```
> 
> 不过我试了下并不可以
好的，谢谢，不知道为什么我的网易云Flac没办法播，可以下下来但是也播不了，我再研究下怎么把咪咕请求成m4a，相关文件就一个migu.js吧

**Comment by nondanee** [comment]
对
