### ISSUE TITLE
打包失败

### ISSUE THREAD

**Issue by qq517351411** [nondanee/UnblockNeteaseMusic#324]
F:\02_project\03_other\UnblockNeteaseMusic>npm run pkg

> @nondanee/unblockneteasemusic@0.22.3 pkg F:\02_project\03_other\UnblockNeteaseMusic
> pkg . --out-path=dist/

'pkg' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nondanee/unblockneteasemusic@0.22.3 pkg: `pkg . --out-path=dist/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @nondanee/unblockneteasemusic@0.22.3 pkg script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sunjiang\AppData\Roaming\npm-cache\_logs\2019-12-03T05_38_26_095Z-debug.log

咋回事

**Comment by nondanee** [comment]
```sh
npm install pkg
npm run pkg
```

**Comment by qq517351411** [comment]
先执行第一行 再执行第二行，我知道了，谢谢

**Comment by qq517351411** [comment]
F:\code\UnblockNeteaseMusic>npm install pkg
+ pkg@4.4.0
updated 1 package and audited 1114 packages in 30.405s
found 0 vulnerabilities


  fetched-v10.15.3-linux-x64   [                    ] 0%
> Error! getaddrinfo ENOENT github-production-release-asset-2e65be.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com:443
> Asset not found by direct link:nstall pkg
  {"tag":"v2.6","name":"uploaded-v2.6-node-v10.15.3-linux-x64"}
  fetched-v10.15.3-linux-x64   [                    ] 0%
> Error! getaddrinfo ENOENT github-production-release-asset-2e65be.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com:443
npm ERR! code ELIFECYCLE
npm ERR! errno 2eteaseMusic>npm run pkg
npm ERR! @nondanee/unblockneteasemusic@0.17.0 pkg: `pkg . --out-path=dist/`
npm ERR! Exit status 2easemusic@0.17.0 pkg F:\code\UnblockNeteaseMusic
npm ERR! -out-path=dist/
npm ERR! Failed at the @nondanee/unblockneteasemusic@0.17.0 pkg script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> Targets not specified. Assuming:
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sunjiang\AppData\Roaming\npm-cache\_logs\2019-12-03T09_33_08_655Z-debug.log

F:\code\UnblockNeteaseMusic>

**Comment by qq517351411** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'pkg' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prepkg', 'pkg', 'postpkg' ]
5 info lifecycle @nondanee/unblockneteasemusic@0.17.0~prepkg: @nondanee/unblockneteasemusic@0.17.0
6 info lifecycle @nondanee/unblockneteasemusic@0.17.0~pkg: @nondanee/unblockneteasemusic@0.17.0
7 verbose lifecycle @nondanee/unblockneteasemusic@0.17.0~pkg: unsafe-perm in lifecycle true
8 verbose lifecycle @nondanee/unblockneteasemusic@0.17.0~pkg: PATH: D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;F:\code\UnblockNeteaseMusic\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;D:\soft_java_list\TortoiseGit\bin;D:\soft_java_list\jdk1.8\bin;D:\soft_java_list\jdk1.8\jre\bin;D:\soft_java_list\apache-maven-3.6.0\bin;D:\soft_java_list\TortoiseSVN\bin;D:\Program Files\nodejs;C:\Users\sunjiang\AppData\Local\Microsoft\WindowsApps;
9 verbose lifecycle @nondanee/unblockneteasemusic@0.17.0~pkg: CWD: F:\code\UnblockNeteaseMusic
10 silly lifecycle @nondanee/unblockneteasemusic@0.17.0~pkg: Args: [ '/d /s /c', 'pkg . --out-path=dist/' ]
11 silly lifecycle @nondanee/unblockneteasemusic@0.17.0~pkg: Returned: code: 2  signal: null
12 info lifecycle @nondanee/unblockneteasemusic@0.17.0~pkg: Failed to exec pkg script
13 verbose stack Error: @nondanee/unblockneteasemusic@0.17.0 pkg: `pkg . --out-path=dist/`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid @nondanee/unblockneteasemusic@0.17.0
15 verbose cwd F:\code\UnblockNeteaseMusic
16 verbose Windows_NT 10.0.18362
17 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "pkg"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 2
22 error @nondanee/unblockneteasemusic@0.17.0 pkg: `pkg . --out-path=dist/`
22 error Exit status 2
23 error Failed at the @nondanee/unblockneteasemusic@0.17.0 pkg script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by qq517351411** [comment]
咋回事 我是win10

**Comment by nondanee** [comment]
`npm install pkg` 这一步挂了，后面 `npm run pkg` 也执行不了

> Error! getaddrinfo ENOENT github-production-release-asset-2e65be.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com:443

这个错是网络问题，你自己解决一下，可能要用梯子

**Comment by qq517351411** [comment]
npm install pkg 没有报错 执行成功了
F:\code\UnblockNeteaseMusic>npm install pkg
+ pkg@4.4.0
updated 1 package and audited 1114 packages in 30.456s
found 0 vulnerabilities


F:\code\UnblockNeteaseMusic>npm run pkg

> @nondanee/unblockneteasemusic@0.17.0 pkg F:\code\UnblockNeteaseMusic
> pkg . --out-path=dist/

> pkg@4.4.0
> Targets not specified. Assuming:
  node10-linux-x64, node10-macos-x64, node10-win-x64
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v10.15.3-linux-x64   [                    ] 0%
> Error! getaddrinfo ENOENT github-production-release-asset-2e65be.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com:443
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v10.15.3-linux-x64"}
  fetched-v10.15.3-linux-x64   [                    ] 0%
> Error! getaddrinfo ENOTFOUND api.github.com api.github.com:443
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @nondanee/unblockneteasemusic@0.17.0 pkg: `pkg . --out-path=dist/`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @nondanee/unblockneteasemusic@0.17.0 pkg script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sunjiang\AppData\Roaming\npm-cache\_logs\2019-12-05T01_57_54_747Z-debug.log

F:\code\UnblockNeteaseMusic>
 是网络的问题嘛？

**Comment by nondanee** [comment]
是呀
> Error! getaddrinfo ENOENT github-production-release-asset-2e65be.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com:443

getaddrinfo ENOENT 这错就是访问不到地址
打包过程要下载 node 二进制包的

**Comment by qq517351411** [comment]
F:\01_svn\07_git\UnblockNeteaseMusic>npm install pkg
npm ERR! code ERR_INVALID_ARG_TYPE
npm ERR! The "superCtor.prototype" property must be of type Object. Received type undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sunjiang\AppData\Roaming\npm-cache\_logs\2019-12-05T02_18_49_826Z-debug.log

F:\01_svn\07_git\UnblockNeteaseMusic>

我换了一台电脑 这个错是啥情况 node --version 都出来

**Comment by nondanee** [comment]
不知道
`npm install` 的错你自己查一下吧，跟项目本身没啥关系
