### ISSUE TITLE
配置后依旧不能播放周杰伦

### ISSUE THREAD

**Issue by esr2587758** [nondanee/UnblockNeteaseMusic#325]
软件版本：0.22.1
云音乐版本：2.2.0
Mac 系统： http、https、socks5 都已经配置代理。

从代理服务的日志能看到，都已经配置上了。 
但是周杰伦的歌曲依旧不能播放。 部分与周杰伦合作的歌曲可以: 比如布拉格广场...

不知道问题出在哪里...谢谢

**Comment by esr2587758** [comment]
开启代理后歌曲从灰色不可播放变成可点击播放，但是提示"播放失败，网络错误"

**Comment by nondanee** [comment]
有匹配日志吗？
是匹配到不能播放，还是就没有匹配到呢？
没匹配到的话先检查网络，海外不支持

**Comment by FunSeason** [comment]
我也是匹配到，日志有地址，单独网页点开可以播放，就是网易显示播放失败，网络错误。
我的是win10平台，用的是路由里的解锁网易灰色按钮的功能，其他平台（iOS，Mac，安卓）的客户端都能顺利播放，就是win10的播放不了，但歌曲不是灰色的。然后经过几个小时不断的查找原因和测试，终于win10的网易客户端也能顺利播放了。 我的解决方法是：同样先开启PAC，但网易客户端内的工具就不再自定义代理（不知为何，一开始测试时关闭客户端内的自定义代理，歌曲是会变灰，无法点击的。）然后，误打误撞乱试之下，把证书也给安装至可信任的根目录机构下，再测试，可以正常使用了。。。很神奇。。。记录一下，给遇到同样问题的后者参考一下，看看能不能帮助解决问题。
