### ISSUE TITLE
用的windows 代理方法，如何停掉，因为现在想访问网易云网页版了

### ISSUE THREAD

**Issue by ws1216152464** [nondanee/UnblockNeteaseMusic#326]
新手，勿喷。
用的windows 代理方法，如何停掉，因为现在想访问网易云网页版了，浏览网易云网页提示未授权
``
npx @nondanee/unblockneteasemusic -f 59.111.181.38 -p 2333
``
启动用的上面命令，关掉命令行后还是不行。
重启电脑也不行。
求大佬告知，停用这个用哪个命令。

**Comment by nondanee** [comment]
单单运行上面那个命令是不会设置代理的
代理应该是你自己设的，设成不使用代理就行了
改了 hosts 的话复原 hosts

**Comment by nondanee** [comment]
单单运行上面那个命令是不会设置代理的
代理应该是你自己设的，设成不使用代理就行了
改了 hosts 的话复原 hosts

**Comment by ws1216152464** [comment]
> 单单运行上面那个命令是不会设置代理的
> 代理应该是你自己设的，设成不使用代理就行了
> 改了 hosts 的话复原 hosts

我傻了，是hosts的问题  谢谢了。我混用了hosts和代理了
