### ISSUE TITLE
QQ 音乐加了cookie后还是不能无损吗

### ISSUE THREAD

**Issue by jsnjycwyz** [nondanee/UnblockNeteaseMusic#328]
更新版本后加了cookie发现好像都变成高码mp3了体积比不加cookie大一点，但还是没解析出无损的

**Comment by nondanee** [comment]
需要改一下这行
https://github.com/nondanee/UnblockNeteaseMusic/blob/b1b34db941553e600820b35791e7926ef462686f/provider/qq.js#L11

```js
const name = id => ['F000', '.flac'].join(id)
```

但是如果歌没有 flac 的话会失败吧，不确定

flac 前缀是 F000
ape 前缀是 A000
M800 是 320Kbps 的前缀
这个网上可以搜到

**Comment by jsnjycwyz** [comment]
谢谢，成功解析到flac了，ape貌似没有，不过还是那个问题，iOS上网易云不支持flac
Duplicate of #322 ，没办法了，只能播320Kbps的mp3了

**Comment by nondanee** [comment]
不太清楚
我查了下网上说网易云应该可以播放 flac 的啊
你抓包看一下听网易云自家的无损返回的是什么格式吧

**Comment by jsnjycwyz** [comment]
抓包看了下，他自己下载的就是flac，也能播放，但那些灰色歌曲从别的源来的flac就不能听，下下来也不能播放，放就提示播放失败。。搞不懂为什么，只能听或下320k的了

**Comment by lollyhero** [comment]
帅哥姐妹， QQ加cookie有木有教程？我也有QQ音乐会员

**Comment by nondanee** [comment]
@jsnjycwyz 
我看了下估计是我的问题，你 pull master 试一下吧

**Comment by jsnjycwyz** [comment]
> @jsnjycwyz
> 我看了下估计是我的问题，你 pull master 试一下吧

更新后可以了，flac也可以播放！感谢！
顺便问一下clash上的http代理是不是会有些问题，我在Mac上用clash哪怕开全局都没办法解锁。。

**Comment by jsnjycwyz** [comment]
> 帅哥姐妹， QQ加cookie有木有教程？我也有QQ音乐会员

https://github.com/nondanee/UnblockNeteaseMusic/blob/53bfeaf4364a423e34b913e54d52ce03d66bf67e/provider/qq.js#L8
这行填上你自己的cookie
'cookie': 'uin=    ; qm_keyst=     '

**Comment by lollyhero** [comment]
> > 帅哥姐妹， QQ加cookie有木有教程？我也有QQ音乐会员
> 
> https://github.com/nondanee/UnblockNeteaseMusic/blob/53bfeaf4364a423e34b913e54d52ce03d66bf67e/provider/qq.js#L8
> 
> 
> 这行填上你自己的cookie
> 'cookie': 'uin= ; qm_keyst= '

谢谢，这个我看懂了，只是我不晓得怎么得到自己的cookie，我在网上也没搜到，谢谢

**Comment by jsnjycwyz** [comment]
> > > 帅哥姐妹， QQ加cookie有木有教程？我也有QQ音乐会员
> > 
> > 
> > https://github.com/nondanee/UnblockNeteaseMusic/blob/53bfeaf4364a423e34b913e54d52ce03d66bf67e/provider/qq.js#L8
> > 
> > 这行填上你自己的cookie
> > 'cookie': 'uin= ; qm_keyst= '
> 
> 谢谢，这个我看懂了，只是我不晓得怎么得到自己的cookie，我在网上也没搜到，谢谢

我是用软件抓包的，在chrome登陆QQ音乐，用开发者工具 Network里找链接的header里应该有这两个值

**Comment by lollyhero** [comment]
> > > > 帅哥姐妹， QQ加cookie有木有教程？我也有QQ音乐会员
> > > 
> > > 
> > > https://github.com/nondanee/UnblockNeteaseMusic/blob/53bfeaf4364a423e34b913e54d52ce03d66bf67e/provider/qq.js#L8
> > > 
> > > 这行填上你自己的cookie
> > > 'cookie': 'uin= ; qm_keyst= '
> > 
> > 
> > 谢谢，这个我看懂了，只是我不晓得怎么得到自己的cookie，我在网上也没搜到，谢谢
> 
> 我是用软件抓包的，在chrome登陆QQ音乐，用开发者工具 Network里找链接的header里应该有这两个值

搞定~~~~~3qqqqqqqqq

**Comment by zack66** [comment]
![image](https://user-images.githubusercontent.com/16634459/70996485-d2042580-210d-11ea-81a5-57f8082ea4eb.png)
请问我这样添加cookie正确吗？为什么还是不能解析周杰伦的歌曲

**Comment by Paris0-0** [comment]
就是这么添加的

**Comment by zack66** [comment]
> 就是这么添加的

为什么我是豪华绿钻还是不能解析周杰伦的音乐（只测试了周杰伦的歌曲
指定的qq音源

**Comment by lollyhero** [comment]
> > 就是这么添加的
> 
> 为什么我是豪华绿钻还是不能解析周杰伦的音乐（只测试了周杰伦的歌曲
> 指定的qq音源

别的操作问题  什么平台 怎么配置的 你是不是绿钻都能听周杰伦 没影响
