### ISSUE TITLE
关于https转发，QQ音乐直链可直接播放

### ISSUE THREAD

**Issue by jsnjycwyz** [nondanee/UnblockNeteaseMusic#329]
由于我解析网易云的服务器使用的家里的设备，有公网ip但被封了80和443端口，无法申请证书，所以用了国外的一台vps做https endpoint，看到音频文件都是通过海外vps的域名转发过来的，速度很慢（vps节点比较垃圾），看到 #143 里的配置，把
https://github.com/nondanee/UnblockNeteaseMusic/blob/53bfeaf4364a423e34b913e54d52ce03d66bf67e/hook.js#L286
里直接改成了song.url，无版权的灰色播放下载都正常，音频文件都是别的源的直链，速度飙升，但是网易云的那些收费歌曲就不行了，解析到链接但播放失败（看配置指南照理说iOS不是应该没有https endpoint转发都不能播为什么这些无版权直接用直链也可以）
有没有办法区分开无版权和网易云收费歌曲，然后无版权用直链，收费歌曲走${global.endpoint}/package/ 转发

ps. iOS 安装证书把https://music.163.com 作转发的方法好像失效了，测试了下都是无法播放

**Comment by nondanee** [comment]
那一行的逻辑不设置 `-e` 就是 song.url，这个默认行为 [0.16.0](https://github.com/nondanee/UnblockNeteaseMusic/releases/tag/v0.16.0) 就有了，不太懂你为啥要改代码。。。

你的意思是无版权和收费歌曲客户端处理不一样吗？无版权的直连就可以，付费的必须转发？
应该不会吧，走同一个 api 的
也不太好区分，具体哪些字段来控制，在  enhance/player/url 里有没有返回我都不知道

失效应该不会，加了个 tg 群，大部分是 iOS 用户，我也没收到反馈说用不了
你把这行代码改了的话肯定就用不了 endpoint 了

**Comment by nondanee** [comment]
那一行的逻辑不设置 `-e` 就是 song.url，这个默认行为 [0.16.0](https://github.com/nondanee/UnblockNeteaseMusic/releases/tag/v0.16.0) 就有了，不太懂你为啥要改代码。。。

你的意思是无版权和收费歌曲客户端处理不一样吗？无版权的直连就可以，付费的必须转发？
应该不会吧，走同一个 api 的
也不太好区分，具体哪些字段来控制，在  enhance/player/url 里有没有返回我都不知道

失效应该不会，加了个 tg 群，大部分是 iOS 用户，我也没收到反馈说用不了
你把这行代码改了的话肯定就用不了 endpoint 了

**Comment by jsnjycwyz** [comment]
> 那一行的逻辑不设置 `-e` 就是 song.url，这个默认行为 [0.16.0](https://github.com/nondanee/UnblockNeteaseMusic/releases/tag/v0.16.0) 就有了，不太懂你为啥要改代码。。。
> 
> 你的意思是无版权和收费歌曲客户端处理不一样吗？无版权的直连就可以，付费的必须转发？
> 应该不会吧，走同一个 api 的
> 也不太好区分，具体哪些字段来控制，在 enhance/player/url 里有没有返回我都不知道
> 
> 失效应该不会，加了个 tg 群，大部分是 iOS 用户，我也没收到反馈说用不了
> 你把这行代码改了的话肯定就用不了 endpoint 了

是的，改成song.url就相当于没有-e不走https转发了，这时候无版权依然可以播放的，直接获取直链，但付费听的就不行

可能是还有缓存，我这测试iPhone和iPad从下午开始都不行了

**Comment by jsnjycwyz** [comment]
进一步测试发现了只有QQ音乐的直链可以直接播放，其它的都不行，网易云的付费基本QQ音乐都搜不到用的其它的migu kuwo之类的所以就不能直接播放了。

**Comment by jsnjycwyz** [comment]
直接加了个简单粗暴的判断，QQ音源就直链，其他走https转发😂
`if (song.url.indexOf('qq') > -1){
					item.url = song.url;
				}else{
					item.url = global.endpoint ? `${global.endpoint}/package/${crypto.base64.encode(song.url)}/${item.id}.${item.type}` : song.url
				}`

我又重装了一遍网易云，iOS证书的应该已经失效了，没什么人反应一个是有缓存，还有就是默认QQ 音源无需证书可以直接播放下载，如果qq音源没有匹到音源就会失效。

**Comment by nondanee** [comment]
因为 qq 音乐的文件链接支持 https；酷我酷狗咪咕都是 http，改成 https 都无法访问

**Comment by nondanee** [comment]
那我不清楚，我也没有 iOS 设备

**Comment by jsnjycwyz** [comment]
原来如此，难怪。
