### ISSUE TITLE
歌单只能支持500首歌

### ISSUE THREAD

**Issue by JasonKhew96** [nondanee/UnblockNeteaseMusic#33]
代理
![image](https://user-images.githubusercontent.com/29531167/50736005-23175400-11f2-11e9-930d-cc058954e2b7.png)
无代理
![image](https://user-images.githubusercontent.com/29531167/50735999-0549ef00-11f2-11e9-981d-32c1f245d925.png)

OS: Win 10

**Comment by nondanee** [comment]
@JasonKhew96 
感谢反馈！
我测了下感觉是网易云自己的问题
不知道你那边是怎么“激活”载入 500 之后的歌曲的

我测试了下，使用代理和不使用都是这样的结果（版本 2.5.1）
- 从侧边栏进入歌单后仅仅是上下滑动，始终只有 500 首
- 切换到歌单评论再回来查看歌曲，下滑到底部才会加载更多
- 点击 “音乐标题”，“歌手”，”专辑“，”时长“ 进行排序后，下滑到底部也可以加载更多

请再次测试下谢谢

**Comment by JasonKhew96** [comment]
@nondanee 
进行排序后，剩下的加载出来了
不过使用代理加载非常慢（版本2.5.2）

**Comment by nondanee** [comment]
@JasonKhew96 
可是我更新到 2.5.2 依旧是 500 首一页啊，怎么滑都没不会变多，必须点一下别的再点回来
歌单 id 能不能发我一下，我试一下

**Comment by JasonKhew96** [comment]
@nondanee 
`http://music.163.com/playlist?id=2166009452`

**Comment by nondanee** [comment]
@JasonKhew96 
😂 我试了没问题啊，不卡

**Comment by JasonKhew96** [comment]
@nondanee 
行吧，每次要点击排序列表才能加载全部🙃

**Comment by nondanee** [comment]
@JasonKhew96 
点评论也行的啊！
但我觉得真不是我的锅 😭
我用 SS 的代理试了下也是一样的效果

**Comment by JasonKhew96** [comment]
😭确认过了，确实是网易云的锅，气死了
