### ISSUE TITLE
如何设置前置代理

### ISSUE THREAD

**Issue by liuminglm** [nondanee/UnblockNeteaseMusic#330]
服务器是海外服务器,但是有一个国内的http代理(127.0.0.1:3838 ),我尝试使用如下设置:

使用参数u:
docker run  -u http://127.0.0.1:3838 nondanee/unblockneteasemusic
提示:
docker: Error response from daemon: unable to find user http: no matching entries in passwd file.

使用参数e:
docker run  -e http://127.0.0.1:3838 nondanee/unblockneteasemusic

可以正常使用,客户端灰色也会变正常,但是会提示:"播放失败 歌曲不存在"

不知道是不是我设置的前置代理有错误?

**Comment by nondanee** [comment]
是的

docker 的启动 options 是写在 image name 前，image 自己启动的参数写在后面
参考 https://docs.docker.com/engine/reference/run/

```
docker run [options] nondanee/unblockneteasemusic -u http://<正确的IP>:3838
```

**Comment by liuminglm** [comment]
> 是的
> 
> docker 的启动 options 是写在 image name 前，image 自己启动的参数写在后面
> 参考 https://docs.docker.com/engine/reference/run/
> 
> ```
> docker run [options] nondanee/unblockneteasemusic -u http://<正确的IP>:3838
> ```

使用新的命令:
docker run  nondanee/unblockneteasemusic -u http://127.0.0.1:3838
报错:
{ Error: connect ECONNREFUSED 127.0.0.1:3838
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3838 }

测试http 代理:
curl --connect-timeout 2 -x 127.0.0.1:3838 http://www.baidu.com
显示:"<!DOCTYPE html>
<html> <head><meta http-equiv=content-type.........(后面省略)"

所以代理应该没问题

请问我的设置还是有问题吗?

**Comment by nondanee** [comment]
应该是这个问题，你看看
https://jingsam.github.io/2018/10/16/host-in-docker.html
