### ISSUE TITLE
匹配错误音乐

### ISSUE THREAD

**Issue by icharle** [nondanee/UnblockNeteaseMusic#331]
针对匹配错误音乐是否可以采用白名单的方式维护，将匹配错误的音乐的歌名以及对应的正确的链接放在一个文件中，请求时候先判断是否为这一类歌。

**Comment by nondanee** [comment]
不考虑
各家的搜索算法肯定每天都在学习优化，版权也有周期
白名单维护费精力，冗余没人检查，做到后面就是一张超级大的人工 map 表

需要频繁更新就不会放到仓库里面做，通过请求下发的话需要基础设施 (协作/更新/维护)，你想做可以做一套
