### ISSUE TITLE
安卓自动配置proxy.pac后 微信公众号图片无法正常加载

### ISSUE THREAD

**Issue by Uzibird** [nondanee/UnblockNeteaseMusic#332]
使用自动配置后，微信公众号文章文章内的缩略图永远在转圈，点进去后可以看大图。
网易云客户端的个人主页一直加载失败。

请问，您遇到了这样的问题了吗? （应该是pac规则问题吧?）

非常感谢。

**Comment by nondanee** [comment]
个人主页无法加载见 https://github.com/nondanee/UnblockNeteaseMusic/issues/30#issuecomment-472538422

使用手动代理 (全局) 是否有问题？
如果觉得 PAC 规则有问题可以把 PAC 文件下载下来打开看看有哪里不对

**Comment by Uzibird** [comment]
你好，使用手动代理微信图片加载是正常的。您使用的时候是一直挂着全局的吗？（我是机器在家里，人在外地所以用pac了，机器上还有别的服务给家里人用）

我用的docker，新手，不知道在哪里找pac文件。。。。。

非常感谢。

**Comment by nondanee** [comment]
在浏览器里打开 PAC 地址就可以下载

**Comment by Uzibird** [comment]
但是在docker里我要在哪里修改它呢？

**Comment by nondanee** [comment]
是动态生成的，不是一个文件
https://github.com/nondanee/UnblockNeteaseMusic/blob/53bfeaf4364a423e34b913e54d52ce03d66bf67e/server.js#L13-L24
需要修改 server.js 文件，可以用 `-v` (https://docs.docker.com/storage/volumes/) 映射一个本地文件，或者 attach 到 container 里修改

本项目对环境没什么要求，可以直接在宿主调试，不一定要使用 docker

**Comment by Uzibird** [comment]
🌚我抓包看了下，微信图片的地址并没有和规则里有重合。触及到我的知识盲区了。

感谢大佬。。。
我回头学习下这方面知识再看看吧。。。

**Comment by nondanee** [comment]
我试了下，PAC 下确实公众号文章配图一直转圈，用手动代理就没问题
可能和这个问题差不多吧 https://github.com/nondanee/UnblockNeteaseMusic/issues/313#issuecomment-554658527 ，猜测是微信自己的问题
