### ISSUE TITLE
音效不能连接

### ISSUE THREAD

**Issue by JrantKing** [nondanee/UnblockNeteaseMusic#335]
![QQ截图20191209145636](https://user-images.githubusercontent.com/16501400/70414242-7e9e3180-1a94-11ea-81e7-4e1727aab9b4.png)
![QQ截图20191209145730](https://user-images.githubusercontent.com/16501400/70414244-7e9e3180-1a94-11ea-865c-3793356173af.png)

**Comment by nondanee** [comment]
用证书就可以了，参考 https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-477870013
