### ISSUE TITLE
最新版 Windows 客户端失效

### ISSUE THREAD

**Issue by steven7851** [nondanee/UnblockNeteaseMusic#336]
Windows 网易云音乐 版本 2.7.0 (Build:198230)
貌似这版才出现的问题，退回 2.6.0 (Build:198181) 后可正常播放

付费歌曲: 好想爱这个世界啊 - 华晨宇
![snipaste_20191210_121507](https://user-images.githubusercontent.com/6252238/70494572-b9f93880-1b46-11ea-8403-dca2cf38e8d6.png)

无版权歌曲会变灰色且也无法播放
![snipaste_20191210_125143](https://user-images.githubusercontent.com/6252238/70496811-fda27100-1b4b-11ea-8ee6-5615fad4392b.png)

**Comment by jsnjycwyz** [comment]
一样，iOS和Mac上如果是安装证书使用的，所有QQ音乐源里没有的歌都没法播放

**Comment by nondanee** [comment]
可是我没问题啊 (虽然肯定是匹配错的 ==

![image](https://user-images.githubusercontent.com/26399680/70541895-cb702e00-1ba2-11ea-8752-636b723cdd5c.png)

是改 hosts 用的吗？改 hosts 的话可能会用不了，现在桌面端也会直连 IP 了，见 https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-554661621

**Comment by steven7851** [comment]
嗯是用 hosts 没错，只好改用 proxy 了😕
