### ISSUE TITLE
Android下iptables屏蔽IP求助

### ISSUE THREAD

**Issue by obcsl** [nondanee/UnblockNeteaseMusic#337]
**1. 遇到问题：**
本来想用Android改Host + iptables屏蔽IP的方法达成无感知。但是屏蔽了以下四部分IP和music.httpdns.c.163.com ，歌单该灰的还是灰：

- [a]  ReadMe里面提到的https://jixun.moe/post/netease-android-hosts-bypass/ ，即223.252.199.10。

- [b]  curl music.httpdns.c.163.com/d --data music.163.com 跑出来的，即["59.111.181.60","223.252.199.66","223.252.199.67","59.111.160.195","59.111.160.197","59.111.181.35","59.111.181.38","193.112.159.225","118.24.63.156"]

- [c]   issue里面有位老兄逆向以后的内置IP，即["59.111.21.13", "59.111.179.213", "59.111.21.14", "59.111.179.214", "1.81.5.114", "1.81.5.115", "110.185.122.114", "110.185.122.115", "14.18.239.11", "14.18.239.12", "223.202.198.132", "223.202.198.134" ]

- [d]   Packet Capture 抓包以后的部分IP，这里就不仔细列出来了，每次屏蔽完一堆又跳出来新的一堆，累死在WY的CDN中。可能是我的分析包的方法不对lol。

**2.背景参考**

- 首先，我是部署在国内服务器端的（百毒云），项目不用docker，直接node裸奔，用了自签证书，-s限制模式。

- 并且测试最新的Windows客户端和Mac客户端均无问题，如下log。
![image](https://user-images.githubusercontent.com/36759408/70551426-79cf9f80-1bb2-11ea-87c9-f9406403431e.png)

- 但是从log来看Android的死活代理不到music.163.com和interface.music.163.com，能看到的就只有apm3.music.163.com 和 clientlog3.music.163.com，如图：
![image](https://user-images.githubusercontent.com/36759408/70551770-2873e000-1bb3-11ea-9244-9e8455e5768c.png)

- Android的版本是国内的6.4.2，从Packet Capture 抓包来看，Iptables是生效的，封完一堆IP以后不会再出现，但是立刻又会冒出一大堆其他的，初步判断可能是IP没有封完，但是也不太确定有无其他问题。

**3.抱大腿宣言**
本来对这块不是很熟，研究了几天实在是木有时间耗下去了，只能厚颜求抱大腿。恳请大佬指点指点^_^，看看是否我做的有问题？

**Comment by obcsl** [comment]
ps:我的host只设了music.163.com和interface.music.163.com

**Comment by nondanee** [comment]
https://github.com/nondanee/UnblockNeteaseMusic/blob/53bfeaf4364a423e34b913e54d52ce03d66bf67e/hook.js#L26-L30
那就把这些都写到 hosts 里试试看

**Comment by obcsl** [comment]
现在成功了。感谢大佬^_^。
![image](https://user-images.githubusercontent.com/36759408/70582018-0d759000-1bf4-11ea-8915-503c083fcf7c.png)

一开始的时候只是加了hook.js的interface3和apm还是不行，但是服务端log可以看到代理了interface3.music.163.com。
重新抓包以后再屏蔽一个IP（59.111.181.40），成功了。

**Comment by Fanx-jk** [comment]
> 现在成功了。感谢大佬^_^。
> ![image](https://user-images.githubusercontent.com/36759408/70582018-0d759000-1bf4-11ea-8915-503c083fcf7c.png)
> 
> ~一开始的时候只是加了hook.js的interface3和apm还是不行，但是服务端log可以看到代理了interface3.music.163.com。 重新抓包以后再屏蔽一个IP（59.111.181.40），成功了。~
> 事实证明后面屏蔽的IP并无卵用，只要hosts添加那几个domain就可以了。

大佬我想问一下你是怎么实现的
我的 HOSTS 是这样的:
```
127.0.0.1 music.httpdns.c.163.com # 这一条加和不加都一样没效果
x.x.x.x music.163.com
x.x.x.x interface.music.163.com
x.x.x.x interface3.music.163.com
x.x.x.x apm.music.163.com
x.x.x.x apm3.music.163.com
```

然后 Android 上也装了证书
客户端还是一样，该灰的还是灰
服务端 log:
```
MITM > interface3.music.163.com 
MITM > interface3.music.163.com 
MITM > interface3.music.163.com 
MITM > interface3.music.163.com 
MITM > interface3.music.163.com 
MITM > interface3.music.163.com 
MITM > interface3.music.163.com 
MITM > interface3.music.163.com 
MITM > interface3.music.163.com 
MITM > interface3.music.163.com 
MITM > interface3.music.163.com 
MITM > interface3.music.163.com 
MITM > interface3.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 

```

**Comment by Fanx-jk** [comment]
搞定了，最后是通过iptables实现的
 看了下 @Flysky12138 大佬的[代码](https://github.com/Flysky12138/UnblockNeteaseMusic-Android/blob/1d253386fd6675a89cdc60d17d84d6272fc7e811/app/src/main/assets/shell/proxy.sh)
自己写了一个转发，由于不想在手机上跑服务，就用了iptables
```
re=$(grep -m1 -i "com.netease.cloudmusic" /data/system/packages.list | cut -d' ' -f2)
iptables -t nat -A OUTPUT -p tcp -m owner --uid-owner $re -m tcp --dport 80 -j DNAT --to server:port
iptables -t nat -A OUTPUT -p tcp -m owner --uid-owner $re -m tcp --dport 443 -j DNAT --to server:port
```
正常使用，顺手写了个 Magisk 模块，做到无感知使用
