### ISSUE TITLE
Mac Catalina｜网易云2.3.1（828）｜方法① (代理模式)｜Proxifier｜摸索教程分享

### ISSUE THREAD

**Issue by shuiRong** [nondanee/UnblockNeteaseMusic#338]
安装Node.js、下载项目、[自签证书](https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-477870013)不介绍，看[使用指南](https://github.com/nondanee/UnblockNeteaseMusic/issues/22)。

Proxifier部分和[这个](https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-436505087)几乎一样，可以参考这个。
**但有区别！** 因为我完全按照 @gqbre 的办法却没有搞定，或许从那之后又出现了新状况。

**区别如下：**
1. 启动命令不同：`node app.js `（这里和作者 方法1 那里说的一样，不加任何参数）
2. 你新建的名叫NeteaseMusic 的 Proxifier Rule里的 Applications这一项，不用 @gqbre 提供的，你点击 Applications边框的右下角，然后选择网易云音乐，然后Yes，会添加进来一堆。（理由是可能因为系统版本和网易云版本的不同，这里面的东西会不同）

**几个关键信息**：
1. 不需要在系统网络设置的代理设置那边添加 `....proxy.pac`，因为上面Proxifier就是在做这件事。
2. 不需要修改DNS。因为我们是方法1，而不是方法2。

最后，赞美作者！

**Comment by nondanee** [comment]
咋关了啊 😅

**Comment by shuiRong** [comment]
@nondanee 因为我看你开着的项目都是Wiki类的，所以不想打乱你的队形。就关了。

**Comment by shuiRong** [comment]
补充信息：很奇怪，刚才失效了几分钟。即：我是用Proxifier转发请求时，网易云那边网络都打不开。Proxifier显示：
![image](https://user-images.githubusercontent.com/16076993/70763053-ba374500-1d8d-11ea-88d8-e6a33f1a65e7.png)
然后我不用Proxifier转发，而是按照作者教程说的在网络设置那边添加pac，就没问题。正在纳闷呢，Proxifier这边恢复正常了。
特此记录。

**Comment by nondanee** [comment]
@shuiRong 
代理修改响应并没有设置 statusCode 为 400 的逻辑，应该就是网易云服务器给你返回了 400，你的账号被风控了一小下
可能是 hook.js 里 X-Real-IP 的问题，你可以改成任何一个国内 IP

**Comment by shuiRong** [comment]
X-Real-IP换过了，无效。
我很好奇为什么经过Proxifier就不行，不经过是可以的。我想知道经过Proxifier的请求详情，但Charles没抓到网易云客户端的包。有建议吗？

**Comment by gqbre** [comment]
@shuiRong Proxifier 选中网易云音乐后自动添加其他程序的 Proxifier 新增的 feature，只需要添加 NeteaseMusic;com.apple.WebKit.Networking 这两个就行，前述的自动添加并没有包含 com.apple.WebKit.Networking 这个程序

**Comment by shuiRong** [comment]
@gqbre 谢谢提醒。我改了下。问题依旧...

**Comment by shuiRong** [comment]
问题解决了...很迷
和上面不同的是：
1. Proxifier设置Proxy那边，换了个端口，换成了8082；
2. 启动程序的命令换成了：`node app.js -p 8082:8081`

P.S. 我换成8082端口的原因是，8080端口访问不到。我在浏览器打开`http://127.0.0.1:8080/proxy.pac`时，被定向成了`http://cn.bing.com/proxy.pac`。奇怪的问题。我排查过hosts和Proxifier，还有网络设置那边，搞不懂为什么。因此干脆换个端口，然后正常。

**Comment by gqbre** [comment]
今日测试网易云音乐 Mac 客户端更新
Proxifier 目标代理域名更新为：*.music.163.com;*.music.126.net;*.netease.com;
https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-436505087

**Comment by lioliy** [comment]
@shuiRong 
开机自启的方法：使用[LaunchAgents](https://developer.apple.com/library/archive/technotes/tn2083/_index.html)
以 `npx @nondanee/unblockneteasemusic -p 8080 -e http://music.163.com` 为例

配置：

- 创建文件

  ​	位置：/Users/[用户名]/Library/LaunchAgents/

  ​	文件名：com.nondanee.unblockneteasemusic.plist

  ​	内容如下：

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>com.nondanee.unblockneteasemusic</string>
	<key>ProgramArguments</key>
	<array>
		<string>/usr/local/bin/npx</string>
		<string>@nondanee/unblockneteasemusic</string>
		<string>-p</string>
		<string>8080:50000</string>
		<string>-e</string>
		<string>http://music.163.com</string>
	</array>
	<key>EnvironmentVariables</key>
	<dict>
		<key>PATH</key>
		<string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
	</dict>
	<key>RunAtLoad</key>
	<true/>
	<key>KeepAlive</key>
	<true/>
</dict>
</plist>

```

- 运行命令
  `launchctl load /Users/[用户名]/Library/LaunchAgents/com.nondanee.unblockneteasemusic.plist`

**Comment by wx-11** [comment]
https://linshuirong.cn/blog/2019/12/12/%E8%A7%A3%E9%94%81%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%E6%AD%8C%E5%8D%95%E7%89%88%E6%9D%83%E5%9C%B0%E5%8C%BA%E9%99%90%E5%88%B6%EF%BD%9C%E4%BD%BF%E7%94%A8Proxifier%EF%BD%9C%E5%BC%80%E6%9C%BA%E8%87%AA%E5%90%AF%E5%8A%A8Shell/

发现一样 原来是你的博客
