### ISSUE TITLE
## 自签证书

### ISSUE THREAD

**Issue by jsnjycwyz** [nondanee/UnblockNeteaseMusic#339]
## 自签证书
macOS 客户端 700 以上版本无法通过握手后返回空数据的方式降级 https 请求 (如有别的降级方式，请告知我)，Linux 客户端 1.2 以上版本有同样问题，其它平台暂时还未遇到

可以直接换用旧版本
http://d1.music.126.net/dmusic/NeteaseMusic_2.0.0_700_web.dmg
http://d1.music.126.net/dmusic/NeteaseMusic_2.0.0_690_web.dmg
http://d1.music.126.net/dmusic/NeteaseMusic_1.5.10_636_web.dmg

新版通过自签证书直接代理 https 流量能够解决此问题 (同时支持 hosts 模式和代理模式)
可以直接使用仓库里的证书，若需自己签发证书，步骤如下 (需要用到 OpenSSL)
**仓库未公开 CA 私钥，若担心作者作恶，请自行创建 CA 签发证书，感谢 @ITJesse 提醒** #166 

```
# 生成 CA 私钥
openssl genrsa -out ca.key 2048

# 生成 CA 证书 ("YOURNAME" 处填上你自己的名字)
openssl req -x509 -new -nodes -key ca.key -sha256 -days 1825 -out ca.crt -subj "/C=CN/CN=UnblockNeteaseMusic Root CA/O=YOURNAME"

# 生成服务器私钥
openssl genrsa -out server.key 2048

# 生成证书签发请求
openssl req -new -sha256 -key server.key -out server.csr -subj "/C=CN/L=Hangzhou/O=NetEase (Hangzhou) Network Co., Ltd/OU=IT Dept./CN=*.music.163.com"

# 使用 CA 签发服务器证书
openssl x509 -req -extfile <(printf "subjectAltName=DNS:music.163.com,DNS:*.music.163.com") -days 365 -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out server.crt
```

上述步骤完成后

将服务器私钥 (server.key) 和服务器证书 (server.crt) 拷贝到仓库中覆盖原有文件 (若使用 docker，可通过添加 `-v server.crt:/usr/src/app/server.crt -v server.key:/usr/src/app/server.key` 参数映射本地路径覆盖原有文件)，再将 CA 证书 (ca.crt) 安装到系统；如果不自行签发，直接安装仓库里的 CA 证书 ([ca.crt](https://raw.githubusercontent.com/nondanee/UnblockNeteaseMusic/master/ca.crt)) 即可

**CA 证书需要手动配置为信任，切记**

之后在启动命令中增加 https 监听端口，格式为 `-p <http port>:<https port>`，hosts 模式应为 `80:443`，代理模式随意，两个端口号不同即可

自签证书下网易云网页版是可用的，但是阻止变灰无效，因为网页内嵌加密，需要[脚本](https://greasyfork.org/zh-CN/scripts/382285-neteasemusic-ui-unlocker)配合

_Originally posted by @nondanee in https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-477870013_

**Comment by DOTA2mm** [comment]
> 之后在启动命令中增加 https 监听端口，格式为 -p <http port>:<https port>
我在配置了证书后， docker 中加了 -p 8080:8081, 同时主机端口映射为 10086:80800, Mac 和 iPhone中歌单不变灰了，但是播放提示网络问题。请问可能是哪里有问题？

播放失败的docker log:
```
http://dl.stream.qqmusic.qq.com/M500001PLl3C4gPSCI.mp3?vkey=F80F3FA1565D0CBB8E26F2B7F1232E9B000D6C87FB7B5129BDD0895BBF61C42531F39A989ED15ED5FB104663CA39355F961A764ABC2B818A&uin=0&fromtag=8&guid=7332953645
```

**Comment by nondanee** [comment]
@DOTA2mm 
Mac 中应该不会有问题的，有问题的应该是 iPhone 吧？

给 iPhone 使用需要加上 `-e http://music.163.com` 或 `-e https://music.163.com`，自测一下哪个能用就用哪个 ( #65 "方法一：使用证书" 里有提示 )

**Comment by DOTA2mm** [comment]
```
docker run -d -p 12306:8080 -v /home/pi/SourceCode/unblockneteasemusic/server.crt:/usr/src/app/server.crt -v /home/pi/SourceCode/unblockneteasemusic/server.key:/usr/src/app/server.key  --name neteasemusic nondanee/unblockneteasemusic -p 8080:8081 -e https://music.163.com
```
是的，目前这样iPhone不行，晚上我再试试Mac

**Comment by nondanee** [comment]
@DOTA2mm 
用 http://music.163.com 可以吗？

你直接回复在 original post #48 里就好了，这个 issue 应该是误建的，我到时候 delete 了

**Comment by DOTA2mm** [comment]
也不行。都是提示播放失败。

**Comment by blvae** [comment]
自建证书的最后一步，显示系统找不到指定的文件

**Comment by nondanee** [comment]
@blvae 
完整的报错信息贴一下
我试了在 linux 上试了没问题，macOS 上也应该也没问题的

**Comment by EromangaMe** [comment]
直接设置系统代理也可以

**Comment by nondanee** [comment]
@EromangaMe 
请回复到 #48 谢谢

**Comment by nondanee** [comment]
@blvae 
还有问题麻烦新建 issue，这个 lock 了
