### ISSUE TITLE
好像不行了哎

### ISSUE THREAD

**Issue by ymmshi** [nondanee/UnblockNeteaseMusic#34]
版权歌曲虽然不变灰了,但是还是无法播放,之前一直可以的 @nondanee

**Comment by nondanee** [comment]
看到了，是虾米源炸了

**Comment by ymmshi** [comment]
> 看到了，是虾米源炸了

请问如何指定源呢

**Comment by nondanee** [comment]
@ymmshi 
`-o qq,xiami,baidu`
不过现在 qq 源也炸了...

**Comment by nondanee** [comment]
已修复 https://github.com/nondanee/UnblockNeteaseMusic/commit/3443782c5618016ee872637ac04c13d25fa1e6fc https://github.com/nondanee/UnblockNeteaseMusic/commit/b4a38654f567170ece8032a2daf239cf85d04375

**Comment by rosyriver** [comment]
又出现这个问题了...

**Comment by nondanee** [comment]
@rosyriver 等你下课在 QQ 要付费

**Comment by rosyriver** [comment]
@nondanee  啊..这样明白了!不好意思! 感谢分享..

**Comment by nondanee** [comment]
@rosyriver 我看了下确实不行了，不是付费的问题，只能音质了
