### ISSUE TITLE
Mac网易云 2.3.1(830)，iPad网易云HD(1.7.0)均失效

### ISSUE THREAD

**Issue by Paris0-0** [nondanee/UnblockNeteaseMusic#340]
Mac网易云昨天自动偷偷升级830了，一打开歌曲就开始狂跳，一个都放不了，全是无法播放，iPad网易云HD 昨天诈尸更新1.7.0，灰色的都没法变黑。。
用的是自签证书方法，Mac和iPad用iPhone那种https endpoint好像无效

**Comment by shuiRong** [comment]
提供个828（我正在用）版本[下载地址](http://www.pc6.com/mac/113934.html)

**Comment by jsnjycwyz** [comment]
对的之前828是可以的，不过好像一些付费的听不了，比如华晨宇的好像爱这个世界，还是提示网络错误

**Comment by gqbre** [comment]
Mac 刚更新到 2.3.2（832），一切正常

**Comment by jsnjycwyz** [comment]
不知道是不是因为我实在远程服务器上运行的原因，安装证书方法总是有各种各样的毛病。。

**Comment by shuiRong** [comment]
上面两位用Mac的同学，遇到个[问题](https://github.com/nondanee/UnblockNeteaseMusic/issues/338#issuecomment-565265795)，能给些建议吗？谢谢

**Comment by luckyyyyy** [comment]
我用的路由器 所以只能帮你到这里了
![image](https://user-images.githubusercontent.com/9210430/70866829-889ac580-1fa9-11ea-9164-1a183d6e1656.png)


![image](https://user-images.githubusercontent.com/9210430/70866824-77ea4f80-1fa9-11ea-92bd-e298786170ff.png)

![image](https://user-images.githubusercontent.com/9210430/70866818-6c972400-1fa9-11ea-9a2a-96b736de36cb.png)


![image](https://user-images.githubusercontent.com/9210430/70866836-95b7b480-1fa9-11ea-8120-10a0bcece60d.png)

**Comment by Paris0-0** [comment]
> 我用的路由器 所以只能帮你到这里了
> ![image](https://user-images.githubusercontent.com/9210430/70866829-889ac580-1fa9-11ea-9164-1a183d6e1656.png)
> 
> ![image](https://user-images.githubusercontent.com/9210430/70866824-77ea4f80-1fa9-11ea-92bd-e298786170ff.png)
> 
> ![image](https://user-images.githubusercontent.com/9210430/70866818-6c972400-1fa9-11ea-9a2a-96b736de36cb.png)
> 
> ![image](https://user-images.githubusercontent.com/9210430/70866836-95b7b480-1fa9-11ea-8120-10a0bcece60d.png)

我证书什么的也都信任了，代理也监听https了。。搞不懂

**Comment by shuiRong** [comment]
谢谢，问题解决了。
> （解决方法更新在了隔壁链接里）
