### ISSUE TITLE
Windows用自签证书后无法播放

### ISSUE THREAD

**Issue by Brightmbsh** [nondanee/UnblockNeteaseMusic#341]
各位大佬好，本人在Windows系统用了自签证书后无法播放任何歌曲。。
![image](https://user-images.githubusercontent.com/43743875/70843664-0d35f880-1e71-11ea-9a32-5df91b1f513e.png)
![image](https://user-images.githubusercontent.com/43743875/70843672-2343b900-1e71-11ea-87ca-88530a6c3c74.png)
客户端除了播放不了歌曲之外，其余功能都是可用的。。
如果用普通http代理，则没有问题，需要我提供什么log吗
![image](https://user-images.githubusercontent.com/43743875/70843690-b41a9480-1e71-11ea-9125-6ff4cfedd882.png)

**Comment by nondanee** [comment]
可是你的 log 里都看不到 m(?).music.126.net 开头的音频请求 ==
正常是这样的

![image](https://user-images.githubusercontent.com/26399680/70843917-b2060500-1e74-11ea-956e-9beaf4bc1db6.png)

**Comment by Brightmbsh** [comment]
> 可是你的 log 里都看不到 m(?).music.126.net 开头的音频请求 ==
> 正常是这样的
> 
> ![image](https://user-images.githubusercontent.com/26399680/70843917-b2060500-1e74-11ea-956e-9beaf4bc1db6.png)

有的 我没截出来
![image](https://user-images.githubusercontent.com/43743875/70843974-95b69800-1e75-11ea-8994-7b86ba2930af.png)

**Comment by nondanee** [comment]
m开头是音频，p开头是图片==

**Comment by Brightmbsh** [comment]
> m开头是音频，p开头是图片==

那确实是没有，播放器卡一会儿就自动播放失败了

**Comment by nondanee** [comment]
直接用浏览器打开网易云日志里 Request Http File Error 的链接打得开吗？

**Comment by Brightmbsh** [comment]
> 直接用浏览器打开网易云日志里 Request Http File Error 的链接打得开吗？

可以的
![image](https://user-images.githubusercontent.com/43743875/70844051-5c325c80-1e76-11ea-9567-f0e4f8d518fa.png)

**Comment by nondanee** [comment]
有重定向？
网易云给的 URL 应该是 .mp3/.flac 结尾的啊

**Comment by Brightmbsh** [comment]
> 有重定向？
> 网易云给的 URL 应该是 .mp3/.flac 结尾的啊

日志里那个地址就是带重定向的
![image](https://user-images.githubusercontent.com/43743875/70844095-ed093800-1e76-11ea-819e-62e87160322a.png)

**Comment by Brightmbsh** [comment]
> 有重定向？
> 网易云给的 URL 应该是 .mp3/.flac 结尾的啊

也有一些是不带重定向的  同样可以打开
![image](https://user-images.githubusercontent.com/43743875/70844107-3b1e3b80-1e77-11ea-8811-6be4bdde83e1.png)
![image](https://user-images.githubusercontent.com/43743875/70844110-407b8600-1e77-11ea-997d-0158c3060669.png)

**Comment by nondanee** [comment]
好的

> 如果用普通http代理，则没有问题

你说的普通 http 代理是指什么，`-p 7080` 这样？能不能也贴一下 log？

**Comment by Brightmbsh** [comment]
是的，这是log
![image](https://user-images.githubusercontent.com/43743875/70844157-f050f380-1e77-11ea-9af6-8ff1edd761e6.png)
![image](https://user-images.githubusercontent.com/43743875/70844165-0ced2b80-1e78-11ea-873c-39f930c26fb8.png)
![image](https://user-images.githubusercontent.com/43743875/70844169-11b1df80-1e78-11ea-8521-4dda15ee4b3c.png)
![image](https://user-images.githubusercontent.com/43743875/70844177-3443f880-1e78-11ea-85b3-35929ef28ca2.png)
![image](https://user-images.githubusercontent.com/43743875/70844184-49b92280-1e78-11ea-90db-4e3a40aff6ee.png)

**Comment by nondanee** [comment]
那你试试去证书管理器里删掉证书
然后还用 `-p 7080:7082` 启动，还能不能播放

还是 2.7 版本的 release log 是这样的
> ★ 受版权方要求2.6及以下版本可能无法收听部分歌曲，升级即可聆听
★ 音量条样式优化
★ 支持关闭播放页的直播推荐
★ 修复部分网络卡顿问题与bug

要不你更新下试试
我实在不知道为什么

**Comment by Brightmbsh** [comment]
> 那你试试去证书管理器里删掉证书
> 然后还用 `-p 7080:7082` 启动，还能不能播放
> 
> 还是 2.7 版本的 release log 是这样的
> 
> > ★ 受版权方要求2.6及以下版本可能无法收听部分歌曲，升级即可聆听
> > ★ 音量条样式优化
> > ★ 支持关闭播放页的直播推荐
> > ★ 修复部分网络卡顿问题与bug
> 
> 要不你更新下试试
> 我实在不知道为什么

好的 稍等我试一下

**Comment by Brightmbsh** [comment]
> 那你试试去证书管理器里删掉证书
> 然后还用 `-p 7080:7082` 启动，还能不能播放
> 
> 还是 2.7 版本的 release log 是这样的
> 
> > ★ 受版权方要求2.6及以下版本可能无法收听部分歌曲，升级即可聆听
> > ★ 音量条样式优化
> > ★ 支持关闭播放页的直播推荐
> > ★ 修复部分网络卡顿问题与bug
> 
> 要不你更新下试试
> 我实在不知道为什么

我找到问题了 这应该是客户端的bug 它不太支持在客户端自带的设置那里设置https代理的方式
为什么说不太支持 是因为只要客户端配置文件里有dnscache这一段 就可以用 如果没有 就用不了
![image](https://user-images.githubusercontent.com/43743875/70844562-1e393680-1e7e-11ea-895f-21d035d8463d.png)
其实它设置代理的那里也没有https代理这个选项，我是直接在配置里改过来的
这个强制在新版客户端里直接彻底就用了了，不只是播放不了
![image](https://user-images.githubusercontent.com/43743875/70844570-52145c00-1e7e-11ea-8162-f07621e2294d.png)

**Comment by nondanee** [comment]
NB！

其实我之前就想问你是不是用了 https 代理==
但是我去客户端试了下填上压根用不了就没问。。。

正常情况 log 是不会直接显示的 MITM (ssl)
```
MITM > music.163.com (ssl)
```
在 MITM (ssl) 之前肯定会先有 tunnel 转发到 https 端口才能 MITM
```
TUNNEL > localhost:7082
MITM > music.163.com (ssl)
```

装了证书，开了第二个端口，你还是填 http 代理的端口就行
https 端口虽然和 http 端口共用逻辑(全功能代理) 但是仅仅做内部转发用

**Comment by Brightmbsh** [comment]
> NB！
> 
> 其实我之前就想问你是不是用了 https 代理==
> 但是我去客户端试了下填上压根用不了就没问。。。
> 
> 正常情况 log 是不会直接显示的 MITM (ssl)
> 
> ```
> MITM > music.163.com (ssl)
> ```
> 
> 在 MITM (ssl) 之前肯定会先有 tunnel 转发到 https 端口才能 MITM
> 
> ```
> TUNNEL > localhost:7082
> MITM > music.163.com (ssl)
> ```
> 
> 装了证书，开了第二个端口，你还是填 http 代理的端口就行
> https 端口虽然和 http 端口共用逻辑(全功能代理) 但是仅仅做内部转发用

感谢大佬，正常了 是我沙雕了
