### ISSUE TITLE
配置成功后周杰伦的歌曲依然不能播放，其他歌手无问题

### ISSUE THREAD

**Issue by a08381** [nondanee/UnblockNeteaseMusic#342]
系统版本：iOS 12.1.2
软件版本：6.4.4

播放周杰伦的音乐时就提示网络不给力，无法继续播放，播放同样无版权的ASCA的音乐时就能够正常播放。后台日志正常。
![9D651EC7-F07F-4959-9B89-E140554C6BFB](https://user-images.githubusercontent.com/2505002/70865387-03f37b80-1f98-11ea-860f-5660ec259a1f.png)
![6D6BA6DA-31E1-458F-B63C-05A1C75F1D13](https://user-images.githubusercontent.com/2505002/70865388-048c1200-1f98-11ea-9694-89c413ee4512.png)
![2A3E098E-84E0-4F3F-B520-E72E6BF95DFB](https://user-images.githubusercontent.com/2505002/70865389-048c1200-1f98-11ea-9a35-baa5dff64580.png)
![49C0C7C5-43E9-4486-8EC6-5553BD86EF41](https://user-images.githubusercontent.com/2505002/70865390-0524a880-1f98-11ea-9b9f-5701b2f43dff.png)
![7992C2E1-C6B4-4002-9E69-048457A53AE0](https://user-images.githubusercontent.com/2505002/70865391-0655d580-1f98-11ea-9fe8-486e06abb942.png)

**Comment by nondanee** [comment]
启动参数是什么

**Comment by a08381** [comment]
> 启动参数是什么

`npx @nondanee/unblockneteasemusic -p 4398:4399`
使用4398端口连接服务器

**Comment by nondanee** [comment]
盲猜是没配置好

问题原因在这里 https://github.com/nondanee/UnblockNeteaseMusic/issues/329#issuecomment-562629736 ，解决方法看 #65

**Comment by nondanee** [comment]
加上 `-e http://music.163.com` 或者 `-e https://music.163.com` 试试看

**Comment by a08381** [comment]
> 加上 `-e http://music.163.com` 或者 `-e https://music.163.com` 试试看

加上`-e https://music.163.com`后依然无法播放周杰伦的音乐

**Comment by a08381** [comment]
问题已解决。
![8D50EDC9-4A7D-43E2-8176-CCBF72C0B737](https://user-images.githubusercontent.com/2505002/70865860-2936b880-1f9d-11ea-9de0-5caa595d2183.jpeg)

**Comment by nondanee** [comment]
没懂，是加了规则？

**Comment by a08381** [comment]
> 没懂，是加了规则？

嗯，加了music.163.com规则

**Comment by nondanee** [comment]
好。music.126.net 不用加的

**Comment by a08381** [comment]
> 好。music.126.net 不用加的

网易云返回的音乐地址应该都是类似于m*.music.126.net的地址吧？这个不用加的吗？

**Comment by nondanee** [comment]
是，这个不用过代理，直连即可
