### ISSUE TITLE
关于QQ音源添加cookie问题

### ISSUE THREAD

**Issue by zack66** [nondanee/UnblockNeteaseMusic#344]
![image](https://user-images.githubusercontent.com/16634459/70997039-12b06e80-210f-11ea-8143-5068847b6009.png)
请问这样添加Cookie正确吗？
我是豪华绿钻，这样添加Cookie无法解析出周杰伦的音乐

**Comment by nondanee** [comment]
对的

重新登录刷新 qm_keyst 试试看

**Comment by nondanee** [comment]
那你之前是怎么做的呢？https://github.com/nondanee/UnblockNeteaseMusic/issues/288#issuecomment-544275142

**Comment by zack66** [comment]
@ejiaogl 他做的，#288 的发起人

**Comment by nondanee** [comment]
@zack66 
你可以试试把所有 cookie 都填进去看看，我自己测的话用那两个就够了

**Comment by zack66** [comment]
收到，我试试

**Comment by zack66** [comment]
@nondanee 
![image](https://user-images.githubusercontent.com/16634459/71012301-dc341d00-2129-11ea-927c-89714aeb16b6.png)

**Comment by nondanee** [comment]
@zack66 
直接调接口试好了

```js
require('./provider/qq').check({keyword: '我要夏天 - 周杰伦'}).then(console.log)
```

没有的话我也没办法 ==

**Comment by steven7851** [comment]
经测试，最少需要`p_luin=; p_lskey=; uin=; qm_keyst=`才能正常解析

**Comment by nondanee** [comment]
@steven7851 
会不会是登录方式的问题？
我直接用 qq 账密登的

**Comment by zack66** [comment]
@nondanee 
我也是用qq账号密码登录的

**Comment by zack66** [comment]
> 经测试，最少需要`p_luin=; p_lskey=; uin=; qm_keyst=`才能正常解析

`p_luin=; p_lskey=;`  我在cookie里找不到这两个的值...

**Comment by steven7851** [comment]
那我也没办法了，我这里试出来是这样的
不过我是用快速登录，不是用QQ号

**Comment by nondanee** [comment]
@steven7851 
要多次请求的，逻辑要改
不会做，而且项目里是主动屏蔽无损的，因为我没需求 🙃

**Comment by lollyhero** [comment]
> @steven7851
> 要多次请求的，逻辑要改
> 不会做，而且项目里是主动屏蔽无损的，因为我没需求 🙃

hi我像问一下 COOKIE需要定期重新更新吗？是否会失效，因为我看最近我的歌下载下来又是三四兆了，我会员没到期，另外是否是只要有cookie就能320K还是必须是会员，谢谢

**Comment by nondanee** [comment]
@lollyhero 
应该会过期的，我没试过
视歌曲而定吧，有些歌要绿钻，比如周杰伦

**Comment by lollyhero** [comment]
> @lollyhero
> 应该会过期的，我没试过
> 视歌曲而定吧，有些歌要绿钻，比如周杰伦

我刚刚试了  cookie会过期，过期后他就默认走kuwo下载所以又变成128K的音质了，更新了QQ的cookie重启服务器，然后手机升级一下音质周杰伦的歌就可以320K了，另外还有个问题请教一下，这个软件只会把网易灰色的歌去别的网站匹配吗？因为我有个歌（林俊杰-友人说）我看QQ里有320K的我也能在QQ音乐里下载320K的，但是我在网易里下载时候只能下载到128K的，是因为我没网易的会员吗？怎么能全部都匹配别的网站？有方法吗？ （感觉这样不如直接用QQ了-。-，不过主要我喜欢网易的界面和推荐，QQ也有许多网易没的歌），谢谢！

**Comment by zack66** [comment]
cookie一般24小时过期，开头就说了是豪华绿钻

**Comment by nondanee** [comment]
@lollyhero 
嗯，现在实现确实有点问题，cookie 过期了页不会降到 M500，之后优化一下

对，只会处理不能听的和试听的歌 #106 #264  

是的因为你没有网易会员

![image](https://user-images.githubusercontent.com/26399680/71459288-b53cb180-27e1-11ea-8b11-19b562282ecf.png)

你要全部匹配别的话改这行就行

https://github.com/nondanee/UnblockNeteaseMusic/blob/ee9d883b968b78842ab626f4f8051b40d4e7ff47/hook.js#L283

```diff
--		if((item.code != 200 || item.freeTrialInfo) && (target == 0 || item.id == target)){
++		if(target == 0 || item.id == target){
```

按音质区分也可以

```diff
--		if((item.code != 200 || item.freeTrialInfo) && (target == 0 || item.id == target)){
++		if((item.br < 320000) && (target == 0 || item.id == target)){
```

当然匹配到的音质也不见的都有 320K
如果能播放的歌匹配不到，还是会用网易自己的播放地址

**Comment by nondanee** [comment]
@zack66 
cookie 的事你直接问 @ejiaogl 吧，他不是先做出来了嘛
我能做的最多就是再帮你测一下，你把你 cookie 发给我 (邮箱)，测出来行就行，不行就不行
