### ISSUE TITLE
编译出现问题

### ISSUE THREAD

**Issue by xiaoluoabc123** [nondanee/UnblockNeteaseMusic#345]
/workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/etc/init.d/unblockmusic: line 6: uci: command not found
/workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/etc/init.d/unblockmusic: line 7: uci: command not found
/workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/etc/init.d/unblockmusic: line 8: uci: command not found
/workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/etc/init.d/unblockmusic: line 9: uci: command not found
/workspace/OpenwrtCompileScript/Openwrt/LEAN/lede/build_dir/target-mipsel_24kc_musl/root-ramips/etc/init.d/unblockmusic: line 10: uci: command not found

**Comment by nondanee** [comment]
去插件那边问
