### ISSUE TITLE
更新后无法破灰

### ISSUE THREAD

**Issue by zengxiaoliang** [nondanee/UnblockNeteaseMusic#346]
MAC 下 更新了UnblockNeteaseMusic和网易云APP，出现无法破灰现象；

启动项目成功
HTTP Server running @ http://0.0.0.0:8888
HTTPS Server running @ https://0.0.0.0:443

配置1   
在网络代理设置中使用 自动代理 http://127.0.0.1:8888/proxy.pac
出现提示网络连接失败，但部分歌曲可以播放(可能是本地缓存)

pac 文件
function FindProxyForURL(url, host) {
						if (host == 'music.163.com' || host == 'interface.music.163.com' || host == 'interface3.music.163.com' || host == 'apm.music.163.com' || host == 'apm3.music.163.com' || host == '59.111.181.35' || host == '59.111.181.38' || host == '59.111.181.60' || host == '223.252.199.66' || host == '223.252.199.67' || host == '59.111.160.195' || host == '59.111.160.197' || host == '118.24.63.156' || host == '193.112.159.225' || host == '112.13.119.17' || host == '112.13.122.1' || host == '39.105.63.80' || host == '47.100.127.239') {
							return 'PROXY 127.0.0.1:8888'
						}
						return 'DIRECT'
					}

配置2
代理中配置http 代理， 127.0.0.1     端口8888 
出现非灰色歌曲能正常播放，灰色的提示版权问题

MITM > wanproxy.127.net
MITM > ocsp.trust-provider.com
MITM > web.push.126.net:6003
MITM > p2.music.126.net
MITM > p1.music.126.net
MITM > p2.music.126.net
MITM > p1.music.126.net
MITM > ocsp.trust-provider.com

**Comment by gqbre** [comment]
https://github.com/nondanee/UnblockNeteaseMusic/issues/338#issuecomment-565931815

**Comment by gqbre** [comment]
https://github.com/nondanee/UnblockNeteaseMusic/issues/338#issuecomment-565931815

**Comment by zengxiaoliang** [comment]
修改 Hooks.js  中的配置如

今日测试网易云音乐 Mac 客户端更新
Proxifier 目标代理域名更新为：*.music.163.com;*.music.126.net;*.netease.com;

还是不行

**Comment by nondanee** [comment]
@zengxiaoliang 

![macOS 10 14-2019-12-19-00-45-11](https://user-images.githubusercontent.com/26399680/71105618-d78a6a00-21f8-11ea-8b3e-f1a28434dde9.png)


没问题啊，用的 PAC
Mojave 10.14
NeteaseMusic 2.3.2 (832)

手动代理的话 http 和 https 都要勾上，地址都填 http://127.0.0.1:8888

**Comment by zengxiaoliang** [comment]
系统：mac 10.13.6
网易云  ： 2.3.2 (832)
启动方式： node app.js

配置：
使用pac 方式，勾选自动代理 url 设置 http://127.0.0.1:9999/proxy.pac  (和你的配置一样，无其他网络代理)

现象：app 提示网络异常，无法正常播放

端口情况：
tcp4       0      0  127.0.0.1.9999         127.0.0.1.49234        FIN_WAIT_2
tcp4       0      0  127.0.0.1.49234        127.0.0.1.9999         CLOSE_WAIT
tcp4       0      0  127.0.0.1.9999         127.0.0.1.49233        FIN_WAIT_2
tcp4       0      0  127.0.0.1.9999         127.0.0.1.49232        FIN_WAIT_2
tcp4       0      0  127.0.0.1.49233        127.0.0.1.9999         CLOSE_WAIT
tcp4       0      0  127.0.0.1.49232        127.0.0.1.9999         CLOSE_WAIT
tcp4       0      0  127.0.0.1.9999         127.0.0.1.49230        FIN_WAIT_2
tcp4       0      0  127.0.0.1.49230        127.0.0.1.9999         CLOSE_WAIT
tcp4       0      0  127.0.0.1.9999         127.0.0.1.49228        FIN_WAIT_2
tcp4       0      0  127.0.0.1.49228        127.0.0.1.9999         CLOSE_WAIT
tcp4       0      0  127.0.0.1.9999         127.0.0.1.49227        FIN_WAIT_2
tcp4       0      0  127.0.0.1.49227        127.0.0.1.9999         CLOSE_WAIT
tcp46      0      0  *.9999                 *.*                    LISTEN
tcp4       0      0  127.0.0.1.49491        127.0.0.1.9999         TIME_WAIT

**Comment by nondanee** [comment]
@zengxiaoliang 
只是 `node app.js` 不行的
之前装过证书了吗？用浏览器 (过代理) 能打开 music.163.com 吗？

**Comment by zengxiaoliang** [comment]
之前一直都这么启动，没有单独安装过证书；

先配置代理，浏览器房屋music.163.com   能正常访问（Chrome提示证书不可信任，手动信任后正常访问）

MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)

**Comment by nondanee** [comment]
@zengxiaoliang 
那你装一下证书吧

**Comment by zengxiaoliang** [comment]
安装证书后，问题解决；
