### ISSUE TITLE
docker部署ios手机无法播放win.web.ri01.sycdn.kuwo.cn的歌

### ISSUE THREAD

**Issue by linxubin1994** [nondanee/UnblockNeteaseMusic#348]
通过docker部署，拉的是最新的代码，
启动参数：
`docker run --restart=always --name unmusic  -e http://music.163.com -d -p 4567:8080  nondanee/unblockneteasemusic`
上面改成 https://music.163.com 一样不可用
点播放的时候，日志：
![image](https://user-images.githubusercontent.com/13884091/71547934-8ee56480-29e1-11ea-8a9c-7948523163e5.png)
然后手机上显示网络不给力，无法继续播放，
以 `win.web.ri01.sycdn.kuwo.cn`开头的歌手机都没法播放，直接在浏览器打开解析后的mp3格式是可以播放的。
以`dl.stream.qqmusic.qq.com`解析的歌都可以手机播放。

手机已经按照这个步骤执行了。

![image](https://user-images.githubusercontent.com/13884091/71547957-e257b280-29e1-11ea-9190-98ad60d62693.png)
![image](https://user-images.githubusercontent.com/13884091/71547961-00251780-29e2-11ea-89df-62128927a66d.png)

是docker的参数写错了吗？

**Comment by nondanee** [comment]
解决了吗？

确实写错了

```diff
--docker run --restart=always --name unmusic -e http://music.163.com -d -p 4567:8080 nondanee/unblockneteasemusic
++docker run --restart=always --name unmusic -d -p 4567:8080 nondanee/unblockneteasemusic -e http://music.163.com -p 8080:8081
```

**Comment by linxubin1994** [comment]
> 解决了吗？
> 
> 确实写错了
> 
> ```diff
> - docker run --restart=always --name unmusic -e http://music.163.com -d -p 4567:8080 nondanee/unblockneteasemusic
> + docker run --restart=always --name unmusic -d -p 4567:8080 nondanee/unblockneteasemusic -e http://music.163.com -p 8080:8081
> ```
解决啦，后面看了大家的讨论，然后改了之后可以了
