### ISSUE TITLE
紧急通告

### ISSUE THREAD

**Issue by nondanee** [nondanee/UnblockNeteaseMusic#35]
*抱歉的通知各位*

### QQ 音乐 vkey 策略变动
目前网上流传的提升音质方法应该都失效了，包括各种无损下载器，包括音量增强器
暂时只能回滚到 m4a 音源

### 虾米 API 被 punish
会修复，不过现在虾米有海外墙了

*修复时间待定*

**Comment by ymmshi** [comment]
大佬加油

**Comment by nondanee** [comment]
QQ 音乐暂时修复，还是 320K，不知道能撑多久...

**Comment by nondanee** [comment]
虾米暂时修复，仍有几率被 punish。有海外墙，建议海外用户不要启用

**Comment by abc1763613206** [comment]
感觉还是抓紧fork下或是备份到gitlab比较好，感觉企鹅家快DMCA takedown了

**Comment by nondanee** [comment]
不太张扬是不会的，别奶了
fork 了的记得定期 pr 同步
万一项目死了，留着旧版本也没用

**Comment by mu-yu** [comment]
listen 1曾经被短期DMCA takedown 过，后来又恢复了…如果有什么不幸的消息，可以和listen 1的 repo 主探讨下经验…

**Comment by nondanee** [comment]
@mu-yu 了解
