### ISSUE TITLE
能不能每天定时自动更新QQ音乐COOKIE

### ISSUE THREAD

**Issue by 3131210** [nondanee/UnblockNeteaseMusic#351]
能不能每天定时自动更新QQ音乐COOKIE。输入QQ号码和密码，自动获取cookie

**Comment by 3131210** [comment]
JS脚本   自动把qm_keyst复制到剪贴板
`function getCookie(cookieName) {
	var strCookie = document.cookie;
	var arrCookie = strCookie.split("; ");
	for (var i = 0; i < arrCookie.length; i++) {
		var arr = arrCookie[i].split("=");
		if (cookieName == arr[0]) {
			return arr[1]
		}
	}
	return ""
}
function put_qm_keyst(txt) {
	let tmp_el = document.createElement("input");
	tmp_el.setAttribute("readonly", "readonly");
	tmp_el.setAttribute("value", txt);
	document.body.appendChild(tmp_el);
	tmp_el.select();
	tmp_el.setSelectionRange(0, 9999);
	if (document.execCommand("copy")) {
		document.execCommand("copy")
	}
	document.body.removeChild(tmp_el);
	alert("复制成功")
}
put_qm_keyst(getCookie("qm_keyst"))`

**Comment by 3131210** [comment]
下面代码搞到收藏夹，QQ音乐网页点击这个标签也会自动复制到剪贴板

[获取QM_KEYST](javascript:(function()%7Bfunction getCookie(cookieName) %7Bvar strCookie %3D document.cookie%3Bvar arrCookie %3D strCookie.split("%3B ")%3Bfor (var i %3D 0%3B i < arrCookie.length%3B i%2B%2B) %7Bvar arr %3D arrCookie%5Bi%5D.split("%3D")%3Bif (cookieName %3D%3D arr%5B0%5D) %7Breturn arr%5B1%5D%7D%7Dreturn ""%7Dfunction put_qm_keyst(txt) %7Blet tmp_el %3D document.createElement("input")%3Btmp_el.setAttribute("readonly"%2C "readonly")%3Btmp_el.setAttribute("value"%2C txt)%3Bdocument.body.appendChild(tmp_el)%3Btmp_el.select()%3Btmp_el.setSelectionRange(0%2C 9999)%3Bif (document.execCommand("copy")) %7Bdocument.execCommand("copy")%7Ddocument.body.removeChild(tmp_el)%3Balert("复制成功")%7Dput_qm_keyst(getCookie("qm_keyst"))%7D)())

**Comment by Paris0-0** [comment]
其实直接复制整个cookie就好了不用特地分出qm_keyst，主要是有没有办法模拟QQ登录自动获取cookie。
没抓包看过，估计不太行QQ登录都是有单独跳转验证的

**Comment by nondanee** [comment]
是的，账密登录一般都有 captcha 机制，很难模拟
可以考虑一下 token refresh ，不太熟悉 QQ 音乐的接口，不知道有没有，等有空看看

**Comment by 3131210** [comment]
快速修改cookie的代码

`read -e -p "输入qm_keyst：" qm_keyst
sed -i 's/qm_keyst=.\+\?''/qm_keyst='$qm_keyst''\''/g' /usr/local/UnblockNeteaseMusic/src/provider/qq.js
/etc/init.d/unblock163 restart`

**Comment by nondanee** [comment]
@3131210 
建议 cookie 写到文件
启动 sh 脚本读 cookie 文件内容设置环境变量 `QQ_COOKIE`
**不要直接改代码**

账密登录肯定做不了
网页版这边没仔细看，但我几乎每次都要重登那应该也木的挖掘价值
不知道移动端 cookie 时效会不会长一点，你可以试试看

或者期待一下 [sososo/QQMusicApi](https://github.com/jsososo/QQMusicApi) 解决这个问题吧
https://github.com/jsososo/QQMusicApi/issues/9#issuecomment-575991410

**Comment by yufire** [comment]
❌qq登录验证实现起来非常的困难，需要绕过验证码，可能还需要你提供你的QQ账号密码，这非常的不安全。
✅**换个思路（已实现），我们可以去研究一下QQ的扫码登录，破解一下扫码oauth2授权的流程，换取到授权码后请求qq音乐的登录接口，登录接口会返回refresh_token。每隔24小时刷新一下token即可实现cookie永久使用的功能。
好处是只需要登录一次就能使cookie永久有效，并且不用提供账号密码。**
 
@3131210

**Comment by wzhs** [comment]
@yufire 我怎么没有发现会返回refresh_token，你请求的登录接口是哪个？是https://u.y.qq.com/cgi-bin/musicu.fcg 吗？

**Comment by yufire** [comment]
@wzhs 是https://u.y.qq.com/cgi-bin/musicu.fcg接口，没问题，你可以参考jsososo大佬的代码去研究参数，我就不透露了

**Comment by wzhs** [comment]
@yufire 扫码登录的参数，跟jsososo大佬的代码没关系啊，这是一套登录的参数吧。难道 refresh方法还能用？

**Comment by yufire** [comment]
@wzhs 你先去逆向qq的扫码登录，拿到qq音乐的登录二维码，登录后拿到oauth2必备的参数code，调用qq音乐的登录接口，拿到refresh_token以及musickey等需要的信息，保存refresh_token，后续musickey过期了，使用refresh_token刷新musickey即可完成定时更新cookie，因为cookie里重要的参数就是登录接口返回的musickey。

**Comment by wzhs** [comment]
@yufire 【qq的扫码登录，拿到qq音乐的登录二维码，登录后拿到oauth2必备的参数code，调用qq音乐的登录接口，拿到refresh_token以及musickey等需要的信息】这块我已经完成了；【musickey过期了，使用refresh_token刷新musickey即可完成定时更新cookie】这个不清楚是哪个接口和参数

**Comment by yufire** [comment]
想一起交流吗

**Comment by wzhs** [comment]
@yufire 整套流程你都弄完了？可以交流啊。我现在就差一个刷新登录，重新获取cookies了

**Comment by yufire** [comment]
@wzhs 来知识星球，这不好交流：https://t.zsxq.com/14iFo9PfQ

**Comment by yufire** [comment]
@wzhs 刚试了一下，这套还好使，现在可以一对一教你

**Comment by wzhs** [comment]
好的，我现在有点事，晚上有时间吗？晚上联系你

**Comment by yufire** [comment]
> 好的，我现在有点事，晚上有时间吗？晚上联系你

可以

**Comment by K3522349** [comment]
解决了吗，刷新接口能分享一下吗

**Comment by cwuom** [comment]
> ❌qq登录验证实现起来非常的困难，需要绕过验证码，可能还需要你提供你的QQ账号密码，这非常的不安全。 ✅**换个思路（已实现），我们可以去研究一下QQ的扫码登录，破解一下扫码oauth2授权的流程，换取到授权码后请求qq音乐的登录接口，登录接口会返回refresh_token。每隔24小时刷新一下token即可实现cookie永久使用的功能。 好处是只需要登录一次就能使cookie永久有效，并且不用提供账号密码。**
> 
> @3131210

您好，方便透露具体流程吗，我需要做音乐解析API，能否给一个联系方式？
