### ISSUE TITLE
大佬可以说下用到的技术栈

### ISSUE THREAD

**Issue by gomingge** [nondanee/UnblockNeteaseMusic#353]
想学习这方面的东西, 不是前端开发工程师, 是不是基于某框架呀

**Comment by nondanee** [comment]
谈不上技术栈吧
只是用 node.js 实现 http 代理
原理参考 https://imququ.com/post/web-proxy.html
官方文档里有示例 https://nodejs.org/api/http.html#http_event_connect

和前端没啥关系，node 属于大前端的范畴，其实还是个服务器 (后端)

没有用框架，也没有用三方库
