### ISSUE TITLE
MAC 使用 docker 部署配置后 云音乐网络连接异常

### ISSUE THREAD

**Issue by AlexanderJLiu** [nondanee/UnblockNeteaseMusic#354]
* MAC OS 版本： Catalina 10.15.2
* 云音乐版本：2.3.2（834）
* 使用最新的 git 仓库内容生成 docker 镜像: 
`docker build -t nondanee/unblockneteasemusic:latest .`
* docker 本机运行：
`docker run -d -p 8080:8080 -p 8081:8081 -v server.crt:/usr/src/app/server.crt -v server.key:/usr/src/app/server.key nondanee/unblockneteasemusic -p 8080:8081 -f 59.111.181.35`
* 自签证书，且 ca.crt 也手动置信 [#22](https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-477870013)
* 系统自动代理配置了：http://127.0.0.1:8080/proxy.pac
* 重启云音乐后，网络连接不上 

还有什么地方遗漏的么？[#338](https://github.com/nondanee/UnblockNeteaseMusic/issues/338#issuecomment-565931815)这里提到的会有影响么，不用Proxifier该如何修改呢？谢谢~

**Comment by nondanee** [comment]
看起来没问题，和 Proxifier 没关系

麻烦贴一下 docker 的 log

**Comment by AlexanderJLiu** [comment]
@nondanee 
云音乐网页版也访问不了，高级选项里也没有继续访问
docker log 内容如下：
```
HTTP Server running @ http://0.0.0.0:8080
HTTPS Server running @ https://0.0.0.0:8081
TUNNEL > localhost:8081
TUNNEL > localhost:8081
TUNNEL > localhost:8081
TUNNEL > localhost:8081
TUNNEL > localhost:8081
TUNNEL > localhost:8081
TUNNEL > localhost:8081
TUNNEL > localhost:8081
TUNNEL > localhost:8081
TUNNEL > localhost:8081
TUNNEL > localhost:8081
TUNNEL > localhost:8081
TUNNEL > localhost:8081
TUNNEL > localhost:8081
TUNNEL > localhost:8081
TUNNEL > localhost:8081
TUNNEL > localhost:8081
TUNNEL > localhost:8081
TUNNEL > localhost:8081
TUNNEL > localhost:8081
TUNNEL > localhost:8081
TUNNEL > localhost:8081
TUNNEL > localhost:8081
TUNNEL > localhost:8081
TUNNEL > localhost:8081
```

**Comment by nondanee** [comment]
试试用设置手动代理，看看访问别的网站能不能正常打开？

**Comment by AlexanderJLiu** [comment]
* 如下图设置，两个都设置了相同的内容，所有网站都无法访问了，包括云音乐
![image](https://user-images.githubusercontent.com/15494997/71642333-b2135b00-2ce4-11ea-9e4f-23e4fc31fe39.png)

**Comment by nondanee** [comment]
你看一眼 log

**Comment by AlexanderJLiu** [comment]
log 如下：

TUNNEL > 172.217.160.110:443
TUNNEL > 61.135.169.125:443
TUNNEL > 172.217.160.110:443
TUNNEL > 17.248.161.78:443
TUNNEL > 61.135.169.125:443
TUNNEL > 220.181.38.156:443
TUNNEL > 123.125.132.33:443
TUNNEL > 61.135.169.125:443
TUNNEL > 61.135.169.125:443
TUNNEL > 172.217.160.110:443
TUNNEL > 61.135.169.125:443
TUNNEL > 123.125.132.32:443
TUNNEL > 61.135.169.125:443
TUNNEL > 221.204.189.192:443
TUNNEL > 61.135.169.125:443
TUNNEL > 172.217.160.110:443
TUNNEL > 172.217.160.110:443
TUNNEL > 123.125.132.33:443
TUNNEL > 220.181.38.156:443
TUNNEL > 61.135.169.125:443
TUNNEL > 17.248.161.78:443
TUNNEL > 61.135.169.125:443
TUNNEL > 61.135.169.125:443
TUNNEL > 172.217.160.110:443
TUNNEL > 61.135.169.125:443
TUNNEL > 123.125.132.32:443
TUNNEL > 61.135.169.125:443
TUNNEL > 221.204.189.192:443
TUNNEL > 172.217.160.110:443
TUNNEL > 172.217.160.110:443
TUNNEL > 61.135.169.125:443
TUNNEL > 123.125.132.33:443
TUNNEL > 220.181.38.156:443

**Comment by nondanee** [comment]
emmm
我也不知道为啥==
正常应该不会显示 IP 的
![image](https://user-images.githubusercontent.com/26399680/71642564-387d6c00-2ce8-11ea-91d4-ecaf572ec75c.png)

那你可以试一下不用 docker 跑的情况

**Comment by AlexanderJLiu** [comment]
嗯，好的，我再试试其它方式，多谢了~

**Comment by 1715173329** [comment]
MacOSX应该需要开启EndPoint吧。。

**Comment by nondanee** [comment]
@1715173329 
这个问题和 endpoint 没关系，代理那层就挂了，连不上网

**Comment by 1715173329** [comment]
> @1715173329
> 这个问题和 endpoint 没关系，代理那层就挂了，连不上网

嘛。。抱歉，没看清楚

不过完全没必要用docker跑啊 (docker的网络环境很迷)，用pm2做后台运行就好了啊 (

**Comment by tojason** [comment]
> 看起来没问题，和 Proxifier 没关系
想问一下，现在Proxifier改IP为什么都是Invalid http header？（这里问这个问题可能不太合适）

**Comment by nondanee** [comment]
@tojason 没有懂，啥叫 Proxifier 改 IP？

**Comment by tojason** [comment]
@nondanee 就是给云音乐用Proxifier上代理。

**Comment by nondanee** [comment]
@tojason 麻烦贴个图

**Comment by Lodour** [comment]
我也碰到了这个问题，在 `-v server.crt:/usr/src/app/server.crt -v server.key:/usr/src/app/server.key` 这个参数会报错，似乎是因为 `-v` 不允许挂载单个文件。

安装项目自带的 `ca.crt` 和 `server.crt`，并全部手动添加信任后解决。

目测使用 `docker cp` 替换单个文件也是可行的。

**Comment by bl4ck5un** [comment]
同样的配置在我的系统上(macOS Catalina)可以。

**Comment by bl4ck5un** [comment]
Share一下我的compose file

https://gist.github.com/bl4ck5un/484a47f580ed5021c16e115fce4ed5d3

**Comment by nondanee** [comment]
@Lodour 
刚试了，允许单个文件的，但要用文件的绝对路径
