### ISSUE TITLE
连接直接在chrome里可以打开，但网易云无法播放，一直加载状态

### ISSUE THREAD

**Issue by hdchieh** [nondanee/UnblockNeteaseMusic#355]
我猜我需要安装旧版本网易云。

**Comment by hdchieh** [comment]
手机可以播放。但是windows就不行。。

**Comment by hdchieh** [comment]
我在路由器上运行，手机和电脑都是内网，windows直接在客户端上设置，手机用shadowrocket，手机可以播放，电脑客户端一直在加载中，返回的链接直接打开也可以播放。。人都傻了。试了好几个版本还是不行。

**Comment by hdchieh** [comment]
之前很早的时候是可以的，从什么时候不可以的也没有注意，今天才受不了。

**Comment by nondanee** [comment]
客户端版本是多少？
再提供一下 server log

**Comment by hdchieh** [comment]
> 客户端版本是多少？
> 再提供一下 server log

[1413304973] 请珍重
http://dl.stream.qqmusic.qq.com/M500004OlyuC3HgcL1.mp3?vkey=5E0728459A2C402E58133C2679017053045EB9516EE5BDFBC274C834579ADB2156EFC98E0C6919B2F9F5AA1CB67A8D3B382BE23E8F630909&uin=0&fromtag=8&guid=7332953645
MITM > clientlog.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > m8.music.126.net 
MITM > clientlog.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
[1413304973] 请珍重
http://dl.stream.qqmusic.qq.com/M500004OlyuC3HgcL1.mp3?vkey=78F8090876AA58F9B4FD618362AF255FE1D95A5FD12D647027D10C100DE62F2929C3D9645472D4BAFA34C233B4516FADA1D0C277E81808A0&uin=0&fromtag=8&guid=7332953645
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > clientlog.music.163.com 
MITM > interface.music.163.com

**Comment by hdchieh** [comment]
> 客户端版本是多少？
> 再提供一下 server log

客户端最近的五六个都试了 windows的

**Comment by nondanee** [comment]
是不是有用 `-e` ？`-e` 的地址设了什么？

**Comment by hdchieh** [comment]
没有 只是 nohup node app.js -p 2333 -f ping返回的ip & 
并且我用手机代理是可以无限制播放的

**Comment by hdchieh** [comment]
> 是不是有用 `-e` ？`-e` 的地址设了什么？

没有 只是 nohup node app.js -p 2333 -f ping返回的ip &
并且我用手机代理是可以无限制播放的

**Comment by hdchieh** [comment]
![image](https://user-images.githubusercontent.com/33096672/72208622-e99db680-34df-11ea-8b01-70082bc8b4c9.png)

而iOS可以播放。。 唉...

**Comment by nondanee** [comment]
@hdchieh 
发现问题了
![image](https://user-images.githubusercontent.com/26399680/72866455-45edab00-3d16-11ea-8802-26a5be09e76a.png)

打开 `-s` (严格模式) 以后 dl.stream.qq.com 的请求会被拒绝，因为不是网易云所属域名

解决方法: 
可以加上 `-e http://music.163.com` 包裹一个地址
或者关掉 `-s`

**Comment by hdchieh** [comment]
一直没看到 哭了 太感谢了
