### ISSUE TITLE
mac版本试了好几种方法都不行

### ISSUE THREAD

**Issue by HHX0129** [nondanee/UnblockNeteaseMusic#357]
如果修改hosts或者用proxifier只提示连接成功
hosts是连的80
```
HTTP Server running @ http://0.0.0.0:8888
HTTPS Server running @ https://0.0.0.0:8889
```

没有后续的输出

proximier+ 代理的话就会提示
![image](https://user-images.githubusercontent.com/48744022/72046485-73d4f780-32f3-11ea-81ad-70dad60966d6.png)
![image](https://user-images.githubusercontent.com/48744022/72046516-8a7b4e80-32f3-11ea-8e61-bc290191f753.png)

```
HTTP Server running @ http://0.0.0.0:8888
HTTPS Server running @ https://0.0.0.0:8889
TUNNEL > localhost:8889
TUNNEL > localhost:8889
TUNNEL > localhost:8889
TUNNEL > localhost:8889
TUNNEL > localhost:8889
TUNNEL > 42.81.118.35:443
TUNNEL > localhost:8889
TUNNEL > localhost:8889
TUNNEL > localhost:8889
TUNNEL > localhost:8889
TUNNEL > localhost:8889
TUNNEL > localhost:8889
TUNNEL > localhost:8889
TUNNEL > localhost:8889
TUNNEL > localhost:8889
TUNNEL > localhost:8889
TUNNEL > localhost:8889
TUNNEL > localhost:8889
TUNNEL > localhost:8889
TUNNEL > localhost:8889
```
![image](https://user-images.githubusercontent.com/48744022/72046604-beef0a80-32f3-11ea-996e-3c39b015e4b7.png)
![image](https://user-images.githubusercontent.com/48744022/72046622-c7474580-32f3-11ea-8bb8-dadd46643801.png)

**Comment by HHX0129** [comment]
图片好像挂了... 网易云版本是2.0.0(Build:700)
电脑系统MACOS 10.14.6

**Comment by nondanee** [comment]
图没挂

proxifier 和代理不要同时用
只用 PAC 可以吗？

**Comment by HHX0129** [comment]
> 图没挂
> 
> proxifier和代理不要同时用
> 只用PAC可以吗？

PAC是什么的东西....

**Comment by nondanee** [comment]
你设的自动代理配置文件就是 PAC

**Comment by HHX0129** [comment]
> 你设的自动代理配置文件就是 PAC

只用的话也是灰的....

**Comment by zhangyanq** [comment]
测试了下是可以的
![image](https://user-images.githubusercontent.com/15721388/72067952-f32bf080-331e-11ea-89d0-ef7b4183c77a.png)

**Comment by HHX0129** [comment]
> 测试了下是可以的
> ![image](https://user-images.githubusercontent.com/15721388/72067952-f32bf080-331e-11ea-89d0-ef7b4183c77a.png)

你是怎么弄得..  我咋弄都不行

**Comment by govizlora** [comment]
根据你的log，感觉是没信任证书

**Comment by govizlora** [comment]
浏览器访问 https://music.163.com 的时候那边的log显示什么？

**Comment by HHX0129** [comment]
> 浏览器访问 https://music.163.com 的时候那边的log显示什么？
![image](https://user-images.githubusercontent.com/48744022/72580131-09850e00-3916-11ea-85cc-cd1cced0e58d.png)

**Comment by govizlora** [comment]
不好意思，我是想指unblock这边的输出，就是
```
HTTP Server running @ http://0.0.0.0:8888
HTTPS Server running @ https://0.0.0.0:8889
```
之后的。我没信任证书的时候，显示的都是类似
```
TUNNEL > localhost:8889
TUNNEL > localhost:8889
TUNNEL > localhost:8889
TUNNEL > localhost:8889
TUNNEL > localhost:8889
TUNNEL > localhost:8889
TUNNEL > localhost:8889
TUNNEL > localhost:8889
```
信任之后就好了。。

**Comment by Xun66** [comment]
我这里是Mac客户端+信任证书+设置系统全局代理之后就可以正常使用了，本机运行的话可以从简

**Comment by nondanee** [comment]
@HHX0129 
浏览器打开 https://music.163.com 会提示证书错误吗？会的话就是证书没装好

还有设完代理以后网易云客户端重启一次
