### ISSUE TITLE
修改hosts没有走

### ISSUE THREAD

**Issue by Vikec** [nondanee/UnblockNeteaseMusic#358]
修改host  interface.music.163.com 指向本地
 unblockneteasemusic -p 80 
打开客户端流量并没有走 手动指定代理才可以

**Comment by nondanee** [comment]
Windows 客户端？已知问题
https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-554661621 
https://github.com/nondanee/UnblockNeteaseMusic/issues/336#issuecomment-564084754
https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-569512739

README 上还没有同步这个问题，之后会加上

**Comment by Vikec** [comment]
Windows 客户端 安卓都不行 我是在路由器上做的反向代理

**Comment by nondanee** [comment]
安卓不行写在 README 里 https://github.com/nondanee/UnblockNeteaseMusic/commit/12e1910897b16e895aa650cadcd76fbf1f54e607 (commit 时间 2019.5.2)
