### ISSUE TITLE
iOS设备无法播放酷我音源的歌曲

### ISSUE THREAD

**Issue by ZeaKyX** [nondanee/UnblockNeteaseMusic#359]
设备iOS 13，最新客户端，地址改为http也无效
播放显示网络不给力，而实际log已经出现sycdn.kuwo.cn的地址
其他音源如qq是可以使用的，Windows等其他设备上使用最新网易云客户端酷我的音源也能播放

**Comment by nondanee** [comment]
嗯只有 QQ 音乐的链接支持 https，其他都不支持

这个问题应该就出在设了 -e 但没效果
你能不能改下代码把 global.endpoint 打印出来看一看？可能是你设参数的姿势问题

启动命令也发一下

**Comment by ZeaKyX** [comment]
> 嗯只有 QQ 音乐的链接支持 https，其他都不支持
> 
> 这个问题应该就出在设了 -e 但没效果
> 你能不能改下代码把 global.endpoint 打印出来看一看？可能是你设参数的姿势问题
> 
> 启动命令也发一下

非常抱歉，我使用的衍生项目[https://github.com/coolsnowwolf/lede/tree/master/package/lean/luci-app-unblockmusic](url) ，不是很清楚原理
启动参数应该是[https://github.com/coolsnowwolf/lede/blob/master/package/lean/luci-app-unblockmusic/root/etc/init.d/unblockmusic](url)中的这个：
`node /usr/share/UnblockNeteaseMusic/app.js $endponintset -p 5201:5202 -o $TYPE`
好像没有使用-e参数。。。endpointset即为自定义的http://music.163.com

**Comment by yxk2012** [comment]
同样的问题，同样的测试方法= =。ios13 最新版网易云出的问题

**Comment by nondanee** [comment]
能不能找个电脑跑 node 测一下？我不知道插件还有哪些默认行为
感觉你给 iOS 用的端口没有打开 `-e`
能不能确定一下出现 sycdn.kuwo.cn 地址的实例是 5200 还是 5201？两边的 log 是打在一起的吗？

**Comment by Xun66** [comment]
> > 嗯只有 QQ 音乐的链接支持 https，其他都不支持
> > 这个问题应该就出在设了 -e 但没效果
> > 你能不能改下代码把 global.endpoint 打印出来看一看？可能是你设参数的姿势问题
> > 启动命令也发一下
> 
> 非常抱歉，我使用的衍生项目[luci-app-unblockmusic](https://github.com/coolsnowwolf/lede/tree/master/package/lean/luci-app-unblockmusic) ，不是很清楚原理
> 启动参数应该是[unblockmusic](https://github.com/coolsnowwolf/lede/blob/master/package/lean/luci-app-unblockmusic/root/etc/init.d/unblockmusic)中的这个：
> `node /usr/share/UnblockNeteaseMusic/app.js $endponintset -p 5201:5202 -o $TYPE`
> 好像没有使用-e参数。。。endpointset即为自定义的http://music.163.com

iOS客户端好像会把音源地址升级到https。如果你能看到客户端这边的通信日志的话，你看看客户端去获取音源的时候，有没有一个http://music.163.com/package/...这样的请求？如果是HTTPS，那应该是会被服务器关掉连接的，说明你必须使用一个其他的endpoint(自己的域名，且要开始https)；如果有的话就说明是其他的问题。

**Comment by Xun66** [comment]
> 同样的问题，同样的测试方法= =。ios13 最新版网易云出的问题

我现在就是iOS13，使用的是shadowrocket+endpoint(自己的域名做反代转发歌曲)，未信任证书，可以正常播放所有歌曲。(#368)

**Comment by ZeaKyX** [comment]
> > > 嗯只有 QQ 音乐的链接支持 https，其他都不支持
> > > 这个问题应该就出在设了 -e 但没效果
> > > 你能不能改下代码把 global.endpoint 打印出来看一看？可能是你设参数的姿势问题
> > > 启动命令也发一下
> > 
> > 
> > 非常抱歉，我使用的衍生项目[luci-app-unblockmusic](https://github.com/coolsnowwolf/lede/tree/master/package/lean/luci-app-unblockmusic) ，不是很清楚原理
> > 启动参数应该是[unblockmusic](https://github.com/coolsnowwolf/lede/blob/master/package/lean/luci-app-unblockmusic/root/etc/init.d/unblockmusic)中的这个：
> > `node /usr/share/UnblockNeteaseMusic/app.js $endponintset -p 5201:5202 -o $TYPE`
> > 好像没有使用-e参数。。。endpointset即为自定义的http://music.163.com
> 
> iOS客户端好像会把音源地址升级到https。如果你能看到客户端这边的通信日志的话，你看看客户端去获取音源的时候，有没有一个http://music.163.com/package/... 这样的请求？如果是HTTPS，那应该是会被服务器关掉连接的，说明你必须使用一个其他的endpoint(自己的域名，且要开始https)；如果有的话就说明是其他的问题。

谢谢科普，大概是衍生项目的问题了，我换了一个默认-e是http://music.163.com/的即可正常使用。

**Comment by ZeaKyX** [comment]
非常抱歉打扰作者，经过更换[luci-app-unblockneteasemusic](https://github.com/project-openwrt/luci-app-unblockneteasemusic)后以上所有最新客户端都可使用，因为默认http，所以所有设备需打开自动代理，ios设备的同学可以尝试

**Comment by nondanee** [comment]
@ZeaKyX 

https://github.com/nondanee/UnblockNeteaseMusic/issues/359#issuecomment-573050258
> > 嗯只有 QQ 音乐的链接支持 https，其他都不支持
> > 这个问题应该就出在设了 -e 但没效果
> > 你能不能改下代码把 global.endpoint 打印出来看一看？可能是你设参数的姿势问题
> > 启动命令也发一下
> 
> 非常抱歉，我使用的衍生项目[luci-app-unblockmusic](https://github.com/coolsnowwolf/lede/tree/master/package/lean/luci-app-unblockmusic) ，不是很清楚原理
> 启动参数应该是[unblockmusic](https://github.com/coolsnowwolf/lede/blob/master/package/lean/luci-app-unblockmusic/root/etc/init.d/unblockmusic)中的这个：
> `node /usr/share/UnblockNeteaseMusic/app.js $endponintset -p 5201:5202 -o $TYPE`
> 好像没有使用-e参数。。。endpointset即为自定义的http://music.163.com

https://github.com/nondanee/UnblockNeteaseMusic/issues/359#issuecomment-576983061
> > > > 嗯只有 QQ 音乐的链接支持 https，其他都不支持
> > > > 这个问题应该就出在设了 -e 但没效果
> > > > 你能不能改下代码把 global.endpoint 打印出来看一看？可能是你设参数的姿势问题
> > > > 启动命令也发一下
> > > 
> > > 
> > > 非常抱歉，我使用的衍生项目[luci-app-unblockmusic](https://github.com/coolsnowwolf/lede/tree/master/package/lean/luci-app-unblockmusic) ，不是很清楚原理
> > > 启动参数应该是[unblockmusic](https://github.com/coolsnowwolf/lede/blob/master/package/lean/luci-app-unblockmusic/root/etc/init.d/unblockmusic)中的这个：
> > > `node /usr/share/UnblockNeteaseMusic/app.js $endponintset -p 5201:5202 -o $TYPE`
> > > 好像没有使用-e参数。。。endpointset即为自定义的http://music.163.com
> > 
> > 
> > iOS客户端好像会把音源地址升级到https。如果你能看到客户端这边的通信日志的话，你看看客户端去获取音源的时候，有没有一个http://music.163.com/package/... 这样的请求？如果是HTTPS，那应该是会被服务器关掉连接的，说明你必须使用一个其他的endpoint(自己的域名，且要开始https)；如果有的话就说明是其他的问题。
> 
> 谢谢科普，大概是衍生项目的问题了，我换了一个默认-e是[http://music.163.com/的即可正常使用。](http://music.163.com/%E7%9A%84%E5%8D%B3%E5%8F%AF%E6%AD%A3%E5%B8%B8%E4%BD%BF%E7%94%A8%E3%80%82)

这个是啥意思啊
你不是说之前默认的 endpoint 也是 http://music.163.com 吗？为啥又能用了呢

我看 luci-app-unblockneteasemusic 的 README 写了让用户装 CA 证书
难道你之前证书没装过吗==

**Comment by ZeaKyX** [comment]
> @ZeaKyX
> 
> [#359 (comment)](https://github.com/nondanee/UnblockNeteaseMusic/issues/359#issuecomment-573050258)
> 
> > > 嗯只有 QQ 音乐的链接支持 https，其他都不支持
> > > 这个问题应该就出在设了 -e 但没效果
> > > 你能不能改下代码把 global.endpoint 打印出来看一看？可能是你设参数的姿势问题
> > > 启动命令也发一下
> > 
> > 
> > 非常抱歉，我使用的衍生项目[luci-app-unblockmusic](https://github.com/coolsnowwolf/lede/tree/master/package/lean/luci-app-unblockmusic) ，不是很清楚原理
> > 启动参数应该是[unblockmusic](https://github.com/coolsnowwolf/lede/blob/master/package/lean/luci-app-unblockmusic/root/etc/init.d/unblockmusic)中的这个：
> > `node /usr/share/UnblockNeteaseMusic/app.js $endponintset -p 5201:5202 -o $TYPE`
> > 好像没有使用-e参数。。。endpointset即为自定义的http://music.163.com
> 
> [#359 (comment)](https://github.com/nondanee/UnblockNeteaseMusic/issues/359#issuecomment-576983061)
> 
> > > > > 嗯只有 QQ 音乐的链接支持 https，其他都不支持
> > > > > 这个问题应该就出在设了 -e 但没效果
> > > > > 你能不能改下代码把 global.endpoint 打印出来看一看？可能是你设参数的姿势问题
> > > > > 启动命令也发一下
> > > > 
> > > > 
> > > > 非常抱歉，我使用的衍生项目[luci-app-unblockmusic](https://github.com/coolsnowwolf/lede/tree/master/package/lean/luci-app-unblockmusic) ，不是很清楚原理
> > > > 启动参数应该是[unblockmusic](https://github.com/coolsnowwolf/lede/blob/master/package/lean/luci-app-unblockmusic/root/etc/init.d/unblockmusic)中的这个：
> > > > `node /usr/share/UnblockNeteaseMusic/app.js $endponintset -p 5201:5202 -o $TYPE`
> > > > 好像没有使用-e参数。。。endpointset即为自定义的http://music.163.com
> > > 
> > > 
> > > iOS客户端好像会把音源地址升级到https。如果你能看到客户端这边的通信日志的话，你看看客户端去获取音源的时候，有没有一个http://music.163.com/package/... 这样的请求？如果是HTTPS，那应该是会被服务器关掉连接的，说明你必须使用一个其他的endpoint(自己的域名，且要开始https)；如果有的话就说明是其他的问题。
> > 
> > 
> > 谢谢科普，大概是衍生项目的问题了，我换了一个默认-e是[http://music.163.com/的即可正常使用。](http://music.163.com/%E7%9A%84%E5%8D%B3%E5%8F%AF%E6%AD%A3%E5%B8%B8%E4%BD%BF%E7%94%A8%E3%80%82)
> 
> 这个是啥意思啊
> 你不是说之前默认的 endpoint 也是 http://music.163.com 吗？为啥又能用了呢
> 
> 我看 luci-app-unblockneteasemusic 的 README 写了让用户装 CA 证书
> 难道你之前证书没装过吗==

当然装了，我也觉得奇怪，原先这个衍生项目默认是https的我改成http无效，我怀疑是这个获取uci的步骤哪里出错了，实际上-e参数没有用上

**Comment by nondanee** [comment]
@ZeaKyX 好的，那我关闭了
