### ISSUE TITLE
macOS设置代理, 网易云无法联网

### ISSUE THREAD

**Issue by ihwf** [nondanee/UnblockNeteaseMusic#36]
按教程运行并设置代理后网易云如下图
![image](https://user-images.githubusercontent.com/17941662/51382205-221ae680-1b51-11e9-9743-b791b55e267b.png)
终端日志如下图
![image](https://user-images.githubusercontent.com/17941662/51382226-34952000-1b51-11e9-9be5-5cd6de030624.png)

**Comment by nondanee** [comment]
多切换几个 tab 看看

**Comment by rexx0520** [comment]
報告，最新版網易雲音樂也有此問題

**Comment by nondanee** [comment]
@rexx0520 
2.X 是全新安装的吗，从 1.X 覆盖升级上来才行 https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-459421423

**Comment by rexx0520** [comment]
@nondanee 是 1.X 覆蓋升級的，看起來沒有要降級 HTTP 的意思
剛剛試了去官網下載全新安裝包覆蓋也不行
版本是 2.0.0 build 700

**Comment by nondanee** [comment]
@rexx0520 在 1.X 可以降级吗，在 1.X 成功了再覆盖安装

**Comment by rexx0520** [comment]
@nondanee 1.X 也不行

**Comment by nondanee** [comment]
@rexx0520 重装 1.X 的时候确认删除干净了吗？可能有残留配置？我查查看

**Comment by rexx0520** [comment]
@nondanee 好像是 docker 的問題...?
我剛剛用 host 模式佈署而不是用端口轉發就成功了
也有可能是湊巧

**Comment by nondanee** [comment]
@rexx0520 
我也不清楚，能用就好
现在唯一能确定的是全新安装 2.X 不能降级
log 改过了 MITM 就是降级了 😂

**Comment by Yansongsongsong** [comment]
@nondanee 
env：
os: MacOS
client: netease_2.0.0_726
lib: UnblockedNetease:latest
config: docker + proxifier

最新版的网易云 不能通过覆盖1.x版本来达到降级目的了好像
![image](https://user-images.githubusercontent.com/20450379/54411896-cbcebc00-472b-11e9-8914-7c7d49e98a63.png)

**Comment by Yansongsongsong** [comment]
> @nondanee
> env：
> os: MacOS
> client: netease_2.0.0_726
> lib: UnblockedNetease:latest
> config: docker + proxifier
> 
> 最新版的网易云 不能通过覆盖1.x版本来达到降级目的了好像
> ![image](https://user-images.githubusercontent.com/20450379/54411896-cbcebc00-472b-11e9-8914-7c7d49e98a63.png)

1.x 相同配置是OK的
![image](https://user-images.githubusercontent.com/20450379/54411944-f02a9880-472b-11e9-8e7c-ce2c10483224.png)

**Comment by nondanee** [comment]
@Yansongsongsong 
那没办法了，想用新 UI 的话回到 690 和 700 试试看吧
http://d1.music.126.net/dmusic/NeteaseMusic_2.0.0_690_web.dmg
http://d1.music.126.net/dmusic/NeteaseMusic_2.0.0_700_web.dmg

726 要求 Sierra 10.12，黑苹果怕更新会崩，没法测试，抱歉啦
