### ISSUE TITLE
openwrt同时使用全局ssr时无法解锁

### ISSUE THREAD

**Issue by WROIATE** [nondanee/UnblockNeteaseMusic#361]
我手动设置了网易云的代理设置，音乐的确不灰了，但是还是无法播放，不知道如何设置，希望作者能指点一下

**Comment by nondanee** [comment]
无法播放时有无匹配成功的 log？

全局 ssr 是指全局走海外吗？
各大音乐平台都有海外墙，请求走海外获取不到数据，没匹配到就无法播放

**Comment by xsm1997** [comment]
如果是使用的luci-app-unblockmusic的话，请手动把网易云客户端的代理设置为192.168.4.1:5200，而不是5201或者5202端口。
刚刚遇到这个问题，用此方法解决。

**Comment by WROIATE** [comment]
> 无法播放时有无匹配成功的 log？
> 
> 全局 ssr 是指全局走海外吗？
> 各大音乐平台都有海外墙，请求走海外获取不到数据，没匹配到就无法播放



> 如果是使用的luci-app-unblockmusic的话，请手动把网易云客户端的代理设置为##路由器IP##:5200，而不是5201或者5202端口。
> 刚刚遇到这个问题，用此方法解决。

我这不行，不管是5200还是5201都不行

**Comment by WROIATE** [comment]
> 无法播放时有无匹配成功的 log？
> 
> 全局 ssr 是指全局走海外吗？
> 各大音乐平台都有海外墙，请求走海外获取不到数据，没匹配到就无法播放

可是我走全局还是能听那些原本不灰的歌的，应该和音乐墙没关系。
顺带一提我走全局是因为在校学生，所以想出用ipv6免流这个歪门邪道==

**Comment by nondanee** [comment]
@WROIATE 
网易云的海外墙这边默认是绕过的，你可以看 README
有匹配 log 吗？没有就是没匹配到

**Comment by WROIATE** [comment]
> @WROIATE
> 网易云的海外墙这边默认是绕过的，你可以看 README
> 有匹配 log 吗？没有就是没匹配到

HTTP Server running @ http://0.0.0.0:5201
HTTPS Server running @ https://0.0.0.0:5202
TUNNEL > s6.music.126.net:443
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
TUNNEL > ac.dun.163yun.com:443
TUNNEL > ac.dun.163yun.com:443
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
TUNNEL > ac.dun.163yun.com:443
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
TUNNEL > p1.music.126.net:443
TUNNEL > p2.music.126.net:443
TUNNEL > p2.music.126.net:443
TUNNEL > p2.music.126.net:443
MITM > music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
TUNNEL > acstatic-dun.126.net:443
MITM > interface.music.163.com 
TUNNEL > localhost:5202
MITM > interface.music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > web.push.126.net:6003 
MITM > interface.music.163.com (ssl)
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > clientlog.music.163.com 
TUNNEL > p4.music.126.net:443
TUNNEL > p3.music.126.net:443
TUNNEL > p3.music.126.net:443
MITM > p2.music.126.net 
TUNNEL > p3.music.126.net:443
TUNNEL > p3.music.126.net:443
MITM > p2.music.126.net 
MITM > p2.music.126.net 
MITM > p2.music.126.net 
TUNNEL > p4.music.126.net:443
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > p2.music.126.net 
TUNNEL > p4.music.126.net:443
MITM > interface.music.163.com 
MITM > p2.music.126.net 
MITM > interface.music.163.com 
TUNNEL > web.push.126.net:6003
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
TUNNEL > m8.music.126.net:443
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > clientlog.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > music.163.com 
MITM > clientlog.music.163.com 
MITM > interface.music.163.com 
TUNNEL > m9.music.126.net:443
MITM > interface.music.163.com 
MITM > clientlog.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
TUNNEL > p4.music.126.net:443
TUNNEL > m9.music.126.net:443
MITM > interface.music.163.com 
MITM > clientlog.music.163.com

**Comment by xsm1997** [comment]
我感觉是因为你全局代理的原因，导致触发了QQ音乐、酷我那些的海外墙。原来没灰的歌还能听，是因为这个项目做了网易云音乐的海外墙绕过。

**Comment by WROIATE** [comment]
> 我感觉是因为你全局代理的原因，导致触发了QQ音乐、酷我那些的海外墙。原来没灰的歌还能听，是因为这个项目做了网易云音乐的海外墙绕过。
能听不是因为这个，因为在这个插件没出来之前我就一直在用全局听歌了

**Comment by nondanee** [comment]
@WROIATE 
看日志就是没有匹配到
具体为什么 error 了只能你自己查了==

**Comment by WROIATE** [comment]
> @WROIATE
> 看日志就是没有匹配到
> 具体为什么 error 了只能你自己查了==

我试了一下，发现不管开不开全局好像都不行，只有把ssr关了才可以，自己看一下防火墙好像也没问题啊。。。我去给passwall的作者提一下，还有是不是可能是dns问题？

**Comment by WROIATE** [comment]
> @WROIATE
> 看日志就是没有匹配到
> 具体为什么 error 了只能你自己查了==

还有我发现网易云如果不设内置代理的话会出现这种影流之主的效果
![Snipaste_2020-01-16_16-51-58](https://user-images.githubusercontent.com/44677306/72508505-bb71fb00-3880-11ea-98c7-716e63d55a0d.png)

**Comment by nondanee** [comment]
> **只有把ssr关了才可以**

那就是说可以了咯？好了的话我把 issue 关掉了

影流之主这个问题能不能复现？
我用系统代理试了下也没啥问题
看截图应该是个歌单吧，歌单 id 是多少？

**Comment by WROIATE** [comment]
> @WROIATE
> 
> > **只有把ssr关了才可以**
> 
> 那就是说可以了咯？好了的话我把 issue 关掉了
> 
> 影流之主这个问题能不能复现？
> 我用系统代理试了下也没啥问题
> 看截图应该是个歌单吧，歌单 id 是多少？

ssr那个我怀疑是防火墙规则或者dns解析问题，我在固件的issue下发了讨论
重复问题我是在网易云里的代理设置设置自定义代理端口号5200就会出现
歌单就是我喜欢的音乐，用户名是WROIATE
