### ISSUE TITLE
安卓使用出现语法错误，如图，小白一个，求助各位

### ISSUE THREAD

**Issue by DEMOONww** [nondanee/UnblockNeteaseMusic#362]
![1320261909](https://user-images.githubusercontent.com/59812544/72230755-f19e4900-35fa-11ea-8c1a-bc0f0b51e9e0.jpg)

**Comment by nondanee** [comment]
`$ node` 会打开 [node REPL](https://www.runoob.com/nodejs/nodejs-repl.html)
在 node 解释器里只能运行 js 代码，而 `node app.js` 是 shell 语句，所以语法错误

直接在 shell 里运行 `node app.js` 就行了

**Comment by DEMOONww** [comment]
> 
> 
> `$ node` 会打开 [node REPL](https://www.runoob.com/nodejs/nodejs-repl.html)
> 在 node 解释器里只能运行 js 代码，而 `node app.js` 是 shell 语句，所以语法错误
> 
> 直接在 shell 里运行 `node app.js` 就行了

感谢回复！搭配drony在安卓完美工作了！
再次感谢作者！
