### ISSUE TITLE
windows无限加载

### ISSUE THREAD

**Issue by wy217817** [nondanee/UnblockNeteaseMusic#367]
如题，Openwrt Koolshare mod V2.33运行2.2.3版本，经测试安卓手机设代理可以正常使用，电脑win10 64位 1909，网易云2.7.0版本设置代理后无限加载无法使用，但是点下载可以下载成功，且下载成功后就可以播放了，直接播放就是无限加载然后加载失败。

**Comment by wy217817** [comment]
log里也是获取到链接了，点进链接可以听，但是网易云就是无限加载，很难受。

**Comment by nondanee** [comment]
是不是配了 `-e` 的问题？
路由器插件有哪些默认配置我是不知道的

麻烦测试一下直接用仓库源码有没有问题，如果没有问题，去找插件作者
