### ISSUE TITLE
docker 容器如何啟動嚴格模式

### ISSUE THREAD

**Issue by rexx0520** [nondanee/UnblockNeteaseMusic#37]
如題，請問 docker 容器如何啟動嚴格模式?
謝謝

**Comment by rexx0520** [comment]
能讓 proxy 加個帳號密碼也可以(?

**Comment by nondanee** [comment]
这样就行
```
docker run nondanee/unblockneteasemusic -s
```

是说需要 Basic Authentication 吗？
下次 commit 加上 👌

**Comment by rexx0520** [comment]
多謝
docker 開了一天發現被當成肉雞 嚇死我啦

**Comment by nondanee** [comment]
加了 Authentication 但好像不适配 Windows 客户端设置用户名密码，也不适配 macOS 系统代理
但是我在 Proxy SwitchyOmega 可以用，不知道为什么

**Comment by palfans** [comment]
在Docker-compose 中，新增command即可追加命令
```
Command: "-s"
```
