### ISSUE TITLE
还走P站的？我直接被封了

### ISSUE THREAD

**Issue by Megumiovo** [nondanee/UnblockNeteaseMusic#370]
https://ftp.bmp.ovh/imgs/2020/01/16c8a03e1a9592ca.png

**Comment by Xun66** [comment]
图好像挂了，503

**Comment by nondanee** [comment]
走 P 站啥意思？

**Comment by Megumiovo** [comment]
我在服务器上挂了2天的代理，今天百度云就把我服务器封了
https://imgchr.com/i/1AUXFA

**Comment by Xun66** [comment]
你用的默认代理端口被人扫了？

**Comment by Megumiovo** [comment]
我在服务器上挂了2天的代理，今天百度云就把我服务器封了
https://s2.ax1x.com/2020/01/22/1AUXFA.png

**Comment by nondanee** [comment]
REAMDE 加粗写着

**若将服务部署到公网，强烈建议使用严格模式 (此模式下仅放行网易云音乐所属域名的请求) `-s`  限制代理范围 (需使用 PAC 或 hosts)，~~或启用 Proxy Authentication `-t <name>:<password>` 设置代理用户名密码~~ (目前密码认证在 Windows 客户端设置和 macOS 系统设置都无法生效，请不要使用)，以防代理被他人滥用**

**Comment by Jacky346** [comment]
被人用了吧，，，，

**Comment by Megumiovo** [comment]
我是憨憨 我没注意到
