### ISSUE TITLE
有关音质的问题

### ISSUE THREAD

**Issue by Jacky346** [nondanee/UnblockNeteaseMusic#371]
现在酷我的无损接口是被close了吗，，，好像不是无损的。另外除了酷我咪咕没有提供的了吧。

**Comment by nondanee** [comment]
从来没有说过提供无损，把注释去掉是你自己的事情

酷我 antiserver 这个接口应该是不会给无损的
之前以为 aac 是高品，其实是低品 (和 QQ 的 m4a 一个性质)
