### ISSUE TITLE
没有兼容ipv6吗？

### ISSUE THREAD

**Issue by Adan-bd** [nondanee/UnblockNeteaseMusic#373]
`C:\music>ping music.163.com

正在 Ping bgpv6.music.ntes53.netease.com [2407:ae80:200:1001::20] 具有 32 字节的数据:
来自 2407:ae80:200:1001::20 的回复: 时间=39ms
来自 2407:ae80:200:1001::20 的回复: 时间=40ms
来自 2407:ae80:200:1001::20 的回复: 时间=39ms
来自 2407:ae80:200:1001::20 的回复: 时间=39ms

2407:ae80:200:1001::20 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 39ms，最长 = 40ms，平均 = 39ms

C:\music>node app.js -p 2333 -f 2407:ae80:200:1001::20
Please check the server host.`

![image](https://user-images.githubusercontent.com/37149246/72982340-c943f500-3e19-11ea-8856-9127b177462e.png)

**Comment by nondanee** [comment]
是 `-f ` 参数校验规则不支持 ipv6
https://github.com/nondanee/UnblockNeteaseMusic/blob/e0050253c94d4ece6a2a15af07188d597896d2d6/app.js#L33

程序支不支持我不清楚，应该是支持的，你可以把校验规则先去掉测试一下，我的网没法测

另外，因为你没有改 hosts ，所以不需要设置 `-f` (当然你想设一个也行)

**Comment by Adan-bd** [comment]
试过了，程序是支持ipv6的，只是校验规则只校验了ipv4。

**Comment by nondanee** [comment]
好的，我会加上的

但你这个使用方法其实不用去设 `-f`

**Comment by Adan-bd** [comment]
ok

**Comment by 0blivionU** [comment]
您好，现在ping 网易云 ip 都是ipv6，之前ipv4的配置跑不起来了，请问应该怎么配置，谢谢！
