### ISSUE TITLE
YT音源問題

### ISSUE THREAD

**Issue by kai456789** [nondanee/UnblockNeteaseMusic#375]
已按照步驟申請好API 開通YOUTUBE DATA V3
也在網易雲填入KEY 看日誌 只有出現
MITM > interface.music.163.com 
MITM > interface.music.163.com 
MITM > interface.music.163.com 
沒替換訊息 去看API服務用量有調用到
歌都有解灰色 JOY跟JOLINE的歌都顯示加載失敗

**Comment by nondanee** [comment]
master 分支上有个 bug

这次 commit 导致的 https://github.com/nondanee/UnblockNeteaseMusic/commit/e0050253c94d4ece6a2a15af07188d597896d2d6

因为 querystring 没改
https://github.com/nondanee/UnblockNeteaseMusic/blob/7ded0518904ceda1ee7abfbcd6b54568f02ae5d4/provider/youtube.js#L58

可以先 revert 到 e005025 之前

**Comment by kai456789** [comment]
好的 謝謝 我直接SSH進去修改youtube.js 看看
