### ISSUE TITLE
在vps上安装后8080端口无网络，但是80端口可用

### ISSUE THREAD

**Issue by XrTianMing** [nondanee/UnblockNeteaseMusic#376]
![image](https://user-images.githubusercontent.com/22984778/73283683-7493e600-422e-11ea-9f23-8274353706fe.png)
鄙人小白，未搞懂

**Comment by nondanee** [comment]
如果是比较老的客户端版本，测试代理会有问题 (客户端的 bug)  ，不用管 https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-429514688

新版测试代理没有问题，看你自己的配置

启动程序的时候设置了哪个端口？没设置的话默认是 8080

P.S. VPS 如果有防火墙/安全组之类的记得要配置

**Comment by XrTianMing** [comment]
> 如果是比较老的客户端版本，测试代理会有问题 (客户端的 bug) ，不用管 [#22 (comment)](https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-429514688)
> 
> 新版测试代理没有问题，看你自己的配置
> 
> 启动程序的时候设置了哪个端口？没设置的话默认是 8080
> 
> P.S. VPS 如果有防火墙/安全组之类的记得要配置

8080端口无论是测试和使用都是没有网络的，但是80端口可以，run时使用的是默认的，而且提示也是0.0.0.0:8080，有点迷

**Comment by nondanee** [comment]
浏览器直接访问 http://<你的IP>:8080 看看日志里会不会有 `MITM > null`
