### ISSUE TITLE
大大可以提供API Server吗?

### ISSUE THREAD

**Issue by huulien** [nondanee/UnblockNeteaseMusic#377]

**Comment by nondanee** [comment]
什么 API？

**Comment by huulien** [comment]
> 什么 API？

类似[这个](https://github.com/winterssy/mxget#%E4%BD%9C%E4%B8%BAapi%E6%9C%8D%E5%8A%A1%E9%83%A8%E7%BD%B2)

**Comment by nondanee** [comment]
有桥接用的 server

```sh
node bridge.js # http://127.0.0.1:9000
```

### 支持的 PATH


- /qq/check
- /qq/track
- /xiami/check
- /xiami/track
- /baidu/check
- /kugou/check
- /kugou/search
- /kuwo/check
- /kuwo/track
- /migu/check
- /migu/track
- /joox/check
- /joox/track
- /youtube/check
- /youtube/track

provider 按被墙情况导出方法，需要别的 api 可以自行在 `module.exports = {}` 里增加

参数均写在 url 里，method 不限

### /\<provider\>/check 调用示例
需要参数 info (JSON String)，必须有 keyword
```
/<provider>/check?{"keyword":"笑忘歌 - 五月天"}
```
返回歌曲 url

### /\<provider\>/search 调用示例
需要参数 info，同 /\<provider>\/check
```
/<provider>/search?{"keyword":"笑忘歌 - 五月天"}
```
返回对应平台歌曲 id (JSON String/number/string)

### /\<provider\>/track 调用示例
需要参数平台歌曲 id (JSON String/number/string)
```
/qq/track?{"song":"0034UmOI0ObAqd","file":"001pSSJ10V7r7e"}
/kuwo/track?443605
```
返回歌曲 url
