### ISSUE TITLE
是否对原生ip有限制？

### ISSUE THREAD

**Issue by YLaido** [nondanee/UnblockNeteaseMusic#379]
有两台服务器，一台海外原生ip，另一台是阿里云香港(非原生ip)，使用相同版本(当前最新)相同命令，都用v2ray转发流量，只有原生ip的服务器能播放。

使用的启动命令：
<pre><code>/usr/bin/node /home/UnblockNeteaseMusic/app.js -p 16788 -f 223.252.199.66 -o joox qq kugou kuwo migu > /dev/null &</code></pre>
请问大家有遇到过这个问题吗？

**Comment by nondanee** [comment]
和原不原生没关系
qq kugou kuwo migu 海外不支持
joox 仅香港及东南亚支持

**Comment by YLaido** [comment]
> 和原不原生没关系
> qq kugou kuwo migu 海外不支持
> joox 仅香港及东南亚支持

这个我是知道的，但是joox已经设置为首选，非原生ip还是播放不了。相同环境下变量只有ip了，我试下用国内部署

**Comment by nondanee** [comment]
emmm 不好意思有点激动看反了

感觉和 ip 没太大关系
应该就是没有匹配到，有 log 吗？

可以找某首歌调接口快速测一下

**Comment by YLaido** [comment]
用两首歌试了下，容祖儿的明月和杰伦的床边故事。这是有原生ip的log:
<pre><code>
root@aml:~ # /usr/bin/node /home/UnblockNeteaseMusic/app.js -p 16788 -f 223.252.199.66 -o joox qq kugou kuwo migu
HTTP Server running @ http://0.0.0.0:16788
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
[1379736739] 
https://hk.stream.music.joox.com/M800003XWGig4XOiJK.mp3?vkey=23FA9EC4989A44D81F74E3D48492B269E44CF9DD07359317EA5E974BEB606F68EF325D5DEF3CEC1F4DE40B3BF90E383F&amp;hdnts=exp=1580740229~acl=/*~hmac=7d816d508a41f3fb9298667464ac4393b266a5e12542ee8279856e2b14e201ad&guid=JOOX@WEB_OPENUDID&uin=0&fromtag=8
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
[415792916] 廨¾¹

https://hk.stream.music.joox.com/M800Z55e7403bc1078.mp3?vkey=A0BD46960AC05335BDC8E819362F1482E0B7DC643081A76EABE87DF01E2FFB7600BFF9A555E9A79A3B389CE3EA681E70&amp;hdnts=exp=1580740305~acl=/*~hmac=a7aa575e441c50e1ba1c0b9e0d996af41190c9baff88839d4a28e8b51e66b0a5&guid=JOOX@WEB_OPENUDID&uin=0&fromtag=8

</code></pre>

阿里香港，非原生ip：
<pre><code>
root@HK:~/UnblockNeteaseMusic # /usr/bin/node /root/UnblockNeteaseMusic/app.js -p 10988 -f 59.111.181.35 -o joox qq kugou kuwo migu
HTTP Server running @ http://0.0.0.0:10988
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > clientlog.music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
</code></pre>

看来可能是joox过滤了非原生ip，目前办法只能是用原生ip再中转一次流量了

**Comment by nondanee** [comment]
我试了下没问题，那可能是网段没识别到吧？
阿里云轻量香港

![image](https://user-images.githubusercontent.com/26399680/73664025-a3e89e00-46d9-11ea-803f-b73a4978ec20.png)

**Comment by YLaido** [comment]
还是感觉跟ip有关，轻量hk是有部分原生ip的，我用的ecs在ytb上连taylor swift的mv都看不了

**Comment by nondanee** [comment]
那应该是的，joox 的限制
