### ISSUE TITLE
安卓客户端使用咪咕音源可播放无法下载

### ISSUE THREAD

**Issue by alex4ord** [nondanee/UnblockNeteaseMusic#380]
网易云安卓客户端，版本号：v7.0.10.008245
非本项目，但是原理与本项目相同。
在使用咪咕音源时，客户端可以播放，但是无法下载。
提示下载失败，服务器错误。

测试音乐，周杰伦的蓝色风暴，专辑十一月的萧邦。
win端客户端没有下载问题。

返回给安卓客户端的数据如下
```
{"Id":"185905","Size":37115003,"Br":999000,"Url":"http://tyst.migu.cn/public/ringmaker01/n17/2017/07/%E6%97%A0%E6%8D%9F/2009%E5%B9%B406%E6%9C%8826%E6%97%A5%E5%8D%9A%E5%B0%94%E6%99%AE%E6%96%AF/flac/%E8%93%9D
%E8%89%B2%E9%A3%8E%E6%9A%B4-%E5%91%A8%E6%9D%B0%E4%BC%A6.flac","Md5":"183e3bbcedcf85ae4e82e1760c7671f4","Name":"蓝色风暴","Artist":"周杰伦","MatchScore":1}
```

经过手动下载文件，测试md5和size并无错误。

猜想，安卓客户端下载强制https？

**Comment by alex4ord** [comment]
刚刚测试了一下，本项目的咪咕音源在新版按照客户端也是只能试听无法下载

**Comment by nondanee** [comment]
v7.0.10.008245
测了下酷我，也是 http 的地址，强制 https 也访问不了，但下载正常，所以没有强制 https

查了下原因是 migu 链接在 range request 时返回状态码是 200 不是 206，网易云客户端认为服务器出错

**Comment by alex4ord** [comment]
我的项目经过相同修改后，目前安卓客户端可以开始进行下载，当进度条到达100%后提示下载失败。
我想请教一下，这种情况会是什么原因导致的？

将浏览器进行相同代理后，chrome对咪咕音乐的链接进行下载，下载速度极快。但是网易云安卓客户端下载速度却极慢，会有什么可能的原因？

上面这一些都非本项目，本项目测试后完美运行

**Comment by nondanee** [comment]
我之前遇到过的下载失败的原因是 md5 对不上和返回的 type 有问题 (flac 返回了 mp3)

不知道原因

你是说浏览器直接打开链接吗？
如果你按我这样改的话，代理应该是不会处理浏览器这个请求的
直接打开链接，浏览器不会主动 range request 的
就不能放一起比了

**Comment by alex4ord** [comment]
浏览器的处理我是返回200，下载速度极快,1M/s-3M/s
网易云客户端的处理修改为206，下载速度慢的一批，300k/s-1M/s左右

md5我再详细测试一下

**Comment by nondanee** [comment]
那就不清楚了，刚试了下我这边下载还挺快的==

**Comment by alex4ord** [comment]
我搞定了，是md5的原因，是flac有30多M，按我说的下载速度1M/s来算，对咪咕flac的md5计算需要30秒所有，所以这就很麻烦了

**Comment by alex4ord** [comment]
一开始是md5计算错误，现在是不知道该怎么处理网易云获取md5需要等待30秒然后超时报错

**Comment by nondanee** [comment]
我觉得让用户手动触发重新下载就行了

或者你试试先把 状态码和响应头 write 给客户端，body 挂起等到计算完再 write，不知道这样会不会触发超时

**Comment by alex4ord** [comment]
测试了先发送header，然后body等计算完md5再发送。
在等待的过程中，网易安卓客户端应该是超时了，总共发起3次尝试都没获得body后就显示下载失败了。

**Comment by nondanee** [comment]
那没有办法，让用户触发，md5 结果缓存一下就行了
