### ISSUE TITLE
download migu music error

### ISSUE THREAD

**Issue by Jacky486** [nondanee/UnblockNeteaseMusic#381]
依旧无法下载咪咕音乐(即使代理咪咕域名），pull了最新的代码12min ago

**Comment by nondanee** [comment]
只有对网易云全局代理才会生效
如果有用规则代理，记得把 tyst.migu.cn 加到规则里
或者用 `-e http://music.163.com` 将所有音频请求打到代理上

**Comment by alex4ord** [comment]
Question: http CONNECT 全部返回 `HTTP/1.0 200 Connection Established\r\n\r\n` 这个逻辑有问题吗？

目前我按照新思路将response的statuscode重设为206，但是发现安卓端在对  tyst.migu.cn 发起CONNECT请求时就出错了

**Comment by nondanee** [comment]
@alex4ord 
没问题，协议规范 https://tools.ietf.org/html/draft-luotonen-web-proxy-tunneling-01#section-3.2

**Comment by Jacky486** [comment]
> Question: http CONNECT 全部返回 `HTTP/1.0 200 Connection Established\r\n\r\n` 这个逻辑有问题吗？
> 
> 目前我按照新思路将response的statuscode重设为206，但是发现安卓端在对 tyst.migu.cn 发起CONNECT请求时就出错了

-e http://music.163.com这个可行
