### ISSUE TITLE
Docker 镜像更新

### ISSUE THREAD

**Issue by Qusic** [nondanee/UnblockNeteaseMusic#382]
https://hub.docker.com/r/nondanee/unblockneteasemusic
最后一次是2月前了，也许可以配个 travis 或者 github actions 之类的？

**Comment by nondanee** [comment]
有 travis ci 的
只是我一直没有 release 😅

**Comment by nondanee** [comment]
release 了
对了，我这边打镜像是用 dockerhub 的 ci，travis 只用来发 npm 包
