### ISSUE TITLE
ipad 连上代理后，播放失败，会提示网络不给力，无法继续播放

### ISSUE THREAD

**Issue by heyitong0929** [nondanee/UnblockNeteaseMusic#383]
ipad 连上代理后，播放失败，会提示网络不给力，无法继续播放
我看日志返回的链接，电脑上能够打开播放
[28793787] 白头吟
http://nc01.sycdn.kuwo.cn/067de92c4e14a7f88d280066317077df/5e3d14b9/resource/n1/45/36/2715345927.mp3

在这之前是可以的，是什么问题呢

**Comment by heyitong0929** [comment]
不好意思 我开了严格模式了。。换种启动方式就可以了

**Comment by nondanee** [comment]
👌
