### ISSUE TITLE
酷狗音源匹配问题

### ISSUE THREAD

**Issue by 1715173329** [nondanee/UnblockNeteaseMusic#385]
目前很多歌会自动匹配到伴奏版本上面，例如周董的歌，牛奶咖啡的蝶恋花等等

**Comment by nondanee** [comment]
这个已知 BUG 啊 https://github.com/nondanee/UnblockNeteaseMusic/issues/30#issuecomment-517984439
有什么问题吗？
或者说你有什么改进意见吗？

**Comment by 1715173329** [comment]
好吧，没看到，抱歉（
