### ISSUE TITLE
按照教程配置，网易云 2.3.2 (832)无法使用

### ISSUE THREAD

**Issue by finalxcode** [nondanee/UnblockNeteaseMusic#386]
系统：mac 10.14
网易云 ： 2.3.2 (832)
启动方式： node app.js
代理使用：proxifier
自签证书：https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-477870013 已经按照这个文章做了，且覆盖了UnblockNeteaseMusic 中的证书文件，并信任了

配置：
使用pac 方式， http://127.0.0.1:8090/proxy.pac

下面是环境的截图：

<img width="998" alt="screenshot_04" src="https://user-images.githubusercontent.com/6211616/74211907-e6f3d400-4ccc-11ea-894d-b9bb83dc2d9e.png">

<img width="745" alt="screenshot_05" src="https://user-images.githubusercontent.com/6211616/74211979-24f0f800-4ccd-11ea-9642-2369efafde09.png">

<img width="801" alt="screenshot_07" src="https://user-images.githubusercontent.com/6211616/74211990-30dcba00-4ccd-11ea-81ea-3018239e2b0d.png">

<img width="527" alt="screenshot_08" src="https://user-images.githubusercontent.com/6211616/74212120-a779b780-4ccd-11ea-9a2d-43c123857266.png">

结果：之前无法听灰色歌曲，依然无法是灰色

**Comment by nondanee** [comment]
需要加上 com.apple.WebKit.Networking 
原因见 https://github.com/nondanee/UnblockNeteaseMusic/issues/91#issuecomment-492925551

可以只用域名匹配，参考
https://github.com/nondanee/UnblockNeteaseMusic/issues/338#issuecomment-565931815 https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-436505087

或者咨询 @gqbre

**Comment by du5** [comment]
Surge 为所欲为！
![image](https://user-images.githubusercontent.com/54979375/74231936-b62e9180-4d02-11ea-9c81-70815ba770d5.png)

**Comment by finalxcode** [comment]
@nondanee  修改为下图之后是一样的结果
<img width="837" alt="screenshot_12" src="https://user-images.githubusercontent.com/6211616/74295804-04807680-4d7d-11ea-9ca2-988bdac061b0.png">

**Comment by finalxcode** [comment]
> Surge 为所欲为！

好厉害的样子

**Comment by nondanee** [comment]
@finalxcode 
我没看懂啊==

全局代理/PAC 代理都是系统偏好里的吧？
建议不要和 proxifier 混着用

还有 *music.126.net 是不用过代理的

**Comment by finalxcode** [comment]
> @finalxcode
> 我没看懂啊==
> 
> 全局代理/PAC 代理都是系统偏好里的吧？
> 建议不要和 proxifier 混着用
> 
> 还有 *music.126.net 是不用过代理的

我现在都是走的代理

**Comment by nondanee** [comment]
@finalxcode 
还是用的 proxifier 吗？

**Comment by jovechina** [comment]
系统：mac 10.15.3
网易云 ： 2.3.2 (832)
启动方式： node app.js
代理使用：proxifier
自签证书：#48 (comment) 已经按照这个文章做了，且覆盖了UnblockNeteaseMusic 中的证书文件，并信任了

配置：
使用proxifier方式

下面是环境的截图：
![image](https://user-images.githubusercontent.com/8078116/77735636-46742c00-704e-11ea-85c5-a9490c5c9b9b.png
![image](https://user-images.githubusercontent.com/8078116/77735726-6572be00-704e-11ea-96b0-033fa0d615ab.png)
![image](https://user-images.githubusercontent.com/8078116/77735783-7cb1ab80-704e-11ea-806c-71302392f1ef.png)
![image](https://user-images.githubusercontent.com/8078116/77735827-8e934e80-704e-11ea-91f9-fce71c971a74.png)

**Comment by nondanee** [comment]
@jovechina 
看 log 是没信任，给浏览器应用代理打开网易云官网测试一下

**Comment by jovechina** [comment]
和 #458 是同样的问题，信任了但是证书无效。
我试试 #458 的解决方案是不是同样可以解决这个问题。
