### ISSUE TITLE
无法运行项目

### ISSUE THREAD

**Issue by zack66** [nondanee/UnblockNeteaseMusic#387]
![FB2681AA-22F0-4DF4-8FF2-C6E5AFEB15D0](https://user-images.githubusercontent.com/16634459/74373188-eff0bc80-4e16-11ea-8047-2d23ddee8b3b.jpeg)
如图，求解答！ 以前可以直接运行

**Comment by tabjy** [comment]
@zack66 `node` 版本检查一下。看起来这个这个版本连 ES6 语法都不支持。建议升级到最新的 LTS 版本。

**Comment by nondanee** [comment]
对的，版本太低了

`node -v` 可以看版本

6 以上就行了
