### ISSUE TITLE
http proxy 可以加认证 (proxy authentication) 

### ISSUE THREAD

**Issue by wo2429** [nondanee/UnblockNeteaseMusic#388]
http proxy 可以加认证 (proxy authentication) 

这个认证怎么开启     比较小白了

**Comment by wo2429** [comment]
好了 好了 问题删掉吧    我加了-s   我说怎么没网

**Comment by nondanee** [comment]
README 里写了 `-t <name>:<password>` 且注明了有问题
应该大部分情况都用不了，你试试看吧，如果能用也可以分享下

底下 "Close issue" 你可以自己点的

**Comment by qy2009** [comment]
@wo2429 能告诉下我你是怎么弄好用户名和密码的嘛？谢谢
