### ISSUE TITLE
灰色歌曲可以点击但是播放失败？

### ISSUE THREAD

**Issue by cesaryuan** [nondanee/UnblockNeteaseMusic#39]
![image](https://user-images.githubusercontent.com/35998162/51579387-c27b5d00-1efb-11e9-9d30-2f1ae0a23471.png)
![image](https://user-images.githubusercontent.com/35998162/51579516-3453a680-1efc-11e9-8d2f-26ecf71eecb5.png)

如图，虽然可以点击灰色歌曲，但还是在加载几秒后跳到下一首歌曲；或者是直接提示加载失败

**Comment by cesaryuan** [comment]
> @cesaryuan 我剛剛試了沒問題
> 你是用最新版本的code嗎

是最新版本，源应该是没有问题，我试了一下那个链接是可以下载的，就是不知道为什么在网易云里播放不了，你网易云是什么版本
![image](https://user-images.githubusercontent.com/35998162/51582051-6ae1ef00-1f05-11e9-8cb4-916aa2ec67c5.png)

**Comment by theandychung** [comment]
v2.5.0 windows 10, host 修改

**Comment by cesaryuan** [comment]
> v2.5.0 windows 10, host 修改
> 我播放時所得到的QQ連結跟你一樣

难道是我网易云版本的原因，我的是2.5.2，其他环境和你一样，我hosts和代理方式都试了，但是都不行

**Comment by nondanee** [comment]
把 stream.music.tc.qq.com 那个地址复制出来打开看看

**Comment by nondanee** [comment]
#35 或许是因为 vkey

**Comment by cesaryuan** [comment]
> 你说音源没问题
> 那么两个地方可以尝试一下
> 
> [UnblockNeteaseMusic/provider/match.js](https://github.com/nondanee/UnblockNeteaseMusic/blob/0193a1d110a09c05a9a7e0ef8edcd8adbf7b9665/provider/match.js#L41)
> 
> Line 41 in [0193a1d](/nondanee/UnblockNeteaseMusic/commit/0193a1d110a09c05a9a7e0ef8edcd8adbf7b9665)
> 
>  return request('HEAD', url) 
> 
> 这一行的 HEAD 改成 GET 看看
> [UnblockNeteaseMusic/hook.js](https://github.com/nondanee/UnblockNeteaseMusic/blob/0193a1d110a09c05a9a7e0ef8edcd8adbf7b9665/hook.js#L225)
> 
> Line 225 in [0193a1d](/nondanee/UnblockNeteaseMusic/commit/0193a1d110a09c05a9a7e0ef8edcd8adbf7b9665)
> 
>  item.url = `http://music.163.com/package/${crypto.base64.encode(song.url)}/${item.id}.mp3` 
> 
> 直接 item.url = song.url

我试了一下，将HEAD改为GET就可以了。这是为什么，为什么其他人不需要改？

**Comment by nondanee** [comment]
HEAD 改成 GET 以后 log 还是 stream.music.tc.qq.com 这个地址吗？

**Comment by cesaryuan** [comment]
> HEAD 改成 GET 以后 log 还是 stream.music.tc.qq.com 这个地址开头吗？

变成了这个 http://192.168.73.134/streamoc.music.tc.qq.com

**Comment by nondanee** [comment]
嗯，按照标准 HEAD 和 GET 得到的 headers 应该是一样的，可以理解 HEAD 是没有 body 的 GET
但实际情况不一定，看 server 具体实现
就像你遇到的 HEAD 的返回结果没有表明需要重定向（没有 location 字段）
而 GET 的返回结果表明有重定向（有 location 字段）

那个播放地址是包装了一层的，包装在 music.163.com 里面
`http://music.163.com/package/${crypto.base64.encode(song.url)}/${item.id}.mp3`
代理之后的 location 会因为是在原来的虚拟 host 基础上做重定向，可能出问题
或者播放器完全不支持重定向也有可能，内部怎么样的我也不知道

至于不把 HEAD 换成 GET 的原因，个人感觉 GET 会浪费资源，虽然在 nodejs 上实现的效果一样，但是底层进入网络栈的数据可能会变多，就没必要了。
