### ISSUE TITLE
周杰伦一些歌曲在网页版里可以听,为什么不走网页版？

### ISSUE THREAD

**Issue by jiyiv5** [nondanee/UnblockNeteaseMusic#391]
比如这首歌曲 [https://music.163.com/#/song?id=34167344&userid=102064458](眼泪成诗(Live)) 在网页版里可以听,我看程序日志却没有走网页版的,为什么不走网页版呢？

**Comment by nondanee** [comment]
你想解决的问题是什么？是说网页版能听的歌客户端不能听吗？

我测过了，你给的那首歌在客户端本来就能听啊！

**Comment by jiyiv5** [comment]
> 你想解决的问题是什么？是说网页版能听的歌客户端不能听吗？
> 
> 我测过了，你给的那首歌在客户端本来就能听啊！

emm..我搭建你的这个程序,我用苹果手机测试的,这首歌走的是酷我音乐的,正常客户端我没看。所以疑问的过来问问你

**Comment by nondanee** [comment]
能复现吗？
log 里的歌曲 id 和你链接里是一样的吗？
最好能贴截图

代码的逻辑是能听的歌不会走匹配

你的代码是仓库拉的源码或者我发布的 docker / npm 吗？有没有做过类似强制高音质的 hack？

**Comment by jiyiv5** [comment]
> 能复现吗？
> log 里的歌曲 id 和你链接里是一样的吗？
> 最好能贴截图
> 
> 代码的逻辑是能听的歌不会走匹配
> 
> 你的代码是仓库拉的源码或者我发布的 docker / npm 吗？有没有做过类似强制高音质的 hack？

是直接拉的仓库,复现貌似不能了,我又重装了系统。。。

歌曲ID我不知道,我改了hook代码（ item.url = song.url ）

上面那个ID是我在网易云分享复制的链接。

**Comment by nondanee** [comment]
没法复现就比较难找了

改那个地方没影响

程序逻辑是能听的歌不会走匹配的
可以 review 代码，能听的歌 code 会是 200

https://github.com/nondanee/UnblockNeteaseMusic/blob/1251b9d96826ce5bb63131d0f18696253ec02127/src/hook.js#L279
