### ISSUE TITLE
ios使用出现问题

### ISSUE THREAD

**Issue by mw418** [nondanee/UnblockNeteaseMusic#392]
大佬，这个项目我试过好多次，最后还是没弄出来
http代理可以在pc上使用，可以ios wifi设置代理使用
通过ios代理软件qx使用失败  已经安装证书(github上的 )  
尝试使用goproxy/glider 转换成ss代理 在软件上使用  依旧不行
问题都是歌曲不再是灰色 但是放不出来  长时间转圈圈 网络不给力 阿里云深圳学生机 

我最大可能是哪里搞错了呢？

**Comment by nondanee** [comment]
启动参数是什么？有没有加上 `-e`，没有加的话加一下 `-e http://music.163.com`

**Comment by mw418** [comment]
> 启动参数是什么？有没有加上 `-e`，没有加的话加一下 `-e http://music.163.com`

pm2 start app.js --name UnblockNeteaseMusic--s -e https://music.163.com -p 8080：8081

**Comment by nondanee** [comment]
格式有点问题
是这样的吗？
```
pm2 start app.js --name UnblockNeteaseMusic -- -s -e https://music.163.com -p 8080:8081
```

**Comment by mw418** [comment]
> 格式有点问题
> 是这样的吗？
> 
> ```
> pm2 start app.js --name UnblockNeteaseMusic -- -s -e https://music.163.com -p 8080:8081
> ```

是这样的  刚才是翻译插件导致的  我可能是http转换ss出问题了

**Comment by nondanee** [comment]
可以把 `-s` 去掉试试

**Comment by mw418** [comment]
> 可以把`-s`去掉

试过了
shadowrocket  无论是http还是转换ss都可以用
quantumultx  无论是http还是ss都失败了

**Comment by nondanee** [comment]
emmm 那就不知道了==

**Comment by mw418** [comment]
谢谢你的帮助
