### ISSUE TITLE
歌曲名称在哪

### ISSUE THREAD

**Issue by jiyiv5** [nondanee/UnblockNeteaseMusic#394]
请问一下怎么变更歌曲的名称？比如一些灰色歌曲名字更改一下,在以前加一个符号,用于识别那些歌曲是原本不能听的

**Comment by nondanee** [comment]
https://github.com/nondanee/UnblockNeteaseMusic/blob/586d043806ed8885319d9fcb4806cd05dfa71f09/src/hook.js#L157-L170

用 `JSON.stringify` 的 `replacer` 来改

识别下歌曲对象的结构，然后把 `value.name` 改掉

**Comment by jiyiv5** [comment]
> https://github.com/nondanee/UnblockNeteaseMusic/blob/586d043806ed8885319d9fcb4806cd05dfa71f09/src/hook.js#L157-L170
> 
> 用 `JSON.stringify` 的 `replacer` 来改
> 
> 识别下歌曲对象的结构，然后把 `value.name` 改掉

好的 谢谢。
