### ISSUE TITLE
IOS最新版本好像有点问题

### ISSUE THREAD

**Issue by sppsun** [nondanee/UnblockNeteaseMusic#396]
IOS刚更新了7.0.10，有些歌曲变灰色了，比如周的《说好不哭》，以前旧版本是正常的，我的启动参数如下：
npx @nondanee/unblockneteasemusic -p 8090:1080 -e https://music.163.com -s
大佬帮忙指点下原因，谢谢～

**Comment by nondanee** [comment]
`-e` 使用 `http://music.163.com` 并且去掉 `-s` 试一下

对 iOS 端支持我一直不太清楚 (没有 iOS 设备)，可以去 #65 问一下其他人

**Comment by sppsun** [comment]
刚试了，还是不行，我去65问下，谢谢啦～

**Comment by Xun66** [comment]
我这里7.0.10播放尚正常(已清理过缓存)，我刚刚更新了 #368 ，看看能不能帮到你？

**Comment by sppsun** [comment]
@Xun66 非常感谢您的回复，我目前也使用了与您同样的配置，但是好像还是有问题。
下面是我的配置：
启动：npx @nondanee/unblockneteasemusic -p 8090 -e https://mydomain.com -s
手机端配置代理：http://mydomain.com:8090/proxy.pac
nginx转发也参照65进行了设置，不知道哪里还没设置正确。
谢谢。

**Comment by Xun66** [comment]
是一部分无版权可以点亮，一部分无版权没点亮吗？如果是都不亮，看起来应该是请求被直连了。如果是前者不太好办，如果是后者，控制台日志什么反应？也可以用通信嗅探软件确认一下

**Comment by sppsun** [comment]
@nondanee 您好哈，还没睡么，都是夜猫子～
刚才通过Shadowrocket的方式成功了，但是通过WLAN 代理的方式还是不行。。。
WLAN 代理方式时我测试了周的《说好不哭》一直是暗的，看了下unblockneteasemusic的日志，貌似请求也都到了，但是好像nginx反向代理没什么反应，不知道您是否测试过WLAN 代理方式。
谢谢。

**Comment by nondanee** [comment]
@sppsun 
歌曲是暗的话请求没到代理上==

**Comment by Xun66** [comment]
测试了下WLAN PAC，这边正常。歌曲亮起，控制台日志，反代反应都与shadowrocket无异。建议浏览器下载proxy.pac看下代理脚本是否正常。如果还是不行可以用Thor等软件抓包看下。

**Comment by sppsun** [comment]
@nondanee 好的，谢谢～

**Comment by Ladding** [comment]
感谢，终于能放了
