### ISSUE TITLE
增加Proxy Authentication功能

### ISSUE THREAD

**Issue by qy2009** [nondanee/UnblockNeteaseMusic#397]
能增加这个功能嘛?我想部署在公网,这样我可以在路上用手机听..这样子最省事..不用设置shadowrocket...谢谢

**Comment by nondanee** [comment]
目前有这个功能，README 里有写
但我自测好像不可用，已在 "已知 BUG" 里注明了 https://github.com/nondanee/UnblockNeteaseMusic/issues/30#issuecomment-455782470
你可以问问 #388 的老哥
