### ISSUE TITLE
找到一个ios手机端直接可用的pac，不知道是什么原理

### ISSUE THREAD

**Issue by zhouchangyi** [nondanee/UnblockNeteaseMusic#398]
https://wy.ydlrqx.com/proxy.pac
这个pac，iphone无需做其他配置即可听网易云，试了周杰伦，都可以。不知道是什么道理，哪位大大研究一下

**Comment by Cloud370** [comment]
> https://wy.ydlrqx.com/proxy.pac
> 这个pac，iphone无需做其他配置即可听网易云，试了周杰伦，都可以。不知道是什么道理，哪位大大研究一下

我刚才在b站刷到了一个解锁教程的视频，几w播放量 感觉要出事 这也太不安全了8 但是他那个还是改进版的

**Comment by nondanee** [comment]
@zhouchangyi 
我没 iOS 设备，就用 PAC 里的 ip 在 pc 端试了下，随便挑了几首，都没有匹配结果，没法进一步测试
可能对 iOS 端请求有筛选吧，我不知道

本来就可以做到设备上不装证书的，有公网 https endpoint 就行了

我看灰色歌曲歌名都有 ★ 标记，可能和 #394 的 @jiyiv5 大佬会有关系吧
看了眼他也在用证书，证书署名是 YeShengJi_WangYiMusic

来源未知的代理尽量别用，README 里加粗写着，对自己负责

**Comment by jiyiv5** [comment]
> @zhouchangyi
> 我没 iOS 设备，就用 PAC 里的 ip 在 pc 端试了下，随便挑了几首，都没有匹配结果，没法进一步测试
> 可能对 iOS 端请求有筛选吧，我不知道
> 
> 本来就可以做到设备上不装证书的，有公网 https endpoint 就行了
> 
> 我看灰色歌曲歌名都有 ★ 标记，可能和 #394 的 @jiyiv5 大佬会有关系吧
> 看了眼他也在用证书，证书署名是 YeShengJi_WangYiMusic
> 
> 来源未知的代理尽量别用，README 里加粗写着，对自己负责

灰色歌曲歌名都有 ★ 标记和我没关系,我还没写。。。关于灰色歌曲歌名标记 ★ 的我是看别人[ 野生技 ]这样弄的,觉得可以搞一下,由于一些原因没搞了。

**Comment by Cloud370** [comment]
> > @zhouchangyi
> > 我没 iOS 设备，就用 PAC 里的 ip 在 pc 端试了下，随便挑了几首，都没有匹配结果，没法进一步测试
> > 可能对 iOS 端请求有筛选吧，我不知道
> > 本来就可以做到设备上不装证书的，有公网 https endpoint 就行了
> > 我看灰色歌曲歌名都有 ★ 标记，可能和 #394 的 @jiyiv5 大佬会有关系吧
> > 看了眼他也在用证书，证书署名是 YeShengJi_WangYiMusic
> > 来源未知的代理尽量别用，README 里加粗写着，对自己负责
> 
> 灰色歌曲歌名都有 ★ 标记和我没关系,我还没写。。。关于灰色歌曲歌名标记 ★ 的我是看别人[ 野生技 ]这样弄的,觉得可以搞一下,由于一些原因没搞了。

原来是这样 这个规则在b站和酷安都有人说他是原作者。。。。

**Comment by jiyiv5** [comment]
> > > @zhouchangyi
> > > 我没 iOS 设备，就用 PAC 里的 ip 在 pc 端试了下，随便挑了几首，都没有匹配结果，没法进一步测试
> > > 可能对 iOS 端请求有筛选吧，我不知道
> > > 本来就可以做到设备上不装证书的，有公网 https endpoint 就行了
> > > 我看灰色歌曲歌名都有 ★ 标记，可能和 #394 的 @jiyiv5 大佬会有关系吧
> > > 看了眼他也在用证书，证书署名是 YeShengJi_WangYiMusic
> > > 来源未知的代理尽量别用，README 里加粗写着，对自己负责
> > 
> > 
> > 灰色歌曲歌名都有 ★ 标记和我没关系,我还没写。。。关于灰色歌曲歌名标记 ★ 的我是看别人[ 野生技 ]这样弄的,觉得可以搞一下,由于一些原因没搞了。
> 
> 原来是这样 这个规则在b站和酷安都有人说他是原作者。。。。

他搞得解锁网易云比我自己搞得好太多了,我自己搞得,用了几天就不能用了,我还用了https转发。

**Comment by nondanee** [comment]
@jiyiv5 @Cloud370 
ok 知道了

不过我刚试了 117.28.121.98:19959 和 106.52.127.72:19951 都没匹配结果，不太清楚

[野生技] 是个啥？社区吗？我没搜到
你让那个大佬来 PR 吧，非常欢迎的

**Comment by jiyiv5** [comment]
> @jiyiv5 @Cloud370
> ok 知道了
> 
> 不过我刚试了 117.28.121.98:19959 和 106.52.127.72:19951 都没匹配结果，不太清楚
> 
> [野生技] 是个啥？社区吗？我没搜到
> 你让那个大佬来 PR 吧，非常欢迎的

一个微信公号。

**Comment by nondanee** [comment]
@jiyiv5 好的

**Comment by jiyiv5** [comment]
> @jiyiv5 @Cloud370
> ok 知道了
> 
> 不过我刚试了 117.28.121.98:19959 和 106.52.127.72:19951 都没匹配结果，不太清楚
> 
> [野生技] 是个啥？社区吗？我没搜到
> 你让那个大佬来 PR 吧，非常欢迎的

大佬,我想问一下。我根据 #65 这个用宝塔搭建的。也用了Https转发,第一天好好的,第二天就提示 网络有问题。这是怎么回事？

**Comment by nondanee** [comment]
@jiyiv5 
建议用证书，只用证书可以吗？
不清楚，可以帮忙查一下，但也不保证以后一定可用，你邮件联系我好了

**Comment by jiyiv5** [comment]
> @jiyiv5
> 建议用证书，只用证书可以吗？
> 不清楚，可以帮忙查一下，但也不保证以后一定可用，你邮件联系我好了

emm...没弄证书。。。。请问一下,你的邮件多少？

**Comment by nondanee** [comment]
@jiyiv5 
Github profile 里，点头像进去就能看见了

**Comment by Xun66** [comment]
> https://wy.ydlrqx.com/proxy.pac
> 这个pac，iphone无需做其他配置即可听网易云，试了周杰伦，都可以。不知道是什么道理，哪位大大研究一下

* 他在PAC里加了几条域名和IP规则，都指向106.52.127.72:19951，这个服务器开启了严格模式，命中真白名单以外的网站还会显示一句提示`<body>野生技提示:请不要使用全局代理或者直接填写IP地址。<br />请使用配置自动代理https://wy.ydlrqx.com/proxy.pac<br /></body>`。
* 他的服务器也配了自签名证书的，签发者署名是YeShengJi_WangYiMusic
* 从endpoint来看，服务器似乎不是配置的这个项目。他的无版权歌曲都解析到了网易云自己的曲库里去了(好像主要是m7.music.126.net)，没有看到第三方endpoint。所以好像是他用了一些方法，把被网易隐藏的歌曲链接都挖出来了。感觉非常厉害，大佬可以再细看看吗？@nondanee

一些无版权歌曲收到的URL(因为含时间戳，可能过段时间就不能访问了)：
「床边故事」  http://m7.music.126.net/20200223003129/eae73cd68e332f6580e6d27973a772c9/ymusic/NQSV7OH7xqKSQyM-kjOzWA==/509951162829510354
「청춘 (Rock Ver.)」   http://m7.music.126.net/20200223003959/1cea337881448daad23747496610cda0/ymusic/PKLWy3kuLSwGP3WiZRkcrQ==/509951163071660190
「걱정말아요 그대」   http://m7.music.126.net/20200223004043/9265c9807a4ba56995076b6e48a1369a/ymusic/jAga5Wl_HPoRrs43U9p1tw==/509951163064179908
「体面（于文文）」  
http://m7.music.126.net/20200223004133/a0be10cd2f7f89a838448c4c65733acb/ymusic/Lef3a6GZ95o2vih1qTbX2g==/509951163067772262
「当真（蒋蒋 / 曲肖冰）」   
http://m7.music.126.net/20200223004251/4117aa4231d3d3ce882de23007e57746/ymusic/QaUWiF43hAkMwFiIPCe16Q==/509951162969813267
「突然好想你（五月天）」  
http://m7.music.126.net/20200223004639/e4abce57e4a9ca6a6d105515a9768d12/ymusic/10b5/3eef/bfc2/48c02af5e9ce8e11fc9a8f2813ed7e1d.mp3

**Comment by Xun66** [comment]
我是用Mac 网易云测试的，得到了上述结果。ios上也能正常使用，区别只是这些地址的域名变成了ip。这个是什么原理啊，感到害怕。我想过也有可能是链到了网易云的音乐网盘的资源地址，但是觉得这工作量好像有点太大了吧？
附上播放列表截图一张，
<img width="1002" alt="加载的情况" src="https://user-images.githubusercontent.com/26293463/75095836-23300a00-55d4-11ea-93ca-d5a0eab7cea8.png">

**Comment by nondanee** [comment]
@Xun66 
看了，有限制客户端访问石锤
原理不一样，不是匹配的，用 id 直达

是网易云自己的资源
509951162829510354 类似 dfsId，猜测链接(包括时间校验)是直接生成的应该
我做不到==

**Comment by Xun66** [comment]
现在有已知接口能拿到这个id吗，还是说这是调用了隐藏接口？
另外想问下大佬  现在有什么比较相对弱耦合一点的eapi加解密模块吗，我想初步看下网易云的通信格式，js和py都可以

**Comment by nondanee** [comment]
@Xun66 
猜错了，那个地址应该是云盘的==

**Comment by nondanee** [comment]
@Xun66 
我按匹配结果传了几首到云盘

「525239752 体面（于文文）」
用的是 qq 音乐的文件 
http://dl.stream.qqmusic.qq.com/M500001kMEcr1vxQW0.mp3?vkey=
最后播放出来这首的 id 和你贴的一样的 (md5 应该是一样的)
.../ymusic/Lef3a6GZ95o2vih1qTbX2g==/509951163067772262

应该就是云盘了
不是 hack 的，放心了
实话说我之前没见过云盘的那种地址==
id 我也不知道哪个接口有，应该是不会有的

嗯......以后可以考虑尝试一下自动传云盘的功能~~~
(估计逻辑会是 md5 能匹配上直接云盘喜+1)

**Comment by nondanee** [comment]
加解密的问题，我感觉不耦合啊

**Comment by Xun66** [comment]
> @Xun66
> 加解密的问题，感觉不耦合啊
> 
> crypto.js 里 eapi 就这些
> 
> https://github.com/nondanee/UnblockNeteaseMusic/blob/436046c63b1d985c62e6695beaa21672423a747a/src/crypto.js#L3-L37

原来最简单的就在这个项目里…我之前看一些别的同类项目，加解密和项目其他功能耦合度较高，想分离出来觉得麻烦一直在拖。我抽空看一下，感谢！

**Comment by Forward233** [comment]
> https://wy.ydlrqx.com/proxy.pac
> 这个pac，iphone无需做其他配置即可听网易云，试了周杰伦，都可以。不知道是什么道理，哪位大大研究一下



> https://wy.ydlrqx.com/proxy.pac
> 这个pac，iphone无需做其他配置即可听网易云，试了周杰伦，都可以。不知道是什么道理，哪位大大研究一下

请问这个pac连接怎么用呢 配在哪里呢？

**Comment by Forward233** [comment]
> https://wy.ydlrqx.com/proxy.pac
> 这个pac，iphone无需做其他配置即可听网易云，试了周杰伦，都可以。不知道是什么道理，哪位大大研究一下

请问这个pac连接怎么用呢 配在哪里呢？

**Comment by nondanee** [comment]
@Forward233 
不是

从 "配在客户端的代理中" 可以看出你在用 windows 客户端，你填的这个 PAC 限制了只为 macOS/iOS 的客户端匹配，所以不会有效果

另外，这个 PAC 地址不是我提供的哦

README 里加粗写着 
**警告：本项目不提供线上 demo，请不要轻易信任使用他人提供的公开代理服务，以免发生安全问题**

如果你对本项目不是特别了解，建议先读 README 和 #22

**Comment by Forward233** [comment]
@nondanee 

了解了 ，谢谢大佬指点和提醒 ღ

**Comment by nondanee** [comment]
@zhouchangyi 
@Cloud370 
@jiyiv5 

结案了

测试了一下，没有本人的 cookie 应该是不能访问账号的云盘歌曲的
个人观点(可能不对)是代理内登了一(或几)个"云盘资源极全"的账号，具体是手动传的还是自动化的不太清楚
优势在于使用了网易云自己的 cdn 资源 (云盘资源)，是 https 且速度有保证
如果你们的 endpoint 带宽足够也是可以做到的，代理架在本地也可以做到

我在公号里留言了希望大佬来 pr，希望他能看到

说实话，这个代理把首屏推荐歌单 hook 就有点可怕，内部还改了多少是未知数，建议慎重使用

**Comment by czpwpq** [comment]
围观一下，不管怎么说觉得在歌曲名字前加个符号来区别正常的歌和解锁的歌的确很明了，大佬下次更新代码的时候看看能不能整进去

**Comment by nondanee** [comment]
@czpwpq 我不会加的

**Comment by czpwpq** [comment]
@nondanee 哈哈，秒回复呀，现在已经挺好用了，自己整了很久总算搞定了公网的调用

**Comment by nondanee** [comment]
@czpwpq 
说一下为什么不加
- 无感使用就行了，用户不需要知道，用户知道了又能怎样呢？
- 丑 (多占一个字符宽度)
- 入侵感太强 (我第一次看到那个效果我就不敢用了)，下载的歌曲文件名应该都会带那个符号吧？

小故事: 测那个代理使用证书的时候我浏览器切错窗口没用隐身模式，然后我第一时间把密码改了，结果发现网易云改密码以后 cookie 不会失效，一言难尽。。。

现在不加标记唯一不好的就是搜索的时候得很仔细地找，因为灰歌的权重都不高排在列表中间确实眼睛都看花了==
解决方式：直接去歌手页/专辑页找歌

**Comment by Xun66** [comment]
@nondanee 这两天我在想，能不能利用网易云自带的歌曲标识，比如SQ，独家，云盘标志等？个人感觉云盘标志比较合适，因为不会有强入侵效果。而且大多数用户云盘其实都是空的，即便用户云盘原有歌曲，匹配到的歌曲其实也和云盘的无版权歌曲特性也十分接近。比如无法评论无法分享等，符合用户习惯。

**Comment by nondanee** [comment]
@Xun66 那么云盘标记是哪个呢？ 😂

**Comment by Xun66** [comment]
@nondanee 你是说代码里的标记还是软件里的标记？后者的话我可以给你提供一个截图😂

**Comment by Xun66** [comment]
如下图出现的几种标识：独家、试听、VIP、SQ、云盘、下载、灰色（相应标识在电脑版中也都存在）。推测除下载外，应该都是由服务器在返回列表中进行标记。几种标识中，灰色、试听、VIP可能会影响播放所以pass，独家和音质入侵太强，看看云盘图标可不可行
![0A4BC57F-98A7-4332-A20C-C80828F9F6E5](https://user-images.githubusercontent.com/26293463/75950223-8a5a9200-5ee3-11ea-9155-6e8fe720c3b0.jpeg)

**Comment by 1273457900** [comment]
![98DB359E-2208-4E4B-9E52-D6ADF53C8E15](https://user-images.githubusercontent.com/62231849/79895763-f95f5c00-8439-11ea-8756-36b0ee0691c5.png)
那个作者回复也是替换成别的平台资源

**Comment by 1273457900** [comment]
> ![98DB359E-2208-4E4B-9E52-D6ADF53C8E15](https://user-images.githubusercontent.com/62231849/79895763-f95f5c00-8439-11ea-8756-36b0ee0691c5.png)
> 那个作者回复也是替换成别的平台资源

就是楼主发的这个pac  他替换掉了首页推荐歌单，看了一下歌单作者给别人的回复 
传送门：你猜我是拿果在网易云音乐听过了14889首歌，做了17张歌单，还收获了45539位粉丝，想了解TA更多？戳 http://music.163.com/m/user/home?id=50014293

**Comment by ufoxb** [comment]
@Xun66 
我发现有些源文件是其他网站的，比如搜一下亮声open的专辑，2018-8-6的，爱的故事上集，看跟我的是不是一样的

**Comment by solxnp** [comment]
卧槽  之前根据食用指南，一直都是网易云无法联网。试了下提供的这个pac，瞬间好了。简直泪奔。。。。搞了好久

**Comment by 1273457900** [comment]
> 卧槽 之前根据食用指南，一直都是网易云无法联网。试了下提供的这个pac，瞬间好了。简直泪奔。。。。搞了好久

这不还是没搭建成功么....按理说直接能用的，ip加端口试试 或者看一下你服务器端口是否打开了

**Comment by zhouchangyi** [comment]
意外的帮到了你 倍感荣幸



------------------&nbsp;Original&nbsp;------------------

**Comment by solxnp** [comment]
@1273457900 都是按照食用指南来的，始终不知道是哪里的问题，搞了两周多，几乎快把issues翻了个遍。。。

**Comment by 1273457900** [comment]
> @1273457900 都是按照食用指南来的，始终不知道是哪里的问题，搞了两周多，几乎快把issues翻了个遍。。。

网易云联不上网 检查服务器 用域名就先换成IP地址  并检查端口 没用域名 就检查端口 看看能通吗 我之前也遇到了 慢慢测试就完美了 这个项目直接搭起来就能用是没错的 比较良心了

**Comment by solxnp** [comment]
@1273457900 请问下你说的用域名就换成ip地址是什么意思？我的启动命令是node app.js -s -e https://music.163.com -p 8080:8081，服务器有域名，启动命令需要换吗？

**Comment by solxnp** [comment]
@1273457900  之前的操作是这样的 https://github.com/nondanee/UnblockNeteaseMusic/issues/65#issuecomment-653352407

**Comment by 1273457900** [comment]
> @1273457900 之前的操作是这样的 [#65 (comment)](https://github.com/nondanee/UnblockNeteaseMusic/issues/65#issuecomment-653352407)

启动命令 换成你自己服务器地址

**Comment by solxnp** [comment]
@1273457900 没明白怎么添加服务器地址  用哪个参数追加？比如ip为127.0.0.1，麻烦帮忙贴下命令

**Comment by 1273457900** [comment]
> @1273457900 没明白怎么添加服务器地址 用哪个参数追加？比如ip为127.0.0.1，麻烦帮忙贴下命令

服务器公网ip node app.js -s -e https://你的服务器公网ip -p 端口

**Comment by 1273457900** [comment]
> @1273457900 没明白怎么添加服务器地址  用哪个参数追加？比如ip为127.0.0.1，麻烦帮忙贴下命令

再没好加我Q 用户名就是

**Comment by Apiee** [comment]
> 如下图出现的几种标识：独家、试听、VIP、SQ、云盘、下载、灰色（相应标识在电脑版中也都存在）。推测除下载外，应该都是由服务器在返回列表中进行标记。几种标识中，灰色、试听、VIP可能会影响播放所以pass，独家和音质入侵太强，看看云盘图标可不可行
> ![0A4BC57F-98A7-4332-A20C-C80828F9F6E5](https://user-images.githubusercontent.com/26293463/75950223-8a5a9200-5ee3-11ea-9155-6e8fe720c3b0.jpeg)

我看这个代理 加了 vip 和 云 那个图标了 请问你尝试过怎么加了么?指教一下

**Comment by zhouchangyi** [comment]
说实话最近没用这个了，其实图个乐呵，在淘宝0元就可以买到网易云音乐包和QQ音乐包 用起来更方便



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: baicai <notifications@github.com&gt;
发送时间: 2020年11月15日 12:33
收件人: nondanee/UnblockNeteaseMusic <UnblockNeteaseMusic@noreply.github.com&gt;
抄送: zhouchangyi <85824673@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[nondanee/UnblockNeteaseMusic] 找到一个ios手机端直接可用的pac，不知道是什么原理 (#398)
