### ISSUE TITLE
能否使用TAP网卡取代系统代理来实现对云音乐的流量拦截？ 

### ISSUE THREAD

**Issue by bv5757** [nondanee/UnblockNeteaseMusic#4]
就像sstap和某些游戏加速器那样

**Comment by nondanee** [comment]
这个不太懂，稍微去了解了下
感觉比较困难，好像也没有必要
1. 网卡级的流量已经到网络层了，对应用层的接口数据操作可能需自己组合拼接，应该比较复杂
2.  看了下SSTAP的目的主要是全局代理和流量转发，但实际上只需对拦截网易云请求的进行拦截就可以了，其余流量都没必要经过代理

我想你可能对现在两种使用方式还不太满意
，能具体说说使用遇到什么麻烦吗
