### ISSUE TITLE
使用方法2设置代理后无法打开一些网页和App

### ISSUE THREAD

**Issue by alidawud** [nondanee/UnblockNeteaseMusic#40]
您好nondanee,
我这边设置代理后无法打开一些网页和app。（微信号公众号文章，谷歌Play，知乎文章等。）
我尝试过添加https到代理，也没有起到作用。eg. https://domain.com:8080/proxy.pac

**Comment by nondanee** [comment]
改成 https 是肯定不行的 😂
http 可以转发 https 流量的不需要改

其他网页和 app 都可以吗？
能不能提供一下 log？

**Comment by alidawud** [comment]
log那边什么都没提示，你没有这个问题吗？ 难道是华为手机的问题。从浏览器打开网页没有问题，现在就是微信公众号文章，谷歌地图，Google Play，知乎文章内容打不开(知乎极速版)。

**Comment by nondanee** [comment]
收到，我测一下哈，可能是 PAC 的问题

**Comment by alidawud** [comment]
感谢感谢🙏，我们一个办公室的人都靠你代码活着😂

**Comment by nondanee** [comment]
借了一台荣耀来测，好像确实不行，只有网易云能联网？
不知道什么原因，但是我自己用 xperia 很正常
手动设置的全局代理有试过吗？

**Comment by alidawud** [comment]
微信能收到消息，Chrome也能打开网页，目前只发现我上面提的这些无法访问，应该是跟华为手机有关系。打扰了🙏🏻

**Comment by nondanee** [comment]
试试看代理手动设置吧，服务器运行在本地的话全局的开销也不会太大

**Comment by alidawud** [comment]
试了一下手动设置代理，所有网站都打不开了，估计是华为OS的问题，我把Issue关了，有空了再研究研究。谢谢你开发这个项目。
