### ISSUE TITLE
周杰伦的歌好像听不了

### ISSUE THREAD

**Issue by hcer1999** [nondanee/UnblockNeteaseMusic#400]
各个客户端都试了，iOS端显示网络连接失败，但是服务器的日志里是有响应的，输出的地址也是歌曲的地址，就是听不了

**Comment by nondanee** [comment]
怎么配置的？启动参数是什么？

pinned issue 看过吗？
#65 #368 看过吗？

不知道你试了哪些，部分客户端使用有额外要求，README 中有写
https://github.com/nondanee/UnblockNeteaseMusic#使用

> 支持 Windows 客户端，UWP 客户端，Android 客户端，Linux 客户端 (1.2 版本以上需要自签证书 MITM，启动客户端需要增加 `--ignore-certificate-errors` 参数)，macOS 客户端 (726 版本以上需要自签证书)，iOS 客户端 (配置 https endpoint 或使用自签证书) 和网页版 (需要自签证书，需要脚本配合)

**Comment by hcer1999** [comment]
运行的严格模式，然后iOS端在HTTP代理设置的ip和端口，然后只能访问网易云音乐，其他软件都没网。如果使用pac的话，好像没有代理上，网易云那些歌还是灰色的

**Comment by nondanee** [comment]
@hcer1999 
严格模式的作用和效果在 README 里有说，其他软件没有网是正常的

你现在这个问题和之前的不一样，之前的问题解决了吗？
iOS 使用必须配置 endpoint，#65 麻烦看一下
之前 "服务器的日志里是有响应的，输出的地址也是歌曲的地址" 是什么模式呢？

如果 PAC 没代理到的话，看看全局的时候有哪些目标地址请求在 pac 里没有，你可以自己补上 (hook.target.host)
