### ISSUE TITLE
按照进阶教程里生成的证书会报错

### ISSUE THREAD

**Issue by Paris0-0** [nondanee/UnblockNeteaseMusic#403]
按照进阶教程里生成自己的证书，发现无法启动，好像是证书太弱了？
0|ubm2  | Error: error:140AB18E:SSL routines:SSL_CTX_use_certificate:ca md too weak
0|ubm2  |     at Object.createSecureContext (_tls_common.js:129:17)
0|ubm2  |     at Server.setSecureContext (_tls_wrap.js:1293:27)
0|ubm2  |     at Server (_tls_wrap.js:1157:8)
0|ubm2  |     at new Server (https.js:68:14)
0|ubm2  |     at Object.createServer (https.js:92:10)
0|ubm2  |     at Object.<anonymous> (/etc/UnblockNeteaseMusic/src/server.js:167:26)
0|ubm2  |     at Module._compile (internal/modules/cjs/loader.js:1158:30)
0|ubm2  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
0|ubm2  |     at Module.load (internal/modules/cjs/loader.js:1002:32)
0|ubm2  |     at Function.Module._load (internal/modules/cjs/loader.js:901:14) {
0|ubm2  |   library: 'SSL routines',
0|ubm2  |   function: 'SSL_CTX_use_certificate',
0|ubm2  |   reason: 'ca md too weak',
0|ubm2  |   code: 'ERR_SSL_CA_MD_TOO_WEAK'
0|ubm2  | }

**Comment by nondanee** [comment]
仓库里的可以吗？仓库的 ca 也是这么生成的
把 2048 改成 4096 看看呢？

**Comment by Paris0-0** [comment]
改了，还是不行，用仓库里自带的就可以。。不知道为啥

**Comment by nondanee** [comment]
你现在 node 什么版本？

**Comment by nondanee** [comment]
刚试了用 node 13.9 没问题
你是不是还更新过 openssl 之类的东西呢？

可能跟证书签署时间会有关系的，我翻了下这个 issue 有提 https://github.com/nondanee/UnblockNeteaseMusic/issues/276#issuecomment-555219137
官方说明 https://support.apple.com/zh-cn/HT210176
不知道会不会是这个原因

我现在再签一组证书，你试试看
[test-cert.zip](https://github.com/nondanee/UnblockNeteaseMusic/files/4268215/test-cert.zip)
我自测用里面的 server.key 和 server.crt 是不会报错的

我的 macOS 不是这个版本，你先自己查查

**Comment by Paris0-0** [comment]
我试了你签的也可以，但我自己的和我之前签的都不行，我尽量说全些：
我的Unblock server是部署在一个debian系统的小主机上，我自己签的证书都是在我的MacBook系统Catalina上签的，我的macOS终端上也没更新过什么东西，之前签的大概在2019.12月，按照进阶教程签发的，当时是正常使用的，我就把他保存了一下。
前两天我在小主机debian上折腾homebridge，提示nodejs版本太低，之前是8.7.0，然后我就更新到了12.16.1，更新完node路径改了，又重新安装了pm2（我习惯用pm2部署），这时候启动Unblock server就运行不了了（当时太晚了没仔细看，反正是运行不起来了，Unblock server 代码对比之前没有任何改动，用node app.js和pm2 start app.js都不能启动），然后我以为可能是我太久没同步代码了就又clone了最新的代码，依然启动不了，看了log大致是证书问题（就是我上面贴的错误代码），就在Macbook 上按照进阶配置又签了一遍，还是同样的问题，但是用你仓库里的和你发的test里的都是可以的。。

**Comment by nondanee** [comment]
你签的可以发一下文件我测测看

可能和 openssl 的版本有关系
你直接在 debian 上签试试

**Comment by zelinsong** [comment]
杜比大喇叭的服务器地址是啥

**Comment by Paris0-0** [comment]
在debian上签了也是可以的
[cer.zip](https://github.com/nondanee/UnblockNeteaseMusic/files/4270213/cer.zip)

**Comment by nondanee** [comment]
@Paris0-0 
我测了都能用， catalina 那两个我也能用
如果 debian 签的能用就用 debian 来签吧

**Comment by nondanee** [comment]
@zelinsong 
杜比大喇叭是啥

**Comment by Paris0-0** [comment]
@nondanee 嗯，就用debian的了，搞不懂是什么原因hhh
