### ISSUE TITLE
网络服务解锁是产生错误结果的反馈

### ISSUE THREAD

**Issue by blueveryday** [nondanee/UnblockNeteaseMusic#404]
通过网络搭建的服务，大部分使用正常，但是个别歌曲解锁识别的结果并不是所需要的歌曲。
比如，黄凯芹的《桃花依旧》，解锁出来的结果就不对。

但是用本地服务的时候，结果有时候又是正确的。
本地服务在解锁的时候也会发生类似问题，很奇怪。

**Comment by nondanee** [comment]
是的，因为匹配都是实时的，结果不确定 (和时间/空间都有关系)

你这个问题可能是因为搭建服务的 IP 地理位置
之前测的话过应该是所有音源都有海外墙的 (测试 IP 日本，国内这些全军覆没)
kuwo 和 migu 在香港(境外)可以用
joox 服务地区香港东南亚等
youtube 需要 XX 你懂的

(以后反馈音源的问题贴上 log，log 上是能看出匹配到了哪个源的，不要只给一首歌
每个人的匹配结果不同，我不一定能复现)

**Comment by blueveryday** [comment]
> 
> 
> 是的，因为匹配都是实时的，结果不确定 (和时间/空间都有关系)
> 
> 你这个问题可能是因为搭建服务的 IP 地理位置
> 之前测的话过应该是所有音源都有海外墙的 (测试 IP 日本，国内这些全军覆没)
> kuwo 和 migu 在香港(境外)可以用
> joox 服务地区香港东南亚等
> youtube 需要 XX 你懂的
> 
> (以后反馈音源的问题贴上 log，log 上是能看出匹配到了哪个源的，不要只给一首歌
> 每个人的匹配结果不同，我不一定能复现)

请教如何找出log？

**Comment by nondanee** [comment]
标准输出就是 log
```
...
MITM > music.163.com 
MITM > music.163.com 
TUNNEL > p3.music.126.net:443
[503206031] 桃花依旧
http://dl.stream.qqmusic.qq.com/M500002k2HN007NNoT.mp3?vkey=AAC7DD58EDFCD7299B57C8046F42B4114BD7B7C78A6FF1FBE10FCDC49C4AEFBF80A2A1497267CCFD686ED39BD66F917042A2FEFA0F48BB67&uin=0&fromtag=8&guid=7332953645
MITM > dl.stream.qqmusic.qq.com 
MITM > music.163.com
...
```

**Comment by blueveryday** [comment]
以下是log，之前运行程序是设成路由器后台运行的，所以看不到log信息。
如何把这些log内容输出到log.txt呢？以便给你报告错误。
谢谢。
大陆ping的服务器IP是59.111.181.60
新加坡ping的服务器IP是103.126.92.133
而且有个奇怪的现象，大陆ip得出的英文歌的内容容易出错，而新加坡ip得出的中文歌容易出错。
正好是相反的。
测试歌曲信息：
歌名：A Number On My Back
专辑：Anthems - A Celebration of Australia
歌手：John Williamson

MITM > interface.music.163.com
MITM > interface.music.163.com
TUNNEL - interface.music.163.com:443
TUNNEL - interface.music.163.com:443
TUNNEL - interface.music.163.com:443
TUNNEL - interface.music.163.com:443
[31066059] A Number On My Back
http://rq01.sycdn.kuwo.cn/19cc3b9dcb0d4653d857cd3d7bc613b7/5e5ca53b/resource/n2/63/83/905742776.mp3
MITM > rq01.sycdn.kuwo.cn
MITM > rq01.sycdn.kuwo.cn
MITM > clientlog.music.163.com
MITM > interface.music.163.com
MITM > music.163.com
MITM > clientlog.music.163.com

**Comment by nondanee** [comment]
输出到文件你要找路由器插件的作者，应该是默认有保存的，可以问下路径是什么

ping 的服务器 ip 是网易云服务器的 ip，匹配是其他平台匹配的，两者没有关系，ip 不同说明不了问题

和网络环境有关系，可以具体测一下同一首歌 (同一个 id) 匹配到了哪个源
我觉得国内海外搜索结果优化方向不一样的可能性比较低
不会出现在某一时刻相同源对同一首歌匹配结果不一样的情况

匹配错误是已知 BUG https://github.com/nondanee/UnblockNeteaseMusic/issues/30#issuecomment-517984439
有能力的话可以自己动手，参考 https://github.com/nondanee/UnblockNeteaseMusic/issues/372#issuecomment-583751043

**Comment by blueveryday** [comment]
> 输出到文件你要找路由器插件的作者，应该是默认有保存的，可以问下路径是什么
> 
> ping 的服务器 ip 是网易云服务器的 ip，匹配是其他平台匹配的，两者没有关系，ip 不同说明不了问题
> 
> 和网络环境有关系，可以具体测一下同一首歌 (同一个 id) 匹配到了哪个源
> 我觉得国内海外搜索结果优化方向不一样的可能性比较低
> 不会出现在某一时刻相同源对同一首歌匹配结果不一样的情况
> 
> 匹配错误是已知 BUG [#30 (comment)](https://github.com/nondanee/UnblockNeteaseMusic/issues/30#issuecomment-517984439)
> 有能力的话可以自己动手，参考 [#372 (comment)](https://github.com/nondanee/UnblockNeteaseMusic/issues/372#issuecomment-583751043)
感谢回复。
最后一个问题，如何自定义优先选择哪个网站作为搜索？
我发现kuwo不太适合我，就想保留xiami和qq，谢谢。

**Comment by nondanee** [comment]
配置参数为 `-o` ，参考 https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-429515355

虾米接口容易被反爬机制 punish，需要 `x5sec`，几乎不可用 https://github.com/nondanee/UnblockNeteaseMusic/issues/30#issuecomment-515751681
