### ISSUE TITLE
关于安卓手机无ROOT无XP框架实现代理

### ISSUE THREAD

**Issue by DyingLight12** [nondanee/UnblockNeteaseMusic#405]
这个早在去年8月份就弄好了的。9月上传到吾爱破解，感觉好多人都还不知道有这方法，直接发这里算了。

[点我下载](http://yun.xdw6.cn:81/index.php?share/file&user=1&sid=37hQSiyk)

**Comment by nondanee** [comment]
要做教程的话建议将完整的内容写到 issue 里

这个方法和 termux 没本质区别，只是启动方式不一样
代码可以用 termux clone 到存储根目录 (`/sdcard`) 之后同步更新直接 pull 就行了，不需要手动拷贝
