### ISSUE TITLE
伍佰的《突然的自我》

### ISSUE THREAD

**Issue by MaggieForest** [nondanee/UnblockNeteaseMusic#407]
除了伍佰的《突然的自我》，都挺好的。

**Comment by MaggieForest** [comment]
大佬的代码很棒！赞👍

**Comment by nondanee** [comment]
原则上只处理无版权的歌，VIP 歌曲建议充个黑胶

我试了下匹配到了 QQ 音乐的这首歌 (默认音源顺序是 QQ 首位)
https://y.qq.com/n/yqq/song/002JlQoD2CDC0w.html

QQ 音乐的搜索结果是这样的
https://y.qq.com/portal/search.html#page=1&searchid=1&remoteplace=txt.yqq.top&t=song&w=%E7%AA%81%E7%84%B6%E7%9A%84%E8%87%AA%E6%88%91%20-%20%E4%BC%8D%E4%BD%B0

![image](https://user-images.githubusercontent.com/26399680/75571781-ced5d000-5a94-11ea-8fb2-0e874b8ab3b0.png)

排在第一的是翻唱歌曲

目前没有匹配度计算的逻辑，默认取各音源搜索结果第一首，再按音源排序 https://github.com/nondanee/UnblockNeteaseMusic/issues/30#issuecomment-517984439
故不会在看之后酷我咪咕的匹配结果 (就算完美匹配也不会使用)

[v0.24.0 版本](https://github.com/nondanee/UnblockNeteaseMusic/releases/tag/v0.24.0) 开始已留好接口，如有需要可以自己添加，参考 https://github.com/nondanee/UnblockNeteaseMusic/issues/372#issuecomment-583751043

> 心里话: 可以用钱解决的就用钱解决，不用搞这么复杂
