### ISSUE TITLE
HTTPS代理无法连接

### ISSUE THREAD

**Issue by wutong233** [nondanee/UnblockNeteaseMusic#409]
使用HTTP没有问题,可就是在使用HTTPS(不管是哪个端口)时网易云说无法使用此代理,浏览器使用的话打不开任何网页,服务器上没有任何反应
在手机和服务器上搭建的代理均有此问题

如下,此后就没反应了(443换成别的端口也不能连接)

[root@localhost UnblockNeteaseMusic]# node app.js -p 23333:443 -f 59.111.181.38
HTTP Server running @ http://0.0.0.0:23333
HTTPS Server running @ http://0.0.0.0:443

**Comment by nondanee** [comment]
为什么要用 https 代理呢？因为好奇吗？

-----

这个 https 端口用的是自己签署的网易云 (music.163.com 和 *.music.163.com) 所属域名的证书，具体内容见 #48 

要正常使用 https 代理(等价于 https 网站能正常访问)要满足两个条件
- 证书能被信任
- (代理)服务器地址能与证书包含的域名相匹配 (代理地址肯定不能是 IP)

操作步骤：首先需要安装自己的 CA 证书才会被信任，其次需要给代理地址添加一个域名，最简单的就是改 hosts，增加一个类似 `127.0.0.1 proxy.music.163.com` 的记录指向代理服务器，端口号倒不一定要求是 443

亲测在浏览器的 switchy omega 插件里设置地址和端口号后即可使用
![image](https://user-images.githubusercontent.com/26399680/75627031-87238580-5c07-11ea-96cc-ae68d56eb4d8.png)

是因为没设置对，所以不能用

-----

至于网易云 PC 客户端，设置里写明了是 HTTP 代理，不知道你有没有注意看

![image](https://user-images.githubusercontent.com/26399680/75627053-b76b2400-5c07-11ea-9215-cf232e6dc6cd.png)

Android 的 wifi 高级选项里虽然没有写明，但是类原生底下会提示 "浏览器会使用 HTTP 代理"，说明其实也是 HTTP 代理

![image](https://user-images.githubusercontent.com/26399680/75627019-7a069680-5c07-11ea-9e21-2f77df009fef.png)

是因为不支持，所以不能用

-----

综上，不是我的问题 😁

**Comment by wutong233** [comment]
> 为什么要用 https 代理呢？因为好奇吗？
> 
> 这个 https 端口用的是自己签署的网易云 (music.163.com 和 *.music.163.com) 所属域名的证书，具体内容见 #48
> 
> 要正常使用 https 代理(等价于 https 网站能正常访问)要满足两个条件
> 
> * 证书能被信任
> * (代理)服务器地址能与证书包含的域名相匹配 (代理地址肯定不能是 IP)
> 
> 操作步骤：首先需要安装自己的 CA 证书才会被信任，其次需要给代理地址添加一个域名，最简单的就是改 hosts，增加一个类似 `127.0.0.1 proxy.music.163.com` 的记录指向代理服务器，端口号倒不一定要求是 443
> 
> 亲测在浏览器的 switchy omega 插件里设置地址和端口号后即可使用
> ![image](https://user-images.githubusercontent.com/26399680/75627031-87238580-5c07-11ea-96cc-ae68d56eb4d8.png)
> 
> 是因为没设置对，所以不能用
> 
> 至于网易云 PC 客户端，设置里写明了是 HTTP 代理，不知道你有没有注意看
> 
> ![image](https://user-images.githubusercontent.com/26399680/75627053-b76b2400-5c07-11ea-9215-cf232e6dc6cd.png)
> 
> Android 的 wifi 高级选项里虽然没有写明，但是类原生底下会提示 "浏览器会使用 HTTP 代理"，说明其实也是 HTTP 代理
> 
> ![image](https://user-images.githubusercontent.com/26399680/75627019-7a069680-5c07-11ea-9e21-2f77df009fef.png)
> 
> 是因为不支持，所以不能用
> 
> 综上，不是我的问题 😁

注意看了,感谢回答,原来是我的误解,看你说HTTPS已无法降级认为必须要开HTTPS代理...
