### ISSUE TITLE
在windows上无法运行项目

### ISSUE THREAD

**Issue by a936919** [nondanee/UnblockNeteaseMusic#410]
系统:win10 1909
nodejs版本:V12.16.1
![image](https://user-images.githubusercontent.com/41937411/75650448-d5c93200-5c90-11ea-8b90-7fc8a34cc57a.png)
我在本机的Ubuntu虚拟机上运行也是报这个错
![image](https://user-images.githubusercontent.com/41937411/75650523-0dd07500-5c91-11ea-880b-c766c1eab1f4.png)

**Comment by nondanee** [comment]
浏览器里能不能打开这两个 url
https://httpdns.n.netease.com/httpdns/v2/d
https://music.httpdns.c.163.com/d
(404 算能打开)

打开会不会提示证书错误？

**Comment by a936919** [comment]
可以打开并没有报错

**Comment by nondanee** [comment]
虚拟机上
```
curl https://httpdns.n.netease.com/httpdns/v2/d
curl https://music.httpdns.c.163.com/d
```
看看

**Comment by a936919** [comment]
我自己用控制变量法 发现了是我路由器上的openclash插件 配置文件中有一个网易云音乐的规则 但是那个服务器端口应该是被封掉了 连不通所以才会出现这种情况 选择直连之后 就可以了
![image](https://user-images.githubusercontent.com/41937411/75776022-1ce91d00-5d8e-11ea-923a-8062a828d662.png)
![image](https://user-images.githubusercontent.com/41937411/75776054-2c686600-5d8e-11ea-800b-33d799184209.png)

**Comment by nondanee** [comment]
好的👌
