### ISSUE TITLE
音效选择失败

### ISSUE THREAD

**Issue by legendtang** [nondanee/UnblockNeteaseMusic#411]
![image](https://user-images.githubusercontent.com/1352729/75672914-bc3ddf80-5cbc-11ea-9d83-f91d58e79e5c.png)

Mac 2.3.2 Build 832
已配置 SSL 证书

**Comment by nondanee** [comment]
断开耳机试一下
https 被阻断了不是这个报错 #317

我看你很早就 fork 了 (Feb 2019)
之前使用有问题吗？

**Comment by legendtang** [comment]
@nondanee 第一页是相同的提示，按他的解决方法还是一样的提示，暂无解决
以前 fork 是因为有些其他曲库 API 坏了尝试 debug 过

**Comment by nondanee** [comment]
@legendtang 
好的我看看

**Comment by nondanee** [comment]
我试了下没问题

![macOS 10 14-2020-03-03-02-26-17](https://user-images.githubusercontent.com/26399680/75705679-d0063780-5cf6-11ea-9dbd-52f07fe6a410.png)

mojave 10.14
