### ISSUE TITLE
反馈一个歌曲适配不正确的问题

### ISSUE THREAD

**Issue by xiaocainiao2020** [nondanee/UnblockNeteaseMusic#414]
搜到的《纸短情长》花粥版的，但是实际播放的并不是花粥的版本，也有一些其他的歌曲匹配有问题，看看作者可以优化匹配规则吗？

**Comment by nondanee** [comment]
要是我会做得话早就做啦 https://github.com/nondanee/UnblockNeteaseMusic/issues/30#issuecomment-517984439

《纸短情长》花粥版再怎么优化也匹配不到，除非 youtube，建议黑胶 😁
