### ISSUE TITLE
想知道是什么原理，理论上能否支持QQ音乐？

### ISSUE THREAD

**Issue by Gh-Levi** [nondanee/UnblockNeteaseMusic#416]
app.js中有几处网易云的host地址，不知道通过改这些地址能否让QQ音乐也支持。能否介绍一下原理和思路？谢谢！

**Comment by WROIATE** [comment]
> app.js中有几处网易云的host地址，不知道通过改这些地址能否让QQ音乐也支持。能否介绍一下原理和思路？谢谢！

我个人理解是调包，通过流量进入代理后匹配网易链接进行劫持后将requests请求修改重新发送一个新的链接（这个链接就是provider的），请求到音乐以后再重新将provider的response改写成网易的，然后返回到应用。为什么https需要安装证书也是因为这事劫持了链接伪造的response没有真正的网易证书，所以需要手动信任来让系统相信这是真的response

**Comment by nondanee** [comment]
原理在 README 中有写，简单来说是修改 http 请求和响应

思路就是把需要修改的请求过滤出来改成你想要的样子
这边主要的工作就是给没有播放地址的返回数据填充一个有效的播放地址

播放地址是从别的平台通过搜索歌曲搜出来的（搜索关键词是歌名歌手专辑等）
这个匹配过程是可以复用的，也就是 provider 的主要逻辑
provider 作为项目的一部分已经导出了，再 npm install 后可以直接调用，调用方法看 README

对别人来说是调包，对我来说是我在花时间维护这个包
调这个包并不是一个"发送一个新的链接"，只是调一下里面的方法，拿到返回值而已

app.js 里的 ip 地址是网易 httpdns 的地址，和网易云音乐本身没有太大关系
通过改这些地址肯定没法让 QQ 音乐也支持

每一家的请求参数、返回数据结构、加密方式、标志位意义都不一样，没有普适性

P.S. 楼上说的大概差不多意思，就是表述稍微有点问题，需要安装 CA 证书也确实是这个作用

**Comment by nondanee** [comment]
类似的 issue #73 #116 #241 #253

**Comment by Super1Windcloud** [comment]
厉害啊, 想知道这些从别的平台通过搜索歌曲搜出来的 , 是指的那些平台呢
