### ISSUE TITLE
macOs网络连接失败？

### ISSUE THREAD

**Issue by lxsunbin** [nondanee/UnblockNeteaseMusic#417]
1.ping music.163.com获取[ip]
2.修改本地host
3.sudo npx @nondanee/unblockneteasemusic -p 80 -f [ip] 

npx: 1 安装成功，用时 2.711 秒
HTTP Server running @ http://0.0.0.0:80

此时打开网易云音乐，提示网络连接错误。。如何处理呢？

**Comment by nondanee** [comment]
0.安装 CA 证书
3.sudo npx @nondanee/unblockneteasemusic -p 80:443 -f [ip]

README 中有写
> macOS 客户端 (726 版本以上需要自签证书)
