### ISSUE TITLE
部分歌曲播放失败

### ISSUE THREAD

**Issue by Co2333** [nondanee/UnblockNeteaseMusic#419]
只发生在特定歌曲 比如下面这首
只发生在特定客户端 目前用下来只出现在iOS的最新iPhone版上

iPad和macOS还有Windows都可以用
配置的话是我想应该没有问题因为别的歌已经可以听了唯独这一首不行

不知道问题出在哪里了摊手

```
nm     | MITM > interface.music.163.com 
nm     | TUNNEL > p1.music.126.net:443
nm     | [422094253] 好好 (想把你写成一首歌)
nm     | http://other.player.nf01.sycdn.kuwo.cn/4c2ecca699d6272df6b5c5148e59ddf8/5e615836/resource/n1/67/44/1053086599.mp3
nm     | MITM > interface.music.163.com 
nm     | MITM > interface.music.163.com 
```

**Comment by nondanee** [comment]
没设备没有 debug 能力
这首歌失败一直可以复现吗？清除缓存再试一下呢？

**Comment by Co2333** [comment]
100%可以复现。。。。

删了重装也没用。。

**Comment by nondanee** [comment]
就只是这一首歌有问题吗？
可以去 #65 问问别人
一定想听的话自己传个云盘吧~

**Comment by Co2333** [comment]
确实是只有这一首歌 我看他都解析出来了诶

**Comment by idoet1** [comment]
还有一首，刘明湘的漂洋过海来看你，专辑是我不要再比了，可以播放，但是和原来的不是同一首，变成了dj版，，

**Comment by nondanee** [comment]
@idoet1 你这个问题不一样，匹配不准是正常现象 https://github.com/nondanee/UnblockNeteaseMusic/issues/30#issuecomment-517984439

**Comment by KaierChou** [comment]
日语歌好像挺难匹配准的..
比如 天气之子 和 你的名字 这两张专辑, 全跪了 QAQ

**Comment by Co2333** [comment]
匹配不准是正常现象 有能力的git友可以自己搞一个匹配数据库

**Comment by Co2333** [comment]
该问题是由于没有正确配置endpoint导致的
