### ISSUE TITLE
macOS一切正常，但是播放不了jay的歌曲？

### ISSUE THREAD

**Issue by lxsunbin** [nondanee/UnblockNeteaseMusic#422]
改host方法，CA证书已用，网易云版本降级为2.0.0，所有歌曲都已点亮，其他的大部分都能播放，但是jay的一首都播放不了。。什么情况？

 sudo npx @nondanee/unblockneteasemusic -p 80:443 -f xxx.xxx.xx.xx
npx: 1 安装成功，用时 2.401 秒
HTTP Server running @ http://0.0.0.0:80
HTTPS Server running @ http://0.0.0.0:443

**Comment by lxsunbin** [comment]
> 改host方法，CA证书已用，网易云版本降级为2.0.0，所有歌曲都已点亮，其他的大部分都能播放，但是jay的一首都播放不了。。什么情况？
> 
> sudo npx @nondanee/unblockneteasemusic -p 80:443 -f xxx.xxx.xx.xx
> npx: 1 安装成功，用时 2.401 秒
> HTTP Server running @ http://0.0.0.0:80
> HTTPS Server running @ http://0.0.0.0:443

多次尝试，反复重试播放同一首jay的歌，有概率会解析成功。。

**Comment by nondanee** [comment]
装了证书不需要降版本

> 大部分能播放

按 log 来看都匹配到哪个平台？
都是 qq 音乐的吗？有没有匹配到酷我的歌和咪咕的歌？

> 有概率会解析成功。。

成功解析到什么平台？

是实时匹配的，视网络环境而定，影响因素很多

**Comment by lxsunbin** [comment]
> 装了证书不需要降版本
> 
> > 大部分能播放
> 
> 按 log 来看都匹配到哪个平台？
> 都是 qq 音乐的吗？有没有匹配到酷我的歌和咪咕的歌？
> 
> > 有概率会解析成功。。
> 
> 成功解析到什么平台？
> 
> 是实时匹配的，视网络环境而定，影响因素很多

经常解析到一个地址  xxx.xx.xx/disabled.html..

**Comment by lxsunbin** [comment]
> 装了证书不需要降版本
> 
> > 大部分能播放
> 
> 按 log 来看都匹配到哪个平台？
> 都是 qq 音乐的吗？有没有匹配到酷我的歌和咪咕的歌？
> 
> > 有概率会解析成功。。
> 
> 成功解析到什么平台？
> 
> 是实时匹配的，视网络环境而定，影响因素很多

"您尝试访问的网站类型属于[下载工具/多线程下载]已经被上网策略[禁用下载]拒绝访问。如果有疑问，请联系网络管理员。"
被公司网络拦截了，这里用了啥下载策略呀？

**Comment by nondanee** [comment]
就是正常的 get 请求，读取 body，都算不上是下载
也没有多线程

你试试浏览器打开酷我的网站 (http 站点) 能听歌吗？
QQ 音乐和网易云音乐也试一下 (https 站点)

如果是 https 的可以听，http 的被拦截了，就在公网开一个 https endpoint

**Comment by lxsunbin** [comment]
> 就是正常的 get 请求，读取 body，都算不上是下载
> 也没有多线程
> 
> 你试试浏览器打开酷我的网站 (http 站点) 能听歌吗？
> QQ 音乐和网易云音乐也试一下 (https 站点)
> 
> 如果是 https 的可以听，http 的被拦截了，就在公网开一个 https endpoint

以上都可以听，感觉是咪咕音乐的问题。。

**Comment by nondanee** [comment]
那开 endpoint 能解决，或者加一个上游代理也能解决

不过部分周杰伦的歌是应该可以匹配到酷我吧
检查一下 node 版本，不是 10 以上的话能更新就更新一下

**Comment by lxsunbin** [comment]
> 那开 endpoint 能解决，或者加一个上游代理也能解决
> 
> 不过部分周杰伦的歌是应该可以匹配到酷我吧
> 检查一下 node 版本，不是 10 以上的话能更新就更新一下

确实大部分是酷我，node版本 `v12.16.1`

**Comment by lxsunbin** [comment]
> 那开 endpoint 能解决，或者加一个上游代理也能解决
> 
> 不过部分周杰伦的歌是应该可以匹配到酷我吧
> 检查一下 node 版本，不是 10 以上的话能更新就更新一下

endpoint咋加呀？
