### ISSUE TITLE
正确歌曲源问题

### ISSUE THREAD

**Issue by Nyazuki** [nondanee/UnblockNeteaseMusic#426]
在网易云音乐上播放一些歌曲，发现不是原版的歌曲，匹配出来的应该是同名的翻唱版本或者现场版本。

例：Taylor Swift - The Man 在Lover专辑里播放的不是专辑版本的而是她在London的Live版本。

请问这个问题有什么比较好的办法解决吗？

我又阅读参考了以下内容: https://github.com/nondanee/UnblockNeteaseMusic/issues/372, https://github.com/nondanee/UnblockNeteaseMusic/issues/407, https://github.com/nondanee/UnblockNeteaseMusic/issues/404, https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-429515355

大致明白机制是去用引擎去搜索所有支持的音源上是否有match，但无法确定准确。
这样的话，可不可以在server log里把所有match的结果全部print出来呢？

例如：
[x] [$song_id] $song_name $song_url
[ ] [$song_id] $song_name $song_url
[ ] [$song_id] $song_name $song_url
......

第一个按顺序默认选取的音源不变，但是其他的matches也可以在log里看到，如果需要可以自行下载尝试之类的。

**Comment by nondanee** [comment]
所有结果做不到，每个音源最多只会有一个 song_url
因为 song_url 要单独获取，不可能为十几个搜索结果全都请求一遍
默认开三个音源最多只有 3 个地址

要把 song_name 打印出来的话得改一改，目前还不支持
(目前的 song_name 是网易云的 song_name，和 match 结果没关系)

如果想要这种 feature 的话，可能
https://github.com/winterssy/mxget
https://github.com/0xHJK/music-dl
更适合你

**Comment by Nyazuki** [comment]
> 所有结果做不到，每个音源最多只会有一个 song_url
> 因为 song_url 要单独获取，不可能为十几个搜索结果全都请求一遍
> 默认开三个音源最多只有 3 个地址
> 
> 要把 song_name 打印出来的话得改一改，目前还不支持
> (目前的 song_name 是网易云的 song_name，和 match 结果没关系)
> 
> 如果想要这种 feature 的话，可能
> https://github.com/winterssy/mxget
> https://github.com/0xHJK/music-dl
> 更适合你

song_name 在console log里是可以看到的，只是想说，用同样的方式可不可以把所有匹配的结果都print出来...（loop on array）
match的结果是以reference的方式存在吗？如果不去请求就得不到url？如果是的话，全部请求一下url，然后print出来（不播放）会有什么问题或者麻烦么？如果url在search的时候就已经都有了，那就是print一下array object的内容，应该很简单吧。

**Comment by nondanee** [comment]
我意思是目前显示的 song_name 是网易云里的 song_name，不是在其他平台的 song_name，不知道你想要显示哪个？

js 里 object 全都是 reference

是的，不去请求就得不到 url
花时间啊，要等全部返回了我才能取第一条数据吐给客户端，还有可能因为高频请求被 ban
search 的时候没有 url

**Comment by Nyazuki** [comment]
> 我意思是目前显示的 song_name 是网易云里的 song_name，不是在其他平台的 song_name，不知道你想要显示哪个？
> 
> js 里 object 全都是 reference
> 
> 是的，不去请求就得不到 url
> 花时间啊，要等全部返回了我才能取第一条数据吐给客户端，还有可能因为高频请求被 ban
> search 的时候没有 url

明白了！感谢。
