### ISSUE TITLE
docker run 方式不行了吗？

### ISSUE THREAD

**Issue by libra1010** [nondanee/UnblockNeteaseMusic#429]
公网部署，直接 docker run 取得是latest版本
macos 客户端版本 834
macos设置pac代理
重启云音乐后，正常歌曲都提示网络不通，无法播放

**Comment by nondanee** [comment]
试了下 docker 镜像功能正常

是不是网络问题，自查一下

**Comment by libra1010** [comment]
> 试了下 docker 镜像功能正常
> 
> 是不是网络问题，自查一下

我尝试过的

Port configuration | 0.0.0.0:5555  8080/tcp
上面是我的端口映射，我将host的5555端口映射到8080
然后macos代理地址就是http://ip:5555/proxy.pac
我使用telnet ip 5555 是可以连接上的
并且通过代理地址在浏览器里面是可以下载到pac文件的

	function FindProxyForURL(url, host) {
						if (host == 'music.163.com' || host == 'interface.music.163.com' || host == 'interface3.music.163.com' || host == 'apm.music.163.com' || host == 'apm3.music.163.com' || host == '59.111.181.38' || host == '59.111.181.60' || host == '223.252.199.66' || host == '223.252.199.67' || host == '59.111.160.195' || host == '59.111.160.197' || host == '118.24.63.156' || host == '193.112.159.225' || host == '59.111.181.35' || host == '47.100.127.239' || host == '39.105.63.80' || host == '115.236.121.1' || host == '115.236.118.33') {
							return 'PROXY 112.74.188.99:5555'
						}
						return 'DIRECT'
					}
				

![image](https://user-images.githubusercontent.com/9667153/76585334-163e7080-6519-11ea-9d73-35f2659e75ca.png)
播放效果就是这样
以前的老版本同样的操作方式是没有问题的

**Comment by nondanee** [comment]
是仅仅播放失败还是所有操作都失败？像打开专辑打开歌单这种可以吗？
老版本是什么版本？
是说网易云的老版本还是 UnblockNeteaseMusic 的老版本？

**Comment by libra1010** [comment]
所有操作，打开歌单都是转菊花，然后提示网络不给力，最后没有歌单出来
老版本是指都是老版本，UnblockNeteaseMusic 和 网易云都是老版本
因为中间有一段时间没有听需要解封的歌，所以中间不行了，就去掉代理了
现在重新升级了 网易云和 UnblockNeteaseMusic
都是同样的操作方式，现在就什么操作都不行了

**Comment by nondanee** [comment]
UnblockNeteaseMusic 没有 breaking change，可以降网易云的版本试试看
你的启动参数是什么，有没有装过证书？参考 https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-477870013

**Comment by libra1010** [comment]
重新安装了证书并信任(直接使用 服务里面的ca.crt 没有使用自签名)

命令如下
docker run -d -p 5555:8080   --name 163 nondanee/unblockneteasemusic

发现启动日志只监听了一个http 8080 这样是不是有问题，是docker 镜像不是最新的吗？
HTTP Server running @ http://0.0.0.0:8080

**Comment by nondanee** [comment]
默认参数下就只监听一个 http 8080，一直都是，跟版本没关系

可以 `docker run nondanee/unblockneteasemusic -v` 看一眼版本确认一下
更新用 `docker pull nondanee/unblockneteasemusic`

开第二端口要手动加配置
```
docker run -d -p 5555:8080 --name 163 nondanee/unblockneteasemusic -p 8080:8081
```

**Comment by libra1010** [comment]
OK了，原来需要开启第二个端口，我就说看前面说的需要https，但是docker日志里面怎么没有 https端口监听，
使用开启第二个端口，则使用正常
THANKS
