### ISSUE TITLE
想问下，在Android端，无root的情况的怎么使用搭建的代理（ps，vivo无wlan代理自动配置）

### ISSUE THREAD

**Issue by zFengling** [nondanee/UnblockNeteaseMusic#430]
最近不是阿里云有学生白嫖服务器的活动，就弄了个，虽然网速是1Mbps，但是用于使用大佬这个项目，还是可以了，毕竟免费的。
目前就是有个想法，能否在手机无论是移动网络还是wifi下都能使用该pac代理，类似于小飞机那种。
但是手机是没有root的，我主要是给朋友用，艹蛋的是vivo竟然没有wlan代理自动配置，无语了。
我也在issures找了，但我一头雾水，小白一个。
可能我描述很不清楚，见谅哈

**Comment by nondanee** [comment]
emmm 我看到你 star 了 Nroxy，可以用吗？
那个项目目前不支持 Android 10，10 以下的版本可以用的
有其他问题在那边提 issue 就行

另外，可以使用 goproxy / glider 转化成 ss 协议再使用小飞机
https://github.com/snail007/goproxy
https://github.com/nadoo/glider

**Comment by zFengling** [comment]
1.Nroxy,昨晚下载了，忘记使用了，想问下proxy.js文件是在哪呢，使用教程就是readme图片上那些吧。
2.我自己手机使用wlan的代理自动配置时，不是填了pac地址吗，但是过一会后，手机网络就出了问题，浏览器不能打开网页，很多应用不能刷新了，把代理关了，就恢复正常了，网易云貌似正常🤣
3.自己小白一个，啊，接触这些头大呀，hhhh，感谢大佬的耐心回答

**Comment by zFengling** [comment]
4.还有一个问题/电脑端这样设置，uwp和客户端段均可以正常使用，但是网页端打不开，不能访问，log显示tunnel -music.163.com:443
[https://s1.ax1x.com/2020/03/13/8n2Nxs.png](url)
ps：不知道怎么上传图片，就使用外链了
我问题是不是太多了，我应该善用搜索的，但是效率不尽人意。

**Comment by zFengling** [comment]
4.还有一个问题/电脑端这样设置，uwp和客户端段均可以正常使用，但是网页端打不开，不能访问，log显示tunnel -music.163.com:443
https://s1.ax1x.com/2020/03/13/8n2Nxs.png
ps：不知道怎么上传图片，就使用外链了
我问题是不是太多了，我应该善用搜索的，但是效率不尽人意。

**Comment by nondanee** [comment]
1. 截图里的 proxy.js 代指程序入口，对于这个项目来说是 app.js，截图只是 demo，不是教程
先看本项目的使用教程 #22，具体参数根据自身情况配置
2. 部分软件对 PAC 支持有问题，比如新浪微博，比如微信公众号文章看不到图片，建议手动代理
3. 好
4. 网页端打不开的问题 README 里有解释
> ....
> 和网页版 (需要自签证书，需要脚本配合)
>
> 目前除 UWP 外其它客户端均优先请求 HTTPS 接口，默认配置下本代理对网易云所有 HTTPS API 连接> 返回空数据，促使客户端降级使用 HTTP 接口 (新版 Linux 客户端和 macOS 客户端已无法降级)

网页版的 HTTPS 连接默认配置下会全部阻断
要使用网页版需要证书，方便一点安装仓库自带的就行，要在网页版使用解锁灰色功能的话需要油猴脚本配合，具体看 https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-477870013

**Comment by AckyLin** [comment]
> emmm 我看到你 star 了 Nroxy，可以用吗？
> 那个项目目前不支持 Android 10，10 以下的版本可以用的
> 有其他问题在那边提 issue 就行
> 
> 另外，可以使用 goproxy / glider 转化成 ss 协议再使用小飞机
> https://github.com/snail007/goproxy

你好，我用goproxy已转换成ss 协议。
苹果端用shadowrocket，配置好default.conf就可以使用了
安卓端用的是v2rayNg和shadowsocks，发现两个在服务端都可以下载到音乐，返回客户端就播放不了。是缺了什么配置吗

**Comment by nondanee** [comment]
@AckyLin 
你的  `-e` 设了什么？安卓端不需要 `-e`，先去掉试一下（去掉以后 ios 不可用，仅做测试）

**Comment by AckyLin** [comment]
> @AckyLin 
> 
> 你的  `-e` 设了什么？安卓端不需要 `-e`，先去掉试一下（去掉以后 ios 不可用，仅做测试）
> 
> 

试了，客户端无法播放不行
