### ISSUE TITLE
IOS点击我的消息后播放失败

### ISSUE THREAD

**Issue by bytxk** [nondanee/UnblockNeteaseMusic#431]
谷歌云香港vps部署的服务，ios 网易云上可点亮可播放音乐，但是点击 右下角账号-我的消息或我的好友或个人主页后，显示获取数据失败，之后网易云就不能播放歌曲不能搜索，点击歌曲显示获取播放信息失败，打开surge显示socket closed by remote peer，需要等几分钟网络才能恢复。

**Comment by bytxk** [comment]
代理规则DOMAIN-SUFFIX,music.126.net,DIRECT
USER-AGENT,NeteaseMusic*,🎸 NeteaseMusic
DOMAIN-SUFFIX,music.163.com,🎸 NeteaseMusic

**Comment by bytxk** [comment]
![DF563C90-C872-451E-84DB-616BC2FE654F](https://user-images.githubusercontent.com/62052872/76608581-d72c1180-6550-11ea-9695-416c242b3aee.jpeg)

**Comment by bytxk** [comment]
![01F3BF18-044B-4AE7-A5B2-5C3486A7803E](https://user-images.githubusercontent.com/62052872/76608632-ead77800-6550-11ea-819b-1cb8bb6c4705.png)

**Comment by nondanee** [comment]
证书安装了吗？

**Comment by bytxk** [comment]
> 证书安装了吗？

平时使用的surge Mitm，平时可以正常解锁灰色和播放，但是每次自动退出或强制退出网易云后台后，再次进入网易云也需要等一分钟左右才能和服务器连上，之后就可以正常使用。我今天试了下载您提供的证书，结果还是一样，无法点击我的消息

**Comment by bytxk** [comment]
服务端配置pm2 start app.js -i 3 --name UnblockNeteaseMusic --watch --max_memory_restart 100M -- -e https://music.163.com -p 5200:5201

**Comment by bytxk** [comment]
pm2 start app.js -i 3 --name UnblockNeteaseMusic  -- max_memory_restart 100M -- -e https://music.163.com -p 5200:5201

**Comment by nondanee** [comment]
那么 surge MITM 有效果吗？
surge MITM 是不是只有 surge 自己可以解密查看，发到代理的还是 https 啊？

**Comment by bytxk** [comment]
1|UnblockNeteaseMusic  | MITM > music.163.com 
2|UnblockNeteaseMusic  | TUNNEL > localhost:5200
0|UnblockNeteaseMusic  | MITM > music.163.com 
1|UnblockNeteaseMusic  | TUNNEL > localhost:5200
2|UnblockNeteaseMusic  | MITM > music.163.com 
0|UnblockNeteaseMusic  | TUNNEL > localhost:5200
2|UnblockNeteaseMusic  | TUNNEL > localhost:5200
1|UnblockNeteaseMusic  | MITM > music.163.com 
0|UnblockNeteaseMusic  | MITM > interface.music.163.com 
1|UnblockNeteaseMusic  | TUNNEL > localhost:5200
2|UnblockNeteaseMusic  | MITM > music.163.com 
0|UnblockNeteaseMusic  | TUNNEL > localhost:5200
1|UnblockNeteaseMusic  | MITM > interface.music.163.com 
2|UnblockNeteaseMusic  | TUNNEL > localhost:5200
0|UnblockNeteaseMusic  | MITM > interface.music.163.com 
1|UnblockNeteaseMusic  | TUNNEL > localhost:5200
0|UnblockNeteaseMusic  | TUNNEL > localhost:5200
2|UnblockNeteaseMusic  | MITM > interface.music.163.com 
1|UnblockNeteaseMusic  | MITM > interface.music.163.com 
2|UnblockNeteaseMusic  | TUNNEL > localhost:5200
1|UnblockNeteaseMusic  | [1378491298] 愛にできることはまだあるかい
1|UnblockNeteaseMusic  | http://other.player.nf01.sycdn.kuwo.cn/18c6478b471eb644e85e6bdd697c0ed5/5e6ba190/resource/
n1/77/27/1361794173.mp3
0|UnblockNeteaseMusic  | MITM > interface.music.163.com 
1|UnblockNeteaseMusic  | TUNNEL > localhost:5200
2|UnblockNeteaseMusic  | MITM > music.163.com 
0|UnblockNeteaseMusic  | [1378491298] 愛にできることはまだあるかい
0|UnblockNeteaseMusic  | http://other.player.nf01.sycdn.kuwo.cn/81a8f5c3e42fdfeaf60fa690ad337696/5e6ba192/resource/
n1/77/27/1361794173.mp3
0|UnblockNeteaseMusic  | TUNNEL > localhost:5201
2|UnblockNeteaseMusic  | MITM > other.player.nf01.sycdn.kuwo.cn (ssl)
1|UnblockNeteaseMusic  | TUNNEL > localhost:5200
2|UnblockNeteaseMusic  | MITM > interface.music.163.com 
0|UnblockNeteaseMusic  | TUNNEL > localhost:5200
1|UnblockNeteaseMusic  | MITM > interface.music.163.com 
2|UnblockNeteaseMusic  | [1378491298] 愛にできることはまだあるかい
2|UnblockNeteaseMusic  | http://other.player.nf01.sycdn.kuwo.cn/d89b54da172c7033c21063960228369a/5e6ba197/resource/
n1/77/27/1361794173.mp3

**Comment by bytxk** [comment]
surge MITM情况下日志 ios端可以播放

**Comment by bytxk** [comment]
1|UnblockNeteaseMusic  | [1378491298] 愛にできることはまだあるかい
1|UnblockNeteaseMusic  | http://other.player.nf01.sycdn.kuwo.cn/444302c3b5b3d18c98550c5f39287414/5e6ba199/resource/
n1/77/27/1361794173.mp3
2|UnblockNeteaseMusic  | MITM > other.player.nf01.sycdn.kuwo.cn (ssl)
0|UnblockNeteaseMusic  | TUNNEL > localhost:5200
2|UnblockNeteaseMusic  | TUNNEL > localhost:5200
1|UnblockNeteaseMusic  | MITM > interface.music.163.com 
0|UnblockNeteaseMusic  | TUNNEL > localhost:5200
1|UnblockNeteaseMusic  | MITM > interface.music.163.com 
2|UnblockNeteaseMusic  | MITM > interface.music.163.com 
2|UnblockNeteaseMusic  | TUNNEL > localhost:5201
1|UnblockNeteaseMusic  | MITM > other.player.nf01.sycdn.kuwo.cn (ssl)
0|UnblockNeteaseMusic  | TUNNEL > localhost:5200
1|UnblockNeteaseMusic  | MITM > interface.music.163.com 
2|UnblockNeteaseMusic  | TUNNEL > localhost:5200
0|UnblockNeteaseMusic  | MITM > interface.music.163.com 
1|UnblockNeteaseMusic  | TUNNEL > localhost:5200
0|UnblockNeteaseMusic  | TUNNEL > localhost:5201
2|UnblockNeteaseMusic  | MITM > interface.music.163.com 
2|UnblockNeteaseMusic  | TUNNEL > localhost:5200
0|UnblockNeteaseMusic  | MITM > music.163.com 
1|UnblockNeteaseMusic  | TUNNEL > localhost:5200
0|UnblockNeteaseMusic  | TUNNEL > localhost:5201
这是点击我的消息之后的日志，ios网易云客服端这时候已经显示网络不给力了，打开surge查看连接失败 socket closed by remote peer，等一分钟左右可恢复正常

**Comment by bytxk** [comment]
我试过关闭MITM，使用下载的证书，也可以播放，但是也是一点我的消息或者我的好友就网络断开

**Comment by nondanee** [comment]
嗯，看到了，发到代理的 api 请求全部是 http
```
MITM > other.player.nf01.sycdn.kuwo.cn (ssl)
```
但是这个是 package 链接就是 https 的
api 接口全都不是 https MITM

下载证书的话会不会有
```
MITM > music.163.com (ssl)
```
这样的 log 呢？
没有的话就比较麻烦了，估计是不被信任了

然后你确认一下安装有没有遗漏步骤
https://support.apple.com/zh-cn/HT204477

**Comment by bytxk** [comment]
2|UnblockNeteaseMusic  | MITM > interface.music.163.com 
0|UnblockNeteaseMusic  | TUNNEL > localhost:5200
1|UnblockNeteaseMusic  | MITM > interface.music.163.com 
2|UnblockNeteaseMusic  | [1371144017] カタルシスト
2|UnblockNeteaseMusic  | http://sd.sycdn.kuwo.cn/d73a823fc359b3ff641e9c406807f9fe/5e6bad7e/resource/n3/97/57/231945
9692.mp3
1|UnblockNeteaseMusic  | MITM > interface.music.163.com 
1|UnblockNeteaseMusic  | [1371144017] カタルシスト
1|UnblockNeteaseMusic  | http://sd.sycdn.kuwo.cn/f245e5087fc64380c8ee76d6caa81fcb/5e6bad81/resource/n3/97/57/231945
9692.mp3
2|UnblockNeteaseMusic  | TUNNEL > localhost:5201
1|UnblockNeteaseMusic  | MITM > sd.sycdn.kuwo.cn (ssl)
0|UnblockNeteaseMusic  | TUNNEL > localhost:5200
1|UnblockNeteaseMusic  | MITM > interface.music.163.com 
1|UnblockNeteaseMusic  | [22735517] Sorry (Dear. Daddy)
1|UnblockNeteaseMusic  | http://no01.sycdn.kuwo.cn/33fd023fce14d14b7329d95f8683b8ad/5e6bad89/resource/n1/95/90/7194
72868.mp3
2|UnblockNeteaseMusic  | TUNNEL > localhost:5200
0|UnblockNeteaseMusic  | MITM > interface.music.163.com 
0|UnblockNeteaseMusic  | [22735517] Sorry (Dear. Daddy)
0|UnblockNeteaseMusic  | http://no01.sycdn.kuwo.cn/f046670cbe122dd2bdaa67f45ddd119b/5e6bad8e/resource/n1/95/90/7194
72868.mp3
1|UnblockNeteaseMusic  | TUNNEL > localhost:5200
0|UnblockNeteaseMusic  | TUNNEL > localhost:5200
1|UnblockNeteaseMusic  | MITM > interface.music.163.com 
1|UnblockNeteaseMusic  | [22735517] Sorry (Dear. Daddy)
1|UnblockNeteaseMusic  | http://no01.sycdn.kuwo.cn/1c2ad3513eb6c0f790ca721deb42dad7/5e6bada5/resource/n1/95/90/7194
72868.mp3
2|UnblockNeteaseMusic  | TUNNEL > localhost:5201
0|UnblockNeteaseMusic  | MITM > no01.sycdn.kuwo.cn (ssl)

使用证书的情况 也有ssl

**Comment by bytxk** [comment]
AND,((URL-REGEX,.+eapi/ad/get), (USER-AGENT,NeteaseMusic*)),REJECT-TINYGIF
AND,((URL-REGEX,.+/api/log.+), (USER-AGENT,NeteaseMusic*)),DIRECT
AND,((URL-REGEX,.+/api/feedback/client/log.+), (USER-AGENT,NeteaseMusic*)),DIRECT
AND,((URL-REGEX,/eapi/batch), (USER-AGENT,NeteaseMusic*)),DIRECT
AND,((URL-REGEX,.+eapi/v1/user.+), (USER-AGENT,NeteaseMusic*)),DIRECT
AND,((URL-REGEX,/eapi/pl/count), (USER-AGENT,NeteaseMusic*)),DIRECT
AND,((URL-REGEX,.+eapi/(user|delivery|usersafe|college|sign|msg|forward|comment|topic|mlog|djradio).+), (USER-AGENT,NeteaseMusic*)),DIRECT
DOMAIN-SUFFIX,music.126.net,DIRECT
USER-AGENT,NeteaseMusic*,🎸 NeteaseMusic
DOMAIN-SUFFIX,music.163.com,🎸 NeteaseMusic
我改了规则 我的消息和我的好友请求走直连，现在可以打开了，但是打开之后去搜索音乐还是显示网络断开 无法搜索，播放音乐显示网络不给力，需要等一会网络才能恢复

**Comment by bytxk** [comment]
00:11:07.713092 Rule matched: USER-AGENT NeteaseMusic*
00:11:07.714385 Connecting with address: 服务器1
00:11:07.750694 Connected to address 服务器 in 35ms
00:11:07.767445 Disconnect with reason: Outgoing connection setup failed (Socket closed by remote peer)

**Comment by bytxk** [comment]
我用surge大概看了一下，即使修改了规则，打开我的消息我的好友的请求还是会走代理，
interface.music.163.com:80 (http://interface.music.163.com/eapi/ios/version?_nmclfl=1)
interface.music.163.com:80 (http://interface.music.163.com/eapi/usersafe/pl/count?_nmclfl=1)
原因是匹配了DOMAIN-SUFFIX,music.163.com,🎸 NeteaseMusic 规则

**Comment by bytxk** [comment]
我猜会不会是因为占用了interface.music.163.com:80 ，所以导致播放失败

**Comment by bytxk** [comment]
http://59.111.181.35/eapi/usersafe/pl/count?_nmclfl=1这种类型请求可以匹配规则走直连

**Comment by bytxk** [comment]
两种请求都可能发出 我不知道怎么将第一种也强制直连，希望有懂的人说说看

**Comment by bytxk** [comment]
打开我的好友只要出现下面这种类型请求，我的好友也可以打开，但是打开之后网易云播放歌曲网络连接一定会断开interface.music.163.com:80 (http://interface.music.163.com/eapi/ios/version?_nmclfl=1)
interface.music.163.com:80 (http://interface.music.163.com/eapi/usersafe/pl/count?_nmclfl=1)

如果是
http://interface.music.163.com/eapi/ios/version?_nmclfl=1
http://interface.music.163.com/eapi/usersafe/pl/count?_nmclfl=1，就会走直连，搜索和播放歌曲无影响。
希望大神帮忙解答一下什么原因

**Comment by nondanee** [comment]
并没有 
```
MITM > music.163.com (ssl)
```
说明客户端是直接降级到 http 请求的，不用证书都没事

你把启动参数改成
```
pm2 start app.js -i 3 --name UnblockNeteaseMusic -- max_memory_restart 100M -- -p 5200
```
关闭 surge MITM
这样肯定不能播放，仅仅为了测试
> 点了我的消息或我的好友或个人主页后，能不能搜索

interface.music.163.com:80 这个是走 TUNNEL 的，URL-REGEX 规则估计是匹配不到

**Comment by bytxk** [comment]
> 并没有
> 
> ```
> MITM > music.163.com (ssl)
> ```
> 
> 说明客户端是直接降级到 http 请求的，不用证书都没事
> 
> 你把启动参数改成
> 
> ```
> pm2 start app.js -i 3 --name UnblockNeteaseMusic -- max_memory_restart 100M -- -p 5200
> ```
> 
> 关闭 surge MITM
> 这样肯定不能播放，仅仅为了测试
> 
> > 点了我的消息或我的好友或个人主页后，能不能搜索
> 
> interface.music.163.com:80 这个是走 TUNNEL 的，URL-REGEX 规则估计是匹配不到

改了之后，歌曲可点亮，网络连接很稳定，点了我的消息或我的好友或个人主页后都能搜索，强制退出网易云后台再进也可以很快连接上，几乎没有延迟，的确不能播放音乐

**Comment by bytxk** [comment]
0|UnblockNeteaseMusic  | MITM > interface.music.163.com 
1|UnblockNeteaseMusic  | MITM > music.163.com 
0|UnblockNeteaseMusic  | MITM > music.163.com 
2|UnblockNeteaseMusic  | MITM > interface.music.163.com 
1|UnblockNeteaseMusic  | [185910] 四面楚歌
1|UnblockNeteaseMusic  | http://other.player.ra01.sycdn.kuwo.cn/d820dacb3692f39694f48663ad8f33fd/5e6cb508/resource/
n2/320/41/40/1182795548.mp3
1|UnblockNeteaseMusic  | MITM > music.163.com 
0|UnblockNeteaseMusic  | MITM > music.163.com 
2|UnblockNeteaseMusic  | MITM > music.163.com 
1|UnblockNeteaseMusic  | MITM > music.163.com 
0|UnblockNeteaseMusic  | MITM > music.163.com 
2|UnblockNeteaseMusic  | MITM > music.163.com 
1|UnblockNeteaseMusic  | MITM > music.163.com 
0|UnblockNeteaseMusic  | MITM > music.163.com 
2|UnblockNeteaseMusic  | MITM > music.163.com 
1|UnblockNeteaseMusic  | MITM > interface.music.163.com 
0|UnblockNeteaseMusic  | MITM > interface.music.163.com 
2|UnblockNeteaseMusic  | MITM > interface.music.163.com 
1|UnblockNeteaseMusic  | MITM > interface.music.163.com 
0|UnblockNeteaseMusic  | MITM > interface.music.163.com 
2|UnblockNeteaseMusic  | [185813] 阳光宅男
2|UnblockNeteaseMusic  | http://other.player.ra01.sycdn.kuwo.cn/966945f1cd5096d451fc4e6d6dae2323/5e6cb526/resource/
n3/320/60/74/1234316213.mp3
2|UnblockNeteaseMusic  | MITM > music.163.com 
1|UnblockNeteaseMusic  | MITM > music.163.com 
0|UnblockNeteaseMusic  | MITM > interface.music.163.com 
2|UnblockNeteaseMusic  | MITM > interface.music.163.com 
1|UnblockNeteaseMusic  | TUNNEL - interface.music.163.com:443
0|UnblockNeteaseMusic  | TUNNEL - interface.music.163.com:443
2|UnblockNeteaseMusic  | TUNNEL - interface.music.163.com:443
1|UnblockNeteaseMusic  | TUNNEL - interface.music.163.com:443
改之后的日志

改完之后用最简单的规则也可以连接
SUFFIX,music.126.net,DIRECT
USER-AGENT,NeteaseMusic*,🎸 NeteaseMusic
DOMAIN-SUFFIX,music.163.com,🎸 NeteaseMusic

之前用这个规则打不开我的消息或我的好友

**Comment by nondanee** [comment]
好的，那再配个 https endpoint 就能播放了

**Comment by bytxk** [comment]
> 好的，那再配个 https endpoint 就能播放了
请问是这种吗
pm2 start app.js -i 3 --name UnblockNeteaseMusic --max-memory-restart 100M -- -e https://music.163.com -p 5200
不需要转发端口了吗，方便的话能不能说一下开始连接失败的原因，我想了解一下

**Comment by nondanee** [comment]
不是，要配个公网可信任的 https 站点作为 endpoint，不能用 https://music.163.com 
自己有域名做一个站或者用云函数 / PaaS / Cloudflare worker 等等做一个都可以

不知道原因

**Comment by bytxk** [comment]
我有一个域名，但是已经用来转发了v2ray的流量，不知道可不可以用同一个

**Comment by bytxk** [comment]
我刚刚搜了一下，还不是很懂，复杂吗？

**Comment by nondanee** [comment]
可以用同一个
不复杂，就是普通的 https 网站搭建过程，网上教程应该蛮多的
反向代理到代理的 http 端口上就行了

用 caddy 配置比较短
自己搜一下 caddy 怎么用 caddyfile 怎么写
(issue 里搜也有，就是和其他内容混在一起了，有点不好找)

或者用 nginx，配置写的比较多，见 https://github.com/nondanee/UnblockNeteaseMusic/issues/65#issue-439169649

**Comment by bytxk** [comment]
算了吧 我先将就用吧 我怕万一跟v2ray冲突了

**Comment by nondanee** [comment]
好👌
