### ISSUE TITLE
Linux客户端使用代理模式一定要安装证书吗？

### ISSUE THREAD

**Issue by kevinMintnick** [nondanee/UnblockNeteaseMusic#432]

**Comment by yangon99** [comment]
readme里有写啊

> Linux 客户端 (1.2 版本以上需要自签证书 MITM，启动客户端需要增加 --ignore-certificate-errors 参数)

具体也许可以参考 #208

**Comment by nondanee** [comment]
@kevinMintnick 
不需要安装，因为系统上安装了客户端也不会信任，启动加参数 ignore 就行了
