### ISSUE TITLE
IOS播放显示网络不给力

### ISSUE THREAD

**Issue by cilone** [nondanee/UnblockNeteaseMusic#433]
GCP台湾VPS上部署的，mac上使用没问题，IOS上可显示歌曲但不能播放，提示“播放失败，网络不给力，无法继续播放”，请大佬给看看是哪里的问题，感谢！
按照以下步骤部署的
①拉取项目代码：
git clone https://github.com/nondanee/UnblockNeteaseMusic.git
cd UnblockNeteaseMusic
②安装Docker：
#CentOS 7、Debian、Ubuntu
curl -sSL https://get.docker.com/ | sh
systemctl start docker
systemctl enable docker
③运行镜像：
docker run --restart=always --name unmusic -d -p 4567:8080 nondanee/unblockneteasemusic

ios用小火箭代理的，已安装证书并信任，ios代理设置如下：
![WechatIMG24](https://user-images.githubusercontent.com/5538302/76672655-46e5df00-65d9-11ea-845b-7b7ecf43a3b3.jpeg)
![WechatIMG25](https://user-images.githubusercontent.com/5538302/76672656-49e0cf80-65d9-11ea-9526-7bbd9ba9c1a4.jpeg)

**Comment by bytxk** [comment]
vps端还需要加启动参数-e https://music.163.com

**Comment by cilone** [comment]
> vps端还需要加启动参数-e https://music.163.com

加上后mac下也播放不了。

**Comment by nondanee** [comment]
docker run 改成
```sh
docker run --restart=always --name unmusic -d -p 4567:8080 nondanee/unblockneteasemusic -p 8080:8081 -e http://music.163.com
```
安装 CA 证书 https://raw.githubusercontent.com/nondanee/UnblockNeteaseMusic/master/ca.crt
并手动信任，参考 https://support.apple.com/zh-cn/HT204477

**Comment by cilone** [comment]
> https://raw.githubusercontent.com/nondanee/UnblockNeteaseMusic/master/ca.crt

感谢！IOS上也可以了，之前也加过-e但是不行，又重新弄了下，把证书删了重新安装信任后可以了。

**Comment by cilone** [comment]
感谢！IOS上也可以了，之前也加过-e但是不行，又重新弄了下，把证书删了重新安装信任后可以了。

**Comment by nondanee** [comment]
好👌

**Comment by solxnp** [comment]
> 好👌

请问下，我这边不是用的docker，我是直接在自己服务器上git clone 然后 node app.js -e https://music.163.com启动的
证书也安装并信任
小飞机也添加了规则，但全局路由不论是选择代理还是配置，进网易云都访问不了任何歌单，这是怎么回事

**Comment by Ruoxhy** [comment]
> > vps端还需要加启动参数-e https://music.163.com
> 
> 加上后mac下也播放不了。

我和你一样的问题。请问你是如何解决的？谢谢
