### ISSUE TITLE
音乐链接正常解析，windows网易云音乐无法播放

### ISSUE THREAD

**Issue by zhxiaoping** [nondanee/UnblockNeteaseMusic#435]
版本说明：
 UnblockNeteaseMusic 0.24.1
windows 网易云音乐客户端 2.7.1

UnblockNeteaseMusic 日志：
![捕获](https://user-images.githubusercontent.com/47968604/76685468-da0d2c00-664e-11ea-9376-e787a4ebf7ee.PNG)
启动命令：
24388 root      619m S    node /usr/share/UnblockNeteaseMusic/app.js -e https://music.163.com -p 5201:5202 -o migu
24389 root      607m S    node /usr/share/UnblockNeteaseMusic/app.js -p 5200 -o migu

问题说明
点击解析音乐链接可播放，尝试切换换音源，其他歌曲，客户端均无法播放vip歌曲。

**Comment by nondanee** [comment]
使用默认参数，我无法复现
路由器插件默认加了什么参数我不清楚
如果将 endpoint 设为 https://music..163.com 对 windows 客户端来说是不行的

**Comment by nondanee** [comment]
`-e https://music.163.com` 对 windows 端不适用，一定要用改成 `-e http://music.163.com`，windows 端不需要加 `-e`
(也不知道是谁教的，反正不是我教的)

**Comment by zhxiaoping** [comment]
大佬好，我用的 是lede，插件参数都是安装时默认的。按照大佬说的把插件参数改成http就好了。
感谢大佬。
