### ISSUE TITLE
Android 端代理失效

### ISSUE THREAD

**Issue by yussuy** [nondanee/UnblockNeteaseMusic#437]
采用 docker 方式部署并启动，在 Windows 端可以正常代理和使用，在 Android 端采用
`http://<Server Name:PORT>/proxy.pac`
的方式代理失败，歌曲为灰色。

**Comment by moontosea** [comment]
Android手机怎么使用？

**Comment by nondanee** [comment]
@yussuy 无法复现

**Comment by Jkkoi** [comment]
无法复现，你可以在浏览器打开 music.163.com 坚持是否代理成功

**Comment by luis-arch** [comment]
实测手机小米8，miui10.3版本，
使用Nroxy+d/node.js想实现android网易云音乐破解。
情况：无法连接music.163.com。查看node.js服务器状态下图如下：
链接：https://imgchr.com/i/8JRSmT

**Comment by nondanee** [comment]
@luis-arch 参考 #438 打开 https 端口(你的问题其实可以新提一个 issue)
