### ISSUE TITLE
Android搭配Nroxy使用時降級失敗

### ISSUE THREAD

**Issue by rti56kt** [nondanee/UnblockNeteaseMusic#438]
如題，在Android客戶端(7.0.2)搭配Nroxy食用時似乎會降級失敗，log都會顯示ip:443
![Screenshot_20200316-002318_Nroxy](https://user-images.githubusercontent.com/43367240/76705786-887fa280-671d-11ea-9892-ef08b7f2c890.png)

**Comment by nondanee** [comment]
开两个端口让证书验证失败，也会降级

**Comment by rti56kt** [comment]
已解決，感謝
