### ISSUE TITLE
非本地无法成功获取的问题

### ISSUE THREAD

**Issue by fz6m** [nondanee/UnblockNeteaseMusic#439]
反复测试了一个通宵，目前得出的几个结论：

### 成功案例：

1. 本地启动
```
node app.js -s
```
默认在 `8080` 端口上启动。

2.  Windows 客户端内使用本地网关 `127.0.0.1` 和 `8080` 端口，可以成功获取到灰曲。

### 失败案例：

**1. 服务器做出以下启动**
```
node app.js -s -p 8080 -e https://域名 
```
这种方式是之前 issue #65 IOS 食用指南 里提到的 https endpoint 方法，参考 #368 iOS配置经验分享 里介绍的第 2 个 endpoint 方案，无论是 Windows 还是 IOS 均失效。

**2. 服务器做出以下启动**
```
node app.js -s -p 80 -f Ping获得的网易服务器IP
```
这种方式应该是 issue 和网上本项目常见教程的做法了，其中 `-p` 无论是不是 `80` ，`-f` 参数是否存在均失效。
或许是本地 Host 未配置，做出以下配置
```
127.0.0.1  music.163.com
127.0.0.1  interface.music.163.com
```
同样失效，这种做法我觉得在分离式上是不对的，应该是自己的服务器 IP，于是改换了：
```
自己的服务器IP  music.163.com
自己的服务器IP  interface.music.163.com
```
同样失效。
我考虑了一下，难道是填网易服务器 IP，换为：
```
自己Ping得的网易服务器IP  music.163.com
自己Ping得的网易服务器IP  interface.music.163.com
```
同样失效。
Windows 端失败了还不够，在 ios 端采用 WLAN 代理更改 和 ShadowRocket 全局代理 两种方式测试，以上两种启动方式 所有可能的搭配 均无效。
有人在 issue #65 里提供了一种宝塔搭建，经尝试，失效。还踩了一个 nginx 版本的坑（`ssl on` 不适用了，要换成 `listen 443 ssl http2`）
IOS 证书的方法也同样试过了，失效（在最近的 issue 里已经有过反映了）
思前想后，或许 `-s` 强制模式存在问题，去掉该参数 全复试所有的可能 失效。
<br>
脚本是能获取到相应链接的，只不过本地拿不到，或许是 IOS 的 https 问题，但是这个用上面第一种方式应该已经解决了，还是失效，同样 Windows 也失效。总是超时，国内国外服务器我都试过了。
### 小总结：
或许服务器这种分离模式真的是全军覆没了，只能本地走全局网关，也可能是我测试的不全面，不过确实挺顶的。
如果哪位 dalao 有什么分离模式成功的案例希望分享一下啊呜呜呜。

**Comment by LemonPG** [comment]
今天本来想下首歌的，我发现也我的服务器也失效了。

**Comment by Jkkoi** [comment]
刚才看了一下，log里输出的网址是可以正常播放的
这就很迷惑了，难道说是各家都屏蔽了网易云音乐的 header ？

**Comment by Jkkoi** [comment]
浏览器打开了下log输出的网址，发现播放两三秒后就会卡顿一下，感觉像是酷我的外链做了限制（或者崩了？）
等有空换源做进一步测试

**Comment by fz6m** [comment]
> 浏览器打开了下log输出的网址，发现播放两三秒后就会卡顿一下，感觉像是酷我的外链做了限制（或者崩了？）
> 等有空换源做进一步测试

我昨晚也试过不同音源的，都没用，虽然能获取链接但是拿不到本地

**Comment by Jkkoi** [comment]
> > 浏览器打开了下log输出的网址，发现播放两三秒后就会卡顿一下，感觉像是酷我的外链做了限制（或者崩了？）
> > 等有空换源做进一步测试
> 
> 我昨晚也试过不同音源的，都没用，虽然能获取链接但是拿不到本地

我这边是能够正常播放 1-4 秒，然后缓存失败，和我之间打开链接的结果一致

**Comment by fz6m** [comment]
> > > 浏览器打开了下log输出的网址，发现播放两三秒后就会卡顿一下，感觉像是酷我的外链做了限制（或者崩了？）
> > > 等有空换源做进一步测试
> > 
> > 
> > 我昨晚也试过不同音源的，都没用，虽然能获取链接但是拿不到本地
> 
> 我这边是能够正常播放 1-4 秒，然后缓存失败，和我之间打开链接的结果一致

你是服务器获取，分离式的吗，试试本地加代理（我感觉都不行了，可能是客户端防止第三方的对策）

**Comment by RonnyJiang** [comment]
我在aliyun ECS上跑的docker容器，在安卓手机上通过手动代理ip+port到时可以。 家里内网穿透的服务不可以了

**Comment by fz6m** [comment]
> 我在aliyun ECS上跑的docker容器，在安卓手机上通过手动代理ip+port到时可以。 家里内网穿透的服务不可以了

嗷嗷，这么说满足一定条件下，安卓应该还能活。

**Comment by fz6m** [comment]
> > > 浏览器打开了下log输出的网址，发现播放两三秒后就会卡顿一下，感觉像是酷我的外链做了限制（或者崩了？）
> > > 等有空换源做进一步测试
> > 
> > 
> > 我昨晚也试过不同音源的，都没用，虽然能获取链接但是拿不到本地
> 
> 我这边是能够正常播放 1-4 秒，然后缓存失败，和我之间打开链接的结果一致

我调试成功本地能收到了（ios），但是只能听几秒，下载也不行，推测和网易客户端识别有关（断网没用），也许这首歌的信息早就下载好了，如果和第三方获取的不一致就没法播放（比如歌词等标识不匹配就没法播放）

**Comment by nondanee** [comment]
本地和非本地没有区别

我无法定位也无法解决 iOS 的问题，你说什么就是什么，不行就不行吧

失败案例
1. 确实是严格模式的 bug，endpoint 不在白名单里，tunnel 的时候被 ban 掉了，马上修复，影响全平台 (严格模式 bug 确实多==)

测试不开严格模式 Windows 端用 https endpoint 没有问题

![image](https://user-images.githubusercontent.com/26399680/76878857-60747880-68b0-11ea-8016-1e3ec96e19ef.png)

2. 改 hosts 在 windows 端失效了
这个没的说，因为不知道具体是从什么版本开始的，所以 README 里一直没写 windows 端改 hosts 失效==
如果你知道可以告诉我
https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-554661621
https://github.com/nondanee/UnblockNeteaseMusic/issues/336#issuecomment-564084754
https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-569512739
这个要解决也很简单，退到之前的版本

iOS 的问题我不管

**Comment by nondanee** [comment]
@Jkkoi 
目前没观察到酷我有外链限制
浏览器打开链接都有问题的话，是网络问题的可能性比较大
