### ISSUE TITLE
MacOs更新云音乐客户端出现网络错误

### ISSUE THREAD

**Issue by zpx2012** [nondanee/UnblockNeteaseMusic#443]
昨天更新客户端了之后，一打开客户端就是“网络连接失败请重试”， 点击播放一直出现“播放失败，网络错误，请检查网络设置“，看代理输出是有走代理的。

![image](https://user-images.githubusercontent.com/7723235/76899024-0b0a7e00-6854-11ea-8e55-5d1d9b649825.png)

![image](https://user-images.githubusercontent.com/7723235/76892484-06d86380-6848-11ea-828f-908320754944.png)

**Comment by nondanee** [comment]
更新前是什么版本？更新后是什么版本？

**Comment by zpx2012** [comment]
当前版本2.3.2，更新前没记，是2.0之前

**Comment by nondanee** [comment]
那你看看这个吧 https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-477870013

**Comment by zpx2012** [comment]
好的， 回滚了，试了自签证书也没用，还是1.5.10那个可以用。谢谢。

**Comment by nondanee** [comment]
好的

我最近测试过自签证书可以用的 https://github.com/nondanee/UnblockNeteaseMusic/issues/411#issuecomment-593549539
可能是有个体差异

用旧版本也行，反正能用就行

**Comment by RYOTENG** [comment]
你是不是在OpenWRT里安装了解锁网易云灰色歌曲的插件？
