### ISSUE TITLE
android端显示“资源不存在”，但PC端可正常运行

### ISSUE THREAD

**Issue by luis-arch** [nondanee/UnblockNeteaseMusic#445]
android配置：Nroxy+dnode配置成功，前几天都可以正常听歌（周杰伦+taylor）。
今天下午android端出现“资源不存在”，付费资源出现“请付费”的消息。马上检查windows端，发现一切正常，这是什么情况。
另：一些本身是灰色音乐的歌曲（如周杰伦的live）都可以正常在android端收听，实在搞不太懂，请问您有出现类似情况吗？您有什么建议吗

**Comment by nondanee** [comment]
我这边无法复现
nroxy 和代理的实现机制不一样，没有可比性
目前是否会显示灰色？
客户端有缓存，建议清缓存后再试一试本身是灰色的歌曲

**Comment by luis-arch** [comment]
谢谢您的及时回复
以下是启动Nroxy在android端的结果
链接:https://imgchr.com/i/848DyD
链接:https://imgchr.com/i/8480SK
链接:https://imgchr.com/i/848aJx
我将网易云(当前版本 V4.3.1 567509)所有数据全部删除后，依然得到上述链接结果。可以看到的是由于代理启动，列表灰色歌曲已全部恢复正常，但奇怪的是，我只能听部分歌曲，如"说好不哭"等歌曲却无法播放，显示资源不存在。这令我十分不解。

另附没开nroxy代理时，歌曲资源如下所示:
链接:https://imgchr.com/i/84GC79

这就是我所能展现的全部情况了，希望对您找到原因有用处。再次感谢您能看到这里。

**Comment by nondanee** [comment]
我试了下还是无法复现 (v4.3.1.077776)

<img src="https://user-images.githubusercontent.com/26399680/77247752-f58bbe80-6c6e-11ea-8e89-b246fc0f7a16.jpg" height="640"/>

你的启动参数是什么？

**Comment by luis-arch** [comment]
我是直接dnode启动app.js 
app.js内容为

#!/usr/bin/env node
Array.prototype.push.apply(process.argv, '-p 1123:1124 -a 127.0.0.1 -o qq'.split(/\s/g))
require('./src/app')

nroxy打开1123http端口

**Comment by nondanee** [comment]
你之前用的应该不是这个配置吧？
只启用 QQ 源的话确实是只能听部分歌曲
用这个配置大部分周杰伦和 Taylor 的歌应该都不能听

但是 英雄(live) 和 说好不哭 是可以的
和你的描述不太一样

Nroxy 的 log 有匹配结果吗？

**Comment by luis-arch** [comment]
感谢您的热心，我已经弄好了。(也是我不太注意看readme了)
配置大概为去除app.js中的-o选项就可以了(这样默认选中joos盗版源)
另外我找了找，找不到nroxy的log，不知道存放在哪里呢，如开发者需要log，我可以去帮您看看。

**Comment by nondanee** [comment]
好的

> 使用 QQ / 虾米 / 百度 / 酷狗 / 酷我 / 咪咕 / JOOX 音源替换变灰歌曲链接 (默认仅启用一、五、六)

默认音源是 QQ、酷我、咪咕
(JOOX 是腾讯子公司)

nroxy 不存储 log，node 程序运行时会在首屏输出 log
若从多任务卡片中划去，再次打开 APP 时输出会清空

**Comment by luis-arch** [comment]
再次感谢开发者

**Comment by NewBugger** [comment]
> 好的
> 
> > 使用 QQ / 虾米 / 百度 / 酷狗 / 酷我 / 咪咕 / JOOX 音源替换变灰歌曲链接 (默认仅启用一、五、六)
> 
> 默认音源是 QQ、酷我、咪咕
> (JOOX 是腾讯子公司)
> 
> nroxy 不存储 log，node 程序运行时会在首屏输出 log
> 若从多任务卡片中划去，再次打开 APP 时输出会清空

请问默认音源在哪定义

**Comment by nondanee** [comment]
@NewBugger 
默认音源在 provider/match.js 中定义
https://github.com/nondanee/UnblockNeteaseMusic/blob/2498a5d31769679956ebef5be0ad73c051585fda/src/provider/match.js#L18

配置项见 https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-429515355
