### ISSUE TITLE
tcp 连接不会自动断开

### ISSUE THREAD

**Issue by lovemegowin** [nondanee/UnblockNeteaseMusic#448]
![image](https://user-images.githubusercontent.com/25566683/77273060-a042c200-6ced-11ea-82ad-7a3fd3645707.png)
如图 跑一段时间后 会有大量的 ESTABLISHED CLOSE_WAIT 的 tcp 连接
然后 -s 灰色的歌听不了

**Comment by lovemegowin** [comment]
一种解决方案 
sysctl -a |grep keepalive 查看默认的配置
> net.ipv4.tcp_keepalive_time = 7200
net.ipv4.tcp_keepalive_probes = 9
net.ipv4.tcp_keepalive_intvl = 75

把 net.ipv4.tcp_keepalive_time = 7200 改成小一点

> sudo vim /etc/sysctl.conf
net.ipv4.tcp_keepalive_time = 200 
// 重启配置
sudo sysctl -p

**Comment by Jkkoi** [comment]
@nondanee
