### ISSUE TITLE
显示TUNNEL的时候客户端会网络异常

### ISSUE THREAD

**Issue by chy9002** [nondanee/UnblockNeteaseMusic#45]
我是挂载NAS的Docker，有公网IP走DDNS。如果我通过Clash走HTTP代理music.163.com和interface.music163.com。就会显示TUNNEL - music.163.com:80, 客户端显示网络异常。

如果通过Proxifier同样走HTTP代理，则是MITM > music.163.com. 能够正常工作。所以我有点懵，不知道是哪儿出了问题。麻烦指导以下。

![image](https://user-images.githubusercontent.com/7344772/53557335-a618b300-3b80-11e9-8888-2d089dcc1df7.png)

**Comment by nondanee** [comment]
这是 clash 的行为，一般 http 流量不会走隧道代理。tunnel 那边因为一般是加密的 https 流量，为了客户端降级 http 直接截断了。
参考资料:
https://imququ.com/post/web-proxy.html

**Comment by chy9002** [comment]
@nondanee 谢谢，我先关掉issue, 如果我找到兼容clash的解决方案会更新到这里。

**Comment by nondanee** [comment]
@chy9002 
这个问题好像 clash 那边解决了 https://github.com/Dreamacro/clash/pull/112#issuecomment-468484399

**Comment by nondanee** [comment]
@chy9002 
啊我看错了， clash 那边还没 merge
不过我这边应该已经兼容 clash 的方式了，有空的话麻烦测试一下，谢谢

**Comment by iDesperad0** [comment]
挖个焚，请问是否找到兼容clash的解决方案了？
