### ISSUE TITLE
电脑客户端无法播放了~

### ISSUE THREAD

**Issue by mingwei900** [nondanee/UnblockNeteaseMusic#450]
电脑无法播放，但是手机可以，安卓没测试~但IOS可以正常播放周董 的歌。

**Comment by nondanee** [comment]
win 还是 mac ？之前可以吗？有什么前提条件吗？启动参数是什么？客户端版本？我应该怎么复现？

**Comment by mingwei900** [comment]
启动命令是node /media/AiDisk_a1/UnblockNeteaseMusic-master/app.js -s -e https://music.163.com -p 5200:5201
上个月记得还是可以的。客户端是最新版本，试过2.7.0的版本也不行。

**Comment by nondanee** [comment]
那你肯定记错了
windows 端不能写成 `-e https://music.163.com`
请改成 `-e http://music.163.com`

**Comment by mingwei900** [comment]
> 那你肯定记错了
> windows 端不能写成 `-e https://music.163.com`
> 请改成 `-e http://music.163.com`

好的，我试试。感谢！

**Comment by mingwei900** [comment]
> 那你肯定记错了
> windows 端不能写成 `-e https://music.163.com`
> 请改成 `-e http://music.163.com`

果然成功了，非常感谢。
