### ISSUE TITLE
endpoint方式不能使用子域名

### ISSUE THREAD

**Issue by maxzh0916** [nondanee/UnblockNeteaseMusic#453]
相同配置相同启动项测试时
`node app.js -s -p 163 -e https://example.com`正常可用
`node app.js -s -p 163 -e https://music.example.com`不可用
IOS端配置不变，使用子域名时会跳到59.111.181.38等几个IP上，顶级域名就没问题

**Comment by nondanee** [comment]
不太可能

**Comment by maxzh0916** [comment]
已经解决了。子域名可以使用。谢谢！
