### ISSUE TITLE
征求意见: 是否可以添加屏蔽广告的功能

### ISSUE THREAD

**Issue by binsee** [nondanee/UnblockNeteaseMusic#455]
目前自用的代码已经实现了屏蔽 安卓/PC 端的**首屏、Banner**广告，但对是否提交pr存有疑虑，希望征求下意见。

1. 云音乐的广告其实比较少，只看到首屏和Banner有广告位，对日常使用影响不大（对比其他app并不流氓），因此是否添加此支持可有可无。
2. 云音乐的广告也算是其的一笔收入来源，其可怜的有效歌库数量也是此项目的诞生原因之一。不添加屏蔽广告的功能也算对其的一种支持和认可（？）
3. 添加广告屏蔽功能可能惹来通知函，影响此项目。
4. 对非付费用户来说，屏蔽仅有的广告只是满足强迫症而已。

看看大家是什么意见，我再决定是否提交pr。
最后，有条件的还是上vip比较好。

另外，通过观察数据发现，云音乐很频繁的上传地理位置数据（gps位置），主要用于广告相关。且查看了其隐私协议，确实有注明利用地址位置数据来实现个性化广告的推送。
个人还是比较反感隐私数据上传的，虽然现在很多隐私数据都满天飞，但能少点泄露渠道还是少点好。

**Comment by nondanee** [comment]
其实广告还是蛮多的
评论区，分享页，搜索页，日推等都有

我不会 merge 的
说实话，音效的 PR 我也不太想 merge

还是那句话
愿意留在网易云的话，充个黑胶不过分吧

**Comment by binsee** [comment]
ok，那我就都close了

**Comment by nondanee** [comment]
👌 谢谢理解
