### ISSUE TITLE
## 自签证书

### ISSUE THREAD

**Issue by jovechina** [nondanee/UnblockNeteaseMusic#458]
```
# 生成 CA 私钥
openssl genrsa -out ca.key 2048

# 生成 CA 证书 ("YOURNAME" 处填上你自己的名字)
openssl req -x509 -new -nodes -key ca.key -sha256 -days 1825 -out ca.crt -subj "/C=CN/CN=UnblockNeteaseMusic Root CA/O=YOURNAME"

# 生成服务器私钥
openssl genrsa -out server.key 2048

# 生成证书签发请求
openssl req -new -sha256 -key server.key -out server.csr -subj "/C=CN/L=Hangzhou/O=NetEase (Hangzhou) Network Co., Ltd/OU=IT Dept./CN=*.music.163.com"

# 使用 CA 签发服务器证书
openssl x509 -req -extfile <(printf "subjectAltName=DNS:music.163.com,DNS:*.music.163.com") -days 365 -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out server.crt
```
以上签名方式在MAC的新OS版本上出现不能使用的问题，使用代码中的自带的签名可以正常使用。
MAC OS 10.15.3
LibreSSL 2.8.3

**Comment by nondanee** [comment]
？

**Comment by nondanee** [comment]
"不能使用" 是怎么个不能使用法呢？都没有具体描述的吗？

先看看是不是这个问题 #403 

如果是，找一台 linux 签证书

**Comment by nondanee** [comment]
还有你签的证书打个包发一下，我试试看

**Comment by henry2au** [comment]
根据苹果最新要求：https://support.apple.com/en-us/HT210176
里面有这一项：TLS server certificates must contain an ExtendedKeyUsage (EKU) extension containing the id-kp-serverAuth OID.

我尝试了：
openssl x509  -req -extfile <(printf "subjectAltName=DNS:music.163.com,DNS:*.music.163.com\nextendedKeyUsage=serverAuth,clientAuth") -days 365 -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out server.crt

还是有点问题：
<img width="647" alt="Screen Shot 2020-03-28 at 4 52 32 am" src="https://user-images.githubusercontent.com/5416751/77785262-0776c280-70b0-11ea-97d7-1001ac554a06.png">

**Comment by nondanee** [comment]
@henry2au 
我查了好久最后发现是没加 `-sha256`，好气啊😂

```
openssl x509 -req -extfile <(printf "subjectAltName=DNS:music.163.com,DNS:*.music.163.com") -sha256 -days 365 -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial  -out server.crt
```

加或不加 extendedKeyUsage 都没有影响，加上最好

**Comment by nondanee** [comment]
@jovechina #48 里签名方式已更新

**Comment by henry2au** [comment]
@nondanee 哇哦。谢谢啦。
我以为是加了，现在看截图上证书的签名算法，其实已经有了这个信息，只是没有往这个方向去查。🤪
