### ISSUE TITLE
虾米异常

### ISSUE THREAD

**Issue by steven7851** [nondanee/UnblockNeteaseMusic#46]
search api 回应 `{"rgv587_flag":"sm","url":"https://www.taobao.com/markets/bx/deny_h5"}`

**Comment by nondanee** [comment]
我这边好像没问题，加代理也没问题。麻烦你在别的机器上测一下。

**Comment by steven7851** [comment]
找到问题了 用腾讯云或阿里云做的代理都被禁 麻烦死了

**Comment by nondanee** [comment]
check，你可以自己开 bridge，转发虾米流量。

**Comment by nondanee** [comment]
emmm，表达得不太清楚，其实只要代理 track 请求就行了，音源文件本身不用代理
1. 在你的国内服务器上跑 [bridge.js](https://github.com/nondanee/UnblockNeteaseMusic/blob/master/bridge.js)
2. 把 host 改成你自己地址
https://github.com/nondanee/UnblockNeteaseMusic/blob/01843697a47968a9f633d847039d8828e9231d43/provider/insure.js#L2
3. 把仅用于 qq 的限制去掉
https://github.com/nondanee/UnblockNeteaseMusic/blob/01843697a47968a9f633d847039d8828e9231d43/provider/insure.js#L13
