### ISSUE TITLE
求助 浏览器无法访问网络

### ISSUE THREAD

**Issue by Dylan998** [nondanee/UnblockNeteaseMusic#460]
在ubuntu 16中部属的 可以解锁 可以听歌 其他app可以上网 唯独浏览器不行 防火墙开启22 10331端口 服务器安全组开放10331 10332 采用的wifi代理
附完整代码
curl -sL https://deb.nodesource.com/setup_10.x | bash -

apt install -y nodejs git

git clone https://github.com/nondanee/UnblockNeteaseMusic.git

cd UnblockNeteaseMusic

cat > /etc/systemd/system/UnblockNeteaseMusic.service <<EOF
[Unit]
Description=UnblockNeteaseMusic
After=network.target
Wants=network.target

[Service]
Type=simple
PIDFile=/var/run/UnblockNeteaseMusic.pid
WorkingDirectory=/root/UnblockNeteaseMusic
ExecStart=$(command -v node) app.js -s -e https://music.163.com -p 10331:10332
RestartPreventExitStatus=23
Restart=always

[Install]
WantedBy=multi-user.target
EOF

systemctl start UnblockNeteaseMusic

systemctl status UnblockNeteaseMusic

ufw allow 22
ufw allow 10331
ufw enable

**Comment by nondanee** [comment]
> 其他 app 可以上网

你确定吗？wifi代理是手动还是 PAC 啊？
手动的话其他 app 也上不了网，因为你开了严格模式 `-s`

> 若将服务部署到公网，强烈建议使用严格模式 (此模式下仅放行网易云音乐所属域名的请求) `-s` 限制代理范围 (需使用 PAC 或 hosts)

**Comment by Dylan998** [comment]
> > 其他 app 可以上网
> 
> 你确定吗？wifi代理是手动还是 PAC 啊？
> 手动的话其他 app 也上不了网，因为你开了严格模式 `-s`
> 
> > 若将服务部署到公网，强烈建议使用严格模式 (此模式下仅放行网易云音乐所属域名的请求) `-s` 限制代理范围 (需使用 PAC 或 hosts)

手动 我又试了几个 微信 qq可以发消息给腾讯视频不行

**Comment by Dylan998** [comment]
> > 其他 app 可以上网
> 
> 你确定吗？wifi代理是手动还是 PAC 啊？
> 手动的话其他 app 也上不了网，因为你开了严格模式 `-s`
> 
> > 若将服务部署到公网，强烈建议使用严格模式 (此模式下仅放行网易云音乐所属域名的请求) `-s` 限制代理范围 (需使用 PAC 或 hosts)

请问是将http://vps地址:10331/proxy.pac填入wifi代理 自动吗 不是很看得懂readme 望告知

**Comment by nondanee** [comment]
是的

**Comment by Dylan998** [comment]
> 是的

我刚试了一下解锁都失效了…是我哪里没弄好吗

**Comment by nondanee** [comment]
你是 Android 吗？Android 上新版客户端好像不能用 PAC 了

**Comment by Dylan998** [comment]
> 你是 Android 吗？Android 上新版客户端好像不能用 PAC 了

ios

**Comment by Dylan998** [comment]
> 你是 Android 吗？Android 上新版客户端好像不能用 PAC 了

我下午在windows server上部署  也是wifi手动 浏览器可以上网 但是我感觉速度没有linux的快  所以又装成了ubuntu

**Comment by nondanee** [comment]
iOS 的话使用问题不清楚，可能也用不了吧

解决没网的问题把 `-s` 去掉就行了，在局域网内部署就没有滥用问题

在任何系统部署都可以，没区别

启动命令一样吗？参数不一样效果就不一样

**Comment by Dylan998** [comment]
> iOS 的话使用问题不清楚，可能也用不了吧
> 
> 解决没网的问题把 `-s` 去掉就行了，在局域网内部署就没有滥用问题
> 
> 在任何系统部署都可以，没区别
> 
> 启动命令一样吗？参数不一样效果就不一样

启动命令一样 我把-s去掉也试了 还是不行

**Comment by Dylan998** [comment]
已解决 在shadowrocket中添加http节点 然后在配置中按教程加入ua和163.com即可
