### ISSUE TITLE
浏览器脚本不能阻止「歌曲详情页面」播放按钮变灰

### ISSUE THREAD

**Issue by Jkkoi** [nondanee/UnblockNeteaseMusic#462]
搜索列表节目是正常的
![Screen Shot 2020-03-29 at 21 25 35](https://user-images.githubusercontent.com/39653010/77850271-eaeb9f00-7203-11ea-8d94-781d9fffbedd.png)
![Screen Shot 2020-03-29 at 21 24 25](https://user-images.githubusercontent.com/39653010/77850273-ecb56280-7203-11ea-9ee9-acf5e36e29ea.png)

插件信息

```
// ==UserScript==
// @name         NeteaseMusic UI Unlocker
// @namespace    https://github.com/nondanee
// @version      0.2.1
// @description  Simple UI Unblock for Netease cloud music Website
// @author       nondanee
// @match        https://music.163.com/*
// @grant        none
// ==/UserScript==
```

**Comment by nondanee** [comment]
已支持
