### ISSUE TITLE
关于 macOS 修改 hosts 网易云客户端无网络的解决办法

### ISSUE THREAD

**Issue by Jkkoi** [nondanee/UnblockNeteaseMusic#463]
先按照 [这个 issues](https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-477870013) 配置证书

然后用 `safari` 打开 [music.163.com](https://music.163.com/) ，它会提示你证书错误，点击 「继续浏览」后输入密码安装证书即可

**Comment by nondanee** [comment]
点开证书安装就行

**Comment by Jkkoi** [comment]
@nondanee  我这边 Catalina 10.15.4 直接安装证书无效，客户端还是提示无网络

**Comment by nondanee** [comment]
要手动信任的啊

**Comment by nondanee** [comment]
在 #48 里加了
