### ISSUE TITLE
请问是否只能播网易云音乐有 index 的歌？

### ISSUE THREAD

**Issue by ZhaofengWu** [nondanee/UnblockNeteaseMusic#464]
比如有些节目的歌，如果网易云音乐根本没有 index，而比如 YouTube 有，有办法播吗？Technically 很容易拿到音源，但是否无法搜索？

**Comment by nondanee** [comment]
是的，无法搜索
拿音源并不简单

Youtube Music 没有接口，Youtube API 搜出来都是视频没有歌手名称、专辑名称，造数据很难

想听什么网易云没有的直接传云盘

**Comment by ZhaofengWu** [comment]
我没有研究过具体的 request，所以不知道可不可行，但是否可能拿到 search 的 request，同时往其他 provider 发送同样的 search request，然后在网易云的搜索结果里插入其他 provider 的结果？那个搜索结果的 list 必须要有歌手、专辑吗？不可以是 empty 吗？

**Comment by nondanee** [comment]
可以，能拿到。可以搜索可以插入，不是必须的，空字符串肯定可以。
