### ISSUE TITLE
匹配到了音源却无法播放

### ISSUE THREAD

**Issue by zhuhongjie** [nondanee/UnblockNeteaseMusic#466]
如图从控制台中看到已经匹配到了音源：
![image](https://user-images.githubusercontent.com/17695023/78116069-587f1180-7436-11ea-8324-12658d0d5b7a.png)

但是windows客户端进度条不动，无法播放：
![image](https://user-images.githubusercontent.com/17695023/78116050-4ef5a980-7436-11ea-80d1-f513547961d1.png)

程序版本：最新版（npx直接拉取运行）
网易云客户端版本：2.7.1

**Comment by nondanee** [comment]
启动参数是什么？

**Comment by Grergo** [comment]
同样问题 ， 启动参数 -s -e https://music.163.com -p 8089

**Comment by nondanee** [comment]
@Grergo 改成 `-s -e http://music.163.com -p 8089`

**Comment by Grergo** [comment]
可以了，感谢开发者！

**Comment by zhuhongjie** [comment]
> 启动参数是什么？
用的默认-e参数启动的，按照你在楼上指定的http方式启动就没问题了，谢谢。
