### ISSUE TITLE
唯独安卓端无法使用？

### ISSUE THREAD

**Issue by EnderQIU** [nondanee/UnblockNeteaseMusic#467]
启动命令：
node app.js -a 192.168.1.101 -p 8080:8443

启动log：
HTTP Server running @ http://192.168.1.101:8080
HTTPS Server running @ http://192.168.1.101:8443

安卓PAC设置：
http://192.168.1.101:8080/proxy.pac

问题表现为：安卓客户端解锁不了歌曲，但Windows UWP（未安装证书），MacOS（安装了证书），iOS（未安装证书）都可以正常解锁。四台设备都是在局域网中使用。

可提供进一步的信息。

**Comment by EnderQIU** [comment]
安卓客户端当前版本：V7.1.20.641399

**Comment by tarontop** [comment]
对，我也是，本来我打算提问的，被你抢先了一步

**Comment by tarontop** [comment]
> 安卓客户端当前版本：V7.1.20.641399

但是我身边一台华为的手机用PAC能解锁，oppo试了三台都不行，只能用手动

**Comment by nondanee** [comment]
我也测过，PAC 不支持了

**Comment by EnderQIU** [comment]
> > 安卓客户端当前版本：V7.1.20.641399
> 
> 但是我身边一台华为的手机用PAC能解锁，oppo试了三台都不行，只能用手动

请问是最近的安卓客户端版本才开始失效的嘛？

**Comment by tarontop** [comment]
> > > 安卓客户端当前版本：V7.1.20.641399
> > 
> > 
> > 但是我身边一台华为的手机用PAC能解锁，oppo试了三台都不行，只能用手动
> 
> 请问是最近的安卓客户端版本才开始失效的嘛？

这我就不知道了，我只是拿了几台书记测试了一下

**Comment by EnderQIU** [comment]
> 我也测过，PAC 不支持了

请问[Issue#434](https://github.com/nondanee/UnblockNeteaseMusic/issues/434)里使用Magisk安装系统证书和改iptables的方案是否仍然有效？

**Comment by nondanee** [comment]
> > > 安卓客户端当前版本：V7.1.20.641399
> > 
> > 
> > 但是我身边一台华为的手机用PAC能解锁，oppo试了三台都不行，只能用手动
> 
> 请问是最近的安卓客户端版本才开始失效的嘛？

你可以找旧版测试

**Comment by nondanee** [comment]
> > 我也测过，PAC 不支持了
> 
> 请问[Issue#434](https://github.com/nondanee/UnblockNeteaseMusic/issues/434)里使用Magisk安装系统证书和改iptables的方案是否仍然有效？
> 
> 编辑1：已证明仍有效

uid + iptables 永久有效

**Comment by luovivi** [comment]
> > 安卓客户端当前版本：V7.1.20.641399
> 
> 但是我身边一台华为的手机用PAC能解锁，oppo试了三台都不行，只能用手动

我的华为用pac代理可以解锁，可是抖音打不开了。
