### ISSUE TITLE
怎么在OKteto 上配置unblockneteasemusic.

### ISSUE THREAD

**Issue by huguangwen** [nondanee/UnblockNeteaseMusic#469]
怎么在OKteto 上配置unblockneteasemusic.
![image](https://user-images.githubusercontent.com/32874705/78461942-dfb2da80-76ff-11ea-8d5b-119cd6533c1f.png)

![image](https://user-images.githubusercontent.com/32874705/78461947-ea6d6f80-76ff-11ea-88d6-f1ecb08e6c6d.png)
![image](https://user-images.githubusercontent.com/32874705/78461950-f0fbe700-76ff-11ea-8098-9d3e6770724d.png)

**Comment by nondanee** [comment]
不支持，代理服务器不是普通的 web server，反向代理生成的 endpoints 无法使用
同理，各种 cloud function / PaaS / BaaS，凡是当 web 托管的都无法使用
