### ISSUE TITLE
不会用，请问作者QQ多少啊

### ISSUE THREAD

**Issue by zeyouwang** [nondanee/UnblockNeteaseMusic#47]
你好 作者，我看那个说明书，我 在 源文件打开CMD窗口 输入 node app.js 它说我服务运行在 http://0.0.0.0:8080 这里，我打开网易云 客户端 还是不能下载 已经下架的歌曲，我也修改了host文件

**Comment by nondanee** [comment]
#22 说得很详细啊，用 hosts 方式按照 [使用方法②](https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-429514826) 操作即可

如果还是有困难，请邮件给我你的 QQ

**Comment by zeyouwang** [comment]
> #22 说得很详细啊，用 hosts 方式按照 [使用方法②](https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-429514826) 操作即可
> 
> 如果还是有困难，请邮件给我你的 QQ

571162904
