### ISSUE TITLE
安卓开代理抖音打不开？

### ISSUE THREAD

**Issue by luovivi** [nondanee/UnblockNeteaseMusic#470]
还有微信公众号图片加载也会变慢，抖音完全刷不出来。最新版本0.24.1

**Comment by nondanee** [comment]
有没有加 `-s`，手动代理还是 PAC？
上次测试过 PAC 下可以用抖音，(第一次打开抖音提示网络错误，但是关闭再打开就好了)，不能用快手
公众号图片 PAC 下无法加载，已知问题

**Comment by nondanee** [comment]
PAC 本身没有问题，是 app 本身不支持
之后会去掉部分 PAC 支持，桌面端用 PAC 不受影响

**Comment by luovivi** [comment]
> PAC 本身没有问题，是 app 本身不支持
> 之后会去掉部分 PAC 支持，桌面端用 PAC 不受影响

就是在安卓WiFi设置添加http://<192.168.2.1:8888>/proxy.pac这个

**Comment by luovivi** [comment]
> 有没有加 `-s`，手动代理还是 PAC？
> 上次测试过 PAC 下可以用抖音，(第一次打开抖音提示网络错误，但是关闭再打开就好了)，不能用快手
> 公众号图片 PAC 下无法加载，已知问题
没有加-S，我加上再试一下

**Comment by luovivi** [comment]
> > 有没有加 `-s`，手动代理还是 PAC？
> > 上次测试过 PAC 下可以用抖音，(第一次打开抖音提示网络错误，但是关闭再打开就好了)，不能用快手
> > 公众号图片 PAC 下无法加载，已知问题
> > 没有加-S，我加上再试一下

试了一下加-s也不行，华为手机

**Comment by nondanee** [comment]
是 PAC 的问题，用手动代理
