### ISSUE TITLE
VIP歌曲会提示试听，需要开通VIP，但是实际上可以听整首歌曲。

### ISSUE THREAD

**Issue by primovist** [nondanee/UnblockNeteaseMusic#471]
可以去掉提示吗？

**Comment by nondanee** [comment]
应该可以的。哪一端出现的？怎么复现？

**Comment by primovist** [comment]
> 应该可以的。哪一端出现的？怎么复现？

使用最新的Docker版本，iOS最新版客户端，搜索到某一VIP歌曲，点击收听，进入歌曲播放页面就会出现。即使使用了全局代理。

**Comment by xapenny** [comment]
> > 应该可以的。哪一端出现的？怎么复现？
> 
> 使用最新的Docker版本，iOS最新版客户端，搜索到某一VIP歌曲，点击收听，进入歌曲播放页面就会出现。即使使用了全局代理。

你越狱后用Flex patch掉那几个isVIP的bool就没有了，本地会显示会员，不仅不会弹窗还能使用vip功能

**Comment by primovist** [comment]
> > > 应该可以的。哪一端出现的？怎么复现？
> > 
> > 使用最新的Docker版本，iOS最新版客户端，搜索到某一VIP歌曲，点击收听，进入歌曲播放页面就会出现。即使使用了全局代理。
> 
> 你越狱后用Flex patch掉那几个isVIP的bool就没有了，本地会显示会员，不仅不会弹窗还能使用vip功能

不喜欢越狱😂有什么办法可以用Surge或者QX的js来改吗？
