### ISSUE TITLE
PAC代理方式无法正常使用，但是全局代理可以

### ISSUE THREAD

**Issue by Colin-XKL** [nondanee/UnblockNeteaseMusic#475]
不知道各位有没有碰到过类似的情况，PAC配置方式下，播放什么歌曲都连接出错，但是更换为全局代理就可以。
**环境信息：**
* 配置方式：Docker
* 平台：arm64
* 测试平台：Android、iOS
* 代理配置方式：WLAN菜单的代理设置项

我这边已经搭建了HTTPS endpoint，所以iOS是可以使用的，但是也是需要全局代理才可以。
这全局代理的话，所有流量都会从我的服务器上过，有点顶不住啊。。。希望作者大大可以看下这个问题，我这边会配合做测试

**Comment by tarontop** [comment]
> 不知道各位有没有碰到过类似的情况，PAC配置方式下，播放什么歌曲都连接出错，但是更换为全局代理就可以。
> **环境信息：**
> 
> * 配置方式：Docker
> * 平台：arm64
> * 测试平台：Android、iOS
> * 代理配置方式：WLAN菜单的代理设置项
> 
> 我这边已经搭建了HTTPS endpoint，所以iOS是可以使用的，但是也是需要全局代理才可以。
> 这全局代理的话，所有流量都会从我的服务器上过，有点顶不住啊。。。希望作者大大可以看下这个问题，我这边会配合做测试

安卓的PAC基本上都失效了

**Comment by Colin-XKL** [comment]
哦问题解决了，原来是HTTPS的锅。
在Android、iOS系统的PAC设置都是默认走的https，而这个项目的话的程序会给所有https的请求返回空，强制降级http。但是上述平台在请求PAC文件时不会自动降级，所以一直读取错误，导致代理没有生效。
**也给后来人提个醒：设置PAC要指定走HTTP协议**
