### ISSUE TITLE
命令行里有链接，但是网易云一直在转圈

### ISSUE THREAD

**Issue by 1553497378** [nondanee/UnblockNeteaseMusic#476]
![image](https://user-images.githubusercontent.com/33971782/78669517-f9763c80-790e-11ea-9add-8a17e848fb67.png)

**Comment by nondanee** [comment]
把 `-e` 参数去掉

**Comment by 1553497378** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Nzix"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 晚上8:34
收件人:&nbsp;"nondanee/UnblockNeteaseMusic"<UnblockNeteaseMusic@noreply.github.com&gt;;
抄送:&nbsp;"低调&amp;#x2661;"<1553497378@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nondanee/UnblockNeteaseMusic] 命令行里有链接，但是网易云一直在转圈 (#476)





 
Closed #476.

**Comment by 1553497378** [comment]
好了谢谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Nzix"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 晚上8:34
收件人:&nbsp;"nondanee/UnblockNeteaseMusic"<UnblockNeteaseMusic@noreply.github.com&gt;;
抄送:&nbsp;"低调&amp;#x2661;"<1553497378@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nondanee/UnblockNeteaseMusic] 命令行里有链接，但是网易云一直在转圈 (#476)





 
Closed #476.
