### ISSUE TITLE
服务器在搬瓦工CN2GT DC3洛杉矶机房 结果返回很慢

### ISSUE THREAD

**Issue by phlinhng** [nondanee/UnblockNeteaseMusic#477]
这不是issue，只是建议。若服务器架设在离中国太远的机房，受到地理限制需要比较久的时间才能得到歌曲匹配结果，由于请求路径是`用户→美国服务器→中国酷我音乐→美国服务器→用户`，一首歌需要来回两次才能得到结果，实测慢的时候要30秒才能刷出来。    
    
出于以上原因，建议选择境内或离大陆近地点架设服务器。

**Comment by shenyiakng** [comment]
能贴一下启动参数么 我部署在瓦工，提示播放错误，在境内服务器没问题

**Comment by phlinhng** [comment]
> 能贴一下启动参数么 我部署在瓦工，提示播放错误，在境内服务器没问题

別部署在瓦工，响应太慢。参数在 #478 ，同样的参数我部署在日本节点就没问题。

**Comment by shenyiakng** [comment]
> > 能贴一下启动参数么 我部署在瓦工，提示播放错误，在境内服务器没问题
> 
> 
> 
> 別部署在瓦工，响应太慢。参数在 #478 ，同样的参数我部署在日本节点就没问题。

需要设置特别参数么 比如音源 国内中继什么的

**Comment by phlinhng** [comment]
> > > 能贴一下启动参数么 我部署在瓦工，提示播放错误，在境内服务器没问题
> > 
> > 
> > 別部署在瓦工，响应太慢。参数在 #478 ，同样的参数我部署在日本节点就没问题。
> 
> 需要设置特别参数么 比如音源 国内中继什么的

在国外的服务器只能选`kuwo`, `joox`, `youtube`三种音源

**Comment by shenyiakng** [comment]
> > > > 能贴一下启动参数么 我部署在瓦工，提示播放错误，在境内服务器没问题
> 
> > > 
> 
> > > 
> 
> > > 別部署在瓦工，响应太慢。参数在 #478 ，同样的参数我部署在日本节点就没问题。
> 
> > 
> 
> > 需要设置特别参数么 比如音源 国内中继什么的
> 
> 
> 
> 在国外的服务器只能选`kuwo`, `joox`, `youtube`三种音源

谢谢 我试一下
