### ISSUE TITLE
uwp版歌曲灰色

### ISSUE THREAD

**Issue by skrhane** [nondanee/UnblockNeteaseMusic#479]
cmd管理员身份执行
checknetisolation loopbackexempt -a -n="1F8B0F94.122165AE053F_j2p0p5q0044a6"
显示 完成
官网下载安装了node js最新的长期版，并执行node app
停留在HTTP Server running @ http://0.0.0.0:8080
打开云音乐uwp，歌曲依旧灰色。
没有MITM > ...

**Comment by nondanee** [comment]
要设置代理

**Comment by skrhane** [comment]
感谢

**Comment by DoveBoy** [comment]
> cmd管理员身份执行
> checknetisolation loopbackexempt -a -n="1F8B0F94.122165AE053F_j2p0p5q0044a6"
> 显示 完成
> 官网下载安装了node js最新的长期版，并执行node app
> 停留在HTTP Server running @ http://0.0.0.0:8080
> 打开云音乐uwp，歌曲依旧灰色。
> 没有MITM > ...

老哥怎么解决的？我也是这个问题，代理具体怎么设置？我设置了但是没用
