### ISSUE TITLE
youtube源无法播放

### ISSUE THREAD

**Issue by steven7851** [nondanee/UnblockNeteaseMusic#481]
不久前还可以，今天突然发现不行

**Comment by xianingz** [comment]
我今天刚开始用，配置了API_KEY，也是不行，log里只有163.
node app.js -p 2345 -a 127.0.0.1 -o youtube joox kuwo

TUNNEL > web.push.126.net:6003
MITM > music.163.com
MITM > music.163.com
MITM > music.163.com
MITM > music.163.com
MITM > music.163.com
MITM > music.163.com
MITM > music.163.com
MITM > clientlog.music.163.com

**Comment by nondanee** [comment]
估计是 sig 变了

**Comment by xianingz** [comment]
需要我这里更改配置么？还是需要改代码。
先谢谢大佬！非常有用的东西！

**Comment by nondanee** [comment]
需要改代码的

应该是签名函数没找到，流程可参考
https://blog.maple3142.net/2018/05/05/how-to-download-youtube-video/

你改完 PR 一下吧，多谢

**Comment by xianingz** [comment]
我按照这个上面说的找到了现在的两个signature加密函数分别是Nt和Mt
然后我改了下面的代码在你的signature函数里面。
`
const fnNameResult = /=([a-zA-Z0-9\$]+?)\(decodeURIComponent\(c/.exec(body)
const fnName = fnNameResult[1]
const _argNameFnBodyResult = new RegExp(
		fnName + '=function\\((.+?)\\){(.+?)}'
		).exec(body)
const [_, funcArg, funcBody] = _argNameFnBodyResult
`
我测试了这几个变量，输出都是对的，和Nt和Mt符合的。但运行起来还是不work。实在不了解js，不知道其他的该怎么改了。。。

**Comment by xianingz** [comment]
今天又尝试了下，修改了其他几个地方，在我这work了。我已经提交了PR

**Comment by nondanee** [comment]
@xianingz 感谢

**Comment by lonelykid** [comment]
好像又失效了，改版了没有assets这一项了
