### ISSUE TITLE
Ubuntu 19.10 可以抓到网易CC直播的,都是不能捕捉到网易云音乐的= . =

### ISSUE THREAD

**Issue by Ryanshinta** [nondanee/UnblockNeteaseMusic#482]
![1434741305](https://user-images.githubusercontent.com/50620558/78926992-a51aba80-7ad0-11ea-97c3-3cf8e4e06fff.jpg)
用的是node app.js  代理本地127.0.0.1:8080

**Comment by nondanee** [comment]
网易云是 look 直播，和 cc 直播没关系啊

**Comment by Ryanshinta** [comment]
> 网易云是 look 直播，和 cc 直播没关系啊，你想说明什么问题？
不知道为什么网易云音乐用不了,但是这个会有显示,开了代理以后cc.163.com就打不开,但是网易云音乐还是可以用

**Comment by nondanee** [comment]
你怎么使用的呢？网页版 or 客户端？
MITM 指定的域名都是 *.music.163.com，不会影响 cc.163.com，刚才了 cc 直播过代理完全没问题
cc 是网易游戏的，和网易云音乐没关系，不能说明问题
