### ISSUE TITLE
一个与本项目不太相关的问题请教，关于Nginx问题

### ISSUE THREAD

**Issue by a95788** [nondanee/UnblockNeteaseMusic#485]
自上次#319 请教大佬后，最近也没什么事情就把服务器给备案了。现在经过一些调整和搜索，已经成功运行，并且能够在PC和iOS（通过修改hosts文件）上完美运行。
但现在有个问题就是，因为国内的法规要求网站需要显示备案号，我目前的Nginx已经设置了监听443端口并代理到本地的80端口，目前访问我的网站直接返回503，我想在503页面中显示我的备案号，我搜索了很多遍如何在Nginx上定义50x页面或者当50x时跳转到指定页面，但都没有效果，担心因为页面没有备案号导致主机被停。

目前我的Nginx的配置文件如下：
（我不懂Nginx，但配置是看别人一步一步改的）
`user  www www;
worker_processes auto;
error_log  /www/wwwlogs/nginx_error.log  crit;
pid        /www/server/nginx/logs/nginx.pid;
worker_rlimit_nofile 51200;

events
    {
        use epoll;
        worker_connections 51200;
        multi_accept on;
    }

http
    {
        include       mime.types;
		#include luawaf.conf;

		include proxy.conf;

        default_type  application/octet-stream;

        server_names_hash_bucket_size 512;
        client_header_buffer_size 32k;
        large_client_header_buffers 4 32k;
        client_max_body_size 50m;

        sendfile   on;
        tcp_nopush on;

        keepalive_timeout 60;

        tcp_nodelay on;

        fastcgi_connect_timeout 300;
        fastcgi_send_timeout 300;
        fastcgi_read_timeout 300;
        fastcgi_buffer_size 64k;
        fastcgi_buffers 4 64k;
        fastcgi_busy_buffers_size 128k;
        fastcgi_temp_file_write_size 256k;
		fastcgi_intercept_errors on;

        gzip on;
        gzip_min_length  1k;
        gzip_buffers     4 16k;
        gzip_http_version 1.1;
        gzip_comp_level 2;
        gzip_types     text/plain application/javascript application/x-javascript text/javascript text/css application/xml;
        gzip_vary on;
        gzip_proxied   expired no-cache no-store private auth;
        gzip_disable   "MSIE [1-6]\.";

        limit_conn_zone $binary_remote_addr zone=perip:10m;
		limit_conn_zone $server_name zone=perserver:10m;

        server_tokens off;
        access_log off;

server {
        listen       443 ssl;
        server_name  我的域名;
        ssl_certificate /www/server/nginx/1.crt;
        ssl_certificate_key /www/server/nginx/2.key;
        ssl_session_timeout 10m;
        ssl_session_cache shared:SSL:10m;

        ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers 'AES128+EECDH:AES128+EDH';
        ssl_prefer_server_ciphers on;
         location / {
             proxy_pass  http://localhost:80;
             proxy_set_header HOST 'localhost:80';
         }
     }
}`

**Comment by nondanee** [comment]
> 我想在503页面中显示我的备案号

这个问题可以先放放

先确认一下你是否用了改 hosts 的方式？
改 hosts 的话 nginx 的 server_name 必须要设成 "music.163.com" 或者 "_" / "*" 才行
你这样仅仅是个 https endpoint 吧？

**Comment by nining377** [comment]
@a95788 可以在Nginx配置中加入如下内容：
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
/50x.html文件在你Nginx/html目录下，你可以随意更改内容

**Comment by a95788** [comment]
已解决，自行closed
