### ISSUE TITLE
安卓客户端提示无法缓冲，网络错误

### ISSUE THREAD

**Issue by EnderQIU** [nondanee/UnblockNeteaseMusic#486]
安卓客户端版本号：7001030
Log：
MITM > null
MITM > null
MITM > null
MITM > null
MITM > null
...
在server.js:line 25增加以下代码可解决问题（我知道这样做并不对）：
`				if (parse(req.url).host==null) {
					req.url = 'http://' + req.headers.host + req.url
				}
`
但不知道原因。

**Comment by nondanee** [comment]
改了以后 log 显示 MITM 什么 host？

设成 null 是一种保护，不然你直接访问代理地址就会死循环
https://github.com/nondanee/UnblockNeteaseMusic/blob/5af576094229e3efb6bbed05996ec9bf101a0d56/src/hook.js#L72

**Comment by EnderQIU** [comment]
改了之后相应的地方显示的就是音源host了

**Comment by nondanee** [comment]
是网易云 uid + iptables 那种转发吗？
确实会有问题的，非网易云请求都是不会反向代理的

你加上 `-e http://music.163.com` 就行
(从原理上讲你加上 `-e http://任何地址` 都行)

**Comment by EnderQIU** [comment]
明白了，问题解决
