### ISSUE TITLE
网易云音乐最新版本7.1.30失效，不要升级网易云音乐客户端

### ISSUE THREAD

**Issue by id77** [nondanee/UnblockNeteaseMusic#487]
不要升级，不要升级，不要升级

**Comment by id77** [comment]
经测试，推荐使用 7.1.0 版本| 版本ID: 834850667

因为7.1.20/7.1.10的搜索结果，「单曲」列表的歌曲还是灰色的。单曲列表灰色歌曲无法播放，专辑里面却能解锁播放。

 7.1.0搜索结果，灰色能成功解锁播放。

![image](https://user-images.githubusercontent.com/9592236/79055866-fa96c900-7c82-11ea-8c74-e1fcdb168baa.png)

**Comment by nondanee** [comment]
你用的 release 版本吧？(npm 和 docker 都算 release 版本)
搜索结果的问题在 master 分支上已解决

失效的具体表现是什么？

**Comment by id77** [comment]
> 你用的 release 版本吧？(npm 和 docker 都算 release 版本)
> 搜索结果的问题在 master 分支上已解决
> 
> 失效的具体表现是什么？

我用的openwrt/lede插件，之前都正常，网易云音乐app升级之后就不正常了。
最新版本是7.1.30，会出现图中提示，但看插件日志；已经匹配到音源了的，就是无法播放。
app降级就正常了，mac客户端倒一直正常。
![34D277E3-F7C0-41BA-9CDE-A887AAD84E53](https://user-images.githubusercontent.com/9592236/79066968-66624b80-7cee-11ea-9739-55da7701e010.png)

### 7.1.20/7.1.10这两个版本也有问题。
「单曲」列表的歌曲还是灰色的。单曲列表灰色歌曲无法播放，专辑里面却能解锁播放。

![B5D909E6-7442-4AE6-AF98-1A7C9639A109](https://user-images.githubusercontent.com/9592236/79067037-1932a980-7cef-11ea-9e07-f1a65cb5be96.png)
![548A102B-E368-4A13-A23E-DE9A18B2BD4C](https://user-images.githubusercontent.com/9592236/79067038-1c2d9a00-7cef-11ea-824e-15d8bb1eb1fc.jpeg)

**Comment by nondanee** [comment]
部分灰部分正常是因为只有白名单内请求会进行修改 (修改需要加密并读取到内存，为节省资源)，新接口不在白名单内，master 分支的代码已添更新白名单

去灰范围包括歌单详情、专辑详情、歌手热门歌曲、日推、搜索结果
不要只盯着一处看，加了新接口会有用户反馈或者我自己发现，白名单会更新

能否去灰和能否播放是两件事

去灰完全失效的可能
- 不支持代理了 (这个估计不可能)
- 没有 http 兜底策略了 (短时间内不可能) / 不信任用户证书了
- eapi 密钥变了 (短时间内不可能)

iOS 能否播放的问题在于 endpoint 和 https
从你的用法看应该只能说某一种配置失效了

插件默认配置我不知道是啥
如果还有问题，根据目前的反馈，自己配 https endpoint 一定可以

**Comment by wangfeng87** [comment]
确实，ios端升级后不能播放了，还不知道怎么降级呢

**Comment by id77** [comment]
> 确实，ios端升级后不能播放了，还不知道怎么降级呢

用抓包工具修改下载请求的请求体里面的版本号即可。详细操作可以google到。我自己账号下载的ipa，你应该用不了。
