### ISSUE TITLE
关于请教一些疑难杂症，部分环境可以部分不可以

### ISSUE THREAD

**Issue by a95788** [nondanee/UnblockNeteaseMusic#489]
在解决了#485 的问题之后，随后发现一个比较难搞的问题。
运行平台：
Windows 10 / 云音乐版本2.7.0 / 通过设置软件自带的代理实现 / 可正常使用
iPhone iOS12 已越狱 / 云音乐版本5.90 / 通过修改/etc/hosts文件实现 / 可正常使用 （因使用Hosts，根据ReadMe必须要是80端口）
iPad iOS13 未越狱 / 云音乐版本 HD版1.71 / 通过设置WiFi PAC 实现 / 异常

服务器情况：
国内主机+国内域名+国内免费证书+已完成备案

问题
1.测试执行的命令是：
```
node app.js  -s -p 80 -e http://我的域名
```
请注意这里并非https。
这种情况下 iPad 能够通过设置PAC模式实现解锁，并且通过浏览器访问 http://我的域名/proxy.pac 可以下载pac文件，说明是能够正常访问的。
2.实际部署的命令是
```
pm2 start app.js --name UnblockNeteaseMusic -- -s -p 80 -e http://我的域名
```
一旦断开ssh，node就会随之被结束，问题就出现在这里，一旦我使用pm2 来运行的话，浏览器能够正常访问到 http://我的域名/proxy.pac ，但尚未越狱的iPad就会出现 无法连接网络，大概情况就是，客户端显示 无网络连接，但是 日志中有不太正常的日志
```
0|UnblockNeteaseMusic  | MITM > interface.music.163.com
0|UnblockNeteaseMusic  | MITM > interface.music.163.com
0|UnblockNeteaseMusic  | MITM > interface.music.163.com
0|UnblockNeteaseMusic  | MITM > interface.music.163.com
0|UnblockNeteaseMusic  | MITM > music.163.com
0|UnblockNeteaseMusic  | MITM > music.163.com
```
刷新的日志寥寥无几，不像前面所述的PC和已越狱的手机的日志刷刷刷的日志状态。
随后我通过screen 创建一个终端来守护我的进程（直接运行node），但也不太清楚为什么，screen中的虚拟终端不会因ssh超时而导致被挂起（可能，输入任何按键无效，Ctrl+C除外），但Unblock NetEaseMusic 会卡死不动，表现的情况就像是，日志还在，但日志不滚动，所有设备都无法连接。
附上我的Nginx
```
server {
        listen       443 ssl;
        server_name  我的域名.com; # 假设我的域名是123.com 那么就是 123.com 
        ssl_certificate /www/server/nginx/1.crt; #证书文件
        ssl_certificate_key /www/server/nginx/2.key; #证书文件
        ssl_session_timeout 10m;
        ssl_session_cache shared:SSL:10m;
        ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers 'AES128+EECDH:AES128+EDH';
        ssl_prefer_server_ciphers on;
        location / {
        proxy_pass  http://127.0.0.1:80; #反代至本机的80端口
        proxy_intercept_errors on; #开启Nginx错误页面
         error_page 502 503 404 403 /404.html; #为避免80端口被占用，同时在开启Unblock NetEaseMusic的情况下，浏览器访问我的域名，会返回Nginx 的502措施，但为了遵循管局的要求，必须要附上备案号，因此将502页面指定到一个html文件上
         location = /404.html {
         root  /www/;
```
因此，我是不是pm2上有些什么样的问题？ 或者还有什么办法能够使 Node 在结束ssh后，能够依然保持稳定运行的方法？

**Comment by nondanee** [comment]
PAC，全局代理，hosts 实现方法不一样，没有可比性

- `-e` 的地址只会影响音频播放，不会影响界面显示(包含去灰功能)，这是两套逻辑
- 用 node/screen/pm2 启动没有任何区别。测试命令下是否能够正常使用？iPad 客户端是否显示 "无网络连接"？
- 这是正常的日志
- "卡死不动"这个很好验证，用浏览器直接访问 `http://我的域名`，若出现 MITM > null，就**不是**卡死不动
- "无法连接网络" 这个属于显示范畴，尚未涉及播放问题，与 nginx 配置无关

你的 pm2 启动命令没有问题

nohup/supervisor/systemd 都可以实现，本质上和 node/screen/pm2 没有区别，只是守护方式不一样，不影响功能

**Comment by a95788** [comment]
> PAC，全局代理，hosts 实现方法不一样，没有可比性
> 
> * `-e` 的地址只会影响音频播放，不会影响界面显示(包含去灰功能)，这是两套逻辑
> * 用 node/screen/pm2 启动没有任何区别。测试命令下是否能够正常使用？iPad 客户端是否显示 "无网络连接"？
> * 这是正常的日志
> * "卡死不动"这个很好验证，用浏览器直接访问 `http://我的域名`，若出现 MITM > null，就**不是**卡死不动
> * "无法连接网络" 这个属于显示范畴，尚未涉及播放问题，与 nginx 配置无关
> 
> 你的 pm2 启动命令没有问题
> 
> nohup/supervisor/systemd 都可以实现，本质上和 node/screen/pm2 没有区别，只是守护方式不一样，不影响功能

那么我想了解以下
假设我的域名是 123.com
WiFi的PAC应该是填入下列哪一个呢？
【http】

1. http://公网IP/proxy.pac
2. http://公网IP：80/proxy.pac
3. http://公网IP:443/proxy.pac
4. http://123.com/proxy.pac
5. http://123.com：80/proxy.pac
6. http://123.com:443/proxy.pac

【https】

1. https://公网IP/proxy.pac
2. https://公网IP：80/proxy.pac
3. https://公网IP:443/proxy.pac
4. https://123.com/proxy.pac
5. https://123.com：80/proxy.pac
6. https://123.com:443/proxy.pac

我感觉后面加80和443的可能性比较低，毕竟http和https就已经默认了80和443端口的
但是我现在分别填入了 
http：//公网IP/proxy.pac
和
http://123.com/proxy.pac
有时候可以 有时候不行，有开启iPad的飞行模式并关掉客户端，且有重启iPad

**Comment by nondanee** [comment]
对于你的情况
http 中 1、2、4、5 都可以
https 都不行，因为 nginx 默认不支持反代 connect

手动代理吧
客户端不是我开发的，我不知道为啥有时走代理，有时不走代理

**Comment by a95788** [comment]
> 对于你的情况
> http 中 1、2、4、5 都可以
> https 都不行，因为 nginx 默认不支持反代 connect
> 
> 手动代理吧
> 客户端不是我开发的，我不知道为啥有时走代理，有时不走代理

目前的最新状况是
有时候运行了之后 iPad可以听，并且我让在别的地方的朋友也体验了一下，也成功了，但是当我Ctrl+C结束掉服务后，只是想调整音源优先顺序，iPad就无法播放了。
体现在于，客户端提示无网络可用，但我能确保客户端已经走代理了，我在主页中挑选系统精选给我的歌单，尽管点进去提示无网络可用，但日志中能够看到 会有
‘MITM > music.163.com‘ 这样的日志在滚动，且歌单中我每在两个歌单之间来回点击多少次，日志就会出现多少次这样的Log。

**Comment by nondanee** [comment]
是正常的 log，表示在降级

> 目前除 UWP 外其它客户端均优先请求 HTTPS 接口，默认配置下本代理对网易云所有 HTTPS API 连接返回空数据，促使客户端降级使用 HTTP 接口 (新版 Linux 客户端和 macOS 客户端已无法降级)

**Comment by a95788** [comment]
确认了，并非服务端的问题。
而是采用PAC模式的情况下，你根本不知道客户端什么时候会走代理什么时候不走。
自行close
