### ISSUE TITLE
使用docker部署后信任仓库中的证书，在ios上无法解锁求问是什么问题？

### ISSUE THREAD

**Issue by QQ29701** [nondanee/UnblockNeteaseMusic#490]
使用docker部署的命令：
docker run --restart=always --name unmusic -d -p 8080:8080 nondanee/unblockneteasemusic -p 8080 -e http://music.163.com
信任的仓库中的证书：
https://raw.githubusercontent.com/nondanee/UnblockNeteaseMusic/master/ca.crt
iOS代理app使用的surge但是无法解锁灰色歌曲，也不能播放
求问下可以是哪里的问题？

**Comment by nondanee** [comment]
不知道，请先用 WLAN 手动代理测试

**Comment by QQ29701** [comment]
WLAN测也不成功..

**Comment by QQ29701** [comment]
-e参数改成 http://music.163.com 在PC上测试OK了，但是iOS还是不行

**Comment by mingwei900** [comment]
> -e参数改成 http://music.163.com 在PC上测试OK了，但是iOS还是不行

试试 https://music.163.com，在IOS上应该就能用了，但是PC用不了。

**Comment by fmwww** [comment]
你可能没有在“关于本机”——“证书信任设置”里面信任证书

**Comment by QQ29701** [comment]
证书已经信任了，还是不行，已经改为手动布署，顺便问一下家庭宽带443端口被封，如果使用自已的域名加证书，如何解决443被封的问题

**Comment by QQ29701** [comment]
> > -e参数改成 http://music.163.com 在PC上测试OK了，但是iOS还是不行
> 
> 试试 [https://music.163.com，在IOS上应该就能用了，但是PC用不了。](https://music.163.com%EF%BC%8C%E5%9C%A8IOS%E4%B8%8A%E5%BA%94%E8%AF%A5%E5%B0%B1%E8%83%BD%E7%94%A8%E4%BA%86%EF%BC%8C%E4%BD%86%E6%98%AFPC%E7%94%A8%E4%B8%8D%E4%BA%86%E3%80%82)

试过https了还是不行，我不知道问题倒底出在了哪里

**Comment by QQ29701** [comment]
> 不知道，请先用 WLAN 手动代理测试

相同的启动参数，手动部署可以，docker就行

**Comment by Jkkoi** [comment]
你现在 docker 版服务端依然以 http only 的形式在运行，https 访问自然会不能连接

配置方法见 #48

**Comment by nondanee** [comment]
@QQ29701 

emmm 之前没注意，你要用证书的话，https 端口得打开 (@Jkkoi 说的对)

改成
```
docker run --restart=always --name unmusic -d -p 8080:8080 nondanee/unblockneteasemusic -p 8080:8081 -e http://music.163.com
```
或者
```
docker run --restart=always --name unmusic -d -p 8080:8080 nondanee/unblockneteasemusic -p 8080:8081 -e https://music.163.com
```

区别在 `-e` 后面的内容

前者 iOS 上不一定用的了，windows 上没问题
后端 iOS 上应该能用，windows 上肯定用不了

**Comment by Jkkoi** [comment]
@nondanee 
后端  -> 后者
