### ISSUE TITLE
请教一下关于在路由器上的使用

### ISSUE THREAD

**Issue by a95788** [nondanee/UnblockNeteaseMusic#492]
由于购买的服务器的上传带宽比较感人，造成缓冲时间特别久，而腾讯云的提速和来年续费价格又十分的黑。但自家的宽带网络上传速度有200mb/s，同时配有主路由和旁路由。
目前考虑买一个树莓派放在家里的网络运行。公网IP都已经申请下来了，但因为已越狱的iPhone通过修改Hosts的方法运行比较稳定，但一旦使用Hosts的方法就必须使用80端口，而目前三大运营商的入口中，80端口已经被屏蔽。
那么想请教各位大佬，如何通过 外网访问我自家的公网IP的80端口时，能够映射到自家网络的其他端口中？（将所有的数据原本不动的转到其他端口）
搜索了一下网上的方法，普遍都不太符合预期。

**Comment by nondanee** [comment]
可以的，iPhone 上用 iptables 转发

**Comment by 3131210** [comment]
为什么不用shadowrocket
