### ISSUE TITLE
我在阿里云服务器上配置的，那么我在本地开启代理，所有的流量都会经过服务器转发吗。

### ISSUE THREAD

**Issue by lNeverl** [nondanee/UnblockNeteaseMusic#494]
我在阿里云服务器上搭建成功了，在本地代理中填写的服务器ip和端口。那么我有一下几个疑惑。
1.我看到本地访问的所有流量在服务器上都会有显示，如百度，哔哩哔哩等。是不是说本地的流量都会经过服务器转发。
2.这样本地的网速是不是受到服务器的带宽限制。
3.如果服务器要是限制流量的话，是不是本地使用的所有流量都会在都会在服务器上对应消耗。
非常感谢您的解答。

**Comment by nondanee** [comment]
1. 是
2. 是
3. 是

**Comment by lNeverl** [comment]
> 1. 是
> 2. 是
> 3. 是

感谢解惑
