### ISSUE TITLE
请问下这个和ssr如何同时使用

### ISSUE THREAD

**Issue by zhjcreator** [nondanee/UnblockNeteaseMusic#495]
我用群晖docker搭建好了，windows端正常使用。linux端用pac代理正常，但我同时也要挂ssr，这就冲突了，请问下大佬有没有什么办法。

**Comment by nondanee** [comment]
65536 个端口号任你用，为什么会冲突？

**Comment by zhjcreator** [comment]
> 65536 个端口号任你用，为什么会冲突？

抱歉，我没说明白。我因为unblockneteasemusic服务端不能用80端口，所以客户端不能用改host的方式使用 。如果客户端用pac代理模式的话又不能和ssr的pac模式同时使用

**Comment by wowcaiya** [comment]
host这个可以改成别的端口啊

**Comment by a95788** [comment]
> host这个可以改成别的端口啊

想请教一下在修改Hosts文件的情况下如何能够指向非80的端口~

**Comment by zhjcreator** [comment]
> 
> 
> host这个可以改成别的端口啊

host能带端口吗？我试试看

**Comment by nondanee** [comment]
hosts 不能带端口
可以用 iptables nat 达到改 hosts 的效果 #436 

其他方法
可以设置 ssr 代理为上游代理
可以转换 http 代理为 ssr
可以使用类似 clash 的规则代理
