### ISSUE TITLE
部分歌曲网易云已有且可以直接播放但是会调取其他平台的资源来播放

### ISSUE THREAD

**Issue by Colin-XKL** [nondanee/UnblockNeteaseMusic#497]
使用了一段时间，观察日志发现所有歌曲都会由程序进行解析，然后调取其他平台上的资源来进行播放。很多网易云平台上已经有的歌曲也会调取其他平台的资源进行播放，一来拖慢了速度，二来偶尔会出现匹配错误的问题，实际播放的并不是本来要播放的歌曲。

**Comment by nondanee** [comment]
不会的，请举例

**Comment by Colin-XKL** [comment]
刚去看了下，好像的却部分网易云平台的歌曲是可以直接播放的。不过最近版权收紧了，印象中的那些原来免费的歌现在都要VIP了，所以才会从其他平台调的资源
