### ISSUE TITLE
iOS配合QuantumultX配置，一直报错，求大佬指导正确姿势

### ISSUE THREAD

**Issue by LaureatePoet** [nondanee/UnblockNeteaseMusic#498]
看了#478 的分享

我使用的[GitHub某个项目提供的conf文件](https://github.com/Hedilict/QuantumultX)，测试了就无法连接，我不知道怎么解决，这是我第一次用QuantumultX。

[policy]
[filter_remote]
[server_local]
我都设置了 

我在服务端自己部署了UnblockNeteaseMusic，Windows上直接http代理没有问题。我把我的服务器端口号改到conf文件里，依旧显示 如图的错误

![](https://s1.ax1x.com/2020/04/15/JCb3nI.png)

我也尝试写切换，切換到全局模式再切回策略組分流模式。依旧还是报错

请问这个是QuantumultX的BUG吗？

如果这个没办法解决的话，有大佬可以分享一下iOS端的正确姿势吗。我在issue看到的教程有些选哟nodejs我不知道iOS如何开启。

目前自己是在服务器端通过docker部署了这个项目
```
docker run -d -p 5163:8080 --name 163music \
	nondanee/unblockneteasemusic

```

Windows，网易云客户端直接使用http代理完全没有问题。问题就是不知道iOS端不知道怎么解决。
**求大佬拯救，谢谢**

**Comment by Grergo** [comment]
只保留 http=地址:端口,tag=tag 试试

**Comment by lingan1996** [comment]
好像因为你的是共享版的圈叉，才会报这个错

**Comment by LaureatePoet** [comment]
@lingan1996 @Grergo  谢谢大佬们帮助，的确是共享版圈X的缘故
