### ISSUE TITLE
iptables屏蔽地址如何查找？

### ISSUE THREAD

**Issue by monkey000** [nondanee/UnblockNeteaseMusic#50]
还是倾向使用host
不然每次听歌都要挂代理有点麻烦
android端的
iptables里设置屏蔽的ip如何查找？这个应该是会变的吧 我试了下223.252.199.10不管用

**Comment by MartisW** [comment]
> https://github.com/nondanee/UnblockNeteaseMusic#%E6%96%B9%E6%B3%95-1-%E4%BF%AE%E6%94%B9-hosts

curl music.httpdns.c.163.com/d --data music.163.com

把出来的 IP 加进去：

{"dns":[{"host":"music.163.com","ips":["103.211.228.143","103.211.228.142"],"ttl":300,"http2":0}]}

回复的这些 IP 应该是根据你的地理位置寻找的最近的节点。

**Comment by nondanee** [comment]
之前版本硬编码的 IP 有两个
223.252.199.10 和 .9 或者 .11，不记得了
另外的是从 httpdns 取得
用 host 屏蔽这个应该就行了 music.httpdns.c.163.com
6.+ 没试过
