### ISSUE TITLE
请问用的pac文件储存位置在哪里？

### ISSUE THREAD

**Issue by gudejbvsoyczqu** [nondanee/UnblockNeteaseMusic#500]
输入http://mydoamin:port/proxy.pac下载的文件是这样的，想问下这个文件储存在哪里的，怎么也找不到。

					function FindProxyForURL(url, host) {
						if (host == 'music.163.com' || host == 'interface.music.163.com' || host == 'interface3.music.163.com' || host == 'apm.music.163.com' || host == 'apm3.music.163.com' || host == '103.126.92.133' || host == '103.126.92.132' || host == '59.111.181.38' || host == '59.111.181.60' || host == '223.252.199.66' || host == '223.252.199.67' || host == '59.111.160.195' || host == '59.111.160.197' || host == '59.111.181.35') {
							return 'PROXY 127.0.0.1:49002'
						}
						return 'DIRECT'
					}

**Comment by nondanee** [comment]
动态生成的，不是文件

**Comment by gudejbvsoyczqu** [comment]
感谢回复，我现在想修改这个proxy.pac需要在哪里修改呢？

**Comment by nondanee** [comment]
https://github.com/nondanee/UnblockNeteaseMusic/blob/5af576094229e3efb6bbed05996ec9bf101a0d56/src/server.js#L13-L24
