### ISSUE TITLE
脚本运行起来之后这个 TUNNEL 后面跟着的都是些什么内容啊

### ISSUE THREAD

**Issue by 1273457900** [nondanee/UnblockNeteaseMusic#501]
![634E938D-F3B3-4FD1-BDB6-8D6BF70320B4](https://user-images.githubusercontent.com/62231849/79599957-f2260e80-8118-11ea-9225-0d2f9b961578.png)
有几个网址频繁出现  
想问一下 这些是什么意思

**Comment by nondanee** [comment]
一般来说是 https 请求过代理记录下的日志

**Comment by 1273457900** [comment]
为什么会一直请求这些网站呢  我就把服务器共享给了周围几个朋友在用 有几个从今天下午就一直出现到的是国外的票务网站。
而且 通过proxy的函数不应该 把不是163的都过滤掉吗

**Comment by nondanee** [comment]
看 README 粗体
https://github.com/nondanee/UnblockNeteaseMusic#使用
默认不开启严格模式哦
