### ISSUE TITLE
OS X下运行

### ISSUE THREAD

**Issue by alexlee728** [nondanee/UnblockNeteaseMusic#502]
在OS X下运行服务，Android手机连接服务，服务已经打印连通日志，还是没有解锁（灰色）。

**Comment by nondanee** [comment]
日志贴一下

**Comment by alexlee728** [comment]
TUNNEL - 47.100.127.239:443
TUNNEL - 47.100.127.239:443
TUNNEL - 39.105.63.80:443
TUNNEL - 39.105.63.80:443
TUNNEL - 39.105.63.80:443
TUNNEL - 39.105.63.80:443
TUNNEL - 193.112.159.225:443
TUNNEL - 193.112.159.225:443
TUNNEL - 193.112.159.225:443
TUNNEL - 193.112.159.225:443
TUNNEL - interface3.music.163.com:443
TUNNEL - interface3.music.163.com:443
TUNNEL - interface3.music.163.com:443
TUNNEL - interface3.music.163.com:443
MITM > interface3.music.163.com 
TUNNEL > localhost:25501
MITM > interface3.music.163.com 
TUNNEL - 115.236.121.1:443
TUNNEL - 115.236.121.1:443
TUNNEL - 115.236.118.33:443
TUNNEL - 115.236.118.33:443
TUNNEL - 59.111.181.35:443
TUNNEL - 59.111.181.35:443
TUNNEL - 59.111.181.38:443
TUNNEL - 59.111.181.38:443
TUNNEL - 59.111.181.60:443
TUNNEL - 59.111.181.60:443
TUNNEL - 118.24.63.156:443

**Comment by nondanee** [comment]
是降级的 log
不知道你用了什么工具
请先设置 WLAN 代理试一下

**Comment by alexlee728** [comment]
> 是降级的 log
> 不知道你用了什么工具
> 请先设置 WLAN 代理试一下

手机用的是clash代理的

**Comment by alexlee728** [comment]
用的是0.24.1版本

**Comment by alexlee728** [comment]
下载master版本就正常了。
