### ISSUE TITLE
是否可以考虑建一个TG讨论组用于大家交流？

### ISSUE THREAD

**Issue by alexlee728** [nondanee/UnblockNeteaseMusic#503]

**Comment by nondanee** [comment]
这种事情不需要我同意啊，随便建 😂
当然我大概率没空讨论就是了 😅

**Comment by alexlee728** [comment]
> 这种事情不需要我同意啊，随便建 😂
> 当然我大概率没空讨论就是了 😅

你可以建立一个，将链接放到ReadMe里！否则大家不知道讨论组
