### ISSUE TITLE
Windows启动报错TIMEDOUT

### ISSUE THREAD

**Issue by TianenPang** [nondanee/UnblockNeteaseMusic#504]
Node启动一直报错，多次尝试后小概率启动成功。
使用时音乐虽不是灰色，但一直加载不出来。
求解。

![批注 2020-04-19 104017](https://user-images.githubusercontent.com/32772271/79678106-5ab0e080-822a-11ea-8747-0b3986bbac87.JPG)

**Comment by TianenPang** [comment]
![批注 2020-04-19 104426](https://user-images.githubusercontent.com/32772271/79678144-c5fab280-822a-11ea-870f-1e9a265df0eb.JPG)

**Comment by TianenPang** [comment]
![批注 2020-04-19 104608](https://user-images.githubusercontent.com/32772271/79678164-ff332280-822a-11ea-82d5-b264b1227094.JPG)

**Comment by TianenPang** [comment]
@nondanee 大佬，求解，是不是我的食用方式不对？

**Comment by wowcaiya** [comment]
你这是直接使用hosts模式吗

**Comment by TianenPang** [comment]
> 你这是直接使用hosts模式吗

不是吧，我是启动后直接在网易云设置的代理

**Comment by wowcaiya** [comment]
我也有挨报错过，重启后重新输入 node app.js 啥都好了。。。不知道对你有没有帮助吧，加载不出来是不是你网易云里面没有设置代理啊？

**Comment by TianenPang** [comment]
> 我也有挨报错过，重启后重新输入 node app.js 啥都好了。。。不知道对你有没有帮助吧，加载不出来是不是你网易云里面没有设置代理啊？

启动很多次很小概率才能启动成功，但是启动成功后还是有可能听不了。
网易云里面代理是配置好的。

**Comment by wowcaiya** [comment]
...那我不知道了，没遇到过这种情况

**Comment by nondanee** [comment]
不知道为什么

把这一行

https://github.com/nondanee/UnblockNeteaseMusic/blob/9c9582401e999e1876c4baa204d35284a3d32bec/src/app.js#L77

改成 `Promise.all([])`

**Comment by TianenPang** [comment]
> 不知道为什么
> 
> 把这一行
> 
> https://github.com/nondanee/UnblockNeteaseMusic/blob/9c9582401e999e1876c4baa204d35284a3d32bec/src/app.js#L77
> 
> 改成 `Promise.all([])`

OK了，感谢。
请问这是什么原因造成的？
