### ISSUE TITLE
mac上如何翻墙和代理一起使用

### ISSUE THREAD

**Issue by Jratil** [nondanee/UnblockNeteaseMusic#506]
您好，我mac上已经使用了clashX进行翻墙，然后按照教程配置网易云的系统代理后，翻墙会失效。请问有什么方法能让翻墙和代理一起使用吗？谢谢。

**Comment by alexlee728** [comment]
> 您好，我mac上已经使用了clashX进行翻墙，然后按照教程配置网易云的系统代理后，翻墙会失效。请问有什么方法能让翻墙和代理一起使用吗？谢谢。

写一个规则指定网易云的域名走UnblockNeteaseMusic就好了

**Comment by nondanee** [comment]
楼上正解

**Comment by unix2dos** [comment]
> 楼上正解

可是同时只能使用一个 Proxy , 我现在要么切换翻墙, 要么切换网易云
有没有办法能同时的
