### ISSUE TITLE
Android客户端/Mac客户端都能正常使用，但是网页端不行

### ISSUE THREAD

**Issue by alexlee728** [nondanee/UnblockNeteaseMusic#507]
浏览器灰色歌曲没有解锁，客户端可以正常解锁

node app.js -s -e https://music.163.com -p 8080:8081

**Comment by nondanee** [comment]
https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-477870013

**Comment by alexlee728** [comment]
> https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-477870013

原来网页版本是要配合脚本使用！
