### ISSUE TITLE
Error: ENOENT: no such file or directory, open './keys/server.key'

### ISSUE THREAD

**Issue by xyzbeta** [nondanee/UnblockNeteaseMusic#51]
直接使用nohup node app.js -s -p port & 命令后台运行时。出现了报错，报错信息提示Error: ENOENT: no such file or directory, open './keys/server.key'。检查了的server.js路径下的代码。发现server.key与server.crt是直接使用"./"方式进行引用的。应该使用pwd等参数改成绝对路径引用。

**Comment by nondanee** [comment]
用 __dirname 确实没毛病
但出的问题不在这里，为什么你的路径是 `./keys/server.key`？
keys 这个文件夹是从哪里来的，我代码不是这样的，是不是你自己改过？
