### ISSUE TITLE
配置了HTTP 转发  iphone 和window可以使用； iPad 和 Android却不可以使用

### ISSUE THREAD

**Issue by 1273457900** [nondanee/UnblockNeteaseMusic#511]
请问有没有大佬遇到过这种情况  
有域名  
iPhone能用是参考 [#65 ](url)的 方法二 
Window 能用是直接 用的本地pac文件 连到服务器
很不解为什么 iPad和Android怎么调都弄不好？
有没有大佬给指导指导

**Comment by 1273457900** [comment]
> 请问有没有大佬遇到过这种情况
> 有域名
> iPhone能用是参考 [#65 ](url)的 方法二
> Window 能用是直接 用的本地pac文件 连到服务器
> 很不解为什么 iPad和Android怎么调都弄不好？
> 有没有大佬给指导指导

又测试了一下  是网易云HD不能用 同样在平板上下载手机版的客户端的话是可以使用的。。。。
有大佬有解决办法吗 
目前是在安卓和网易云HD上无法使用。。

**Comment by nondanee** [comment]
用方法 2 是越狱了？
interface3.music.163.com 也加一下 hosts

安卓上改 hosts 没用，README 里写了
安卓目前的版本 pac 也没用了

**Comment by 1273457900** [comment]
> 用方法 2 是越狱了？
> interface3.music.163.com 也加一下 hosts
> 
> 安卓上改 hosts 没用，README 里写了
> 安卓目前的版本 pac 也没用了


好的我改一下看看
没越狱  
iphone 服务器启动参数是 
node app.js -s -e https://music.163.com -p 8080:8081 &
node app.js -s -e https://yourdomain.com  (配置反代)
这两个启动参数 苹果手机版app都能正常用      
但是 在平板上下载 **网易云音乐** 和**网易云HD** 两个app  
**网易云音乐**正常使用pac   
**网易云HD** 就无法使用  
服务器端 全是 TUNNEL

安卓前两天pac还能用啊。。。
欲哭无泪，现在安卓pac怎么改都不能了吗？

**Comment by nondanee** [comment]
……好吧我看走眼了，别改 hosts
iOS 问题不清楚

-s 去掉试试

安卓现在应该不支持 pac 了
前两天？是你自己升级了吧……

**Comment by 1273457900** [comment]
大约是 4天前 
没升级 

自从域名备案下来以后 安卓就不能用了
域名备案以后 ios才可以用  同时Android失效 
很奇怪了 之前不加任何参数 
就可以Android 和 windows 都可用 
现在windows也是只能通过 pac才可以用    客户端设置全局代理 也连不上了
猜测是域名惹的祸  但又不知道问题出在哪

**Comment by 1273457900** [comment]
> ……好吧我看走眼了，别改 hosts
> iOS 问题不清楚
> 
> -s 去掉试试
> 
> 安卓现在应该不支持 pac 了
> 前两天？是你自己升级了吧……
启动参数这个 node app.js -s -e https://yourdomain.com
结果是这个 不能用
![Y `IJXYV{_CWNYUN_7 KR2](https://user-images.githubusercontent.com/62231849/80165527-3d0abf00-860e-11ea-87f1-e0eee4d43128.jpg)

**Comment by nondanee** [comment]
降级 http 没成功，开第二个端口试试
```sh
node app.js -s -e https://yourdomain.com -p 8080:8081
```
证书错误也会降级的

**Comment by Grergo** [comment]
建议开https， 我之前碰到ipad 上就死活无法使用，信任证书，添加https就可以了

**Comment by 1273457900** [comment]
> 降级 http 没成功，开第二个端口试试
> 
> ```shell
> node app.js -s -e https://yourdomain.com -p 8080:8081
> ```
> 
> 证书错误也会降级的

谢谢大佬 解决了
现在 安卓ios win都可用了。
不过启动参数有区别 
**ios是 node app.js -s -e https://yourdomain.com -p 8080:8081
Android 是 node app.js -s -e https://music.163.com -p 200:300 &
windows 是 node app.js -s
反向代理是 http://localhos:200**
PS:不知道为啥要弄这么多不同启动参数才行，不过总算是三个平台都弄好了，很感谢能给予指导

**Comment by 1273457900** [comment]
> 建议开https， 我之前碰到ipad 上就死活无法使用，信任证书，添加https就可以了

换了启动参数 ios 已经好了 美中不足就是ios和Android需要开两个 ，谢谢啦
