### ISSUE TITLE
mac本地配置，网易云出现网络错误

### ISSUE THREAD

**Issue by ZhangMingZhao1** [nondanee/UnblockNeteaseMusic#512]
请问一下mac本地的配置有没有一个比较全的教程啊，代理是使用switchhosts

**Comment by karanokk** [comment]
用这个版本 2.0.0 (730) 后面的我都失败了
加参数 -e https://music.163.com -p 8080:8081

**Comment by nondanee** [comment]
switchhosts 是代理吗？

**Comment by nondanee** [comment]
改 hosts 一共三步

1. 装证书
2. `-p 80:443 -f <ip>`
3. 改 hosts

完
