### ISSUE TITLE
关于严格模式开启即失败的问题

### ISSUE THREAD

**Issue by wutong233** [nondanee/UnblockNeteaseMusic#513]
我向来都在使用node app.js -s -p 23333 -f 59.111.181.60这条命令开启代理，Windows端和移动端都可以正常使用，可突然有一天就没法用了（服务器能正确获取其他源的音乐，看起来几乎和从前一样，但客户端没法加载）直到今天我试着关了严格模式居然可以播放了，求大佬们解惑

以下是使用node app.js -s -p 23333 -f 59.111.181.60后的结果，无法播放
> HTTP Server running @ http://0.0.0.0:23333
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
TUNNEL > p3.music.126.net:443
TUNNEL > m9.music.126.net:443
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
[448763917] 水之畔 (feat. 陶心瑶)
http://other.player.nf01.sycdn.kuwo.cn/99d8570b19dd1b11f42b55e12afabe2c/5ea2c529/resource/n2/24/12/1601012048.mp3

以下是使用node app.js -p 23333 -f 59.111.181.60后的结果，可以正常播放
> HTTP Server running @ http://0.0.0.0:23333
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
[448763917] 水之畔 (feat. 陶心瑶)
http://other.player.nf01.sycdn.kuwo.cn/ae6eaa236c5774f6d584c52660ffe38d/5ea2c57d/resource/n2/24/12/1601012048.mp3
MITM > other.player.nf01.sycdn.kuwo.cn

**Comment by nondanee** [comment]
https://github.com/nondanee/UnblockNeteaseMusic/releases/tag/v0.16.0
0.16.0 (18 Jul 2019) 改了默认行为 (这个是 featue)

给 windows 端用加上 `-e http://music.163.com`

严格模式 bug 蛮多的，建议本地跑服务，别上公网了
