### ISSUE TITLE
部分Android设备无法正常使用pac

### ISSUE THREAD

**Issue by kb1000fx** [nondanee/UnblockNeteaseMusic#514]
两个Android 10的设备 (均为EMUI)无法正常使用pac，一台Android 8设备 (氢OS)可正常使用无此问题。

问题设备表现为:
pac模式下初次使用时均可正常播放，一段时间后(期间进行过关机)发现发现失效。如果换为收到全局代理仍可正常使用，仅pac失效。

目前发现一种解决方法: 重新安装网易云app，清除保存的WiFi重新设置代理可以恢复正常使用，但再过一段时间还是会出现这个问题。

请问此问题是否与Android 10或是emui有关，有什么解决方法吗？

**Comment by nondanee** [comment]
没有

**Comment by kb1000fx** [comment]
我这个问题是系统的原因吗，是普遍存在还是个例?

**Comment by nondanee** [comment]
不知道

我自测目前的网易云版本用不了 PAC
我是 Android 10，非 emui

你可以试试看网易云之前的版本，6.5 7.0 之类的
