### ISSUE TITLE
配合 Nginx 使用 浏览器打开网页会无限重定向

### ISSUE THREAD

**Issue by Jkkoi** [nondanee/UnblockNeteaseMusic#515]
![image](https://user-images.githubusercontent.com/39653010/80279122-104dc900-872e-11ea-85b6-d308b8b87b5b.png)

macOS 和 安卓客户端可以正常使用

相较于教程，我在 Nginx 配置中加了一句 `proxy_set_header Host $http_host;` ，否者 log 中输出 `MITM > null ` Nginx 返回 `502` 客户端提示「网络错误」

使用的 Docker ，启动命令如下

`docker run --restart=always --name unmusic -d -p <port>:8080 nondanee/unblockneteasemusic`

Nginx 配置如下

```
server
{
    listen 80;
    listen 443 ssl http2;
    server_name music.163.com *.music.163.com;
    ssl_certificate    PathTo_ssl_certificate.pem;
    ssl_certificate_key    PathTo_privkey.pem;
    ssl_protocols  TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    location / {
        proxy_set_header Host $http_host;
        proxy_pass http://localhost:<port>;
        }

    access_log  PathTo_music.163.com.log;
    error_log  PathTo_music.163.com.error.log;
}
```

**Comment by JieJiSS** [comment]
改成 `server_name *.music.163.com;` 即可

**Comment by Jkkoi** [comment]
> 改成 `server_name *.music.163.com;` 即可

不需要处理 music.163.com 的内容吗？

**Comment by nondanee** [comment]
是的，要加 `proxy_set_header Host xxx`
https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-441240990

无限重定向的问题
是因为浏览器访问云音乐主站 http 会自动重定向到 https
加 server_name 不能解决

如果你启动的时候用 `-p 80:443`，代理是会自动处理的
port1 内部使用 http://music.163.com
port2 内部使用 https://music.163.com

但是你 nginx 80 和 443 全都反代的是 http 端口，port1 只会按 http://music.163.com 处理，访问一直被重定向

80 和 443 两个 proxy_pass 应该分别 proxy_pass 到 http://localhost:port1 https://localhost:port2
或者，两个端口全部都 proxy_pass 到 https://localhost:port2 (因为直接访问 https 不会被重定向)

**Comment by JieJiSS** [comment]
> > 改成 `server_name *.music.163.com;` 即可
> 
> 不需要处理 music.163.com 的内容吗？

@Jkkoi 我这里亲测不用

**Comment by Jkkoi** [comment]
> 是的，要加 `proxy_set_header Host xxx`
> [#22 (comment)](https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-441240990)
> 
> 无限重定向的问题
> 是因为浏览器访问云音乐主站 http 会自动重定向到 https
> 加 server_name 不能解决
> 
> 如果你启动的时候用 `-p 80:443`，代理是会自动处理的
> port1 内部使用 http://music.163.com
> port2 内部使用 https://music.163.com
> 
> 但是你 nginx 80 和 443 全都反代的是 http 端口，port1 只会按 http://music.163.com 处理，访问一直被重定向
> 
> 80 和 443 两个端口应该分别 proxy_pass 到 http://localhost:port1 https://localhost:port2
> 或者，两个端口全部都 proxy_pass 到 https://localhost:port2 (因为直接访问 https 不会被重定向)

成功了，谢谢大佬的帮助
这里记录一下我最后的配置以便其他人遇到类似情况快速解决
`<>` 中的内容需要根据实际情况修改

至于 @JieJiSS 说的不需要代理 `music.163.com` 这个域名，我五一再测试并修改一下吧

环境 Nginx + Docker

# Nginx

```
server
{
    listen 80;
    listen 443 ssl http2;
    server_name music.163.com *.music.163.com;
    ssl_certificate    <PathTo_ssl_certificate.pem>;
    ssl_certificate_key    <PathTo_privkey.pem>;
    ssl_protocols  TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    location / {
        proxy_set_header Host $http_host;
        proxy_pass https://localhost:<port>;
        }

    access_log  <PathTo_music.163.com.log>;
    error_log  <PathTo_music.163.com.error.log>;
}
```

# Docker 

```
docker run --restart=always --name unmusic -d -p <port>:443 nondanee/unblockneteasemusic -p 80:443 -s
```

**Comment by SSDespair** [comment]
老哥，我用你的配置没有启动起来，能在发下配置嘛

**Comment by Jkkoi** [comment]
@SSDespair  报错什么？

`<>`中的内容需要自行修改

**Comment by qinkangdeid** [comment]
> > 是的，要加 `proxy_set_header Host xxx`
> > [#22 (comment)](https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-441240990)
> > 无限重定向的问题
> > 是因为浏览器访问云音乐主站 http 会自动重定向到 https
> > 加 server_name 不能解决
> > 如果你启动的时候用 `-p 80:443`，代理是会自动处理的
> > port1 内部使用 http://music.163.com
> > port2 内部使用 https://music.163.com
> > 但是你 nginx 80 和 443 全都反代的是 http 端口，port1 只会按 http://music.163.com 处理，访问一直被重定向
> > 80 和 443 两个端口应该分别 proxy_pass 到 http://localhost:port1 https://localhost:port2
> > 或者，两个端口全部都 proxy_pass 到 https://localhost:port2 (因为直接访问 https 不会被重定向)
> 
> ===== 2020/5/2 更新了一下配置 ======
> 
> 成功了，谢谢大佬的帮助
> 这里记录一下我最后的配置以便其他人遇到类似情况快速解决
> `<>` 中的内容需要根据实际情况修改
> 
> 环境 Nginx + Docker
> 
> # Nginx
> ```
> server{
>   listen 80;
>   server_name music.163.com *.music.163.com;
>   location / {
>     proxy_set_header Host $http_host;
>     proxy_pass http://localhost:<port1>;
>     }
>     
>   
>     access_log  <PathTo_music.163.com.log>;
>     error_log  <PathTo_music.163.com.error.log>;
> }
> 
> 
> 
> server
> {
>     listen 80;
>     listen 443 ssl http2;
>     server_name music.163.com *.music.163.com;
>     ssl_certificate    <PathTo_ssl_certificate.pem>;
>     ssl_certificate_key    <PathTo_privkey.pem>;
>     ssl_protocols  TLSv1.2 TLSv1.3;
>     ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
>     ssl_prefer_server_ciphers on;
>     ssl_session_cache shared:SSL:10m;
>     ssl_session_timeout 10m;
>     location / {
>         proxy_set_header Host $http_host;
>         proxy_pass https://localhost:<port2>;
>         }
> 
>     access_log  <PathTo_music.163.com.log>;
>     error_log  <PathTo_music.163.com.error.log>;
> }
> ```
> 
> # Docker
> ```
> docker run --restart=always --name unmusic -d -p <port1>:80 
>  -p <port2>:443 nondanee/unblockneteasemusic -p 80:443 -s
> ```

大佬 自己的域名要怎么反代呢？ server_name music.163.com *.music.163.com; 这个是不是要在本地修改hosts？
