### ISSUE TITLE
Mac、Windows、iOS食用指南

### ISSUE THREAD

**Issue by Mother-Ship** [nondanee/UnblockNeteaseMusic#518]
分享一下个人成功的玩法吧

---
##### 版本：
2.3.2 build 832（2.0.0有歌词不滚动的BUG，忍不了）
##### 方法：
为了使用最新版做出了一些牺牲。。
- 修改Hosts
```
127.0.0.1 music.163.com
127.0.0.1 interface.music.163.com
```
- 信任自签证书（见进阶配置的issue）
- 本地启动node服务
```
node /***/app.js -p 80:443 -f 223.252.199.66
```
##### 缺陷：
node不启动就直接听不了歌，不过不影响

---
#### OpenWRT
参考[隔壁项目](https://github.com/maxlicheng/luci-app-unblockmusic)，下述iOS、Windows均依赖此服务
当然有自己的国内服务器按这个命令搭一个也有同样效果
```
node /usr/share/UnblockNeteaseMusic/app.js -e http://music.163.com -p 5200:5201
```
---
##### 版本：
5.7.3（自行摸索抓包降级）
##### 方法：
ShadowRocket，添加自行搭建的HTTP代理，路由器域名:5200即可。
##### 缺陷：
暂时没摸索出小火箭同时使用两个节点（v2ray+本项目）的方式（本来是可以根据UA配规则的），目前是直接不开严格模式+全局HTTP代理。

其他App的HTTPS连接必定会不通，需要暂时关闭小火箭全局代理。

---
##### 版本：
2.4.0 build 196477（**最新版应该是不可用的**）
##### 方法：
自带代理设置
##### 缺陷：
无

**Comment by Depos1t** [comment]
我的windows最新版测试后显示代理可用，但是这个2.4.0 build 196477就显示代理不可用。。。

**Comment by nondanee** [comment]
@Mother-Ship  windows 最新版可以用的

@Depos1t 可能是老版本客户端的 BUG https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-429514688
