### ISSUE TITLE
代理可用但是无法解锁的问题

### ISSUE THREAD

**Issue by Depos1t** [nondanee/UnblockNeteaseMusic#519]
我是Ubuntu 18.04.4 LTS，服务器在大陆

最新的release直接Git Clone上去的，安装NodeJS后直接Supervisor，配置如下

`[supervisor]
nodaemon=false

[program:unblocker]
user=root
directory=/root/UnblockNeteaseMusic
command=/usr/bin/node app.js -s -p 2333
autostart=true
autorestart=true
`
现在是网易云PC最新版输入代理后点击测试显示该代理可用，但是没法解锁，听VIP歌曲会加载失败。我去装了2.4.0 build 196477，测试代理显示该代理不可用，但是实际可以正常打开歌单听歌什么的，同样是听VIP歌曲显示加载失败。

之后更换了多个介于2.4.0到最新版之间和2.4.0之前的版本都是代理不可用但是实际可用然后VIP歌曲记载失败。

我有用Koolshare的梅林官改，并且开了酸酸乳插件，但是关闭插件后重启了网易云还是同样的问题。除了这个就没有其他会影响代理的东西了。机器上也没有开启过中继模式。

@nondanee

**Comment by nondanee** [comment]
#513

**Comment by Depos1t** [comment]
> #513

谢谢大佬回复，加上 -e http://music.163.com 后可以解锁了，如果大佬同意的话我可以拿我的这个机器来做live demo

**Comment by nondanee** [comment]
不同意
