### ISSUE TITLE
无法稳定运行

### ISSUE THREAD

**Issue by toooonyy** [nondanee/UnblockNeteaseMusic#52]
macOS `10.4.4`
UnblockNeteaseMusic `b0b1afc`（但在这个 commit 之前也会出现）
NeteaseMusic `2.0.0(730)`

hosts 模式，在一段时间的运行后会无法播放音乐（表现为歌单里的会不断跳过），log 里也只有一行`MITM > music.163.com` 且难以稳定复现...但差不多每天都会出现一次。重开网易云可以解决。

不知道有没有什么好的测试办法，比如运行的时候 verbose？但 -v 被输出版本占用了

**Comment by nondanee** [comment]
重开网易云就能解决？那就不是 server 的稳定性问题咯~
你想看到怎么样的 log 呢，匹配失败的 log？

**Comment by toooonyy** [comment]
是的，其实也可能是自己的网络问题（需求有点模糊）。总之就是想定位下到底是哪的锅

**Comment by nondanee** [comment]
emmm 主要是我在匹配阶段主动 reject 的地方都没写出错原因，主要是不 care 。

一般来说不断跳过就是因为没匹配到

server 这边有匹配结果缓存，如果是匹配缓存的问题重启客户端是没用的（比如 token 过期，链接过期这样的问题）所以感觉不是匹配的问题……

你可以在 provider/ 里面多打几个点 log 一下

我暂时没空……之后我会把 reject 原因补一下，你愿意做的话也可以 PR

**Comment by toooonyy** [comment]
好的，那我自己先本地测试下。开这个 issue 是以为有 verbose 的方法文档里没提。

**Comment by toooonyy** [comment]
加了一些 console.log 后出现情况时仍然没有其他输出，基本可以确定上 app 的问题了吧。

**Comment by nondanee** [comment]
@toooonyy 
swca 是用来做 fluent design 亚克力背景的，你可以在注释掉
还是别用了吧，功能也不全==

**Comment by boohoo555** [comment]
git@github.com:nodegui/react-nodegui.git
