### ISSUE TITLE
只有网易有音源且是vip的歌曲，似乎无法解锁

### ISSUE THREAD

**Issue by skymyself** [nondanee/UnblockNeteaseMusic#522]
今天听了一个"往后余生"  王贰浪的版本，提示无法缓冲。
换了好几个节点都是这样，有一个节点干脆给了个错误的音源。
关掉代理后，发现是vip试听的歌曲，能试听一下，
再到某度查一下，
发现只有网易云有这个歌曲(只是随便查一下，没有全面查)。

我就想问:这个歌是不是被网易买断版权了，
然后只有网易的vip有音源，
我们这个脚本搞不到其他音源，
然后就缓冲不了这样子

帅气的大哥能解答一下嘛

**Comment by skymyself** [comment]
刚才又看了一下，原来音乐下面有个独家的标签，版权是被买断了。试了一下独家标签的其他音乐，大部分能听，就是有个别不能听

**Comment by skymyself** [comment]
要是能把独家标签的耶全部解锁了，那就厉害了

**Comment by Jkkoi** [comment]
原理就是替换为其他平台链接

如果其他平台没有该歌曲就无法使用

老老实实 开会员/买专辑
