### ISSUE TITLE
mac可以用虚拟机启动服务，然后代理吗

### ISSUE THREAD

**Issue by fattyca1** [nondanee/UnblockNeteaseMusic#523]
你好，请问下：
我想把服务跑在虚拟机的docker中，然后宿主机通过虚拟机代理，听歌， 这样可行吗？   试了试， 没成功， 不知道是不是操作有问题

**Comment by Jkkoi** [comment]
理论可以

**Comment by nondanee** [comment]
macOS <=> VM <=> docker 这样？
端口能访问到就可以啊

**Comment by fattyca1** [comment]
@nondanee  我试了下 不知道为什么  好奇怪，  我在VM中启动用一个端口，然后在mac上访问 ， 就是没有网络

**Comment by fattyca1** [comment]
> 理论可以

 试了下 失败了  网易云音乐连接不到网络.

**Comment by nondanee** [comment]
@fattyca1 
本地可以吗？启动参数是什么？

**Comment by fattyca1** [comment]
> @fattyca1
> 本地可以吗？启动参数是什么？

我没有在本地试， 就拿虚拟机弄了一下   ￣□￣｜｜    
docker run -d --name xx -p 8900:8080 mirrorName

**Comment by Jkkoi** [comment]
> > @fattyca1
> > 本地可以吗？启动参数是什么？
> 
> 我没有在本地试， 就拿虚拟机弄了一下   ￣□￣｜｜    
> docker run -d --name xx -p 8900:8080 mirrorName  


macOS 最新版本客户端强制使用 HTTPS

详见 #48

**Comment by fattyca1** [comment]
> > > @fattyca1
> > > 本地可以吗？启动参数是什么？
> > 
> > 
> > 我没有在本地试， 就拿虚拟机弄了一下   ￣□￣｜｜
> > docker run -d --name xx -p 8900:8080 mirrorName
> 
> macOS 最新版本客户端强制使用 HTTPS
> 
> 详见 [#48 (comment)](https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-477870013)

好的，我去看看，谢谢了
