### ISSUE TITLE
关于音源匹配的问题

### ISSUE THREAD

**Issue by JiuyeXD** [nondanee/UnblockNeteaseMusic#524]
比如缺氧这首歌 我网易云中的是 个翻唱
现在网易云有一些不用cover了而是 （翻自 xxxx）
在别的平台是有这个翻唱作者的作品
但是匹配到是原唱 大佬能修复一下吗 去掉翻自后面的匹配文字

**Comment by JiuyeXD** [comment]
/src/provider/find.js
在24行后面插入
```
.replace(/（\s*翻自[:：\s][^）]+）/i, '')
.replace(/\(\s*翻自[:：\s][^\)]+\)/i, '')
```
即可

**Comment by nondanee** [comment]
好

**Comment by JiuyeXD** [comment]
大佬 还有就是 qq的库源 已经失效了 希望大佬有时间修复一下 谢谢！
