### ISSUE TITLE
安卓客户端

### ISSUE THREAD

**Issue by CKHCKH** [nondanee/UnblockNeteaseMusic#526]
![截屏_20200503_171530](https://user-images.githubusercontent.com/57807561/80910393-cb5d0000-8cf4-11ea-985f-071f3c169015.jpg)
这个是啥原因呢，作者大大

**Comment by nondanee** [comment]
是不是有路由器插件？证书不对

**Comment by CKHCKH** [comment]
> 是不是有路由器插件？证书不对

不是吧，路由器没装插件的，就是升级之后就一直这样报错了，然后重新拉库也不行

**Comment by nondanee** [comment]
那你 merge develop 分支好了，develop 分支不用 httpdns 了

**Comment by CKHCKH** [comment]
> 那你 merge develop 分支好了，develop 分支不用 httpdns 了

如何拉develop分支呢，git clone啥，我是一个新手，有点笨哈

**Comment by CKHCKH** [comment]
> 那你 merge develop 分支好了，develop 分支不用 httpdns 了

![截屏_20200504_084732](https://user-images.githubusercontent.com/57807561/80930163-58e13400-8d77-11ea-8564-e6053421429a.jpg)
![截屏_20200504_084743](https://user-images.githubusercontent.com/57807561/80930168-63033280-8d77-11ea-95a8-076c2d16c611.jpg)
拉取develop分支好像mitm失效

**Comment by nondanee** [comment]
代理转换过吧？用了什么 app？

**Comment by CKHCKH** [comment]
> 代理转换过吧？用了什么 app？

用了clash，排除termux避免回环了

**Comment by CKHCKH** [comment]
> > 代理转换过吧？用了什么 app？
> 
> 用了clash，排除termux避免回环了

但是还是不行

**Comment by nondanee** [comment]
`pull origin develop` 再试一次
如果还不行，那就是你离不开 httpdns，还是要用 master 的代码，然后把证书校验去掉
```
export NODE_TLS_REJECT_UNAUTHORIZED=0
```

**Comment by CKHCKH** [comment]
> `pull origin develop` 再试一次
> 如果还不行，那就是你离不开 httpdns，还是要用 master 的代码，然后把证书校验去掉
> 
> ```
> export NODE_TLS_REJECT_UNAUTHORIZED=0
> ```

刚刚重新拉了一下develop分支，还是不行，只能去master了吗

**Comment by CKHCKH** [comment]
> `pull origin develop` 再试一次
> 如果还不行，那就是你离不开 httpdns，还是要用 master 的代码，然后把证书校验去掉
> 
> ```
> export NODE_TLS_REJECT_UNAUTHORIZED=0
> ```

谢谢作者，证书验证去掉成功了，用的master分支

**Comment by nondanee** [comment]
好
