### ISSUE TITLE
关于单应用代理

### ISSUE THREAD

**Issue by qingihuan** [nondanee/UnblockNeteaseMusic#53]
有没有可能通过代理服务器ssr流量从而实现安卓端的单应用代理，这样能节省很多资源

**Comment by nondanee** [comment]
这个问题本来应该你自己研究的！

$$ 和 $$R 是否支持上游 http 代理？我不知道（应该不支持）

如果用 hosts 模式的话，$$ 和 $$R 的安卓客户端都要用远程 DNS，（改 VPS 的 hosts 文件是没有用的）
所以你要自己开一个 DNS server（比如 dnsmasq），把 music.163.com 指到你自己服务器公网地址，$$/$$R 里远程 DNS 填自己的自己服务器公网地址（Windows 用 $$ 代理的话改了 VPS 的 hosts 就可以用）

如果你服务器上已经用了 80 端口，需要用 nginx 做反代，`server_name` 需要写 `_`，`proxy_set_header HOST music.163.com` 别忘了，如果又用了 443 端口，你需要：
用 iptables ban 掉 INPUT 源是 localhost 目的端口是 443（即本地请求自己的 443 端口）
```
iptables -A INPUT -p tcp -s 127.0.0.1 --dport 443 -j DROP
```
（自签证书不行！反代不要 `listen 443`，不要 `ssl on`）

然后从网易云的 httpdns 取直连 IP
```
curl music.httpdns.c.163.com/d --data music.163.com
```
用 iptables nat 表重定向 直连 IP 到 127.0.0.1
```
iptables -t nat -A OUTPUT -p tcp -d <Netease IP> -j DNAT --to-destination 127.0.0.1
```
就差不多了

**Comment by vcheckzen** [comment]
请问能否提供 socks5 代理

**Comment by nondanee** [comment]
@vcheckzen 不提供，请问为什么要 sock5 代理呢？

**Comment by vcheckzen** [comment]
> @vcheckzen 不提供，请问为什么要 sock5 代理呢？

我在安卓寻找支持单应用 http 代理的软件没找到😀

**Comment by nondanee** [comment]
@vcheckzen Drony
https://play.google.com/store/apps/details?id=org.sandroproxy.drony

**Comment by vcheckzen** [comment]
@nondanee 谢谢，现在在用 ProxyDroid，不过需要 root 权限，并且好久不更新了

**Comment by nondanee** [comment]
@vcheckzen 我发现 http proxy 转换 socks proxy 的轮子还蛮多的，你可以去试试~~~

**Comment by vcheckzen** [comment]
@nondanee 我找过，好像大多数都是 socks 转 http 的。之前说的 [ProxyDroid](https://play.google.com/store/apps/details?id=org.proxydroid) 在 root 设备上可以满足需求，另外网上说 [Postern](https://play.google.com/store/apps/details?id=com.tunnelworkshop.postern) 类似于 Surge，但下面的规则无法使用，可能是没人维护了

```txt
[Proxy]
UnblockNeteaseMusic = http,<Server Name>,<PORT>,,

[Rule]
DOMAIN-SUFFIX,163.com,UnblockNeteaseMusic
FINAL,DIRECT
```

**Comment by nondanee** [comment]
@vcheckzen 
iOS 和 Android 的 app 有 IP 直连（桌面客户端都没有），对 app 来说只有 DOMAIN-SUFFIX 这个条件不够。
