### ISSUE TITLE
无法下载vip歌曲

### ISSUE THREAD

**Issue by gudejbvsoyczqu** [nondanee/UnblockNeteaseMusic#531]
安卓上用的是部署在windows客户端的PAC自动代理，不能下载VIP歌曲。

**Comment by gudejbvsoyczqu** [comment]
vip都只能试听二十秒，也下载不了。

**Comment by Jkkoi** [comment]
看着像完全没有生效

建议看下 log

**Comment by zronghui** [comment]
这个项目还能听 VIP 歌曲吗，我还以为只能听没有版权的歌

**Comment by nondanee** [comment]
@zronghui 
可以的，是同一套逻辑，也从别的平台取，当然大概率是匹配错的，基本网易云 vip 在别的平台也是 vip，取不到

**Comment by nondanee** [comment]
@gudejbvsoyczqu 
用手动代理，pac 可能失效了
#467 #489 #514
