### ISSUE TITLE
分享下我目前试过可行的方法

### ISSUE THREAD

**Issue by gudejbvsoyczqu** [nondanee/UnblockNeteaseMusic#532]
### windows PC:
部署在windows客户端，可以解锁灰色音乐，但是不能播放或下载VIP歌曲。
                     方法：
                         1.电脑上运行软件，设置代理端口为8080
                         2.打开网易云音乐-设置-工具-自定义代理-http代理，填入服务器127.0.0.1和 
                            端口8080
### 安卓: 
**情况1**： 部署在windows客户端的PAC自动代理，可以解锁灰色音乐，不能播放或下载VIP 
                  歌曲，其他app会有联网问题（如谷歌市场,微信等）
                  方法：
                       1.电脑上运行软件，设置代理端口为8080
                       2.在路由配置页面使用端口转发将8080端口指向电脑ip
                       3.在手机上-设置-WLAN-高级设置-代理服务器-自动配置-pac网 
                          址:http://192.168.0.XX:8080/proxy.pac -保存重连wifi

**情况2**： 部署在手机上的PAC自动代理，可以解锁灰色音乐，可以播放完整VIP歌曲但不能下载。
                  方法：
                       1.电脑上运行软件，设置代理端口为8080
                       2.下载Termux app或者其他终端app并依次此输入
                                apt update 
                                apt upgrade 
                                pkg install nodejs
                                pkg install git
                                git clone https://github.com/nondanee/UnblockNeteaseMusic.git 
                                cd UnblockNeteaseMusic 
                                node app.js -p 8080
                       3. 在手机上WLAN-高级设置-代理服务器-自动配置-pac网 
                        址:http://127.0.0.1:8080/proxy.pac -保存重连wifi

**Comment by realstephenzhao** [comment]
楼主在情况2方法中的`apt upgrade`一句后忘记加一句`pkg install nodejs`，不然下面执行`node app.js -p 8080`时会提醒安装node.js

**Comment by gudejbvsoyczqu** [comment]
> 楼主在情况2方法中的`apt upgrade`一句后忘记加一句`pkg install nodejs`，不然下面执行`node app.js -p 8080`时会提醒安装node.js

是的，忘记了

**Comment by realstephenzhao** [comment]
> 
> 
> > 楼主在情况2方法中的`apt upgrade`一句后忘记加一句`pkg install nodejs`，不然下面执行`node app.js -p 8080`时会提醒安装node.js
> 
> 是的，忘记了
其实`node app.js -p 8080`这句可以简写为`node app.js`，因为默认就是8080端口，参数p是自定义端口的意思。

**Comment by nondanee** [comment]
这不是和 README 一毛一样吗？

在 termux 上安装 git 和 nodejs 的教学
与项目本身没什么关系啊

你的情况1 和情况 2没什么区别

不推荐 Android 端使用 PAC (而且我这边已经失效了 #514 )
termux 跑本地代理或者跑局域网代理内直接手动全局代理就行
省事，其他app也不会有联网问题

刚试了，全局代理下 Android 端下载没问题
