### ISSUE TITLE
ios无法播放，提示网络不给力

### ISSUE THREAD

**Issue by usgate** [nondanee/UnblockNeteaseMusic#534]
windows客户端可正常播放。使用ios（已安装，并信任证书，设置中手动配置代理），以前灰色的可以变亮，但是播放会提示网络不给力。测试：通过本地v2ray转发方式，日志可以看到正常解析出来的地址，带不带https不知道。windows客户端客户端正常播放，显示访问地址是interface.music.163，ios不能正常播放，显示的地址是qq音乐，或者kuwo的链接。
目前已在app.js启动参数加入了-e http://music.163.com

**Comment by Jkkoi** [comment]
建议打开v2ray浏览器打开 https://music.163.com 看看有没有报证书错误和证书是否为你安装的证书

**Comment by Jkkoi** [comment]
建议打开v2ray浏览器打开 https://music.163.com 看看有没有报证书错误和证书是否为你安装的证书

**Comment by q4w5e6** [comment]
FetchEvent.respondWith received an error: Returned response is null
iPhone检测https://music.163.com报这个错

**Comment by Jkkoi** [comment]
证书没加上 还是用的 http only 模式

参考一下 #48

**Comment by nondanee** [comment]
@usgate 
不知道你说的日志是 v2ray 日志还是我这边的日志，v2ray 转发是前置还是后置
加了 `-e http://music.163.com` 以后返回给客户端的连接是封装过的，不是真实地址
看你的描述像是客户端内置了逻辑，把这个地址解出来了，直接去请求了，访问地址是真实地址
我觉得不会吧，不至于

**Comment by usgate** [comment]
参照其他issue，分别配置了ios，和windows的代理，手机和电脑均可正常使用，ipad hd版本貌似还是不可以
