### ISSUE TITLE
更简单的用法

### ISSUE THREAD

**Issue by ljs1201** [nondanee/UnblockNeteaseMusic#535]
看来你们的白嫖过程，发现你们的好麻烦啊。node.js,装一下，本地写个自动ping music.163.com（酷我/qq酷狗这些都行）2333端口脚本，然后管理员启动（或者脚本弄到开机自启），客户端用http代理，127.0.0.1，端口2333，window环境我都这样用的，其它平台也能白嫖啊

**Comment by nondanee** [comment]
不 ping 都可以
