### ISSUE TITLE
win版不能打开音效

### ISSUE THREAD

**Issue by wkmyws** [nondanee/UnblockNeteaseMusic#537]
![image](https://user-images.githubusercontent.com/45654909/81771980-24a80900-9517-11ea-9c37-dde8dc3f0653.png)

**Comment by nondanee** [comment]
老问题了 #317 #335 #411 

这个页面是个 https 的静态页

README 中描述了默认逻辑
> 目前除 UWP 外其它客户端均优先请求 HTTPS 接口，默认配置下本代理对网易云所有 HTTPS API 连接返回空数据，促使客户端降级使用 HTTP 接口 (新版 Linux 客户端和 macOS 客户端已无法降级)

使用证书可以解决 #48 
实测不信任 CA 都可以，只要开双端口 `-p 8080:8081` 就行
