### ISSUE TITLE
好多歌无法听了，不知道是不是解析那一块的原因。

### ISSUE THREAD

**Issue by X-Crack** [nondanee/UnblockNeteaseMusic#538]
![image](https://user-images.githubusercontent.com/45416520/81901577-52fa1700-95f1-11ea-878f-32f766ed9d9c.png)

这些歌都无法听！

**Comment by misaka123456** [comment]
我这边情况一样  比如周董的灰色歌曲都不听  加载不了  其它歌曲没问题

**Comment by nondanee** [comment]
@misaka123456 周杰伦的歌走酷我源，没问题

**Comment by misaka123456** [comment]
> @misaka123456 周杰伦的歌走酷我源，没问题

我发下大部分vip或者周董的灰色歌曲都无法播放，即使我设置音源为kuwo或者全部音源开启都无效

**Comment by nondanee** [comment]
@misaka123456 
我从来没说过能听大部分 vip

周杰伦大部分走酷我，少部分走咪咕，这两个源现在都没问题
![image](https://user-images.githubusercontent.com/26399680/82116623-c93b7c80-979d-11ea-8d5b-24bf8f2eca45.png)
![image](https://user-images.githubusercontent.com/26399680/82116692-423ad400-979e-11ea-8877-2346e12d01ba.png)

release 版本 qq 音乐设了 cookie 会有问题，不开 qq 音乐试试

**Comment by misaka123456** [comment]
```
TUNNEL > m8.music.126.net:443
MITM > music.163.com
MITM > music.163.com
MITM > music.163.com
[185694] 给我一首歌的时间
http://other.player.ra01.sycdn.kuwo.cn/37f16b8086884ff76dafffe3b2996f78/5ec27269/resource/n1/320/55/26/3210631106.mp3
MITM > clientlog.music.163.com
MITM > clientlog.music.163.com
```
后台显示转到了酷我的地址，但是win10电脑上的网易云软件一直加载不出来，我试了服务器直接wget下载这个链接是没问题的。

安装我直接用这个
`node app.js -s -p 10032`

**Comment by Fanx-jk** [comment]
> @misaka123456
> 我从来没说过能听大部分 vip
> 
> 周杰伦大部分走酷我，少部分走咪咕，这两个源现在都没问题
> ![image](https://user-images.githubusercontent.com/26399680/82116623-c93b7c80-979d-11ea-8d5b-24bf8f2eca45.png)
> ![image](https://user-images.githubusercontent.com/26399680/82116692-423ad400-979e-11ea-8877-2346e12d01ba.png)
> 
> release 版本 qq 音乐设了 cookie 会有问题，不开 qq 音乐试试

酷我源最近查询特别慢，不知道为什么，稍微热度没那么高的热度点击播放要很久才获取到地址

**Comment by nondanee** [comment]
看了下目前
标红框的三首歌都没问题的，都是酷我源，都是匹配正确的
有 qq 音乐 cookie 的话，可以匹配到 qq 源，也都是匹配正确的

**Comment by X-Crack** [comment]
> 看了下目前
> 标红框的三首歌都没问题的，都是酷我源，都是匹配正确的
> 有 qq 音乐 cookie 的话，可以匹配到 qq 源，也都是匹配正确的

我这边真的无法听，你能把你的启动参数给我吗。 我第一个 -o kuwo 就是酷我！

**Comment by nondanee** [comment]
@X-Crack 
我用的默认参数

你原来也的这个启动参数吗？用多久了啊？这样写参数肯定不行的

**Comment by X-Crack** [comment]
> @X-Crack
> 我用的默认参数
> 
> 你原来也的这个启动参数吗？用多久了啊？这样写参数肯定不行的

我改成默认的也不行啊，你发布的最新版和master版本我都用过就是听不了，很气。

**Comment by nondanee** [comment]
你截图是 windows 端我默认你用客户端设置里的代理 (全局的)

那你这个肯定是不行的
```sh
pm2 --update-env restart /www/wwwroot/NeteaseMusic/app.js --name UnblockNeteaseMusic -- -s -p 61122 -o kuwo qq kugou xiami baidu netease
```

起码要改成这样
```sh
pm2 --update-env restart /www/wwwroot/NeteaseMusic/app.js --name UnblockNeteaseMusic -- -s -p 61122 -o kuwo qq kugou xiami baidu netease -e http://music.163.com
```

严格模式下其他平台的音源地址也是不放行的，要用 endpoint 包一下
