### ISSUE TITLE
QQ音乐源好像无法解析了

### ISSUE THREAD

**Issue by Paris0-0** [nondanee/UnblockNeteaseMusic#539]
不管加没加Cookie，看日志都没有解析到QQ音乐的源了，设置里QQ音乐是放在第一位的

**Comment by nondanee** [comment]
试了下，不加 cookie 可以，加了就不行，我看看

**Comment by Paris0-0** [comment]
我不加cookie写none好像也不行，晚点再试试😂

**Comment by nondanee** [comment]
查了半天人都傻了，headers 都搞没了😂
https://github.com/nondanee/UnblockNeteaseMusic/commit/e00b357f1d5631e4ae1b5231ed95243fe8654cfd#diff-5cb1dbfd4bfae3d327c3d91201830fa3L58

**Comment by Paris0-0** [comment]
哈哈哈headers丢了可还行，，我试了下最新的，倒是能解析出QQ音乐的了，但是填了cookie还是最低品质的那种，没有无损的

**Comment by nondanee** [comment]
我试了下没问题，你检查下你的 cookie 里面有没有 `qm_keyst`

刚才好像遇到 QQ 音乐网页版的 BUG，虽然头像是亮着的，但是其实没有登录状态，点我的音乐会出现叹号，复制出来的 cookie 也没有那个值，需要重新登录一次

**Comment by Paris0-0** [comment]
我是直接从手机QQ音乐app里抓出cookie的一直不带qm_keyst，以前一直这么用的可以解析出flac，现在不行了。。搞不懂

**Comment by nondanee** [comment]
那你看看用之前的接口行不行 https://github.com/nondanee/UnblockNeteaseMusic/commit/e00b357f1d5631e4ae1b5231ed95243fe8654cfd

我是因为之前的接口用网页版的 cookie 取不到了才换的，说不定用移动端的 cookie 还是能用的

**Comment by Paris0-0** [comment]
好的，晚点我来试试
