### ISSUE TITLE
能否开发一个chrome extension

### ISSUE THREAD

**Issue by zzmao** [nondanee/UnblockNeteaseMusic#54]
方便浏览器使用

**Comment by zzmao** [comment]
目前只支持客户端使用吗？

**Comment by zzmao** [comment]
重新读了一个readme，发现网页版不能支持。 能否通过chrome extension 降级 https 到http呢？

**Comment by nondanee** [comment]
首先
网页版的问题不是 https（自签证书就行）；RSA 加密，没有私钥，代理无法修改请求内容，但是返回数据是可以改的，所以之后我可以一定程度上支持网页版；最最主要的问题是网页版的数据部分是内嵌在 js 或者 里面的而且加了密，不全是 XHR 

只有插件做不到
这个问题很早就想过了
插件可以通过 inject script 来拦截

**Comment by nondanee** [comment]
sorry 手机码字不小心点到了😂😅

**Comment by zzmao** [comment]
有点晕，思考了一下，感觉是有两个思路，1 插件修改网页内容， 2插件可以做代理客户端，和服务端交流。
1的问题是，优秀内容是加密的，不单纯xhr
2的问题是？  和播放器客户端不一样吗？

**Comment by nondanee** [comment]
@zzmao 
sorry 有一部分没写完就 comment 了，你再看看上一条

你说插件做代理客户端的意思是 proxyswitchy omega ？插件代理只是修改代理服务器设置啊
https://crxdoc-zh.appspot.com/extensions/proxy

**Comment by zzmao** [comment]
在桌面端：
我们可以设置代理，连接server， server帮我们搜索歌曲返回歌曲
这样桌面客户端不用做任何修改，只是request全都被代理了。 

所以我想，在chrome上，
如果我们的插件是个代理的角色，这样chrome所有的request走插件(代理)，代理去和server request。 感觉是可以的。

----

我还没有看代码，node app.js 起来后，是会看/修改 request的内容的 对吧？

**Comment by nondanee** [comment]
插件做不了浏览器的代理，只能修改浏览器的代理设置
所有 request 插件可以看到，可以修改 headers，但不能修改 body
https://developer.chrome.com/extensions/webRequest

要修改 body 只能 inject 覆盖 XHR 的 onreadystatechange
https://stackoverflow.com/questions/18310484/modify-http-responses-from-a-chrome-extension/51594799#51594799

------

是的

**Comment by zzmao** [comment]
```要修改 body 只能 inject 覆盖 XHR 的 onreadystatechange
https://stackoverflow.com/questions/18310484/modify-http-responses-from-a-chrome-extension/51594799#51594799```

这部分让server来做不就行了么？

**Comment by nondanee** [comment]
那就是说用 extension 还要自己开个 server，所以单独用 extension 实现不行啊
然后问题又来了，内置一个公共 server？谁来开，谁付钱呢

**Comment by zzmao** [comment]
可以在local开server，就跟运行客户端需要在local或者server开`node app.js` 一样。

**Comment by zzmao** [comment]
所以理论上是可行的喽？  那我开一个全局代理，由app.js代理，那么理论上网页端也可以正常运转的，对吧？

**Comment by mu-yu** [comment]
需要浏览器插件的话，就用 listen1  呗……

**Comment by nondanee** [comment]
@zzmao 
https://github.com/nondanee/UnblockNeteaseMusic/issues/54#issuecomment-486002894
> 代理无法修改请求内容，但是返回数据是可以改的，所以之后我可以一定程度上支持网页版

之前没做是之前没有尝试过自签证书 v0.11.0，是直接拒绝 https 强制降级的，网页版没法降级
https://github.com/nondanee/UnblockNeteaseMusic/releases/tag/v0.11.0

其实对于网页版，代理本身就可以做到大部分功能，不需要扩展，现在的版本不行，之后会做
（要求：安装CA证书，开 https 端口）

插件如果不能独立作用或者要配合本地 server 就没有意义，那自己拿 tampermonkey 注入一下不就好了

**Comment by zzmao** [comment]
学习了！ @nondanee 
你说的降级是什么意思？ 本来是https的endpoint ，程序替换成http endpoint么？

**Comment by zzmao** [comment]
> 插件如果不能独立作用或者要配合本地 server 就没有意义

那插件能否运行一个server 程序呢?这样就不用inject，重用现在的code就可以吧？

**Comment by nondanee** [comment]
@zzmao 
降级是指网易云客户端发现 https API 有问题，会自动降级使用 http API，这是网易云客户端的策略
具体这个“有问题”的触发条件我不清楚，我用的是代理握手后关闭 socket

**Comment by nondanee** [comment]
@zzmao 
https://stackoverflow.com/a/21186208
> Note that this is a Chrome app, not a Chrome extension. Standalone chrome extensions cannot launch a server, though it is possible to start a server from an extension via external messaging (between extension and chrome app) or native messaging (between extension and some pre-installed application on the OS). – Rob W

这是那个 live show 的视频
https://www.youtube.com/watch?v=-wumTIhaKYc

不过 chrome app 很早就不让上架，不让非 chrome os 用户下载了
所以做不到一键安装

**Comment by nondanee** [comment]
@zzmao 
网页版支持已经加上了，在个人歌单页可以看到效果（个人歌单页用的 XHR）
独立的歌单歌手专辑页都是内嵌加密的，所以没有效果，需要用油猴在 UI 上解锁灰色的样式

我看了下上面的回答，可能有一些没有直接回答你的问题，我编辑过了，麻烦再看一下，感谢

**Comment by zzmao** [comment]
@nondanee  非常感谢！ 我试一下！ 
独立的歌单歌手专辑页 只是css被变灰？ 没有资源被锁？ 

我的需求出发点是想在海外听(虽然有一个很好用的插件可以解锁有版权的)，但是如果能解锁无版权的，那就更棒了，我试一下！非常感谢！ 早点休息！

**Comment by zzmao** [comment]
@nondanee  
试了一下，感觉是哪里配置不对，可能没用cert？

node app.js  监听8080端口  (remote服务器)
proxyOmega 设置proxy由此服务器代理

app.js 可以看到log:
TUNNEL - music.163.com:443
TUNNEL - music.163.com:443
TUNNEL - music.163.com:443
TUNNEL - music.163.com:443

但是浏览器无法打开music.163.com

代理其他traffic没有问题。

**Comment by nondanee** [comment]
@zzmao 
准确的说是 UI 的限制，客户端也是一样的，灰色的不发请求直接弹窗警告
css 样式屏蔽了点击，如果可以点击，就会发 request 到后端 server，proxy 能匹配到就能听了

哦你是说 NetEaseMusicWorldPlus 吗？那个也是我得啊 😂

**Comment by nondanee** [comment]
@zzmao  
`-p 8080:8081`
仓库里的 ca 装一下

**Comment by zzmao** [comment]
就是那个！ 厉害了。。。
你是怎么发现X-REAL-IP是用来限制海外请求的？

**Comment by nondanee** [comment]
@zzmao plus 插件是 fork 以后改的，X-Real-IP 原插件就有
这个东西很多人知道啊
https://github.com/nondanee/vsc-netease-music/issues/19

**Comment by nondanee** [comment]
@zzmao 
研究了好久 UI 限制都不知道怎么去掉
然后去找了别人的代码 https://github.com/JixunMoe/cuwcl4c
发现连网易云的 ajax 入口都有，那么做成单独插件也可行
我好菜啊，@JixunMoe 大佬 nb！

我把解锁 UI 的部分提出来了，可以先配合 proxy server 使用
https://github.com/JixunMoe/cuwcl4c/blob/master/src/site/music.163.ts#L123-L161

安装地址
https://greasyfork.org/zh-CN/scripts/382285-neteasemusic-ui-unlocker

（但是我不会用 browserify，webpack 之类的，怎么重用代码呢 == 我打个 help wanted 吧）
