### ISSUE TITLE
证书已过期

### ISSUE THREAD

**Issue by sirstrone** [nondanee/UnblockNeteaseMusic#540]
Mac使用项目签的证书提示在今天早上的时候过期了
![图片](https://user-images.githubusercontent.com/30281719/82189315-c10c4a00-9921-11ea-9d30-ee5f9222b521.png)
作者可以更新一下证书吗

**Comment by wbc8615728** [comment]
ios端，同证书过期，手动调整系统时间到昨天可以正常使用。

**Comment by nondanee** [comment]
https://github.com/nondanee/UnblockNeteaseMusic/releases/tag/v0.25.3

**Comment by nondanee** [comment]
不是昨天更新了吗？

**Comment by sirstrone** [comment]
> 不是昨天更新了吗？

master分支的证书还是去年的版本
emmm导致git clone 下来的证书没更新

**Comment by nondanee** [comment]
是 master 分支更新的啊？
https://github.com/nondanee/UnblockNeteaseMusic/commit/f0bd3f27cddd7aa9f37559e168f2c1f38452069b

**Comment by sirstrone** [comment]
> 是 master 分支更新的啊？[f0bd3f2](https://github.com/nondanee/UnblockNeteaseMusic/commit/f0bd3f27cddd7aa9f37559e168f2c1f38452069b)

但是git下来也没发现server.crt更新了呀
怪事
![图片](https://user-images.githubusercontent.com/30281719/82190612-daae9100-9923-11ea-9e11-bf61362d6c62.png)

**Comment by nondanee** [comment]
emmm 我试了下有的呢

![image](https://user-images.githubusercontent.com/26399680/82191286-e058a680-9924-11ea-9d85-92a2801a8261.png)

**Comment by sirstrone** [comment]
不管了直接从release下一份重新部署
谢谢作者大大的解答 我在研究下是不是被dns劫持了
邪门
