### ISSUE TITLE
百思不得其解的ios端显示网络不给力的问题

### ISSUE THREAD

**Issue by dumin32** [nondanee/UnblockNeteaseMusic#541]
自己在 centos 服务器用
`node app.js -p 8712:8713 -e https://music.163.com`  
启动的服务，用 windows 连上去毫无问题，但是 ios 就是死活没有办法听，用的是 Quantumult X，灰能变亮，但是听不了，提示网络不给力。

但是又确定 ios 配置是没有问题的，我简单的改成别人提供的服务 ip:port 就可以听

到处改到处碰，最后发现把 Quantumult X 里面的 MITM 里面的 hostname 配上 music.163.com, *.music.163.com 就突然好了，ios 终于可以播放了

但是没明白为什么，也没发现其他人说明过需要配置这个

**Comment by nondanee** [comment]
你确定配置了 `-e https://music.163.com` 以后 windows 端可用？不可能吧？？？

改成别人提供的服务，别人提供的服务是用自己的 endpoint 吗？你怎么确定别人的启动命令和你的一样的，又怎么确定别人的服务没有二次开发过呢？

iOS 安装 CA 证书有两步，你都做了吗？
把 safari 加到 Quantumult X 规则里，用 safari 访问网易云官网是否会证书错误呢？
如果是，就是没安装好。

**Comment by lulu1199** [comment]
我用safari访问网易云官网提示（此连接非私人连接）是怎么回事？我确定我的证书已经安装并信任了！

**Comment by dumin32** [comment]
> 你确定配置了 `-e https://music.163.com` 以后 windows 端可用？不可能吧？？？
> 
> 改成别人提供的服务，别人提供的服务是用自己的 endpoint 吗？你怎么确定别人的启动命令和你的一样的，又怎么确定别人的服务没有二次开发过呢？
> 
> iOS 安装 CA 证书有两步，你都做了吗？
> 把 safari 加到 Quantumult X 规则里，用 safari 访问网易云官网是否会证书错误呢？
> 如果是，就是没安装好。

感谢回复。确实我自己的问题，跟 Quantumult X 里面的 MITM 配置没关系，反复测试后确定之前问题其实是因为自己的云服务网速太慢导致的，切换到家里的 NAS 搭建的（上行 30M）就全部问题都不存在（切成  NAS 启服务的时候刚好配置上了圈X 的 MITM 还以为是后者解决的，但其实就只是网速，再另外之前测试 windows 的时候命令行用的是 node app.js -p 8712 确实没有带上 -e）

既然大佬回复了，顺便帮忙瞄一眼：

1. 如果用户指定了 -p 1111:2222 这种形态，是不是后面的 -e https://music.163.com 就不用再用户额外配置，代码里面不能自动补齐这个配置？
2. windows 的用上述 -p 1112:2222 -e https://music.163.com 这种形态下，可以有简单方式也能工作起来吗，以便 ios / windows 能同时用一个服务，毕竟这种配置不需要 nginx 反向代理启的更方便一些

**Comment by lulu1199** [comment]
怎么用nas配置的求教  是否可以在4g网络下使用？

**Comment by dumin32** [comment]
我是用 qnap（群晖的应该是更容易 ），Container Station 里面 docker 镜像选 node，然后把这个代码上传上去就可以，电信公网 IP 路由端口映射出去，DDNS 域名绑定

很稳定，4G 没问题，当时需求就是为了边开车边听的

**Comment by lulu1199** [comment]
哈哈 老哥我也是为了开车能听才折腾的 能留个微信吗 具体请教一下

**Comment by dumin32** [comment]
具体搜一下教程不少，我是卡在命令行运行参数这步其实，结论就是：
我最终实际启动用的正常跑的参数是
`node app.js -s -p 8712:8713 -e https://music.163.com`

其他基本顺着别人写的教程，没碰到坎

**Comment by lulu1199** [comment]
用小火箭能不能实现呢？

**Comment by dumin32** [comment]
没试过小火箭，但是讲道理来说应该是可以

**Comment by lulu1199** [comment]
你远程使用时是使用域名的吗？ quantumult x是用http代理吗？

**Comment by dumin32** [comment]
域名或者IP都试过都可以

**Comment by lulu1199** [comment]
你的域名是用国内还是国外的  国内的必须备案才能用吗？另外你是看的哪个教程？

**Comment by lulu1199** [comment]
看的是谁的教程

**Comment by lulu1199** [comment]
https://mdzz.eu/archives/UnblockNeteaseMusic.html我看这个教程在申请证书的时候就卡住了   请问老哥是看哪个教程

**Comment by nondanee** [comment]
@dumin32
你的两个问题
> 1. 如果用户指定了 -p 1111:2222 这种形态，是不是后面的 -e https://music.163.com 就不用再用户额外配置，代码里面不能自动补齐这个配置？

不能，很多地方会影响到
-e 这个配置只有在 iOS 上必须用，其他端不是必需的；
在使用代理规则 (PAC 或者其他规则) 时，不加 -e 会直连，加了 music.163.com 会走代理；
-e 使用 https 在 windows 端很可能播放不了 (自己签的证书一定不行，公网可信任 CA 发的也不一定行) #472 

> 2. windows 的用上述 -p 1112:2222 -e https://music.163.com 这种形态下，可以有简单方式也能工作起来吗，以便 ios / windows 能同时用一个服务，毕竟这种配置不需要 nginx 反向代理启的更方便一些

不清楚

windows 用的话 -e 后面是 http 肯定没问题的，但是 iOS 不知道
我很久前测过填 -e http://music.163.com 在 iOS 端也是可用的，因为 iOS 会自动把 http 改成 https，但据说现在不行了 https://github.com/nondanee/UnblockNeteaseMusic/issues/491#issuecomment-613775518 没实测过 (没 iOS 设备)

如果要识别客户端类型自动切换 -e 是用 http 还是 https，目前配置上做不到，要改代码，然后加个新的 arg

**Comment by lulu1199** [comment]
你好 老哥这几天折腾到凌晨三四点也没搞好 感觉步步都是坎，能不能加个联系方式具体请教一下

**Comment by dumin32** [comment]
@lulu1199 
我 ios 用的是 Quantumult X ：
https://merlinblog.xyz/wiki/qx-unblocknetsase.html
小火煎 / Surge 之类应该都差不多，无非就是转发特定流量到某个规则节点下而已

**确定先用自己本地 win10 启动的 node，局域网 node 启的服务可以听。**

之后再考虑把代码打个 zip 丢公网能访问的地方，阿里云 / 腾讯云都可以，我是用 nas 机器的 docker 上跑，只要有公网 IP（电信打电话给客服要）路由端口转发进去就可以

@nondanee 
目前 5 天下来崩过一次（第一次启动 2 天多之后崩的，最近 3 天都很正常），不确定是否是碰到之前其他人提到的内存爆掉导致的被杀，我再观察如果再碰到看下把缓存毙掉看下
另外，-s A:B -e http://music.163.com 在 ios 确实不行，刚实测了一把，必须 https:  才行。win 在 -e http 下测试是 OK 的，坐等大神支持，或者实在没法自己改个闭源脏的版本多监听一个端口给 win（这个端口流过来的就强行走 win 方式）
看别人提到用 endpoint 方式可以 win / ios 共存，但是 endpoint 方式最大问题占用了宝贵的 443 端口

**Comment by dumin32** [comment]
-e https://customDomain.com 这种 endpoint 方式有办法指定不用 443 端口？

**Comment by lulu1199** [comment]
我在群晖安装了docker  然后启动运行UnblockNeteaseMusic    再用ssh连接群晖内网ip输入类似于你的命令node app.js -s -p 8712:8713 -e https://music.163.com    是不是就可以使用？（之后再考虑把代码打个zip丢公网能访问的地方）您说的这句话我没懂 具体怎么操作呢？

**Comment by dumin32** [comment]
额额额，你群晖是直接跑 UnblockNeteaseMusic 的 docker？那应该直接配置下参数就行了。群晖应该有 docker 的参数配置页面才是

我是跑的 node docker，UnblockNeteaseMusic 是自己传代码上去跑的（主要因为里面的 ca 证书是自己签的）

**Comment by lulu1199** [comment]
那我这种运行方式和你的运行方式有什么不一样吗？或者试过哪个更好？  ca证书是用项目自带的还是自签的好？

**Comment by lulu1199** [comment]
还是说必须自签证书到https服务端口ios才能使用？

**Comment by dumin32** [comment]
不，用项目的证书 ios 肯定也是可以的，因为我最早测试过程全是用项目自带的证书

**Comment by dumin32** [comment]
“同一局域网内的 win10 启动的 node，ios 连这个局域网的服务可以听”

这一步 OK 了吗？

你这交流略糟心，能详细有条理的诉说自己的碰到的情况，成功到哪步，做过哪些挣扎又碰到了什么坎，把问题先缩小化到一个具体细节上才好帮

**Comment by lulu1199** [comment]
好的 晚上下班回家后我把我搭建的详细步骤进行整理一下 然后发出来

**Comment by nondanee** [comment]
@dumin32 
最好是能提供下崩溃日志，再观察观察吧
把缓存去掉的话移动端应该就下载不了

> 但是 endpoint 方式最大问题占用了宝贵的 443 端口

不会啊，endpoint 用 https://youdomain:8000 也行的啊，开 https 不一定要 443 端口

**Comment by lulu1199** [comment]
我第一步是下载映像
![Uploading 566E3538-49F6-4406-BA70-733AF7EDF4D3.jpeg…]()
第二步设置启动
![Uploading 30EE5D47-692E-420A-8277-D35FA5C4C576.jpeg…]()

第三步设置端口
![CB663142-26E0-4B8C-84C9-96DD58CFC3E4](https://user-images.githubusercontent.com/63286563/82827183-14156c80-9ee1-11ea-9280-d10a2dee127d.jpeg)
第四步设置启动命令
![8DDA7D8F-6FD9-463C-A3E1-05C8E37071B7](https://user-images.githubusercontent.com/63286563/82827218-22638880-9ee1-11ea-8711-1faa5ce4f923.jpeg)
  这就是我设置的方法 pc和ios是不行的 
 但是如果我将端口只设置一个 例如1234之类的 在pc就可以解锁成功但是ios还是解锁不了

**Comment by dumin32** [comment]
ios 貌似一定要 -e 模式
1. -p 1234:1235  -e https://music.163.com 
这种方式，node 会自己启动 https，所以比较方便省心，但是带来的问题是 pc 不能连
2. -p 1234 -e https://自己域名  
这种方式一般是用 nginx 之类的反向代理把 https 流量再交回给 1234，好处是 pc 也能连

你参数配置先用我说的 1 方式，然后看看 ios 自己对应怎么配置，我 ios 的是根据这篇 https://merlinblog.xyz/wiki/qx-unblocknetsase.html 印象什么坎都没碰到

**Comment by nondanee** [comment]
@lulu1199 
对的，iOS 一定会用到 `-e`
PC 上默认你使用客户端设置里的代理，那么有 `-s` 的情况下一定要有 `-e`

**Comment by lulu1199** [comment]
> @ lulu1199
> 对的，iOS的一定会用到`-e`
> 电脑上默认你使用客户端设置里的代理，有那么`-s`的情况下一定要有`-e`

非常感谢解答

**Comment by lulu1199** [comment]
> unblocknetsase

好的 谢谢我试一下

**Comment by lulu1199** [comment]
我使用这个命令启动 -p 1234:1235 -e https://music.163.com    还是不可以   连普通音乐都播放不了 我也是醉了

**Comment by nondanee** [comment]
@lulu1199 
确认一遍证书有没有装好 https://support.apple.com/zh-cn/HT204477

**Comment by lulu1199** [comment]
> @ lulu1199
> 确认一遍证书有没有装好https://support.apple.com/zh-cn/HT204477

确认安装并以信任

**Comment by nondanee** [comment]
用 safari 打开 https://music.163.com，观察群晖 docker 日志 (侧边栏最后一个)

**Comment by lulu1199** [comment]
> @ lulu1199
> 用safari [：https：](https://music.163.com)//music.163.com，观察群晖docker logger（侧边栏最后一个）

![DB1A0CE0-5BD3-4628-8215-10B6CBAB9EC0](https://user-images.githubusercontent.com/63286563/82921248-c2391900-9faa-11ea-9c84-21b1e433cf9a.jpeg)
这是显示出来的日志

**Comment by nondanee** [comment]
@lulu1199 
没问题啊，重启一遍网易云 app，再看下日志

**Comment by lulu1199** [comment]
> @lulu1199
> 没问题啊，重启一遍网易云 app，再看下日志

还是不可以  我访问https://music.163.com会自动跳转到https://y.music.163.com/m/
![image](https://user-images.githubusercontent.com/63286563/82921920-89e60a80-9fab-11ea-919e-59332eb2171a.jpg)

**Comment by nondanee** [comment]
@lulu1199 
跳转时正常的
还有什么问题？

**Comment by lulu1199** [comment]
> @lulu1199
> 跳转是正常的
> 还有什么问题？

最大的问题还是解锁不了  我的网易云音乐app是最新版的

**Comment by nondanee** [comment]
@lulu1199 
是有灰色还是无法播放？
有灰色的地方在哪？搜索结果页，歌单详情页，专辑详情页是不是全灰的？
无法播放的话，日志里有没有匹配成功的 log？
群晖是不是全局翻墙的？还是你人肉翻墙？

**Comment by lulu1199** [comment]
无灰色     日志只有我发给你的那样    我是在手机使用小火箭翻墙  群晖没有翻墙

**Comment by lulu1199** [comment]
是不是因为我是在群晖docker下载的项目导致的

**Comment by nondanee** [comment]
@lulu1199 
那就是没有匹配上，和网络环境有关系，和是不是群晖没关系

**Comment by lulu1199** [comment]
> @lulu1199
> 那就是没有匹配上，和网络环境有关系，和是不是群晖没关系

那就很奇怪了

**Comment by dumin32** [comment]
有没有可能是你家群晖上行带宽太低了？

我家电信 30M 带宽没问题，之前用的腾讯云带宽 2M 即使配置都没问题经常提示我网络不给力

**Comment by lulu1199** [comment]
> 有没有可能是你家群晖上行带宽太低了？
> 
> 我家电信30M带宽没问题，之前用的腾讯云带宽2M即使配置都没问题经常提示我网络不给力

我是20m的上传
