### ISSUE TITLE
ios 证书好像过期了?

### ISSUE THREAD

**Issue by timmylu1980** [nondanee/UnblockNeteaseMusic#542]
你好 openwrt开启解锁 pc端不用设置解锁了所有音乐 ios添加并信任证书歌曲灰色消失 但是提示网络不给力 打开https://music.163.com提示证书2天前到期 然后手动调节了下ios时间到3天前 顺利播放 证书是从 https://raw.githubusercontent.com/nondanee/UnblockNeteaseMusic/master/ca.crt 下载的

**Comment by sirius0213** [comment]
[https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-477870013](url) 恩，17号之后就不能用了，我是按照上面的方法自己做了证书的

**Comment by sirius0213** [comment]
#48 17号之后不行了，按上面方法可以自己做

**Comment by nondanee** [comment]
Duplicate #540 

CA 证书签了 5 年，到 2024 年过期

过期的是服务器证书 (server.crt)，在 v0.25.3 续签了，可以看 release log
https://github.com/nondanee/UnblockNeteaseMusic/releases/tag/v0.25.3

拉仓库代码就行了
openwrt 插件应该自带更新吧？你问问插件作者，我不清楚
