### ISSUE TITLE
将QQ音乐歌单导出到网易云音乐的Python脚本

### ISSUE THREAD

**Issue by keivenliao** [nondanee/UnblockNeteaseMusic#543]
https://github.com/keivenliao/QQ2NE
如有问题欢迎大家反馈，谢谢

**Comment by nondanee** [comment]
> ### 为什么要写这个脚本
> 1、网易云音乐可以解锁无版权歌曲
> 2、我QQ音乐歌单里有几百首歌

方向错了啊哥，应该搞个 UnblockQQMusic 啊
