### ISSUE TITLE
使用 -u 指定代理后，linux客户端无法使用解锁

### ISSUE THREAD

**Issue by yangon99** [nondanee/UnblockNeteaseMusic#544]
使用 -u 指定本地一http代理之后，linux客户端无法正常播放音频内容，似乎无法降级。安卓端可以解锁。
使用命令及输出：
`$ sudo node ./app.js -p 81:443 -t username:passwd -s -u http://127.0.0.1:1234`
> HTTP Server running @ http://0.0.0.0:81
> HTTPS Server running @ http://0.0.0.0:443
> TUNNEL > localhost:443
> MITM > music.163.com (ssl)
> TUNNEL > localhost:443
> MITM > music.163.com (ssl)

**Comment by yangon99** [comment]
似乎算是预期行为，抱歉，丢人了

**Comment by nondanee** [comment]
昂。linux 客户端是无法降级的，README 里有说
