### ISSUE TITLE
安卓

### ISSUE THREAD

**Issue by CKHCKH** [nondanee/UnblockNeteaseMusic#545]
![截屏_20200525_105751](https://user-images.githubusercontent.com/57807561/82774321-207ac600-9e0a-11ea-9398-123a16f0b4f6.jpg)
作者大大，用原来的export NODE_TLS_REJECT_UNAUTHORIZED=0去掉证书校验也不能解决这个问题了吗，求解

**Comment by nondanee** [comment]
应该可以的

**Comment by CKHCKH** [comment]
> 应该可以的

但我试了还是不行诶。

**Comment by CKHCKH** [comment]
> 应该可以的

![截屏_20200525_170147](https://user-images.githubusercontent.com/57807561/82797314-82542380-9e3c-11ea-88a4-646e1699f6d5.jpg)
作者帮我看看吧，试了很多遍了

**Comment by nondanee** [comment]
这前后两个错都不一样呢
不只是证书错误的问题，直接 RST 了都

你把 httpdns 去掉吧，参考这个 https://github.com/nondanee/UnblockNeteaseMusic/commit/e289be900949fddac095443ceba8e43db79f4be7#diff-bd9c9dcd314f2d7df52935b3a6a4d504R75
或者直接切 develop 分支

**Comment by CKHCKH** [comment]
> 这前后两个错都不一样呢
> 不只是证书错误的问题，直接 RST 了都
> 
> 你把 httpdns 去掉吧，参考这个 [e289be9#diff-bd9c9dcd314f2d7df52935b3a6a4d504R75](https://github.com/nondanee/UnblockNeteaseMusic/commit/e289be900949fddac095443ceba8e43db79f4be7#diff-bd9c9dcd314f2d7df52935b3a6a4d504R75)
> 或者直接切 develop 分支

拉了develop可以了，第一种方法不是很懂，试了一下是要改脚本？

**Comment by nondanee** [comment]
嗯，要改，就改一行，应该有高亮标出来的

用 develop 分支也行的
