### ISSUE TITLE
请教一下，开启代理后，其他流量会走服务器吗？

### ISSUE THREAD

**Issue by gaoxianglyx** [nondanee/UnblockNeteaseMusic#547]
请教一下，我在我的服务器上服务跑起来了。
添加代理后
是所有流量都会走我服务器吗？
还是网易云域名的流量会走服务器？
还是网易云域名下的需要解锁的流量才走服务器？

如果是都走服务器的话，岂不是速度会受影响。

**Comment by nondanee** [comment]
主要看添加的代理是什么类型的
#494

**Comment by gaoxianglyx** [comment]
手机--wifi的手动代理呢？

**Comment by nondanee** [comment]
是全局的

**Comment by gaoxianglyx** [comment]
所以我服务器的带宽，决定了所有代理到这服务的总带宽是吧

**Comment by nondanee** [comment]
是

**Comment by gaoxianglyx** [comment]
谢谢，从移动端来说，是否有方案只让网易云的流量走代理呢？

**Comment by dumin32** [comment]
各种手机端科学上网的工具一般都能做，Surge / ShadowRocket / Quantumult 等等

**Comment by gaoxianglyx** [comment]
> 各种手机端科学上网的工具一般都能做，Surge / ShadowRocket / Quantumult 等等

多谢，我去研究下

**Comment by lNeverl** [comment]
> > 各种手机端科学上网的工具一般都能做，Surge / ShadowRocket / Quantumult 等等
> 
> 多谢，我去研究下

请问研究出来了吗，可以指点一下吗，非常感谢

**Comment by gaoxianglyx** [comment]
> > > 各种手机端科学上网的工具一般都能做，Surge / ShadowRocket / Quantumult 等等
> > 
> > 
> > 多谢，我去研究下
> 
> 请问研究出来了吗，可以指点一下吗，非常感谢
我自己没有尝试，找到了一个这个链接，看起来是可以实现的，可以参照
http://www.adsl88.com/jc/pptpjc/2019/0701/599.html

**Comment by gaoxianglyx** [comment]
> > > 各种手机端科学上网的工具一般都能做，Surge / ShadowRocket / Quantumult 等等
> > 
> > 
> > 多谢，我去研究下
> 
> 请问研究出来了吗，可以指点一下吗，非常感谢
找到一个这个链接，看起来可以实现。我还没尝试
http://www.adsl88.com/jc/pptpjc/2019/0701/599.html
