### ISSUE TITLE
证书安装后网易云网站提示证书过期

### ISSUE THREAD

**Issue by digitcloud** [nondanee/UnblockNeteaseMusic#548]
Root CA证书导入后客户端能使用，但是发现打开music.163.com后提示证书过期了，失效日期是最近的几天，虽然是不影响正常使用，有什么方法解决不

**Comment by nondanee** [comment]
不知道你是什么时候开始用的，可以 `-v` 看下版本
https://github.com/nondanee/UnblockNeteaseMusic/releases/tag/v0.25.3
