### ISSUE TITLE
Android网易云音乐极速版V1.0.0 个人主页无法加载

### ISSUE THREAD

**Issue by Wesley1999** [nondanee/UnblockNeteaseMusic#549]
![ebda29de555732ad7f9c246ce36d6f1](https://user-images.githubusercontent.com/35622526/83224415-ee71b700-a1af-11ea-871b-51fa96f9a9cc.jpg)

**Comment by nondanee** [comment]
https://github.com/nondanee/UnblockNeteaseMusic/issues/30#issuecomment-472538422
