### ISSUE TITLE
Windows UWP客户端使用问题

### ISSUE THREAD

**Issue by DoveBoy** [nondanee/UnblockNeteaseMusic#550]
已经执行过checknetisolation loopbackexempt -a -n="1F8B0F94.122165AE053F_j2p0p5q0044a6"，提示成功。Powershell中执行node app.js也是正常的，提示HTTP Server running @ http://0.0.0.0:8080。Windows设置下也设置了pac脚本，但是实际运行UWP还是灰色歌单，请教，我是不是还有哪里没做到和设置的？
![image](https://user-images.githubusercontent.com/19201447/83272440-bb561480-a1fd-11ea-8931-12f61dba62e1.png)
![image](https://user-images.githubusercontent.com/19201447/83272596-e8a2c280-a1fd-11ea-9d74-a95526e71122.png)

**Comment by nondanee** [comment]
代理地址写本机回环地址，如 127.0.0.?, localhost 等

**Comment by DoveBoy** [comment]
> 代理地址写本机回环地址，如 127.0.0.?, localhost 等

![image](https://user-images.githubusercontent.com/19201447/83314805-d0a75f00-a24e-11ea-86af-548395c1448a.png)
已经改了http://localhost:8080/proxy.pac或者http://127.0.0.1:8080/proxy.pac，但是测试打开UWP客户端还是不行，Powershell中依旧没有反应

**Comment by CHN-STUDENT** [comment]
你是不是用的改版的UWP版本？确定UWP id是对的？

**Comment by DoveBoy** [comment]
> 你是不是用的改版的UWP版本？确定UWP id是对的？

用的就是商店下载的，没有用第三方的

**Comment by DoveBoy** [comment]
> 代理地址写本机回环地址，如 127.0.0.?, localhost 等

> 你是不是用的改版的UWP版本？确定UWP id是对的？

已经自己解决了，Windows设置中，代理填写http://localhost:8080/proxy.pac。同时网易云音乐UWP客户端中需要设置IE代理才行。至于和是否执行过checknetisolation loopbackexempt -a -n="1F8B0F94.122165AE053F_j2p0p5q0044a6"命令有没有必然关系就不知道了

**Comment by nondanee** [comment]
这周五更新的 (5.27)，是 win32 转制版，我还没试过，刚试了下
https://www.ithome.com/0/489/877.htm

看了下和 windows 版功能一致，支持自定义代理
可以直接在客户端内直接设置代理，就不用再设置 Windows 系统代理了

README 里的说明针对之前的 UWP 版本
需要执行 `checknetisolation loopbackexempt -a -n="1F8B0F94.122165AE053F_j2p0p5q0044a6"` 是因为 UWP 默认不能访问本机地址，现在这个转制版本确实不用，挺神奇的

还发现，UWP 版、windows 版设置和登录状态等都是通的，同时只能打开一个，UWP 没啥优势了

**Comment by CHN-STUDENT** [comment]
因为我觉得新uwp强转版本特别难用，所以我用别人打包的老uwp不更新版本，他的sid值变了，我从注册表找到了，哎，网易云现在也是一言难尽。
