### ISSUE TITLE
我使用了#521的教程配置完成，ios使用小火箭代理解锁不了

### ISSUE THREAD

**Issue by lulu1199** [nondanee/UnblockNeteaseMusic#552]
如题 ，使用小火箭代理用不了， 却可以在Wi-Fi设置http代理下使用。而且我把小火箭的“配置”改为“代理”不经过配置文件却又可以使用了！我用安卓手机数据网络开一个热点然后我的iPhone连上这个热点设置http代理也可以用。如果使用小火箭经配置文件代理又不可以了！求大佬解决！

**Comment by lulu1199** [comment]
我用ipad测试用小火箭经配置文件代理却可以正常解锁 真是奇怪了 ipad系统13.4.1 iPhone系统是13.5难道是系统的锅？

**Comment by lulu1199** [comment]
由于我这个服务搭建在我本地的群晖虚拟机上的，我在局域网下用小火箭经配置文件却可以正常解锁了 ！啊！我的目的是在4g状态下使用啊！求解啊！

**Comment by nondanee** [comment]
你说的 iPad 是 HD 版吧，两个客户端版本都不一样，iPad 上用 iPhone 版的有效果吗？
4G 下能连到你局域网吗？有内网穿透或者公网端口吗？

**Comment by lulu1199** [comment]
> 你说的iPad是HD版吧，两个客户端版本都不一样，iPad上用iPhone版的有效果吗？
> 4G下能连到你放置吗？有内网穿透或者公网端口吗？

对的，是ipad的HD版  至于ipad用iPhone版网易云音乐倒是没试过   不过我已经使用其他的搭建方法成功解锁了   是用glider转http协议为ss协议，使用quantumult开启代理 经测试在局域网和4g状态下均可正常解锁

**Comment by nondanee** [comment]
记得 close
