### ISSUE TITLE
建议把音源详细修改方法和示例写入readme

### ISSUE THREAD

**Issue by CHN-STUDENT** [nondanee/UnblockNeteaseMusic#553]
rt，今天发现搜索歌曲区配不对，想要更改音源但是不知道怎么改，查了下issue列表，看您说到修改 https://github.com/nondanee/UnblockNeteaseMusic/blob/1193e29a2c8f72c738d2988d5cf5afbb2fee7463/src/provider/match.js#L18 可以实现，也可以在启动时候指定，我觉得这个没有示例和说明可以对我们新用户不是很友好，我们不知道怎么改，请问您是否能将音源详细修改方法和示例写入`readme.md`?
感谢

**Comment by nondanee** [comment]
你查到哪个 issue 说要改这个？我去标下 outdated
README 里有啊，直接 `-h` 也可以看到

**Comment by CHN-STUDENT** [comment]
@nondanee 我是在这里查到的 #203 
我的意思我们新手可能不知道音源有哪几种，设置格式是什么，因此希望写全一点（示例）到readme中。
感谢

**Comment by nondanee** [comment]
#203 的诉求是在代码里改默认配置，你要在代码里改吗？
改代码肯定不会写 README 里

总共有几种在 README 里有 https://github.com/nondanee/UnblockNeteaseMusic#方法-3-调用接口
设置格式在 https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-429515355 里有
新手推荐用默认配置

**Comment by CHN-STUDENT** [comment]
@nondanee 感谢您，我大概明白了，请问能否在readme中提供对 #22 引用并标注配置用法，您要不说还真没看到...

**Comment by nondanee** [comment]
用 issue 写是因为回复方便
#22 是 pinned issue 第一个，issues 左上角就是

文档必要
README 里原理和使用限制都讲的很清楚了
配置项说明我加个链接吧
其他也没什么需要说明的了

#22 比较基础，还是不引用了
