### ISSUE TITLE
-s 导致解析失效

### ISSUE THREAD

**Issue by uselibrary** [nondanee/UnblockNeteaseMusic#554]
环境：debian 10 amd64, nodejs v12
操作：开启-s参数严格限制代理
问题：包括windowsr版本的http代理和hosts重定向，安卓的pac代理，都无法解锁灰色歌曲。

**Comment by nondanee** [comment]
没有 `-s` 的情况呢？没有对比吗？

目前 windows 不支持 hosts 模式，部分安卓手机 pac 无效
严格模式不能全局代理 (windows 版客户端内代理)

**Comment by uselibrary** [comment]
没有`-s`时，在windows版上使用内置http代理功能正常，在安卓版上连接WiFi使用pac功能正常，均可解锁灰色歌曲。

**Comment by PaleNutcrackers** [comment]
类似问题 本地或服务器端部署后 -s pac/hosts 只能解锁 无法播放

**Comment by cbwang2016** [comment]
完全相同的问题。

**Comment by cbwang2016** [comment]
可以看到歌曲从灰变黑，但尝试下载/播放时，Log里可以看到win客户端下载/播放的歌名，客户端却没法下载/播放。

**Comment by AckyLin** [comment]
> 没有 `-s` 的情况呢？没有对比吗？
> 
> 目前 windows 不支持 hosts 模式，部分安卓手机 pac 无效
> 严格模式不能全局代理 (windows 版客户端内代理)

有哪个参数是控制不解析vip付费歌曲的吗？只想解锁灰色音乐，不解锁VIP付费专辑歌曲

**Comment by yanranxiaoxi** [comment]
相同问题，使用 docker 部署。在旧 UWP 客户端可以登录账号，可以播放付费或无版权歌曲；在新“UWP”客户端(Windows 应用商店 UWP 版近期被更新成桌面 Win32 版本)以及普通 Win32 客户端不可以登陆账号，可以播放普通歌曲，不能播放付费或无版权歌曲，但灰色歌曲已变黑。
以下为我部署用的代码：
`docker run --name unblockneteasemusic --restart always -d -p 51301:8080/tcp nondanee/unblockneteasemusic:latest -s`
我在 Win32 客户端配置 HTTP 代理地址为：<服务器 IP 地址>:51301

**Comment by nondanee** [comment]
@yanranxiaoxi 没有，VIP 用的哪个 flag 含义是什么我还不知道 😂

**Comment by nondanee** [comment]
@cbwang2016
@yanranxiaoxi 
你们这个问题就是没看 README 啊
> 使用严格模式 (此模式下仅放行网易云音乐所属域名的请求) `-s` 限制代理范围 (需使用 PAC 或 hosts)

请问你们用的是 PAC 还是改 hosts 呢？
Android WLAN 代理，Windows 系统设置代理都是全局代理
客户端代理也是全局代理

**Comment by yanranxiaoxi** [comment]
看遍了issue  就是没注意到README中的这句话 我的错😂

**Comment by nondanee** [comment]
@uselibrary 
如果安卓 PAC 能用，严格模式应该是不会有问题的，根本不会影响到
Windows 端的问题和 @cbwang2016 @yanranxiaoxi 的一样，加 `-e` 就能解决的

**Comment by nondanee** [comment]
@PaleNutcrackers
并不类似，pac/hosts 下请求根本不会发到我这里
