### ISSUE TITLE
歌曲名与音源的匹配问题

### ISSUE THREAD

**Issue by Catkaikai** [nondanee/UnblockNeteaseMusic#555]
如下图migu音源有两个名字相同的歌曲，其中目标歌曲的名字后面没有括号作补充，但实际返回的歌曲为有括号的，而需要返回的是没有括号的，我猜测是搜索结果的排序问题导致的，建议在音源歌曲匹配可以严格匹配歌曲名，或者可以选择是否启用正则表达式。
![](https://raw.githubusercontent.com/Catkaikai/MD_KK/master/img/sample.png)

**Comment by nondanee** [comment]
没排过序，你可以自己加
https://github.com/nondanee/UnblockNeteaseMusic/issues/372#issuecomment-583751043

**Comment by Catkaikai** [comment]
了解了，谢谢开发者大大:kissing_smiling_eyes:
