### ISSUE TITLE
Android PAC代理重启服务器后失效

### ISSUE THREAD

**Issue by Pekary** [nondanee/UnblockNeteaseMusic#558]
昨天配置了一下pac代理，没有安装证书，可以用。
晚上的时候把笔记本电脑盖上了，早上起来重连wifi的时候电脑局域网ip地址变了，重新绑定ip后尝试pac代理失效，安装证书也不行了，有人遇到这样的情况么？

**Comment by nondanee** [comment]
和重启服务器也没啥关系
感觉这个问题可以描述为安卓 PAC 用一次失效？

我现在也用不了 PAC，无法解决
建议全局吧，或者用别的工具按规则分应用代理

**Comment by Pekary** [comment]
好的，改用全局了，谢谢解答~
