### ISSUE TITLE
自签证书后仍无法访问网页端

### ISSUE THREAD

**Issue by kagurainroy** [nondanee/UnblockNeteaseMusic#559]
在linux上自签证书然后复制了ca.crt, ca.key, ca.srl, server.crt, server.csr, server.key到windows目录下，安装ca.crt为受信任的根证书颁发机构，安装了油猴脚本，运行"node app.js -p 80:443 -f 59.111.181.60"，uwp端正常运行，网页版仍旧无法访问

<img width="1704" alt="批注 2020-06-18 172708" src="https://user-images.githubusercontent.com/22196444/85004672-679a7380-b18a-11ea-96e1-b1be9eff1458.png">

有运行v2ray，代理端口1080

原文：
通过chocolatey安装的openssl，如果用powershell执行最后一步，提示
“所在位置 行:1 字符: 28
+ openssl x509 -req -extfile <(printf "extendedKeyUsage=serverAuth\nsub ...
+                            ~
“<”运算符是为将来使用而保留的。
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RedirectionNotSupported”

若用CMD执行最后一步，提示
系统找不到指定的文件。

**Comment by nondanee** [comment]
嗯，签证书去 linux 上签就行了

无法复现
你关掉代理试试，再访问 https://music.163.com 是不是 403，如果是，就不是代理的问题

感觉你访问到了类似 vmware workstation "共享虚拟机"的端口
我之前好像遇到过，你自己检查一下

**Comment by kagurainroy** [comment]
> 嗯，签证书去 linux 上签就行了
> 
> 无法复现
> 你关掉代理试试，再访问 https://music.163.com 是不是 403，如果是，就不是代理的问题
> 
> 感觉你访问到了类似 vmware workstation "共享虚拟机"的端口
> 我之前好像遇到过，你自己检查一下

搞定了，确实就是wmware workstation的问题，默认虚拟机共享和远程访问占用的端口是443= =
