### ISSUE TITLE
尴尬的问下怎么开flac。。

### ISSUE THREAD

**Issue by Paris0-0** [nondanee/UnblockNeteaseMusic#562]
以前好像是改sq，现在貌似在那个select.js里，但不知道怎么改环境变量，cookie已经填了

**Comment by Co2333** [comment]
environment:
      - ENABLE_FLAC=true

**Comment by Paris0-0** [comment]
emm具体是加在哪个文件里呢，我不是用docker部署的

**Comment by Co2333** [comment]
那你还是直接改源码吧

    module.exports.ENABLE_FLAC = true

**Comment by Paris0-0** [comment]
原来如此改成true就行了😂，我来试试，感谢

**Comment by Paris0-0** [comment]
搞定了，谢谢，把select里改成了这个
module.exports.ENABLE_FLAC = (process.env.ENABLE_FLAC || 'true').toLowerCase() === 'true'

**Comment by nondanee** [comment]
> 不知道怎么改环境变量

windows cmd
```cmd
set ENABLE_FLAC=true
```
unix shell
```sh
export ENABLE_FLAC=true
```

> 具体是加在哪个文件里呢

加在启动脚本(命令)里

**Comment by kagurainroy** [comment]
> > 不知道怎么改环境变量
> 
> windows cmd
> 
> ```batchfile
> set ENABLE_FLAC=true
> ```
> 
> unix shell
> 
> ```shell
> export ENABLE_FLAC=true
> ```
> 
> > 具体是加在哪个文件里呢
> 
> 加在启动脚本(命令)里

node app.js -p 80:443 -f 59.111.181.60 set ENABLE_FlAC=true 是启动的时候改成这样就行了吗= =

**Comment by nondanee** [comment]
@kagurainroy 
```cmd
set ENABLE_FLAC=true && node app.js -p 80:443 -f 59.111.181.60
```
或者写两行
```cmd
set ENABLE_FLAC=true
node app.js -p 80:443 -f 59.111.181.60
```
这是 cmd 的语法，powershell 的不一样，你自己查查吧
