### ISSUE TITLE
Windows和IOS共存问题及解决办法

### ISSUE THREAD

**Issue by Perphist** [nondanee/UnblockNeteaseMusic#563]
#22  #65  #359  #368
以上是我看的主要参考

使用环境是这样：
在OpenWrt上 用了[ luci-app-unblockneteasemusic](https://github.com/project-openwrt/luci-app-unblockneteasemusic) 
简单说下这个插件 它在启动的时候 添加了iptables规则 如果用ipset劫持 不做特殊设置 会把目的地址包含各种music.163.com且端口为80、443的访问 重定向到设置的http、https端口（其实是做了个tcp透明代理） 
然后调用app.js 用-p 设置http、https端口 以和上面的iptables规则一致 当然-e也是支持的 默认是http://music.163.com
理论上说 只要局域网内使用 不管什么设备 应该都能正常访问 但使用下来有点问题

使用效果：
参考 #65  设置-e https://music.163.com
这时候iPhone客户端无需做任何设置 就能正常使用
但windows客户端无法播放无版权及VIP曲目（MAC也是这样）
启动windows客户端时 会看到以下日志信息：
MITM > music.163.com (ssl)
MITM > interface.music.163.com (ssl)
（分别重复N行 这里只贴了两行）

播放无版本或VIP曲目时 日志会有以下信息：
MITM > interface.music.163.com (ssl)
MITM > clientlog.music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > interface.music.163.com (ssl)
MITM > interface.music.163.com (ssl)
MITM > interface.music.163.com (ssl)
[185811] 青花瓷
http://sr.sycdn.kuwo.cn/63517158887e9de12afde170d21589a3/5eeb711e/resource/n1/43/63/3458986373.mp3
但无法播放 客户端表现就是进度条的小圆点转菊花 过一会儿跳到播放列表下一首

如果设置-e http://music.163.com
windows和MAC可以播放 IOS无论是设置http代理 还是信任证书 均会提示网络不给力
这个也尝试过
https://github.com/nondanee/UnblockNeteaseMusic/issues/65#issuecomment-493718439

从下午折腾到现在 从这里找到思路：
https://desperadoj.com/17.html
![Snipaste_2020-06-19_02-53-00](https://user-images.githubusercontent.com/13036302/85060565-06998c80-b1d8-11ea-84e0-3a8b3497e68d.png)

然后摸着[#359](https://github.com/nondanee/UnblockNeteaseMusic/issues/359#issuecomment-573050258) 找到L大的[unblockmusic](https://github.com/coolsnowwolf/lede/blob/master/package/lean/luci-app-unblockmusic/root/etc/init.d/unblockmusic)
三天前更新 应该是可用的 加上上面图里的说明 看了下代码
关键在182、183行 照着改了下原来的插件 没问题了（即针对IOS再开个Server）

折腾下来 各种方案总结如下：
1. 核心就是[本项目](https://github.com/nondanee/UnblockNeteaseMusic)
2. 其他各Issue的配置代理也好 shadowrocket也好 都是为了把云音乐的客户端指向运行的UnblockNeteaseMusic实例
3. 在家用OpenWrt科学上网的话 这个方案最方便 不用在局域网内各个设备上设置了 iptables规则已经帮你做好了指向UnblockNeteaseMusic实例的工作
4. 既然有Openwrt了 再把它搞得能从外网访问 也不是难事 出门也就能用了 这阵子忙完再折腾下这个

另外也在找怎么搞flac #562 
参考了L大一些代码还没搞定（不知道为啥 参考本项目的golang版读取到的倒是flac）
作者方便的时候可以回复下 感谢

更新：
测试了下 flac无法在IOS端播放 蛋疼

**Comment by zenimchan** [comment]
我是参考#527这个搭建的，自签的证书，目前Mac客户端最新版本和Android旧版本可用，iOS上版权歌曲还是灰色，Windows版有你说的一直加载播放不了的问题。

**Comment by nondanee** [comment]
> 理论上说 只要局域网内使用 不管什么设备 应该都能正常访问 但使用下来有点问题

不是，哥，win 版和 mac 版理论上一致还说的过去，因为确实是同构的；与 iOS 和 Android 的移动端完全不一致好吗？又不是一套代码跨所有平台，实现都不一样，表现肯定有差异啊

这个问题 #491 有讨论啊，为啥又新开一个 issue？
win32 的版本不认你手动信任的证书，所以你设成 `-e https://music.163.com` 就播放不了

#65 的方法二全端通用，思路就是要有一个公网可信任的 https endpoint，搭建方法随意，不必复制他的

**Comment by Perphist** [comment]
> > 理论上说 只要局域网内使用 不管什么设备 应该都能正常访问 但使用下来有点问题
> 
> 不是，哥，win 版和 mac 版理论上一致还说的过去，因为确实是同构的；与 iOS 和 Android 的移动端完全不一致好吗？又不是一套代码跨所有平台，实现都不一样，表现肯定有差异啊
> 
> 这个问题 #491 有讨论啊，为啥又新开一个 issue？
> win32 的版本不认你手动信任的证书，所以你设成 `-e https://music.163.com` 就播放不了
> 
> #65 的方法二全端通用，思路就是要有一个公网可信任的 https endpoint，搭建方法随意，不必复制他的

咋说呢 之前我有几点理解有误：
1. 以为同时只能运行一个UnblockNeteaseMusic实例
2. 以为一个UnblockNeteaseMusic实例下的参数可以不同平台通用

以后不半夜折腾了 眼有点花没仔细看以前的讨论

然后你可能没理解我说的意思或者对路由所在的网络层的东西不太清楚 anyway 先明确一些前提：
1. OpenWrt是个路由器上运行的系统 有人基于本项目做了路由上的插件
2. 插件的核心逻辑是做了一套iptables规则 规则的结果就是把局域网内对网易云的访问请求 转发到路由器上运行的UnblockNetease上 80端口的请求转发到-p的第一个端口 443的请求转到-p的第二个端口（-p的两个端口参数在图形化界面输入）
由此 不管是Windows Mac IOS Android Linux 只要数据走这个路由 数据包就会自动转发 所以 这个转发对局域网内的设备是透明的（这也是很多科学上网方案叫透明代理的原因）
这个转发工作在OSI模型的网络层的 除非猪厂程序员又写了一套网络层的东西并且被吸纳成为iptables标准 不然这一层的转发不会失效（应用程序当然可以做其他验证 但这是另一层的东西）
所以 在这个环境下 局域网内不管什么设备 应该都能正常访问 且插件作者在使用说明里也提到过这点
至于IOS端更新后用不了 这就到了 #491
3. 我提到的第一个插件有阵子没更新了 查看代码 只运行了一个UnblockNeteaseMusic实例 我是最近一周多才开始用UnblockNeteaseMusic的
于是就遇到 #491 一样的情况 后来搜到其他人的博客 意识到可以运行两个实例 而且合并到lede的路由分支下的插件 最近刚更新过 看代码是运行了两个实例 和 #491 里下面的回复吻合

至此 我的问题解决了

最后 强烈建议分类集中下issue中有效的方案放到readme或开wiki 哪怕是直接贴issue链接也行
作者只管收录 然后根据反馈把有效的保留 过期无效的拿掉

**Comment by nondanee** [comment]
我懂你的意思

这不只是转发，也并不透明
对 https 流量来说就是劫持，劫持是有条件的，证书就是条件
劫持 https 流量时客户端完全可以拒绝你的假证书，直接报错网络异常，你也用不了
起码从表现上看，信不信任你的证书，在每个端的实现就是不一样的，甚至 ui 请求和 player 请求的实现都不一样，有的跟随你系统设置，有的打死不认证书，也没办法

#65 的方法二全端通用，因为那是个合法证书，客户端应该信任 (当然也不是 100% 信任，可以做 ssl pinning)

不建议一个配置全平台用，因为证书这个细节处理就不同，可以说只有 iOS 是必须设置 `-e` 的，其他都不是必须的，完全可以不配

实在是没时间整理，你看回 issue 都要等周末才能回

**Comment by zenimchan** [comment]
> 我懂你的意思
> 
> 这不只是转发，也并不透明
> 对 https 流量来说就是劫持，劫持是有条件的，证书就是条件
> 劫持 https 流量时客户端完全可以拒绝你的假证书，直接报错网络异常，你也用不了
> 起码从表现上看，信不信任你的证书，在每个端的实现就是不一样的，甚至 ui 请求和 player 请求的实现都不一样，有的跟随你系统设置，有的打死不认证书，也没办法
> 
> #65 的方法二全端通用，因为那是个合法证书，客户端应该信任 (当然也不是 100% 信任，可以做 ssl pinning)
> 
> 不建议一个配置全平台用，因为证书这个细节处理就不同，可以说只有 iOS 是必须设置 `-e` 的，其他都不是必须的，完全可以不配
> 
> 实在是没时间整理，你看回 issue 都要等周末才能回

#65 的方法二不能用自签证书是吧？

**Comment by nondanee** [comment]
是的，要申请可信的证书

对 macOS/linux 来说自签证书是必需的，但 `-e` endpoint 可以不配
对 iOS 来说 `-e` 是必需的，自签(要手动信任)或是公网可信的无所谓
对 win32 来说，没有要求，但 `-e` 地址的证书一定不能是自签的
对 Android 来说，没有要求，虽然 `-e` 自签也是不能信任的，但证书错误时它自动降到 http，所以配了自签的也可以用

#65 
方法一用自签证书劫持修改了 https 流量，并用自签证书做了 endpoint
方法二没有劫持 https 流量 (做了强制降级并劫持 http 流量)，用可信证书做了 endpoint

当然也可以既劫持 https 流量，也用可信证书做 endpoint

**Comment by Perphist** [comment]
全局看肯定不透明 也不是简单的转发（http在应用层 https在传输层） 看的角度不一样而已 说的是一回事儿

没时间整理就算了 门槛太低 用的人多影响大了 不一定是好事（比如度盘那事儿）

总之 感谢付出

**Comment by zenimchan** [comment]
> 是的，要申请可信的证书
> 
> 对 macOS/linux 来说自签证书是必需的，但 `-e` endpoint 可以不配
> 对 iOS 来说 `-e` 是必需的，自签(要手动信任)或是公网可信的无所谓
> 对 win32 来说，没有要求，但 `-e` 地址的证书一定不能是自签的
> 对 Android 来说，没有要求，虽然 `-e` 自签也是不能信任的，但证书错误时它自动降到 http，所以配了自签的也可以用
> 
> #65
> 方法一用自签证书劫持修改了 https 流量，并用自签证书做了 endpoint
> 方法二没有劫持 https 流量 (做了强制降级并劫持 http 流量)，用可信证书做了 endpoint
> 
> 当然也可以既劫持 https 流量，也用可信证书做 endpoint

感谢讲解，我尝试了一下方法二没成功，不太了解Nginx的配置。之前方法一iOS一直不行，不过现在奇怪的是iOS又可以了，推测是之前我在上层DNS服务器上也装了CA证书的原因。现在通过wireguard连回家，4G环境下也可以使用，Mac/iOS/Android旧版本都可以使用，Windows下可以单独在跑一个不带-e参数的服务软件上设置下代理，基本上完美了。

**Comment by zenimchan** [comment]
> > 是的，要申请可信的证书
> > 对 macOS/linux 来说自签证书是必需的，但 `-e` endpoint 可以不配
> > 对 iOS 来说 `-e` 是必需的，自签(要手动信任)或是公网可信的无所谓
> > 对 win32 来说，没有要求，但 `-e` 地址的证书一定不能是自签的
> > 对 Android 来说，没有要求，虽然 `-e` 自签也是不能信任的，但证书错误时它自动降到 http，所以配了自签的也可以用
> > #65
> > 方法一用自签证书劫持修改了 https 流量，并用自签证书做了 endpoint
> > 方法二没有劫持 https 流量 (做了强制降级并劫持 http 流量)，用可信证书做了 endpoint
> > 当然也可以既劫持 https 流量，也用可信证书做 endpoint
> 
> 感谢讲解，我尝试了一下方法二没成功，不太了解Nginx的配置。之前方法一iOS一直不行，不过现在奇怪的是iOS又可以了，推测是之前我在上层DNS服务器上也装了CA证书的原因。现在通过wireguard连回家，4G环境下也可以使用，Mac/iOS/Android旧版本都可以使用，Windows下可以单独在跑一个不带-e参数的服务软件上设置下代理，基本上完美了。

好吧，就在我刚回复完，重新退出重新打开了一下网易云，现在iOS的无版权歌又变灰了，不清楚是什么原因...
