### ISSUE TITLE
Docker pull的最新版启动不起来，网易云拒绝？错误信息如下：

### ISSUE THREAD

**Issue by wxiguo** [nondanee/UnblockNeteaseMusic#564]
Error: connect ECONNREFUSED 59.111.179.214:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '59.111.179.214',
  port: 443
}

59.111.179.213 59.111.179.214 两个地址都是同样的错误。

命令：docker run -d --name unblockneteasemusic -p 8080:8080 nondanee/unblockneteasemusic:latest -s -e https://music.163.com -p 8080:8081

**Comment by wxiguo** [comment]
弃用Docker启动，使用node app.js 可以正常 -f 指定地址播放

**Comment by nondanee** [comment]
你想说明什么？docker 和 master 的代码是一致的

**Comment by wxiguo** [comment]
> 你想说明什么？docker 和 master 的代码是一致的

docker部署的时候提示上述信息，是-f 没有起作用么？
用node app.js -f 启动没问题。
代码都是一样的0.25.3

**Comment by JayceCao** [comment]
好奇怪，我也遇到了这个问题：
```
Error: connect EHOSTUNREACH 59.111.179.213:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '59.111.179.213',
  port: 443
}
```
记得以前用 docker 跑别的 node 应用的时候好像也遇到过这个问题......
