### ISSUE TITLE
UWP版网易云音乐不再单独维护

### ISSUE THREAD

**Issue by Sunshine018** [nondanee/UnblockNeteaseMusic#565]
现在UWP的网易云音乐官方可能已经放弃，现阶段的Microsoft Store里的网易云音乐是Win32转制版本，请问转制后的版本是继续按照现有UWP版本使用方法是用还是需要参考Win32版本自行探索？

**Comment by nondanee** [comment]
使用方法同 win32 版

**Comment by kagurainroy** [comment]
可以卸载现有的win32版，然后通过非官方途径安装uwp版然后禁用自动更新
