### ISSUE TITLE
安卓手机怎么在流量的情况下使用代理呀

### ISSUE THREAD

**Issue by lee1080f** [nondanee/UnblockNeteaseMusic#58]
在vps上已经搭建好了这个服务了，在电脑端用的很爽。但是就是出门后就不能连接上代理，所以有没有方法解决在流量的情况下让网易云使用代理呢？或者让网易云通过ssr实现代理的方法呢。

**Comment by nondanee** [comment]
自己加 APN 啊

**Comment by nondanee** [comment]
$$ 和 $$R 参考 https://github.com/nondanee/UnblockNeteaseMusic/issues/53#issuecomment-485466290
应该只能用 hosts 模式，开 80 端口
核心步骤
1. 取 IP
```
curl music.httpdns.c.163.com/d --data music.163.com
```
2. iptables 设置 nat
```
iptables -t nat -A OUTPUT -p tcp -d <Netease IP> -j DNAT --to-destination 127.0.0.1
```
可能只要这两步就可以成功，请自行测试

**Comment by nondanee** [comment]
@lee1080f 
在 #53 的教程我修改过了应该很详细了，直接到那边讨论就好
这个 issue 我关了
