### ISSUE TITLE
突然用不了了,求解答

### ISSUE THREAD

**Issue by shikunshowyou** [nondanee/UnblockNeteaseMusic#580]
![image](https://user-images.githubusercontent.com/28568478/87917595-ce6fbd00-caa7-11ea-88a7-bfbb0c58265c.png)

**Comment by shikunshowyou** [comment]
![image](https://user-images.githubusercontent.com/28568478/87918539-2c50d480-caa9-11ea-883d-0161d0670c81.png)

**Comment by redn3ck** [comment]
刚才那会确实不行了，解析不出地址，还以为凉了，过了一会又好了，目前正常使用

**Comment by shikunshowyou** [comment]
> 刚才那会确实不行了，解析不出地址，还以为凉了，过了一会又好了，目前正常使用

我这里还是不行，很奇怪，这两天突然用不了了，像是连不上网似的  很多网易云自己的歌曲都听不了

**Comment by shikunshowyou** [comment]
> > 刚才那会确实不行了，解析不出地址，还以为凉了，过了一会又好了，目前正常使用
> 
> 我这里还是不行，很奇怪，这两天突然用不了了，像是连不上网似的 很多网易云自己的歌曲都听不了

不是好像连不上网，就是网易云直接连不上网了，mac 客户端一直显示的就是网络不给力，连不上

**Comment by redn3ck** [comment]
> 不是好像连不上网，就是网易云直接连不上网了，mac 客户端一直显示的就是网络不给力，连不上

没有mac设备，没法帮你测试呢，不过你还是检查一下服务端吧，多测试测试

**Comment by shikunshowyou** [comment]
> > 不是好像连不上网，就是网易云直接连不上网了，mac 客户端一直显示的就是网络不给力，连不上
> 
> 没有mac设备，没法帮你测试呢，不过你还是检查一下服务端吧，多测试测试

![image](https://user-images.githubusercontent.com/28568478/87921839-b438dd80-caad-11ea-92c5-25cb61be4d1d.png)
无法联网 郁闷

**Comment by redn3ck** [comment]
> 无法联网 郁闷

你要去检查服务端的代理啊，代理关掉测试，等等，自己要会测试啊，兄弟

**Comment by shikunshowyou** [comment]
> > 无法联网 郁闷
> 
> 你要去检查服务端的代理啊，代理关掉测试，等等，自己要会测试啊，兄弟

这语言不会啊 看不懂，你告我一下代理在哪里关  我自己试试 感谢

**Comment by redn3ck** [comment]
> 这语言不会啊 看不懂，你告我一下代理在哪里关 我自己试试 感谢

我去，你小白啊，代理不知道的话，你是怎么用起来的？？

**Comment by shikunshowyou** [comment]
> > 这语言不会啊 看不懂，你告我一下代理在哪里关 我自己试试 感谢
> 
> 我去，你小白啊，代理不知道的话，你是怎么用起来的？？

看他的方法一  修改host   命令： node app.js -f 59.111.181.60 -p 80   配置好了就成了

**Comment by redn3ck** [comment]
> 看他的方法一 修改host 命令： node app.js -f 59.111.181.60 -p 80 配置好了就成了
ip重新获取一下，然后看看服务端的log提示什么，自己测试，只能说这么多了，很多东西说不清

**Comment by shikunshowyou** [comment]
> > 看他的方法一 修改host 命令： node app.js -f 59.111.181.60 -p 80 配置好了就成了
> 
> ip重新获取一下，然后看看服务端的log提示什么，自己测试，只能说这么多了，很多东西说不清

和版本有关系  700以上的会有问题 降级就好了
**https://github.com/nondanee/UnblockNeteaseMusic/issues/48**
