### ISSUE TITLE
部署到服务器上打不开，是姿势不对吗

### ISSUE THREAD

**Issue by bushizhangwudia** [nondanee/UnblockNeteaseMusic#586]
部署到腾讯云上面，用的端口不是80，端口号防火墙也开启了。本地windows客户端播放不了，但服务器的日志是纯在的。又没懂哥遇到过，求个解决方式。
![image](https://user-images.githubusercontent.com/39025769/88752303-2d11f680-d18c-11ea-9757-ff89407a8ac3.png)

![image](https://user-images.githubusercontent.com/39025769/88752329-3dc26c80-d18c-11ea-970d-919fea20d3f3.png)

**Comment by bushizhangwudia** [comment]
走的是客户端内的代理，不是修改host

**Comment by Jason-Fx** [comment]
等久一点才能播~

**Comment by nondanee** [comment]
猜测是加了 `-s` 没加 `-e`，或者是加了 `-e` 但是证书有点问题
