### ISSUE TITLE
貌似与frp穿透有冲突？启动成功但是不会出现日志也不能听歌

### ISSUE THREAD

**Issue by cryyin** [nondanee/UnblockNeteaseMusic#587]
pac模式部署在阿里云上，同时有frp server，frps要用80和443，貌似80失败也会用8080，遂指定-p 9000，运行一段时间后挂了，再开提示跑在9000但不输出日志也不能听歌，默认跑在8080可以输出日志。
附上一段报错日志
<--- Last few GCs --->
) [828:000001B48EFFB990] 32486500 ms: Mark-sweep 1024.7 (1029.6) -> 1024.1 (1029.9) MB, 1916.8 / 1.6 ms  (+ 148.4 ms in 9 steps since start of marking, biggest step 146.5 ms, walltime since start of marking 3171 ms) (average mu = 0.279, current mu = 0.349) [828:000001B48EFFB990] 32489012 ms: Mark-sweep 1024.8 (1029.9) -> 1023.2 (1029.9) MB, 2329.6 / 1.6 ms  (+ 151.2 ms in 10 steps since start of marking, biggest step 149.7 ms, walltime since start of marking 2512 ms) (average mu = 0.162, current mu = 0.012)

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF7BC12A09D]
Security context: 0x0062105808d1 <JSObject>
    1: socketOnClose(aka socketOnClose) [000002585166E269] [_http_server.js:~518] [pc=0000004E580E2DBA](this=0x02bacd5804b1 <undefined>,0x02281d305a19 <Socket map = 000000060E3FA9A9>,0x02281d309f31 <Object map = 000000060E3F9379>)
    2: emit [0000016DD17D8E49] [events.js:~263] [pc=0000004E5829A2AF](this=0x02281d305a19 <Socket map = 000000060E3FA9A9>,0x03e...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7BB51538F napi_wrap+114751
 2: 00007FF7BB4BFE26 v8::base::CPU::has_sse+66646
 3: 00007FF7BB4C0C26 v8::base::CPU::has_sse+70230
 4: 00007FF7BBCD5B3E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF7BBCBDC11 v8::SharedArrayBuffer::Externalize+833
 6: 00007FF7BBB89E7C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
 7: 00007FF7BBB950B0 v8::internal::Heap::ProtectUnprotectedMemoryChunks+1312
 8: 00007FF7BBB91BD4 v8::internal::Heap::PageFlagsAreConsistent+3204
 9: 00007FF7BBB873D3 v8::internal::Heap::CollectGarbage+1283
10: 00007FF7BBB85A44 v8::internal::Heap::AddRetainedMap+2452
11: 00007FF7BBBA6D8D v8::internal::Factory::NewFillerObject+61
12: 00007FF7BB90CED1 v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+1665
13: 00007FF7BC12A09D v8::internal::SetupIsolateDelegate::SetupHeap+546637
14: 0000004E580E2DBA

**Comment by cryyin** [comment]
而且会报MITM > nullhttps

**Comment by iDesperad0** [comment]
挖个坟，我也出现同样问题，求问最后是如何解决的？

**Comment by 1273457900** [comment]
> 貌似80失败也会用8080，遂指定-p 9000，运行一段时间后挂了，再开提示跑在9000但不输出日志也不能听歌，默认跑在8080可以输出日志。
> 附上一段报错日志

楼主解决了吗。我frp也有问题

**Comment by cryyin** [comment]
> 挖个坟，我也出现同样问题，求问最后是如何解决的？

没解决，pac好像有问题，应该与frp无关
