### ISSUE TITLE
node app起来是403 nginx

### ISSUE THREAD

**Issue by wdw54188ccc** [nondanee/UnblockNeteaseMusic#59]

**Comment by nondanee** [comment]
是啊，headers 里没有 'HOST': 'music.163.com' 就是 403
https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-441240990

**Comment by wdw54188ccc** [comment]
那要怎么做呢，从我本地配置host吗？

**Comment by nondanee** [comment]
那你现在是怎么配置的呢？

**Comment by wdw54188ccc** [comment]
好的谢谢，但是我无法关闭80，有进程守护，能帮忙看下怎么关掉root和www吗
![image](https://user-images.githubusercontent.com/33246715/56891011-a6b0c580-6aad-11e9-86b1-13429dbfd4fe.png)

**Comment by nondanee** [comment]
这个 httpd 是 apache 吧？我猜的
你想关掉？试试看 service apache2 stop
(不知道你是什么系统，你自己搜一下怎么关)
或者说是要用 apache 做反向代理吗？不好意思我没用过 apache，不会配😅

**Comment by wdw54188ccc** [comment]
好的，谢谢啦
