### ISSUE TITLE
vip歌曲無法解鎖(大陆之外)

### ISSUE THREAD

**Issue by hoktophen** [nondanee/UnblockNeteaseMusic#594]

**Comment by hoktophen** [comment]
使用的指令 node app.js -p 8080
![image](https://user-images.githubusercontent.com/64723622/90334629-a53c4100-e001-11ea-8723-63dbd139a28b.png)

**Comment by hoktophen** [comment]
![image](https://user-images.githubusercontent.com/64723622/90334655-d6b50c80-e001-11ea-8e11-d9230f83d058.png)

**Comment by hoktophen** [comment]
有什麼辦法可以解決?

**Comment by NULL204** [comment]
尝试换其他的端口，8080是常用端口，可能会冲突

**Comment by NULL204** [comment]
https://github.com/xiaoyv404/NeteaseMusic-Unlocker/
尝试使用这个脚本一键部署，在运行前请用任务管理器退出Node.js

**Comment by hoktophen** [comment]
同樣無法解鎖vip

**Comment by NULL204** [comment]
请问你是大陆之外的吗？这个我知道，是服务器问题，这个你和原作者讨论一下，他会帮忙的应该

**Comment by hoktophen** [comment]
對的，我在香港，如何解決

**Comment by NULL204** [comment]
这个需要你去找原作者了，我不会，可能是你·无法访问某些服务器导致的

**Comment by hoktophen** [comment]
@NULL204我要找nondanee嗎 ?

**Comment by NULL204** [comment]
是的

**Comment by Hew007** [comment]
我用docker-compose直接部署就能解锁vip

**Comment by hoktophen** [comment]
qaq還是這樣,vip基本上無法聽,自動強行播下一首qaq.

**Comment by hereisderek** [comment]
-o joox kuwo

**Comment by skyispainted** [comment]
我有一台香港的服务器也无法解锁，但是用大陆的服务器就没有问题，我觉得应该是网易云通过IP来限制服务区域了，网易云好像只在大陆提供服务，可以试试购买内地的服务器来搭建环境
