### ISSUE TITLE
流量 APN全部走代理了

### ISSUE THREAD

**Issue by sunht6** [nondanee/UnblockNeteaseMusic#596]
使用 apn的方式所有流量都走 代理了 服务端代理这边已经开启了-s选项，怎么能只代理网易云的网址吗？

还有怎么加入用户名和密码呀，暴露在公网上感觉很危险的。

**Comment by NextMsg** [comment]
-t username:password
这样加入 验证

**Comment by nondanee** [comment]
APN 代理只能全局
公网不安全的话，部署在本地就行了，本地全局代理也不怎么影响速度
