### ISSUE TITLE
Error: Cannot find module 'commander'

### ISSUE THREAD

**Issue by Hiboboo** [nondanee/UnblockNeteaseMusic#6]
![tim 20180723115036](https://user-images.githubusercontent.com/11403290/43056398-b87dff4c-8e6e-11e8-83d6-2ccc5f9cd100.png)
直接报错了啊。
看了app.js的源码，貌似是`const program = require('commander')`找不到commander模块？

**Comment by nondanee** [comment]
`npm install`

**Comment by Hiboboo** [comment]
@nondanee 问题解决了已经，我用了`npm install commander --save`命令之后就可以正常运行了。
但是，新的问题出现了。实在是不好意思，没看懂你写的那个使用文档，修改Hosts是怎么修改的？修改本地的Hosts文件内容吗？还是修改别的什么东西？
因为我运行了app.js之后，打印了`Server running @ http://0.0.0.0:8080`这个信息，并且易云里的歌曲还是灰色不可点击的。我要怎么做呢？

**Comment by nondanee** [comment]
windows客户端？

**Comment by Hiboboo** [comment]
@nondanee 对，Windows10版本的
