### ISSUE TITLE
host和代理模式使用反馈

### ISSUE THREAD

**Issue by y4kumo** [nondanee/UnblockNeteaseMusic#60]
win7  网易云音乐v2.5.0

host模式  全军覆没(刷新了dns也没用  ipconfig /flushdns)  首页提示网络问题不能加载  所有歌曲变灰(本人在海外)

全局代理模式  成功！(例如周杰伦专辑ok)

**Comment by y4kumo** [comment]
很可惜  没版权的歌还是播放不了。 = =

**Comment by nondanee** [comment]
比如？

**Comment by nondanee** [comment]
看了下，是 QQ 音源炸了，往前回滚吧
