### ISSUE TITLE
Windows Server下使用代理模式貌似无法使用

### ISSUE THREAD

**Issue by jdwsxs** [nondanee/UnblockNeteaseMusic#61]
服务器环境：良心云Windows Server 2016   + Strict 模式 
本地环境：网易云 Windows 版内使用自带代理功能连接
网易云音乐为黑胶会员

现象：会员歌曲正常收听，版权受限歌曲灰色消失，但依旧无法正常收听，提示“加载失败”

是我的姿势有问题吗...

![image](https://user-images.githubusercontent.com/5888084/56972477-a55ec600-6b9d-11e9-9e07-48b3d89f8dc4.png)

**Comment by nondanee** [comment]
姿势没问题
QQ 音乐封 vkey 太快了，今天是我换 API 第二天 #60 
已经回滚了 https://github.com/nondanee/UnblockNeteaseMusic/commit/1392128fc0dc4e4ec97f15261ea70a9643f062e4
这是第 3 次回滚 https://github.com/nondanee/UnblockNeteaseMusic/releases
听 128 Kbps 吧，心累......

**Comment by nondanee** [comment]
周杰伦的歌，2018 年之前的，应该可以听，能匹配到网易云自己的源

**Comment by jdwsxs** [comment]
好的 谢谢啦
