### ISSUE TITLE
有请求日志但加载不了歌曲问题

### ISSUE THREAD

**Issue by libilin2018** [nondanee/UnblockNeteaseMusic#62]
![微信图片_20190501094444](https://user-images.githubusercontent.com/41327802/57002976-d23ec780-6bf5-11e9-8f68-5211c4f8bb27.png)
第一次使用可以正常获取歌曲，现在不行了，不知道是什么缘故，望作者大大解决

**Comment by nondanee** [comment]
(默认你在最新的 commit 版本)
只考虑 "安静" 播不了的问题
你把这个 "HEAD" 改成 “GET” 试试
https://github.com/nondanee/UnblockNeteaseMusic/blob/1392128fc0dc4e4ec97f15261ea70a9643f062e4/provider/match.js#L38
相关解释在此 https://github.com/nondanee/UnblockNeteaseMusic/issues/39#issuecomment-457122641

**Comment by libilin2018** [comment]
谢谢作者大大,已经解决了.重新clone代码又可以了,不知道什么缘故

**Comment by nondanee** [comment]
以后用 `git pull` 吧
