### ISSUE TITLE
macOS + 832 网络错误

### ISSUE THREAD

**Issue by isilcala** [nondanee/UnblockNeteaseMusic#622]
首先感谢项目，虽然折腾了两天还是没用上。

MacOS Mojave，客户端 832。可以看到原本灰色的歌曲亮起，但是无法播放，会报网络错误。

尝试过项目 ca，自签 ca，均可以信任，打开网页也是绿锁状态，证书信任应该没有问题。
试过 openwrt 里的各个版本，试过本地的 npm，均报网络错误。
试过删掉 832 重装 700，也不行。
试过 pac，试过 hosts，结果一样。

![image](https://user-images.githubusercontent.com/4241022/94532038-ee71e880-026f-11eb-9f31-692a16ce2672.png)
观察下来每次报网络错误，均会产生四条记录：
MITM > null 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com

日志里偶尔也见到过一些：
MITM > music.163.com (ssl)
但是并没有歌曲被成功播放。

项目里的各个 issue 基本都爬过了一遍，不知道是否还有什么遗漏了？

谢谢。

**Comment by isilcala** [comment]
对了截图里用的是 #597 的办法。

**Comment by hemisu** [comment]
用 safari 打开 https://music.163.com 能访问吗

**Comment by isilcala** [comment]
> 用 safari 打开 https://music.163.com 能访问吗

可以，地址栏绿锁

**Comment by hemisu** [comment]
![image](https://user-images.githubusercontent.com/11391390/95415876-029aa180-0964-11eb-974c-c88660b4bd1e.png)

我刚刚跑了一遍，可以用 👀，看下还有啥疏漏没

**Comment by isilcala** [comment]
依旧……不行……
我用 Windows 的机器测试了 openwrt 里的服务端是没问题的。感觉问题在 mac 和证书中的某个地方。
从我这个 mac 的输出日志可以看得出什么线索/debug 方向嘛？我的日志里绝大部分都没有 (ssl)

**Comment by hemisu** [comment]
帮不到了 :(

**Comment by isilcala** [comment]
我再磨磨……

**Comment by isilcala** [comment]
和我所在的网络环境非大陆 ip 有关。我在阿里云上用 docker 部署了，从 log 看kuwo 和 kugou 可以解析出地址，但是kuwo 和 kugou 都被公司网络屏蔽了……其他的平台都解析不出地址。暂时先关闭吧，我再磨磨。

**Comment by alkayoun** [comment]
80 端口一直被占用，切换到其他端口 网页是正常，但是app还是不行。不知道是不是一定要80：443这样

**Comment by alkayoun** [comment]
最后妥协，不使用HOST方式 转而 使用设置网络代理的方式，解决了app能通过项目获取置灰歌曲。
