### ISSUE TITLE
能改用sock5代理吗

### ISSUE THREAD

**Issue by gqm36524** [nondanee/UnblockNeteaseMusic#63]
能改用sock5代理吗，感觉http有限速，才40kb/s加载一首歌需要好久

**Comment by otherbanana** [comment]
没有限速吧

**Comment by nondanee** [comment]
@gqm36524 
不能，你自己找找代理转换嘛（我试过可以用）
https://github.com/snail007/goproxy/blob/master/README_ZH.md#62-https转httpssocks5ss

![image](https://user-images.githubusercontent.com/26399680/57010217-2d8cac00-6c2e-11e9-9e73-5c0d7ceef546.png)

**Comment by gqm36524** [comment]
> 没有限速吧
你是在本地测试的，还是远端服务器上

**Comment by gqm36524** [comment]
> @gqm36524
> 不能，你自己找找代理转换嘛（我试过可以用）
> [https://github.com/snail007/goproxy/blob/master/README_ZH.md#62-https转httpssocks5ss](https://github.com/snail007/goproxy/blob/master/README_ZH.md#62-https%E8%BD%AChttpssocks5ss)
> 
> ![image](https://user-images.githubusercontent.com/26399680/57010217-2d8cac00-6c2e-11e9-9e73-5c0d7ceef546.png)

我感觉是因为http容易被防火墙干扰导致的限速

**Comment by nondanee** [comment]
本地测试

我只是表明用 goproxy 把 http proxy 转成 socks proxy 的可行性

你觉得 socks 不易被干扰就在前面加一个 socks 到 http 的转换就行了

怎么部署，是你自己的事~
