### ISSUE TITLE
请问我想研究一下云盘的标识 就是图标那些

### ISSUE THREAD

**Issue by Apiee** [nondanee/UnblockNeteaseMusic#641]
我要怎么才能知道 sq vip 云盘这些标识对应的参数呢?
比如 vip 对应 fee 
那云盘这个呢?

**Comment by Apiee** [comment]
![Uploading image.png…]()

**Comment by Apiee** [comment]
![image](https://user-images.githubusercontent.com/24862113/99181891-5458f780-276c-11eb-9af7-758c50ae8752.png)

**Comment by Apiee** [comment]
已解决

**Comment by waleraye** [comment]
你好,这个怎么解决的呀,我想区分出来没版权的歌曲加一个类型的这样的图标
