### ISSUE TITLE
可以帮我删除我提交的这个issue吗..

### ISSUE THREAD

**Issue by Briansunyang** [nondanee/UnblockNeteaseMusic#642]
TUNNEL > i.instagram.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > i.instagram.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > m.youtube.com:443
TUNNEL > www.youtube.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > m.youtube.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > www.youtube.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > www.youtube.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > m.youtube.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > discordapp.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > m.youtube.com:443
TUNNEL > m.youtube.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > www.google.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > m.youtube.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > www.youtube.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > i.instagram.com:443
TUNNEL > m.youtube.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > api.audiomack.com:443
MITM > bing.com 
TUNNEL > api.audiomack.com:443
TUNNEL > www.youtube.com:443
TUNNEL > api.audiomack.com:443
MITM > bing.com 
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > api.audiomack.com:443
MITM > bing.com 
TUNNEL > ios.prod.ftl.netflix.com:443
TUNNEL > www.youtube.com:443
MITM > null 
TUNNEL > api.audiomack.com:443
MITM > null 
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > www.vietinfo.eu:443
TUNNEL > m.youtube.com:443
TUNNEL > www.youtube.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > m.youtube.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > www.famosasderevista.net:443
TUNNEL > api.audiomack.com:443
TUNNEL > www.loombard.pl:443
TUNNEL > api.audiomack.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > mobileproxy.passport.yandex.net:443
TUNNEL > mobileproxy.passport.yandex.net:443
TUNNEL > www.avito.ru:443
TUNNEL > api.audiomack.com:443
TUNNEL > www.loombard.pl:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > mobileproxy.passport.yandex.net:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > www.youtube.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > ext.captcha.yandex.net:443
TUNNEL > api.audiomack.com:443
TUNNEL > mobileproxy.passport.yandex.net:443
TUNNEL > api.audiomack.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > mobileproxy.passport.yandex.net:443
TUNNEL > mobileproxy.passport.yandex.net:443
TUNNEL > api.audiomack.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > finance.yahoo.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > i.instagram.com:443
TUNNEL > i.instagram.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > i.instagram.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > t.me:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
MITM > www.sbjudge3.com 
TUNNEL > ext.captcha.yandex.net:443
TUNNEL > m.youtube.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
MITM > promodj.com 
TUNNEL > mobileproxy.passport.yandex.net:443
TUNNEL > promodj.com:443
TUNNEL > api.audiomack.com:443
TUNNEL > m.youtube.com:443
TUNNEL > ios.prod.ftl.netflix.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443
TUNNEL > l9bjkkhaycw6f8f4.soundcloud.com:443

**Comment by yangon99** [comment]
架设在公网的服务最好开启严格模式（运行时使用 “-s” 参数）
你可以先关闭这个 issue，最近作者似乎不是很活跃
