### ISSUE TITLE
在阿里云运行     node会OOS内存溢出被kill掉

### ISSUE THREAD

**Issue by rocsun** [nondanee/UnblockNeteaseMusic#644]

**Comment by rocsun** [comment]
被kill时系统情况：
[ pid ]   uid  tgid total_vm      rss nr_ptes swapents oom_score_adj name
[ 9074]     0  9074   644243   340026    1226        0             0 node
Out of memory: Kill process 9074 (node) score 703 or sacrifice child

**Comment by Atomjob5** [comment]
用 pm2 ，设置内存占用超过200M把进程踢掉重启，解决
