### ISSUE TITLE
代理现在只能用于下载，vip和没版权放不了，一直转圈或者加载失败，是移动宽带问题吗？已知联通网络没有问题

### ISSUE THREAD

**Issue by Petya360** [nondanee/UnblockNeteaseMusic#654]
如题，pc和手机都如此，求解

**Comment by Petya360** [comment]
目前好像只有移动宽带会这样，各位是怎样的呢？

**Comment by fox9264** [comment]
现在我的是特定的歌听不了，好像是没有版权的歌听不了，不过vip的可以听，http://music.163.com/song?id=413074434 这个和http://music.163.com/song?id=420125990都是听不了的。

**Comment by Petya360** [comment]
> 现在我的是特定的歌听不了，好像是没有版权的歌听不了，不过vip的可以听，http://music.163.com/song?id=413074434 这个和http://music.163.com/song?id=420125990  都是听不了的。同样是移动宽带

联通的是都可以，周杰伦的都可以听

**Comment by fox9264** [comment]
> > 现在我的是特定的歌听不了，好像是没有版权的歌听不了，不过vip的可以听，http://music.163.com/song?id=413074434 这个和http://music.163.com/song?id=420125990  都是听不了的。同样是移动宽带
> 
> 联通的是都可以，周杰伦的都可以听，目前不知道移动网怎么样

我用了别人搭建的代理发现歌是可以听的，不知道是因为我重新搭建的问题还是怎么回事，上次搭建的时候是可以正常用的。

**Comment by Petya360** [comment]
> > > 现在我的是特定的歌听不了，好像是没有版权的歌听不了，不过vip的可以听，http://music.163.com/song?id=413074434 这个和http://music.163.com/song?id=420125990  都是听不了的。同样是移动宽带
> 
> > 
> 
> > 联通的是都可以，周杰伦的都可以听，目前不知道移动网怎么样
> 
> 
> 
> 我用了别人搭建的代理发现歌是可以听的，不知道是因为我重新搭建的问题还是怎么回事，上次搭建的时候是可以正常用的。

大概是网络不稳定，还有就是，pac模式比较通用，并且也很稳定，比sock5代理要稳定

**Comment by belfasthms** [comment]
你解决了吗，我的现在也不能听VIP歌曲了
