### ISSUE TITLE
ios 搜索失败/播放失败

### ISSUE THREAD

**Issue by tangspoon66** [nondanee/UnblockNeteaseMusic#66]
ios 大部分情况下搜索失败/播放失败，就一阵阵子的，极少部分时候可以，然后其他app的网络也会断开【不过ios网易云HD就很流畅一点问题都没有】

**Comment by nondanee** [comment]
@tangspoon66 
不好意思，没法测试，所以不好定位问题（README 里是没说支持 iOS 的），帮不了你

其它应用会断网是不是你开了 `-s` ？
用的 surge/shadowsocket 还是系统 WLAN 代理？surge/shadowsocket 应该有缺省规则 DIRECT 吧

装证书了吗？没装的话装一下试试（server 开启 https 监听）
如果已经装了，我就不知道为什么了==

之前我测试的用系统代理 HD 版是无法强制降级的，现在支持自签证书了，可能可以了吧我不知道

**Comment by Anopia** [comment]
DOMAIN-SUFFIX,163.com, UnblockMusic
DOMAIN-SUFFIX,126.net, UnblockMusic
在规则里添加这两个规则
