### ISSUE TITLE
youtube music api现在还能使用吗?

### ISSUE THREAD

**Issue by shzxm** [nondanee/UnblockNeteaseMusic#661]
API KEY 要自己填
https://github.com/nondanee/UnblockNeteaseMusic/blob/00c857d5cb9ca7a009cded7d52ebc21c875875f0/provider/youtube.js#L7

官方 guide https://developers.google.com/youtube/v3/getting-started#before-you-start

P.S. 不知道算不算 Youtube Music，播放用的是 Youtube 视频的音频部分

_Originally posted by @nondanee in https://github.com/nondanee/UnblockNeteaseMusic/issues/302#issuecomment-548418129_

**Comment by shzxm** [comment]
我看了一下 现在已经没有 youtubu.js这个脚本了

**Comment by lonelykid** [comment]
Windows端可以放。重构改了目录而已

**Comment by shzxm** [comment]
> Windows端可以放。重构改了目录而已

啊.位置在哪了....

找了一圈没找到...
