### ISSUE TITLE
最新master分支打包 windows版本 默认端口8848 支持开机自启 

### ISSUE THREAD

**Issue by cyao2q** [nondanee/UnblockNeteaseMusic#667]
[unblockneteasemusic.zip](https://github.com/nondanee/UnblockNeteaseMusic/files/5735086/unblockneteasemusic.zip)

开机自启 使用的 winsw windows服务 端口可以自己配置 默认是8848

**Comment by 4285f4** [comment]
感谢打包，不过不知道为什么我用最新的master里面的app.js替换原本的运行和使用您打包的都会出现以下错误，不知道可有解决办法？
{ Error: getaddrinfo ENOTFOUND httpdns.n.netease.com httpdns.n.netease.com:80
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'httpdns.n.netease.com',
  host: 'httpdns.n.netease.com',
  port: 80 }


> [unblockneteasemusic.zip](https://github.com/nondanee/UnblockNeteaseMusic/files/5735086/unblockneteasemusic.zip)
> 
> 开机自启 使用的 winsw windows服务 端口可以自己配置 默认是8848

**Comment by 4285f4** [comment]
> 感谢打包，不过不知道为什么我用最新的master里面的app.js替换原本的运行和使用您打包的都会出现以下错误，不知道可有解决办法？
> { Error: getaddrinfo ENOTFOUND httpdns.n.netease.com httpdns.n.netease.com:80
> at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
> errno: 'ENOTFOUND',
> code: 'ENOTFOUND',
> syscall: 'getaddrinfo',
> hostname: 'httpdns.n.netease.com',
> host: 'httpdns.n.netease.com',
> port: 80 }
> 
> > [unblockneteasemusic.zip](https://github.com/nondanee/UnblockNeteaseMusic/files/5735086/unblockneteasemusic.zip)
> > 开机自启 使用的 winsw windows服务 端口可以自己配置 默认是8848

解决了，是我自己的 AdGuardHome 拦截了  httpdns.n.netease.com 这个地址

**Comment by aiguoartist** [comment]
第一次用，下好这个运行了，WIN上运行网易云音乐该灰的还灰，有别的前置需求吗？

**Comment by cyao2q** [comment]
> 第一次用，下好这个运行了，WIN上运行网易云音乐该灰的还灰，有别的前置需求吗？

网易云设置代理啊

**Comment by cyao2q** [comment]
> > 第一次用，下好这个运行了，WIN上运行网易云音乐该灰的还灰，有别的前置需求吗？
> 
> 网易云设置代理啊

![image](https://user-images.githubusercontent.com/10820724/103015629-c0a0f500-457b-11eb-98b1-c045d09376de.png)

**Comment by SekiBetu** [comment]
打包的index.js文件能分享一下吗，以后自己打包快点

傻了，项目里有，当我没说

**Comment by SekiBetu** [comment]
我直接用pkg打包怎么要70mb，大佬你怎么缩到8mb的

**Comment by cyao2q** [comment]
> 我直接用pkg打包怎么要70mb，大佬你怎么缩到8mb的

使用低版本的node呗  打开 package.json pkg哪里 最后添加  -t node8

然后目录文件夹 npm run pkg

![image](https://user-images.githubusercontent.com/10820724/103049192-ff5e9b80-45cb-11eb-8f69-ea5d7c51fff0.png)

**Comment by cyao2q** [comment]
> 我直接用pkg打包怎么要70mb，大佬你怎么缩到8mb的

也是20多m 压缩后就8m了

**Comment by aiguoartist** [comment]
> > > 第一次用，下好这个运行了，WIN上运行网易云音乐该灰的还灰，有别的前置需求吗？
> > 
> > 
> > 网易云设置代理啊
> 
> ![image](https://user-images.githubusercontent.com/10820724/103015629-c0a0f500-457b-11eb-98b1-c045d09376de.png)
运行了以后长这样子，127.0.0.1：8848和0.0.0.0：8080都试了不行，是我这边的问题吗？
![屏幕截图 2020-12-25 032221](https://user-images.githubusercontent.com/64490875/103114775-4e561080-4660-11eb-93c1-eb4d65f801bb.png)

**Comment by aiguoartist** [comment]
> > > 第一次用，下好这个运行了，WIN上运行网易云音乐该灰的还灰，有别的前置需求吗？
> > 
> > 
> > 网易云设置代理啊
> 
> ![image](https://user-images.githubusercontent.com/10820724/103015629-c0a0f500-457b-11eb-98b1-c045d09376de.png)

成功了!**谢谢！**
第一次改的时候失败了，删除了文件重新解压一次运行就没问题了。
