### ISSUE TITLE
大佬  来个图文教程啊  有些地方不懂

### ISSUE THREAD

**Issue by LoveFForever** [nondanee/UnblockNeteaseMusic#67]

**Comment by nondanee** [comment]
哪些地方不懂呢……

**Comment by kifast** [comment]
图文 教程
此文为面向新手的详细手把手图文攻略，对小白友好，操作系统为Windows
https://blog.csdn.net/JayRoxis/article/details/88963180
懒得搬图了

**Comment by LoveFForever** [comment]
![1111111113](https://user-images.githubusercontent.com/22911218/57178247-10f7aa80-6ea0-11e9-9282-7168ce9b587a.png)
![222222222](https://user-images.githubusercontent.com/22911218/57178248-11904100-6ea0-11e9-8887-5799b322b7e2.png)
画圈的都不懂啊 在哪输入啊

**Comment by nondanee** [comment]
@LoveFForever 
![image](https://user-images.githubusercontent.com/26399680/57178306-b27efc00-6ea0-11e9-9edc-fdb0bf7eebb2.png)

**Comment by LoveFForever** [comment]
> @LoveFForever
> ![image](https://user-images.githubusercontent.com/26399680/57178306-b27efc00-6ea0-11e9-9edc-fdb0bf7eebb2.png)

感谢
