### ISSUE TITLE
windows客户端使用hosts模式uwp版本无法联网客户端正常使用

### ISSUE THREAD

**Issue by zwupup** [nondanee/UnblockNeteaseMusic#68]
Windows10 家庭中文版
网易云音乐最新客户端 2.5.2 Build：197409；uwp版1.4.1.0
使用的hosts模式
先是用的uwp版本，连不上网，显示网络异常；改用客户端，可以使用，听了一下午都正常
hosts模式下uwp版本还有什么命令设置吗

**Comment by nondanee** [comment]
应该没有

**Comment by nondanee** [comment]
除了要开启 loopback，应该没有

**Comment by zwupup** [comment]
原来如此，我没开loopback，我看这个写在方法2中，以为使用hosts模式不需要设置这个。
执行这个命令后，就可以了，谢谢，棒棒的

**Comment by nondanee** [comment]
@zwupup
客气 ，我是刚试的，我之前也不知道其实 😂
不过发现如果 hosts 改的不是 127.0.0.1 是不用开 loopback 的
UWP 应用应该只是限制了 loopback，README 上写不是很准确，我去改改
