### ISSUE TITLE
IOS 14.0 解锁成功，播放提示 “网络不给力，无法继续播放”

### ISSUE THREAD

**Issue by libra1010** [nondanee/UnblockNeteaseMusic#685]
系统: IOS 14.0
服务端运行方式: docker 
客户端方式: wifi pac http://xxx.com:xx/proxy.pac
docker run方式
docker run -d -p 5555:8080 --name 163 nondanee/unblockneteasemusic -p 8080:8081

解锁成功，灰色歌单点亮
播放就是 网络不给力，无法继续播放
目前同样的方式，在MACOS 和 安卓上 均为正常
CA证书已安装并信任

看日志，是有下载文件的
[208902] 红色高跟鞋                                                                                             
http://other.player.ra01.sycdn.kuwo.cn/c6b117a44536a816c23cc77367a4c0e2/5ffc072f/resource/n1/320/98/26/186689057
.mp3                                                                                                            
TUNNEL > localhost:8081                                                                                         
MITM > interface3.music.163.com (ssl)                                                                           
TUNNEL > localhost:8081                                                                                         
TUNNEL > localhost:8081                                                                                         
TUNNEL > localhost:8081                                                                                         
TUNNEL > localhost:8081

**Comment by libra1010** [comment]
目前同样的方式，在MACOS 和 安卓上 均为正常

**Comment by Gnosnay** [comment]
@libra1010 请问这个是因为网络的问题吗？

**Comment by leowang16** [comment]
用爱思助手，下载3.7.5版本，新版本会有问题

**Comment by jinshenganyuci** [comment]
docker run --restart=always --name unmusic -d -p 4567:8080 nondanee/unblockneteasemusic -e "https://music.163.com"


用我这个可以正常用
