### ISSUE TITLE
MITM > null 问题

### ISSUE THREAD

**Issue by YanYunNN** [nondanee/UnblockNeteaseMusic#687]
使用npx部署后
![image](https://user-images.githubusercontent.com/33418852/104683161-5241f380-5731-11eb-869d-2003f4a2f4b1.png)
MITM > null，请问怎么处理

**Comment by MikuMikuMe** [comment]
去网上搜教程按他们的部署

**Comment by daniellauyu** [comment]
@YanYunNN 我跟你的一样，用npx部署后就是一直报这个null。网上的教程没几个能用的。我也用不了

**Comment by daniellauyu** [comment]
https://github.com/nondanee/UnblockNeteaseMusic/issues/597，看这篇，可以解决问题。

**Comment by YanYunNN** [comment]
后面重新部署改端口就好了，不行可以加一下提供的几个参数试试，配好了安卓苹果pad版，电脑都可用，ios手机端能解锁灰色，但一播放
就提示网络错误😂
> @YanYunNN 我跟你的一样，用npx部署后就是一直报这个null。网上的教程没几个能用的。我也用不了
