### ISSUE TITLE
MAC本地部署完成了无法正常使用

### ISSUE THREAD

**Issue by daniellauyu** [nondanee/UnblockNeteaseMusic#690]
![image](https://user-images.githubusercontent.com/17739321/105292776-eb6e7f80-5bf3-11eb-9410-417cf4f35d2e.png)
按照教程做了以下几步：
1.clone项目，然后安装；
2.配置hosts；
3.启动脚本，执行了sudo node app.js -p 80 -f 59.111.181.60；启动成功；
4.打开网易云应用，提示无网络；

网上教程都这么写的，哪位大佬看看我哪一步错了？有没有群啥的可以进去咨询下

**Comment by daniellauyu** [comment]
看到了下面这篇issues，问题已解决！

**Comment by yangezheng** [comment]
哪篇？
