### ISSUE TITLE
IOS端播放提示网络不给力无法播放

### ISSUE THREAD

**Issue by daniellauyu** [nondanee/UnblockNeteaseMusic#691]
服务端采用宝塔面板PM2配置，且启动成功，从日志来看也获取到了音源，但是手机上就是无法播放。
看了很多教程都不知道改如何处理了

**Comment by daniellauyu** [comment]
又搞了一晚上，还是不行，证书都信任了，小火箭配置确认也没问题，无解了

**Comment by SpeedPartner** [comment]
pac或者全局代理先试下,可以的话,再考虑是小火箭规则或者小火箭有bug

**Comment by daniellauyu** [comment]
@SpeedPartner 小火箭某宝买美区下载的，规则就设置了那3个，见下图：
![image](https://user-images.githubusercontent.com/17739321/105434161-fa0d7300-5c95-11eb-9a57-7a9c1e28a157.png)

关键是iPad HD的版本就能正常听，都不用配置规则，wifi代理跟小火箭都可以，手机上证书也装了，但是我看后台日志是正常的。是不是iPhone新版本的问题

**Comment by daniellauyu** [comment]
在我准备再试一遍就放弃的时候搞定了，用的NGINX的转发。打卡
