### ISSUE TITLE
服务端搭建 pm2日志中出现未访问的bc网站

### ISSUE THREAD

**Issue by waleraye** [nondanee/UnblockNeteaseMusic#698]
![image](https://user-images.githubusercontent.com/22760584/105624197-b3478680-5e17-11eb-9e78-07ada4716e61.png)
日志中莫名出现未访问的网站,访问了一下发现是bc网站,有没有大神能不能帮忙看一下是那里的问题

**Comment by useblue** [comment]
启用严格模式  -s enable proxy limitation

**Comment by waleraye** [comment]
> 启用严格模式 -s enable proxy limitation

好的,感谢
