### ISSUE TITLE
mac好像无法运行

### ISSUE THREAD

**Issue by shugo-chara** [nondanee/UnblockNeteaseMusic#7]
node一直提示错误列表。。
请教mac运行方式

**Comment by shugo-chara** [comment]
@nondanee npm install安装失败。。发行里只有win的exe应用，小白macos那个请教要怎么打开。。也没有后缀

**Comment by nondanee** [comment]
下载下来的macos应用，需要加一下执行权限，在控制台下才能运行
```
$ chmod 744 unblockneteasemusic-macos
$ ./unblockneteasemusic-macos
```

**Comment by nondanee** [comment]
修改hosts的步骤你应该是没看完整 [#6](https://github.com/nondanee/UnblockNeteaseMusic/issues/6#issuecomment-406964323)

>通过修改hosts使用必须是80端口 -p 80 ，若在本地运行，请务必指定网易云服务器IP -f 223.252.199.66 (改hosts前自己ping一下)。

我默认你的unblock程序和云音乐客户端在一台机器上运行，步骤如下：
1. ping 得网易云服务器真实IP
```
$ ping music.163.com
PING music.163.com (223.252.199.66): 56 data bytes
64 bytes from 223.252.199.66: icmp_seq=0 ttl=54 time=3.808 ms
64 bytes from 223.252.199.66: icmp_seq=1 ttl=54 time=4.349 ms
```
2. hosts增加两行
```
127.0.0.1 music.163.com
127.0.0.1 interface.music.163.com
```
3. 带参启动程序(运行源码或者打包后的程序都可以)
```
$ sudo node app.js -p 80 -f 223.252.199.66
```
```
$ sudo ./unblockneteasemusic-macos -p 80 -f 223.252.199.66
```
*223.252.199.66 只是我ping得的网易云服务器ip，在你的网络环境下可能不同*

**Comment by nondanee** [comment]
解释下加参数的原因

改hosts让music.163.com指向127.0.0.1
> 将云音乐客户端请求导流到本地unblock服务器，由unblock服务器代理完成请求，分析修改返回结果

设置`-p 80`让unblock服务器运行在80端口
> hosts文件不允许 `127.0.0.1:8080 music.163.com`这样的规则

设置`-f 223.252.199.66`设置网易云服务器的真实地址
> hosts修改后，unblock服务器对music.163.com的请求也会指向127.0.0.1，自己请求自己，导致死循环，故需要向unblock服务器显示指明music.163.com的真实ip

**Comment by nondanee** [comment]
以上的修改hosts的使用方法
通过设置代理就很简单了（默认你跑在本地了）
http,https代理都设成`http://127.0.0.1:80`
或者设置自动代理`http://127.0.0.1:80/proxy.pac`

至于默认8080端口报错，估计是被别的程序占用了，你自己检查一下

**Comment by shugo-chara** [comment]
@nondanee 谢谢你，很直观的教程，一次成功了。之前是错把hosts地址指向网易云真实地址而不是本地了。现在直接用打包好的发行很方便。

还有个问题就是和macos在同一wifi网络情况下的android设备要怎么设置才能用呢。macos上运行着unblock程序，android我试着设置自动代理http://127.0.0.1:80/proxy.pac 没有效果。

**Comment by nondanee** [comment]
用ifconfig看一下电脑的ip
自动代理地址里127.0.0.1改成你电脑在局域网的ip

Btw 安卓上用bug很多😂等有空修

**Comment by nondanee** [comment]
啊？自动代理可以用的啊😂
如果网易云提示网络连接失败，你下拉刷新下应该就好了。因为第一批加密https的请求都被强制中断了，之后会降级到http，服务端才能拦截到返回数据。

已知bug是列表播放听下一曲可能会失败😓
因为安卓端一次会请求两个歌曲url但是只用用一个，两首歌还不是顺序的（有时是前一个有时是后一个），还有超时处理。查找替换两个歌曲资源要多一倍请求，还可能因为超时重试个两三次。。。挺惨的

**Comment by shugo-chara** [comment]
@nondanee 原来如此，不过我在使用指定ip全局过滤后好像倒是没有出现听下一曲失败的情况。
不过难过的是又调试了很久好像在我手机上自动代理依旧无效- -。miui10 android o 本以为可能是系统问题，不过既然手动指定可以用的话说明代理系统运作是正常的。
不过不管怎么样现在总算有办法好好在墙的另一段继续听音乐了，感谢～
不知道会不会开发android端的版本诶，会不会被累死哈哈哈。。

**Comment by nondanee** [comment]
我的锅我的锅，自动代理使用80端口特有的bug，已修复😂
不会写java，android版本不会有的😂（有音量增强器xposed啊）

**Comment by nondanee** [comment]
其实可以部署在VPS上哈，然后手机电脑就设置下pac就好了
（当然也有隐患，可能被别人扫到，用代理做奇奇怪怪的事情，就僵硬了==）

**Comment by shugo-chara** [comment]
😂哈哈重下了新发行后手机端可以用了，棒棒哒。
之前一直有用xposed，因为pokemon go跟安全软件的原因不得不弃用，vxposed里云村又不稳定，所以出门基本都是tiz半残，然而遇到版权还是生无可恋。。
