### ISSUE TITLE
提示"config.port = (config.port || '8080').split(':').map(string => parseInt(string"

### ISSUE THREAD

**Issue by oOAndyOo** [nondanee/UnblockNeteaseMusic#70]
运行node app.js提示“config.port = (config.port || '8080').split(':').map(string => parseInt(string”
![image](https://user-images.githubusercontent.com/50268439/57180080-ad797700-6eb7-11e9-9cb4-a38b1aa53282.png)

**Comment by nondanee** [comment]
node 6 以上，自查版本

**Comment by oOAndyOo** [comment]
node安装的是
![image](https://user-images.githubusercontent.com/50268439/57180271-72784300-6eb9-11e9-89bf-bc66a8b06968.png)

**Comment by nondanee** [comment]
运行 `node -v` 看一下

**Comment by oOAndyOo** [comment]
![image](https://user-images.githubusercontent.com/50268439/57180312-09dd9600-6eba-11e9-9577-d8c56e3e67b1.png)

**Comment by nondanee** [comment]
嘛 0.12.9，自己查一下环境变量吧

**Comment by oOAndyOo** [comment]
我的是Win7，我在win10正常运行
win7：path变量：C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Qualcomm\QDART\\bin;C:\Program Files\Broadcom\Broadcom 802.11 Network Adapter\Driver;;;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\Common Files\Autodesk Shared\;C:\Program Files (x86)\Autodesk\Backburner\;C:\Program Files\Common Files\Autodesk Shared\;E:\adb;%JAVA_HOME%\bin;%JAVA_HOME%\jre\bin;C:\android-sdk\platform-tools;C:\android-sdk\tools;%APPIUM_HOME%;C:\Program Files (x86)\Appium\node_modules\.bin;C:\Program Files\nodejs\

**Comment by nondanee** [comment]
因为 appium？不太清楚那个是什么
总之是你电脑上之前装过 node
新装的没覆盖旧版
之前的 node 版本太低导致报错

node 6 是底线了，再往前不支持 Promise 要被回调烦死

**Comment by oOAndyOo** [comment]
弄好了，我发现把node删掉了，输入node -v还是会显示V0.12.9
后来输入where  node发现在appim里有个node
![image](https://user-images.githubusercontent.com/50268439/57180710-ef0d2080-6ebd-11e9-8a5e-a1d04ece2316.png)
我直接把新的node复制进去替换之后变成新版的了
![image](https://user-images.githubusercontent.com/50268439/57180719-0d731c00-6ebe-11e9-9060-ec4a0c61779c.png)
谢谢啦

**Comment by nondanee** [comment]
客气
