### ISSUE TITLE
Linux求一个详细的教程

### ISSUE THREAD

**Issue by ayuayue** [nondanee/UnblockNeteaseMusic#701]
本机环境：
1. deepin 20 基于 debain
2. 网易云1.2

Windows好几个版本，mac也有签名等教程。
Linux倒没见什么完整的教程，运行都没问题，只是设置应用代理后Linux客户端网络出现问题，但是加证书什么的操作也没有说明，搞得比较懵。
安卓和Windows倒是简单，但Linux用户就不知道怎么搞

**Comment by saltfishh** [comment]
linux用户
运行环境docker,将docker8080映射到宿主机8080,然后nginx转发music.163.com80 443端口到宿主机8080.
尝试过不用证书,貌似无法生效,所以自签证书即可.

**Comment by ayuayue** [comment]
> linux用户
> 运行环境docker,将docker8080映射到宿主机8080,然后nginx转发music.163.com80 443端口到宿主机8080.
> 尝试过不用证书,貌似无法生效,所以自签证书即可.

怎么看自签证书是否成功呢

**Comment by saltfishh** [comment]
> > linux用户
> > 运行环境docker,将docker8080映射到宿主机8080,然后nginx转发music.163.com80 443端口到宿主机8080.
> > 尝试过不用证书,貌似无法生效,所以自签证书即可.
> 
> 怎么看自签证书是否成功呢

这...一般来说不会失败啊,自签完配置好nginx,能打开网易云听个就没问题
