### ISSUE TITLE
收藏歌曲失败

### ISSUE THREAD

**Issue by zzz6839** [nondanee/UnblockNeteaseMusic#706]
在尝试收藏Blackpink的SOLO和How you like that点红心显示收藏失败，log上显示interface.music.163.com走的也是代理，请问该怎么破呢？

**Comment by zzz6839** [comment]
同理，如果要解除歌单里的爱心，也会显示保存失败

**Comment by SpeedPartner** [comment]
网易云帐号要实名认证才能操作歌单了

**Comment by zzz6839** [comment]
哟西，解决了，谢谢

**Comment by lioliy** [comment]
我的也是无法收藏，弹出付费才能使用，听歌和下载没事，收藏免费的也没事
