### ISSUE TITLE
设置参数 node app.js -p 80 -f xxx.xxx.xxx.xx后火狐浏览器扩展件失效了

### ISSUE THREAD

**Issue by nondanee** [nondanee/UnblockNeteaseMusic#71]
设置参数 node app.js -p 80 -f xxx.xxx.xxx.xx后火狐浏览器扩展件失效了
想知道怎么取消上述参数设置

_Originally posted by @Deicide233 in https://github.com/nondanee/UnblockNeteaseMusic/issues/30#issuecomment-489332142_

**Comment by nondanee** [comment]
@deicide233
哪个火狐扩展？

**Comment by Deicide233** [comment]
> 
> 
> @Deicide233
> 哪个火狐扩展？

所有的，都突然提示《这些扩展不符合现今的Firefox标准，因此已被停用》，由于官方的默认扩展都被停用所以我认为和扩展本身没关系。

**Comment by nondanee** [comment]
@Deicide233 
应该是太久没开 firefox 了吧？你刚更新 quantum？
代理没有此神力把浏览器扩展停用……

**Comment by Deicide233** [comment]
emmmm，我天天在用它，一输入参数，就开始了......
我细节也不是太懂，就指望大佬了

**Comment by nondanee** [comment]
@Deicide233 
看一下这个 
https://www.ithome.com/0/422/060.htm

**Comment by TkzcM** [comment]
这个是Firefox自己的问题，证书过期了

**Comment by Deicide233** [comment]
> 
> 
> @Deicide233
> 看一下这个
> https://www.ithome.com/0/422/060.htm

感激不尽啊......
