### ISSUE TITLE
小白，我在windows服务器上运行好了这个项目。然后在我的电脑上填写ip和端口号，连接不上这个代理。请问是有少了什么步骤吗？

### ISSUE THREAD

**Issue by lmf1468** [nondanee/UnblockNeteaseMusic#733]
![Snipaste_2021-04-18_15-04-14](https://user-images.githubusercontent.com/59329800/115137268-c73a0780-a057-11eb-80fe-3164d2170c4e.png)
![Snipaste_2021-04-18_15-08-19](https://user-images.githubusercontent.com/59329800/115137286-ecc71100-a057-11eb-80ff-4b51e31ad019.png)

**Comment by ininkoho** [comment]
本地用的话服务器填：localhost或者127.0.0.1就好了
