### ISSUE TITLE
最新版,解析错误,EVP_DecryptFinal_ex:wrong final block length

### ISSUE THREAD

**Issue by ibibii** [nondanee/UnblockNeteaseMusic#735]
Debian 10,hosts 模式,Github 下载最新源码
网页和客户端 1.2以上,有openssl证书,能播放免会员和非版权的
版权的可以点击,不能播放
测试周杰伦的歌
地址:https://music.163.com/#/album?id=18893

Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
    at Decipheriv.final (node:internal/crypto/cipher:196:29)
    at decrypt (/opts/github/UnblockNeteaseMusic-master/src/crypto.js:12:58)
    at Object.decrypt (/opts/github/UnblockNeteaseMusic-master/src/crypto.js:23:22)
    at /opts/github/UnblockNeteaseMusic-master/src/hook.js:154:53
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  library: 'digital envelope routines',
  function: 'EVP_DecryptFinal_ex',
  reason: 'wrong final block length',
  code: 'ERR_OSSL_EVP_WRONG_FINAL_BLOCK_LENGTH'
} https://music.163.com/weapi/song/enhance/player/url/v1?csrf_token=2667b41e1ce9b2192ba62683986c7eb7

像是加密解密错误,node 版本 16.0.0,最新版

**Comment by ibibii** [comment]
又用node 14 ,  也是一样问题,是不是网易改了api

**Comment by zengxiaoliang** [comment]
是的，现在无法使用其他源播放了！  不知道你解决了吗？

**Comment by zengxiaoliang** [comment]
curl -L https://github.com/nondanee/UnblockNeteaseMusic/pull/745.patch | git am
curl -L https://github.com/nondanee/UnblockNeteaseMusic/pull/618.patch | git am


详见  https://github.com/nondanee/UnblockNeteaseMusic/issues/746

**Comment by ibibii** [comment]
> curl -L https://github.com/nondanee/UnblockNeteaseMusic/pull/745.patch | git am
> curl -L https://github.com/nondanee/UnblockNeteaseMusic/pull/618.patch | git am
> 
> 详见 #746

谢谢,等哪天想听歌再弄
