### ISSUE TITLE
"我会永远爱坐在我对面的男生"这首歌的歌曲是错误的

### ISSUE THREAD

**Issue by Anopia** [nondanee/UnblockNeteaseMusic#74]
是什么原因呢
![image](https://user-images.githubusercontent.com/20596060/57189638-7650a780-6f43-11e9-811e-8eb3bfea3e31.png)

**Comment by nondanee** [comment]
嗯我自己遇到过，这首就是
![image](https://user-images.githubusercontent.com/26399680/57190490-44dcd980-6f4d-11e9-8d48-dfcd740ffbc3.png)
网易自己 dfsId 的问题，没办法；而且 dfsId 官方已经废弃了，跟官方说也没用

**Comment by nondanee** [comment]
@Anopia 
查了下发现是我的原因，是 js 大整数精度的问题，已经 fix 了，不好意思啦

**Comment by Anopia** [comment]
> @Anopia
> 查了下发现是我的原因，是 js 大整数精度的问题，已经 fix 了，不好意思啦

哇真的好了，我都没想到会是js的问题。谢谢啦。
