### ISSUE TITLE
代理可用，一直显示加载失败

### ISSUE THREAD

**Issue by deardeer7** [nondanee/UnblockNeteaseMusic#749]
### 网易云版本2.8.0 项目代码也最新的
好久没有用网易云了，然后今天上来给网易云更新了下：

![当前版本](https://user-images.githubusercontent.com/42965045/116801584-e2b80e80-ab3d-11eb-9e84-f3ee5cc777b2.png)

然后听歌发现有些歌曲就一直“跳”（**加载失败**），就试试了周总的歌，发现就是**代理可用**，但是那些**歌曲资源实际还是听不了**，拉取了最新的仓库代码还是不行，请问是网易云版本更新了还是什么，有什么解决办法吗？

![代理可用](https://user-images.githubusercontent.com/42965045/116801676-8bff0480-ab3e-11eb-84b4-c59a97c3abb8.png)

![加载失败](https://user-images.githubusercontent.com/42965045/116801560-b3090680-ab3d-11eb-9e5e-e72075287036.png)

**Comment by deardeer7** [comment]
补充一点，其他网易有版权的歌还是可以听的，然后不知道是什么原因，刚才使用过程中客户端还闪退了几次，使用的是windows客户端

**Comment by Colin-XKL** [comment]
同问。
补充信息：自己合并了fix provider kuwo和qq的几个pr，然后手动构建的docker镜像部署的。后台日志可以看到已经请求了资源，而且请求到的资源URL在浏览器中打开也是正常的音频文件，但是客户端进度条就是不走，一直卡在第0秒

**Comment by Colin-XKL** [comment]
我找到了一个可能的原因：严格模式 参数-s    
经过我的多次测试，加了-s参数后所有解锁的歌曲都不能播放，进度条卡在第0秒，但是程序后台是有记录的。  
初步判断是网易云客户端请求的域名列表有新增的项目，但是这个新增的项目并不在严格模式的域名白名单里。

**Comment by deardeer7** [comment]
> 我找到了一个可能的原因：严格模式 参数-s
> 经过我的多次测试，加了-s参数后所有解锁的歌曲都不能播放，进度条卡在第0秒，但是程序后台是有记录的。
> 初步判断是网易云客户端请求的域名列表有新增的项目，但是这个新增的项目并不在严格模式的域名白名单里。

有这个可能哈，我的就是严格模式，有参数-s，我还没尝试非严格模式是否正常，你有没有试试呢 @Colin-XKL

**Comment by Colin-XKL** [comment]
> > 我找到了一个可能的原因：严格模式 参数-s
> > 经过我的多次测试，加了-s参数后所有解锁的歌曲都不能播放，进度条卡在第0秒，但是程序后台是有记录的。
> > 初步判断是网易云客户端请求的域名列表有新增的项目，但是这个新增的项目并不在严格模式的域名白名单里。
> 
> 有这个可能哈，我的就是严格模式，有参数-s，我还没尝试非严格模式是否正常，你有没有试试呢 @Colin-XKL

我根据 #746 给打了个补丁修复了音源，然后程序后台日志显示是可以搜到歌曲的，但是客户端在严格模式下播放不了。严格模式关了就可以播放了

**Comment by deardeer7** [comment]
> > > 我找到了一个可能的原因：严格模式 参数-s
> > > 经过我的多次测试，加了-s参数后所有解锁的歌曲都不能播放，进度条卡在第0秒，但是程序后台是有记录的。
> > > 初步判断是网易云客户端请求的域名列表有新增的项目，但是这个新增的项目并不在严格模式的域名白名单里。
> > 
> > 
> > 有这个可能哈，我的就是严格模式，有参数-s，我还没尝试非严格模式是否正常，你有没有试试呢 @Colin-XKL
> 
> 我根据 #746 给打了个补丁修复了音源，然后程序后台日志显示是可以搜到歌曲的，但是客户端在严格模式下播放不了。严格模式关了就可以播放了

今天按你说的弄了下，目前好像正常了，感谢！
