### ISSUE TITLE
《等你下课》没法播放

### ISSUE THREAD

**Issue by nondanee** [nondanee/UnblockNeteaseMusic#75]
> @iDesperad0
> 最新的 release (包括 docker) 上的挂了，已经好几天了(星期二到现在)
> 最新的 commit，M500 是没问题的
> 以后不会再管 QQ 高音质了，换一个封一个......

你好，我今天刚在google cloud 台湾节点上部署。 周杰伦的《周杰伦的床边故事》可以播放，但是《等你下课》没法播放（可以看评论）。 我现在不清楚是api海外墙的问题，还是其他什么问题。我非常想知道哪里出了问题，后续是否可以解决。

_Originally posted by @onewayticket255 in https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-489398616_

**Comment by nondanee** [comment]
@onewayticket255
和 issue 不相关的问题麻烦新开 issue

**Comment by nondanee** [comment]
https://github.com/nondanee/UnblockNeteaseMusic/issues/61#issuecomment-487997803
被下架的歌在 2018 年之前发行，可以直接匹配到网易云自己的源
2018 年之后，匹配其它平台
检查一下现在的 version
```
node app.js -v
```

**Comment by nondanee** [comment]
@onewayticket255
https://github.com/nondanee/UnblockNeteaseMusic/issues/61#issuecomment-487997803
被下架的歌在 2018 年之前发行，可以直接匹配到网易云自己的源
2018 年之后，匹配其它平台
检查一下现在的 version
```
node app.js -v
```

**Comment by onewayticket255** [comment]
root@vps:/UnblockNeteaseMusic# node app.js -v
0.13.1

无法播放的都是qq的源。网易自己源都可以。

TUNNEL - music.163.com:443
MITM > interface.music.163.com
MITM > interface.music.163.com
MITM > music.163.com
MITM > interface.music.163.com
[561307346] 不爱我就拉倒
http://streamoc.music.tc.qq.com/M5000031TAKo0095np.mp3?vkey=6505C5C69FD42A79C6A58EF80119299EEC55ED96B5977AC6C4879FF38B9A9E8E794216FC63BBA508D34C448AEA2E96AB7870CF05CE30542B&uin=0&fromtag=8&guid=7332953645
MITM > streamoc.music.tc.qq.com
TUNNEL - music.163.com:443
TUNNEL - music.163.com:443
TUNNEL - music.163.com:443
TUNNEL - music.163.com:443
TUNNEL - music.163.com:443
TUNNEL - music.163.com:443
TUNNEL - music.163.com:443
TUNNEL - music.163.com:443
TUNNEL - music.163.com:443
TUNNEL - music.163.com:443
MITM > music.163.com

**Comment by nondanee** [comment]
@onewayticket255 
你点这个链接进去可以打开吗？

**Comment by onewayticket255** [comment]
直接IOS手机浏览器上可以播放，但是在IOS 最新版本网易云上只能播放网易自己的源.

播放自己源的情况
![Snipaste_2019-05-05_16-16-15.png](https://i.loli.net/2019/05/05/5cce9c4c7836f.png)

播放qq源的情况
![Snipaste_2019-05-05_16-08-39.png](https://i.loli.net/2019/05/05/5cce9c872b070.png)

**Comment by nondanee** [comment]
@onewayticket255 
看一下状态码是不是 403

**Comment by onewayticket255** [comment]
HTTP/1.1 200 OK
server: httpserver
content-length: 3934873
accept-ranges: bytes
server-check: 8c997a0bb99e465223a2e4edd3a94b28
connection: Keep-Alive
keep-alive: timeout=60, max=100
last-modified: Thu, 06 Sep 2018 09:49:05 GMT
content-type: audio/mpeg
cache-control: max-age=7200
client-ip: 34.80.137.51
x-serverip: 110.52.197.18
x-resptime: 05/May/2019:16:26:02 +0800
Date: Sun, 05 May 2019 08:26:02 GMT

ID3......ETIT2..........N1r.b1\.b.PTALB..........N1r.b1\.b.PTPE1.........hTpg&O...d................................Info......$..<...............!$')+.0358;=@CEHJMPRUWY\^adfiknqsvx{~.....................................................9LAME3.99r.......?....$..N....<...U.E....................................................................................................................................................................................................................................d...%b:...B+....".......`.63.. ...@.pD".........v<..q.c..........^!n....F._...."t...B.'^.. .D/.....DO...

**Comment by onewayticket255** [comment]
刚才是200 现在又变成206 了

HTTP/1.1 206 Partial Content
server: httpserver
content-range: bytes 0-511999/3934873
content-length: 512000
accept-ranges: bytes
server-check: 8c997a0bb99e465223a2e4edd3a94b28
connection: Keep-Alive
keep-alive: timeout=60, max=100
last-modified: Mon, 10 Sep 2018 10:52:32 GMT
content-type: audio/mpeg
cache-control: max-age=7200
client-ip: 34.80.137.51
x-serverip: 122.190.14.148
x-resptime: 05/May/2019:16:37:08 +0800
Date: Sun, 05 May 2019 08:37:08 GMT

**Comment by nondanee** [comment]
@onewayticket255 
既然是 200/206 为什么前面有个红色的叉呀
不告诉你是什么错吗

**Comment by nondanee** [comment]
@onewayticket255 
哦我看到了 client closed
那就不知道了，在局域网开 server 看看吧，同一网络环境下

**Comment by onewayticket255** [comment]
在Google cloud 台湾和日本节点上测试，qq的源无法下载。目前不清楚Google Cloud 哪里出了问题
![Snipaste_2019-05-05_19-34-11.png](https://i.loli.net/2019/05/05/5cceca449339b.png)

**Comment by nondanee** [comment]
把 host 换成别的看看
不只 streamoc 这一个
位置在 provider/qq.js 
很好找

**Comment by onewayticket255** [comment]
curl -o testaaa.mp3 http://streamoc.music.tc.qq.com/M5000031TAKo0095np.mp3?vkey=6505C5C69FD42A79C6A58EF80119299EEC55ED96B5977AC6C4879FF38B9A9E8E794216FC63BBA508D34C448AEA2E96AB7870CF05CE30542B&uin=0&fromtag=8&guid=7332953645

curl -o testaaa.mp3 http://isure.stream.qqmusic.qq.com/M5000031TAKo0095np.mp3?vkey=5FC87544B0C436F4A1DFC5E9DE6B5E4AC750C836E013F050B3AFBD6C82F585BAF55B97ECB118771D616D27A6056B73F7EA6E784E9DDDA178&uin=0&fromtag=8&guid=7332953645

curl -o testaaa.mp3 http://183.131.60.16/amobile.music.tc.qq.com/M500001J5QJL1pRQYB.mp3?vkey=058E98C4C1DD3A1C02B59291CBE0A267408C90853C6E13174EF5C5A0445E841D5BE896A38422609B30E092EFFBA859FF31CBE097C3E7B605&uin=0&fromtag=8&guid=7332953645

在Google cloud上都无法下载，在我Mac下都可以下载。。。我Google cloud改DNS 114.114.114.114还是不行，弄不明白Google cloud 哪里出了问题。

**Comment by nondanee** [comment]
GCP 哪个区啊？nslookup 可以查到 ip 吗？查不到就没办法了……

**Comment by onewayticket255** [comment]
更正一下，GCP是可以用curl下载streamoc.music.tc.qq.com的，不过速度太慢，一首歌要下1分钟左右。

我在腾讯云 上海测试了一下，无论是网易自己源还是qq源都无法播放，并且在GCP上 床边故事这首歌是用网易自己源，而在腾讯云上所有歌都用的是qq的源

现在情况是GCP台湾 只能听网易源，腾讯云所有无版权都用qq源且无法播放

`[415792916] 床边故事
http://streamoc.music.tc.qq.com/M500002MVjb31ZNK5m.mp3?vkey=AB5B33341DA7FEBE71F51D690DA494CAC40490578CF9A00ABD30887BECE1DA68D3401210ED4FCC13F604240ACA177A2A7CECDD272AA5FF32&uin=0&fromtag=8&guid=7332953645
MITM > interface.music.163.com
MITM > interface.music.163.com
MITM > streamoc.music.tc.qq.com
MITM > interface.music.163.com
TUNNEL - music.163.com:443
TUNNEL - music.163.com:443
TUNNEL - music.163.com:443
TUNNEL - music.163.com:443`
腾讯云

**Comment by nondanee** [comment]
@onewayticket255 
匹配完会用 HEAD 请求检查一次可达性
讲道理匹配到的应该是都可以访问的

你用 macOS 客户端测试吧
iOS 上或许会有别的问题

网络问题不是我能解决的
现在 endpoint 是可以自定义的，上游 proxy 也是可以自定义的，所以你自己想办法啦==
