### ISSUE TITLE
部分音源会完全变成另外一首歌了

### ISSUE THREAD

**Issue by MengYongKange** [nondanee/UnblockNeteaseMusic#76]
比如a歌曲，播放的时候会变成另外一首不相干的歌曲╮(╯▽╰)╭

**Comment by nondanee** [comment]
Duplicate #18 #74

**Comment by David318** [comment]
> Duplicate #10 #18 #74

我也找到几首音乐不匹配的情况，歌曲是对的，但是版本是错的，大概就是Live版本变成了录音版的情况

不知道应该怎么描述，复制一些具体情况

[1370871492] 丽园便利店 (Live)
http://isure.stream.qqmusic.qq.com/M500001Qh8c20EHWdt.mp3?vkey=C2BD15370F92C3BF0592ED49C9A4F2265D5A88708C50724F0EE445D26C048DF2A88CFE7ECEEC8DCCA26FF7E4D0E36631F594437A002E2399&uin=0&fromtag=8&guid=7332953645

[1370871494] 你怎么不上天呢 (Live)
http://isure.stream.qqmusic.qq.com/M500000xioWN1vEssI.mp3?vkey=C2BD15370F92C3BF0592ED49C9A4F2265D5A88708C50724F0EE445D26C048DF2A88CFE7ECEEC8DCCA26FF7E4D0E36631F594437A002E2399&uin=0&fromtag=8&guid=7332953645

[1370871541] 再见杰克 (Live)
http://isure.stream.qqmusic.qq.com/M500001v129s1AnU1f.mp3?vkey=C2BD15370F92C3BF0592ED49C9A4F2265D5A88708C50724F0EE445D26C048DF2A88CFE7ECEEC8DCCA26FF7E4D0E36631F594437A002E2399&uin=0&fromtag=8&guid=7332953645

[1370869626] 嘿！姑娘 (Live)
http://isure.stream.qqmusic.qq.com/M500003ahtAS1Ox1l6.mp3?vkey=C2BD15370F92C3BF0592ED49C9A4F2265D5A88708C50724F0EE445D26C048DF2A88CFE7ECEEC8DCCA26FF7E4D0E36631F594437A002E2399&uin=0&fromtag=8&guid=7332953645

[1370869631] 梦 (Live)
http://isure.stream.qqmusic.qq.com/M500001oxnf71gn6WR.mp3?vkey=C2BD15370F92C3BF0592ED49C9A4F2265D5A88708C50724F0EE445D26C048DF2A88CFE7ECEEC8DCCA26FF7E4D0E36631F594437A002E2399&uin=0&fromtag=8&guid=7332953645

以上，包含且不仅限于这几首

最后，这个东西今天刚发现的，配置好开始运行以后，感觉实在是太Diao了

**Comment by nondanee** [comment]
@David318 
试了下确实是这样
原来用的搜索关键词是 '歌名 - 歌手'
改成 '歌手 - 歌名' 好像就可以了，你试一下

**Comment by David318** [comment]
好，但是我不知道，能教我不  @nondanee

**Comment by David318** [comment]
@nondanee 
好的，但是我不知道怎么改，能不能教我一下

**Comment by nondanee** [comment]
@David318 
已经 commit 了
你 pull master 就行了

**Comment by David318** [comment]
@nondanee 
感恩&牛B

**Comment by David318** [comment]
> @David318
> 已经 commit 了
> 你 pull master 就行了

绝大部分都解决了，超牛逼。只有几个别的，歌曲名也相同，歌手名也相同，但又不是同一个版本，感觉就比较麻烦了，难道还要去匹配专辑名吗，太让人头疼了

比如，以下

[1370871494] 你怎么不上天呢 (Live)
http://isure.stream.qqmusic.qq.com/M5000009fQax1MAFui.mp3?vkey=6E856FB1B78765BFD98D0790EF6FA2C05D5337DC9F66396437D1C9213ACFA3D5E6F038B1A9F84E670E3B028E89530E3748EA93835386DCFA&uin=0&fromtag=8&guid=7332953645

[1370869636] 春风十里 (Live)
http://isure.stream.qqmusic.qq.com/M5000049yqra1VuWjO.mp3?vkey=AE02E38231C4078C37CF09A8A25F4B33689C22049926B742973A8DC5A9A9D8B73C9EEF22CC5F821194966A1747F58AC4831364B5539D0DEB&uin=0&fromtag=8&guid=7332953645

这种简直太顽固了

**Comment by nondanee** [comment]
@David318 
我查了下你说的这两首匹配的 songmid 都是对的，应该是缓存的问题，清下客户端缓存看看？

春风十里 (Live) M5000049yqra1VuWjO.mp3
你怎么不上天呢 (Live) M5000009fQax1MAFui.mp3

你在浏览器里打开链接听一下哈

**Comment by David318** [comment]
@nondanee 
那会不会是这个歌曲的ID错了，我听得是【乐队的夏天 第2期】这个专辑，但是这两首都不是专辑里的

**Comment by nondanee** [comment]
@David318 
嗯嗯，没错的

春风十里 (Live) 匹配的是
QQ 的这个: 乐人·Live：鹿先森乐队“春风千里”巡演深圳站(Live)  - 春风十里 (Live)
https://y.qq.com/n/yqq/song/0049yqra1VuWjO.html

你怎么不上天呢 (Live) 匹配的是
QQ 的这个: 中国乐队 第6期 - 你怎么不上天呢 (Live)
https://y.qq.com/n/yqq/song/0009fQax1MAFui.html

匹配这个看各个平台的搜索排序算法，我只是取搜索结果第一首，#18
如果要好好计算匹配度可能需要 NLP 了 😂

**Comment by David318** [comment]
@nondanee 
这可太烧脑了，不管咋说，就已经让我的软件牛B了一大截子了，辛苦🤘

**Comment by nondanee** [comment]
@David318 
我发现 '歌手 - 歌名' 这样有的歌匹配不到，所以还是要改回去
而且我发现好像 QQ 音乐也做了修正

你怎么不上天呢 (Live) - Mr. Miss
https://y.qq.com/portal/search.html#page=1&searchid=1&remoteplace=txt.yqq.top&t=song&w=你怎么不上天呢%20(Live)%20-%20Mr.%20Miss

Mr. Miss - 你怎么不上天呢 (Live)
https://y.qq.com/portal/search.html#page=1&searchid=1&remoteplace=txt.yqq.top&t=song&w=Mr.%20Miss%20-%20你怎么不上天呢%20(Live)

搜索结果第一首都是正确的

**Comment by David318** [comment]
又发现一首音源匹配错误的情况

[1372295928] 天下 (Live)
http://isure.stream.qqmusic.qq.com/M500004filBr163Ztc.mp3?vkey=CA9E54039DDA4315B588BD39EA9674897550017939DD7EA64E655F70DEC0F9AF07B6EC8D84DB2F2868AB25C470801672B998824C29B7D298&uin=0&fromtag=8&guid=7332953645

这个是演唱者和歌曲名都匹配错误了，QQ音乐里是” 天下(Live) - 南无乐队“ ，网易云里是”天下(Live) - 乐队的夏天“，匹配成了”西湖(Live) - 痛仰乐队“。

我觉得也是网易云把演唱者名字乱写所以匹配不到
