### ISSUE TITLE
1M带宽服务器听不了歌吗？

### ISSUE THREAD

**Issue by layris3** [nondanee/UnblockNeteaseMusic#766]
### 配置：
服务器带宽（腾讯云）：1M
系统：ubuntu 18

### 步骤：
安装node.js 和 npm （node版本14）

执行命令
···bash
npx @nondanee/unblockneteasemusic -s 
···
此时可以看到服务器监听8080端口
pc网易云客户端设置代理为服务器地址，端口8080，然后重启网易云客户端

重启后，可以看到服务端接收到请求，也可以解析到音频地址。
但是客户端播放器进度条一直在loading，等待十几秒后”加载失败“。

### 提问
请问是我少了什么步骤吗？
还是因为1M带宽太少的原因？

**Comment by layris3** [comment]
![image](https://user-images.githubusercontent.com/59719285/124050579-6793ab80-da4d-11eb-8bd0-a406e3d0ef03.png)
今天连歌手都搜索不出来就有点离谱了，感觉不太像是带宽的问题。

**Comment by SamL1n** [comment]
服务端是可以收到请求的。
![image](https://user-images.githubusercontent.com/59719285/124050697-a0cc1b80-da4d-11eb-83f9-ef2904cb2f48.png)

**Comment by layris3** [comment]
服务端可以收到请求。
![image](https://user-images.githubusercontent.com/59719285/124050768-ca854280-da4d-11eb-8ed6-969938fee8ee.png)

**Comment by pan93412** [comment]
可能是沒有安裝並信任 ca.crt 等憑證？

**Comment by layris3** [comment]
> 可能是沒有安裝並信任 ca.crt 等憑證？

谢谢回复~
现在已经可以windows端已经可以正常听歌了，操作步骤没变。挺神奇的

**Comment by layris3** [comment]
结论：1M带宽是可以听歌的·
