### ISSUE TITLE
https endpoint转发 + PM2 ios端无法播放

### ISSUE THREAD

**Issue by layris3** [nondanee/UnblockNeteaseMusic#768]
`node app.js -e https://我的域名`
IOS端可以听歌。

但是`pm2 start app.js -e https://我的域名`
IOS端就听不了了，提示网络不给力。

哭了，有人跟我一样的情况吗？

**Comment by layris3** [comment]
`pm2 start app.js --name UnblockNeteaseMusic --  -e https://<我的域名>`
就可以了。
懵了，有人知道是什么原因吗

**Comment by syymo** [comment]
你的还能用吗？为这里用不了了

**Comment by layris3** [comment]
> 你的还能用吗？为这里用不了了

可以使用~
你提供一下详细的操作步骤及一些相关信息，方便找到问题
