### ISSUE TITLE
docker-compose安装出错

### ISSUE THREAD

**Issue by starshards** [nondanee/UnblockNeteaseMusic#77]
错误信息 Error: getaddrinfo EAI_AGAIN music.163.com
有更改过hosts

**Comment by nondanee** [comment]
知识盲区了
我查了查好像是 dns 的问题
不太清楚
😂

**Comment by Bluefissure** [comment]
似乎是DNS查找超时了，建议通过ping和更换DNS（或hosts）的方式排查一下。
网上搜索了下可能也是npm版本的问题，可以升级下docker里的npm：`sudo npm install npm -g`  或 `npm install -g npm`
