### ISSUE TITLE
8月23日 iOS更新后失效

### ISSUE THREAD

**Issue by Grergo** [nondanee/UnblockNeteaseMusic#773]
服务端可以看到解析的酷我的歌曲连接，APP中也可以看到时长，但是提示网络不给力，无法继续播放.

**Comment by sipgov** [comment]
IOS端如果提示“网络不给力无法播放”，请在服务器端启动时加上-f 参数即可正常播放。
食用方法：
1、先找到music.163.com这个域名的ip地址（直接ping music.163.com，记下那个返回的IP地址，如国内目前是59.111.160.195、59.111.19.33，海外目前是103.126.92.132、103.126.92.133），
2、启动时添加参数 -f +以上的某个 IP地址，例如：-f  59.111.19.33
3、好了，可以正常播放了

附上自己能用的docker 命令：
docker run -d -p 77:8080 --name unblock163  --restart=always  nondanee/unblockneteasemusic:latest    -e "https://music.163.com"   -f  59.111.19.33

**Comment by Grergo** [comment]
谢谢您的解决方法！

**Comment by wxchil** [comment]
非常感谢大佬的解答
