### ISSUE TITLE
ipad hd可用 iphone播放失败 

### ISSUE THREAD

**Issue by hsy66** [nondanee/UnblockNeteaseMusic#78]
提示网络不给力 播放失败 
已经添加了规则 是否因为签名问题？如何解决
切换hd版本测试可用 但是iphone版本不行（灰色歌曲成功变色但不能播放）

使用的是shadowrocket

**Comment by nondanee** [comment]
那就是 README 里写的转发的问题了 #65 
去 #56 或者 #65 讨论吧，谢谢
我没有 iOS 设备
作者什么忙都帮不上

**Comment by daniellauyu** [comment]
@hsy66 同层主的问题，iPad HD完全没问题，iPhone总是提示”网络问题“，想问下是怎么解决的这个问题啊
