### ISSUE TITLE
Error: connect ECONNREFUSED 59.111.179.214:80

### ISSUE THREAD

**Issue by Yuanda-Dong** [nondanee/UnblockNeteaseMusic#780]
Error: connect ECONNREFUSED 59.111.179.214:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '59.111.179.214',
  port: 80
}
今天遇到这个问题，之前还能用的，不知道怎么修。
系统 manjaro, 修改了host并且自发证书，然后跑了这个指令
`node app.js -p 443 -f 103.126.92.132
`

**Comment by ZhaofengWu** [comment]
请问你解决了吗？

**Comment by Yuanda-Dong** [comment]
> 请问你解决了吗？



> 请问你解决了吗？

**Comment by Yuanda-Dong** [comment]
> 请问你解决了吗？

我这边它自己解决了
