### ISSUE TITLE
mac使用pac代理有效，但是许多歌曲依旧是灰的（比如纠结伦）

### ISSUE THREAD

**Issue by KiraYo4kage** [nondanee/UnblockNeteaseMusic#79]
mac使用pac代理有效，但是许多歌曲依旧是灰的（比如纠结伦）

**Comment by Anopia** [comment]
可能是音源有问题。尝试一下转发音源呢。。

**Comment by KiraYo4kage** [comment]
> 可能是音源有问题。尝试一下转发音源呢。。

sorry，页面没有刷新，我重进一下就有啦。
另外还有个问题，node有什么方法可以设置系统pac地址吗，我想写个一键启动脚本。

**Comment by nondanee** [comment]
@KiraYo4kage 
直接在 shell 里 networksetup 就行了
https://stackoverflow.com/questions/4029471/how-to-you-toggle-on-and-off-a-web-proxy-in-os-x-from-the-command-line

之前有想过做一个启动时修改系统代理，关闭时还原系统代理的功能
但是 windows 上关窗口的行为没法触发 exit 事件，就不做了==

**Comment by 78775546946** [comment]
我是安卓手机，Android9.0，使用pac也没法点亮，但是proxy.pac这个文件可以下载到。相同的地址和端口，改成手动就可以，不过这个时候例如浏览器就会使用HTTP代理。

**Comment by nondanee** [comment]
@78775546946 
第一你是不是 6.2？先更新下，6.2 改了 hostname
手动能用 pac 不能用说明有请求漏掉了，在手动模式下看 log 然后发 issue 或者 PR

如果是服务器和手机不再同一环境，可能 httpdns 结果会不一样导致服务器不知道手机那边的直连 IP，然后有直连 IP 的请求被漏掉，或许把 httpdns 加到 pac 里面就好了，你可以自己加

我从没有说过要求部署到公网，鼓励在本地运行，我也想把 server 直接运行在手机上，nodejs mobile 早就有了，所以这个问题我不会优先处理的。
