### ISSUE TITLE
pkg打出的包执行报错，版本为macos

### ISSUE THREAD

**Issue by KiraYo4kage** [nondanee/UnblockNeteaseMusic#80]
原因是server.js中使用了fs.readFileSync读取证书文件，而打包时没有将这两个文件指定为assets。
在package.json中增加一下代码就好了。
`pkg": {
    "assets": [
      "server.key",
      "server.crt"
    ]
  },`
此外，fs.readFileSync中的路径最好使用__dirname作为根目录

**Comment by nondanee** [comment]
好的
