### ISSUE TITLE
《致姗姗来迟的你》播放时是另外一首歌

### ISSUE THREAD

**Issue by attenton** [nondanee/UnblockNeteaseMusic#81]

**Comment by nondanee** [comment]
阿肆的？歌曲 ID 是多少
请贴上 log 截图说明匹配到了哪个地址

我试了下没问题
今天凌晨 3 点有次 [release](https://github.com/nondanee/UnblockNeteaseMusic/releases/tag/v0.13.2)，修了一个匹配的 bug，请检查版本

遇到问题先去搜搜 issue #74 #76 
Duplicate

**Comment by attenton** [comment]
[432506809] 致姗姗来迟的你
http://p1.music.126.net/8vj0Gicm_uMNu6JrztqVEA==/18669707440351870

**Comment by nondanee** [comment]
是这个问题，已经 fix，请 pull 新版本

**Comment by attenton** [comment]
👌

**Comment by attenton** [comment]
之前重拉代码《致姗姗来迟的你》匹配正确，这次重拉代码，《致姗姗来迟的你》又匹配错误了

**Comment by attenton** [comment]
之前重拉代码《致姗姗来迟的你》匹配正确，这次重拉代码，《致姗姗来迟的你》又匹配错误了 @nondanee

**Comment by nondanee** [comment]
@attenton 
我没有问题，匹配到的地址贴一下，应该就是这个
http://p1.music.126.net/itvWex5x8yZtFjF97u09Vw==/18669707440351874

**Comment by attenton** [comment]
好像是因为之前缓存了错误的歌曲，清了缓存就好了，多谢
