### ISSUE TITLE
macos proxy

### ISSUE THREAD

**Issue by Sube-py** [nondanee/UnblockNeteaseMusic#817]
mac上用不了啦，采用的node启动然后设置hosts，打开网易云显示网络错误，配置了ca，求解

**Comment by Sube-py** [comment]
> mac上用不了啦，采用的node启动然后设置hosts，打开网易云显示网络错误，配置了ca，求解

更新下ca就好了😄

**Comment by QSupervillain** [comment]
mac 现在还能使用吗?我都好久没用了

**Comment by Sube-py** [comment]
> mac 现在还能使用吗?我都好久没用了

@QSupervillain 可以 有点麻烦 后面我出个教程

**Comment by winfordguo** [comment]
@Sube-py 大佬，mac现在还能用吗？

**Comment by Sube-py** [comment]
> @Sube-py 大佬，mac现在还能用吗？

可以的 更新ca
