### ISSUE TITLE
iOS 测试交流 汇总

### ISSUE THREAD

**Issue by onewayticket255** [nondanee/UnblockNeteaseMusic#82]
# iOS
[参考iOS 食用指南](https://github.com/nondanee/UnblockNeteaseMusic/issues/65)
# Mac
## 使用 2.0(730) 版本[直连http]

[http://d1.music.126.net/dmusic/NeteaseMusic_2.0.0_730_web.dmg](http://d1.music.126.net/dmusic/NeteaseMusic_2.0.0_730_web.dmg)

### Surge 配置
```
[Proxy]
NeteaseMusicUnlock = http, your_domain, unlockmusicserverport

[Rule]
//NeteaseMusic
DOMAIN-KEYWORD,wanproxy,REJECT
DOMAIN,web.push.126.net,REJECT
URL-REGEX,http://music.163.com/eapi/v3/playlist/detail,NeteaseMusicUnlock
URL-REGEX,http://music.163.com/eapi/v3/song/detail,NeteaseMusicUnlock
URL-REGEX,http://music.163.com/eapi/v6/playlist/detail,NeteaseMusicUnlock
URL-REGEX,http://music.163.com/eapi/album/play,NeteaseMusicUnlock
URL-REGEX,http://music.163.com/eapi/artist/privilege,NeteaseMusicUnlock
URL-REGEX,http://music.163.com/eapi/album/privilege,NeteaseMusicUnlock
URL-REGEX,http://music.163.com/eapi/v1/artist,NeteaseMusicUnlock
URL-REGEX,http://music.163.com/eapi/v1/artist/songs,NeteaseMusicUnlock
URL-REGEX,http://music.163.com/eapi/v1/album,NeteaseMusicUnlock
URL-REGEX,http://music.163.com/eapi/playlist/privilege,NeteaseMusicUnlock
URL-REGEX,http://music.163.com/eapi/song/enhance/player/url,NeteaseMusicUnlock
URL-REGEX,http://music.163.com/eapi/song/enhance/player/url/v1,NeteaseMusicUnlock
URL-REGEX,http://music.163.com/eapi/song/enhance/download/url,NeteaseMusicUnlock
URL-REGEX,http://music.163.com/eapi/batch,NeteaseMusicUnlock
URL-REGEX,http://music.163.com/eapi/v1/search/get,NeteaseMusicUnlock
URL-REGEX,http://music.163.com/eapi/cloudsearch/pc,NeteaseMusicUnlock
URL-REGEX,http://music.163.com/eapi/v1/playlist/manipulate/tracks,NeteaseMusicUnlock
URL-REGEX,http://music.163.com/eapi/song/like,NeteaseMusicUnlock
URL-REGEX,http://music.163.com/eapi/v1/play/record,NeteaseMusicUnlock
URL-REGEX,http://music.163.com/eapi/playlist/v4/detail,NeteaseMusicUnlock
URL-REGEX,http://music.163.com/package,NeteaseMusicUnlock
```

**Comment by nondanee** [comment]
应该不是限速，可能没因为没有 CDN 加速
不能播网易云的源，找能播的位置，把 p1.music.126.net 的 IP ping 出来，改 hosts；不能播 QQ 的同理，如果 IP 不可达，那没救了，换区开 VPS 吧

如果觉得是 VPS 网速的问题，你应该先在局域网搭代理测试 iOS 上不同版本啊，何必为难自己
代理内部不区分是哪个平台的客户端，匹配逻辑是一模一样的
如果是 iOS 版的有完成加载时限，局域网内代理总够快了吧？

**Comment by onewayticket255** [comment]
[推测原因](https://www.zhihu.com/question/53215675/answer/138938558)
新版本可能开启App Transport Security，所以http://music.163.com/package 会被client closed
旧版本没有，所以http://music.163.com/package正常。

**Comment by nondanee** [comment]
@onewayticket255 
嗯？你用 #65 解决了？
那问题应该就是：
http://music.163.com/package 这个链接被客户端擅自升到 https
然而 music.163.com 的 https 连接会被我全局 block （因为区分不出来）
所以需要一个额外的 https endpoint
这个问题我写 README 里了，一直因为这个问题吗==
但是你截图里的 log 都是连到 http 的啊！

**Comment by onewayticket255** [comment]
解决了

对一直就是这个问题，我就奇怪为什么新版 http://music.163.com/package 后面跟随着一连串的music.163.com 的 https 连接 ，而旧版全是 http://music.163.com/package。

README写的很简要，我没弄清楚每一步原理。（我水平不够，前几次看都没理解为什么这么做，现在才知道背后的原因。。。）

然后[配合 Surge 或 Clash 食用](https://github.com/nondanee/UnblockNeteaseMusic/issues/56)，这里面大部分失败的情况都应该是没配置https endpoint（和我一开始情况一样），建议取消pin （我一开始以为那里面问题是其他什么原因引起的，有些误导作用），pin下[iOS 食用指南](https://github.com/nondanee/UnblockNeteaseMusic/issues/65)和我这个

**Comment by nondanee** [comment]
@onewayticket255 
好的

因为你的 log 显示一直都是 http://music.163.com/package/ 开头不是 https 所以我一直不知道是这个问题；
还有 https 连接是 proxy server 主动 close 的，在 log 里是说 client closed 也很迷
不过现在解决了就好

我也不知道别人是怎么成功的，反正我是没有设备啦 😂

我去 #56 加个说明好了，那个 issue 还是 pin 着吧

**Comment by onewayticket255** [comment]
还有一个问题，为什么ios最新版播放网易源时不会强制升级https呢，qq源却会强制升级https呢。

无法播放qq源
![Snipaste_2019-05-07_22-41-51.png](https://i.loli.net/2019/05/07/5cd1996caff8e.png)

---

可以播放网易源
![Snipaste_2019-05-07_22-41-37.png](https://i.loli.net/2019/05/07/5cd1996d79532.png)

**Comment by nondanee** [comment]
@onewayticket255 
但是你这两个 log 都是 http 开头的啊我看不出来有升级==

**Comment by onewayticket255** [comment]
第一张图2,3,4个请求 貌似就是http://music.163.com/package 的https加密
旧版本里package请求下没有 music.163.com:443 这样的请求的

**Comment by otherbanana** [comment]
所以就播放不了周杰伦的青花瓷、等你下课是吗？ @onewayticket255

**Comment by onewayticket255** [comment]
> 所以就播放不了周杰伦的青花瓷、等你下课是吗？ @onewayticket255

现在还不知道什么原因，等作者有最新版iOS设备再测试吧。你可以用周杰伦《等你下课》（qq源）
周杰伦《告白气球》（网易源）测试。不过现在情况是iOS最新客户端只能自配endpoint 才能播放全部歌曲。

**Comment by otherbanana** [comment]
@onewayticket255 好的，十分感谢，再请教一下如何自配endpoint

**Comment by nondanee** [comment]
@onewayticket255 macOS 客户端的问题不是 endpoint，不要误导别人==

**Comment by iuzumakin** [comment]
话说，有人在Mac 上使用最新的网易云(730),有成功的嘛~

**Comment by nondanee** [comment]
@iuzumakin 
有啊
issue filter 里搜 730
https://github.com/nondanee/UnblockNeteaseMusic/issues?q=730

**Comment by yimshing** [comment]
同样ios最新版不能播放 歌曲名倒是变黑了 但是播放失败 那个转发音源也太复杂 什么your_domain 证书路径一头雾水

**Comment by 1047958328** [comment]
> 同样ios最新版不能播放 歌曲名倒是变黑了 但是播放失败 那个转发音源也太复杂 什么your_domain 证书路径一头雾水

大佬你怎么配制的。前两步不懂怎么操作，教我一下好么

**Comment by goxofy** [comment]
你们能播放周杰伦的等你下课吗？

**Comment by goxofy** [comment]
@nondanee @onewayticket255 
我用自签证书或者是endpoint的方式，都不能播放qq音源的音频，这是啥原因。。。log显示qq音源没有升级成https，还是http

![image](https://user-images.githubusercontent.com/1695416/59734967-24ab7480-9286-11e9-82c2-bc04ccb77aee.png)

这是用了自签证书之后的log

![image](https://user-images.githubusercontent.com/1695416/59734975-2ffea000-9286-11e9-951a-4363b44c6a32.png)

求教

**Comment by goxofy** [comment]
另外我用《告白气球》测试，貌似网易音源也没有升级啊，但是能正常播放。。很奇怪

![image](https://user-images.githubusercontent.com/1695416/59735098-badf9a80-9286-11e9-83b6-c6f7a638edd2.png)

**Comment by pianississimo** [comment]
用shadowrocket根据食用指南配置的conf文件，同一台手机wifi的时候能够正常试用，但是蜂窝网络没有办法正常使用有什么解决办法吗？
启动设置是这样的：
`node app.js -p 80:443 -f 103.126.92.132 -e https://music.163.com`
启动设置如果去掉f和e以及80端口的话，macOS端就上不去了。
