### ISSUE TITLE
2023年了，现在还可以用吗？我windows配置完，测试代理可用，但是无法添加播放音乐为什么？

### ISSUE THREAD

**Issue by bighammer-link** [nondanee/UnblockNeteaseMusic#835]

**Comment by Horizon-Ljc** [comment]
应该是网易云版本问题，我从2.10回滚到2.9.6后可以正常使用

**Comment by bighammer-link** [comment]
> 应该是网易云版本问题，我从2.10回滚到2.9.6后可以正常使用

谢谢 我去试试旧版本的网易云

**Comment by bighammer-link** [comment]
> 应该是网易云版本问题，我从2.10回滚到2.9.6后可以正常使用

谢谢，大佬，我用2.9.6版本后，确实可以用了，感谢

**Comment by bighammer-link** [comment]
> 应该是网易云版本问题，我从2.10回滚到2.9.6后可以正常使用

谢谢，大佬，我用2.9.6版本后，确实可以用了，感谢


> 应该是网易云版本问题，我从2.10回滚到2.9.6后可以正常使用

但是，我的网易云，重启了一下就显示，网络未连接，没有网络，不能用啊

**Comment by bighammer-link** [comment]
> > 应该是网易云版本问题，我从2.10回滚到2.9.6后可以正常使用
> 
> 谢谢，大佬，我用2.9.6版本后，确实可以用了，感谢
> 
> > 应该是网易云版本问题，我从2.10回滚到2.9.6后可以正常使用
> 
> 但是，我的网易云，重启了一下就显示，网络未连接，没有网络，不能用啊

好像是版本问题，我换到2.9.52就可以了

**Comment by bighammer-link** [comment]
> > > 应该是网易云版本问题，我从2.10回滚到2.9.6后可以正常使用
> > 
> > 
> > 谢谢，大佬，我用2.9.6版本后，确实可以用了，感谢
> > > 应该是网易云版本问题，我从2.10回滚到2.9.6后可以正常使用
> > 
> > 
> > 但是，我的网易云，重启了一下就显示，网络未连接，没有网络，不能用啊
> 
> 好像是版本问题，我换到2.9.52就可以了

运行快捷方式属性中在目标尾部添加 --ignore-certificate-errors    这个方法貌似也可以

**Comment by bighammer-link** [comment]
https://github.com/UnblockNeteaseMusic/server/issues/776

**Comment by Enlixk** [comment]
https://github.com/UnblockNeteaseMusic/server 用这个，并在网易云快捷方式添加--ignore-certificate-errors，最新版网易云2.10.6测试可用

**Comment by LiuDanK** [comment]
> https://github.com/UnblockNeteaseMusic/server 用这个，并在网易云快捷方式添加--ignore-certificate-errors，最新版网易云2.10.6测试可用

同样的版本，但是不能用，真的迷

**Comment by Muggles001** [comment]
实测2.10.10快捷方式 属性 目标 最后面加+空格+--ignore-certificate-errors，可连网可播放

**Comment by bigben0123** [comment]
实测最新版本2.10.11 快捷方式 属性 目标改为 
"x:\Program Files (x86)\Netease\CloudMusic\cloudmusic.exe" --ignore-certificate-errors
确定后，必须点击这个快捷方式启动，可连网可播放

重启后不能播放是因为没有从快捷方式启动，那个--ignore-certificate-errors参数没生效。

有时代理会异常，重启一下代理试试。

另外因为网易云点击关闭后，其实是最小化到任务栏。必须在任务栏右键关闭彻底退出。才能算重启。

**Comment by WowOnWall** [comment]
可能退出后软件没有正常关闭，可以试试在任务管理器结束他
