### ISSUE TITLE
本地node报TUNNEL - music.163.com:443

### ISSUE THREAD

**Issue by FateOfKing** [nondanee/UnblockNeteaseMusic#85]
昨天用的还好好的能听，今天早上本地mac跑就报错了，是不是有缓存。还是别的原因。
<img width="567" alt="image" src="https://user-images.githubusercontent.com/9433531/57346863-db461080-7182-11e9-9c2b-b4253944c221.png">

**Comment by nondanee** [comment]
报什么错？

**Comment by nondanee** [comment]
这个就是正常的 log，为啥你觉得是报错？

**Comment by FateOfKing** [comment]
好吧，我以为是报错，但是听不了是实际情况。

**Comment by nondanee** [comment]
@FateOfKing 客户端版本号？更新过？

**Comment by FateOfKing** [comment]
没有更新。mac网易云2.0.0(700)。列表加载不出来，歌也听不了。
我倒是把项目更新了一下
<img width="822" alt="image" src="https://user-images.githubusercontent.com/9433531/57351064-1d774e00-7193-11e9-957a-bae5defd130b.png">

**Comment by nondanee** [comment]
@FateOfKing 
https 肯定会走 tunnel 啊，比如图片资源什么的
不能降级就打开 https 监听，安装 CA 证书 #48 
原来的代理配置不用修改(我也不知道你在哪儿配的)。

**Comment by FateOfKing** [comment]
你说的 “port 后面带冒号加另一个端口 -p 8080:8081 开启 https 监听” 怎么改你app.js  还是我的这个
<img width="652" alt="image" src="https://user-images.githubusercontent.com/9433531/57352931-8235a700-7199-11e9-8793-4f6ac1cff7a5.png">

**Comment by nondanee** [comment]
@FateOfKing 
PAC 不用改

只要改启动命令 `node app -p 8080:8081` 就好了，另外证书要装好并手动信任

**Comment by FateOfKing** [comment]
可以了 多谢

**Comment by KiraYo4kage** [comment]
同mac，网易云版本730.
昨天还能听的，今天就不行了
![image](https://user-images.githubusercontent.com/20996606/57353771-27517f00-719c-11e9-92cf-5bc32944201c.png)
证书已装且永远信任。
![image](https://user-images.githubusercontent.com/20996606/57353801-3e906c80-719c-11e9-8494-c1f1117fbdc9.png)

**Comment by nondanee** [comment]
@KiraYo4kage 请更新

**Comment by KiraYo4kage** [comment]
> @KiraYo4kage 请更新

thanks

**Comment by WhiteArthurWings** [comment]
> @FateOfKing PAC 不用改
> 
> 只要改启动命令 `node app -p 8080:8081` 就好了，另外证书要装好并手动信任

可以了，非常感谢
