### ISSUE TITLE
Is this repo related to UnblockNeteaseMusic/server?

### ISSUE THREAD

**Issue by theandychung** [nondanee/UnblockNeteaseMusic#855]
This project seems very close to  [UnblockNeteaseMusic/server](https://github.com/UnblockNeteaseMusic/server), and I saw you are supporting it too.
Is the newer version now all in [UnblockNeteaseMusic/server](https://github.com/UnblockNeteaseMusic/server)?
Or this is a separated project?

Thanks.

**Comment by FrzMtrsprt** [comment]
[UnblockNeteaseMusic/server](https://github.com/UnblockNeteaseMusic/server) is a fork of this repo, maintained by other devs, providing enhancements and fixes.  
This repo is no longer maintained, but [UnblockNeteaseMusic/server](https://github.com/UnblockNeteaseMusic/server) is still being maintained (although they are ending support soon too).

**Comment by theandychung** [comment]
Got it. Thanks
