### ISSUE TITLE
用了一段时间后无法使用问题

### ISSUE THREAD

**Issue by libilin2018** [nondanee/UnblockNeteaseMusic#86]
跟我第一次反馈的情况差不多，一开始可以正常使用，我把服务挂在了windows-server上面，但几天后有出现用不了的情况了，请问作者怎么处理，谢谢
![01](https://user-images.githubusercontent.com/41327802/57351135-5a434500-7193-11e9-8538-47d65116c70a.png)
![02](https://user-images.githubusercontent.com/41327802/57351145-60392600-7193-11e9-91dd-fbdaf601170b.png)

**Comment by nondanee** [comment]
#62 
看到有新版本，先更新，再提 issue
