### ISSUE TITLE
music.httpdns.c.163.com 获取的IP不可用

### ISSUE THREAD

**Issue by JasonKhew96** [nondanee/UnblockNeteaseMusic#87]
目前给出的ip
```
103.65.41.125, 103.65.41.126
```
无法加载歌单（超时），自己的歌单可以加载

根据bin大佬的代码获取的IP，歌单直接加载出来了
Jixun的也没问题

**Comment by nondanee** [comment]
没懂，我没要求过要用 httpdns 取 IP 啊？
这个在部分 issue 里提过，你想说哪个 issue 的问题请 refer 一下

我这边 ping 到的 IP 就是 126，网页版访问正常没问题

**Comment by nondanee** [comment]
bin 大佬的代码又是什么啊==

**Comment by JasonKhew96** [comment]
dns获取ip的
![image](https://user-images.githubusercontent.com/29531167/57369787-1404da80-71c1-11e9-8a97-f141a22f0959.png)

我换个网就没问题了，我大学的网线不行......，不好意思，打扰了
我还用charles看了一下，就是没加载完...
