### ISSUE TITLE
评论不了

### ISSUE THREAD

**Issue by wendingp** [nondanee/UnblockNeteaseMusic#88]
可以看评论 但是不能评论？

**Comment by nondanee** [comment]
@wendingp 
你说无版权的歌吗？
https://github.com/bin456789/Unblock163MusicClient-Xposed/issues/190#issuecomment-485817857

**Comment by nondanee** [comment]
好像是有问题，我看看==

**Comment by wendingp** [comment]
我这好像是都评论不了。。。难道没人发现orz？

**Comment by nondanee** [comment]
@wendingp 
还真没人发现，这个问题应该 2 月就有了==
https://github.com/nondanee/UnblockNeteaseMusic/commit/cffa03f8eea22816623ae6fc5d531b281e97880a#diff-35ca339294c52b6cc99f4d45317666c3R136

**Comment by nondanee** [comment]
@wendingp 
修好了，麻烦更新下，感谢反馈
