### ISSUE TITLE
建议考虑支持将变灰歌曲收藏到歌单的功能

### ISSUE THREAD

**Issue by datou1996** [nondanee/UnblockNeteaseMusic#9]
希望未来可以支持，收藏变灰歌曲这个功能还是比较有用的

**Comment by nondanee** [comment]
很抱歉这个无法实现，是网易云服务器不允许
```
{ msg: '下架歌曲无法收藏', code: 401 }
```

**Comment by steven7851** [comment]
https://github.com/bin456789/Unblock163MusicClient-Xposed 可以实现，不知道怎么做到的，可能安卓api可以?

**Comment by nondanee** [comment]
@steven7851 
我试了weapi也会报401
```
{"trackIds":"[561307346]","code":401,"count":5,"cloudCount":0}
```
之前试的eapi也是401，安卓就是走eapi

@bin456789 
xposed模块确实可以收藏下架的歌曲
不过我看xposed模块里这些操作都[在后端实现](https://github.com/bin456789/Unblock163MusicClient-Xposed/blob/master/app/src/main/java/bin/xposed/Unblock163MusicClient/Handler.java#L120)
大佬能不能透露一下是怎么做到的🙏🙏🙏

**Comment by JasonKhew96** [comment]
[自建服务器吧](https://github.com/bin456789/Unblock163MusicClient-Xposed/blob/master/app/src/main/java/bin/xposed/Unblock163MusicClient/Handler.java#L30)

**Comment by nondanee** [comment]
@JasonKhew96 
是啊，所以希望 @bin456789 大佬能透露一下后端实现嘛😂

**Comment by bin456789** [comment]
收藏到歌单
url = "http://music.163.com/api/playlist/manipulate/tracks"
data = {
                'trackIds': '[%s,%s]' % (trackId, trackId),
                'pid': playlistId,
                'op': op
            }
post请求，cookie可能要添加{'os': 'pc'}


红心收藏
http://music.163.com/api/v1/user/info 得到uid
http://music.163.com/api/user/playlist?uid=%s&limit=1000&offset=0 得到"我喜欢的音乐"列表的playlistId
再次用上面的api就可以了

**Comment by nondanee** [comment]
@bin456789 
多谢指导，请问下是这样吗
![image](https://user-images.githubusercontent.com/26399680/45148623-4907fa00-b1fa-11e8-95df-c5580add95b2.png)
这样还是401~

**Comment by bin456789** [comment]
大概MUSIC_U和pid对不上，歌曲只能添加到自己创建的歌单

**Comment by nondanee** [comment]
@bin456789 我傻了，多谢😂

**Comment by nondanee** [comment]
@datou1996 已支持

**Comment by nondanee** [comment]
@bin456789感觉是网易云API的BUG，重复填两个trackId用weapi也可以成功添加到歌单😂

**Comment by datou1996** [comment]
@nondanee 感谢
