### ISSUE TITLE
路由配置了hosts，ios手机连接路由器 无法播放

### ISSUE THREAD

**Issue by Mathisdifficult** [nondanee/UnblockNeteaseMusic#90]
ios只能开vpn食用吗？我电脑连路由器是可以播放的。

**Comment by nondanee** [comment]
移动端仅仅改 hosts 是没用的，存在 IP 直连（不看 hosts 不看 dns），需要用路由器屏蔽
iOS 使用指南，请去 #65 #82 #90 讨论
