### ISSUE TITLE
源码中链接和名字的输出在哪个类的哪一句话

### ISSUE THREAD

**Issue by FateOfKing** [nondanee/UnblockNeteaseMusic#92]
如图
<img width="476" alt="image" src="https://user-images.githubusercontent.com/9433531/57785177-c873a300-7763-11e9-9583-d25c2af013f3.png">
我想在那写个下载方法，每次播放的时候自动下载到本地。麻烦指点一二

**Comment by nondanee** [comment]
https://github.com/nondanee/UnblockNeteaseMusic/blob/580344092fc4947a11c1d5e618c937d853b9d73c/provider/match.js#L31
注：直接下载链接一般来说没有 ID3 tag
