### ISSUE TITLE
mac本地跑node是不是不稳定

### ISSUE THREAD

**Issue by FateOfKing** [nondanee/UnblockNeteaseMusic#93]
昨天还好的，今天拉了下代码，就不行了。链接倒是有了，但是失效了

<img width="492" alt="image" src="https://user-images.githubusercontent.com/9433531/57842588-708a7a00-77ff-11e9-9b80-2ebd949f42a3.png">

**Comment by nondanee** [comment]
以后拉了下代码就不行这种反馈学会自己先查原因
1. 看 commit 的 message 和 dif
2. git reset

链接复制到浏览器可以打开吗？看一眼 network 是不是 200？
因为没有 content-type 所以浏览器可能不会显示播放器

**Comment by nondanee** [comment]
跑 node 稳定啊，作为一个 proxy server 它是稳定的
音源有变动很正常，不然我就没必要维护了

**Comment by FateOfKing** [comment]
好的 多谢
