### ISSUE TITLE
代理正常，播放显示加载失败

### ISSUE THREAD

**Issue by small2star** [nondanee/UnblockNeteaseMusic#94]
![QQ截图20190517050129](https://user-images.githubusercontent.com/21169546/57886997-04d8f900-7861-11e9-9dac-fe13137a39b3.png)
林俊杰的一些版权歌曲播放显示加载失败

**Comment by nondanee** [comment]
是的没匹配到

**Comment by nondanee** [comment]
你可以试试其它的源，我看了下 joox 可以匹配到，migu 能匹配到但好像不是一首歌

**Comment by small2star** [comment]
> 你可以试试其它的源，我看了下joox可以匹配到，migu能匹配到但好像不是一首歌

好的 ，多谢
