### ISSUE TITLE
在 iOS 端的歌手热门单曲列表呈灰色

### ISSUE THREAD

**Issue by nondanee** [nondanee/UnblockNeteaseMusic#96]
我发现一个BUG,在IOS端的歌手的所有歌曲列表是灰色的，但是在专辑列表里是能播放的。
![微信图片_20190517114006](https://user-images.githubusercontent.com/20596060/57902069-2acebf80-789a-11e9-8da0-8097e6d4cb7b.png)
![微信图片_20190517115109](https://user-images.githubusercontent.com/20596060/57902070-2b675600-789a-11e9-84c9-6e7b2ab8af7a.png)

_Originally posted by @Anopia in https://github.com/nondanee/UnblockNeteaseMusic/issues/65#issuecomment-493309851_

**Comment by otherbanana** [comment]
大佬，你在ios用的小火箭吗？

**Comment by nondanee** [comment]
@otherbanana 
这个 reference #65 里的一个 BUG，别人提的 (我连 iOS 都没有)

**Comment by Anopia** [comment]
@otherbanana 我在使用小火箭。怎么了？

**Comment by abae136ab** [comment]
> @otherbanana
> 这个 reference #65 里的一个 BUG，别人提的 (我连 iOS 都没有)

好像这个BUG还是存在。。。

**Comment by otherbanana** [comment]
你说的是哪个BUG？

**Comment by otherbanana** [comment]
@abae136ab

**Comment by abae136ab** [comment]
> 你说的是哪个BUG？

检索歌曲灰色，专辑里可以听
