### ISSUE TITLE
求iptables脚本

### ISSUE THREAD

**Issue by Flysky12138** [nondanee/UnblockNeteaseMusic#97]
谁会写这个，写个只代理网易云音乐的脚本。我用PAC其他软件很多加载不了

**Comment by nondanee** [comment]
那用全局呢？

**Comment by Flysky12138** [comment]
@nondanee 一样😂

**Comment by nondanee** [comment]
什么设备啊？

**Comment by Flysky12138** [comment]
安卓

**Comment by nondanee** [comment]
是不是华为？#40

**Comment by Flysky12138** [comment]
小米。对了，wifi下我用pac用不了，ip加端口那样才行。启动我加了-s参数

**Comment by nondanee** [comment]
好的，懂了
不加 -s 时用 PAC 应该没问题的吧？
是 BUG

**Comment by nondanee** [comment]
不对，PAC 下是其他 APP 用不了还是网易云解锁无效？
加了 -s 的话 ip + 端口号，其他 APP 肯定用不了

**Comment by Flysky12138** [comment]
加-s。IP端口这样网易音乐能用，其他不能用。PAC就相反

**Comment by Flysky12138** [comment]
电脑pac能用，手机wifi不行

**Comment by nondanee** [comment]
@Flysky12138
> 我用PAC其他软件很多加载不了
 那你最开始的这个描述是错的咯

因为发现 PAC 下网易云无效，然后你用 ip + 端口，然后发现其它软件不能加载？
省略了中间一步？

其它相反是指网易云解锁无效，而不是网易云不能联网吧？

**Comment by Flysky12138** [comment]
对

**Comment by nondanee** [comment]
以后反馈 BUG 请描述清楚
是 BUG，马上修

**Comment by Flysky12138** [comment]
o jb k

**Comment by nondanee** [comment]
白名单确实有问题

但是我问了你说 PAC 下网易云可以联网但是不能解锁
那么这个 BUG 修了可能也还是不行

建议你装证书，开启 https MITM，这样可以保证能拦截到

**Comment by Flysky12138** [comment]
我试试

**Comment by nondanee** [comment]
好的，你先试试吧，我确认过这次白名单没问题了

还是不行就把证书装上

**Comment by Flysky12138** [comment]
用最新版0.14.2。在安卓上的wifi连接下用pac没问题了。

**Comment by nondanee** [comment]
是刚 pull 的吗？我还没 release

**Comment by Flysky12138** [comment]
就是release那里下载的0.14.2

**Comment by nondanee** [comment]
啊？最新的 release 还是有白名单问题的
你没问题了？那你之前用的是什么版本啊

**Comment by Flysky12138** [comment]
额。。。之前用的0.14.1

**Comment by nondanee** [comment]
云音乐 6.2？

**Comment by Flysky12138** [comment]
嗯

**Comment by Flysky12138** [comment]
额，重启软件又不行了，看来还所有问题

**Comment by nondanee** [comment]
6.2 多了加了一个 host，0.14.2 release 说明里第一条那个问题

**Comment by nondanee** [comment]
你用最新的 master 版本先试一下吧
https://codeload.github.com/nondanee/UnblockNeteaseMusic/zip/master

**Comment by Flysky12138** [comment]
行，试试，我是弄在服务器上的。

**Comment by Flysky12138** [comment]
不行，歌还是灰色的，播放提示资源不存在

**Comment by Flysky12138** [comment]
电脑上同样用PAC代理但是电脑就能用，手机就不行

**Comment by nondanee** [comment]
是的，移动端不一样的

你装一下 ca 证书吧
然后启动命令换成 node app.js -p <port1>:<port2>

**Comment by Flysky12138** [comment]
o jb k

**Comment by Flysky12138** [comment]
那个，我用宝塔面板弄个网站，文件放在里面，这个网站也安装了ssl，启动用的
nohup node app.js -e https://域名 &
之后使用安卓上使用pac一样的情况，操作还有哪里不对的

**Comment by nondanee** [comment]
你理解错了
重点不在你的代理是 http 代理还是 https 代理，PAC 是 http:// 开头还是 https:// 都无所谓
所以你用宝塔开 ssl 网站没有用

要在安卓上装 CA 证书
https://raw.githubusercontent.com/nondanee/UnblockNeteaseMusic/master/ca.crt
点开链接，在手机上装好

启动用 nohup node app.js -p 8080:8081 &

这个 8081 的 https 端口是用来内部转发隧道里的流量的

PAC 上依旧用 http://

**Comment by Flysky12138** [comment]
哦

**Comment by Flysky12138** [comment]
哎，同样不行啊

**Comment by nondanee** [comment]
用这个 PAC 试一下
http://149.129.122.247:8080/proxy.pac

**Comment by Flysky12138** [comment]
一样用不了

**Comment by nondanee** [comment]
我找了一台小米设备试过了，没问题
MIUI 10.0.1.0
网易云 6.2.0.005504

再确认一下，你有没有在手机上装证书啊？

**Comment by Flysky12138** [comment]
我的版本是v6.2.0.926741,wifi，vpn两种情况的证书都安装了

**Comment by nondanee** [comment]
那没办法了
要不你在局域网中不加 -s 运行看看是哪些请求不在 PAC 规则里

**Comment by Flysky12138** [comment]
我用ProxyDriod单独代理网易云音乐了

**Comment by Flysky12138** [comment]
我用ProxyDriod单独代理网易云音乐了
