### ISSUE TITLE
macos 下载失败

### ISSUE THREAD

**Issue by sunzongzheng** [nondanee/UnblockNeteaseMusic#98]
![image](https://user-images.githubusercontent.com/12635613/58069246-0ab73d00-7bc7-11e9-9be1-5f82bf7a0d25.png)
试听正常
log里的音乐url正常
![image](https://user-images.githubusercontent.com/12635613/58069288-363a2780-7bc7-11e9-8c55-1d21da4315d6.png)
表现是 点击下载后正常开始下载并显示进度，下载100%后又会重试几次，最后提示下载失败

网易云版本730

**Comment by nondanee** [comment]
测了下，应该是 2.0 以上开始查 MD5，因为 MD5 对不上导致下载失败
跟安卓上的已知问题一样 https://github.com/nondanee/UnblockNeteaseMusic/issues/30#issuecomment-475724232

已经打了 helped wanted 的标签

现在代码里 MD5 实现是这样的
https://github.com/nondanee/UnblockNeteaseMusic/blob/ffb826a84abe6fe7c4e626560fd43813b5b832a4/provider/match.js#L41-L45
如果 response headers 里面没有真实的话，只能填充一个假的 MD5 进去
