### ISSUE TITLE
请问在群辉NAS上如何部署？

### ISSUE THREAD

**Issue by zpwork** [nondanee/UnblockNeteaseMusic#99]
在群晖NAS上无论执行node app.js还是在Docker上安装都会卡住。小白一个，有大佬可以指点一下吗？

**Comment by nondanee** [comment]
什么叫卡住啊😂
就是不显示 server run @0.0.0.0 之类的吗？

**Comment by zpwork** [comment]
> 什么叫卡住啊😂
> 就是不显示 server run @0.0.0.0 之类的吗？

会显示server run @0.0.0.0，然后就卡住了，按照ios食用教程的方法连接了，但是似乎无效。

**Comment by nondanee** [comment]
哦那不是卡住 😂
因为没有流量进来，所以没有新的 log

配置先用这个试一下
https://github.com/nondanee/UnblockNeteaseMusic/issues/65#issuecomment-493718439

**Comment by zpwork** [comment]
用node可以了，谢谢大神。

> 哦那不是卡住 😂
> 因为没有流量进来，所以没有新的 log
> 
> 配置先用这个试一下
> [#65 (comment)](https://github.com/nondanee/UnblockNeteaseMusic/issues/65#issuecomment-493718439)

谢大神，在node上运行成功了

**Comment by nondanee** [comment]
试试 docker 吧

**Comment by Rasielco** [comment]
在群晖的docker上面部署的，需要什么特别的步骤么？还是一路往下点就行？
出现了这个：
MITM > music.163.com | stdout
HTTP Server running @ http://0.0.0.0:8080
然后端口也设置完了，就是不成功...

**Comment by nondanee** [comment]
@Rasielco 
没有特别的步骤
不知道一路有什么==
